### ISSUE TITLE
Use the Dockerfile rel path against Copilot dir instead of pwd 

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#1030]
Now we default the Dockerfile path to be `./Dockerfile`. As expected `.` should be the path for Copilot dir instead of `pwd`. However, if I have an app like this:

- Copilot/
  - mySvc/
     - manifest.yml
- Dockerfile
- mySvc/
- fluentbit/
   - Dockerfile

Then if I run `svc deploy` in `fluentbit/`, then Copilot will pick up the Dockerfile for fluentbit instead of the Dockerfile in the root dir, which can be considered as a bug.

**Comment by efekarakus** [comment]
Related https://github.com/aws/copilot-cli/pull/1059

**Comment by bvtujo** [comment]
Just to clarify, do you suggest that the path specified in the manifest for the top-level Dockerfile in your example should be `../Dockerfile` and the fluentbit Dockerfile should be `../fluentbit/Dockerfile`?

**Comment by iamhopaul123** [comment]
ah no since the fluentbit dockerfile is just a sidecar. So far we don't do the upload for their sidecar image automatically. It's just i would expect `svc deploy` should always pick up the same dockerfile no matter which level i am at in my application folder.
