### ISSUE TITLE
Not deleting local files `flag` design

### ISSUE THREAD

**Issue by seongm-1** [aws/copilot-cli#1031]
## Overview
Related #800. The CLI current behavior is that it deletes the local files it generates. We want to change this default behavior but still possibly provide the option to delete the files if the user wants. 

### Default Behavior
We will change the default behavior to not delete the local files generated by the CLI when the user runs either `svc delete` or `pipeline delete`

If we want to still provide the option to delete the generated local files then we can propose a flag option such as `svc delete --files` to provide the current behavior.   

If we do not provide this option, then the user can simply delete the folder.

**Comment by efekarakus** [comment]
Released with #1034
