### ISSUE TITLE
Add integ tests for cfn template

### ISSUE THREAD

**Issue by huanjani** [aws/copilot-cli#1032]
We should make sure CFN templates are being rendered as they should be, including the new TestCommands field of deploy.PipelineStage.

Ex: Add test commands here: https://github.com/aws/amazon-ecs-cli-v2/blob/master/internal/pkg/deploy/cloudformation/pipeline_integration_test.go#L193

**Comment by efekarakus** [comment]
We have now integration tests under `stack/gh_pipeline_integration_test.go` or `stack/cc_pipeline_integration_test.go` resolving :)
