### ISSUE TITLE
add test_command actions to `pipeline status` output 

### ISSUE THREAD

**Issue by huanjani** [aws/copilot-cli#1045]
Currently, `pipeline status` human output looks like this:
```
Pipeline Status

  Stage             Status              Transition          
  -----             ------              ----------
  Source            Succeeded           ENABLED
  Build             Succeeded           ENABLED
  DeployTo-test     Succeeded           ENABLED
  DeployTo-prod     Succeeded           ENABLED

Last Deployment

  Updated At    2 hours ago
```

We'd like to add the new TestCommands action to this output so users can see if the stage failed in the test action. My recommendation is for Option 1, below, because it is much easier to read. Option 2 may be useful if more actions will be added in the near future.

Option 1:
```
Pipeline Status

  Stage             Status              Transition          
  -----             ------              ----------
  Source            Succeeded           ENABLED
  Build             Succeeded           ENABLED
  DeployTo-test     Succeeded           ENABLED
    TestCommands    Succeeded
  DeployTo-prod     Succeeded           ENABLED
    TestCommands    Succeeded

Last Deployment

  Updated At    2 hours ago
```

Option 2:
```
Pipeline Status

Stage: Source
  Status              Transition          
   ------              ----------
  Succeeded           ENABLED

Stage: Build  
  Status              Transition          
  ------              ----------
  Succeeded           ENABLED

Stage: DeployTo-test
  Status              Transition          
  ------              ----------
  Succeeded           ENABLED

  Action                      Status       
  ------                      ------
  CreateOrUpdate-svc-test     Succeeded
  TestCommands                Succeeded

Stage: DeployTo-prod
  Status              Transition          
  ------              ----------
  Succeeded           ENABLED

  Action                      Status         
  ------                      ------
  CreateOrUpdate-svc-prod     Succeeded
  TestCommands                Succeeded

Last Deployment

  Updated At    2 hours ago
```

(The JSON output includes TestCommands):
```
{"pipelineName":"pipeline-sample-huanjani-ecs-demo-php-simple-app","stageStates":[{"stageName":"Source","actions":[{"name":"SourceCodeFor-sample","status":"Succeeded"}],"transition":"ENABLED"},{"stageName":"Build","actions":[{"name":"Build","status":"Succeeded"}],"transition":"ENABLED"},{"stageName":"DeployTo-test","actions":[{"name":"CreateOrUpdate-svc1-test","status":"Succeeded"},{"name":"TestCommands","status":"Succeeded"}],"transition":"ENABLED"},{"stageName":"DeployTo-prod","actions":[{"name":"CreateOrUpdate-svc1-prod","status":"Succeeded"}],"transition":"ENABLED"}],"updatedAt":"2020-06-22T16:50:34Z"}
```

**Comment by efekarakus** [comment]
Oooh I really like Option1, would you display all the actions in a stage? or just the testcommands action?

One thing that might be neat is displaying the actions under a stage like a tree (https://github.com/ahmetb/kubectl-tree)

**Comment by huanjani** [comment]
> Oooh I really like Option1, would you display all the actions in a stage? or just the testcommands action?

I asked the same thing, and was told do just the testcommands action. I think that makes sense for now, but adding in the other actions wouldn't be a big leap from this. All of the actions _are_ in the json output, for what it's worth.

> One thing that might be neat is displaying the actions under a stage like a tree (https://github.com/ahmetb/kubectl-tree)

That _would_ be really cool.

**Comment by huanjani** [comment]
> > Oooh I really like Option1, would you display all the actions in a stage? or just the testcommands action?
> 
> I asked the same thing, and was told do just the testcommands action. I think that makes sense for now, but adding in the other actions wouldn't be a big leap from this. All of the actions _are_ in the json output, for what it's worth.

Update: I refactored to include all actions.
> 
> > One thing that might be neat is displaying the actions under a stage like a tree (https://github.com/ahmetb/kubectl-tree)
> 
I will do this separately. Will open an Issue for it.
