### ISSUE TITLE
Default branch in repository should be named mainline, not master. 

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#1049]
We have decided to rename the default branch for this repository from `master` to `mainline` in order to use more inclusive language. Once this change is made, all PRs will be automatically cut against the new mainline branch. 

A checklist of necessary prerequisites follows:
- [x] Create `mainline` branch on Github. 
- [x] Create new branch protection rule targeting `mainline` mimicking current `master` branch protection
- [x] Ensure that CI will run on all pull requests regardless of branch. 
- [x] Update CD pipeline to source from `mainline`, not `master`.
- [ ] Delete obsolete `master` branch from remote after a short transition period.

**Comment by devoredevelops** [comment]
How about just `main`?

**Comment by efekarakus** [comment]
This is done!
