### ISSUE TITLE
Copilot env command doesn't inspect environment variables

### ISSUE THREAD

**Issue by codypenta** [aws/copilot-cli#1068]
For AWS Control Tower accounts where access is governed by temporary credentials:

``` bash
export AWS_ACCESS_KEY_ID="<redacted>"
export AWS_SECRET_ACCESS_KEY="<redacted>"
export AWS_SESSION_TOKEN="<redacted>"
```

The command copilot init works fine

```bash
copilot init
```

But once you try to provision infrastructure with `copilot env init`, the CLI wants credentials from .aws/ and not the environment variables mentioned above, causing the command to fail.

This can be easily fixed on the user end by manually writing temp creds to ~/.aws/credentials.

**Comment by jasonumiker** [comment]
Seconded. I get those environment variables by AWS SSO and had to write this script to echo them out to the .aws/config file to get things to work as a workaround:
echo "[default]" > ~/.aws/config
echo "region = ap-southeast-2" >> ~/.aws/config
echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/config
echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
echo "aws_session_token = $AWS_SESSION_TOKEN" >> ~/.aws/config

**Comment by kohidave** [comment]
Just as a nicer alternative to the current work around you can also use a credential process in your profile:


https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

This will essentially run whatever script your using to generate your credentials as part of your profile.

**Comment by efekarakus** [comment]
Heya! We just put up this design proposal to support this feature: https://github.com/aws/copilot-cli/issues/1228, we'll start working on this in this sprint. So if you have any feedback, please let us know in the comments :)
