### ISSUE TITLE
Parsing HEALTHCHECK CMD bug

### ISSUE THREAD

**Issue by seongm-1** [aws/copilot-cli#1079]
Current behavior:
When parsing a user's Dockerfile for HEALTHCHECK, this is the format it is parsed in the `manifest.yml`. This returned an error because it returned as a single string.
![image](https://user-images.githubusercontent.com/51001622/86300159-e940c700-bbb6-11ea-8e62-d6ab9c775011.png)

Wanted behavior:
`command: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]`

**Comment by kohidave** [comment]
Hiya @seongm-1 ! Looks like this is merged in. Can we resolve this ^^
