### ISSUE TITLE
Accept arg values of in addition to --name flag

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#1099]
Many of our commands have a `--name` flag. This is used to filter down to a particular service, application or pipeline. The `--name` flag is useful, but we've observed that many people often attempt to put the name as an arg value.

```sh
copilot svc logs my-service
```

We should update our styleguide and our implementation to accept the name through the `--name` flag or an argument value, as well. 

If a customer provides both, we can ignore both and devolve into them having to select one.

**Comment by efekarakus** [comment]
We most likely won't get to this. Resolving this issue.
