### ISSUE TITLE
Unexpected profile usage when profiles not fully defined

### ISSUE THREAD

**Issue by mikesir87** [aws/copilot-cli#1104]
I accidentally used a profile in which I had credentials in `~/.aws/credentials`, but no config in `~/.aws/config` (my region was set as an env var). When I first did a deploy, things got funky... some of the infra fell back to the default profile (in my case, a different account). Then, when I tried to delete the app, things just hung for quite a while. Once I realized what was going on, I fixed my config file and the delete happened instantly. But, took some cleaning up between the accounts to get things back to a clean state.

One thing that also helped me was that one of the commands gave me a "profile chooser" (can't remember which one) and the profile I was trying to use wasn't listed.

So... I'm not sure what the right answer/fix is here. But, maybe I'd expect some sort of warning/failure if the profile being used from the `AWS_PROFILE` env var isn't a valid choice/isn't configured completely.

## Screenshots

Notice the two different accounts being used...

<img width="1264" alt="Screen Shot 2020-07-09 at 3 13 00 PM" src="https://user-images.githubusercontent.com/746837/87082757-7c05e500-c1f9-11ea-82c8-58fb6a906640.png">

Delete hanging for several minutes. Eventually just Ctrl+c'ed it and ran it again after fixing my config.

<img width="620" alt="Screen Shot 2020-07-09 at 3 30 59 PM" src="https://user-images.githubusercontent.com/746837/87082782-83c58980-c1f9-11ea-9647-ec3fd0f7ba3a.png">

**Comment by kohidave** [comment]
That makes total sense - thanks for the thoughtful debugging. 

I think there are some things we can do to help clear up how we interact with the credential provider. 

We'll brainstorm some UX on how we can improve this but maybe before the first deployment we can mention which region/account we're going to deploy the test environment to. 

We show a profile selector when you delete an app, or when you create an env through `env init`. 

Thanks again for your patience :pray:

**Comment by mikesir87** [comment]
No problemo! It's a new tool, so figured there'd be some bumps in the road. Definitely happy with the direction this is going though!

**Comment by efekarakus** [comment]
Heya! We just put up this design proposal to support this feature: https://github.com/aws/copilot-cli/issues/1228, we'll start working on this in this sprint. So if you have any feedback, please let us know in the comments :)

**Comment by efekarakus** [comment]
We released [v0.3.0](https://github.com/aws/copilot-cli/releases/tag/v0.3.0) which uses your default credential provider chain while using `copilot init`, or we will prompt for your credentials if you use `copilot env init`.
We've also added documentation here on our rational behind credentials with Copilot: https://github.com/aws/copilot-cli/wiki/Credentials
