### ISSUE TITLE
Unexpected account on app infra permissions

### ISSUE THREAD

**Issue by mikesir87** [aws/copilot-cli#1105]
When using a custom profile (set through `AWS_PROFILE`) to init a new service, I saw it uses a CF stack to create a few resources, including a S3 bucket for build pipeline artifacts. When looking at the policy for the S3 bucket, the KMS key, and the ECR repo, I noticed all are granted access to both the correct/intended account, but also to my default profile (which I was not expecting). I would expect this policy to _only_ contain my specified account, not the additional account.

## Screenshot

Screenshot from the S3 bucket policy

<img width="773" alt="Screen Shot 2020-07-09 at 3 53 26 PM" src="https://user-images.githubusercontent.com/746837/87084685-a3aa7c80-c1fc-11ea-88ab-198960355513.png">

**Comment by mikesir87** [comment]
The same thing is also occurring on the KMS key created by that stack set.

**Comment by efekarakus** [comment]
heya @mikesir87 ! The fix for this was released in [v0.3.0](https://github.com/aws/copilot-cli/releases/tag/v0.3.0) which now leverages temporary credentials while running `copilot init` so this bug shouldn't happen.
