### ISSUE TITLE
Request for correction of errors in the `copilot env init` documentation

### ISSUE THREAD

**Issue by tasogare0919** [aws/copilot-cli#1111]
I found what I believe to be an error in the wiki description.

In the `copilot env init` document below, it says `ecs-preview env init` when it should say `copilot env init`.

>What does it do?
> ecs-preview env init creates a new environment where your services will live.

https://github.com/aws/copilot-cli/wiki/env-init-command

I think this is a mistake and I would appreciate your help in correcting the description in the documentation.

**Comment by efekarakus** [comment]
@tasogare0919 thank you so much for bringing the typo to our attention! We fixed it now ☺️
