### ISSUE TITLE
Rationale for not using private subnets?

### ISSUE THREAD

**Issue by carlosafonso** [aws/copilot-cli#1113]
Hi,

Thank you for your work on Copilot, this looks like a great tool. I was wondering what's the rationale for not using private subnets? From reading the docs it seems that even backend services are deployed on the public subnets. What's the reason behind this decision? Is it to avoid the cost of using a NAT Gateway (or the need for a NAT instance for that matter)?

Just curious.

Thanks!

**Comment by kohidave** [comment]
That’s exactly right - to avoid using NAT Gateways. We have some designs around being able to force the service into a private subnet but haven’t finalized it yet.

**Comment by efekarakus** [comment]
I'll close the issue for now, but please let us know if you have a usecase where you'd want the service deployed to private subnets. We'd love to learn more to build the right experience!
