### ISSUE TITLE
Service Type Extensibility

### ISSUE THREAD

**Issue by jritsema** [aws/copilot-cli#1116]
Congrats on the release!

What is the thinking around extending the supported service types?  Are the current 2 (web and backend) hard coded?  Is there a way to customize the cloud formation for these or add new ones?

Thanks!

**Comment by efekarakus** [comment]
Hi @jritsema

Thank you! Are there any particular service types that you are looking for that's not supported at the moment?

We currently have a way of adding more resources to your service stacks through "addons" (https://github.com/aws/copilot-cli/wiki/Additional-AWS-Resources). So for example, if you'd like to add additional permissions to your task or add a database, like DynamoDB, it can be done through that feature.

We have also roadmap item to be able to tap into the TaskDefinition parameters: https://github.com/aws/copilot-cli/issues/948 that's in the design phase.

Long term, we're trying hard to make Copilot provider independent (manifest, CloudFormation, CDK, Terraform) so we'd like to get to a point where you can define your service with any of these providers.

**Comment by jritsema** [comment]
> Long term, we're trying hard to make Copilot provider independent (manifest, CloudFormation, CDK, Terraform) so we'd like to get to a point where you can define your service with any of these providers.

**Comment by jritsema** [comment]
Some scenarios I had in mind are non-public or firewalled services (launching containers and ALBs in private subnets connected to direct connects) and scheduled tasks.  In general, allowing control over the infrastructure as code would be useful as there are typically settings that need to be tweaked.

> Long term, we're trying hard to make Copilot provider independent (manifest, CloudFormation, CDK, Terraform) so we'd like to get to a point where you can define your service with any of these providers.

That sounds great!
