### ISSUE TITLE
Environment Variable and Secret for Sidecar container

### ISSUE THREAD

**Issue by FarmaanElahi** [aws/copilot-cli#1119]
Currently adding env variable  and secrets for the works for the main container.

There might be some scenario where env variable and secrets for sidecar might be required which is currently missing

**Comment by iamhopaul123** [comment]
Hello @FarmaanElahi,

This is a very useful feedback! I think we should support injecting env variables and secrets for sidecar. Thanks for bringing it up!

**Comment by rothgar** [comment]
Could this also be used for adding args to the sidecar? environment variables would probably be enough to write my own docker-entrypoint.sh and wrap the command but it would be nice to get native support.

I could also open a new issue for arg/cmd support if that makes sense.

**Comment by bdevore17** [comment]
@iamhopaul123 any timeline for this?

**Comment by bdevore17** [comment]
@iamhopaul123 Appreciate this being prioritized! A few unsolicited thoughts:
- both explicit and implicit sidecars (like firelens) should be supported
- this feature is only truly useful if we can parameterize the values based on copilot environment

**Comment by iamhopaul123** [comment]
Hello @bdevore17, so sorry for the late reply. We probably won't be able to do this feature very soon but I'll try to get to it as soon as possible and keep you posted!

> this feature is only truly useful if we can parameterize the values based on copilot environment

Really appreciate this input. It is very helpful to us!

**Comment by efekarakus** [comment]
This feature was released just now in v1.1.0: https://github.com/aws/copilot-cli/releases/tag/v1.1.0
