### ISSUE TITLE
Set CIDR values

### ISSUE THREAD

**Issue by chrissamcat** [aws/copilot-cli#1125]
Is it possible to explicitly set the values for VpcCIDR, PublicSubnet1CIDR, PublicSubnet2CIDR, PrivateSubnet1CIDR and PrivateSubnet2CIDR in an environment?

The use case is an AWS implementation that leverages VPC peering so needs to control the CIDR for VPC's.

I can see the variables in templates/environment/cf.yml, but i'm not yet Golang enough to establish if these values can be passed through by any mechanism (however undocumented).

I think setting these explicitly would be an advanced use case and as such not necessarily checked for validity or prompted for during an interactive environment creation.

If this is not currently possible, I think I could manage to to implement them in a PR as optional flags and I would be happy to do this work.

**Comment by efekarakus** [comment]
Hi @chrissamcat! 

Currently there is no way to set these values in an environment, but we're in the process of designing this feature (#740). Thanks for letting us know that the use case is for VPC peering. 

We'll update this issue once we solidify how #740 looks and would love to hear your feedback on our proposal :)

**Comment by chrissamcat** [comment]
Just to be clear; #740 talks about importing existing resources, but this request is to be able to set the CIDR to be used when the vpc and subnets are created by a copilot environment.

**Comment by efekarakus** [comment]
:wave: @chrissamcat

Just to make sure that I understand the request properly, does that mean you'd also want to be able to create a [AWS::EC2::VPCPeeringConnection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html) resource in a Copilot environment? besides being able to change the CIDR ranges

Thank you!

**Comment by chrissamcat** [comment]
That wasn't an expectation that I had. I was hoping to be able to set the CIDR so that peering could be achieved manually afterwards.

**Comment by efekarakus** [comment]
Sounds good!

**Comment by efekarakus** [comment]
heya! This feature is now released 🥳 in [v0.3.0](https://github.com/aws/copilot-cli/releases/tag/v0.3.0), when you run `copilot env init` you can now choose to `"Configure default resources"` which allows you to specify CIDR ranges.
