### ISSUE TITLE
Still have another AWS account environment, but copilot cli deletes ECR repository

### ISSUE THREAD

**Issue by hkobayash** [aws/copilot-cli#1126]
### copilot cli version
`v0.1.0`

### Steps to Reproduce
```bash
$ copilot app init example-app
$ copilot svc init --name front-end --svc-type "Load Balanced Web Service" --dockerfile Dockerfile
$ copilot env init -n test --profile accountA-apn1-profile
$ copilot env init -n prod --profile accountB-apn1-profile
$ copilot svc deploy --name front-end --env test
$ copilot svc deploy --name front-end --env prod
$ copilot svc delete --name front-end --env test
```
`prod` environment ECS service still running, but `front-end` ECR repository deleted and `copilot svc show front-end` command failed.

**Comment by kohidave** [comment]
I'm so sorry about this! We will take a look ASAP.

**Comment by kohidave** [comment]
All right, just want to say again that I'm sorry you encountered this bug - but we've got a fix in PR. I'll let you know when it's merged in. 

Thank you so much for letting us know - and I hope it hasn't caused you too much trouble!
