### ISSUE TITLE
Ability to start an interactive session with deployed containers

### ISSUE THREAD

**Issue by paulxuca** [aws/copilot-cli#1133]
First of all, great work with this tool! Love the direction and simplicity it offers.

Was just wondering if there are plans to support being able to start an interactive shell session with a launched container. I see there are plans to support one-off commands with #702, but an interactive shell session would be quite useful for our workflows.

**Comment by kohidave** [comment]
Thanks for the feedback @paulxuca ! We really appreciate it :D

Do you mind if I ask you a question? Are you interested in running an interactive shell on an existing, running container? Or do you just want an interactive shell running that's in your Cluster/VPC?

If it's the first, we'd need [this feature](https://github.com/aws/containers-roadmap/issues/187) to be implemented for Fargate.

**Comment by paulxuca** [comment]
@kohidave Thanks for the quick response. I'd love to be able to start a session on an existing container running already.

**Comment by kohidave** [comment]
Gotcha! That makes total sense. I'll keep this feature open. Once our friends on the Fargate team pick this work up, we'll add it to Copilot!

**Comment by mwarkentin** [comment]
@kohidave having both options is nice. We use convox which offers both options:

- shell into existing container: convox exec <existing container id> <cmd>
- launch a new one off shell: convox run <service> <cmd>

**Comment by benguillet** [comment]
Agreed! I would love to have interactive session with Copilot! In my use case would be totally enough to just have a new one off shell (a la heroku or convox run (service) cmd), attaching to an existing container would also be awesome, but less needed, and I understand fargate needs to support docker exec.. first.

**Comment by hundredwatt** [comment]
Anyone have workarounds for this? 

We currently use ECS with EC2 instances (not Fargate) and have a bash script to launch an interactive session there via `run-task` and then stop the Task when the session is closed. We're thinking about keeping this separate cluster just for running interactive sessions and migrating all our services to Copilot (assuming that Copilot created Task Definitions run just fine on a non-Copilot Cluster, though I haven't tested this yet). Curious if anyone else has different ideas?

**Comment by iamhopaul123** [comment]
Hey @hundredwatt, we are planning to add `copilot exec` which will launch an interactive session with the Fargate tasks Copilot spins up. Please stay tuned for this feature!

**Comment by iamhopaul123** [comment]
Close this issue as [`copilot exec`](https://aws.github.io/copilot-cli/docs/commands/svc-exec/) is available now 🎉
