### ISSUE TITLE
homebrew support

### ISSUE THREAD

**Issue by chenrui333** [aws/copilot-cli#1140]
FYI, I am writing a formula to support the homebrew installation.

**Comment by kohidave** [comment]
That's *awesome*. Thank you. Our build is a little more complicated than a simple go build, unfortunately. It also includes packaging some CloudFormation custom resources which are written in JavaScript.

```
make tools
make build
```

It's kind of a pain, that's why in our AWS Tap we just use the binary.

**Comment by chenrui333** [comment]
Yeah, I saw them in the `buildspec`. I was curious why we cannot build with the native golang though.

I will trying to use make commands to see if it can be ported over.

**Comment by kohidave** [comment]
Sure! I think it can be as easy as doing make tools && make, and ensuring that Golang and NPM are on the source system.

**Comment by chenrui333** [comment]
> Sure! I think it can be as easy as doing make tools && make, and ensuring that Golang and NPM are on the source system.

@kohidave I have just shipped the PR (I think build process fits into what we have in here), let me know if you have any concerns (I can have it open and close it later)

**Comment by rothgar** [comment]
Have a link to the PR?

**Comment by chenrui333** [comment]
The link attached from Homebrew side is the PR

**Comment by rothgar** [comment]
🤦‍♂️ I can't read.

Thanks

**Comment by chenrui333** [comment]
yeah, homebrew-core has already contained the formula. Due to that, closing this formula.

Also, it would be nice to migrate the tap formula into core (so that it would be more cross tested within the homebrew installations), happy to help out on that.
