### ISSUE TITLE
Allow specifying Docker build args in manifest

### ISSUE THREAD

**Issue by bunnyhugdev** [aws/copilot-cli#1158]
I've looked through the code and documentation but I can't find a way to pass a build arg to my docker container when building via the `copilot svc deploy` command.

Ideally I think specifying it in the manifest under `image` would be perfect.

**Comment by efekarakus** [comment]
Hi @bunnyhugdev we've started the work on this feature here: https://github.com/aws/copilot-cli/pull/1059 :)

**Comment by bunnyhugdev** [comment]
Awesome! Thanks!

**Comment by efekarakus** [comment]
heya @bunnyhugdev this was just released in [v0.3.0](https://github.com/aws/copilot-cli/releases/tag/v0.3.0), for documentation: https://github.com/aws/copilot-cli/wiki/Services#build
