### ISSUE TITLE
Example: Branch deploys on subdomains with ACM and load balancer

### ISSUE THREAD

**Issue by jaredpalmer** [aws/copilot-cli#1159]
Would it be possible to give an example of a workflow where each PR gets a subdomain, https, and a new build that updates on each commit? Ideally the load balancer is shared too so you don’t need to redeploy it. 

The goal is a workflow like Zeit/Vercel, Render, or Heroku pipelines

**Comment by kohidave** [comment]
Hello!!!!

Would you mind taking a look at this: https://github.com/kohidave/dns-and-lb-copilot-demo/tree/mainline

And let me know what you think? I want to make sure I'm answering the right questions for ya'll!

**Comment by jaredpalmer** [comment]
Thank you! Going to try it out! I skimmed over the Readme. Looks cool. It’s slightly different than the workflow that I’m after I think. 

What I’m looking for is pipeline for a single Docker application, where master is api.myexample.com. It redeploys with production environment variables whenever master updates. In addition, and each time a new branch is created on GitHub a new app is deployed with test/dev environment variables with the url <branch>.test.myexample.com. Whenever there is a new push on that existing branch occur, that application is redeployed with the changes. 

Bonus: when the branch is deleted, teardown the environment.
