### ISSUE TITLE
[Design] Better Credential Management and UX

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#1181]
One consistent bit of feedback that we've gotten from customers is that the way we handle profiles and AWS Credentials is confusing. 

There are two areas where we need to improve. The first is technically, honoring the default credential provider's flow, i.e. using the credential change customers expect. Environment Variables > Profile (AWS_PROFILE env var honored) > Default Profile > ECS/EC2 metadata.

The second area we need to help customers in is a UX when we offer the ability to choose different credential paths (e.g. setting up an environment). We currently have a profile selector, but we need a way to expose the values from the environment variables too.

**Comment by kohidave** [comment]
Tagging our friends at Docker @metcalfc so we can keep the experience consistent in Docker Compose too.

**Comment by efekarakus** [comment]
This was resolved with https://github.com/aws/copilot-cli/issues/1228
