### ISSUE TITLE
copilot init does not work behind proxy and assume role .

### ISSUE THREAD

**Issue by cool-raj** [aws/copilot-cli#1184]
here is what i get when i run the **copilot init** 

👍copilot init
Note: It's best to run this command in the root of your Git repository.
Welcome to the Copilot CLI! We're going to walk you through some questions
to help you get set up with an application on ECS. An application is a collection of
containerized services that operate together.

Your workspace is registered to application mero.
Service type: Load Balanced Web Service
Service name: mero-fronend
Dockerfile: ./Dockerfile
port represented at EXPOSE ${PORT} is invalid or unparseable
Port: 80
Ok great, we'll set up a Load Balanced Web Service named mero-fronend in application mero listening on port 80.

✔ Created the infrastructure to manage services under application mero.

✔ Manifest file for service mero-fronend already exists at copilot/mero-fronend/manifest.yml, skipping writing it.
Your manifest contains configurations like your container size and port (:80).

✔ Created ECR repositories for service mero-fronend.

All right, you're all set for local development.
Deploy: Yes

✘ Failed to accept changes for the test environment.

✘ describe stack mero-test: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, default.
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
	status code: 503, request id:

**Comment by cool-raj** [comment]
Also I am not able to find the images in the ECR. Does this create images ECR in the same account or somewhere else.

**Comment by efekarakus** [comment]
heya @cool-raj :wave:

Right now the CLI assumes that there is a "default" [named profile](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) and doesn't support environment variables for credentials.   
To mitigate the issue, would you mind taking a step similar to:
https://github.com/aws/copilot-cli/issues/1068#issuecomment-658712960

We're working on a long term fix here: https://github.com/aws/copilot-cli/issues/1181

**Comment by cool-raj** [comment]
thanks

**Comment by efekarakus** [comment]
heya! With [v0.3.0](https://github.com/aws/copilot-cli/releases/tag/v0.3.0) `copilot init` uses your default credential chain to create the environment so this err shouldn't happen. Resolving.

**Comment by jnvshubham7** [comment]
**how to use this solutoin please give me brief about that?**
```
copilot-proxy.githubusercontent.com
api.github.com (Also used for Self-hosted runners)
```


This error have shown in vs code when we trying to connect copilot on my collage internet which will use proxy system
`[ERROR] [default] [2022-06-16T05:43:59.030Z] GitHub Copilot could not connect to server. Extension activation failed: "getaddrinfo ENOTFOUND api.github.com"`

how to solve this problem ?
please reply me

**Comment by Lou1415926** [comment]
Hello @jnvshubham7, this is AWS Copilot, not GitHub Copilot.
Looks like [this](https://github.com/github/feedback/discussions/categories/copilot-feedback) is the place to post your issue for them.
Good luck!

**Comment by jnvshubham7** [comment]
> Hello @jnvshubham7, this is AWS Copilot, not GitHub Copilot. Looks like [this](https://github.com/github/feedback/discussions/categories/copilot-feedback) is the place to post your issue for them. Good luck!

ohh, sorry for that
