### ISSUE TITLE
Allow additional healthcheck configuration on "Load Balanced Web Service"

### ISSUE THREAD

**Issue by ivan-myob** [aws/copilot-cli#1195]
At the moment it is not possible to configure anything in the target group except of healthcheck path itself. Currently it is not possible to use copilot without manual intervention for the containers that take very long time to start. It would be very helpful to be able to specify other options in the manifest, such as:
- healthy threshold
- unhealthy threshold
- timeout
- interval
- success codes

**Comment by kohidave** [comment]
This is a great suggestion. Thank you @ivan-myob

**Comment by efekarakus** [comment]
This was released in v0.6.0 https://github.com/aws/copilot-cli/releases/tag/v0.6.0 happy building! 🚀
