### ISSUE TITLE
Pipeline: --deploy option for `pipeline init` seems not to exist.

### ISSUE THREAD

**Issue by git823** [aws/copilot-cli#1202]
The example for `copilot pipeline init` includes --deploy option.
https://github.com/aws/copilot-cli/wiki/pipeline-init-command
https://github.com/aws/copilot-cli/blob/ff9282854b1eabdcd446150e7ab105e85d3e8b50/internal/pkg/cli/pipeline_init.go#L508-L514

However, it seems that `pipeline init` does not have --deploy option. The deployFlag is never set for `pipeline init`.
https://github.com/aws/copilot-cli/blob/ff9282854b1eabdcd446150e7ab105e85d3e8b50/internal/pkg/cli/pipeline_init.go#L537-L540

If we specify --deploy option, the following error occurs with v0.2.0.
```bash
$ copilot pipeline init \
--github-url https://github.com/gitHubUserName/myFrontendApp\
--github-access-token file://myGitHubToken \
--environments "test,prod" \
--deploy
✘ unknown flag: --deploy
```

Is the example wrong? Or, do you have a plan to implement --deploy option in a future? If the example is wrong at the moment, I'll fix and submit PR.

**Comment by kohidave** [comment]
Oh, we need to remove that from our documentation. It's old.

We included it in the original command, but since we need you to commit the buildspec and pipeline.yml, the `--deploy` option didn't actually make sense.

**Comment by git823** [comment]
Thank you for your confirmation and approval for request! As PR was just merged, I'm closing this.
