### ISSUE TITLE
Pipeline: --github-access-token option for `pipeline init` does not read value from a file.

### ISSUE THREAD

**Issue by git823** [aws/copilot-cli#1209]
The example for `copilot pipeline init` is described as below:

```bash
$ copilot pipeline init \
--github-url https://github.com/gitHubUserName/myFrontendApp.git \
--github-access-token file://myGitHubToken \
--environments "test,prod"
```

docs: 
https://github.com/aws/copilot-cli/blob/master/site/content/en/docs/Commands/pipeline/init.md

help command:
https://github.com/aws/copilot-cli/blob/86ac9de84d570a077261c018f757673504340862/internal/pkg/cli/pipeline_init.go#L509-L513

However, if we write a token in a file and specify it as a value of --github-access-token option, SecretString in SecretsManager becomes not actual personal access token but specified string in command line.

Example:
```bash
$ copilot pipeline init --github-url https://github.com/git823/aws-copilot-sample-service --github-access-token file://myGitHubToken --environments "test"
✔ Created the secret github-token-https-aws-copilot-sample-service for pipeline source stage!
✔ Wrote the pipeline manifest for aws-copilot-sample-service at 'copilot/pipeline.yml'
The manifest contains configurations for your CodePipeline resources, such as your pipeline stages and build steps.
✔ Wrote the buildspec for the pipeline's build stage at 'copilot/buildspec.yml'
The buildspec contains the commands to build and push your container images to your ECR repositories.

Recommended follow-up actions:
- Commit and push the generated buildspec and manifest file.
- Update the build phase of your buildspec to unit test your services before pushing the images.
- Update your pipeline manifest to add additional stages.
- Run `copilot pipeline update` to deploy your pipeline for the repository.

$ aws secretsmanager get-secret-value --secret-id github-token-https-aws-copilot-sample-service
{
    "Name": "github-token-https-aws-copilot-sample-service",
    "VersionId": "593563DF-631A-4E30-AB76-CAA5A2450B08",
    "SecretString": "file://myGitHubToken",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1596139061.87,
    "ARN": "arn:aws:secretsmanager:ap-northeast-1:xxxxxxxxxxxx:secret:github-token-https-aws-copilot-sample-service-4DeiEi"
}
```

This SecretString is set to OAuthToken property for pipeline's source action, so pipeline fails to get source from GitHub.

Is the example wrong? Or, do you have a plan to support reading argument from a file as same as AWS CLI in a future? If the example is wrong at the moment, I'll fix and submit PR.

**Comment by huanjani** [comment]
Hello, @git823! 
I'm so sorry we never responded to you on this issue! Thank you for finding that ☝🏼 bug. 
As you probably know, we no longer use `--github-access-token` (https://aws.github.io/copilot-cli/docs/manifest/pipeline/#source-properties-ats), as we are connecting to GitHub via CodeStar Connections.
Thanks for your feedback!
