### ISSUE TITLE
Request for correction of errors in the `copilot env show` documentation 

### ISSUE THREAD

**Issue by tasogare0919** [aws/copilot-cli#1217]
I found what I believe to be an error in the wiki description.

In the `copilot env show` document below, I thought that it says `copilot env ls` when it should say `copilot env show`.

>What does it do?
>copilot env ls shows info about a deployed environment, including region, account ID, and services.

[env show command · aws/copilot-cli Wiki · GitHub](https://github.com/aws/copilot-cli/wiki/env-show-command)

I think this is a mistake and I would appreciate your help in correcting the description in the documentation.

**Comment by kohidave** [comment]
Thank you so much for pointing this out. I've updated it and believe it should be more clear!
