### ISSUE TITLE
Documentation error on secrets

### ISSUE THREAD

**Issue by jonchase** [aws/copilot-cli#1219]
From: https://github.com/aws/copilot-cli/wiki/Developing-With-Secrets

This:

```
aws ssm put-parameter --name GH_WEBHOOK_SECRET --value secretvalue1234 --type SecureString --overwrite master
```

Should actually read like this:

```
aws ssm put-parameter --name GH_WEBHOOK_SECRET --value secretvalue1234 --type SecureString --tags Key=copilot-environment,Value="env_name" Key=copilot-application,Value="app_name"
```

Changes: 

* Added `--tags Key=copilot-environment,Value="env_name" Key=copilot-application,Value="app_name"`, as these are required by the backend secrets policy of the IAM execution role
* Removed the erroneous `master` at the end
* Removed the `--overwrite`, as that is not allowed when setting tags

For reference, the execution role has a policy like (snippet):

```
            "Condition": {
                "StringEquals": {
                    "ssm:ResourceTag/copilot-environment": "env_name",
                    "ssm:ResourceTag/copilot-application": "app_name"
                }
```

**Comment by kohidave** [comment]
Ah perfect! I could have sworn we replaced that line, but looks like we didn't commit that. Awesome catch, and thanks for digging into the policy to figure it out! I'm sure that was a pain to debug, so I really appreciate it!
