### ISSUE TITLE
env init returns error if not in a workspace

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#1238]
When I run `copilot env init` and I'm not in a copilot workspace, then instead of prompting me to choose which application do I want to use, the CLI just errors out saying `✘ no application found: run `app init` or `cd` into your workspace please`.

**Comment by Nishikoh** [comment]
Hi, I'd like to tackle that.
Do you have example or idea of  prompting ?

**Comment by kohidave** [comment]
> Hi, I'd like to tackle that.
> 
> Do you have example or idea of  prompting ?

Take a look at the Ask() section of env_init. You can do something similar for what we do for name. If the app name is empty, call the SelectApp method prompt. 

Thank you for your help!

**Comment by efekarakus** [comment]
Released in v1.3.0! https://github.com/aws/copilot-cli/releases/tag/v1.3.0
