### ISSUE TITLE
Unexpected Escape Sequence on option-backspace in macos

### ISSUE THREAD

**Issue by glenwinters** [aws/copilot-cli#1244]
### Problem
I use option-backspace to delete the last word in iTerm2 on a macbook. I tried doing that during the `copilot init` prompts and it crashed the cli.

### Error

``` bash
$ copilot init
Note: It's best to run this command in the root of your Git repository.
Welcome to the Copilot CLI! We're going to walk you through some questions
to help you get set up with an application on ECS. An application is a collection of
containerized services that operate together.


X Sorry, your reply was invalid: Value is required

  What would you like to name your application? [? for help] stuff✘ ask app init: prompt get application name: Unexpected Escape Sequence: ['\x1b' '\u007f']
```

### Repro

1. Run `copilot init`
1. Type something in for the application name
1. Hit `option-backspace` to delete the input

I'm not sure if this is easily reproducible or if it's specific to my terminal config and shortcuts.

**Comment by efekarakus** [comment]
Hi @glenwinters ! 
I just tried to reproduce the issue but I didn't receive an error using iTerm2 with `option-delete`. Please let us know if this is still occurring for you, I'll close the issue in the mean time.
