### ISSUE TITLE
Feature: Github Enterprise Server in Pipelines

### ISSUE THREAD

**Issue by hnrc** [aws/copilot-cli#1247]
I'd love the ability to trigger a Copilot Pipeline from a self-hosted Github Enterprise instance.
I see that [CodeBuild already have support GH Enterprise Server](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-enterprise.html) but I'm not sure if it's supported by CodePipeline.

**Comment by hnrc** [comment]
> I see that [CodeBuild already have support GH Enterprise Server](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-enterprise.html) but I'm not sure if it's supported by CodePipeline.

~~I just learned that CodePipeline doesn't have Github Enterprise support just because it's supported by CodeBuild.
The only [supported source providers](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers) in CodePipeline seem to be: S3, ECR, CodeCommit, CodeStarSourceConnection and Github.~~

**Comment by hnrc** [comment]
> ~~I just learned that CodePipeline doesn't have Github Enterprise support just because it's supported by CodeBuild.
The only [supported source providers](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers) in CodePipeline seem to be: S3, ECR, CodeCommit, CodeStarSourceConnection and Github.~~

CodePipeline added native support for Github Enterprise Server repos a few weeks ago. Yay! 

https://aws.amazon.com/about-aws/whats-new/2020/09/aws-codepipeline-supports-github-enterprise-server/

**Comment by efekarakus** [comment]
Awesome! We're starting our work with additional pipeline source stages this week, so stay tuned :)

**Comment by hnrc** [comment]
> Awesome! We're starting our work with additional pipeline source stages this week, so stay tuned :)

Couldn't be more hyped! 😃

**Comment by efekarakus** [comment]
With #2073, you'll be able to specify an existing CodeStar connection created outside of Copilot to be able to integrate with GitHub enterprise!

**Comment by efekarakus** [comment]
This is now released in v1.5.0! https://github.com/aws/copilot-cli/releases/tag/v1.5.0 🚀
