### ISSUE TITLE
Arrow keys in "archer init" template step generate lots of newlines

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#127]
I'm a new user to archer and am creating my very first project. 

I define a project, then an application name, and when offered my choice of "Load Balanced Fargate Service" and told that I can use the arrow keys to navigate, my terminal is filled with newlines containing 
`? Which template would you like to use? [Use arrows to move, type to filter, ? for more help]`.

A new line is printed each time I press an arrow key. 

I expect this not to happen; ie if there is only one choice, no newlines should be printed.

**Comment by efekarakus** [comment]
mm we changed a lot of things for the prompt since the bug bash, would you mind retrying the CLI @bvtujo to see if this happens?

**Comment by bvtujo** [comment]
![Screen Shot 2020-01-28 at 2 44 00 PM](https://user-images.githubusercontent.com/25392995/73312345-50f47f80-41dd-11ea-98b0-f658f7ca5455.png)
It now seems to generate an extra newline when I press the arrow keys.

**Comment by efekarakus** [comment]
We haven't observed this behavior in a long time, resolving the issue.
