### ISSUE TITLE
Support Bitbucket repositories for Copilot pipelines

### ISSUE THREAD

**Issue by sanjeevtejyan** [aws/copilot-cli#1274]
I was trying to setup the pipeline using bitbucket git repository but getting following error

please pass the repository URL with the format `--github-url https://github.com/{owner}/{repositoryName}`

**Comment by jwillingham789** [comment]
https://aws.amazon.com/about-aws/whats-new/2019/12/aws-codepipeline-now-supports-atlassian-bitbucket-cloud/

CodePipeline supports Bitbucket repos, so I think it would be possible to add support for it in Copilot.

**Comment by kohidave** [comment]
We should notify @srhise on Twitter once this integration is done - he was interested in it :)

**Comment by nnajiabraham** [comment]
Just curious on an update on this, any luck supporting this?

**Comment by efekarakus** [comment]
@nnajiabraham We're starting the work for supporting CodeCommit soon (https://github.com/aws/copilot-cli/issues/781) and then we'll add support for CodeStar Connections which will handle supporting both Bitbucket and GitHub enterprise!

**Comment by nnajiabraham** [comment]
Thanks for update, awesome stuff @efekarakus

**Comment by efekarakus** [comment]
Hi folks! the feature is released in v1.3.0: https://github.com/aws/copilot-cli/releases/tag/v1.3.0!
