### ISSUE TITLE
Using secrets results in "Service did not stabilize"

### ISSUE THREAD

**Issue by BenediktMiller** [aws/copilot-cli#1291]
Hello,

whenever I try to use secrets in the manifest.yml the deployment fails (after quite some time) with the following error:

"Service arn:aws:ecs:eu-central-1:xxx:service/my-Cluster-xxx/xxx-Service-xxx did not stabilize."

as soon as I remove the secrets part form my manifest the deployment succeeds.

Is this some issue with copilot or do I need some additional policy for accessing the Systems Manager Parameters?

Copilot version: v0.2.0
macOs 10.15.4 (19E287)

**Comment by efekarakus** [comment]
Heya!

I'll update our documentation to make this more explicit: https://github.com/aws/copilot-cli/wiki/Developing-With-Secrets, but for Copilot to read the secrets in SSM the secrets have to have the following two tags:
- Key=copilot-environment and Value={Your Environment Name}
- Key=copilot-application and Value={Your Application Name}

If you use the AWS CLI to create the secrets you can run:
```
aws ssm put-parameter --name ${SECRET_NAME} --value ${SECRET_VALUE} --type SecureString\
  --tags Key=copilot-environment,Value=${ENVIRONMENT_NAME} Key=copilot-application,Value=${APP_NAME}
```

**Comment by efekarakus** [comment]
Updated our documentation with: 

> ⚠️&nbsp; **IMPORTANT**  Copilot requires the `copilot-application` and `copilot-environment` tags to limit access to this secret.  It's important to replace the `${ENVIRONMENT_NAME}` and `${APP_NAME}` with the Copilot application and environment you want to have access to this secret.

**Comment by BenediktMiller** [comment]
Worked for me! Thanks for the help.😃
