### ISSUE TITLE
task run fails to display logs when --follow is set

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#1301]
## Issue Description
Dockerfile (this is also the Dockerfile used in task e2e test)
```
FROM python:3.7-slim

RUN mkdir /app

ADD . /app

WORKDIR /app

CMD ["echo", "e2e success: task running."]
```

When using `task run` to run tasks from this Dockerfile, `--follow` failed to display "e2e success: task running.". Instead, this log was swallowed. Note that this also causes our task e2e test failure.

Dive deep into the root of this problem, this is because logs for all tasks that built from the same task definition are usually running in the same log group. As a result, we get the earliest start time among all running tasks as filter when we get the logs, in order to not only show logs from all running tasks but also avoid showing any logs from previous tasks. As we detect all tasks are stopped, the CLI exits.

However, in this Dockerfile scenario, the earliest start time is actually slightly later than the timestamp for log event "e2e success: task running." (less than one second differential). As a consequence, this log event is not able to be fetched and displayed.

## Solution Proposal
Given this limitation of CW and ECS described above, we need to find another way of filtering log events so as to get the correct logs. We can possible solve this problem by filtering logs by task ID instead of start time since each task ID is uniquely associated with a task stream.

**Comment by efekarakus** [comment]
Thanks for diving deep on the issue!
