### ISSUE TITLE
"task run" stacks cannot be deleted after app is deleted

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#1306]
### Description
If a user uses `task run` to run a one off task in a Copilot environment, then the CFN stack is created using the environment's CFNExecution role. If a user runs `app delete`, the environments get deleted and hence the CFNExecution role is also deleted. This results in dangling task run stacks that cannot be deleted because cfn needs to assume a deleted role.

### Proposal
Implement a `task delete` command to remove the stack, and during `app delete` invoke it while deleting an environment.

### Mitigation
Although not ideal, one way of removing this stacks is to create this role again manually, delete the CFN stack and then delete the role again.

**Comment by aviflax** [comment]
Yes please!

**Comment by efekarakus** [comment]
Closing this was released in v1.2.0: https://github.com/aws/copilot-cli/releases/tag/v1.2.0!
