### ISSUE TITLE
Logs should not color those words with "ERR" string

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#1312]
Currently, when outputting log events, any words with substring "ERR" or other fatal codes or warning codes will be shown with color. We should fix this.

<img width="523" alt="Screen Shot 2020-08-20 at 12 39 52 PM" src="https://user-images.githubusercontent.com/51377557/90942935-991efd80-e3cc-11ea-8f9c-4c4cd5e79a48.png">

**Comment by corykitchens** [comment]
Hi @iamhopaul123 

I would love to contribute to the project by contributing a patch to this issue!

In regards to the proposed patch, are you hoping for a sanitized string that removes all references to color prior to writing to the logs? Or removing the references to the color package in the `cloudwatchlogs.Event.HumanString()` method? 

Let me know your thoughts/concerns and I will start my implementation.

**Comment by iamhopaul123** [comment]
Hello @corykitchens, thank you for your interest in contributing to Copilot! Honestly I don't mind that much about the implementation details which we could discuss in comments after having the PR out, as long as those colored logs make sense to most of users!

**Comment by efekarakus** [comment]
Resolved in https://github.com/aws/copilot-cli/pull/1350
