### ISSUE TITLE
[question] is there a way to configure vpc, security groups and subnets?

### ISSUE THREAD

**Issue by fullstackdev-online** [aws/copilot-cli#1315]
Hi,

my ecs cluster is supposed to use some resources running on EC2 instance(s) in a dedicated vpc/subnet/security group(s). Is there a possibility to provide this configuration to a new app with copilot?

PS: perhaps, it's a good candidate for FAQ, but haven't found an answer yet. Also couldn't find anything related in [the wiki](https://github.com/aws/copilot-cli/wiki/Manifests#load-balanced-web-svc).

**Comment by waiyanminyoma** [comment]
You can use the existing VPC and subnets.

**Comment by toricls** [comment]
@fullstackdev-online Check out the wiki [here](https://github.com/aws/copilot-cli/wiki/env-init-command) and see the `--import-xxx` options to bring your existing VPCs into your Copilot apps!

**Comment by fullstackdev-online** [comment]
thank you, it's exactly what I was looking for!
