### ISSUE TITLE
Support multi-stage build targets

### ISSUE THREAD

**Issue by jahsome** [aws/copilot-cli#1331]
I may be going about this wrong, but I have a container which needs asset dependencies installed and compiled for a production build but not local/development builds. Specifically, I need to install npm dependencies and run gulp.

I couldn't think of a way to accomplish this, other than to create a multi-stage build in the Dockerfile and attempt to reference the specific stage but I don't see a way to do that with the init command.

If I have missed something or am attempting some grave sin by attempting this, I welcome any feedback.

Cheers!

**Comment by efekarakus** [comment]
😄 Heya @jake-harris ! 
Would modifying the `build`  section of the manifest for your service help in this situation? https://github.com/aws/copilot-cli/wiki/Services#build 
Under `build` there is an `args` property that map to the `--build-args` flag while building your container image. So I wonder if that can be used to refer to a specific stage.

If this helps, you can modify the manifest before deploying to the "test" environment and the image should build properly before pushing to the ECR repository.

**Comment by jahsome** [comment]
Thanks for the response! 

Modifying the manifest with `args` would probably get me there, but would require some rethinking of my Dockerfile, and potentially eliminate the multi-stage build. Unfortunately I have other workflows dependent upon some of the stages so I don't think that's an option for me particularly.

Ideally, in the manifest, there would be a 


```
image:
  build:
    dockerfile: path/to/dockerfile
    context: context/dir
    args:
      key: value
    target: my-build-stage
````
Which would output to:

```
docker build --file path/to/dockerfile --build-arg key=value context/dir --target=my-build-stage
```

**Comment by efekarakus** [comment]
Thanks yeah that totally makes sense, I've updated the issue with a feature request label for us to prioritize in our sprints!
As we make progress on the task, this issue will get updated.
