### ISSUE TITLE
Copilot pipeline - support other platforms than GitHub

### ISSUE THREAD

**Issue by niros1** [aws/copilot-cli#1343]
Is there any plan to support other code management platforms than GitHub?
I am currently working with BitBucket and GitLab.
Is there another workaround to overcome that? I thought of building "manually" the CodeBuild process but that put Copilot aside.

**Comment by efekarakus** [comment]
Hi @niros1!

> Is there any plan to support other code management platforms than GitHub?

We do not support at the moment other pipeline triggers besides GitHub, but yes we do plan to integrate with both BitBucket and GitLab. We have a main tracking issue here for all pipeline triggers: https://github.com/aws/copilot-cli/issues/1339.

Please give a 👍 to both https://github.com/aws/copilot-cli/issues/1274 and https://github.com/aws/copilot-cli/issues/1338 as it will help us prioritize the work.

> Is there another workaround to overcome that?

We don't have to overcome this hurdle at the moment unfortunately, but we are starting the work on adding new sources

**Comment by efekarakus** [comment]
I'll close this issue in favor of #1274 and #1338 if you've additional requirements please let us know there, thank you!
