### ISSUE TITLE
task run hangs for a long time when I forget to provide credentials

### ISSUE THREAD

**Issue by aviflax** [aws/copilot-cli#1370]
I have my local AWS CLI environment set up so that the default profile doesn’t have credentials.

Usually I set the environment variable AWS_PROFILE before running copilot.

Just now, I forgot to do so, so copilot reported an error.

Which is fine, and the error message was useful, but it took a *long* time to show up. For a very long time (at least 3 minutes) the tool printed no output, so it seemed like it might be hung.

Finally, it printed this and exited:

```text
✘ get application: get application plotwatt: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

All the behavior here is fine, except the lack of feedback. For example, if the tool had output something like “No credentials found in shared credentials file, querying local metadata server for IAM credentials…” then I would have immediately understood what was happening, realized my mistake, and I would have killed the tool immediately, rather than waiting for some indefinite amount of time with no sign of progress or activity.

**Comment by kohidave** [comment]
Thanks a ton for taking the time to let us know about this! Yea - this sounds really frustrating, sorry about that. I think we can pull the credential timeout in quite a bit or at least provide some more feedback like you suggested. 

Again, really appreciate you taking the time to let us know! We'll post updates here on our fix.

**Comment by aviflax** [comment]
My pleasure, that sounds great. Thanks for accepting the feedback so graciously!

**Comment by Lou1415926** [comment]
Closing this via #2816.
