### ISSUE TITLE
svc status: don't prompt with "Only found one deployed service <svc> in environment <env>" when i specify env

### ISSUE THREAD

**Issue by adamjkeller** [aws/copilot-cli#1416]
Should copilot prompt me that it only found one service in the environment even though I am specifying the name of the service as well as the name of the environment?

Example:
```
$ copilot svc status -n ecsdemo-frontend --env test
Only found one deployed service ecsdemo-frontend in environment test
```

This is kind of a silly issue to open, sorry. It just feels like it's an unnecessary output when i'm explicitly setting my svc name and env.

Current workaround:

$ copilot svc status -n ecsdemo-frontend --env test 2> /dev/null

**Comment by huanjani** [comment]
Note: This behavior also happens in `svc logs`.
