### ISSUE TITLE
CLI sometimes, rarely, prompts me to choose an AWS CLI profile, despite AWS_PROFILE being set

### ISSUE THREAD

**Issue by aviflax** [aws/copilot-cli#1420]
For example:

```shell
$ copilot app delete
Which named profile should we use to delete test? pw-dev
```

This seems inconsistent because I always have the environment variable AWS_PROFILE exported when I’m using copilot, and *most* commands seem to just pick up on that and use it just fine.

I’m not sure what exactly is going on here, but in general I’d prefer that the tool use the profile specified in AWS_PROFILE rather than prompting me.

Thank you!

**Comment by efekarakus** [comment]
heya @aviflax ! that makes sense :) the reason why we prompt is in case you have multiple environments defined with different profiles.

In that case we'd need to provide a way of specifying another profile besides the `AWS_PROFILE`. But we can maybe make this nicer by pulling the `AWS_PROFILE` to the top and just pressing enter

**Comment by aviflax** [comment]
That makes sense!

The one thing that still puzzles me is why this seems to be inconsistent. Why do some commands ask for this and others don’t?

**Comment by efekarakus** [comment]
heya! with #1510 environment && app deletions should no longer require profiles so it should remove this confusion :)
