### ISSUE TITLE
Ability to set the domain per environment

### ISSUE THREAD

**Issue by inssein** [aws/copilot-cli#1430]
First of all, awesome project, it's been working great so far.

I'm not sure if this is the right place for feature requests, but it would be awesome to be able to have set the domain per environment. The current application I am working on has 2 separate AWS accounts for the different environments, and also has completely separate domains.

**Comment by kohidave** [comment]
That makes total sense! We've started planning out what more DNS control might look like in this issue: https://github.com/aws/copilot-cli/issues/1188

**Comment by inssein** [comment]
@kohidave awesome.

I also just realized that my current ask works just fine. I instantiated the app separately per AWS profile and set the relevant domain name, and so far it is working.

Going to close this issue as the rest of my asks are already tracked in the other issue.
