### ISSUE TITLE
Feature request: when a service deployment fails, output the underlying reason

### ISSUE THREAD

**Issue by aviflax** [aws/copilot-cli#1431]
For example, I just had this experience:

I ran `copilot svc deploy` and got this output:

```
✘ Failed to deploy service.

✘ deploy service: wait until stack plotwatt-avi-test-shared-infra update is complete: ResourceNotReady: failed waiting for successful resource state
```

I don’t know what all that means, but I know in order to discover the underlying problem I have to go to the CloudFormation console and dig around.

Eventually under the _Events_ tab for the stack for this service, I saw this:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/141844/94275603-26e29100-ff15-11ea-8167-26f17a5375d5.png">

It’d be way better for the tool to find that info for me and print it out.

Thank you!

**Comment by iamhopaul123** [comment]
Hello @aviflax.

> I don’t know what all that means, but I know in order to discover the underlying problem I have to go to the CloudFormation console and dig around.

Yeah I agree we should make our error message more useful for you to find out the reason why your CFN deployment fail in this situation when your addon stack fails to update.

**Comment by bvtujo** [comment]
Hi @aviflax, we've just merged in a PR which fixes this issue. We now go looking for the chronologically first error event and append the status reason to the end of the error output. 

The following output is due to a nested stack with a malformed DDB table failing to deploy:

```bash
✘ Failed to deploy service.

✘ deploy service: wait until stack sample-test-fe update is complete: ResourceNotReady: failed waiting for successful resource state: Embedded stack arn:aws:cloudformation:us-west-2:803937525441:stack/sample-test-fe-AddonsStack-G2K8VXZESYN2/070bcac0-1d4e-11eb-892b-068a43604208 was not successfully created: The following resource(s) failed to create: [my-table]. 
```

**Comment by aviflax** [comment]
Very nice!
