### ISSUE TITLE
Shouldn't ask for port for backend service

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#1435]
Right now if you try and create a backendservice without an expose, it'll ask you for a port:

```
Dockerfile: ./Dockerfile
no EXPOSE statements in Dockerfile ./Dockerfile

  Which port do you want customer traffic sent to? [? for help] (80)
```

This often doesn't make much sense for backend services (I was building a queue processing service).

**Comment by bvtujo** [comment]
Is there anything in service discovery we need the port for, so this would just be a prompt wording change, or do we need to remove this ask entirely for backend services?

**Comment by hnrc** [comment]
Heya 😄
👉 https://github.com/aws/copilot-cli/issues/1246 👈
