### ISSUE TITLE
Support alarms for services

### ISSUE THREAD

**Issue by inssein** [aws/copilot-cli#1442]
It looks like there is some support for alarms (`copilot svc status`) but I can't find any documentation for how I can create an alarm.

If someone can point me to an example, I don't mind writing the docs.

**Comment by efekarakus** [comment]
Heya @inssein ! Right now we don't have a way of defining CW alarms using the CLI. Unfortunately, you'd need to create them separately through the console, AWS CLI, or CFN. 
But, Copilot will display these alarms for you when you run `svc status` if you tag the alarms with `copilot-application`, `copilot-environment` and `copilot-service`.

For example, if I have a service named "site" in a "test" environment in a "vote" app:
```
$ aws cloudwatch tag-resource --resource-arn arn:aws:cloudwatch:region:account-id:alarm:alarm-name --tags Key=copilot-application,Value=vote
$ aws cloudwatch tag-resource --resource-arn arn:aws:cloudwatch:region:account-id:alarm:alarm-name --tags Key=copilot-environment,Value=test
$ aws cloudwatch tag-resource --resource-arn arn:aws:cloudwatch:region:account-id:alarm:alarm-name --tags Key=copilot-service,Value=site 
```
https://github.com/aws/copilot-cli/issues/1442

Let us know if you have any ideas on the kindof UX you'd like to have around alarm creation!

**Comment by inssein** [comment]
Ah okay, seems like I am being hampered by this CloudFormation feature request: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/64

I have already used the addons CloudFormation stack to create relevant alarms (for example, I have an alarm when something ends up in a dead letter queue), but since I can't tag them via CFN, it doesn't show up up when I run the `svc status` command.

Will add a manual step to tag alarms for now until the above feature request is resolved.

As for the UX of alarms, that's going to be pretty tough. From my experience, there are some basic alarms that should be setup for certain resources, especially queues, but every organization wants to deal with them differently. Perhaps just some CFN samples that people can use.

**Comment by ssyberg** [comment]
Is this doable via addons now?

**Comment by huanjani** [comment]
Yes, just be sure to tag them with the `copilot-application`, `copilot-environment`, and `copilot-service` tags (as mentioned [here](https://github.com/aws/copilot-cli/issues/1442#issuecomment-700353648)) if you'd like them to be included in the output of `copilot svc status`. 

If you're interested in alarm-based rollbacks, see https://aws.github.io/copilot-cli/blogs/release-v126/#service-alarm-based-rollback.
