### ISSUE TITLE
Feature request: “import” a secret from Secrets Manager by name

### ISSUE THREAD

**Issue by aviflax** [aws/copilot-cli#1449]
…via service manifest, and have it be “exported” to service tasks at runtime. (And, later, also to the tasks that run in the “context” of the service (#1269)).

This came out of a discussion in #1365 

I’ll try to summarize:

* I’ve got a service called `shared-infra` that’s not really a service — it’s just a host for some addons defining shared infrastructure resources that I need to define+deploy that are used, and shared, by my _real_ services
* One of the resources I’ve defined in one of my add-ons is a Secrets Manager secret
* I’d like to be able to inject that Secrets Manager secret into the tasks of my other services
* @efekarakus suggested trying this:
  ```yaml
  test:
    secrets:
      DB_PASSWORD: 'arn:aws:secretsmanager:region:aws_account_id:secret:secret_name-AbCdEf'
  ```

* That worked great!
* **However,** it required me to hard-code the region and account ID into the manifest file I’d like to avoid this so that the config is more flexible and can be used with an arbitrary account and an arbitrary region.

So that’s the point of my request here: I’d like to be able to inject a Secrets Manager secret by specifying just the name, (the logical name) rather than the ARN.

Thank you!

**Comment by huanjani** [comment]
Hi all!
AWS Copilot v1.15.0 is now released with this feature! https://github.com/aws/copilot-cli/releases/tag/v1.15.0 🎉🚀
