### ISSUE TITLE
feature request: use copilot cli with another AWS profile than default

### ISSUE THREAD

**Issue by ivanbarlog** [aws/copilot-cli#1454]
It is not possible to use copilot cli with other than `default` profile.

Could you please provide some `--profile` flag so it could be changed per command?

Cheers!

**Comment by hnrc** [comment]
You can set the `AWS_PROFILE` environment variable to override `default` if you want to, e.g. `AWS_PROFILE=foo copilot init`.

**Comment by ivanbarlog** [comment]
sorry, my bad, I've just read it within the documentation - it is hidden too good ;-)

https://github.com/aws/copilot-cli/wiki/Credentials#application-credentials
