### ISSUE TITLE
Ability to use existing VPCs 

### ISSUE THREAD

**Issue by CountryNerd** [aws/copilot-cli#1456]
Ability to use existing VPCs

**Comment by iamhopaul123** [comment]
Hello @CountryNerd, you could use existing VPC when you [create an environment](https://github.com/aws/copilot-cli/wiki/env-init-command) by doing `copilot env init`. The CLI should prompt you whether to use existing VPC instead of creating a new one.

**Comment by CountryNerd** [comment]
Oh thank you that does work.
