### ISSUE TITLE
Ability to use existing ALBs

### ISSUE THREAD

**Issue by CountryNerd** [aws/copilot-cli#1457]
Ability to use existing ALBs

**Comment by samuelthan** [comment]
Love this feature to be incorporated :)

**Comment by Lou1415926** [comment]
Hi all, AWS Copilot v1.32.0 is now released: https://github.com/aws/copilot-cli/releases/tag/v1.32.0 🎉🚀 We shipped the feature that lets you place your existing ALB in front of your Load-Balanced Web Service - just specify the name or the ARN of the ALB in the `http.alb` field.  Check out our [blog post](https://aws.github.io/copilot-cli/blogs/release-v132/) for more details, as well as other very cool features ❤️ !
