### ISSUE TITLE
Quoting and command argument parsing for one-off tasks

### ISSUE THREAD

**Issue by Envek** [aws/copilot-cli#1466]
When I try to execute complex command as one-off task (like one in the README):

```sh
copilot task run        \
  --default             \
  --follow              \
  --image alpine:latest \
  --command "echo 'Howdy, Copilot'"
```

Command gets split into words by spaces without account for nested quoted strings.

**Expected behavior**

Container runs with quoted string as single argument:
```json
["echo","'Howdy, Copilot'"]
```

**Actual behavior:**

Container runs with  quoted string split in-between:
```sh
["echo","'Howdy,","Copilot'"]
```

**Real world example**

If you need to use environment variable like this: `curl $ECS_CONTAINER_METADATA_URI_V4`, you need to run command inside some shell to be able to read it: `/bin/sh -c 'curl $ECS_CONTAINER_METADATA_URI_V4'`, but if you do

```sh
copilot task run        \
  --default             \
  --follow              \
  --image quay.io/evl.ms/curl:3.8 \
  --command '/bin/sh -c "curl $ECS_CONTAINER_METADATA_URI_V4"
```

Container will be executed with following command:
```json
["/bin/sh","-c","\"curl","$ECS_CONTAINER_METADATA_URI_V4\""]
```

And following error will be returned:
```
copilot-task/test $ECS_CONTAINER_METADATA_URI_V4": line 1: syntax error: unterminated quoted string
```

**Is there any workaround for that?**

**Comment by iamhopaul123** [comment]
Hi @Envek, thank you for your feedback for Copilot! Yes, this is definitely an issue we need to resolve for `copilot task run`. So far unfortunately there's no easy workaround for this issue, but there'll be a quick fix for this soon.

**Comment by Envek** [comment]
@iamhopaul123 thank you for rapid fix! :pray:
