### ISSUE TITLE
Update installation docs for brew

### ISSUE THREAD

**Issue by mkjsix** [aws/copilot-cli#1470]
The documentation says to install we have to run `brew install aws/tap/copilot-cli` but brew answers with:

```
Error: No available formula or cask with the name "aws/tap/copilot-cli".
==> Searching for similarly named formulae...
This similarly named formula was found:
copilot-cli
To install it, run:
  brew install copilot-cli
```

I guess the docs need to be updated?

**Comment by efekarakus** [comment]
Heya!

I just tried it out:
```
==> Installing copilot-cli from aws/tap
==> Downloading https://github.com/aws/copilot-cli/releases/download/v0.4.0/copilot_0.4.0_macOS_amd64.tar.g
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/202018792/2b0a6800-fc1
######################################################################## 100.0%
```

and it seems to work fine for me! Which platform are you using macOS or linux?

**Comment by mkjsix** [comment]
I have the latest MacOS Catalina. 

However, if you look at the Homebrew catalog, the package is in the root brew folder and not in the aws/tap anymore: https://formulae.brew.sh/formula/copilot#default 

Perhaps locally you have an older brew cache, that's why you can still install from there?

**Comment by efekarakus** [comment]
I wonder if running `brew tap aws/tap` first will help:
```
$ brew tap aws/tap
$ brew install aws/tap/copilot-cli
```
If that works I'll update our docs to add the extra step
