### ISSUE TITLE
Not seeing stdout in service logs

### ISSUE THREAD

**Issue by ctindel** [aws/copilot-cli#1471]
It seems like my service logs are only showing me stderr (exceptions etc) but none of my stdout debugging statements.

According to this blog post I thought I'd see stdout:

https://aws.amazon.com/blogs/containers/introducing-aws-copilot/

Is this a known problem, do I need to do something special to get stdout routed to the logs?

**Comment by efekarakus** [comment]
Heya @ctindel !

Copilot doesn't do any particular regarding forwarding logs to CloudWatch.   
Is it possible that an environment variable needs to be set for the service logs or some sort of framework configuration needs to be put in place? What is the tech stack for the service?

**Comment by ctindel** [comment]
@efekarakus This is just a simple python script that runs in an infinite loop.  All I know is that if I run it from the shell I see some startup debugging messages but when I launch it as a copilot service all I see are things like exceptions.

**Comment by efekarakus** [comment]
How are the logs printed? do you use just `print` or a logging library?

**Comment by ctindel** [comment]
print() statements

**Comment by ctindel** [comment]
I am closing this for now.  It seems to be working although I have no idea what changed.  Sorry about the misfire.

**Comment by efekarakus** [comment]
That's very strange haha, I'm glad that it's working now though :D
