### ISSUE TITLE
Environmental variables for service deployment

### ISSUE THREAD

**Issue by huezo89** [aws/copilot-cli#1502]
Is it possible to use environmental variables for service deployment?

I have my projects in Gitlab and was trying to push my projects with Gitlab pipelines. I can use environmental variables for my credentials if I want to read data (svc ls, env ls, app ls, etc), but if I want to deploy a service, it then goes to ~/.aws/ to look for the credentials/config files.

It seems it is possible to do this when initializing environments 
copilot env init --aws-access-key-id string  --aws-secret-access-key string

but I haven't seen this yet for svc deployment. Is it possible?

Thanks.
Regards.

**Comment by efekarakus** [comment]
Heya @huezo89 !

What version of the Copilot CLI are you using? would you mind also copy pasting the error that you get?

I just tried this out locally using `v0.4.0` by doing:
```
export AWS_ACCESS_KEY_ID="my access key"
export AWS_SECRET_ACCESS_KEY="my secret access key"
export AWS_SESSION_TOKEN="my session token"
$ copilot svc deploy
```
and it picked up the correct credentials.

Thanks!

**Comment by huezo89** [comment]
Hi, thanks for the reply, I am using v0.4.0

$ export AWS_ACCESS_KEY_ID=$AAKI
$ export AWS_SECRET_ACCESS_KEY=$ASAK
$ export AWS_DEFAULT_REGION=$ADR

If I try to deploy I get this error:
✘ get environment test configuration: get environment test in application ecom-system: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed

It fails if I try to deploy, but if I try to do an "sudo copilot svc ls" it works fine. I use the same credentials (no token) in the ~/.aws/credentials file and it works fine, but it doesn't if I use the Environmental Variables.

The only thing I didn't do was install the AWS CLI, so maybe that is all that is needed?

Thanks.
Regards.

**Comment by efekarakus** [comment]
That's so strange!

I deleted the AWS CLI, moved `~/.aws` to a different directory and it worked with:
```
export AWS_ACCESS_KEY_ID="my access key"
export AWS_SECRET_ACCESS_KEY="my secret access key"
export AWS_SESSION_TOKEN="my session token"
export AWS_REGION="us-east-2"
```

> The only thing I didn't do was install the AWS CLI, so maybe that is all that is needed?

Would you mind giving this a shot?

Maybe as an other alternative, this might work:
```yaml
# in ~/.aws/config
[default]
credential_source = Environment
```

**Comment by huezo89** [comment]
I found the problem, I was running "sudo copilot svc deploy" so it was unable to access the variables.
running "copilot svc deploy" (like you did) did the trick.

**Comment by efekarakus** [comment]
Yay awesome! I'll close the issue if that's okay, feel free to re-open it for any additional issues :)
