### ISSUE TITLE
GitHub Default Branch is main NOT master for Pipeline

### ISSUE THREAD

**Issue by trevorrobertsjr** [aws/copilot-cli#1503]
GitHub is updating their repo terminology so that "main" is the default branch name, not "master". Please update pipeline functionality accordingly.

**Comment by kohidave** [comment]
💯 Thanks so much for the catch! We actually just updated our code to use `main` as the default branch! This change will be released in the next Copilot release 👍 

https://github.com/aws/copilot-cli/commit/51369a39f009b7a432b8aef98ca34ed89b38ee2b

Thanks again!
