### ISSUE TITLE
Running a one task with a exists Cluster

### ISSUE THREAD

**Issue by codecrack3** [aws/copilot-cli#1506]
How i can run a task with a exists cluster ?.

**Comment by efekarakus** [comment]
Hello @codecrack3 !

With the `task run` command at the moment there are only two options:
* Run in the default cluster (you can specify subnets and security groups)
* Or, run in a Copilot environment cluster.

Is there a reason why you'd like to run in a specific cluster? Is there a particular advantage?

**Comment by codecrack3** [comment]
Hi @efekarakus  thanks you for reply me. In this case, I’m have a cluster with 2 services and now I want to run more another service quickly with copilot. Do you think is a advantage? . I hope see your answer soon.  Thanks

**Comment by efekarakus** [comment]
Heya!

Just to make sure that I'm on the same page:
* You have already an existing ECS Cluster with 2 running services that was created outside of Copilot. Is that right?
* And you want to add a third service service to the existing ECS Cluster?

One way that I can think of is running:
```bash
$ copilot app init    # create a new copilot application
$ copilot env init    # create a new environment but use the existing VPC where your 2 services exist
$ copilot svc init    # create your new service
$ copilot deploy    #  deploy the new service
```
These steps will still create a new ECS cluster, however the new service will be in the same VPC and can be communicated to with [service discovery](https://aws.github.io/copilot-cli/docs/developing/service-discovery/)!

**Comment by codecrack3** [comment]
> Heya!
> 
> Just to make sure thatsame page:
> 
> * You have already an existing ECS Cluster with 2 running services that was created outside of Copilot. Is that right?
> * And you want to add a third service service to the existing ECS Cluster?
> 
> One way that I can think of is running:
> 
> ```shell
> $ copilot app init    # create a new copilot application
> $ copilot env init    # create a new environment but use the existing VPC where your 2 services exist
> $ copilot svc init    # create your new service
> $ copilot deploy    #  deploy the new service
> ```
> 
> These steps will still create a new ECS cluster, however the new service will be in the same VPC and can be communicated to with [service discovery](https://aws.github.io/copilot-cli/docs/developing/service-discovery/)!

**Comment by codecrack3** [comment]
Hey. Thanks you explained to me. I think i already have the answer . Many thanks

**Comment by efekarakus** [comment]
Awesome, please feel free to re-open if you have any questions!
