### ISSUE TITLE
Branch deploy? Per-env (dev/qa/prod) vars from SSM?

### ISSUE THREAD

**Issue by jaredpalmer** [aws/copilot-cli#1511]
I am a running a Docker Dropwizard Kotlin app on Fargate right now and deploying via AWS CLI. I currently only use Fargate for production, but I am wondering if copilot plus codedeploy can handle the following Vercel/Heroku-style branch deploy architecture:

- push to master branch on github => test => build => push image => deploy to production at `api.example.com` (prod IAM policy and SSM credentials (e.g. `/prod/api/stripe_key`))
- push to a new `feature-123` branch on github => test => build => push image => deploy at `feature-123-api.example.com` (dev IAM policy and SSM credentials (e.g. `/dev/api/stripe_key`)). Subsequent pushes redeploy.
- push to a new `feature-456` branch on github => test => build => push image =>  deploy at `feature-456-api.example.com` (dev IAM policy and SSM credentials (e.g. `/dev/api/stripe_key`)). Subsequent pushes redeploy.
- When I delete any of the feature branches, I want to teardown all of its fargate resources/containers/etc.
- During a branch deploy, need to be able to override or specify environment variables passed to the application in the CI. For example, Sentry needs to know the git commit hash for releases (e.g like `SENTRY_RELEASE=${GIT_COMMIT_SHA}`. Another requirement to would be to specify a different db connection string for each branch (like `PG_URL=xxxx:xxxxx/${GIT_BRANCH_NAME}`).
- I want to share an application load balancer so I don't need to wait on it for branch deploys
- Everything needs to be HTTPS at all times. HTTP must redirect to HTTPS.
- Use a wildcard cert from certificate manager for *.example.com

I'm happy to move from Circle to CodeDeploy and Cloudflare to Route53 if it makes this easier. Thanks!

**Comment by iamhopaul123** [comment]
Hello @jaredpalmer. Glad to hear you are trying Copilot. Hopefully our tool is easy enough for the migrating.

In terms of branch deploying I think our pipeline feature allows you to automatically deploy your container application with different branches, and ALB is shared within services deployed in the same environment. Here's an [tutorial](https://aws.amazon.com/blogs/containers/automatically-deploying-your-container-application-with-aws-copilot/) on how to set up Copilot pipeline. Additionally, HTTPS is supported by Copilot and we have an [example](https://github.com/kohidave/dns-and-lb-copilot-demo) for it.

Also, our [website](https://aws.github.io/copilot-cli/) was just available. Feel free to check it out and let us know if there's any question about it!

**Comment by jaredpalmer** [comment]
@iamhopaul123 Ahh I missed the new docs site! Checking it out now.

**Comment by kohidave** [comment]
I think Copilot today is going to be a little awkward with branch deploys / CI today. Let me chat with the team in the morning and try to list the gaps we see and what it'd take to bridge them.

**Comment by jaredpalmer** [comment]
Thanks. I think this is a major feature ppl will want. It’s extremely hard to replicate by hand on AWS at the moment

**Comment by wub** [comment]
Hey everyone, was there any progress in this space? Particularly interested in being able to pass the commit hash to Sentry.

**Comment by Lou1415926** [comment]
Hello @wub! You should be able to create [multiple pipelines](https://github.com/aws/copilot-cli/issues/3231) today with Copilot. You can configure each [pipeline's manifest](https://aws.github.io/copilot-cli/docs/manifest/pipeline/) so that they each source from different branches. 

> Particularly interested in being able to pass the commit hash to Sentry.

I am not very familiar with Sentry - does this happen during `Build` stage? If so, you can probably try reading the environment variable [`CODEBUILD_RESOLVED_SOURCE_VERSION`](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html#CODEBUILD_RESOLVED_SOURCE_VERSION).

**Comment by wub** [comment]
Thanks @Lou1415926! Yes, basically I wanted to pass something generated at build time into an environment variable accessible at runtime.

I did something hacky in the `buildspec.yml`:

1. Installed `yq` after installing copilot
2. Once the .stack.yml files have been generated, I run `yq -i '.Resources.TaskDefinition.Properties.ContainerDefinitions[0].Environment += {"Name": "VERSION", "Value": "'${tag}'"}' ./infrastructure/${svc}-${env}.stack.yml;`

`${tag}` in this case is `$(echo ${CODEBUILD_BUILD_ID##*:}-$env | sed 's/:/-/g' | rev | cut -c 1-128 | rev)`

Obviously not great (as it's hardcoded to the first ContainerDefinition), but this works for us for now.

**Comment by Lou1415926** [comment]
@wub Ah I see! For the specific example you gave, an alternative would be to modify the manifest file before running `copilot svc package` in `buildspec.yml`. You would still need to write something like `yq -i '.variables += {"VERSION":"'${tag}'"}' ./copilot/svc/manifest.yml` to write to the manifest though. 

Perhaps in the future we could support `from_ssm` for `variables` field in manifest. This way, you can write in manifest:
```yaml
variables:
  VERSION:
    from_ssm: build_version
```
and in buildspec, update the ssm parameter named `build_version` with `${tag}`. At deployment stage, ECS will fetch the value of that ssm parameter and inject it into the container.
