### ISSUE TITLE
UX improvement: more readable errors for svc init & job init when no app in workspace

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#1543]
Currently, when you try to run `copilot svc init` without an app in the workspace, the error message is super opaque. 

```
$ copilot svc init
✘ get application : get application : ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
	status code: 400, request id: 8fb856a1-05c9-4287-b2f9-f78bff564198
```

This happens because the "appName" variable is "" and it's failing a validation check. We should intercept this and fail gently, then prompt customers to run `app init` or `copilot init`.

**Comment by huanjani** [comment]
Currently returning `errNoAppInWorkspace`: `✘ could not find an application attached to this workspace, please run 'app init' first`.
