### ISSUE TITLE
env show dash line should be in the same length as the longest

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#1562]
`$copilot env show`

```
Only found one environment, defaulting to: test
About

  Name              test
  Production        false
  Region            us-west-2
  Account ID        1234567890

Services

  Name              Type
  ----              ----

Tags

  Key                  Value
  ---                  -----
  copilot-application  my-project
  copilot-environment  test
```

Dash line should be in the same length as the longest in the column. For example, dash line in "Key" column should be as long as "copilot-application".

**Comment by nao-kagayaki** [comment]
Hi @iamhopaul123

This is my first time to contribute to the OSS, but I would like to submit a PR for this simple issue to fix at first.
