### ISSUE TITLE
[Question] How can we specify cpu and memory limit to one off tasks

### ISSUE THREAD

**Issue by ye-lin-aung** [aws/copilot-cli#1563]
Hi, 
How can we specific the cpu and memory for one-off tasks. Is there any env variables or options to do that? Is there any one line command to specify that ?

 copilot task run      \
  --default             \
  --follow              \
  --image alpine:latest \
  --command "echo 'Howdy, Copilot'"

**Comment by kohidave** [comment]
Yea! You sure can via the `--memory` and `--cpu` flags. So, for example:

```
copilot task run
--default
--follow
--image alpine:latest
--command "echo 'Howdy, Copilot'"
--memory 512
--cpu 256
```

You can read more about task-run and the flags available here: 
https://aws.github.io/copilot-cli/docs/commands/task-run/

Hope that helps!

**Comment by ye-lin-aung** [comment]
Thank you. It works now
