### ISSUE TITLE
How to use with TCP load balancer?

### ISSUE THREAD

**Issue by revmischa** [aws/copilot-cli#1567]
I have a websocket service I'd like to launch with copilot, but I need a TCP/TLS load balancer in front. How can I do this with copilot?

**Comment by efekarakus** [comment]
Heya @revmischa !

Unfortunately, Copilot does not support Network Load Balancers at the moment :(   
We have a tracking issue: https://github.com/aws/copilot-cli/issues/1304 and are making progress towards it in our current sprint but I can't think of a way of unblocking you currently.

**Comment by revmischa** [comment]
Okay thanks. Does it support HTTPS listeners for ALBs? Nobody should be deploying web services without HTTPS these days.

**Comment by efekarakus** [comment]
Yes! with `copilot app init --domain` you can provide an existing domain name and get an HTTPS endpoint. 

Our teammate @kohidave has a tutorial here demonstrating how to get started: https://github.com/kohidave/dns-and-lb-copilot-demo

**Comment by kohidave** [comment]
Yea and to just add on to what Efe mentioned, ALBs support websockets (you can enable session stickiness as well)!

**Comment by revmischa** [comment]
I don't see any configuration for HTTPS though here https://github.com/kohidave/dns-and-lb-copilot-demo/tree/mainline/copilot
I guess it only works when you init the app? What if my app is already created?

**Comment by kohidave** [comment]
Yea :( unfortunately it's not easy to add the DNS after the fact. We have plans on fixing this though:

https://github.com/aws/copilot-cli/issues/1188

**Comment by Lou1415926** [comment]
Hello friends! We have a proposal for supporting network load balancer in #2918. Please Feel free to take a look - we'd love to hear your thoughts!

**Comment by efekarakus** [comment]
NLB support was released for "Load Balanced Web Service" in v1.14 🥳 https://github.com/aws/copilot-cli/releases/tag/v1.14.0 with TCP/TLS!
