### ISSUE TITLE
Support for Github provider v2 in pipeline

### ISSUE THREAD

**Issue by princepathria97** [aws/copilot-cli#1575]
`copilot pipeline init` uses GitHub provider v1 as pipeline source which is not recommended for CodePipeline.
Please add support for Github provider v2 which uses AWS CodeStar connections.
ref. https://docs.aws.amazon.com/codepipeline/latest/userguide/connections-github.html

**Comment by kohidave** [comment]
Hi there! Thanks so much for reaching out. 

Yea, we need to move off of the polling GH source action. We're tracking our move to CodeStarConnections here: https://github.com/aws/copilot-cli/issues/1339

Appreciate you taking the time to reach out!

**Comment by huanjani** [comment]
@princepathria97-- Just in case you missed it, Copilot started using GitHub provider v2 with our last release! 
https://github.com/aws/copilot-cli/releases/tag/v1.4.0

Thanks so much for your feedback!
