### ISSUE TITLE
copilot svc deploy keep running due to task healthcheck failure

### ISSUE THREAD

**Issue by sanjeevtejyan** [aws/copilot-cli#1580]
when svc deploy is triggered and if task failed to run due to some issue in underlying code and healthcheck, then its keep failing for a long time. If command is terminated manually and retry the copilot svc deploy then it will fail as stackset update is in progress and it will run for hours. Thus one has to manually give command to rollback the stackset update. There should be ability to set the time limit on svc deploy and if within that time deployment is not carried out then stackset update rollback to be executed and svc deploy report the deployment failure.

**Comment by Nogbit** [comment]
I would second this and add that there should be something we can configure ([I don't see it here](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/)) the max amount of times ECS will attempt to restart and fail the container.

**Comment by Nogbit** [comment]
As a temporary solution...

Don't CTRL+C to cancel the copilot command that is stuck.  

To get your copilot CLI to exit as it normally would (as it does on a successful deployment) you can do the following steps in your ECS cluster.  This will result in your stack being cleaned up as well and not leaving you in limbo for hours like @sanjeevtejyan said.

1. Go to the task definition for your service
1. Click the checkbox for the newest revision (the one with the number that is failing)
1. Actions Menu - Update Service
1. Set the "number of tasks" to zero
1. Click next until you can click "update service"
2. Very shortly you will see the copilot CLI and CF stack back to normal

**Comment by Mihailoff** [comment]
> Don't CTRL+C to cancel the copilot command that is stuck.

I wish I knew this before ;)

I think this is a fairly simple feature that will improve UX for newbies like me 1) listen for CLI process signal 2) send the CloudFormation "cancel" command https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn--stack-update-cancel.html

Here is an edge case -- what if I accidentally started the deployment and want to cancel it?

> Actions Menu - Update Service

This is the beauty of copilot -- you can manage things yourself, a healthy balance between magic and clarity!

**Comment by ssyberg** [comment]
The cancel-create-stack doesn't work if you're stuck in CREATE_IN_PROGRESS (which I have been for 20 minutes now) - what is the proper way to stop this?

**Comment by KollaAdithya** [comment]
Hello @sanjeevtejyan  @Nogbit @Mihailoff @ssyberg 
Ctrl-C feature is released in [v1.30](https://github.com/aws/copilot-cli/releases/tag/v1.30.0) 🎉 . You can now cancel your stack update to rollback to previous configuration.
