### ISSUE TITLE
Buildpack support

### ISSUE THREAD

**Issue by mwarkentin** [aws/copilot-cli#1584]
It would be nice if copilot supported [Cloud Native Buildpacks](https://buildpacks.io/) as an alternative to raw Dockerfiles for container builds. Managing raw Dockerfiles feels like a bunch of undifferentiated heavy-lifting / education for developers.

Some of the features they tout:

```
Advanced Caching
Robust caching is used to improve performance.

Bill-of-Materials
Insights into the contents of the app image.

Modular / Pluggable
Multiple buildpacks can be used to create an app image.

Multi-language
Supports more than one programming language family.

Multi-process
Image can have multiple entrypoints for each operational mode.

Minimal app image
Image contains only what is necessary.

Rebasing
Instant updates of base images without re-building.

Reproducibility
Reproduces the same app image digest by re-running the build.

Reusability
Leverage production-ready buildpacks maintained by the community.
```

**Comment by kohidave** [comment]
We actually have a prototype of this working and are keen on fleshing it out and adding it into Copilot. We don't have a timeline yet but we're super excited for it 😃

**Comment by mwarkentin** [comment]
Very cool!

**Comment by mwarkentin** [comment]
Maybe a dupe of #1081? Should I close?

**Comment by mwarkentin** [comment]
Also, looks like GCP is rolling out broad support for buildpacks: https://cloud.google.com/blog/products/containers-kubernetes/google-cloud-now-supports-buildpacks

Would be nice if AWS offered similar support in its managed services! 😊

**Comment by efekarakus** [comment]
> Maybe a dupe of #1081? Should I close?

Sure that sounds good! Thanks :) 


> Also, looks like GCP is rolling out broad support for buildpacks: https://cloud.google.com/blog/products/containers-kubernetes/google-cloud-now-supports-buildpacks
> 
> Would be nice if AWS offered similar support in its managed services! 😊


Yes, this feature is definitely on our roadmap :)

**Comment by mwarkentin** [comment]
Closing as duplicate of #1081
