### ISSUE TITLE
Docker composer?

### ISSUE THREAD

**Issue by dinnouti** [aws/copilot-cli#1598]
Is it possible to user docker composer with copilot? If yes, is there an example?

**Comment by bvtujo** [comment]
Hi @dinnouti, Docker Compose currently doesn't integrate with Copilot; however, you can use the [ECS integration in the `docker-compose` cli](https://docs.docker.com/engine/context/ecs-integration/) to run containers on ECS using docker compose syntax! 

If you specifically need to use `docker compose` to run tasks in the cloud, that's your best bet! If you just want a simple interface to get your services up and running quickly and don't need the detailed customization that compose offers, well, Copilot is pretty great at that 😄

**Comment by dinnouti** [comment]
Thanks!
