### ISSUE TITLE
REST api support for Copilot

### ISSUE THREAD

**Issue by sundarnarasiman** [aws/copilot-cli#1605]
Many GSI and ISV partners have built their own Container Management Platforms on top of Amazon ECS. The GSI partners are ready to augment their Container Management Platforms with Copilot features. However they don’t want to complete replace their home-grown container management platforms with Copilot. The best solution is to marry both the worlds. If Copilot can expose its functionalities (CRUD operations) around environment, application, services, storage and pipeline objects as RESTful APIs, it will be a win-win, big boost for these platforms and as well as increases adoption of ECS through Copilot.

**Comment by efekarakus** [comment]
Closing this issue in favor of: https://github.com/aws/copilot-cli/issues/1642 as a duplicate.
