### ISSUE TITLE
Running Copilot init second time gives error

### ISSUE THREAD

**Issue by sundarnarasiman** [aws/copilot-cli#1606]
This is during the scenario of running Copilot init command. We can run 'copilot init' command on a completely developed co-pilot application, like the voting app below.

Voting app
-------------
https://github.com/copilot-example-voting-app/vote
https://github.com/copilot-example-voting-app/results
https://github.com/copilot-example-voting-app/api

If we run the 'copilot init' second time it fails, after successful first ‘copilot init’ execution on the same AWS account number for that application. The second attempt can be on same desktop environment or different desktop environment. Basically it's checking for existence of certain IAM roles. If it already exists, copilot thinks that the app is previously setup and it fails. This needs to be fixed. This is a valid use case. Because a development team can have a single Copilot/ECS application, which needs to be set up by multiple developers in their own desktop environment (MacOS/Linux/Win10).

**Comment by sundarnarasiman** [comment]
This is a valid use case.

**Comment by efekarakus** [comment]
Heya @sundarnarasiman what's the error message that you see?

**Comment by efekarakus** [comment]
Closing due to lack of response please feel free to re-open!
