### ISSUE TITLE
  Missing ls, package, deploy, delete, show, status and logs for svc commands

### ISSUE THREAD

**Issue by sundarnarasiman** [aws/copilot-cli#1611]
Currently Copilot only supports init commands on storage object. It does not support other commands such as ls, package, deploy, delete, show, status and log like other Copilot objects. This features needs to be implemented ASAP. The persistence is such a key aspect of every micro-service. Nowadays no microservice is without persistence. This feature needs to be implemented ASAP.

**Comment by iamhopaul123** [comment]
Hello @sundarnarasiman, thank you for your suggestion! Storage is considered as an addons module in Copilot, and under the hood addons is in a nested stack to the main workload (service, job). That's the reason why we don't have those commands for storage. However, part of the info about addons is shown in the `svc show` and the logs of the addons will reside in `svc logs`.
