### ISSUE TITLE
Copilot integration with container insights

### ISSUE THREAD

**Issue by sundarnarasiman** [aws/copilot-cli#1614]
Currently Copilot Logs are integrated with ECS Task logs or Docker logs. It's not integrated with CloudWatch Container Insights. We need this capability. This will be very useful for DevOps Engineers and Cloud Infra Specialists.

**Comment by sundarnarasiman** [comment]
Any updates on this one ?

**Comment by efekarakus** [comment]
This feature was released in v1.14! https://github.com/aws/copilot-cli/releases/tag/v1.14.0 🎉
