### ISSUE TITLE
Copilot service/job won't get updated when using image with latest tag

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#1621]
Copilot currently won't be able to update the service/job if users specify any existing image URL with `latest` tag. The reason is because the URL doesn't change and always remain `latest` as its tag. One workaround is to avoid using `latest` tag. From our side introducing `--force` flag would help to some degree.

Related to #1400

**Comment by Lou1415926** [comment]
Closed via https://github.com/aws/copilot-cli/pull/2736
