### ISSUE TITLE
Provision to get inputs on Task Size while creating ECS

### ISSUE THREAD

**Issue by rajikrishnamoorthy** [aws/copilot-cli#1625]
Services requiring medium to high memory compute fail to get created during **_copilot init_** command since the CPU and Memory is defaulted to 256 units and 512 MB respectively. Once **_init_** command runs completely, we need to update the manifest.yml which in turn updates the task definition to bring up the ECS service. It would be good if **_copilot init_** can ask for CPU and Memory in the command line while creating.

**Comment by bvtujo** [comment]
Hi @rajikrishnamoorthy, we intend `copilot init` to be a quick, streamlined initialization experience for customers who are new to the tool, or just want to get up and running quickly. Under the hood, though, it runs: 
```
$ copilot app init
$ copilot env init
$ copilot svc init
$ copilot svc deploy
```

Would it work for your use case to just run `copilot app init`, `copilot env init`, then `copilot svc init`, then update the manifest and run `copilot svc deploy`?

**Comment by rajikrishnamoorthy** [comment]
Yes @bvtujo, that would work. Thanks for the tip 👍
