### ISSUE TITLE
ECS health check grace period

### ISSUE THREAD

**Issue by rajikrishnamoorthy** [aws/copilot-cli#1626]
Some types of services need more than 60 seconds to come up, manifest.yml does not have a place holder for health check grace period. After **_copilot init_** completes and ECS fails to come up, we need to manually update the parameter in the ECS console.

**Comment by huanjani** [comment]
Hello @rajikrishnamoorthy! Thanks for opening this issue. 

We have just implemented the option to customize health checks in the Copilot manifest, handling the very situation you describe (https://github.com/aws/copilot-cli/pull/1592). The PR has been merged and will be available in our next release.

Please let us know if there's anything else you'd like to see from Copilot!

**Comment by rajikrishnamoorthy** [comment]
Thank you @huanjani , this is great!

**Comment by efekarakus** [comment]
This was released in v0.6.0 https://github.com/aws/copilot-cli/releases/tag/v0.6.0 happy building! 🚀
