### ISSUE TITLE
Target group - Time out and Interval parameters configuration

### ISSUE THREAD

**Issue by rajikrishnamoorthy** [aws/copilot-cli#1627]
The manifest.yml created by copilot init does not have a provision to specify the Targetgroup health check settings - Timeout and Interval. One has to manually update the target group settings, many services do need more than 5 seconds for timeout. Would be good if these parameters can be made configurable.

**Comment by huanjani** [comment]
Hello again, @rajikrishnamoorthy! 

The [PR](https://github.com/aws/copilot-cli/pull/1592) mentioned in https://github.com/aws/copilot-cli/issues/1626 includes Timeout and Interval settings. The PR has been merged and will be available in our next release. We're excited that this functionality will be useful to Copilot users! 

Thanks!

**Comment by efekarakus** [comment]
This was released in v0.6.0 https://github.com/aws/copilot-cli/releases/tag/v0.6.0 happy building! 🚀
