### ISSUE TITLE
Copilot exposing Rest API

### ISSUE THREAD

**Issue by rajikrishnamoorthy** [aws/copilot-cli#1642]
Hi,
Is there a plan to have copilot expose its capabilities via REST APIs?
If we want to build custom container management platforms , calling copilot commands through APIs would easily enable us to create User Interfaces. Teams can initialize and deploy ECS services through this UI, they need not be proficient with the commands.

**Comment by efekarakus** [comment]
Heya @rajikrishnamoorthy !

Currently, it's possible to write automation around Copilot by providing the necessary information via flags, for example:
```sh
copilot app init my-app
copilot env init -n test --profile test --default-config
```
I assume by a REST API you mean being able to create high-level abstractions like a "Load Balanced Web Service" that Copilot provides but it's managed by AWS? If so I can pass along this information to our teammates.  
But I'd expect this to be out-of-scope for Copilot. Copilot aims at being a _command line interface_ on top of existing AWS services to make building, releasing and operating containerized applications easy. If a new AWS service is released that'd help building containerized apps that'd fall in the scope of Copilot and we should be able to integrate with it.
