### ISSUE TITLE
svc status: error messaging could be more specific

### ISSUE THREAD

**Issue by huanjani** [aws/copilot-cli#1658]
If a user specifies svc and env with flags for `svc status` and the indicated service isn't actually in the indicated environment, the error message received is about the app, not the env. 
Seems like we could/should have different error messages for the two different scenarios.

```
% copilot svc status --name acorn --env test   
✘ select deployed services for application sample: no deployed services found in application sample
```
(applies to both `status` and `logs`)

**Comment by huanjani** [comment]
Update: this error message does seem to exist but isn't being reached in the above scenario.
https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/term/selector/selector.go#L225

**Comment by iamhopaul123** [comment]
> Update: this error message does seem to exist but isn't being reached in the above scenario.
https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/term/selector/selector.go#L225

This is just to check if the svc is deployed in the env. It will return `false, nil` if the svc is not deployed to that env. I think for this scenario we can update the [error message](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/term/selector/selector.go#L248) to be either

1. more general to fit in scenarios regardless `svc` and `env` flag are set or not
2. more specific and adjusted according to different flag set scenarios

**Comment by huanjani** [comment]
No longer an issue. Closing!
