### ISSUE TITLE
Utilizing Copilot CLI to integrate with Bamboo builds

### ISSUE THREAD

**Issue by gopalc-cap** [aws/copilot-cli#1680]
Feedback:
1.	Copilot looks very useful and easy to use tool which saves efforts of writing scripts and configuring resources in the AWS! 
2.	Copilot does not work with root account. It needs be IAM user account to build and deploy from local.
3.	Docker desktop software also needs to be deployed on local machine to build the image. I have not observed list of all pre-requisite tool on readme docs.
4.	How to customize the default settings and configurations of ports, VPC, ECS and all other resources?
5.      One of our requirement is :Integrate Copilot with Bamboo to build and deploy docker images on AWS seamlessly. Developers do not execute Copilot CLI in given restricted environment. Need detailed information and steps how to perform Copilot integration with Bamboo builds

**Comment by efekarakus** [comment]
Heya @gopalc-cap !

> 3. Docker desktop software also needs to be deployed on local machine to build the image. I have not observed list of all pre-requisite tool on readme docs.

Thanks for pointing this out, we should update our docs to make it more explicit.

> 4. How to customize the default settings and configurations of ports, VPC, ECS and all other resources?

When you run `copilot env init` to create an [environment](https://aws.github.io/copilot-cli/docs/concepts/environments/), Copilot will ask you whether you want to import an existing VPC or customize it. So you can configure the CIDR blocks in your VPC.

For ports and other service specific configuration, Copilot will generate an infrastructure-as-code file called a manifest. For example, https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/ is the manifest for an internet-facing service. You can configure the [`port`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-port), add [`autoscaling`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#count) or customize [env variables](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#variables) and other fields!

> Integrate Copilot with Bamboo

I'm not familiar with Bamboo, but it's possible to automate all the steps that Copilot provides by using flags, for example:
```
copilot app init my-app
copilot env init -n test --app my-app --profile test-profile --default-config 
```
So to automate deployments if it's possible to write your own custom script then it should be possible to use Copilot!
