### ISSUE TITLE
Unable to deploy HTTP Listener

### ISSUE THREAD

**Issue by ryanvade** [aws/copilot-cli#1687]
I've been trying to deploy a test project and keep getting the following error in Cloud Formation: 
`Invalid request provided: AWS::ElasticLoadBalancingV2::Listener Validation exception` when deploying the HTTP Listener. 

Steps to Reproduce: 
1. `copilot init`
2. fill in name, choose Load Balanced Web Service
3. Choose this dockerfile:
```
FROM nginx

EXPOSE 80
```
4. Choose `yes` to deploy a test environment. 

Verson: `version: v0.5.0, built for linux`

**Comment by efekarakus** [comment]
Hi @ryanvade ! That's very strange, can you try to deploy it with the latest version v0.7.0 to see if you get the same error?

**Comment by ryanvade** [comment]
After upgrading to 0.7.0 I now get this error when trying to create a test environment. 

```
➜ copilot env init
What is your environment's name? test
Which credentials would you like to use to create test? Enter temporary credentials
What's your AWS Access Key ID? 
What's your AWS Secret Access Key? 
What's your AWS Session Token? 
Would you like to use the default configuration for a new environment?
    - A new VPC with 2 AZs, 2 public subnets and 2 private subnets
    - A new ECS Cluster
    - New IAM Roles to manage services and jobs in your environment
 Yes, use default.
✘ Failed to create the infrastructure for the test environment.
- Virtual private cloud on 2 availability zones to hold your services and jobs                                                                     [Failed]
  Resource creation cancelled                                                                                                                               
  - Internet gateway to connect the network to the internet                                                                                        [Failed]
  Resource creation cancelled                                                                                                                               
  - Public subnets for internet facing services and jobs                                                                                           [In Progress]
  - Private subnets for services and jobs that can't be reached from the internet                                                                  [In Progress]
  - Routing tables for services and jobs to talk with each other                                                                                   [In Progress]
- ECS Cluster to hold your services and jobs                                                                                                       [Failed]
  Invalid request provided: CreateCluster Invalid Request: Unable to assume the service linked role. Please verify that the ECS service linked role exists  
✘ wait until stack tryouts-test create is complete: ResourceNotReady: failed waiting for successful resource state
```

**Comment by efekarakus** [comment]
Ah @ryanvade  sorry for the trouble! This happens if it's the very first time we're creating an ECS cluster in the account: https://github.com/aws/copilot-cli/issues/1324

One way to mitigate it is to navigate to the ECS console and creating some "default" cluster or you can run:
```
aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com
```
to unblock this issue (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html)

**Comment by ryanvade** [comment]
@efekarakus I see, that has fixed it. 

Side note, do you know why the storage plugin won't allow 2 character DynamoDB attribute names?

**Comment by efekarakus** [comment]
That's a mistake on our end :D we reused some validation logic for DDB which is extra restrictive.
In the mean time you can provide a longer name temporarily, and then modify the generated cloudformation template to rename the attribute name to a 2 character value like "id" to mitigate the issue
