### ISSUE TITLE
How to customize the default settings and configurations of ports, VPC, ECS and all other resources?

### ISSUE THREAD

**Issue by gopalc-cap** [aws/copilot-cli#1692]
How to customize the default settings and configurations of ports, VPC, ECS and all other resources?

**Comment by huanjani** [comment]
Hi @gopalc-cap! 

When you `init` your service, a `manifest.yml` file is created for you in the `copilot` directory. In that file, you can customize fields like port. When you then `deploy`, those customizations are implemented. (See https://aws.github.io/copilot-cli/docs/manifest/overview/ and the other manifest docs for specifics.)

For environment-related config, you may customize those when you run `copilot env init`. (See https://aws.github.io/copilot-cli/docs/concepts/environments/ for more detail.)

I hope that helps; let us know if you have more questions!
