### ISSUE TITLE
Application load balancer

### ISSUE THREAD

**Issue by vikasgoel76** [aws/copilot-cli#1697]
Copilot does not support customization of application load balancer

**Comment by efekarakus** [comment]
@vikasgoel76 
Heya! you can customize to a certain extend ALB fields by modifying the manifest file for a Load Balanced Web Service under the `http` field: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http

Were you looking to customize other properties? Please feel free to open if the above fields don't satisfy your usecases 🙏
