### ISSUE TITLE
Support windows containers

### ISSUE THREAD

**Issue by vikasgoel76** [aws/copilot-cli#1700]
Copilot does not provide support for windows containers

**Comment by sundarnarasiman** [comment]
Hi Vikas,

Can you elaborate more on the windows container requirement ?

**Comment by jasonumiker** [comment]
Agree that now that Fargate supports Windows Containers it'd be good if copilot could as well...

**Comment by efekarakus** [comment]
Hi @jasonumiker Copilot does! Here is a blog post by @huanjani showcasing it: https://aws.amazon.com/blogs/containers/streamline-windows-container-deployment-on-amazon-ecs-with-aws-copilot-and-aws-fargate/


It was added in the latest release: https://github.com/aws/copilot-cli/releases/tag/v1.12.0

**Comment by efekarakus** [comment]
Closing the issue! Let us know if you have any feedback 😃

**Comment by jasonumiker** [comment]
Works great! It even auto-detected that it was Windows from the Dockerfile's FROM line which surprised/impressed me. Maybe you just should highlight this a bit more clearly as a feature in the documentation (because I looked through and didn't realize it was).
