### ISSUE TITLE
Copilot missing features for ECS  

### ISSUE THREAD

**Issue by avvaidya-aws** [aws/copilot-cli#1708]
Integration with other AWS services e.g. EBS EFS Windows container NLP will really help to make this better suited for enterprise workloads.

**Comment by efekarakus** [comment]
There are already existing issues for each one of these items, please give a 👍 and/or comment to these individual issues if you'd like it supported in copilot.
1. #1700
2. #1094
3. Not supported for Fargate launch type.
4. #1559 
5. This is supported with `env init` right now.
6. #1304 

Thanks!
