### ISSUE TITLE
Single pipeline for infra creation

### ISSUE THREAD

**Issue by avvaidya-aws** [aws/copilot-cli#1709]
cross regions (Including China) spread across multi AWS accounts i.e. Single Pipeline which can create environment for dev, stage, prod, DR… in different AWS regions provisioned under different AWS accounts.

**Comment by efekarakus** [comment]
This is supported with copilot! (not China yet though) 
When you run `env init` you can choose which AWS profile to use to create the environment stack in. The profile points to a specific aws account and region and the pipeline generated with `pipeline init` will deploy across accounts and regions.
