### ISSUE TITLE
IDE Integration

### ISSUE THREAD

**Issue by avvaidya-aws** [aws/copilot-cli#1714]
Integration with Id's like Visual  Studio code, Eclipse, PyCharm  and IntelliJ will help

**Comment by efekarakus** [comment]
What type of integration are we looking for ? Copilot creates YAML files as manifest to represent a service/job. 
Are we looking to have intellisense for it? This is a duplicate of https://github.com/aws/copilot-cli/issues/1609 we would appreciate additional details in the issue.
