### ISSUE TITLE
Jenkins/Spinnaker support

### ISSUE THREAD

**Issue by avvaidya-aws** [aws/copilot-cli#1715]
Jenkins/Spinnaker support will help at enterprise level.

**Comment by efekarakus** [comment]
Please comment on #1339 for additional pipeline related support. 
Is there a particular reason why AWS CodePipeline cannob be used? Thank you!

**Comment by sundarnarasiman** [comment]
Hi Efe,

Most of the customers does not use AWS Code* services for DevOps. Commonly lot of customers rely on open source tools like Jenkins/Spinnaker. There is a good amount of customers using Atlassian Bamboo (or) Gitlabs products as well.

Among these list, Jenkins and Bamboo are very popular and highly adopted. In our next evolution of pipeline support, we should support one of these tools based on data points.
