### ISSUE TITLE
copilot env init does not see existing subnets.

### ISSUE THREAD

**Issue by youngfeldt** [aws/copilot-cli#1724]
VPC has 2 public and 2 private subnets.
All are visible with profile used, yet "copilot env init" with arguments and with prompts, fails to acknowledge subnets.

See detail below:

$  copilot env init
What is your environment's name? dev
Which credentials would you like to use to create dev? [profile ec_copilot]
Would you like to use the default configuration for a new production environment?
    - A new VPC with 2 AZs, 2 public subnets and 2 private subnets
    - A new ECS Cluster
    - New IAM Roles to manage services in your environment
 No, I'd like to import existing resources (VPC, subnets).
Which VPC would you like to use? vpc-084303080a6fd9ea2
✘ No existing public subnets were found in VPC vpc-084303080a6fd9ea2. You can either:
- Create new public subnets and then import them.
- Use the default Copilot environment configuration.✘ select public subnets: no existing subnets found
$
$ aws --profile ec_copilot ec2 describe-subnets --filters Name=vpc-id,Values=vpc-084303080a6fd9ea2 --query 'Subnets[].{Name:Tags[?Key==`Name`]|[0].Value,Subnetid:SubnetId,VpcID:VpcId}' --output text
Private Subnet  subnet-062b4e7f3cfb95007        vpc-084303080a6fd9ea2
Private subnet  subnet-03c13da51c8844ae0        vpc-084303080a6fd9ea2
Public Subnnet  subnet-031805325a522ba69        vpc-084303080a6fd9ea2
Public subnet   subnet-0d452e2620153c98f        vpc-084303080a6fd9ea2

**Comment by youngfeldt** [comment]
Role had read-only permissions.  I then gave it AdministratorAccess and have same results.

**Comment by bvtujo** [comment]
Hi @youngfeldt, we filter on public subnets in Copilot by checking whether the subnet has the `MapPublicIPOnLaunch` property enabled. Could that be the blocker here? We control access from the internet by security groups, not subnet isolation. 

You can change this setting in the console from a subnet's page by clicking Actions, then "Modify auto-assign IP settings," or in your IAC definitions.

**Comment by youngfeldt** [comment]
Thanks for explaining.   I guess its understandable that opinionated assumptions like this will be necessary to move forward quickly.   I'll revist later when the product has matured.   I can not sacrifice security layers for convenience.
It is a good looking direction though.  I look forward to seeing it when it is more configurable.

**Comment by iamhopaul123** [comment]
Hello @youngfeldt. I'm sorry Copilot currently doesn't meet your security requirement. As @bvtujo put we use security group to limit internet access to the public subnets. Could you tell us what security layers do you need and what configurable option are you looking for?

**Comment by iamhopaul123** [comment]
Hello @youngfeldt! We now support launching tasks in private subnets with imported VPC. I wonder if it helps anyway. Here's the link to the doc: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network.
