### ISSUE TITLE
Directory/

### ISSUE THREAD

**Issue by niros1** [aws/copilot-cli#1727]
Hi,
I have a copilot application with several services Iv'e create in a repository, I would like to migrate the code, the application and the services to another repository (git), I tried to copy/paste the directory contain the services directory, copilot directory and .workspace file but it doesn't seems to work.
When I tried to do copilot svc deploy I get an error "could not find an application attached to this workspace, please run `app init` first", so I did run app init and choose the existing application but then when I tried to deploy I get this error "select service: no services found".
when I tried `copilot app show` I do see the services under the application.

Is there any migration guidance/docs?

on the same matter but a bit different, is it possible to migrate a specific service from one application to another ?

10X in advance.

**Comment by efekarakus** [comment]
Heya @niros1 !

Mmm this is interesting 🤔 
If I'm understanding right, you already have an existing application but you'd like to just move all your source code to a different repo.

Where are you running `copilot svc deploy` from? If your directory structure looks like:
```
my-repo/
|── copilot
│    ├── .workspace
│    └── my-svc
│        └── manifest.yml
└── Dockerfile
```
Can you try running `copilot deploy` from where the same level as the `copilot/` directory?
Are you using the same credentials to initialize the application from the new repo as the old repo?

> is it possible to migrate a specific service from one application to another ?

Unfortunately there is no command to achieve that at the moment. A three-step process would be:

1. Copy the `my-svc/manifest.yml` file to the new app's repo under `new-app/copilot/my-svc/` and run `copilot svc init` again to register the "my-svc" with "new-app".
2. Run `copilot deploy` to deploy "my-svc" in "new-app".
3. Finally, delete "my-svc" from "old-app" by navigating to the old-app's repo and running `copilot svc delete`.

**Comment by niros1** [comment]
Hi, 
running the deploy command within copilot directory works just fine, this is weird cause in the initial project I used to run it in the upper level.
As for the other part, I will try this flow. 
10X a lot.

**Comment by efekarakus** [comment]
Awesome great to hear! I'll close the issue now :) feel free to re-open it if you run into another issue.
