### ISSUE TITLE
Circuit breaker support

### ISSUE THREAD

**Issue by mifisignal** [aws/copilot-cli#1735]
As soon as [Circuit Breaker Support](https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/) is available in CloudFormation, Copilot should support it.

**Comment by efekarakus** [comment]
Definitely, that's such an awesome feature!

**Comment by efekarakus** [comment]
This was released in v1.1.0 https://github.com/aws/copilot-cli/releases/tag/v1.1.0!
