### ISSUE TITLE
Dockerfile auto detect when creating service.

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#1748]
Copilot's auto-detecting of the dockerfile is case sensitive. In my case, all our files are lowercase "dockerfile" which doesn't get detected. If you capitalize the D to "Dockerfile" auto detection works and you don't have to specify a path. I thought this was a little odd and maybe an easy thing to update.

**Comment by efekarakus** [comment]
Hi @h5aaimtron thanks for the feedback! I moved the issue to our backlog to fix this behavior

**Comment by efekarakus** [comment]
This was released just now in v1.1.0: https://github.com/aws/copilot-cli/releases/tag/v1.1.0!
