### ISSUE TITLE
Announcement should link to v1.0.0 

### ISSUE THREAD

**Issue by motatoes** [aws/copilot-cli#1751]
[The copilot announcement](https://aws.amazon.com/blogs/containers/introducing-aws-copilot/) has some installation instructions and within the article the installation instructions are linking to v0.0.1. This version of the cli is lacking many great features in v1.0.0 and therefore the article should instead to the latest version to avoid frustrations of someone using that version then having to upgrade his environment.

```
curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/download/v0.1.0/copilot-darwin-v0.1.0 &&
  chmod +x /usr/local/bin/copilot &&
  copilot --help
```

**Comment by nathanpeck** [comment]
Thanks for the callout! I updated my blogpost to include the latest install instructions!
