### ISSUE TITLE
Add option to show failed tasks in `svc status`

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#1763]
Right now, when you run `copilot svc status` it shows you the running tasks which is great. It'd be awesome for debugging to have a flag, maybe `--with-stopped` that showed the stopped tasks, and why they were stopped.

**Comment by efekarakus** [comment]
This is now out in v1.8.0 🥳 https://github.com/aws/copilot-cli/releases/tag/v1.8.0
