### ISSUE TITLE
Repository names with capital letters break tasks

### ISSUE THREAD

**Issue by lukeledet** [aws/copilot-cli#1775]
My repo name is all caps like https://github.com/org/APP. This hasn't been an issue until trying to run a task. In CF I get this error for the `ECRRepo` step: `Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])`. RepositoryName is the TaskName parameter combined with "copilot-". Would it be a problem to lowercase the repo name when using it for the TaskName?

**Comment by efekarakus** [comment]
heya @lukeledet ! good idea, we'll fix this on our end.
In the mean time to mitigate the issue, you can use the `-n, --task-group-name` flag and pass in `-n app` (lowercase) and I think that should unblock you.

**Comment by lukeledet** [comment]
I didn't know `-n` would help here, thanks @efekarakus !

**Comment by efekarakus** [comment]
Merged a fix in #1784 it should go out next release 🐛 🔨

**Comment by efekarakus** [comment]
This was released just now in v1.1.0: https://github.com/aws/copilot-cli/releases/tag/v1.1.0!
