### ISSUE TITLE
Backend without healthcheck keeps restarting

### ISSUE THREAD

**Issue by sinedie** [aws/copilot-cli#1776]
Hey there, I have a celery worker on a container. It doesn't serve any api so can't provide any healcheck.

The only way a service in the application communicates to this worker is via message queue.

When deployed with copilot, this services keeps restarting every... 2min max?. I guess it is the healthcheck -cause the logs doesn't show any error-

![image](https://user-images.githubusercontent.com/43920544/102864987-169e5d00-4403-11eb-8d32-4b553265aaad.png)

I need -obligatory- set an api to such service? Ty for the help

**Comment by efekarakus** [comment]
Heya @sinedie 👋 
You shouldn't need to provide container healthchecks for a backend service.
Would you mind checking what's the stopped reason for the tasks that are stopping?

You can view it from the console:
![Screen Shot 2020-09-09 at 9 03 33 AM](https://user-images.githubusercontent.com/879348/92623682-6f465180-f27b-11ea-87c7-32284f7d2658.png)

Let us know what you find out and we'll try our best to help from there!

**Comment by sinedie** [comment]
Heya.

Yeah... in the stopped tasks saw the error.

I was trying this: https://github.com/aws/copilot-cli/issues/1756#issuecomment-748554759 but still seems like I don't have permission

`[2020-12-22 19:18:10,437: CRITICAL/MainProcess] Unrecoverable error: ClientError('An error occurred (AccessDenied) when calling the ListQueues operation: Access to the resource https://queue.amazonaws.com/ is denied.'`

But thats other issue. Gonna close this one.

PD: Idk why I couldn't see those logs in copilot, but all good. Ty for your help. :D

**Comment by iamhopaul123** [comment]
Hi @sinedie I think this should be related to https://github.com/aws/copilot-cli/issues/1763. Adding this feature will surface those tasks stop reasons to users, which might be useful for debugging.
