### ISSUE TITLE
Image healthcheck not propagated to TaskDefinition

### ISSUE THREAD

**Issue by guikcd** [aws/copilot-cli#1795]
During doing experiment with copilot (with the getting started sample app), i noticed that the svc status output for Health Status was `UNKNOWN`:

```
$ copilot svc status --name api --env test
Service Status

  ACTIVE 1 / 1 running tasks (0 pending)

Last Deployment

  Updated At         2 minutes ago
  Task Definition    arn:aws:ecs:eu-west-1:123456789:task-definition/demo-test-api:7

Task Status

  ID                Image Digest        Last Status         Started At          Stopped At          Health Status
  e26da25c          687a129b            RUNNING             3 minutes ago       -                   UNKNOWN

[...]
```
I've tried to change to use `image.healthcheck.command` in `copilot/api/manifest.yml` but the status always remained `UNKNOWN`.
Tried many values in the field, but my understanding is that the field is never propagated in ECS task.

In the ECS task (via AWS console), the `healthCheck` block is always empty:

```
$ task_definition=$(copilot svc show --resources --name api | grep TaskDefinition | awk '{print $NF}')
$ aws ecs describe-task-definition --task-definition ${task_definition} --query 'taskDefinition.containerDefinitions[].healthCheck'
null
```
If i modify the task manually in the console by setting the container healthCheck to `CMD-SHELL, curl -f http://127.0.0.1 || exit 1`, it works as expected:

```
$ task_definition="arn:aws:ecs:eu-west-1:123456789:task-definition/demo-test-api:8"
$ aws ecs describe-task-definition --task-definition ${task_definition} --query 'taskDefinition.containerDefinitions[].healthCheck'
[
    {
        "command": [
            "CMD-SHELL",
            "curl -f http://127.0.0.1 || exit 1"
        ],
        "interval": 30,
        "timeout": 5,
        "retries": 3
    }
]
```

The status for the service is now healthy on ECS & copilot output:
```
$ copilot svc status --name api --env test
Service Status

  ACTIVE 1 / 1 running tasks (0 pending)

Last Deployment

  Updated At         1 minute ago
  Task Definition    arn:aws:ecs:eu-west-1:123456789:task-definition/demo-test-api:8

Task Status

  ID                Image Digest        Last Status         Started At          Stopped At          Health Status
  3dc657d8          687a129b            RUNNING             3 minutes ago       -                   HEALTHY
[...]
```

The copilot generated CloudFormation template seems to not include the `HealthCheck` property in `AWS::ECS::TaskDefinition` resource (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-healthcheck.html), based on `copilot svc package` output.
I will try to investigate in the code and propose a PR in next few days.

**Comment by efekarakus** [comment]
Hi @guikcd !

If the "api" service is defined as a ["Load Balanced Web Service"](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/) then the [`http.healthcheck`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck) field maps to target group health checks. These unfortunately don't show up as container health checks but instead can be viewed when describing the target group health:
![Screen Shot 2020-12-30 at 8 28 23 AM](https://user-images.githubusercontent.com/879348/103367070-0298d200-4a79-11eb-82c1-dc80cc111d55.png)

However, if the service is defined as a ["Backend Service"](https://aws.github.io/copilot-cli/docs/manifest/backend-service/) then there is no load balancer and the [`image.healthcheck`](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#image-healthcheck) field is used for container health checks. In that situation, `svc status` will show the health status of the task.

At the moment, with "Load Balanced Web Services" you can only define target group health checks and no container health checks. Hope this helps clarify things!

**Comment by guikcd** [comment]
Ok i understand, this is by design and make sense, didn't noticed the differences in the manifests for Backend & Load Balanced services in the manifest documentation!

I will close this, as it is not an issue, thanks for clarifying.

**Comment by tekknolagi** [comment]
@efekarakus where can I find this "Registered targets" list in the AWS console? I am also running into this.

**Comment by iamhopaul123** [comment]
Hello @tekknolagi. You can go to the ECS console and if you click into cluster -> service, and then the target group name

<img width="763" alt="Screen Shot 2022-04-07 at 3 50 19 PM" src="https://user-images.githubusercontent.com/51377557/162332163-46ed7908-6def-4315-858e-f4412eb790a8.png">

After that, you'll see the only target group after filtering and click into it to find the registered targets. Hopefully it is helpful to you!

**Comment by tekknolagi** [comment]
Thanks!
