### ISSUE TITLE
I can't delete my test environment

### ISSUE THREAD

**Issue by Kylir** [aws/copilot-cli#1822]
Hi there!

I'm using copilot version 1.0.0.
I have an issue: I'm not able to delete an environment and I have no idea how to find why.

This is the command and the response I get after 10 or so minutes.

```bash
$ copilot env delete --name test --yes
✘ Failed to delete environment test from application my-application.
✘ delete environment test stack: wait until stack my-application-test delete is complete: ResourceNotReady: failed waiting for successful resource state
```

I wanted to get rid of an application with 3 pipelines, 4 services and 1 RDS (MySQL) instance created on the VPC manually. 
I did an `copilot app delete` and it failed at the environment part.
I deleted the MySQL instance thinking it could somehow interfere and tried again with no more luck.

When I list the environment I got this:

```
$ copilot env show
Only found one application, defaulting to: my-application
Only found one environment, defaulting to: test
About

  Name              test
  Production        false
  Region            eu-west-2
  Account ID        <I removed that info>

Services

  Name              Type
  ----              ----

Tags

  Key                  Value
  -------------------  -------------
  copilot-application  my-application
  copilot-environment  test

```
Do you know what is happening?
Where can I find more info?

Many thanks for the super tool you created!

**Comment by efekarakus** [comment]
Hi @Kylir !

Can you take a look at the "Events" tab for the "my-application-test" stack in CloudFormation? That should help us narrow down the issue. If you scroll down eventually there should be a resource that failed to delete first.

![Screen Shot 2021-01-12 at 4 23 31 PM](https://user-images.githubusercontent.com/879348/104390437-8a0f2800-54f2-11eb-9dcb-1fc393c8979a.png)
_Sample screenshot of the Events tab_

We're actively working on bringing this visibility to the tool atm (https://github.com/aws/copilot-cli/issues/1742)

**Comment by Kylir** [comment]
Ah! Thank you very much! I followed your advice and I found the following:

```
resource sg-0dd4538d0c17bbfc6 has a dependent object (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: 061bc880-b6e7-4bfc-b7b1-06775eb552e1; Proxy: null)
```
And several other errors all pointing to the same EC2 instance.
Looks like I have to delete that instance.

Out of curiosity, I created that EC2 instance to interact with the MySQL database that is interacting with the services (using the VPC and subnets.)
Is there a better way to create DBs and VMs that I can keep even if I delete the Copilot Environments?

Anyway, thanks again for the lightning fast and very helpful response! :+1: 
Feel free to close and I'll reopen if getting rid of the EC2 instance does not solve my issue.

**Comment by efekarakus** [comment]
Ah if the DBs and VMs are created within the Copilot environment VPC, there isn't a way at the moment of deleting the Copilot Environment while retaining the VPC itself.

Until we provide that functionality, maybe a safe way would be to create a VPC outside of Copilot, and then running `copilot env init` and choosing to import an existing VPC. This way when the Copilot environment is deleted the VPC won't be touched.

**Comment by Kylir** [comment]
Ah! This is what I missed! I wanted to create a new app with the `--domain` option.
I assumed I will need to destroy everything and then recreate from scratch! My fault!

**Comment by Kylir** [comment]
A little update: the culprit was a security group I added to the VPC manually and forgot about!
Thanks again for your help!
