### ISSUE TITLE
Adding environment to pipeline fails

### ISSUE THREAD

**Issue by vbarba** [aws/copilot-cli#1824]
Hi,

When you add an stage to the pipeline for deploying in a new environment, if the environment contains services with addons the buildspec.yml file needs to be regenerated. If not, the pipeline fails because the packaged templates haven't been uploaded to the s3 buckets.

I think that something is needed to properly update the buildspec.yml file according the stages of the environment

Regards!

**Comment by efekarakus** [comment]
Thanks for creating the issue @vbarba ! We'll investigate this.

**Comment by DaveCollinsJr** [comment]
I can confirm this issue:

With a *fully working* CodePipeline (generated by Copilot) that deployed to the "test" environment, this line was in buildspec.yml:
```jq --arg a "https://stackset-myapp-i-pipelinebuiltartifactbuc-REDACTED.s3.us-east-1.amazonaws.com/manual/$timestamp/$workload.addons.stack.yml" '.Parameters.AddonsTemplateURL = $a' ./infrastructure/$workload-test.params.json > "$tmp" && mv "$tmp" ./infrastructure/$workload-test.params.json```

Then I changed **pipeline.yml** from ```stages:   name: test```  to ```stages:  name: staging``` and ran **copilot pipeline update**

The buildspec.yml did not get updated, so the next deploy fails with ```Template format error: Unresolved resource dependencies [AddonsStack] in the Resources block of the template (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: REDACTED; Proxy: null)```

Then I manually edited **pipeline.yml** and changed the $workload-test instances to $workload-staging:

```jq --arg a "https://stackset-myapp-i-pipelinebuiltartifactbuc-REDACTED.s3.us-east-1.amazonaws.com/manual/$timestamp/$workload.addons.stack.yml" '.Parameters.AddonsTemplateURL = $a' ./infrastructure/$workload-staging.params.json > "$tmp" && mv "$tmp" ./infrastructure/$workload-staging.params.json```

Committed everything, then the next deploy worked.

It seems to me that the ```for workload in $WORKLOADS; do``` block should *also* be iterating through ```for env in $envs; do```

Thanks

**Comment by efekarakus** [comment]
Hi @DaveCollinsJr 👋 

Thank you so much for troubleshooting this and sorry for the inconvenience 🙇 , your suggestion makes total sense! 

We create the S3 buckets: `stackset-myapp-i-pipelinebuiltartifactbuc-REDACTED` in each region available in your application.
One concern that I can see is if the `staging` environment is in a different region than the `test` environment.
In that situation, besides updating `$workload-staging` we would need to update the S3 Bucket URL as well:

```terminal
jq --arg a "https://{UPDATE_S3_BUCKET_NAME}.s3.{UPDATE_REGION}.amazonaws.com/manual/$timestamp/$workload.addons.stack.yml" '.Parameters.AddonsTemplateURL = $a' ./infrastructure/$workload-{UPDATE_ENV_NAME}.params.json > "$tmp" && mv "$tmp" ./infrastructure/$workload-{UPDATE_ENV_NAME}.params.json
```

Like you  mentioned we should be looping also `for env in $pl_envs;` but then we also need a way of fetching the S3 bucket associated with each environment.

### Proposed solution
1. We can add a new environment variable `COPILOT_PIPELINE_BUCKETS` here:
https://github.com/aws/copilot-cli/blob/c2f5d1324e9f50dcc46d4e31bdf5f6011cff6b0d/internal/pkg/template/templates/cicd/pipeline_cfn.yml#L129-L131
Which will have the following format:
```json
{
  "buckets": [{
     "region": "us-east-1",
     "name": "stackset-myapp-name1",
     "environments": ["test", "staging"]
  }, {
     
     "region": "us-west-2",
     "name": "stackset-myapp-name2",
     "environments": ["prod"]
  }]
}
```
The `buckets` is populated based on the `stages` defined in `pipeline.yaml`.

2. Update the buildspec to use the new env variable here:
https://github.com/aws/copilot-cli/blob/c2f5d1324e9f50dcc46d4e31bdf5f6011cff6b0d/internal/pkg/template/templates/cicd/buildspec.yml#L53-L61

Such as this:
```bash
for bucket in $(echo $COPILOT_PIPELINE_BUCKETS | jq -c .buckets[]); do 
  s3URL="s3://$(echo $bucket | jq -r .name)/"; 
  echo $s3URL; 
  httpsURL="https://$(echo $bucket | jq -r .name).s3.$(echo $bucket | jq -r .region).amazonaws.com/"; 
  echo $httpsURL; 
  for env in $(echo $bucket | jq -r -c .environments[]); do 
    echo "./infrastructure/workload-$env.params.json"; 
  done; 
done;
```

**Comment by efekarakus** [comment]
@DaveCollinsJr PR fixing the buildspec: https://github.com/aws/copilot-cli/pull/2751

**Comment by DaveCollinsJr** [comment]
@efekarakus Yes I can see the issue that multiple regions might cause.  Your solution above looks like it would solve the multi-environment issue.

**Comment by dannyrandall** [comment]
This has been resolved in https://github.com/aws/copilot-cli/pull/3283.
