### ISSUE TITLE
Deploy fails when addons contains Transforms

### ISSUE THREAD

**Issue by vbarba** [aws/copilot-cli#1825]
Hi,

The deploy fails when addons template include Transforms. For example, for secrets manager rotation:

```execute svc deploy: deploy service: wait until stack XXXXX update is complete: ResourceNotReady: failed waiting for successful resource state: S3 error: The specified bucket does not exist```

Regards

**Comment by efekarakus** [comment]
Interesting 🤔 would you mind sharing a sample template that would cause this issue for us to re-create on our end?

**Comment by vbarba** [comment]
Thank you for your help in advance.

Here a Serverless Aurora PostgreSQL template with SecretsManager password rotation:

```
Transform: AWS::SecretsManager-2020-07-23
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::password}}'
      Engine: aurora-postgresql
      EnableHttpEndpoint: true
      EngineMode: serverless
      DatabaseName: !Ref Name
      DBSubnetGroupName:
            Ref: MyDBSubnetGroup
      VpcSecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${App}-${Env}-EnvironmentSecurityGroup"       
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 4
        MaxCapacity: 8
        SecondsUntilAutoPause: 1000
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: "Api Database Subnet Group"
      SubnetIds:
        Fn::Split:
          - ","
          -  Fn::ImportValue:
              !Sub "${App}-${Env}-PrivateSubnets" 
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is my rds cluster secret'
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${Name}"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludePunctuation: true

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref MyRDSInstanceRotationSecret
      TargetId: !Ref RDSCluster
      TargetType: AWS::RDS::DBCluster
      
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment 
    Properties:
      SecretId: !Ref MyRDSInstanceRotationSecret
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSecurityGroupIds:
          Fn::ImportValue:
            !Sub "${App}-${Env}-EnvironmentSecurityGroup"
        VpcSubnetIds:
          Fn::ImportValue:
            !Sub "${App}-${Env}-PrivateSubnets" 
      RotationRules:
        AutomaticallyAfterDays: 30

Outputs:
  DBHOST:
    Description: "Database endpoint"
    Value: !GetAtt RDSCluster.Endpoint.Address
  DB:
    Description: "Database name"
    Value: !Ref Name
  DBUSER:
    Description: "Database username"
    Value: !Ref Name
  DBPORT:
    Description: "Database port"
    Value: 5432
  DBPASS:
    Description: "Database secret password"
    Value: !Join [ "", [ !Ref "MyRDSInstanceRotationSecret", ":password" ] ]
```
Deploying this I get this error:

```: json: cannot unmarshal string into Go struct field Template.Resources of type []string``` 

Works without the `AWS::SecretsManager::RotationSchedule` Resource

Also, I am wondering if the pipeline would add the AUTOEXPAND capability to the stage.

**Comment by efekarakus** [comment]
OK I can confirm that we have fixed this issue already in https://github.com/aws/copilot-cli/pull/1804 :D but it's not yet released. I deployed the stack provided as is to my account: 
![Screen Shot 2021-01-13 at 4 19 54 PM](https://user-images.githubusercontent.com/879348/104528100-34528280-55bb-11eb-853e-6711b8d2431f.png)


We're planning a release early next week so look out for `v1.1.0` 👀 .   

------------

In the mean time to mitigate the issue, I think this might be happening because of an underlying library we previously used that would parse the template wrongly.

**Can you try changing the `DependsOn` field of `MySecretRotationSchedule` to be a list?** like below:
```yaml
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: [SecretRDSInstanceAttachment]
    ...
```

Thanks!

**Comment by vbarba** [comment]
The workaround with the `DependsOn` field did the trick but I am still facing `CAPABILITY_AUTO_EXPAND` error.

With `Transform: AWS::SecretsManager-2020-07-23` line in addon template. I get:

`ResourceNotReady: failed waiting for successful resource state: Requires capabilities : [CAPABILITY_AUTO_EXPAND]`

Without this line, same template works fine.

The generated pipeline also didn't included this `CAPABILITY_AUTO_EXPAND`

Thanks in advance!
