### ISSUE TITLE
environment  --prod flag usage 

### ISSUE THREAD

**Issue by vbarba** [aws/copilot-cli#1851]
According the command-line help there is a flag
```
--prod                           If the environment contains production services.
```
And I am wondering what this flag actually does. I didn't find anything in the doc

Thanks

**Comment by efekarakus** [comment]
Hi @vbarba !

It's not really used for anything at the moment :D Before v1.0, the idea was that the flag could provide a way for customers to decide to keep certain resources if a prod env is deleted. But that can be achieved already right now within addons, using [`Mappings`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) and the `Env` parameter.

In the future, it could provide us a way of listing all your production resources but there is no plan at the moment. It's safe to ignore it :)

**Comment by vbarba** [comment]
ok! thanks!
