### ISSUE TITLE
Export the service physical id or service arn

### ISSUE THREAD

**Issue by bennyderickm** [aws/copilot-cli#1864]
If a user wants to build or refer the local services via AWS Cloud Map to API Gateway via VPC link then we need to use the server arn.  Currently, this can be done in UI on API Gateway.  In order to use this on AWS Cloudformation template the service stack created by copilot needs to export the DiscoverServcie ARN.

**Comment by efekarakus** [comment]
This is now released in https://github.com/aws/copilot-cli/releases/tag/v1.2.0!

**Comment by sekamaneka** [comment]
How do we use this in the nested addon stack? or is there a way to create an extra CF stack?
