### ISSUE TITLE
multiple containers behind load balanced web service

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#1878]
We have a scenario where we're running multiple Fargate services behind a single load balancer and using paths to route to them. Is this a scenario that could be supported with copilot? If not, consider this a feature request.

**Comment by iamhopaul123** [comment]
Hello @bpottier, if you create multiple Copilot [load balanced web services](https://aws.github.io/copilot-cli/docs/concepts/services/) in the same [application](https://aws.github.io/copilot-cli/docs/concepts/applications/) and deploy them to one [environment](https://aws.github.io/copilot-cli/docs/concepts/environments/), then you'll have a single load balancer and using paths to route to those services. You can also edit the [path](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-path) for each of the service in the manifest before deploying it.

**Comment by bpottier** [comment]
That's great! Thank you.
