### ISSUE TITLE
Release Roadmap / build from master

### ISSUE THREAD

**Issue by sekamaneka** [aws/copilot-cli#1900]
Hello,

is there a way to build from the latest source locally? I need some changes that are not released yet.
If that isn't possible could we get an approximate release schedule?

**Comment by efekarakus** [comment]
Hi @swilso793 ! 

To build the CLI locally you'd need to install [go](https://golang.org/dl/) and [nodejs](https://nodejs.org/en/download/).
Afterwards, you can run `make` from the root of the repository and the executable should be under `./bin/local`.

Alternatively, we have also a [Dockerfile](https://github.com/aws/copilot-cli/blob/mainline/Dockerfile) present in the repo and you can run `make release-docker` and that will build the binaries for all platforms in a container and then copy them over locally. However, we haven't used the `release-docker` target in a while.

We're planning to do a release for v1.2.0 within a week! We're aiming for the end of this week or early next week.

**Comment by sekamaneka** [comment]
thanks. cool project you have here!
