### ISSUE TITLE
Cloud map service discovery target per environment

### ISSUE THREAD

**Issue by sekamaneka** [aws/copilot-cli#1929]
Hello again,

as mentioned in another issue im trying to create an API GW with copilot authorization. It should have 2 environments. prod and test. But only 1 of them works at any given time (the one created first). I think the issue is that these two service discovery endpoints have the same name. 

```
copilot svc show

Service Discovery

  Environment       Namespace
  -----------       ---------
  prod, test        api.ens.local:443
  
```

**Comment by efekarakus** [comment]
Hi @swilso793 :)

Assuming that you're not importing an existing VPC, Copilot should create for each environment's VPC:
https://github.com/aws/copilot-cli/blob/35ac40cc071b7b266144b4e089bb4b9cf906ee85/templates/environment/versions/cf-v1.1.0.yml#L44-L52

Are you importing an existing VPC?

**Comment by sekamaneka** [comment]
Hey,

Yes it creates two private dns namespaces. With exactly the same name.
Since it's dns i assume the name matters and not some unique id behind it.

Even if selecting the cloudmap manually (from the web console) as an integration target of the API GW it doensn't work. 
I will try changing the local namespace to have the env in the name and report back if it works.

```
     Properties: 
         Name: !Sub ${Env}.${AppName}.local 

```

**Comment by sekamaneka** [comment]
When adding the environment name to the cloudmap namespace it works as expected.

**Comment by efekarakus** [comment]
Wow okay! this is surprising to me, do you have a VPC link for your HTTP API? Does APIGW still pick up the "test" environment's namespace if your VPC link points to the "prod" environment?

**Comment by sekamaneka** [comment]
yes and yes.. It just leads to a service unavailable message. when in doubt blame DNS 💯

**Comment by efekarakus** [comment]
😂 thanks for letting us know! I'll reach out to someone on the APIGW team to see if this is expected behavior or if it's a bug that they can fix!

**Comment by efekarakus** [comment]
Hi @swilso793 I contacted the API GW team to let them know of this behavior, I'll update this issue if we get any updates!

**Comment by efekarakus** [comment]
Hi @swilso793 would you mind emailing me karakuse@amazon.com with your account ID and VPC IDs where this issue was occurring, I'll relay this information to help us troubleshoot with the APIGW team.

Thanks!

**Comment by efekarakus** [comment]
@swilso793 I just head back from the APIGW team that this issue should be fixed now for new CloudMap integrations!

So if we start from new environments hopefully this behavior should be gone.

**Comment by sekamaneka** [comment]
thank you! i will test at a later date but im closing this for now.

**Comment by efekarakus** [comment]
Yay I just tried this out and can confirm that APIGW has fixed this issue!
