### ISSUE TITLE
Scaling based on SQS

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#1933]
Right now the only scaling type we support is simple target tracking. Users want to have [scaling based on SQS](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-using-sqs-queue.html) because they want scaling workers based on queue depth.

Use cases:

1. Our SQS queues are managed by terraform. Our workaround was to perform the scaling configuration in Terraform once the ECS tasks have been deployed by copilot.

**Comment by efekarakus** [comment]
This feature was delivered with the "Worker Service" pattern in https://github.com/aws/copilot-cli/releases/tag/v1.10.0 🥳
