### ISSUE TITLE
CodeBuild fails in pipeline when the GitHub repository path has a long name

### ISSUE THREAD

**Issue by lwcooper** [aws/copilot-cli#1939]
**Issue:** Having a long organisation and github repository name makes the docker build fail in CodeBuild

**Description:**

I have a relatively long GitHub organisation name, and an average sized repository name, but when combined they make up 59 characters. When combined with the uuid and the `pipeline-app-name` the total character count exceeds the [128 character limit docker imposes](https://docs.docker.com/engine/reference/commandline/tag/) for a tag. 

When I looked in the logs for CodeBuild I noticed it was failing on the error `invalid reference format` 

**Workaround:**

I shortened the name of my GitHub repository and verified the build succeeded

It would be great to truncate the tag to a certain length to avoid this problem happening in the future

**Comment by huanjani** [comment]
Hi, @lwcooper! 

Thanks for bringing this issue (and error and workaround) to our attention!
We are working on a fix. Stay tuned...!

**Comment by huanjani** [comment]
Update: the plan is to limit pipeline names to 100 characters, truncating from the front if necessary. Pipeline names can only be 100 characters.
In the buildspec, we'll truncate the CODEBUILD_BUILD_ID to the allotted 128 characters because the added verbiage and UUID add another 50 characters.

**Comment by efekarakus** [comment]
Hi @lwcooper , the fix was released in v1.3.0! https://github.com/aws/copilot-cli/releases/tag/v1.3.0

**Comment by lwcooper** [comment]
@huanjani @efekarakus thanks for the fix! Legends

**Comment by efekarakus** [comment]
It's all @huanjani :D
