### ISSUE TITLE
AddonsStack UPDATE_FAILED Requires capabilities

### ISSUE THREAD

**Issue by rmarapp-dio** [aws/copilot-cli#1954]
Currently, we have a "load-balanced web service" which was working fine. Then we went out to incorporate CI/CD ('pieline init, pipeline update'. 
In the code build pipeline, the build fails with the following error message.
![image (1)](https://user-images.githubusercontent.com/79019642/108728351-1ef04280-74ef-11eb-89c8-a9a9cca0eb86.png)

I checked everything and nothing seems out of the ordinary. We have other services that do not have addon-s and they all seem to do well.

**Comment by efekarakus** [comment]
Thanks @rmarapp-prisidio ! This does indeed seem to be a bug on our end, we don't provide the necessary capabilities here:
https://github.com/aws/copilot-cli/blob/c4d9432d700d47779bb7a9eaa01a43850ce51976/templates/cicd/pipeline_cfn.yml#L309

We should add the same permissions that we provide in our `copilot deploy` path:
https://github.com/aws/copilot-cli/blob/c4d9432d700d47779bb7a9eaa01a43850ce51976/internal/pkg/aws/cloudformation/changeset.go#L102-L106

I've added this issue to our sprint for us to fix it. We'll update the issue once the fix is out!

**Comment by rmarapp-dio** [comment]
Ece,

Thanks. Any idea when the potential fix might arrive?
We are currently blocked or is there any workaround that we could use until you could roll out the release?

Thanks
Ram
________________________________

**Comment by efekarakus** [comment]
Hi @rmarapp-prisidio 

I'm sorry to hear that 🙇 ! We're working on it this sprint, so we should have a fix out within a week. In the mean time to get unblocked, you can modify the pipeline manually and then retry the action by adding the additional capabilities:
1. Edit the pipeline
![edit-pipeline](https://user-images.githubusercontent.com/879348/108773184-d5195380-7512-11eb-9a89-96aca769bd38.png)
2. Edit the stage
![edit-stage](https://user-images.githubusercontent.com/879348/108773205-da769e00-7512-11eb-8f51-ed97023d244b.png)
3. Edit the CreateOrUpdate action
![edit-action](https://user-images.githubusercontent.com/879348/108773221-e06c7f00-7512-11eb-9f60-bcbd9d0d4f96.png)
4. Add the additional capabilities
![edit-capabilities](https://user-images.githubusercontent.com/879348/108773270-ee220480-7512-11eb-937f-8858ea0ca826.png)

**Comment by efekarakus** [comment]
Hi @rmarapp-prisidio we merged the fix in https://github.com/aws/copilot-cli/pull/1962 and it should go out next release!

**Comment by rmarapp-dio** [comment]
Awesome thank you. Meanwhile, We have the temporary fix working..

Thanks
Ram
________________________________

**Comment by efekarakus** [comment]
The fix is released in v1.3.0! https://github.com/aws/copilot-cli/releases/tag/v1.3.0

**Comment by rmarapp-dio** [comment]
Ok thanks..

Thanks

________________________________
