### ISSUE TITLE
Skip prompting for tag value if using an existing image

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#1967]
## Background

I've a copilot manifest file that uses the `location` field instead of building from a Dockerfile:
![Screen Shot 2021-02-23 at 10 50 48 AM](https://user-images.githubusercontent.com/879348/108892684-03f00200-75c5-11eb-973c-b0b143e8d406.png)

## Current behavior
When I run `copilot deploy`, I get the following prompt:
![Screen Shot 2021-02-23 at 10 49 10 AM](https://user-images.githubusercontent.com/879348/108892732-1702d200-75c5-11eb-906c-7d34d2610fe4.png)

## Expected behavior
The "Input an image tag value" prompt should ideally not be there since it's not used by the CLI.

**Comment by toricls** [comment]
Is this issue still valid? Looks it's already been fixed in #2196 :D

**Comment by efekarakus** [comment]
You're right, it's fixed now :D
