### ISSUE TITLE
Question - is this possible to have one ALB per environment, not per service?

### ISSUE THREAD

**Issue by filipgolonka** [aws/copilot-cli#1991]
As far as I understand now, each service has it's own ALB. Is it possible to use one ALB per environment?

**Comment by kohidave** [comment]
Actually that's exactly what we do now 😄 We create one ALB per environment and each service gets its own listener rule. The ALB is only provisioned when a Load Balanced Service is created. Hope that helps!

**Comment by filipgolonka** [comment]
Ok, so I misunderstood the concept :D thanks for explanation!
