### ISSUE TITLE
Incorrect verification steps

### ISSUE THREAD

**Issue by justin8** [aws/copilot-cli#2027]
The verification step of the getting started docs has several incorrect links.

The asc download file for mac and linux is a "Not Found" error page, resulting in a bad PGP signature when verifying.

The windows download doesn't have `.asc` at the end, so it downloads the executable instead, but also it is a bad link too.

I suspect `/latest` isn't being resolved from the github releases page.

**Comment by iamhopaul123** [comment]
Yes. Thank you for finding the bad link. Will send out a quick fix for this soon.

**Comment by justin8** [comment]
Thanks for the quick update
