### ISSUE TITLE
pipeline creation (update command) fails 

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2048]
I did these steps:

`copilot pipeline init`

This created the yaml files. Then pushed these files to my repo.

Then this fails:

`copilot pipeline update`

error:

```
ACTION REQUIRED! Go to https://console.aws.amazon.com/codesuite/settings/connections to update the status of connection xy-user-service from PENDING to AVAILABLE.
✘ Failed to create a new pipeline: pipeline-myApp-user-service.
✘ create pipeline: check if changeset is empty: create change set copilot-51ef519a-711b-4126-bfbd-3d618ef824a5 for stack pipeline-myApp-user-service: ValidationError: Template format error: Unrecognized resource types: [AWS::CodeStarConnections::Connection]
    status code: 400, request id: 8a87f62a-ae14-4fe3-9a3e-8b965d2af794: describe change set copilot-51ef519a-711b-4126-bfbd-3d618ef824a5 for stack pipeline-myApp-user-service: ValidationError: Stack [pipeline-myApp-user-service] does not exist
    status code: 400, request id: 44927d7e-2514-466a-94ff-51e932042737
```

The connection page is empty. There is no xy-user-service connection. Nothing is pending.

Is this a bug? I'm using copilot version: v1.3.0.

Also worth mentioning: I created the pipeline in the root directory of my micro service, and then I moved the resulting files to the repo where I store all docker stuff and I tried to run update there.
As far as I know init just creates these files, update would create the actual pipeline, so I can store the config files anywhere. Is this correct?
I moved the files because I have multiple services and I wanna keep all configs in one place.

But anyway, I tried to run update in the micro service directory as well, where the init was executed. Same error.

Also `copilot pipeline status` prints this:

```
✘ describe status of pipeline: get pipeline status: get pipeline state pipeline-myapp-user-service: RequestError: send request failed
caused by: Post "https://codepipeline.me-south-1.amazonaws.com/": dial tcp: lookup codepipeline.me-south-1.amazonaws.com on [2001:4c48:2::1]:53: no such host
```

**Comment by efekarakus** [comment]
Hi @gtamas ! 
> As far as I know init just creates these files, update would create the actual pipeline, so I can store the config files anywhere. Is this correct?

Copilot looks specifically for a `<repo>/copilot/pipeline.yml` file when running `copilot pipeline update`. It's strange though 🤔 Copilot should have thrown the following error in that situation earlier to you:
```
read pipeline manifest: no pipeline manifest found in the workspace
```

Would you mind moving both the `pipeline.yml` as well as the `buildspec.yml` under the `<root>/copilot/` directory and then try running `copilot pipeline update again?`

_Note that both of these files should be committed and pushed upstream for the pipeline execution to succeed_

**Comment by gtamas** [comment]
Thanks for getting back to me @efekarakus !

I think my description of the issue wasn't totally accurate, sorry about that. Actually all the files are already located in <repoRoot>/copilot/ dir. When I moved them earlier, I moved the entire copilot directory.

And if try to run `copilot pipeline update` in the original location (where `copilot pipeline init` was executed before), I get the same error.

By the way, what do you think about the other issue I mentioned? The `copilot pipeline status` one? It's complaining about a non-existent host. That seems to be a problem, because I can't tell copilot to use another region. I mean codepipeline.me-south-1.amazonaws.com doesn't exist, but for example codepipeline.eu-west-1.amazonaws.com does.

What should I do?

Thanks in advance!

**Comment by gtamas** [comment]
What's best way to use copilot? 

I have 5-6 micro services and other components. These are all stored in different repos. 
So should I just repeat the entire process in each repo dir? Like:

```
copilot app init
copilot pipeline init
(push)
copilot pipeline update
```

Guess I might omit app init? I only have one app. All services belong to that app.

**Comment by efekarakus** [comment]
> And if try to run `copilot pipeline update` in the original location (where `copilot pipeline init` was executed before), I get the same error.

I wonder if this is all related to the second error you're mentioning 💭 Since CodeStar connections and AWS CodePipeline are both [unavailable](https://docs.amazonaws.cn/en_us/general/latest/gr/codestar.html) in Bahrain `me-south-1` then the pipeline fails to create :(

> By the way, what do you think about the other issue I mentioned? The copilot pipeline status one? It's complaining about a non-existent host. That seems to be a problem, because I can't tell copilot to use another region. I mean codepipeline.me-south-1.amazonaws.com doesn't exist, but for example codepipeline.eu-west-1.amazonaws.com does.

Unfortunately, if [CodePipeline is not available in that region](https://docs.aws.amazon.com/general/latest/gr/codepipeline.html), Copilot won't be able to create the pipeline. I am so sorry about the inconvenience 🙇 !   
In that situation, you'll need to instead run `copilot deploy` manually whenever you want to deploy your services. If it's at all a possibility, an alternative might be to create the application and the pipelines in a region supported by CodePipeline.

> What's best way to use copilot?
>
> I have 5-6 micro services and other components. These are all stored in different repos.
> So should I just repeat the entire process in each repo dir? 

That's correct! This will create a separate pipeline for each one of your repositories. When you run `copilot app init` again in a different repository, Copilot will pick up any existing applications and you can just choose one of them. The second time around, the command should be very quick to execute as this will create only a `./copilot/.workspace` file for us to store the application name locally.

**Comment by gtamas** [comment]
Hi

OK I see thanks for the clarification. 
So this is not ideal, but we can manage it manually for now.
Are there any plans for making CodePipeline available in the Middle-East anytime soon?

We are building online services for this region specifically. Our users all live in GCC countries, mainly Saudi Arabia. So moving to another region is not ideal for us.

**Comment by efekarakus** [comment]
Hi @gtamas !

>  Are there any plans for making CodePipeline available in the Middle-East anytime soon?

I've reached out to the CodePipeline team internally sharing with them this issue. Unfortunately, I don't have visibility onto when CodePipeline will be available in Bahrain.

> We are building online services for this region specifically. Our users all live in GCC countries, mainly Saudi Arabia. So moving to another region is not ideal for us.

One thing that's possible with Copilot is creating your environments `"test"`, `"prod"`, ... in `me-south-1` but having the application and CodePipeline initialized in a different region that's supported.

This way all your actual environment (VPC, load balancer), and service (ECS service, addons) will be hosted in `me-south-1` but only the pipeline will be in a different region. That's also another alternative!

**Comment by gtamas** [comment]
Thanks! This sounds like a good solution.
But how to do this? Should we delete the application and recreate it in another region?
Wouldn't remove all associated things as well, like services and environments?

@efekarakus 

Also I don't understand how to create an application in a specific region. As far as I know, copilot uses the AWS cli config to figure out what the region is. I see no option which would me to specify the region.

**Comment by gtamas** [comment]
@efekarakus 
Maybe it would be a good idea to add the --region option to the `copilot pipeline init`, which would allow the pipeline to be initialised in a different region.

**Comment by efekarakus** [comment]
> But how to do this? Should we delete the application and recreate it in another region?
Wouldn't remove all associated things as well, like services and environments?

hmm yes, at the moment we don't provide an easy way unfortunately to create a pipeline in a different region than the original application configuration :( that's a good feature request!
