### ISSUE TITLE
Enable "dev" flags to change circuit breaker values

### ISSUE THREAD

**Issue by ghost** [aws/copilot-cli#2051]
In the midst of debugging a copilto built application - if I happen to deploy a change that causes ECS Containers to fail deployment in the cluster, as of this writing you have to wait until the container image fails 10 times before copilot exits.   A enhancement for development workflow would be a "dev" mode where, as in this case, you could set the circuitbreaker value to 1 before failing.   

A dev flag would also allow for extra verbose output of the CF templates doing the work behind the scenes.

**Comment by efekarakus** [comment]
Hi @mptaws ! I don't think we can configure the circuit breaker threshold unfortunately. This seems to be related to https://github.com/aws/copilot-cli/issues/2041

**Comment by KollaAdithya** [comment]
Hello @mptaws !
`Ctrl-C` feature is released in [v1.30](https://github.com/aws/copilot-cli/releases/tag/v1.30.0) 🎉 . You can now cancel your stack update to rollback to previous configuration.
