### ISSUE TITLE
Pipeline list limited list of services in my workspace

### ISSUE THREAD

**Issue by niros1** [aws/copilot-cli#2058]
I initiate a pipeline with BitBucket and make it works but the problem is that it doesn't list down all of my services as part of the build process.

svcs=$(./copilot-linux svc ls --local --json | jq '.services[].name' | sed 's/"//g') list only 2 services out of 8.
the problem is that it seems like I have 2 .workspace files, follow the below directory structure:
```
copilotRoot
         .workspace
         serviceA
                  Dockerfile
         serviceB
                  Dockerfile
         serviceC
                  Dockerfile
         copilot
                  .workspace
                  serviceA
                          manifest.yml
                  ...
```
when I run _copilot svc ls --local_ from copilotRoot i get A,B (no good) and from copilot directory I get A,B, C (good).
From the build process I get always A,B.
These obviously affect the files in the infrastructure directory (see bellow)
I don't know where come the first workspace file and how to get rid of it or fix it or just make the build work with the right one.

build output:
```
[Container] 2021/03/15 09:42:20 Running command ls -lah ./infrastructure
937 | total 168K
938 | drwxr-xr-x 2 root root 4.0K Mar 15 09:42 .
939 | drwxr-xr-x 7 root root 4.0K Mar 15 09:42 ..
940 | -rw-r--r-- 1 root root  611 Mar 15 09:42 bv-svc-brain-assets-dev.params.json
941 | -rw-r--r-- 1 root root 7.7K Mar 15 09:42 bv-svc-brain-assets-dev.stack.yml
942 | -rw-r--r-- 1 root root  625 Mar 15 09:42 bv-svc-brain-assets-playground.params.json
943 | -rw-r--r-- 1 root root 7.7K Mar 15 09:42 bv-svc-brain-assets-playground.stack.yml
944 | -rw-r--r-- 1 root root  613 Mar 15 09:42 bv-svc-brain-assets-prod.params.json
945 | -rw-r--r-- 1 root root 7.7K Mar 15 09:42 bv-svc-brain-assets-prod.stack.yml
946 | -rw-r--r-- 1 root root  613 Mar 15 09:42 bv-svc-brain-assets-test.params.json
947 | -rw-r--r-- 1 root root 7.7K Mar 15 09:42 bv-svc-brain-assets-test.stack.yml
948 | -rw-r--r-- 1 root root  734 Mar 15 09:42 dgu-keyclaok-dev.params.json
949 | -rw-r--r-- 1 root root  21K Mar 15 09:42 dgu-keyclaok-dev.stack.yml
950 | -rw-r--r-- 1 root root  748 Mar 15 09:42 dgu-keyclaok-playground.params.json
951 | -rw-r--r-- 1 root root  21K Mar 15 09:42 dgu-keyclaok-playground.stack.yml
952 | -rw-r--r-- 1 root root  736 Mar 15 09:42 dgu-keyclaok-prod.params.json
953 | -rw-r--r-- 1 root root  21K Mar 15 09:42 dgu-keyclaok-prod.stack.yml
954 | -rw-r--r-- 1 root root  736 Mar 15 09:42 dgu-keyclaok-test.params.json
955 | -rw-r--r-- 1 root root  21K Mar 15 09:42 dgu-keyclaok-test.stack.yml
956

```

Thanks for the assistance.

**Comment by efekarakus** [comment]
Hi @niros1 !

Do you have the manifest files for `serviceB` and `serviceC` under the `copilotRoot/copilot/` directory? just like for `serviceA`?

The `.workspace` file should only be under the generated `copilot/` directory, so I think we can remove the `copilotRoot/.workspace` file safely and the pipeline should pick up the right services then!

**Comment by niros1** [comment]
Yes i do, just was too lazy to state it 😀

I will try to remove it 
10x

**Comment by niros1** [comment]
All is working fine after tweaking a bit the build code.
thanks a lot, i am closing the ticket.
