### ISSUE TITLE
`app delete` should skip cleaning the S3 bucket if it doesn't exist

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#2070]
Now `app delete` would fail if the S3 bucket it is trying to empty doesn't exist. Ideally for idempotency concern we should just skip.

**Comment by iamhopaul123** [comment]
fixed by #2365

**Comment by efekarakus** [comment]
This is now fixed in v1.8.0 🥳 https://github.com/aws/copilot-cli/releases/tag/v1.8.0
