### ISSUE TITLE
Can't access secrets - "ResourceInitializationError: unable to pull secrets or registry auth...

### ISSUE THREAD

**Issue by markthethomas** [aws/copilot-cli#2095]
hi there! I'm enjoying Copilo, but am running into some issues. Have a pretty basic setup (pipeline, dockerfile, manifest, etc.) and started adding in SSM params to use as secrets, but can't get my cluster to update to a new version of a task now because I consistently get this message:

```ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm: service call has been retried 1 time...```

Haven't done any customization or anything to it, little perplexed. Was able to access secrets with a "dummy" version of the service earlier (lightweight echo server) but can’t now. Thanks for your work and help! :)

**Comment by efekarakus** [comment]
Hi @markthethomas ! 

Just to make sure, do the SSM parameters have the tags `copilot-application`, and `copilot-environment`? https://aws.github.io/copilot-cli/docs/developing/secrets/

**Comment by markthethomas** [comment]
Yes indeed!

**Comment by markthethomas** [comment]
Ah wait - my CLI might have written one of them to the wrong account! I’ll double check and update here 👍

**Comment by efekarakus** [comment]
Hi @markthethomas ! I just wanted to double check if the secrets are working now or if there is anything else that we can help with?

**Comment by markthethomas** [comment]
@efekarakus hey! yes this was all on me - I had set `AWS_PROFILE` in a different terminal session but not in another one and had written like 2-3 of the secrets to the wrong aws account. doh! Totally my bad. Was so confused 😅  thanks!
