### ISSUE TITLE
Stack Cleanup for Environments fails

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#2100]
Good morning COPILOTS!

I've noticed, that while working with customers, that the environment cloudformation stack cleanup currently has a couple of pernicious issues that can cause quite a bit of customer confusion. 

## Steps to repro

1. Run `copilot init`
2. Environment creation CloudFormation fails (for permissions, limits, whatever) 
3. Customer fixes issue
4. Run `copilot init` again
5. The stack creation will fail with an error: 
    > ... check if changeset is empty: create change set copilot-842c4f30-ada3-40ac-984c-0f18b7d5241b for stack app-env: ValidationError: Stack [app-env] already exists and cannot be created again with the changeSet [copilot-842c4f30-ada3-40ac-984c-0f18b7d5241b].
6. Ok, this looks like a race condition - so wait a few seconds, and then try running `copilot init` again
7. In this case, you'll get an error that the CFN Execution role already exists: `app-env-CFNExecutionRole already exists`

Looks like the env manager role is not being deleted 🤔 

## What I expect

1. Run `copilot init`
2. Environment creation CloudFormation fails (for permissions, limits, whatever) 
3. Customer fixes issue
4. Run `copilot init`
5. The previous stack is deleted - and we wait until it's created, and then the new stack is created successfully 

## Summary

Two issues - the environment stack cleanup seems to have a race condition that doesn't properly wait for the stack to be deleted. The CFNExecution role isn't cleaned up. I didn't try with workloads. 

Thank you friends!

**Comment by kohidave** [comment]
For this issue: 
> ... check if changeset is empty: create change set copilot-842c4f30-ada3-40ac-984c-0f18b7d5241b for stack app-env: ValidationError: Stack [app-env] already exists and cannot be created again with the changeSet [copilot-842c4f30-ada3-40ac-984c-0f18b7d5241b].

It looks like it's an easy fix (from @efekarakus the great): 

```golang
	if status.requiresCleanup() {
		// If the stack exists, but failed to create, we'll clean it up and then re-create it.
		if err := c.Delete(stack.Name); err != nil {
			return "", fmt.Errorf("clean up previously failed stack %s: %w", stack.Name, err)
		}
		return c.create(stack)
	}
```
We don't call DeleteAndWait and istead it's just Delete

**Comment by efekarakus** [comment]
The fix is now released in https://github.com/aws/copilot-cli/releases/tag/v1.5.0!
