### ISSUE TITLE
Issues connecting to Aurora from Copilot service

### ISSUE THREAD

**Issue by markthethomas** [aws/copilot-cli#2103]
hey again y'all! 

I'm in the process of getting an app up and running using copilot. It's a rails app that I'm trying to get off elastic beanstalk because....well, you know 😁 Able to deploy and get things running via the pipeline I've created. 

Where Im having issues is this: my container constantly fails to register due to not being able to connect to the aurora postgres DB I'm using (`is the server accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?`). I've confirmed that I can run the Dockerized version of the app w/ all the same environment variables etc. can connect from my laptop w/o issue (I turned on "all access from anywhere" temporarily to confirm). 

So my question is this: is there something in the VPC setup or other quirk of copilot-style setups that would stop my containers from being able to connect? Never seen this before. The setup I have is pretty bland/basic overall, so a little unsure what I'm doing wrong. One thing to note: they are in different VPCs (the DB is in my account default and the copilot service is in the one it created of course)

ty!

**Comment by markthethomas** [comment]
update: created a bare-bones nginx image to run `copilot svc exec` through and `telnet`ing to check connectivity on the host doesn't seem to be working (it hangs) - thinking it has to be something in the way copilot sets up the VPC? I'm a pretty experienced engineer and have used AWS a good deal but a lot less on the VPC/networking side of things, so maybe the reason for all this is obvious 😅

**Comment by bvtujo** [comment]
Hi @markthethomas, how are you setting up Aurora? Can you share an addons template? 

My first guess is that it's a security group ingress issue--the Aurora cluster would need to be associated with a security group with ingress allowed on 5432 from the Environment Security Group which Copilot creates.

**Comment by bvtujo** [comment]
The other issue is the separate VPCs-- can you try creating your DB cluster in a private subnet in the copilot-created VPC? Unless you bridge those VPCs somehow (like with a VPC peering connection) you won't be able to have connectivity.

**Comment by huanjani** [comment]
Closing bc staleness; please reopen if issues persist. Thanks!
