### ISSUE TITLE
Pipeline config uses branch main instead of master

### ISSUE THREAD

**Issue by davivcgarcia** [aws/copilot-cli#2105]
### Description

When creating pipelines with `copilot pipeline init` and selecting the repository, the `pipeline.yaml` configuration file is created using the `main` default branch instead of asking for confirmation or determining the current branch. The problem is that old repositories are still using `master` as default branch, causing problems when deploying the pipeline with `copilot pipeline update`.

### Version

```shell
$ copilot version
version: v1.4.0, built for linux
```

**Comment by kohidave** [comment]
Sorry about that! I think we could be a little smarter and detect the remote branch :)

In the mean time, you can set the branch in your `pipeline.yaml` file:

https://aws.github.io/copilot-cli/docs/manifest/pipeline/#source-properties-branch

**Comment by huanjani** [comment]
Yes, I have run into this problem myself! Another option is to use the `-b`/`--git-branch` flag with `copilot pipeline init`.
