### ISSUE TITLE
Storage init fails due to validateKey

### ISSUE THREAD

**Issue by ghost** [aws/copilot-cli#2134]
When creating DynamoDB with the following options(the length of attribute name is 2):
`$ copilot storage init -n todotable -t "DynamoDB" -w backend --partition-key Id:S --no-lsi --no-sort`

Copilot throws the following error:
`✘ value must contain only alphanumeric characters and ._-`

If the length of DynamoDB table's attribute name is longer like following:
`$ copilot storage init -n todotable -t "DynamoDB" -w backend --partition-key TodoId:S --no-lsi --no-sort`

Copilot wrote CFn template successfully.
`✔ Wrote CloudFormation template for DynamoDB Table todotable at copilot/backend/addons/todotable.yml`

According to DynamoDB's naming rule(https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.NamingRules ), attribute names must be at least one character long. 

Validation for the length of partition key name is needed in validateKey function
https://github.com/aws/copilot-cli/blob/d5d54a5f9583b74f0904b1a7954399ba04d65b9e/internal/pkg/cli/validate.go#L515

**Comment by efekarakus** [comment]
This is now released in https://github.com/aws/copilot-cli/releases/tag/v1.5.0 ! Thank you for the contribution @hidekazu-karino 😄
