### ISSUE TITLE
Support deploying without creating a git commit

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#2139]
## Ask
Running `copilot deploy` should update my service using my local changes even if they're not yet committed.  

Related #1400 

## Current Behavior
When a user has changes that have not yet been committed and run `copilot deploy`, Copilot will:
1. Push to ECR a new image using the latest commit sha as the image tag. 
   > This can be misleading because the image tagged with a particular sha can now refer to code that's not actually part of that commit.
2. Trigger a service or job stack update
   > However, the stack update does not update the service because the image URL did not change. 

So although we pushed an image to ECR, the service update does not happen and leads to a confusing experience to users.
Our recommendation to mitigate this issue at the moment is to run `copilot deploy --tag <unique value>`. 

<img width="1034" alt="deploy" src="https://user-images.githubusercontent.com/879348/113458715-10d3f280-93c8-11eb-9a3c-5b7f1cadce6d.png">

## Expected Behavior
1. The image tagged with the git commit sha should refer to the real commit and not to uncommitted code.
2. If an image gets pushed to ECR, the ECS service should be updated using the image.

## Proposed solution
We should refer to the image digest in our cloudformation templates instead of the tag. For example:
```
# Instead of:
111111111.dkr.ecr.us-west-2.amazonaws.com/demo/frontend:54fda35
# Use:
111111111.dkr.ecr.us-west-2.amazonaws.com/demo/frontend@sha256:1594f4a9be2c12c4aac3545d048ff772fe0f5ee03c0fb4f5525ba363b3e8b3a5
```

To do this, when running `copilot deploy`:
1. We shouldn't require an image tag anymore while pushing by default (so no git repo needed) :
https://github.com/aws/copilot-cli/blob/f8b02ab585c3c6fb2beb5c7558767c0979b8d7b2/internal/pkg/cli/git.go#L31-L37
2. Instead, if there is a commit and `git status --porcelain` returns no ouput then use the commit as a tag for the user's convenience. If not then leave it empty.
3. We can retrieve the digest after pushing by running:
```
$ docker inspect --format='{{json (index .RepoDigests 0)}}'  111111111.dkr.ecr.us-west-2.amazonaws.com/demo/frontend
"111111111.dkr.ecr.us-west-2.amazonaws.com/demo/frontend@sha256:1594f4a9be2c12c4aac3545d048ff772fe0f5ee03c0fb4f5525ba363b3e8b3a5"
```

**Comment by bvtujo** [comment]
To everyone watching this issue, this feature is now released in [Copilot v1.6.0](https://github.com/aws/copilot-cli/releases/tag/v1.6.0)! 🎉🎉
