### ISSUE TITLE
Support web services with non 200 healthchecks

### ISSUE THREAD

**Issue by 0xR** [aws/copilot-cli#2142]
I am deploying a service that will only return 400 or 403 on every url.

It would be nice if I could those statuscodes as healthy status.

It seems like ELB already supports this:
![image](https://user-images.githubusercontent.com/6420016/113519929-d9b03d80-958f-11eb-88fa-9de3bda0ecfc.png)

There is just no way to configure this: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck

**Comment by efekarakus** [comment]
This feature is released! The field is under:
```yaml
http:
  healthcheck:
    success_codes: '200,301'
```
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck-success-codes
