### ISSUE TITLE
Running tasks with workload configurations

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#2159]
This issue is a design proposal to support running tasks with configurations imported from a deployed workload. 

This addresses  #1432 and #1790, and is related to #1269.

# Proposal
## [Preferred] Option 1 - Adding ` --generate-cmd` flag to `task run`
With this option, we will implement a flag to `task run`, named `--generate-cmd` that accepts a workload name (this could be a copilot service/job or an existing service outside of copilot) as argument. 
```
copilot task run --generate-cmd <workload name>
```
It will generate and print a `task run` command with pre-populated arguments to flags such as `--image`, `--task-role`, `--env-vars`, etc. 

For example, suppose we have deployed a copilot service named `my-service`. Then running
```
copilot task run --generate-cmd my-service
```
will print 
```
copilot task run \
--image <image url used for my-service> \
--task-role <task role used for my-service> \
--execution-role <execution role for my-service> \ 
--env-vars <env vars in my-service> \
--entrypoint <entrypoint override specified in my-service> \
--command <command override specified in my-service> \
--secrets <secrets injected into my-service containers> \
--subnets <subnets in which my-service live> 
--security-groups <security groups of my-service>
--cluster <cluster of my-service>
```
Users can then copy and paste the above output to run `task run` with configurations grabbed from "my-service". This is similar to the [`--generate-cli-skeleton`](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-skeleton.html) flag in AWS CLI.

This makes it easier for customers to reuse their workload configurations for one-off tasks, along with the ability to customize it by editing the generated command before running it.

## [Alternative] Options 2 - `copilot svc runtask` and  `copilot job runtask`
With this option, we add `runtask` command to `svc` and `job`. This will provision and start a one-off task using the workload configurations.

For example, suppose we have deployed a copilot service named `my-service`. Then running
```
copilot svc runtask --name my-service
```
will start a one-off task using `my-service`'s image, task role, execution role, environment variables, etc.

Comparing to [Option 1], this requires one less command in order to kick off a task. However, a downside is that it is difficult for customers to customize the configuration. 

## [Alternative] Option 3 - `copilot task run --workload`
With this option, we add a `--workload` flag to `task run`, accepting a copilot workload's name as the argument.

For example, suppose we have deployed a copilot service named `my-service`. Then running
```
copilot task run --workload my-service
```
will start a one-off task using `my-service`'s image, task role, execution role, environment variables, etc.

This option allows more possibility for customization than [Option 2], because it is possible to specify `--workload my-service --command 'echo hello'` to reuse `my-service` configurations while using a different command override. However, how `--workload` interact with the existing flags may add too much complications and can be potentially confusing to users.

**Comment by malkovro** [comment]
💪🏼
Quick doubt, none of these options mentions the secrets defined on the manifest and bound to the service. Some one-off tasks need those to be able to do their intended operations. Would those be injected in the env-vars of the _Option 1_ ?

**Comment by Lou1415926** [comment]
Hello @malkovro! 

They will be injected in the `--secrets` flag by *Option 1*. Although currently `--secrets` is not an available flag yet for `task run`, we are working on #2163 to add it. I have updated the design proposal to include all flags that can be populated!

**Comment by Lou1415926** [comment]
The feature was delivered in [v1.7.0](https://github.com/aws/copilot-cli/releases/tag/v1.7.0)! Closing the issue.
