### ISSUE TITLE
Container dependency

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#2175]
Now that we are able to share storage between sidecars and the main container, as well as mark sidecars as non-essential, it would be great to have an option for dependency. This already exits in Fargate: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDependency.html.

Maybe something like:

```
depends_on:
  sidecarname:
    condition: <start | complete | success | healthy>
```

**Comment by efekarakus** [comment]
This is now shipped in v1.8.0 🥳 https://github.com/aws/copilot-cli/releases/tag/v1.8.0
