### ISSUE TITLE
Pipeline init fails with: select URL: list of provided options is empty

### ISSUE THREAD

**Issue by flyck** [aws/copilot-cli#2181]
Following the instructions from over [here](https://aws.github.io/copilot-cli/docs/concepts/pipelines/), a copilot pipeline init should initiate a new pipeline.
Steps to reproduce
- copilot init (select load balanced web service)
- copilot pipeline init

```
➜  myrepo git:(master) copilot pipeline init
1st stage: test
✘ select URL: list of provided options is empty
```

What would you advise to do in this situation?
For now I'm going to try downgrading to earlier versions.

copilot version v1.5.0 on mac (macOS 10.14.6)

**Comment by flyck** [comment]
Ok, found the issue. It needed a github repository first, makes sense.
Feel free to close this one...

**Comment by bvtujo** [comment]
Glad you were able to resolve this! We also have BitBucket and CodeCommit support available for pipelines if those providers suit your fancy.
