### ISSUE TITLE
Internal Load Balancer

### ISSUE THREAD

**Issue by frs17** [aws/copilot-cli#2183]
We are attempting to use Copilot to deploy a website that we would like to be only accessible from within our VPC. We tried deploying with `allowed_source_ips` set to our VPC’s CIDR range and found our deployed site was still publicly accessible. Our workaround is to deploy our site publicly using Copilot and then:

1. remove rules from the Copilot created load balancer and destroy it
2.  make our own load balancer which is identical to the Copilot created one in every way except is set to `internal` instead of `internet-facing`. 

Might there be a way for us to configure Copilot to create an internal facing load balancer? Or perhaps there is a better way to use Copilot to deploy a website that can only be accessed within a  VPC?
Love the project!

**Comment by efekarakus** [comment]
Hi @frs17 thanks for the feature request!

> Might there be a way for us to configure Copilot to create an internal facing load balancer? 

Not at the moment apologies 🙇 Internal load balancers is in our radar and we definitely want to support this usecase. I've added a roadmap entry here: https://github.com/aws/copilot-cli/projects/2

One thing that's possible today with Copilot is using the Copilot created service discovery namespace in your VPC: https://aws.github.io/copilot-cli/docs/developing/service-discovery/

So if you launch only "Backend Services", they should be accessible at `http://<svc name>.<app name>.local:<port>/` within the VPC but not publicly available.

Does that help? If not, what are some of the features on internal ALBs you'd like to see available in Copilot?

**Comment by frs17** [comment]
Hi @efekarakus, thanks for the quick reply. For our low-traffic use case the backend service is perfect. We re-deployed as a backend service, but haven't had any luck accessing the site via `http://<svc name>.<app name>.local:<port>`.

The CloudWatch logs report our service is up and running on `<port>`, but `http://<svc name>.<app name>.local:<port>`  times out (ERR_CONNECTION_TIMED_OUT). Any ideas what we might be doing wrong?

**Comment by efekarakus** [comment]
Hi @frs17 ! oh very interesting, when you run `copilot svc show`, do you see a service discovery endpoint:

For example, for my app I see:
```
Service Discovery

  Environment       Namespace
  -----------       ---------
  test              backend.demo.local:8080
```

One think you can try is running `copilot svc exec` to get a shell to one of your service's container. And then you can run commands like `curl http://backend.demo.local:8080` to test if your service is working  (assuming curl is in your container image), that might make testing a bit easier.

I wonder if your task comes up and then stops resulting in `ERR_CONNECTION_TIMED_OUT`

**Comment by frs17** [comment]
So I do see my endpoint with `copilot svc show`.  Also when I exec into it and run `curl` the body of my site is returned successfully (from other EC2s within my VPC `curl` returns "Could not resolve host".  

Thanks!

**Comment by efekarakus** [comment]
Ohhh gotcha! OK then for the other EC2 instances you'd need to attach the Copilot generated security group to those instances so that they can reach your services:
![Screen Shot 2021-04-19 at 9 53 00 AM](https://user-images.githubusercontent.com/879348/115274015-15511880-a0f5-11eb-84b8-d29c24d1da08.png)
The `EnvironmentSecurityGroup` should be defined in the environment CloudFormation stack (`{app}-{env}` stack), I believe once you add the security group to your instances it should be able to connect to your ECS service

**Comment by frs17** [comment]
Ahh I see -- is there a way to launch my service such that all traffic from within the VPC is allowed through right from the start?

Thanks for all the help.

**Comment by efekarakus** [comment]
I think alternatively, if you have already an existing security group that allows ingress from your VPC, then you can add it to your service in the `manifest.yml` file:
```yaml
network:
   vpc:
      security_groups: ['sg-1234'] # the security group that allows ingress within the VPC
```
(https://aws.github.io/copilot-cli/docs/manifest/backend-service/#network-vpc-security-groups)

**Comment by frs17** [comment]
That worked perfectly. Thanks a lot!
