### ISSUE TITLE
select service: retrieve services from workspace: yaml: line 5: did not find expected key

### ISSUE THREAD

**Issue by ericterpstra** [aws/copilot-cli#2198]
I can't deploy a load-balanced web service with the `copilot` cli due to the following error:

`select service: retrieve services from workspace: yaml: line 5: did not find expected key`

`copilot init` will create the app and all necessary resources for a load balanced web service, but when it gets to the deploy step for the service (either during the copilot init wizard, or later using `copilot svc deploy`), it always ends up with the workspace yaml error.

Any time I look at the yaml file, there is only 1 line:

contents of .workspace file in my project folder:
`application: myapp`

That's it. Only one line. I've deleted and re-created projects several times. Even just following a basic tutorial with the most basic node app and Dockerfile results in the same error - a one line .workspace file and an error trying to depoy the service.

I'm on the latest version of copilot-cli on an intel based mac (Big Sur).

**Comment by bvtujo** [comment]
Hi @ericterpstra, I think this error is coming not from the .workspace file, but from the manifests in the `copilot` directory. 

Copilot creates two separate objects, the .workspace file, which registers the current directory with a given application, and the `copilot` directory and subfolders, where the manifests are stored. 

Could you check to see if there's a file at `copilot/{{your-service-name}}/manifest.yml` and post the contents of that file here? That will help us see what's going on a bit better.

**Comment by ericterpstra** [comment]
Ok, I think I found the issue(s).

First there was a problem preventing my app from starting correctly if env vars were not set.  Then, in the .manifest file, I tried to set env vars but forgot to uncomment line 31:
`#variables:`

Got thrown off by the error message mentioning workspace line 5.  Everything seems to be working fine now. Thanks!
