### ISSUE TITLE
Reference secretsmanager secrets by JSON key

### ISSUE THREAD

**Issue by blampe** [aws/copilot-cli#2199]
Use case: I'd like to deploy a container with a storage add-on, but I don't have access to the container's source code. 

After running `storage init`, the recommended next step is

> Update svc's code to leverage the injected environment variable SVCCLUSTER_SECRET.
For example, in JavaScript you can write `const {username, host, dbname, password, port} = JSON.parse(process.env.SVCCLUSTER_SECRET)`.

This doesn't work for my use case, because the container expects some environment variables that I don't have control over.

As a workaround, I thought I could inject the appropriate env vars by referencing the secrets by ARN.

Additionally, since the storage credentials are stored as a JSON blob under one secret, I was expecting to be able to reference individual JSON keys within the secret, according to [this latest release](https://aws.amazon.com/blogs/containers/latest-updates-to-aws-fargate-for-amazon-ecs/) for ECS/Fargate.

It works when I reference the entire JSON blob:
```
secrets:
  DB_BLOB: 'arn:aws:secretsmanager:region:account_id:secret:svcclusterAur-12345'
```

However trying to reference keys within that blob (using the syntax described in the blog post above) gives an error 
```
secrets:
  DB_USER: 'arn:aws:secretsmanager:region:account_id:secret:svcclusterAur-12345:username::'
```

```
ValidationError: Template format error: YAML not well-formed. (line 92, column 134
```

As a workaround I can change the container's entrypoint to consume the Copilot environment variable & re-emit it as the variables expected by the container. But it would be nice to handle all of the secret bookkeeping within the manifest.

One final thought: hard-coding the region and random '12345' generated by Copilot definitely makes this feel fragile / unportable so I'm totally open to alternatives!

**Comment by bvtujo** [comment]
Hi @blampe,

Looks like you're getting burned by YAML's string conversions. You can specify full secret ARNs by the following syntax:
```yaml
secrets:
  DB_USER: "'arn:aws:secretsmanager:region:account_id:secret:svcclusterAur-12345:username::'"
```

Note the single AND double quotes that would otherwise get swallowed by YAML :(

Does switching to that syntax help?

**Comment by blampe** [comment]
> Hi @blampe,
> 
> Looks like you're getting burned by YAML's string conversions. You can specify full secret ARNs by the following syntax:
> 
> ```yaml
> secrets:
>   DB_USER: "'arn:aws:secretsmanager:region:account_id:secret:svcclusterAur-12345:username::'"
> ```
> 
> Note the single AND double quotes that would otherwise get swallowed by YAML :(
> 
> Does switching to that syntax help?

Oh gosh you're totally right! I never would have thought to do that! It does indeed do the trick.

Thank you all for the speedy help as always!
