### ISSUE TITLE
Do more validations in pipeline data model

### ISSUE THREAD

**Issue by hencrice** [aws/copilot-cli#221]
Since we haven't finalized the pipeline manifest, for now there's minimum validations in `internal/pkg/manifest/pipeline.go`

- [ ] `CreatePipeline()`
- [ ] `UnmarshalPipeline()`
- [ ] `WithProperties()`

**Comment by efekarakus** [comment]
The pipeline pkg got a lot more validation now as we onboarded CodeCommit and are working on BitBucket atm. 
Resolving the issue: https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/deploy/pipeline.go
