### ISSUE TITLE
doc: Does `task run` prompt users to specify a task group name today?

### ISSUE THREAD

**Issue by toricls** [aws/copilot-cli#2210]
Hello Copilots 👋

## Expected behavior

`task run --follow` asks me to input a `task group name`, according to the documentation, [the first example in the Example section](https://github.com/aws/copilot-cli/blob/v1.5.0/site/content/docs/commands/task-run.md#example) specifically.

> Run a task using your local Dockerfile. 
> You will be prompted to specify a task group name and an environment for the tasks to run in.
> ```
> $ copilot task run --follow
> ```

## Observed behavior

`task run --follow` only asked me to select a Copilot application and a Copilot environment, and it automatically used the directory name where I executed the command.

## Question

It looks like that `task run` defaults to the working directory name with [the current implementation](https://github.com/aws/copilot-cli/blob/v1.5.0/internal/pkg/cli/task_run.go#L383) when the taskGroupName is empty, and this is exactly what I observed. Should we update the `task run` doc I mentioned above or maybe am I missing something?

**Comment by Lou1415926** [comment]
Hello Tori! Thank you so much for finding this. You are not missing anything - the doc is outdated. `task run` is expected to default to the directory name instead of explicitly asking for a `task group name`. I have sent out a fix to the doc!

**Comment by toricls** [comment]
Thank you @Lou1415926 for the quick confirmation and the fix!
