### ISSUE TITLE
Help deploying simple Flask App

### ISSUE THREAD

**Issue by fjpa121197** [aws/copilot-cli#2214]
Hi guys, Im starting to learn AWS ECS and copilot and I have already done the example app deployment from their website and everything worked fine (sorry if I dont use the correct terms). However, Im now trying to deploy a python flask app that is very basic:

```
from flask import Flask, render_template

app = Flask(__name__)

@app.route('/home')
def index():
    return render_template('index.html')

if __name__ == "__main__":
    app.run(host='0.0.0.0',port = 80,debug = True)
```
And my Dockerfile is like:
```
#syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 80
CMD ["python", "app.py"]
```
I have already tested it locally and also building the docker image and running the container, and it works as expected. 
Then I do the copilot command to initialize the project, and I choose Load Balanced Web Service, choose port 80. However, at the last step, where it is creating the ECS task definition, service, load balancer, etc. My tasks keep failing and this failure event is given in the cli console:

```
service my-app-pachis-test-api-pachis-Service-fTra7yDqWq9U) (port 80)
         is unhealthy in (target-group arn:aws:elasticloadbalancing:REGION:
        8------:targetgroup/my-ap-Targe-1D3WWSFRHG9DB/6fc897c667fc2a24) d
        ue to (reason Health checks failed with these codes: [404]
```

I dont understand why. I'm doing something wrong in my docker file or app.py?

Thanks in advance

**Comment by kohidave** [comment]
Hello!!! By default copilot checks to make sure your service is healthy by sending a request to the ‘/‘ endpoint and making sure it returns a 200
Looks like your service only responds to /home so you can either:
Change the health check path in your manifest: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck

```manifest.yaml
http:
  healthcheck: '/home'
```

Or add a route to your flask app that returns 200 on the ‘/‘ path 
```main.py
@app.route('/')
def healthcheck():
  return “ok”
```

**Comment by kohidave** [comment]
> I just changed it, and add that route. However, I got a different error during the last step of initializing:
The following resource(s) failed to create: [PublicLoadBalancer]. The 
    following resource(s) failed to update: [ServiceDiscoveryNamespace
Any idea? I got it one time already, but I just re-run it and the error went away.

**Comment by fjpa121197** [comment]
Thanks again for helping!

**Comment by idelfonsog2** [comment]
> Hello!!! By default copilot checks to make sure your service is healthy by sending a request to the ‘/‘ endpoint and making sure it returns a 200 Looks like your service only responds to /home so you can either: Change the health check path in your manifest: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck
> 
> ```miniyaml
> http:
>   healthcheck: '/home'
> ```
> 
> Or add a route to your flask app that returns 200 on the ‘/‘ path
> 
> ```python
> @app.route('/')
> def healthcheck():
>   return “ok”
> ```

It should be documented or added it to the Getting started 👀

**Comment by ankitjet** [comment]
@idelfonsog2 Added the health check route but still container is failing so in my Dockerfile I am using python:3.10-slim-bullseye image in which trying LaTex dependencies like texlive and texlive-xetex > so it is building , uploading to ECR and then deploying to ECS but due to health check showing Unknown ECS draining out

**Comment by iamhopaul123** [comment]
Hello @ankitjet. Do you know why the tasks kept getting drained out? If the deployment event shown by Copilot while deploying is not very helpful, can you either run `copilot svc logs` or go to the ECS console and click into those stopped tasks and see their logs?
