### ISSUE TITLE
Unable to get SSM secret

### ISSUE THREAD

**Issue by j3lev** [aws/copilot-cli#2230]
Hey there, when I follow the documentation at https://aws.github.io/copilot-cli/docs/developing/secrets/#how-do-i-add-secrets, everything deploys fine and all of my environment variables except my secrets are defined.
I am creating the secret with:
```
aws ssm put-parameter --name API_KEY --value test123 --type SecureString\
  --tags Key=copilot-environment,Value=test Key=copilot-application,Value=myapp
```
and adding the definition in my manifest like so:
```
variables:
  DEMO: 1
  TEST: test

secrets:
  API_KEY: API_KEY
```
The secret shows up in console with the value populated correctly and running `copilot svc show` shows the secret as being there however it is undefined at runtime. Help would be appreciated in debugging this issue.

**Comment by efekarakus** [comment]
hi @j3lev ! I just wanted to make was the issue fixed or do you still experience the problem?

That's strange the secret should definitely be picked up by the tasks in your service as long as the tags match your environment and application names

**Comment by j3lev** [comment]
So I figured out what the issue was. For the example above, I was simplifying variable names to make stuff more readable. My environment variable was actually called `1PASSWORD_KEY`, when I renamed it to `PASSWORD_KEY`, it was defined. It looks like environment variables can't start with a digit in ECS?
