### ISSUE TITLE
Support deploying webapp to an internal VPC

### ISSUE THREAD

**Issue by dpca** [aws/copilot-cli#2233]
Hello! I'm interested in using copilot for an internally-facing app which would not be connected to the internet. I saw that in release 1.5.0 there's some support for launching tasks in private subnets, but I wasn't sure if this works with `copilot env init` yet because trying out that command and choosing an existing VPC yields this error message:

```
✘ No existing public subnets were found in VPC vpc-VPCID. You can either:
- Create new public subnets and then import them.
- Use the default Copilot environment configuration.✘ select public subnets: no existing subnets found
```

Am I on the right track, or are there plans to support functionality like this in copilot? Thanks!

**Comment by huanjani** [comment]
Hi, @dpca! 

As of right now, Copilot requires two public subnets and two private subnets in your VPC, whether it's Copilot-generated or pre-existing. (We require two (not one) so there can be one of each in each availability zone, following best practices.) 

In your use case, you surface a good point-- if you're using only the new `private` placement, you shouldn't have to bring a VPC with public subnets. We are still in the midst of rolling out support for this (see #1959), so we'll see what we can do to enable your use case! 

Thanks so much for the feedback!

**Comment by efekarakus** [comment]
This should be a small effort for us to just remove that error and enable this usecase. Marking it as a small issue.

**Comment by huanjani** [comment]
@dpca -- You can now deploy your app to an imported VPC without public subnets!
See https://github.com/aws/copilot-cli/releases/tag/v1.8.0. 

For fully isolated networking, see https://github.com/aws/copilot-cli/discussions/2378.

Thanks for the request!
