### ISSUE TITLE
Add ci mode for copilot deploy command

### ISSUE THREAD

**Issue by vymarkov** [aws/copilot-cli#2251]
aws copilot is an awesome tool that makes a lot easier to use ecs! Thanks for this tool!

currently I'm trying to adapt aws copilot for my stack   what I use within my project, I configured a github action pipeline to deploy my monorepo to ecs by copilot and I found that it produces a lot of logs, so it makes unmaintainable those logs for later usage.

You can find logs here:
https://github.com/lazyorangejs/nestjs-ng-workspaces/runs/2486113894?check_suite_focus=true

You need to take a look at `Deploy affected apps` step.

It looks like to introduce CI mode should let know copilot to don't make a lot of screen updates.

**Comment by iamhopaul123** [comment]
Hi @vymarkov. Thank you so much for the feedback. It totally makes sense to me!

**Comment by efekarakus** [comment]
Hi @vymarkov 

We're thinking of detecting the environment variable `CI=true` (https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables) and if so increase the render interval from `0.1s` to `30s` to reduce the number of logs we are spitting out.

**Comment by efekarakus** [comment]
#2440 should fix this!

**Comment by efekarakus** [comment]
This is now out in v1.8.0 🥳 https://github.com/aws/copilot-cli/releases/tag/v1.8.0
