### ISSUE TITLE
docs: possible typo in svc storage section

### ISSUE THREAD

**Issue by toricls** [aws/copilot-cli#2252]
In the `storage` section in [include/common-svc-fields.md](https://github.com/aws/copilot-cli/blob/48cf6adee52dc37ab5c04fcfdfdaa1b38155caef/site/content/docs/include/common-svc-fields.md), there is a sentence like "This allows you to access persistent storage across regions for data processing or CMS workloads.". But I was wondering that the `across regions` could be a typo, and it should be `across availability zones` (or `in a region`?) considering the characteristics of EFS.

**Comment by bvtujo** [comment]
You're so right! This is an error on my part, thanks for catching this!
