### ISSUE TITLE
manifest in source control?

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2253]
Noob question here. What is the point of generating manifest files under the copilot install directory instead my project where they would be kept under source control? Or perhaps I'm supposed to install copilot inside my project?

**Comment by iamhopaul123** [comment]
Hello @mikelhamer. The reason why you might want to keep the manifest files in source control is because of the pipelines. Under the hood the pipeline source the GH or the other provider and deploy your services/jobs. Without those manifests, the pipeline won't be able to deploy them. Hopefully that could clarify the issue. Also could you tell me if there is any concern for you to keep them under source control?

**Comment by mikelhamer** [comment]
> 
> 
> Hello @mikelhamer. The reason why you might want to keep the manifest files in source control is because of the pipelines. Under the hood the pipeline source the GH or the other provider and deploy your services/jobs. Without those manifests, the pipeline won't be able to deploy them. Hopefully that could clarify the issue. Also could you tell me if there is any concern for you to keep them under source control?

My concern is that I won't be able to store them in source control because they are generated in C:\copilot instead of inside my project. I would prefer to store them in source control.

**Comment by iamhopaul123** [comment]
Ideally the `copilot` folder should be placed in the workspace where your application (or part of your application locates or see [here](https://github.com/aws/copilot-cli/issues/2256#issuecomment-831407113)) so if you source control the workspace, the `copilot` folder and all the manifests within would be included as well.

**Comment by mikelhamer** [comment]
Oh, so then rather than installing on Windows via `Invoke-WebRequest -OutFile 'C:\Program Files\copilot.exe' https://github.com/aws/copilot-cli/releases/latest/download/copilot-windows.exe` we should use the directory of our project?

**Comment by iamhopaul123** [comment]
I think `Invoke-WebRequest -OutFile 'C:\Program Files\copilot.exe' https://github.com/aws/copilot-cli/releases/latest/download/copilot-windows.exe` this just helps to install the CLI. You could give it an alias and use it anywhere! For example after installation and alias it as `copilot`, then you could just go to the directory of your project and run `copilot app init` there.

**Comment by mikelhamer** [comment]
I did create an alias as you said, but even then running `copilot` inside my app it generates the manifest wherever I installed copilot in the first step.

**Comment by iamhopaul123** [comment]
That's really strange. Here's what i've been doing on my windows machine trying to reproduce the issue. I have my copilot executable in `C:\Program Files\copilot.exe` and then I created `C:\Users\iamho\Documents\profile.ps1` with
```
New-Alias -Name copilot -Value C:\Program Files\copilot.exe
```
When I was working on creating my application, I went to `C:\Users\iamho\flask-app` to run `copilot app init` and it created the `copilot` folder under my current directory.

**Comment by mikelhamer** [comment]
Hmmm interesting, and now that I think about it I do get an error when I run `copilot app delete` that it is unable to delete .workspace because it doesnt exist. And Im not actually creating an alias in that way, I am adding it to my PATH. Will need to take some time to recreate and confirm

**Comment by mikelhamer** [comment]
Confirmed that when I run `copilot init` in my project with copilot located at C:\copilot it creates the workspace and manifest files under C:\copilot.

When I delete the app with `copilot app delete` it deletes AWS resources successfully but I get the following error 
```
X Error deleting .workspace file.
X delete .workspace file: remove copilot\.workspace: The system cannot find the path specified.
```

**Comment by iamhopaul123** [comment]
Hello @mikelhamer sorry for the late reply. I cannot find the reason why the `copilot` folder was created in the wrong directory but for a workaround could you move the folder manually into the workspace? I think that might unblock `app delete` and the other commands.

**Comment by mikelhamer** [comment]
Not sure what was going on earlier but it's working now, thank you! Previously I had installed at `C:\copilot` instead of `C:\Program Files`. and this time I created a powershell alias instead of adding it to my path. Perhaps somehow a combo of those two things were the culprit.

**Comment by iamhopaul123** [comment]
Hello @mikelhamer. Great finding! Thank you for figuring out the reason. I am not very familiar with the Windows world but thank you for letting us know. I'll keep investigating and if it is the case we might want to note it in our doc for Windows installation.
