### ISSUE TITLE
Copilot should be able to deploy to multiple AZs

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#2260]
As a copilot user, I want to deploy Service to 3 Availability Zones with AWS Copilot, but it is pretty tough (see original request [here](https://dev.classmethod.jp/articles/aws-copilot-cannot-deploy-service-to-3az/):
- As a feature of Copilot, configuring ECS ​​tasks to deploy to 3AZ and 3 or more subnets is not supported.
- This is temporarily possible by directly updating the CloudFormation stack generated by Copilot.
- However, if you deploy the Service using Copilot after that, the stack will be overwritten and the subnet setting of the deployment destination will be returned.

**Comment by kohidave** [comment]
Related: https://github.com/aws/copilot-cli/issues/780 (and maybe tangentially related: https://github.com/aws/copilot-cli/issues/1298)

**Comment by huanjani** [comment]
Related: 
#2233 (don't require public subnets with custom VPC if not needed)
#2079 (allow fewer than two of each type of subnet even though not best practice)

**Comment by huanjani** [comment]
This is now released 🎉 in v1.14.0 https://github.com/aws/copilot-cli/releases/tag/v1.14.0 !
