### ISSUE TITLE
Ability to edit ECS params such as shm-size and tmpfs in Copilot Sidecar (linuxParameters on ECS Task Definition)

### ISSUE THREAD

**Issue by wstewarttennes** [aws/copilot-cli#2278]
Heyo -- I'm running into this issue: https://github.com/elgalu/docker-selenium/issues/20#issuecomment-133011186 when running a selenium container in a sidecar using copilot.  The only solution it seems, is to increase the /dev/shm size, but I don't see a way to do that through copilot.  I know this is pretty niche, but would be nice if there was a way to add custom linuxParameters, which seems like it would solve this issue (maybe there is a way to do this I'm not seeing?!) -- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters.

**Comment by iamhopaul123** [comment]
Hello @wstewarttennes. That sounds like to be very related to https://github.com/aws/copilot-cli/issues/948. Could you give a thumb-up on this issue and we will prioritize?

**Comment by wstewarttennes** [comment]
Will do, thanks!

**Comment by huanjani** [comment]
Closing this, as we now have overrides functionality.
