### ISSUE TITLE
Import VPC with Public Subnets

### ISSUE THREAD

**Issue by spensireli** [aws/copilot-cli#2287]
I'm trying to use the import feature. When selecting my existing VPC which it finds, it does not select the public subnets that are available. I saw [1724](https://github.com/aws/copilot-cli/issues/1724) was closed and the final comment was that this support is now available for launching tasks in private subnets with imported vpcs. Is this done outside of the import feature? 

Like the user in 1724, we do not auto-enable ipv4 on resources created in public subnets due to security concerns. 

```
What is your environment's name? 
Would you like to use the default configuration for a new environment?
    - A new VPC with 2 AZs, 2 public subnets and 2 private subnets
    - A new ECS Cluster
    - New IAM Roles to manage services and jobs in your environment
 No, I'd like to import existing resources
Which VPC would you like to use? vpc-xxx
✘ No existing public subnets were found in VPC vpc-xxx. You can either:
- Create new public subnets and then import them.
- Use the default Copilot environment configuration.✘ select public subnets: no existing subnets found
```

**Comment by iamhopaul123** [comment]
Hello @spensireli. Sorry for the inconvenience about the requirement we made for auto-enable ipv4. As a current workaround could you create two subnets with ipv4 on but place your tasks in private subnets instead? You can specify the task placement in the manifest [here](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network) before deploying your services.

Also, I've been curious by "for security concern you don't auto-enable ipv4", do you mean you don't enable ipv4 but ipv6 or the subnets shouldn't be directly facing publicly at all? Thank you!

**Comment by spensireli** [comment]
Thanks for the response @iamhopaul123 I will experiment some more based on what you sent over.  

As per the security concerns around subnetting that you are seeing from multiple users post, hopefully my explanation will help shed some light on some of the common configurations other organizations may have.  This also covers some of the standard security configurations that are backed by industry regulations such as PCI-DSS/HIPAA/ FedRamp etc. 

Our network architecture follows a NIST template that was designed by AWS several years ago (some modifications and updates done by us). It is my knowledge that this is still the "best practice" network architecture for three-tier web applications, even those running on ECS. A version of this can be found [here](https://aws.amazon.com/quickstart/architecture/compliance-nist/). 

A watered down explanation of this is that our version comprises of a VPC with a public and private subnet. Resources for compute are housed in the private subnets across multiple availability zones. Load balancers live in the public subnet with routes to the private subnet compute resources. Everything is locked down with security groups to restrict access to least privilege. 

Because of this we do not launch resources into public subnets and public facing infrastructure outside of our load balancers are undesirable. [This is actually an AWS config finding that will get flagged ](https://docs.aws.amazon.com/config/latest/developerguide/subnet-auto-assign-public-ip-disabled.html) if you are using any of the AWS Config managed rules. Furthermore other products such as [Palo Alto Prisma Cloud](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-policy-reference/configuration-policies/configuration-policies-build-phase/amazon-web-services-configuration-policies/policy_11743cd3-35e4-4639-91e1-bc87b52d4cf5.html) (i'm sure other vendors too) flag resources that have automatic public IP assignment as a security finding. 

Their security reasoning is the same as ours and many of the regulatory needs - "Assigning the Public IP to the subnet automatically (on launch) can accidentally expose the instances within this subnet to internet and should be edited to 'No' post creation of the Subnet."

**Comment by iamhopaul123** [comment]
Hi @spensireli. Thank you so much for the explanation. That clarified a lot of questions. Based on those concerns I think it placing tasks in the private subnets could solve the problem. Right now by default if you are placing tasks in private subnets then we'll create a NAT gateway for you so that the tasks can get access to all the other aws service like dynamodb or s3. In the future we will make NAT gateway to be optional but introducing VPC endpoint allowing those private tasks to be able to get access to those services without using the NAT gateway.

Generally we use security groups to control the inbound traffics to the tasks (by default we only allows inbound traffic from load balancer we created or the other tasks in the same security group). If your tasks don't handle sensitive internal data, maybe it's ok to place in public subnets. 

Edit: Hopefully this [guidance](https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/networking-outbound.html#networking-public-subnet) helps.

**Comment by spensireli** [comment]
@iamhopaul123 thanks for the response. Today we also use NAT gateways to route out to the internet. If copilot has capability of entirely bringing your own network that is what would be desired. We do not have the need (and would actually prefer if it didn't) for copilot to create a network for us. When trying to specify our existing VPC the private subnets don't get populated, it actually just fails out. For the reason of auto-enable ipv4 not being enabled. Even if we don't plan on putting tasks in the public subnet. 

We have been looking to use something like ecs-cli, ecs-cli v2, docker compose, and now this to help with deployment onto ECS environments and use it for management of service/task definitions only and not necessarily for creation of the ECS service and network (I understand that the purpose of this tool is to create the whole stack, but being able to use it in piecemeal would be ideal).

**Comment by iamhopaul123** [comment]
Hello @spensireli unfortunately we don't allow ECS service import but for the network import does [this workaround](https://github.com/aws/copilot-cli/issues/2287#issuecomment-836863973) to deploy in private subnets not work for you?

**Comment by huanjani** [comment]
@spensireli 
Related: https://github.com/aws/copilot-cli/pull/2356
