### ISSUE TITLE
Creating addon fails: change set has no changes

### ISSUE THREAD

**Issue by sugarjig** [aws/copilot-cli#2293]
I'm trying to add a Redis cluster to my service following the instructions at https://github.com/aws/copilot-cli/discussions/2011. I was able to create on my first try, but then updates to it failed, similar to what happened in #2089. I tried deleting my app and starting over, but now I cannot add the addon at all. Whenever I try to run `copilot svc deploy` with the addon in place, I get `deploy service: change set with name copilot-xxx for stack xxx has no changes`.

**Comment by iamhopaul123** [comment]
Hello @sugarjig. That sounds very related to https://github.com/aws/copilot-cli/issues/2257. We've been implemented a fix for it and would be included in our next release. Please stay tuned. As for the reason I think it could be possible that you have a bad reference in your addons template that's not resolvable by CFN. Could you check your CFN template or see the changeset that's been created in the aws console to see the real reason why the changeset cannot be executed? Thank you!

**Comment by efekarakus** [comment]
If you don't mind sharing with us your addon template, we can also help troubleshoot it!

**Comment by sugarjig** [comment]
It turned out that I was trying to access a return value that `CacheCluster` doesn't support. I'm able to deploy the addon now!

**Comment by iamhopaul123** [comment]
Nice! Glad to hear.

**Comment by efekarakus** [comment]
Awesome, resolving the issue now :D
