### ISSUE TITLE
App level addons

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2296]
The documentation here explains how to create addons at the service level
https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/

Is there any way to create them at the app level?

My use case is that I would like to addon a security group and IP prefix at the app level and pass that to each service manifest as an env var or something to add the security group to the network security groups section.

**Comment by efekarakus** [comment]
Related to #1368 and #1975

We don't have a great way to do that unfortunately at the moment. In the mean time, here are some possible workarounds:

1. Create the security group in a separate CloudFormation stack outside of Copilot and then modify the manifest files with the security group ID.
2. To emulate an app-resource, you can create a scheduled job with `job init` that never gets triggered and create the security group under `addons/`. This will keep everything within Copilot, but has the downside of being awkward under a never triggered scheduled job.
3. Create the security group as part of `addons/` under one of the services. We will automatically attach the security group to your service if you create an Output referring to the resource. Then you can modify the manifest of the remaining services to use the new security group ID.

**Comment by mikelhamer** [comment]
@efekarakus oh nice, glad I'm not the only one with this idea.

Thanks for the workarounds! Option #1 is what I'm thinking for now.

**Comment by efekarakus** [comment]
Sounds good! I'll close the issue in favor of #1975 would you mind giving a 👍 to that issue as well. I'll try to consolidate all the feedback under that issue.
