### ISSUE TITLE
Listen on ports instead of paths

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2297]
I noticed the generated load balancer listens on port 80 for all services and then forwards to a service based on the path.

If possible I would like to have a listener for each port  that can forward on any path with /

So if I have my frontend on port 80, any path on port 80 will go to my frontend.
If I have an api on port 8080, any traffic on port 8080 will go to my api.

is this possible?

The way it currently works it seems I couldnt have any service on the default path of / because it would catch all traffic that would normally go to my other services. I have to set the base path configuration manually in various ways for each of my services (I mean in my code, not the manifest).

**Comment by efekarakus** [comment]
Related #1304, I think this will be supported once we allow a Network Load Balancer as an option. Would you mind giving a 👍  to that issue? 🙏

**Comment by mikelhamer** [comment]
Oh sweet, done!

**Comment by Lou1415926** [comment]
Hello friends! We have a proposal for supporting network load balancer in #2918. Please Feel free to take a look - we'd love to hear your thoughts!

**Comment by dannyrandall** [comment]
Closing this issue as we released network load balancer support a while ago! Here's our documentation on it: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#nlb
