### ISSUE TITLE
Temporarilly stop a running service

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2298]
Is there any way to stop a cluster / service? Like if I just want to pause it for a time, then resume later? If so, how would I then start it back up?

**Comment by Lou1415926** [comment]
Hi @mikelhamer!

Currently ECS does not support stopping an ECS cluster or ECS service. However, you can stop and start new tasks in your ECS service. 

To do this through Copilot, you can set the `count` field to 0 in the service's manifest, and then run `copilot svc deploy`. This way your ECS service orchestrator will maintain 0 tasks, effectively it is pausing your service.

Later when you want to resume the service, you can just set the `count` to your desired number, and then `copilot svc deploy`.

Does this help your use case?

**Comment by mikelhamer** [comment]
Exactly what I needed, thanks!
