### ISSUE TITLE
Strange text on `{app/env} init` outputs

### ISSUE THREAD

**Issue by toricls** [aws/copilot-cli#2299]
I'm seeing `WWWWWWWW` in the terminal outputs during `app init` and `env init` executions as below.

<img width="119" alt="Screen Shot 2021-05-11 at 6 57 42 PM" src="https://user-images.githubusercontent.com/3761357/117833202-1834c880-b2b1-11eb-86a8-5427afb6ccc9.png">

This actually doesn't affect/block Copilot functionalities to me but it's just strange 😇

(The root cause could be my buggy zsh configuration or something but I also got my fellow DA today who reported the same thing)

**Comment by toricls** [comment]
I got a nice tip "it happens if the terminal screen is too small". Will check it and update here with the result :)

**Comment by hkford** [comment]
I got the same outputs when making font size bigger.

This is Cloud9's outputs during `app init` (terminal font size is 12).
![スクリーンショット 2021-05-12 9 32 14](https://user-images.githubusercontent.com/82389275/117901150-b94d6e80-b305-11eb-9291-9ec5cdb3b9ae.png)

This is Cloud9's outputs during `app init` (terminal font size is 24).

![スクリーンショット 2021-05-12 9 34 10](https://user-images.githubusercontent.com/82389275/117901247-e4d05900-b305-11eb-8573-2a78aad765bb.png)

**Comment by toricls** [comment]
Confirmed that the terminal size was the root cause. Closing :)
