### ISSUE TITLE
pipeline init help menu-- list available sources 

### ISSUE THREAD

**Issue by huanjani** [aws/copilot-cli#2316]
We should surface to users earlier in the pipeline workflow what the possible repo sources are (GitHub, CodeCommit, Bitbucket).

`pipeline --help`
`pipeline init --help`
at the very least, possibly `pipeline update(/deploy) --help` as well...

**Comment by kangere** [comment]
@huanjani I am interested in working on this issue,

**Comment by huanjani** [comment]
Thanks so much, @kangere, for expressing interest in working on this!
Just to get you pointed in the right direction...

This is how the help menu for `copilot pipeline init` currently looks:
```
% copilot pipeline init --help
Creates a pipeline for the services in your workspace, using the environments associated with the application.

Usage
  copilot pipeline init [flags]

Flags
  -a, --app string             Name of the application.
  -e, --environments strings   Environments to add to the pipeline.
  -b, --git-branch string      Branch used to trigger your pipeline.
  -h, --help                   help for init
  -u, --url string             The repository URL to trigger your pipeline.

Examples
  Create a pipeline for the services in your workspace.
  `$ copilot pipeline init \`
  ` --url https://github.com/gitHubUserName/myFrontendApp.git \`
  ` --environments "stage,prod"`
```
We are envisioning the addition of a line listing supported providers, like
```
% copilot pipeline init --help
Creates a pipeline for the services in your workspace, using the environments associated with the application.

Usage
  copilot pipeline init [flags]

Flags
  -a, --app string             Name of the application.
  -e, --environments strings   Environments to add to the pipeline.
  -b, --git-branch string      Branch used to trigger your pipeline.
  -h, --help                   help for init
  -u, --url string             The repository URL to trigger your pipeline.
Supported providers are: GitHub, Bitbucket, CodeCommit.

Examples
  Create a pipeline for the services in your workspace.
  `$ copilot pipeline init \`
  ` --url https://github.com/gitHubUserName/myFrontendApp.git \`
  ` --environments "stage,prod"`
```

If you add a something like 
```
var PipelineProviders = []string{
"GitHub"
"Bitbucket"
"CodeCommit"
}
```
to https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/manifest/pipeline.go, you can use `PipelineProviders` in https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/cli/pipeline_init.go

Let me know if you have questions or thoughts on this!
Thanks again.

**Comment by kangere** [comment]
@huanjani For this changes, would I need to make the changes on a fork of the repository then create a pull request for review when I am ready?

**Comment by huanjani** [comment]
Yes, exactly!

**Comment by kangere** [comment]
@huanjani  could you review my PR
