### ISSUE TITLE
Lambdas?

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2328]
I was a little surprised to see my copilot app generated Lambda Applications and Lambda functions for all of my services and environments. There is no mention of lambdas in the docs.

What is the reason for this?

**Comment by bvtujo** [comment]
Hi @mikelhamer, the lambdas are part of the Cloudformation Custom Resources we create as part of the app or service. We use them to get around some limitations of CloudFormation, like our cross-account DNS delegation, our as-needed creation of ALB and EFS, and a known issue with ECS rolling deployments that would reset the desired count of an autoscaling configuration which had undergone scaling events.

**Comment by mikelhamer** [comment]
Very cool, thanks for the explanation.
