### ISSUE TITLE
Issue in running Copilot on Windows 10

### ISSUE THREAD

**Issue by sundarnarasiman** [aws/copilot-cli#2330]
I have an issue in running Copilot on Windows 10. I'm getting this error' This app can't run on your pc', when i try to launch Copilot from Command Prompt as administrator. Any clue to fix this one ?

**Comment by iamhopaul123** [comment]
Hey @sundarnarasiman. Sorry to hear about that. I didn't experience on my PC before and have no clues why this. I tried to find some info about how to fix this issue. Can you try [this troubleshooting](https://www.easeus.com/computer-instruction/this-app-cant-run-on-your-pc-in-windows-10.html#fix2) or [this tutorial](https://www.youtube.com/watch?v=Oryzlo07cwQ) to see if the error goes away? Thank you!

**Comment by RoniqueRicketts** [comment]
I don't the installation for Windows is sufficient. I am unable to install it on my Windows PC either.
