### ISSUE TITLE
Dynamodb addon IAM Task Execution Role has an uppercase Index in Resource

### ISSUE THREAD

**Issue by AndrchiamusI** [aws/copilot-cli#2362]
When using copilot storage init to create a dynamodb addon, the resource type **index** is incorrectly set with a capitol I. It should be lowercase as per the [documentation](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html) 

          - Sid: DDBLSIActions
            Action:
              - dynamodb:Query
              - dynamodb:Scan
            Effect: Allow
            Resource: !Sub ${ Service.Arn}/Index/*

**Comment by toricls** [comment]
Hi @andrew-nye, thank you for letting us know! I think this should be addressed by https://github.com/aws/copilot-cli/pull/2349, could you take a look at it?

**Comment by AndrchiamusI** [comment]
Perfect, sorry I did search current issues. Thanks!

**Comment by efekarakus** [comment]
The fix is now out in v1.7.1! https://github.com/aws/copilot-cli/releases/tag/v1.7.1
