### ISSUE TITLE
Allow `image.build.options` in Manifest to control `docker build` behavior

### ISSUE THREAD

**Issue by michaelfedell** [aws/copilot-cli#2369]
Developing on Apple M1 and as `arm64` based images are not compatible with Fargate, I've typically solved this by building with `docker build --platform linux/amd64` or `docker build --platform linux/x86_64`. Unfortunately, there's no way to pass in that `--platform` option to the docker build command from `manifest.yml`

It would be great if additional build options could be set in a flexible `options` map, similar to `image.build.args` as described in the [docs](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image)

**Comment by michaelfedell** [comment]
Current workaround is to manually build and push the image to an ECR repo and adjust the manifest to set `image.location` to the manually pushed image.

**Comment by kohidave** [comment]
Totally agree! Thanks for the feedback - we'll try to get to this soon! 

Related: https://github.com/aws/copilot-cli/issues/1949

**Comment by toricls** [comment]
@michaelfedell Wrote a workaround here! https://github.com/aws/copilot-cli/issues/1949#issuecomment-858248930

In summary, you can basically specify the platform by the environment variable `DOCKER_DEFAULT_PLATFORM` 🙌

**Comment by huanjani** [comment]
Closing in favor of #1949.

**Comment by Lou1415926** [comment]
The feature is now released in [v1.9.0](https://github.com/aws/copilot-cli/releases/tag/v1.9.0)! 🎊
