### ISSUE TITLE
Copilot generates the same discovery ep for prod and test?

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2374]
I created an app and using --domain flag so we can use our own domain name.
I added prod and test environments.

However, when I deploy like this:

```
copilot svc deploy --name user-service --env test --tag v1
```

I get this service discovery ep, no matter if it's prod or test env:

```
user-service.coretailcom.local:9000
```

Shouldn't the env be part of the URL here? I mean how can differentiate between prod and test deployments then? Should they use different ports? These are supposed to be running on their own dedicated virtual machines, so this is strange.
I expected copilot to generate something like:

user-service.test.coretailcom.local:9000
user-service.prod.coretailcom.local:9000

What am I doing wrong here?

Thanks in advance!

**Comment by kohidave** [comment]
Howdy! The service discovery name is local to the VPC you're service is deployed in - and the assumption is, every environment will get its own VPC.

So even though the service discovery endpoint is the same in each environment, they resolve differently depending on which environment you're in :)

(tl;dr prod `.local` resolves to services in the prod environment, test `.local` resolves to services in the test environment)

**Comment by gtamas** [comment]
oh ok I see! Thanks for the clarification!
