### ISSUE TITLE
Trying to deploy new version of existing service produce error "generate stack template: read rule priority lambda: read template custom-resources/alb-rule-priority-generator.js: no such file or directory"

### ISSUE THREAD

**Issue by pcolazurdo** [aws/copilot-cli#2375]
I have an existing project that I want to redeploy from an existing folder and found that I'm unable to do so.

```
copilot svc deploy
Service name: root-endpoint
Only found one environment, defaulting to: test
✘ execute "env upgrade --app modernization-lab --name test": upload custom resources to bucket (edited): read template custom-resources/dns-cert-validator.js: stat /home/ec2-user/environment/monolithic-modernization-lab/copilot/root-endpoint/custom-resources/dns-cert-validator.js: no such file or directory
```

I don't have any ```custom-resources/``` folder anywhere.

I find the experience of redeploying previous projects is not very clear to me so probably I'm missing something. 

Any help will be highly appreciated

**Comment by kohidave** [comment]
Hi! How did you install Copilot? Can you run `copilot --version`? 

If you're on a mac, try this: `$ brew install aws/tap/copilot-cli`

On another platform, you can try this: https://aws.github.io/copilot-cli/docs/getting-started/install/

(the error you're seeing tends to result from an improperly built copilot binary)

**Comment by pcolazurdo** [comment]
I installed copilot using homebrew on Linux

copilot version: v1.7.0

**Comment by kohidave** [comment]
Did you do `brew install copilot-cli` ? if so, could you use the AWS tap instead? `brew install aws/tap/copilot-cli`

**Comment by pcolazurdo** [comment]
You were right, looks like having the TAP added to homebrew is not enough in this case and I need to point to it directly. Thanks for your help
