### ISSUE TITLE
Copilot is not spinning a new environment

### ISSUE THREAD

**Issue by sojanthomas-st** [aws/copilot-cli#2377]
I have already an existing environment with the below command.

copilot app init --domain 604bf005.dev.r53.aws.it.ucla.edu

copilot env init --name test --profile default --app iwe-menu-collector --import-vpc-id vpc-0b5ab45
182ebf60e9 --import-public-subnets subnet-056dd707c4383deb5,subnet-0c20ad569c56edb97 --import-private-subnets subnet-081710bb5e50f79c8,
subnet-0d80d8c4cf29b6746

Today I tried to spin another environment called dev by using the below command.

copilot env init --name dev --profile default --app iwe-menu-collector --import-vpc-id vpc-0b5ab45
182ebf60e9 --import-public-subnets subnet-056dd707c4383deb5,subnet-0c20ad569c56edb97 --import-private-subnets subnet-081710bb5e50f79c8,
subnet-0d80d8c4cf29b6746

I am getting the below error and failed to initialize the environment.

      - ServiceDiscoveryNamespace
      - CREATE_FAILED 
      - The VPC vpc-0b5ab45182ebf60e9 in region us-west-2 has already been associated with the hosted zone Z07149982IL1TGMGOEPNF 	with the same domain name. (Service: AmazonRoute53; Status Code: 400; Error Code: ConflictingDomainExists; Request ID: 	cafe874c-9298-4a88-8595-ea5b0de263b5; Proxy: null)

As per the documentation, I should be able to use same domain to spin up another environment.  Please see below.

https://aws.github.io/copilot-cli/docs/concepts/environments/
Optionally, when you set up an application, you can provide a domain name that you own and is registered in Route 53. If you provide a domain name, each time you spin up an environment, Copilot will create a subdomain environment-name.app-name.your-domain.com, provision an ACM cert, and bind it to your Application Load Balancer so it can use HTTPS.

**Comment by bvtujo** [comment]
Hey @sojanthomas-st, Copilot doesn't support more than one environment per VPC. The reason is that we use the same service discovery namespace (`appname.local`) regardless of environment, so you don't need to make changes on a per environment basis to your service code. When you try to create a new environment within the same VPC, the discovery service can't create because of the namespace conflict. 

Could you describe your use case a little more? is it possible for you to use separate VPCs for each environment?

**Comment by sharepointoscar** [comment]
> Hey @sojanthomas-st, Copilot doesn't support more than one environment per VPC. The reason is that we use the same service discovery namespace (`appname.local`) regardless of environment, so you don't need to make changes on a per environment basis to your service code. When you try to create a new environment within the same VPC, the discovery service can't create because of the namespace conflict.
> 
> Could you describe your use case a little more? is it possible for you to use separate VPCs for each environment?

So, just to be clear:  You are saying that if I have a registered and managed subdomain like **apps.lab.io** and I want to deploy 2 apps in the same VPC, importing the VPC and subnets at the time I create each environment.  If I try to create two apps as follows:

1. `dev.apps.lab.io`
2. `staging.apps.lab.io`

I cannot do that?  Isn't the DNS entry created in a way that the environment is a prefix?

**Comment by iamhopaul123** [comment]
Hello @sharepointoscar. I think two services within the same VPC is fine. It's just we don't allow users to reuse the same VPC for multiple environments for now, due to the limit of the service discovery namespace. 

In your example I'm not sure what `env` and `staging` are. If they are env names then it is not what we are doing right now since the SD endpoint for each service is formatted as `${svcName}.${appName}.local` which doesn't contain the environment name.

**Comment by sharepointoscar** [comment]
Ha, thanks @iamhopaul123  I see the issue.  Right, there would be service discovery issues given the endpoint does not include or is prefixed with the environment, like `${env}.${svcName}.${appName}.local`

**Comment by sojanthomas-st** [comment]
Requirement USE CASE as follows,
1) I have deployed the application on "test" environment using copilot init with hosted zone, existing VPC, and Private Subnet.
2) Now, I have to create a new environment called "dev" with same hosted zone, VPC, and Private Subnet.

**Comment by huanjani** [comment]
Gotcha, @sojanthomas-st! 

As @bvtujo and @iamhopaul123 mentioned, Copilot can't support multiple environments in one VPC at the moment. Thanks for bringing this limitation to our attention; we'll see what we can do to enable your use case. Thank you!

**Comment by sojanthomas-st** [comment]
Thanks for your response. Hope we can expect some updates from you soon regarding this.

**Comment by Ashniu123** [comment]
This feature is crucial for my team to adopt copilot as the devops tool for managing ecs. Can we please prioritise this issue and make it to the next release? 
If any help is required, I am willing to contribute to the existing PR.

**Comment by bvtujo** [comment]
@Ashniu123 I'm wrapping this up literally this afternoon; apologies there hasn't been movement on the PR for a little while. We'll have this feature out in 1.9.0, which should  sometime in the next two weeks!

**Comment by efekarakus** [comment]
Hi everyone! Looks like we forgot to close this issue 🙇 the fix was merged in #2515 and released in v1.9: https://github.com/aws/copilot-cli/releases/tag/v1.9.0 

Let us know if you run into this problem again, thanks!
