### ISSUE TITLE
Request-Driven Web Service (App Runner) Creates Unnecessary Resources

### ISSUE THREAD

**Issue by tonycapone** [aws/copilot-cli#2399]
It seems that when running `copilot init` with the new **Request-Driven Web Service/App Runner** workload type, and deploying a test env, copilot creates many resources, including VPC, subnets, Internet Gateways, and an ECS cluster; as if the workload type was an ECS task. 

Not only are these resources unnecessary for an App Runner service, but wasteful since it could contribute towards service quotas.  

I presume if I was using App Runner as an add-on to an existing ECS based application it wouldn't be as big of a deal, but for someone just getting started with App Runner and copilot, it could be an unwelcome surprise.
 
Example:

```
Use existing application: No
Application name: myapp
Workload type: Request-Driven Web Service
Service name: myapp
Dockerfile: ./Dockerfile
Ok great, we'll set up a Request-Driven Web Service named myapp in application myapp listening on port 8080.
```

```
All right, you're all set for local development.
Deploy: Yes

Proposing infrastructure changes for the myapp-test environment.
- Creating the infrastructure for the myapp-test environment.        [create complete]    [79.0s]
  - An IAM Role for AWS CloudFormation to manage resources               [create complete]    [14.4s]
  - An ECS cluster to group your services                                [create complete]    [13.4s]
  - Enable long ARN formats for the authenticated AWS principal          [create complete]    [4.0s]
  - An IAM Role to describe resources in your environment                [create complete]    [14.5s]
  - A security group to allow your containers to talk to each other      [create complete]    [7.4s]
  - An Internet Gateway to connect to the public internet                [create complete]    [15.9s]
  - Private subnet 1 for resources with no internet access               [create complete]    [16.3s]
  - Private subnet 2 for resources with no internet access               [create complete]    [16.8s]
  - Public subnet 1 for resources that can access the internet           [create in progress]  [49.7s]
  - Public subnet 2 for resources that can access the internet           [create complete]    [16.8s]
  - A Virtual Private Cloud to control networking of your AWS resources  [create complete]    [18.3s]
  - 
  ```

**Comment by iamhopaul123** [comment]
Hello @tonycapone. Sorry for those unnecessary environment resources Copilot creates for you. If you also need to create other service types then these are resources that could be shared across those services. Unfortunately for now if you are just using the app runner then these resources are not useful at all. And this is an enhancement we need to make. Thank you so much for bringing it up!

**Comment by huanjani** [comment]
Hi, @tonycapone!
You can now connect an App Runner service to a VPC, so the created resources are now more useful.
AWS Copilot v1.15.0 is now released! https://github.com/aws/copilot-cli/releases/tag/v1.15.0 🎉🚀
