### ISSUE TITLE
Default svc execution policy does not work with ssm path parameters

### ISSUE THREAD

**Issue by ezet** [aws/copilot-cli#2402]
The default service execution policy only allows `ssm:GetParameters`, which does not work with parameters defined with a path. Using paths makes it a lot easier to organize parameters. Could you please add `ssm:GetParametersByPath` to the default policy?

**Comment by iamhopaul123** [comment]
Hello @ezet. Sorry I might misunderstand the question but it seems like the service execution role is just for the Fargate agent to make API calls on your behalf. Would you mind elaborating the reason why you need to get parameters defined with a path? Thank you!
