### ISSUE TITLE
Pipeline failing at the deploy stage

### ISSUE THREAD

**Issue by paulca** [aws/copilot-cli#2408]
Hi,

I've muddled my way through setting up a `test` and `live` environment for a Rails app. Deploys work great from the command line.

I set up a pipeline and got the tests running using `docker-compose`. Great!

When I push to GitHub, a build is kicked off and the tests run.

<img width="488" alt="CleanShot 2021-06-01 at 14 37 44@2x" src="https://user-images.githubusercontent.com/1229/120332855-0b6f2780-c2e7-11eb-8e59-76374749b35d.png">

The build succeeds, but then the deploy to test gets stuck on `UPDATE_IN_PROGRESS`

<img width="471" alt="CleanShot 2021-06-01 at 14 39 03@2x" src="https://user-images.githubusercontent.com/1229/120332978-293c8c80-c2e7-11eb-8375-2c7327074e46.png">

CloudFormation looks like it's attempting to do a lot more than when I run `copilot deploy` on the command line, but I don't know where to look to get a debug log. I'm stuck!

<img width="1111" alt="CleanShot 2021-06-01 at 14 39 57@2x" src="https://user-images.githubusercontent.com/1229/120333078-41141080-c2e7-11eb-83b8-4489354d3a8b.png">

Any pointers would be greatly appreciated! It would be great if `copilot pipeline status` gave me a bit more insight into what was going on, other than just `InProgress`

**Comment by iamhopaul123** [comment]
Hello @paulca. From the screenshots you uploaded I don't see any issue. Did the cloudformation stack creation/update fail? Could you include more logs for it (if it is the service failing to create then you might want to go to the ECS console to see the service event log there). Sorry for the inconvenience! Agree maybe `pipeline status` should give more details about the reason especially when the pipeline fails.

**Comment by paulca** [comment]
Thanks for the reply @iamhopaul123 ... the CloudFormation update is still ongoing, and has been for 52 minutes.

Oh, it JUST failed!

![CleanShot 2021-06-01 at 15 07 58@2x](https://user-images.githubusercontent.com/1229/120337414-32c7f380-c2eb-11eb-9d54-0703694bab93.png)

I'm pretty sure that it's not the service failing, because `copilot deploy` from my local machine works just fine. I had a number of issues when setting everything up, but I managed to work through them, so I got familiar with where to look for errors in ECS.

**Comment by paulca** [comment]
Oh, here's some more from ECS:

<img width="601" alt="CleanShot 2021-06-01 at 15 11 48@2x" src="https://user-images.githubusercontent.com/1229/120337993-b681e000-c2eb-11eb-9c7c-bfb17622ab0d.png">

Do you know if there's anywhere I can look in the pipeline to get a log of it attempting to deploy?

**Comment by paulca** [comment]
Apart from adding the test runs (which pass), I didn't change the boilerplate copilot buildspec.yml, so I was expecting this to "just work".

**Comment by iamhopaul123** [comment]
OK then this is the ECS service update fail. Unfortunately you might have to go to the ECS console to see why those failing tasks cannot spin up. Since our pipeline picks up the latest commit, it is possible you modified your local app to make `copilot deploy` works but didn't commit the change and push to the upstream?

**Comment by paulca** [comment]
Here's the output of the local deploy:

<img width="750" alt="CleanShot 2021-06-01 at 15 22 34@2x" src="https://user-images.githubusercontent.com/1229/120339754-496f4a00-c2ed-11eb-9699-143fdc4ca9e6.png">

I definitely wouldn't have local changes, since the pipeline is pushing from the latest code...!

**Comment by iamhopaul123** [comment]
That's strange. Could you look at the failed tasks by your pipeline to see the reason why it failed to start? Most likely it is either because of the lack of task role permissions or the health check didn't pass.

**Comment by paulca** [comment]
@iamhopaul123 Oh, I'm not sure why I didn't look there sooner. The logs in the failed tasks are showing me exactly what went wrong. I wonder why it works when I deploy locally but not from CodePipeline.

In any case, that gives me something to work with!

It would be **great** if `copilot` surfaced the failed state of the latest ECS task.

**Comment by iamhopaul123** [comment]
@paulca ooh since it's just a service update failure I think https://github.com/aws/copilot-cli/pull/2355 could perfectly address this issue! If you just run `copilot svc status --with-stopped` then it would show you all stopped tasks of the service with the reason! It is expected to be included in our next release.

**Comment by paulca** [comment]
@iamhopaul123 Sounds good. Looking forward to the update!
