### ISSUE TITLE
Does it make sense to use PM2 with copilot deployed Fargate instances?

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2409]
So our prod instances all use the cpu setting 1024. If I'm not wrong about this, that means 1 vCPU.

Does it make sense to run our NodeJS based backends using PM2? I mean ECS already takes care about horizontal scaling, but what about scaling vertically? PM2 should cover that. But it was designed with real CPU cores in mind, and I'm not sure if it makes sense in the world of VCPUs.

Any suggestions?

Thanks in advance.

**Comment by iamhopaul123** [comment]
Heya @gtamas. I don't think it make a lot of sense to use PM2 for vertical scaling in the ECS world especially for Fargate, since even if a container crashes ECS will quickly replace it with a new one. Do you have any specific use case that would require vertical scaling?

**Comment by gtamas** [comment]
OK I see thanks.
We do not have any special need for PM2, I just want to maximise the performance as much as possible. But I think ECS horizontal scaling also fine.
