### ISSUE TITLE
Is there any way to generate the CloudFormation json/yaml for the initial environment

### ISSUE THREAD

**Issue by davewthompson** [aws/copilot-cli#2410]
Hey there,

Is there any way we can generate the CloudFormation YAML/JSON which generates the environment (during init) that the `svc package` command references?

Right now I'm trying to run the CloudFormation script that is generated during `svc package` in a clean environment (so we don't run any `copilot` commands in production) and said deployment fails with a missing import inside the CloudFormation console (`No export named blah-production-VpcId found. Rollback requested by user.`)

Thank you very much,

Dave Thompson

**Comment by iamhopaul123** [comment]
Hello @davewthompson. Sorry we don't have a command to generate the CFN template for the environment. If you created the environment using `env init` then I would expect the CFN should be able to import the VPC when you deploy the service template. Or am I missing anything?

**Comment by davewthompson** [comment]
Thanks for your response!

We’re looking at isolating our production environment completely from Copilot so ideally we’d be able to run the two CloudFormation scripts as part of a managed release.

No worries, though; we shall keep playing around with manually creating the environment with CloudFormation first.

**Comment by huanjani** [comment]
If the VPC is the only missing piece, you could create just the VPC externally then import that when you run `copilot env init`....

**Comment by davewthompson** [comment]
We'll take a look, thanks. Right now it seems it's just missing (for future reference, if someone finds the same question):
- ClusterId,
- EnvironmentSecurityGroup,
- HostedZone,
- PublicSubnets,
- ServiceDiscoveryNamespaceID,
- SubDomain,
- VpcId

Seems like it's primarily missing the VPC and Route53 configuration with a dash of IAM. I'll document how we get around it if we work it out in this issue.

Thanks for your help, everyone - much appreciated.

**Comment by davewthompson** [comment]
This can be closed; we have captured all CloudFormation scripts from the web-based console.
