### ISSUE TITLE
pipeline: I want to create a pipeline for multiple services in a single GitHub repository

### ISSUE THREAD

**Issue by haze-it** [aws/copilot-cli#2431]
I'm trying to create two services using a single GitHub repository.

The repository already has one service and pipeline set up, and I can `git push` it to complete the deployment.
I tried to create a service that uses the source code of that repository and runs it with another command.

The `copilot svc init` completes successfully, so when I run `copilot svc ls`, there are two services.

(Of the two services, let's say the existing service is A and the newly launched service is B. )
However, when I run the `copilot pipeline init`, it does not create a pipeline for the B service.
I did a `git push` and ran the `copilot pipeline update`, but it only runs the pipeline for the A service.

```
$ copilot svc ls
Name                Type
----                ----
A                   Backend Service
B                   Backend Service
```

```
$ copilot pipeline status
Pipeline Status

Stage                               Transition          Status
-----                               ----------          ------
Source                              ENABLED             Succeeded
└── SourceCodeFor-APP_NAME                              Succeeded
Build                               ENABLED             InProgress
└── Build                                               InProgress
DeployTo-development                ENABLED             Succeeded
└── CreateOrUpdate-A-development                        Succeeded

...
```

I want to create a `CreateOrUpdate-B-development` in `DeployTo-development`, is there any way?

( Note that both repositories A and B are created in ECR by the process of `buildspec.yml`, and both Docker Images are created. )

I also checked a similar issue: https://github.com/aws/copilot-cli/issues/2109, but unlike this example, the repository is not separated by service.

If this is not possible with the current copilot cli, it would be very helpful for me to be able to specify something like `copilot pipeline update --service-name B`.

Thanks for reading.

**Comment by efekarakus** [comment]
Hi @haze-it 👋 Thank you for the detailed issue !

After running `copilot svc init` for your service B, and after running `copilot pipeline update` do you not see the new action appear in CodePipeline?  
![Screen Shot 2021-06-09 at 11 23 16 AM](https://user-images.githubusercontent.com/879348/121408301-1cd2b800-c915-11eb-8a9a-405001d48f5c.png)

I followed similar steps to above, where I created a pipeline for only the "frontend" service first, and then ran `copilot svc init` for the "backend" service and updated the pipeline, but the pipeline updated as expected in the screenshot above.

Note that `copilot pipeline status` won't show the new action until it starts running, but in the console I can see that the new action is created.

Thank you!

**Comment by haze-it** [comment]
@efekarakus 
Thanks for the reply and the test!

Looking at the console, I can confirm that the pipeline is created as I had hoped.

Thank you very much!

![スクリーンショット 2021-06-10 10 02 07](https://user-images.githubusercontent.com/31850710/121449684-405d3780-c9d5-11eb-978b-419c7d64ea55.png)
