### ISSUE TITLE
Image cache layers not being used in pipeline

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2433]
Whenever my piepline executes it runs all layers of the Dockerfile in each service. This makes it take forever during the build step. Shouldn't it being using a cache?

**Comment by bvtujo** [comment]
related: #2344

Hey @mikelhamer, thanks for pointing this out. We have an open issue to track this cache behavior--please give it a thumbs up if it's important to you and we'll prioritize it in a future sprint.
