### ISSUE TITLE
pipeline: copilot not seeing manually created codestar connection

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#2436]
I manually created the connection with the name Default and in the pipeline.yaml I have:

  properties:
    branch: branch-name
    repository: https://github.com/repo/url
    connection_name: Default # Optional: specify the name of an existing CodeStar Connections connection.

Copilot continues to ignore the connection_name and try to create its own.

**Comment by efekarakus** [comment]
Hi @h5aaimtron ! Is the connection created in the same account and region as the pipeline?

**Comment by h5aaimtron** [comment]
@efekarakus yeah the connection was made in the same account and region.

**Comment by huanjani** [comment]
@h5aaimtron Did you push the updated pipeline yaml to your repo before running `pipeline update`?

**Comment by h5aaimtron** [comment]
@huanjani yes, committed and pushed prior to update. I'm wondering if it is because I created the connection while logged in with one role (admin), but run cli from another role (poweruser).

**Comment by h5aaimtron** [comment]
@huanjani @efekarakus  still no luck. I recreated the connection under the poweruser role (same as cli) and it still ignores the connection_name and creates its own. Is there a a debug mechanism to see why copilot is ignoring that connection?

**Comment by h5aaimtron** [comment]
@huanjani @efekarakus I got it working. I'm not sure the exact cause but I did go through and clear my aws cli out and set it up again. Not sure if something was cached or what not, but it appears to be working now.

**Comment by efekarakus** [comment]
Awesome that's great to hear!
