### ISSUE TITLE
Reverting to an older version with Copilot?

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2454]
I know this this is not possible yet, but it would be useful feature.

It would be great if I could deploy older versions of a service using Copilot. I mean, the Docker images are right there in ECR, so this should be possible right>?

Maybe something like:

```
copilot svc deploy --image <ECR image URL>

```

Or does this already work if the image is tagged? Like, can I use an old tag to deploy that version?

If this is not possible, what's the best and easiest way to revert to a previous version?

**Comment by Lou1415926** [comment]
Hi gtamas!

You want to deploy a service with an existing image in your ECR repository, is that correct?

You should be able to do so by specifying the image location in your service's manifest [in image location field](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-location).

For example, in your service's manifest:
```
# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: my-service
type: Load Balanced Web Service

image:
  location: 11111111111.dkr.ecr:us-east-1.amazonaws.com/my-app/my-service:latest
```

After updating your manifest, you can just run `copilot svc deploy` to deploy your service with the image specified in your manifest. Copilot will just pull the image and update the service.
