### ISSUE TITLE
Reduce progress log entries in CI/CD environments

### ISSUE THREAD

**Issue by sunaulo-suhail** [aws/copilot-cli#2461]
I am using GitHub actions to deploy code through **copilot cli**. When deploying for some reason GitHub appends the log instead of replacing it as in my local computer.

So is there any option to render logs only after certain interval of time let's say 20 sec.

I found a GitHub issue where it is said that setting ```CI=true``` will fix the issue but no success.

This is the command I ran
```bash
CI=true copilot svc deploy --name servicex --env envx
```

**Comment by efekarakus** [comment]
Hi @sunaulo-suhail that fix is not out yet and it will be released with v1.8.0 soon! 
I'll update this issue once the new binary is out :)

**Comment by sunaulo-suhail** [comment]
Thanks @efekarakus sir, is there any workaround for now? Any config in **GitHub Actions** or other hack you know.

**Comment by efekarakus** [comment]
I think for now, the best workaround is what @coopsmoss does: https://github.com/aws/copilot-cli/discussions/2322#discussioncomment-739959 .

**Comment by sunaulo-suhail** [comment]
Thanks @efekarakus I will definitely try that out, should I keep this issue open or close it, If I should keep this issue open can you suggest me a good title for the issue so that other developers can google the same.

**Comment by efekarakus** [comment]
I've updated the issue title! We can keep it open until the release is out :)

**Comment by efekarakus** [comment]
This is now resolved in v1.8.0 🥳 https://github.com/aws/copilot-cli/releases/tag/v1.8.0
