### ISSUE TITLE
AWS Config environment variables ignored by copilot env init 

### ISSUE THREAD

**Issue by paulhhallam** [aws/copilot-cli#2494]
Using a script to run copilot I have environment variables 
AWS_CONFIG_FILE and 
AWS_SHARED_CREDENTIALS_FILE and
AWS_DEFAULT_REGION 
pointing to an area that is not my default .aws directory location on an AWS EC2 instance.
"copilot env init ..." fails with the error:
✘ read named profiles: read AWS config file /dir1/.aws/config, you might need to run aws configure first: load ini file /dir1/.aws/config: open /dir1/.aws/config: no such file or directory
The message is correct as there is no .aws directory in that location, hence the use of the environment variables which are being ignored.
I have confirmed the variables are set in the script.

**Comment by huanjani** [comment]
Hi @paulhhallam.

Thanks for bringing this to our attention-- your use case sounds like something we don't yet support but should! We'll put this issue in our backlog and try to get to it as soon as we can.

**Comment by huanjani** [comment]
Hi all!
AWS Copilot v1.15.0 is now released with this enhancement! 
https://github.com/aws/copilot-cli/releases/tag/v1.15.0 🎉🚀
