### ISSUE TITLE
Can't run a task within my app

### ISSUE THREAD

**Issue by nbarrera** [aws/copilot-cli#2500]
I 've created a copilot app importing it into my existing vpc.

App is running, and `copilot svc status` says it's all fine.

Now I want to run a new task to execute a db migration by executing a script.

```
% copilot task run 
In which application would you like to run this task? my-app-name
In which environment would you like to run this task? test
✘ provision resources for task my-app-name: read template for task stack: read template task/cf.yml: stat /Users/xxx/git/my-app-name/task/cf.yml: no such file or directory
```

It is true, that file does not exists (nor does the task directory) but I 'm not sure why it should exist and which content should it have.

I 've checked the docs and it seems that execution should work,
could it be that's not working becase the app was imported into an existing vpc?

**Comment by iamhopaul123** [comment]
Hello @nbarrera. Could you check what version of Copilot are you using and how did you install the Copilot?

**Comment by nbarrera** [comment]
Hi, thanks for your attention...
I 've installed Copilot 1.7.1 using `brew`, I 'm running a mbp m1

EDIT: upgraded to latest 1.8.0 using `brew upgrade copilot`, but still same problem

**Comment by huanjani** [comment]
This might be related to the fact that you're on ARM architecture. See https://github.com/aws/copilot-cli/issues/1949.  Did you do some kind of workaround to get as far as you did?

We think the missing CloudFormation template could be related to packr....

**Comment by iamhopaul123** [comment]
Hello @nbarrera. Do you remember which command you used to install Copilot by `brew`? Sorry for the confusion but, it won't work for `brew install copilot`, instead you'll need to use `brew install aws/tap/copilot-cli`.

**Comment by nbarrera** [comment]
> Do you remember which command you used to install Copilot by `brew`?.

Sorry I just wrote that from the top of my head, but now you mention it... I 've followed [these instructions](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Copilot.html#copilot-install)

You are right, there it says: do `brew install aws/tap/copilot-cli` so that's for sure what I did.

**Comment by huanjani** [comment]
And just to confirm: you created your environment named `test` with Copilot and imported your existing VPC in that step?

**Comment by iamhopaul123** [comment]
Gotcha. That sounds strange to me. Could you reinstall the Copilot binary and do `which copilot` to see which copilot by default you are using? because sometimes you might have `copilot` pointing to an outdated version

**Comment by nbarrera** [comment]
> This might be related to the fact that you're on ARM architecture. See #1949. Did you do some kind of workaround to get as far as you did?

So far I 've just followed a couple of guidelines but nothing special.

The simplest copilot example was working for me, I just needed to tune the config to add a Redis addon and also import the app to my own vpc just because I needed a static IP so I could whitelist that on the Mongo Atlas configuration, so I had to create a nat gw and a couple of private subnets and then use those on the copilot app.

but no problems related with arm64/m1 until now I guess

> And just to confirm: you created your environment named test with Copilot and imported your existing VPC in that step?

Yes, I think I did

```
 copilot env init -n test 
```

and selected in the interactive menu my default vpc and the private/public subnets that I created on my own for this matter

**Comment by nbarrera** [comment]
> Could you reinstall the Copilot binary and do `which copilot` to see which copilot by default you are using? because sometimes you might have `copilot` pointing to an outdated version

Yes,... that could be... but just for the record:

I 've been always using version 1.7.1 because that's the one I got when I met and installed copilot.
I encountered this error... and then I realized 1.8.0 was out..
so I 've upgraded to 1.8.0 today, and still the error remains.

Anyway.., this is what I got now:

```
% which copilot
/opt/homebrew/bin/copilot
% /opt/homebrew/bin/copilot --version
copilot version: v1.8.0
```

now I 'm uninstalling:

```
% brew uninstall copilot
Uninstalling /opt/homebrew/Cellar/copilot/1.8.0... (8 files, 53.2MB)
```

and reinstalling

```
% brew install aws/tap/copilot-cli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 10 formulae.
==> Updated Casks
Updated 12 casks.

==> Tapping aws/tap
Cloning into '/opt/homebrew/Library/Taps/aws/homebrew-tap'...
remote: Enumerating objects: 1763, done.
remote: Counting objects: 100% (526/526), done.
remote: Compressing objects: 100% (226/226), done.
remote: Total 1763 (delta 430), reused 372 (delta 300), pack-reused 1237
Receiving objects: 100% (1763/1763), 300.97 KiB | 643.00 KiB/s, done.
Resolving deltas: 100% (1091/1091), done.
Tapped 13 formulae (45 files, 400.7KB).
==> Installing copilot-cli from aws/tap
==> Downloading https://github.com/aws/copilot-cli/releases/download/v1.8.1/copilot_1.8.1_macOS_amd64.tar.gz
==> Downloading from https://github-releases.githubusercontent.com/202018792/840b6480-d40b-11eb-846b-85f67fe019b4?X-Amz-Algorithm=AWS4-HMAC-S
######################################################################## 100.0%
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/copilot-cli/1.8.1: 5 files, 47.9MB, built in 3 seconds
nbarrera@Nicolass-MacBook-Pro beanie-titles-runtime % which copilot
/opt/homebrew/bin/copilot
% /opt/homebrew/bin/copilot --version
copilot version: v1.8.1
```

🚀  v1.8.1 ❗ 
by the way you guys do have a quick release cycle 😄 

aaaand it's fixed now ‼️ 

you rock!
