### ISSUE TITLE
Question: Sidecar entrypoint and cmd configuration

### ISSUE THREAD

**Issue by buddhike** [aws/copilot-cli#2501]
Is it possible to customise `entrypoint` and `cmd` for a sidecar? 🙏🏾

**Comment by Lou1415926** [comment]
At this moment there is no native way of doing this from the manifest😞. It'd be a great addition though. Thanks for the suggestion!

This may be a detour but you can run `copilot svc package` to produce a CloudFormation template, in which you can edit  the sidecar's container definition to customize the `EntryPoint` and `Command` fields. After this, you can deploy the service with the edited template.

**Comment by buddhike** [comment]
Thanks @Lou1415926.  Good to know that this could work with `package` option for now.
