### ISSUE TITLE
Empty addons directory fails the deployment

### ISSUE THREAD

**Issue by buddhike** [aws/copilot-cli#2502]
It looks like having an empty `addons` directory fails the deployment with following error: 

```
deploy service: get addons outputs for namegen: "Resources" field in cloudformation template is not a map
```

**Comment by huanjani** [comment]
Ah, thanks for bringing this to our attention. 
We'll work on fixing this bug.

Ref: https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/deploy/cloudformation/stack/workload.go#L191
