### ISSUE TITLE
Default values for autoscaling?

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2511]
If I have the following count config in my manifest

``` yml
count:
  range: 1-5
```

without specifying properties such as `count.cpu_percentage`, `count.memory_percentage`, etc., what are the default values? On what metric(s) is it using to auto scale?

**Comment by huanjani** [comment]
There are no default values, so your instinct is correct-- you'll need to specify those values in order for Application Auto Scaling to know when to increase the task count. 

I can see how the manifest snippets in our docs are misleading!

**Comment by mikelhamer** [comment]
@huanjani thanks for the explanation. It was a little confusing but I understand now. Now to determine what those values should be haha. Thanks!
