### ISSUE TITLE
skipping image building because location is provided as "Dockerfile"

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#2516]
I have noted in the build stage of the pipeline that the dockerfile is no longer processed with the message:

skipping image building because location is provided as "Dockerfile"

Doesn't seem to matter whether we're pointing to an ECR url or a Dockerfile. Because of this, changes to the dockerfile are not being picked up and nothing is being deployed.

**Comment by iamhopaul123** [comment]
Hello @h5aaimtron. So for [`image.location`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-location) it is used to specify any existing images. Under the hood it is directly mapping into the [image parameter](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_image) in the ECS task definition. Also if `image.location` is used then we'll skip image building from the local dockerfile. Hopefully it makes sense to you!

**Comment by h5aaimtron** [comment]
@iamhopaul123 Does that mean if I remove the location property from the manifest and commit, the build process should automatically detect changes in the Dockerfile and trigger a new build? or does that mean I need to remove the image section to accomplish this?

**Comment by iamhopaul123** [comment]
Yes, you would need to remove the location property then commit the changes and push it to the upstream. Then the pipeline shall automatically detect the new commit which triggers a new build.

**Comment by h5aaimtron** [comment]
I'm guessing due to the change of the manifest I'll need to do a svc deployment as part of that push prior to the pipeline build?
NVM it doesn't. I am getting a message that either image.location or image.build needs to be specified in the build stage.

**Comment by iamhopaul123** [comment]
Yeah, you have to specify the source of your container, either from existing images or local dockerfile.

**Comment by h5aaimtron** [comment]
@iamhopaul123 Ok, so that explains why I saw the issue. The change did indeed fix it.

**Comment by efekarakus** [comment]
Looks like the issue was addressed! feel free to re-open the issue if you have any other questions :)
