### ISSUE TITLE
Redeploy feature

### ISSUE THREAD

**Issue by smiklos** [aws/copilot-cli#2521]
It would be cool to support redeploying a service even if it has no changes. 

Right now if a service has no changes we can't just force a deployment.
My proposal would be to either add a --force flag to svc/job deploy or introduce a new subcommand called `redeploy` or `restart` to kick off a deployment. I believe this is supported by ecs when we say 'force new deployment' on the update service UI.

I would be willing to contribute this if I can

**Comment by iamhopaul123** [comment]
Hello @smiklos. That sounds reasonable to me. Could you also tell me more about what the use cases would be for you? Like why do you need to kick off a new deployment when there are no changes in the service?

**Comment by smiklos** [comment]
Basically I want a way to restart the containers of a running service. The way this can be done right now is by going to the ECS service in the AWS console and update the service -> force new deployment. The use case is that sometimes things go wrong and the fastest way to 'heal' a stuck app is by restarting it

**Comment by efekarakus** [comment]
The feature is now released! https://github.com/aws/copilot-cli/releases/tag/v1.10.0 🥳
