### ISSUE TITLE
unhealthy error on successful deployment

### ISSUE THREAD

**Issue by AkifumiSato** [aws/copilot-cli#2526]
When deploying with copilot, I run into unhealthy errors several times.
I can see from the task log, the health check request has been processed normally, so I don't know the reason for the error.

```
copilot svc deploy --name api --env production
```

After repeating this error several times, the health check succeeds and the deployment is complete.
```
Latest 2 failure events                                                              
      - (service xxxxxxxxx-production-api-Service-xxxxxxxxx) (port 4200) i                              
        s unhealthy in (target-group arn:aws:elasticloadbalancing:ap-northeast                              
        -1xxxxxxxxxxxx:targetgroup/scrap-Targe-xxxxxxxxx/xxxxxxxxx)                              
         due to (reason Health checks failed). 
```

Since the application is processing normally, I think it is a problem around the health check when deploying copilot.
I would appreciate it if you could give me some advice.

**Comment by efekarakus** [comment]
Hi @AkifumiSato !

My guess is that you'd like to set a setting such as [HealthCheckGracePeriodSeconds](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-healthcheckgraceperiodseconds) so that the ECS service scheduler ignores the first few healthcheck requests.

We unfortunately do not surface this field yet in the manifest, duplicate: #2506 🙇 

I outlined a way of mitigating these failures here: https://github.com/aws/copilot-cli/issues/2506#issuecomment-867118411 until we support the field.

**Comment by bvtujo** [comment]
Hey @AkifumiSato this feature has been merged in #2576 and will go out in our next release!

**Comment by AkifumiSato** [comment]
I set `grace_period` in v1.9.0, but it didn't solve this problem.
Is there anything else I can set at the same time?
```yml
http:
  path: '/'
  healthcheck:
    path: '/.health_check'
    grace_period: 120s
```

I put `start_period` in the healthcheck of the image, but it didn't change.

```yml
image:
  build: Dockerfile
  port: 4200
  healthcheck:
    start_period: 120s
```

**Comment by efekarakus** [comment]
Hi @AkifumiSato !

Do you know what's the response status provided by the the `/.health_check` path? 

> The health check request has been processed normally, so I don't know the reason for the error.

I just wanted to make sure that the response status is 200 and not a different code, alternatively you can also set:
```yaml
http:
  healthcheck:
    success_codes: '200,301'
```
to allow error codes to pass healthchecks

**Comment by AkifumiSato** [comment]
@efekarakus Thank you for your prompt reply.
When I checked the log of the request implemented on the application side with ECS, the statusCode was 200.

```js
console.log(
  `[HttpLogging] ${method} ${url} ${statusCode} - ${userAgent} ${time}`,
);
```

ECS task log
```
[HttpLogging] GET /.health_check 200 - ELB-HealthChecker/2.0 1
```

**Comment by AkifumiSato** [comment]
Sorry, this problem seems to have been caused by another library used in my application.
And, I was able to resolve it.
This Issue closes.
