### ISSUE TITLE
Support for cross-account access with copilot pipeline 

### ISSUE THREAD

**Issue by dannysteenman** [aws/copilot-cli#2533]
I have a scenario in which I manage the test and production environments in separate AWS accounts. We have another account for shared services and that's where we also keep our ci/cd pipelines. 

It would be nice to follow best practices and have the ability to deploy copilot pipeline in a shared-services account and add a trust relationship to test and production so we're able to deploy containers cross-account.

I tried to see if it was possible to create a cross-account pipeline on the shared account but I hit the following error: 

```
arn:aws:iam::12345678912:role/pipeline-copilot-nginx-PipelineRole-Q146DG0LUU2A is not authorized to perform AssumeRole on role arn:aws:iam::12345678900:role/copilot-test-EnvManagerRole (Service: AWSCodePipeline; Status Code: 400; Error Code: InvalidStructureException; Request ID: 9f56a295-7bcd-4e16-a7de-5a4bd7e04ff9; Proxy: null)
```

The copilot app is deployed on test account while I try to deploy the pipeline in the shared account (accountnr is changed for sec reason).

Edit: I was able to get it to work when I manually added the shared account id to the trust entity of the `copilot-test-EnvManagerRole` role on the test account. But now that I think of it... there is another issue... because if you want to be able to deploy crossaccount then it's not handy to manage domains via the copilot app command. Then we actually need to have the ability to configure a domain per environment instead of managing it via the copilot app ```copilot app init --domain example.com``` Because if you use a specific domain e.g. "example.com" that is set up on R53 on production. Then you can't share the domain with a test account because it doesn't have access to that "HostedZoneID".

```
~ via v16.3.0 on test-account-cli (eu-central-1)
✦ ➜ copilot app init copilot --domain example.com
✘ get hosted zone ID for domain example.com: domain does not exist
```

So if we have more granular control e.g. manage domain via environment + setup a trust relationship for copilot pipeline, that would be awesome. For the time being, I'll go with setting up a pipeline per environment account, unless there is a better workaround, I'm all ears 👍

**Comment by Lou1415926** [comment]
Hi @dannysteenman !

Glad it worked out for you, and thank you for diving deep and the suggestions!

I'm sorry for the confusion about cross-accounts. We deploy the pipelines using the app account, which could be a different account from the env accounts. That'd be the scenario what we referred to by cross-accounts. This works well for use case where the app account and env accounts are managed separately. In your use case, you'd like to deploy the pipeline using a different account than the app account. This is not natively supported, hence the permission issue.

As for the domain, if your domain is set up with your app, then we will create a `DNSDelegationRole` for you, assumable by the env accounts. In this way, the management of the subdomains can be delegated to your env accounts.

Hope this helps!! Let me know if it doesn't 😊

**Comment by blastedcode** [comment]
@dannysteenman  Thanks for the information this is something I am looking into as my use case is virtually the same.

I use the CDK to create all external infrastructure and this is deployed from a pipeline with manual approval within a shared-services account.

I wonder if the app being deployed in the shared account and the 2 env's would then be deployed into their respective accounts.

I wonder if the domain alias can be made dynamic which can be populated from the environments in the future.

**Comment by dannysteenman** [comment]
In order to make it work by default you should setup the pipelines initially from the pipeline account. In my case I deployed containers from the cli on the test account first. then I deployed the pipeline in the pipeline account. Then you run into the issue of not being able to deploy crossaccount. 

Basically this means you have to start from scratch and setup the copilot app on the pipeline account and then create the crossacount environments from there in order to get access to them via the pipeline. Or you can workaround it by manually changing the trust enitity on the EnvManagerRole.

**Comment by Lou1415926** [comment]
Hi @blastedcode !!
> I wonder if the app being deployed in the shared account and the 2 env's would then be deployed into their respective accounts.

You can run `copilot app init` in one account, and `copilot env init` in different accounts than the app account. Say there is an account A with which `copilot app init` is executed, you can deploy your test env with account B, and production env with account C.

Please let me know if I’m not understanding your question correctly!

> I wonder if the domain alias can be made dynamic which can be populated from the environments in the future.

Yes this will be possible in the future. We will allow you to import your own certificate, so that in the manifest's [`alias`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) field, you'll be able to specify any aliases.

**Comment by blastedcode** [comment]
Luckily for me, it was a new project. I ripped it all out and then deployed the app into the Shared account and set the environments in the correct accounts.

Attaching the pipeline just worked from that point.

**Comment by Lou1415926** [comment]
> Luckily for me, it was a new project. I ripped it all out and then deployed the app into the Shared account and set the environments in the correct accounts.
> 
> Attaching the pipeline just worked from that point.

We should make it more clearer that the pipeline is set up in the app account, and include some recommendations of how the applications should set up. 

Thank you for reaching out!!

**Comment by dannysteenman** [comment]
@blastedcode Same here! @Lou1415926 it's good to include that in the docs indeed!
