### ISSUE TITLE
Routing issues after 1.8.1 upgrade

### ISSUE THREAD

**Issue by sugarjig** [aws/copilot-cli#2538]
I use Copilot to deploy two load balanced services, `www` and `admin`. The `www` service has its path defined as `/`, and the `admin` service has its path defined as `admin`. After deployment, the services are available at `https://www.env.app.domain.com` and `https://admin.env.app.domain.com/admin`, as expected.

After upgrading the Copilot version used in my pipeline to 1.8.1, I noticed that when loading the admin service in a browser, I was no longer able to load static assets like CSS and JS files. The browser console would show 503 status codes for these. An example would be `https://admin.env.app.domain.com/css/bootstrap.min.css`. Notice that `admin` is not in the path. After downgrading Copilot to 1.7.0, I am able to download the static assets.

**Comment by iamhopaul123** [comment]
Hello @sugarjig. Just looked at our code. It seems like in `v1.7.0`, `http.path` is actually ignored when you use HTTPS domain, which means even if you set the `admin` service path to be `admin`, under the hood it is still `/*` to be the listener rule.

However, after `v1.7.0`, the `http.path` is rendered for HTTPS service. So if you set the path to be `admin` then your browser console can only access resources within this path `https://admin.env.app.domain.com/admin` or `https://admin.env.app.domain.com/admin/*`. As a result, the attempt to access `https://admin.env.app.domain.com/css/bootstrap.min.css` shall fail as expected.

**Comment by sugarjig** [comment]
Ah, in that case, I think I want to set the path of the `admin` app to `/`. The routing for the `/admin` path is actually handled by the application itself. I'll give that a try and see if it works.

**Comment by sugarjig** [comment]
That worked. Thanks for looking into it and pointing me towards the fix!
