### ISSUE TITLE
Feature request: Worker service

### ISSUE THREAD

**Issue by mtoftum** [aws/copilot-cli#2541]
I'm looking for a variant of Backend Service that doesn't have a load balancer associated. [see also](https://github.com/aws/copilot-cli/issues/816)

The thinking is something similar to Workers in Elastic Beanstalk with less overhead.
Define an SQS queue and spin up workers that can read from it. 
A variant could expose AWS::ApiGatewayV2::Integration with IntegrationType: AWS_PROXY and IntegrationSubtype: SQS-* to the worker. 

If there's interest I can try to write up more details.

**Comment by Lou1415926** [comment]
Hi @mtoftum !

Thank you for the awesome suggestion! In fact, we are currently working on [#1246](https://github.com/aws/copilot-cli/issues/1246), a worker service pattern that can read from SQS queues. 

Would you like to give us more details on the variant? For example, what'd be the use case of it?

Thank you so much!!

**Comment by mtoftum** [comment]
The variant is inspired by workers in Elastic Beanstalk (at least Tomcat based workers which is what I have a ton of). In beanstalk you'll deploy your webapp on tomcat while the elastic beanstalk sqs-daemon will poll the queue for messages and submit them locally over HTTP to the Tomcat application.
In Elastic Beanstalk, I think the advantage is twofold - first it lets you build an SQS based worker without needing support libraries for SQS and secondly, it's also making it easy manage concurrency from the Beanstalk console without needing to redeploy the application.
My initial thought in suggesting a worker was to "borrow" the daemon from Elastic Beanstalk and stick that in another container. The second thought was using AWS_PROXY with IntegrationSubtype: SQS- to cut down on the number of moving parts that need managing. 
On further reflection, I think the model from Elastic Beanstalk with a daemon handling the SQS polling would be a worthwhile option, while the REST API / AWS_PROXY may be more trouble than it is worth.

HTH.

**Comment by efekarakus** [comment]
Hi @mtoftum ! We have an official proposal for this service type here: #2550 we would love your feedback!

**Comment by efekarakus** [comment]
Closing this issue in favor of #2550 which will be delivered soon!
