### ISSUE TITLE
How to send logs to CloudWatch Logs using Copilot?

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2542]
Hi

We would like to send our prod logs to CloudWatch Logs, so we can use CloudWatch to view the logged information.

Basically, what I want is to send all stuff `copilot svc logs -e prod -n some-service` would print to CloudWatch logs.

How can I do this? We have backend services and load balanced web services. My understanding is that awslogs log driver should be enabled by our task definition. But I don't see how can I implement this.

Thanks ind advance!

**Comment by gtamas** [comment]
According to your docs, this should be implemented using sidecars.

https://aws.github.io/copilot-cli/docs/developing/sidecars/

But awslogs driver is not supported yet, so we should use FireLens log router instead, right?

**Comment by gtamas** [comment]
I just found that the logs for all environments ate already available in CloudWatch under the log group` /copilot/appName-envName-serviceName`

So does this mean that this is already implemented by default? What's the point of implementing a sidecar using FireLens? Is that useful when we have special logging needs, like forwarding logs to something else than CloudWatch?

Is there any benefit using FireLens (and FluentD or Fluent Bit) over the default log forwarding mechanism, which is alerady implemented?

**Comment by iamhopaul123** [comment]
Hello @gtamas. Glad you found the answer! Yeah by default we already send all logs to the cloudwatch under the log group you found. One benefit for Firelens is it allows you to use Fluent Bit to send your logs to custom and multiple destinations (see [here](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-launches-firelens-log-router-for-amazon-ecs-and-aws-fargate/)).

**Comment by gtamas** [comment]
OK thanks for the info!
