### ISSUE TITLE
CLI hanging when ~/.aws/credentials is set incorrectly

### ISSUE THREAD

**Issue by jlucas91** [aws/copilot-cli#2547]
Hi Copilot team! 

Wanted to file a quick bug for you here as I imagine this could be tripping up other new users. 

On a fresh CLI (and incidentally, OS) install I set my ~/.aws/credentials to: 

```
[default]
aws_access_key_id=***
aws_secret_access_key=***

[default]
region=us-east-1
```

Somewhat thoughtlessly copy/pasting from the docs. The CLI hung on any command I ran and after debugging a bit, I realized my mistake. Not sure what caused the hang but wanted to get it on y'alls radar.

**Comment by Lou1415926** [comment]
Closing this issue since it has been fixed. The CLI no longer hangs and will instead return early with an error. Feel free to reopen for further questions!
