### ISSUE TITLE
Multi-region deployments

### ISSUE THREAD

**Issue by buddhike** [aws/copilot-cli#2548]
I would like to deploy my service to multiple regions. When I attempt to deploy it to second region, it fails during `app init` because CF for creating infrastructure roles fails with a message `myapp-adminrole already exists`.

**Comment by kohidave** [comment]
Hi friend! So the way Copilot models this is that:

One application contains one or more environments. Workloads are then deployed into environments. 

A particular environment is in a particular account and region. So, if you wanted to deploy your service to another region, you'd create a new environment in your app for that region 😄

```
# Sets up a default environment in your current region
copilot init

# Add a new environment to your app 
copilot env init --region us-west-2 --name west-env

# deploy your service to that environment 
copilot deploy --env west-env

```

**Comment by buddhike** [comment]
Nice! This makes sense. Thanks @kohidave 🙏🏾
