### ISSUE TITLE
How to specify Fargate version?

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2549]
Is there any way to specify the version of Fargate used when generating a service?

**Comment by bvtujo** [comment]
Hi @mikelhamer, currently we don't expose that as an overrideable property, as the `LATEST` PV now points to `1.4.0` and many features that are standard in Copilot (EFS and configurable ephemeral storage) aren't compatible with `1.3.0` and earlier. Is there a specific feature you need that would be enabled by 1.3? Something to do with ENI allocations, perhaps?

**Comment by mikelhamer** [comment]
@bvtujo thanks! I was on a call with AWS troubleshooting some failed ECS service deployments and they suggested temporarilly trying a different version of Fargate to rule something out. So just figured I'd ask :)
