### ISSUE TITLE
segmentation violation 

### ISSUE THREAD

**Issue by riceian** [aws/copilot-cli#2555]
MacOS 11.4
copilot 1.8.2

Getting the following on all my services including a simple helloworld node service.
Seeing the same thing on 2 different Mac machines

latest: digest: sha256:5f4e91f5b617a4a198304d42c828ed3a53c6d4d364e6e6d72cb6b0baaa05b262 size: 3049
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x223faa9]

goroutine 1 [running]:
github.com/aws/copilot-cli/internal/pkg/cli.validateAppVersion(0xc000923fa0, 0x1b, 0xc0013281e0, 0x0, 0x0, 0x2bd10c0, 0xc0004da060)
	/codebuild/output/src595587352/src/internal/pkg/cli/svc_deploy.go:503 +0x29
github.com/aws/copilot-cli/internal/pkg/cli.validateAlias(0xc00060d710, 0xa, 0xc000923fa0, 0x1b, 0xc0013281e0, 0x28d316b, 0x4, 0x0, 0x0, 0xc0004e3620, ...)
	/codebuild/output/src595587352/src/internal/pkg/cli/svc_deploy.go:465 +0x86
github.com/aws/copilot-cli/internal/pkg/cli.(*deploySvcOpts).stackConfiguration(0xc00000a780, 0x0, 0x0, 0x196, 0x2541fa0, 0xc0004e3620, 0x16)
	/codebuild/output/src595587352/src/internal/pkg/cli/svc_deploy.go:429 +0x405
github.com/aws/copilot-cli/internal/pkg/cli.(*deploySvcOpts).deploySvc(0xc00000a780, 0x0, 0x0, 0x0, 0x0)
	/codebuild/output/src595587352/src/internal/pkg/cli/svc_deploy.go:450 +0x5d
github.com/aws/copilot-cli/internal/pkg/cli.(*deploySvcOpts).Execute(0xc00000a780, 0x0, 0x0)
	/codebuild/output/src595587352/src/internal/pkg/cli/svc_deploy.go:173 +0x3fa
github.com/aws/copilot-cli/internal/pkg/cli.(*initOpts).deploySvc(0xc00036e640, 0x23d0680, 0x2b3aa90)
	/codebuild/output/src595587352/src/internal/pkg/cli/init.go:403 +0xe4
github.com/aws/copilot-cli/internal/pkg/cli.(*initOpts).deploy(0xc00036e640, 0x0, 0x0)
	/codebuild/output/src595587352/src/internal/pkg/cli/init.go:308 +0x5f
github.com/aws/copilot-cli/internal/pkg/cli.(*initOpts).Run(0xc00036e640, 0x28d40b7, 0x6)
	/codebuild/output/src595587352/src/internal/pkg/cli/init.go:288 +0x40e
github.com/aws/copilot-cli/internal/pkg/cli.BuildInitCmd.func1(0xc00034d400, 0x390d9e8, 0x0, 0x0, 0xc00021fd48, 0x0)
	/codebuild/output/src595587352/src/internal/pkg/cli/init.go:444 +0x127
github.com/aws/copilot-cli/internal/pkg/cli.runCmdE.func1(0xc00034d400, 0x390d9e8, 0x0, 0x0, 0x0, 0x0)
	/codebuild/output/src595587352/src/internal/pkg/cli/cli.go:66 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc00034d400, 0x390d9e8, 0x0, 0x0, 0xc00034d400, 0x390d9e8)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00034d180, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/codebuild/output/src595587352/src/cmd/copilot/main.go:25 +0x2b

**Comment by iamhopaul123** [comment]
Hello @riceian. Sorry for the churn. It seems like the application has already been created before with `domain`. Normally `copilot init` is used to create your first application from scratch and it doesn't support creating an app with domain. My suspect is you created the application using `app init` before. Could you try `svc deploy` to deploy the service instead of using `copilot init`? However, there is something to fix on our side so that at least users shouldn't get the exception. Please let me know if anything is still not clear!

**Comment by iamhopaul123** [comment]
Hello @riceian this fix is now released 🎉  https://github.com/aws/copilot-cli/releases/tag/v1.8.3
