### ISSUE TITLE
Cli error referencing old application

### ISSUE THREAD

**Issue by allamand** [aws/copilot-cli#2556]
While working out of a copilot app directory, then copilot seems to default to an old application that I already destory with `copilot app delete`

```bash
$ copilot app ls
aws-copilot-sample-service
emoji-race
wordpress-diy
```

but If I want to create new app it complain about the old one (until I force create a `copilot/.workspace` parameter to overwrite the issue).

```bash
$ copilot app show  
✘ get application wordpress: couldn't find an application named wordpress ...
```

I also check in SSM parameter store, but there is no mention to **wordpress** application.

How can I remove this reference from copilot ?

**Comment by allamand** [comment]
I had a copilot directory hiding in my repo which I may accidently created..

**Comment by efekarakus** [comment]
Awesome glad you got it working @allamand !
