### ISSUE TITLE
Installing plugin exits due to yum unavailability

### ISSUE THREAD

**Issue by aweeraman** [aws/copilot-cli#2561]
Attempting to install session manager plugin exits due to unavailability of yum on a Debian system.

```
$ copilot svc exec --name service --env dev -c /bin/sh
Looks like the Session Manager plugin is not installed yet.
Would you like to install the plugin to execute into the container? Yes
[sudo] password for foo:
sudo: yum: command not found
✘ install ssm plugin: exit status 1
```

It would be good if copilot could use the apt-get equivalent, or give a helpful message that the plugin cannot be installed if the Debian-based distributions are not supported.

**Comment by danelige** [comment]
+1  is there a fix? 

AWS Fargate. 

when running 

copilot svc exec --name xxx --env xxx -c /bin/sh

getting:
```

sudo: yum: command not found
install ssm plugin: exit status 1
```

**Comment by iamhopaul123** [comment]
Hello @danelige. It seems like [session manager plugin](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html#install-plugin-linux)(prerequisite plugin for running ecs exec) only supports ubuntu for Debian-based distribution. What happen if you run `uname -a`?

**Comment by kangere** [comment]
I am using Pop OS which is an ubuntu based distro and I am getting the same error described in this issue.

The command `uname -a` produces the output below 

```
Linux pop-os 6.4.6-76060406-generic #202307241739~1692717645~22.04~5597803 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by kangere** [comment]
It seems there is an explicit check for the string `Ubuntu` when the copilot is trying to determine if the linux distribution is ubuntu based [here](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/exec/ssm_plugin_install_latest_binary_linux.go#L38) .

Is there a better way of doing this for  Ubuntu based distributions that don't have the string `Ubuntu` in the output of the `uname -a` command

**Comment by Lou1415926** [comment]
@kangere good find! I wonder what your output is for [`lsb_release -a`](https://refspecs.linuxfoundation.org/LSB_3.0.0/LSB-PDA/LSB-PDA/lsbrelease.html)? I'm trying to see if this could solve the issue for you.

**Comment by kangere** [comment]
This is my output for `lsb_release -a` 
```
Pop
```

The output for `cat /etc/os-release` below seems to be more ideal since it has a reference to Ubuntu

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

the `/etc/os-release` files seems to be what is also used in places like the docker installation scripts, see `get_distribution` function [here](https://get.docker.com/). You could probably read that file to determine if the linux distro is ubuntu based. I'd be willing to make a PR with this fix.

Let me know what you think

**Comment by Lou1415926** [comment]
Thank you @kangere for looking this up! This looks promising - seems like all systems using systemd would have this file. From the docker installation scripts:
```sh
get_distribution() {
	lsb_dist=""
	# Every system that we officially support has /etc/os-release
	if [ -r /etc/os-release ]; then
		lsb_dist="$(. /etc/os-release && echo "$ID")"
	fi
	# Returning an empty string here should be alright since the
	# case statements don't act unless you provide an actual value
	echo "$lsb_dist"
}
```

Reading the [`os-release` doc](https://www.freedesktop.org/software/systemd/man/os-release.html), it seems like there are two fields we can read to tell if the distro is ubuntu or ubuntu-based:
```
ID=
  A lower-case string (no spaces or other characters outside of 0–9, a–z, ".", "_" and "-") identifying the operating system, excluding any version information and suitable for processing by scripts or usage in generated filenames. If not set, a default of "ID=linux" may be used. Note that even though this string may not include characters that require shell quoting, quoting may nevertheless be used.

  Examples: "ID=fedora", "ID=debian".

ID_LIKE=
  A space-separated list of operating system identifiers in the same syntax as the ID= setting. It should list identifiers of operating systems that are closely related to the local operating system in regards to packaging and programming interfaces, for example listing one or more OS identifiers the local OS is a derivative from. An OS should generally only list other OS identifiers it itself is a derivative of, and not any OSes that are derived from it, though symmetric relationships are possible. Build scripts and similar should check this variable if they need to identify the local operating system and the value of ID= is not recognized. Operating systems should be listed in order of how closely the local operating system relates to the listed ones, starting with the closest. This field is optional.

  Examples: for an operating system with "ID=centos", an assignment of "ID_LIKE="rhel fedora"" would be appropriate. For an operating system with "ID=ubuntu", an assignment of "ID_LIKE=debian" is appropriate.
```

> I'd be willing to make a PR with this fix.

Thank you very much! That'd be a huge help - we'd be very happy to see your PR ❤️ !

**Comment by iamhopaul123** [comment]
Hello this is now fixed in https://github.com/aws/copilot-cli/releases/tag/v1.33.0!
