### ISSUE TITLE
Add "extra commands" tag in manifest.yml

### ISSUE THREAD

**Issue by NonsoAmadi10** [aws/copilot-cli#2570]
Hello copilot team, I would really appreciate it if there was a way of adding an "extra command" variable to my manifest file that allows me run extra commands to my service when it gets deployed to fargate rather than having  to run it using `copilot svc exec` everytime a new task is deployed. It is a bit of a toil.

**Comment by efekarakus** [comment]
Hi @NonsoAmadi10 !

Out of curiosity could this be achieved by using the `ENTRYPOINT` instruction and a shell script as a command so that the commands are executed whenever the container starts?
For example: https://github.com/bvtujo/copilot-wordpress/blob/main/Dockerfile#L9-L10
