### ISSUE TITLE
Visualize local stack changes against deployed stack

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#2574]
## Ask
As a user that made local changes to the manifest,    
I can run `copilot svc package -e {env}` to see the generated CloudFormation template,    
However I don't have a way of seeing the _differences_ between the local changes and what's already deployed.

I would like to have a way of visualizing the differences,   
So that I can ensure the right resources are updated.  
This is especially useful for when #948 is supported.

## Proposed user experience
We can introduce a new flag to the `package` command:
```
$ copilot svc package --diff
```
That will print to stdout a human-friendly digest of the changes to the stack.

## Programming Model
We should be looking at how the AWS CDK does this when running the `cdk diff` command

**Comment by dannyrandall** [comment]
We recently released this in [v1.27.0](https://github.com/aws/copilot-cli/releases/tag/v1.27.0)! Here's our blog post about it: https://aws.github.io/copilot-cli/blogs/release-v127/#preview-aws-cloudformation-template-changes
