### ISSUE TITLE
Intermittent build failures with error "Message: Error while executing command: for workload in $WORKLOADS; do"

### ISSUE THREAD

**Issue by jlucas91** [aws/copilot-cli#2579]
Hi! 

I'm seeing intermittent build failures with the following error message: "Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: for workload in $WORKLOADS; do" 

I'm not entirely sure what the pattern of failures is. Initially, it seemed like the first build after creating the pipeline would pass and subsequent builds would fail. More recently, it's been harder to track.

Based on https://github.com/aws/copilot-cli/issues/2371 I tried to fix it by adding an explicit path to my docker Dockerfile in manifest.yml (`dockerfile: Dockerfile` -> `dockerfile: ./Dockerfile`). That appeared to correct the issue for a bit, but I've started seeing the failures again. 

The pipeline is using the most recent copilot CLI version and I've deleted/recreated it a few times. Any idea what might be going on or how to debug it?

Thanks!

**Comment by huanjani** [comment]
Hello, @jlucas91! 

Is it possible you've reached your dockerhub login limit? See https://github.com/aws/copilot-cli/issues/1869#issuecomment-765643674 for a possible solution.

**Comment by jlucas91** [comment]
Hi! I was wondering the same - but we're deploying 1-2 times per day max. The most recent failure is the first deploy attempt in >24 hours.

Before I go down the rate limit login rabbit hole - do you have any gut sense on whether it would be possible to hit the limit with such infrequent builds? (i.e. could a single build of a not particularly complex image trigger the rate limit) 

If it's helpful to note - I've run a number of staging deploys today locally with `copilot svc deploy` with no issues.

**Comment by huanjani** [comment]
Hm. 
Personally, I'm often surprised by how easy it is to hit that limit.
Would you mind pasting the build log from CodeBuild here? 
If it is the docker rate limit, there's often a semi-hidden error message that comes before that cryptic workloads error message....

**Comment by jlucas91** [comment]
Sure thing - here's what I imagine is the relevant section of the log: 

https://gist.github.com/jlucas91/afa0a15038de0f3f3eb7833e7067443b

**Comment by jlucas91** [comment]
Aha - I think you're right! Will need to dig in a bit more... Thanks for the lead!

```
Step 1/17 : FROM python:3.9.5-slim-buster as base
--
860 | toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by huanjani** [comment]
Yup, you bet! 

That workaround that Efe came up with (linked to above) is quick and easy. 😄

**Comment by mvn-bachhuynh-dn** [comment]
Thank all! It works!
