### ISSUE TITLE
copilot env upgrade fails with `minimum field size of 20, AssumeRoleInput.RoleArn.`

### ISSUE THREAD

**Issue by toshitanian** [aws/copilot-cli#2581]
copilot version: v1.8.2

I tried to create secret value after initialized test env with the command below.
```bash
$ copilot secret init --name foo-key--values test=bar-value
```

However, it failed with the error messages below.
```
✘ execute "env upgrade --app <my-app-name> --name test": get template version of environment test in app <my-app-name>: get metadata for stack <my-app-name>-test: get template summary: InvalidParameter: 1 validation error(s) found.
- minimum field size of 20, AssumeRoleInput.RoleArn.
```

If this may be my mistake but if there's some conditions that fails creating the secret, I want to know how to avoid. And if this is a bug, I hope it's fixed.

The length of `<my-app-name>` is 5 including hyphen. like `a-foo`

**Comment by toshitanian** [comment]
I looked into the code that should calls `GetTemplateSummary` and found that it's also called by `copilot env show`. 

https://github.com/aws/copilot-cli/blob/f75d75011b2ed921f24a7377f5281c1fe18b014b/internal/pkg/aws/cloudformation/cloudformation.go#L204-L212

It also made an error.
```bash
$ copilot env show
Only found one environment, defaulting to: test
✘ describe environment test: list deployed services in env test: get resources by Copilot tags: get resource: InvalidParameter: 1 validation error(s) found.
- minimum field size of 20, AssumeRoleInput.RoleArn.
```

**Comment by toshitanian** [comment]
Internally error occurs while running `copilot env upgrade` seems to be the root cause.
```
$ copilot env upgrade --all
✘ get template version of environment test in app <my-app-name>: get metadata for stack <my-app-name>-test: get template summary: InvalidParameter: 1 validation error(s) found.
- minimum field size of 20, AssumeRoleInput.RoleArn.
```

**Comment by toshitanian** [comment]
One of the name of role is `a-foo-executionrole` which length is 19. So, I will change the app name and try again.

**Comment by toshitanian** [comment]
I got unable to even delete an app. (it's actually trying to delete job.)

```
$ copilot app delete
Are you sure you want to delete application a-foo? Yes
✘ Failed to delete the stack of job <xxxxx>-job from environment test: delete job stack: delete stack <xxxxx>-job: InvalidParameter: 1 validation error(s) found.
- minimum field size of 20, AssumeRoleInput.RoleArn.
.
✘ execute job delete: delete job stack: delete stack <xxxx>-job: InvalidParameter: 1 validation error(s) found.
- minimum field size of 20, AssumeRoleInput.RoleArn.
```

**Comment by toshitanian** [comment]
>One of the name of role is a-foo-executionrole which length is 19. So, I will change the app name and try again.

Now succeeded to create secret with the app name of `a-foooo`. So I guess that the length of app-name should at least 6.

**Comment by iamhopaul123** [comment]
Hello @toshitanian. Sorry for those troubles you had. It seems like an `sts` issue to me. I wonder if it is because in your app account SSM parameter store, the `ManagerRoleARN` of your environment record somehow was broken. Could you check the value there? Thank you!

**Comment by toshitanian** [comment]
@iamhopaul123 Thank you so much. I checked it and found that the `managerRoleARN` value is empty. Also I see a lot of garbage records of app environments in the parameter store that I should have deleted. I guess, at some point, the environment record for a specific app name has got broken and got unable to recover. That's should be the reason why I succeeded after I renamed the app name.
Please close this issue if this is not an issue to be fixed.

```json
/copilot/applications/a-foo/environments/test

{"app":"a-foo","name":"test","region":"us-west-2","accountID":"______","prod":false,"registryURL":"","executionRoleARN":"","managerRoleARN":""}
```

**Comment by iamhopaul123** [comment]
Yeah if the record wasn't cleaned up after deletion. Then the next time when you create the app/env/svc again we won't override the record due to idempotency concern.
