### ISSUE TITLE
'copilot deploy' works fine, pipeline deploy is missing credentials file

### ISSUE THREAD

**Issue by DaveCollinsJr** [aws/copilot-cli#2583]
Loving copilot for AWS ECS Rails deployment so far!

I have an issue with `/config/credentials/test.key`  (ignored by .gitignore)
When I deploy using `copilot deploy --name web` everything works **perfectly** and the `/config/credentials/test.key` file exists in the ECS container.

However, when I deploy using the codePipeline created by copilot, `/config/credentials/test.key` file is missing.

I presume this is because `copilot deploy` is copying _everything_ from my development environment whereas the code pipeline's buildspect.yml is only pulling from what is on github.

What is the **proper copilot best practices** way to resolve this problem?
I have tried:
1) Install AWS CLI in `Dockerfile` and use `AWS S3 CP` to copy that file from a private S3 bucket
  The problem here is the how to get the AWS credentials to the AWS CLI while codepipeline is running `docker build`? (currently getting **fatal error: Unable to locate credentials**)
2) Modify the buildspec.yml file to do this copy manually
  Where?  The file needs to be copied _before_ rails runs inside docker

Would appreciate any help and guidance!

**Comment by huanjani** [comment]
Hello, @DaveCollinsJr!
We're so happy you like Copilot!

What if you were to store the key value as a [secret](https://aws.github.io/copilot-cli/docs/developing/secrets/)? Would that work?

**Comment by DaveCollinsJr** [comment]
Hello @huanjani thanks for your reply.  Yes I could definitely put the small key in SMS parameter store.  But in the built Rails container that small key needs to exist in the file `/config/credentials/test.key`  ... So I would either have to write/create that file in Dockerfile or write it in buildspec.yml.   Which would you recommend?

**Comment by huanjani** [comment]
I believe you can use the env var `RAILS_MASTER_KEY`. (Sorry, I don't have at ton of experience with Rails.) That seems easier than writing it in either your Dockerfile or buildspec. Let me know if that works!

**Comment by DaveCollinsJr** [comment]
Thanks @huanjani - I am using Rails 6 with multi-environment encrypted credentials so I really need this file.  I will also need it for other environments but that will come later.  If I did need to access the AWS credentials inside of Docker running from Copilot / CodePipeline what would be the best copilot way to do that?

**Comment by huanjani** [comment]
Ah, gotcha, @DaveCollinsJr! Sorry for answering questions you weren't asking! 😂  

My Copilot teammate, @efekarakus,  has come up with a couple ideas:
1. You could `exec` into your "web" service and [create and hydrate an EFS file system]( https://aws.github.io/copilot-cli/docs/developing/storage/#hydrating-a-managed-efs-volume) with `/config/credentials/test.key`.
2. You could leverage `ENTRYPOINT` and a script in the Dockerfile
- Upload the content of the file to a private S3 bucket.
- Follow the pattern here in your Dockerfile: https://github.com/bvtujo/copilot-wordpress/blob/main/Dockerfile#L9-L10
- Download the contents of the file from S3 in a separate bash script (https://github.com/bvtujo/copilot-wordpress/blob/main/startup.sh) and then start the rails application

**Comment by DaveCollinsJr** [comment]
Fantastic @huanjani I will try those things and post the results here later this week in case anyone else would be helped.

**Comment by DaveCollinsJr** [comment]
@huanjani so it turns out that you were right about RAILS_MASTER_KEY!  You can use RAILS_MASTER_KEY (setting it to the value of your /config/environment.key) in a per-environment credentials scenario.

Apparently Rails changed this in this PR: [Fixed to RAILS_MASTER_KEY as a default env key for decrypting](https://github.com/rails/rails/pull/33928/files)

I will go in that direction as that should be much more straightforward.  Thanks!!
