### ISSUE TITLE
ECS Deployment Circuit Breaker was triggered

### ISSUE THREAD

**Issue by allemanfredi** [aws/copilot-cli#2584]
Hello guys,

I'm trying to deploy a service by running this command:

```
copilot svc deploy --name ethereum --env staging
```

but i get the following error at this step `- An ECS service to run and maintain your tasks in the environment cluster`:

```
Resource handler returned message: "Error occurred during operation 'ECS Deployment Circuit Breaker was triggered'.(RequestToken: 256edf08-7afc-0783-a02f-4fd6be3a7e60, HandlerErrorCode: GeneralServiceException)
```

Thanks

**Comment by huanjani** [comment]
Hello @allemanfredi!

Can you go into your ECS console to see if there's more information on why Circuit Breaker was triggered?

Thanks!

**Comment by kohidave** [comment]
Yea, typically this means that the service failed to start up. Often this is because a health check is failing. By default, Copilot expects frontend services to return an HTTP 200 on the `/` path.

**Comment by allemanfredi** [comment]
Thanks both (@huanjani @kohidave)! unfortunately i still have the problem!

@kohidave i tried to create an apposite api for the health check but i receive the same error!

**Comment by allemanfredi** [comment]
@huanjani by checking the ECS logs i noticed this error:

`InternalError: failed to normalize image reference "Dockerfile"`

**Comment by allemanfredi** [comment]
I had an error in my manifest file.

I changed from:

```
image:
  location: Dockerfile
```
  
 into:

```
image:
  build: Dockerfile
```

but now i get `ResourceInitializationError: unable to pull secrets or registry auth: pull command failed: : signal: killed`.

ps: i'm not using any secret

**Comment by allemanfredi** [comment]
fixed! I accidentally forgot to put the internet gateway on the public subnet where the task was being deployed

**Comment by huanjani** [comment]
Glad it's working now! 🎉
