### ISSUE TITLE
Manually deleting environment resources

### ISSUE THREAD

**Issue by sunaulo-suhail** [aws/copilot-cli#2591]
I am new to **copilot** & **ECS**.
I was just experimenting with **ECS** & **copilot cli**

I have created two envs ```dev``` & ```prod```

Now when I delete the ```dev``` env it throws the following error what could be the reason to it?

```
✘ get environment dev configuration from app : get environment dev in application : ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
        status code: 400, request id: b068bc5f-6c40-45e3-a5cd-eabf1f82a99a
```

I have deleted all the dev related stuff in my manifest files like secrets.

**Comment by sunaulo-suhail** [comment]
Also what are the things needed to clear all the resources manually, can anyone tell me please

**Comment by mvn-bachhuynh-dn** [comment]
Hi @sunaulo-suhail ,
You could delete manual:
- Delete Stacks in Cloudformation.
- Delete folder copilot/subfolder.

To understand what does Copilot do?!
When you type a command, please take a look the Cloudformation right after that.
You will see the charming! 

Hope it helps!

**Comment by efekarakus** [comment]
Hi @sunaulo-suhail !  
+1 to the comment above from @mvn-bachhuynh-dn :) 
Under the hood the `env delete` command will remove the cloudformation stack: `{app}-{env}` and the AWS Systems Manager Parameter Store parameter `/copilot/applications/{app}/environments/{env}`. Once you delete both you should be in a clean state.

**Comment by sunaulo-suhail** [comment]
Successfully managed to delete all the resources by deleting the cloud formation stacks.

can any one please update the this issue's title so that it's helpful for other developers to google it. [my English is not so good.]
