### ISSUE TITLE
Error while deploying - Target group '*' is currently in use by a listener or a rule

### ISSUE THREAD

**Issue by guyschlider** [aws/copilot-cli#2593]
Hey,

After a change, I made to the manifest.yml (changed the memory value) of a service that is already running - I'm getting this error about a Target group that I have already deleted after seeing this error, which persists.

```
latest: digest: sha256:6a5b30c0001dd2ccbbb7d3975c271dc0d16839b8cb805bd74742c21e00fcdf14 size: 5766
- No new infrastructure changes for stack SERVICE-test-rest-apiapi 
✘ deploy service: change set with name copilot-7d2015fb-470e-42c7-9ae6-01ee079b835f for stack SERVICE-test-rest-api has no changes: Target group 'arn:aws:elasticloadbalancing:us-east-1:0000000000:targetgroup/NAME-Targe-7Q2RZ7K7VE6M/f000c991202e53a2' is currently in use by a listener or a rule (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: ResourceInUse; Request ID: 2fd856dc-7669-465d-a3fb-e2e74a3cfa90; Proxy: null)
```

Any ideas?

**Comment by guyschlider** [comment]
Update: changing the memory value back to the previous value - and deploy is now working. 

I'm really confused :)

**Comment by efekarakus** [comment]
Hi @guyschlider 👋 

That is super strange! I wonder if the value of the memory setting was invalid? 🤔 
Here is the table for valid `cpu` and `memory` settings for Fargate: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-tasks-size


CPU value | Memory value
-- | --
256 (.25 vCPU) | 0.5 GB, 1 GB, 2 GB
512 (.5 vCPU) | 1 GB, 2 GB, 3 GB, 4 GB
1024 (1 vCPU) | 2 GB, 3 GB, 4 GB, 5 GB, 6 GB, 7 GB, 8 GB
2048 (2 vCPU) | Between 4 GB and 16 GB in 1-GB increments
4096 (4 vCPU) | Between 8 GB and 30 GB in 1-GB increments

**Comment by guyschlider** [comment]
Actually when the value is invalid there is a different error

Here when I change from 1vcpu and 3072mb of memory to 1vcpu with 2048mb of memory - I get this weird LB error

I can also mention that I have created a forward rule manually in the LB to handle https, but I can't see how changing the memory value cause the changeset to raise this error

**Comment by efekarakus** [comment]
Hmm that is strange!

I wonder why the target group is being updated 🤔 One thing that might help with troubleshooting is re-running `copilot deploy` with the changes that will cause the failure.  
Then going to the AWS CloudFormation console and clicking on the stack that's being updated, under the "Change sets" tab there should be the change set and when clicked on it it will show the changes that are being proposed. 

Would you mind copy pasting the changes that get proposed here? maybe that will help us understand which resources are being touched and why

**Comment by guyschlider** [comment]
Wooha, Suddenly it just works, I have no clue what was going on. Closing for now.

Thanks for your quick response!

**Comment by efekarakus** [comment]
Awesome glad the heisenbug went away!
