### ISSUE TITLE
Changes to service discovery endpoints in Copilot 1.9.0

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#2601]
Prior to Copilot v1.9.0, the service discovery namespace used the format `{app name}.local`, without including the environment. This limitation made it impossible to deploy multiple environments in the same VPC. Any environments created with Copilot v1.9.0 and newer can share a VPC with any other environment.

When your environments are upgraded, Copilot will honor the service discovery namespace that the environment was created with. That means that the endpoint your services are reachable at will not change. Any new environments created with Copilot v1.9.0 and above will use the _{env name}.{app name}.local_ format for service discovery, and can share VPCs with older environments. 

This will break customers who fit the following profile:
1. Have a service whose code includes hardcoded service discovery endpoint variables (eg `var SvcDiscoveryEndpoint = "app.local"`)
2. Create a new environment with Copilot 1.9.0
3. Deploy this service into the new environment.
For these customers, requests to `svc.app.local` will fail to resolve, as the new environment's Service Discovery endpoint will be `svc.env.app.local`.

Customers whose code relies on the Copilot environment variable `COPILOT_SERVICE_DISCOVERY_ENDPOINT` will be unaffected by this change, as the variable's value will be updated to reflect the new service discovery paradigm.

**Comment by iamhopaul123** [comment]
Close as this feature has been released.
