### ISSUE TITLE
Copilot errors out when trying to deploy a sample application

### ISSUE THREAD

**Issue by pcgeek86** [aws/copilot-cli#2605]
```
[cbt]C:\git\copilot> $env:AWS_PROFILE='cbt'
[cbt]C:\git\copilot> copilot init --name trevor
Note: It's best to run this command in the root of your Git repository.
Welcome to the Copilot CLI! We're going to walk you through some questions
to help you get set up with a containerized application on AWS. An application is a collection of
containerized services that operate together.

Application name: trevor
Workload type: Scheduled Job
Dockerfile: Use an existing image instead

  What's the location of the image to use? [? for help] nginx
Image: nginx
Schedule type: Fixed Schedule
Fixed Schedule: Hourly
Ok great, we'll set up a Scheduled Job named trevor in application trevor running on the schedule @hourly.

√ Created the infrastructure to manage services and jobs under application trevor..

√ Wrote the manifest for job trevor at trevor\manifest.yml
Your manifest contains configurations like your container size and job schedule (@hourly).

√ Created ECR repositories for job trevor..

Deploy: Yes

X Failed to link account XXXXXXXXXXXX and region us-west-2 to application trevor.

X deploy env test to application trevor: adding new stack instance for environment test: operation AB43DBEB-485E-49E5-B0F8-BF4F995012EC for stack set trevor-infrastructure failed
```

**Comment by efekarakus** [comment]
Hi @pcgeek86 !

That's strange! Would you mind navigating to the AWS CloudFormation console and clicking on the stack that failed to create?
Under the "Events" tab there might be more information on why it failed to created. If you can take a screenshot/copy paste here we can help troubleshoot the issue.


If nothing is available there then there should be a tab for "StackSets" on the left navigation panel in CloudFormation. And then under the "Operations" tab there should be additional information on why the operation failed.

Thank you!

**Comment by pcgeek86** [comment]
Hello @efekarakus, here's the information you requested. 

![image](https://user-images.githubusercontent.com/466713/125507733-d9743473-f232-4daf-9f35-d5f359d05493.png)

Also, there's a CloudFormation stack which succeeded to create here:

![image](https://user-images.githubusercontent.com/466713/125507772-92e11bfe-85e3-4575-a38c-fc0c48ecd0d4.png)

**Comment by pcgeek86** [comment]
I think I may have encountered a condition where an automated AWS account cleanup process, which I created, destroyed the IAM roles for this. I deleted the CloudFormation stack named `trevor-infrastructure-roles` and am trying to start from scratch again.

**Comment by efekarakus** [comment]
Sounds good yup! those roles are needed for the application to be created
