### ISSUE TITLE
Circuit breakers configurable timeout?

### ISSUE THREAD

**Issue by nbarrera** [aws/copilot-cli#2608]
Hi guys, I 've checked [this issue](https://github.com/aws/copilot-cli/issues/1180) already but I still have doubts on this one.

If I try to deploy a service which constantly fails the health checks (so it will never end up deploying)

the copilot svc deploy command retries until failing around 10 times.

And the running time of that commands goes up to something like 1 hour.

As I have that command run in an automated fashion I would like the `svc deploy` command have a configurable timeout or number of failures before aborting the deploy.

Is that possible?

thank you

**Comment by efekarakus** [comment]
Hi @nbarrera !

Unfortunately there isn't a way of configuring the circuit breaker behavior today 🙇 

Would you mind giving a 👍 to this issue in the containers-roadmap for ECS: https://github.com/aws/containers-roadmap/issues/1247 whenever ECS supports it we'll be able to surface that information back to you in the manifest!

**Comment by efekarakus** [comment]
I'll close the issue in the mean time until support comes out! Thank you!
