### ISSUE TITLE
Minimum IAM role/permissions for a user to use copilot

### ISSUE THREAD

**Issue by guyschlider** [aws/copilot-cli#2615]
Hey,

We use Github actions for our CI/CD and in order to create new IAM access keys for deployment I wonder what is the best practice or minimum required permissions in order to allow copilot deployments?

**Comment by efekarakus** [comment]
Hi @guyschlider !

In the github action, are you running only `copilot deploy --env <name>`? or are there any other commands?

We don't have one defined at the moment but I have successfully run `copilot deploy` with the following set of attached policies:
- `AmazonSSMReadOnlyAccess `
- `AWSCloudFormationReadOnlyAccess `
- A new policy to assume the `EnvManagerRole`:
```json
{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Action": "sts:AssumeRole",
        "Resource": [
            "arn:aws:iam::XXXXXXXX:role/{app}-{env}-EnvManagerRole"
        ]
    }
}
```
- A new policy to put objects in Copilot S3 buckets to upload zip files for Lambda functions:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:PutObject",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "s3:ResourceAccount": "XXXXXXX"
                }
            }
        }
    ]
}
```
- A new policy to build and push images to ECR repositories:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:DescribeRepositories",
                "ecr:GetAuthorizationToken",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:PutImage",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability"
            ],
            "Resource": "*"
        }
    ]
}
```

There are probably ways of scoping these down further but this could be a starting point!

**Comment by buddhike** [comment]
Thanks for sharing this @efekarakus. I was also looking for a way to handle this scenario and this is great! ❤️
Do you know if `EnvManagerRole` has the ability to update `env` and  `app` infrastructure as well? If it has, we would be able to update Copilot binary version used in pipelines.

**Comment by efekarakus** [comment]
Hi @buddyspike !

The `EnvManagerRole` has indeed the necessary permissions to update the `env` stack but not the application infrastructure!

**Comment by guyschlider** [comment]
Thanks, @efekarakus !

**Comment by huanjani** [comment]
Related: https://github.com/aws/copilot-cli/issues/2941

**Comment by Kylir** [comment]
Hello,
In my AWS account I tried to set up a user group with the policies listed here and I'm receiving the following error:
(Note: in addition to the listed policies, I added a "Deny" condition for all the SSM parameters with the tag "Production".)

> select application: list applications: list applications: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: 820eae47-XXXXXXXXXXXXXXXXX

What am I doing wrong?
Thank you very much!

**Comment by huanjani** [comment]
Hi, @Kylir! 
Have you run `aws configure` since changing your setup?

**Comment by Kylir** [comment]
Hi @huanjani! Thanks for the response :)

No, I don't think my colleague ran `aws configure` after I did the changes. She did it once few months ago and her aws cli works fine.

As an admin I'm setting up the permissions for my team. I really would like them to use copilot to see the logs and the pipelines. For me it's working fine and I created many services over the past year.

Would it be possible that Copilot works only for me? Or did I miss some permissions for my colleagues' user group?
Where is Copilot searching for the applications? I granted read only perms for CloudFormation and SSM.

**Comment by huanjani** [comment]
Copilot generates the list of applications based on SSM. 

Is everything in here https://aws.github.io/copilot-cli/docs/credentials/ as you have set things up? Is the region the correct region?

Something you might consider for limiting certain groups' permissions is to use permissions boundaries-- https://aws.github.io/copilot-cli/blogs/release-v122/#iam-role-permissions-boundary

**Comment by Kylir** [comment]
Hi @huanjani,
Apologies for the troubles - it wasn't Copilot's fault.
Your intuition was right! Something must have happened to the credentials. My colleague wasn't even able to use the aws cli. We regenerated a set of key and ID and now it's working fine!
Thanks a lot for your help!

**Comment by huanjani** [comment]
@Kylir-- Great! Glad you're up and running again!

**Comment by alickwong** [comment]
im running the Copilot CLI in an EC2 instance to deploy "Load Balanced Web Service". Here is my instance profile policy for reference:

* AmazonSSMReadOnlyAccess
* Following inline policy
```
{
	"Version": "2024-10-20",
	"Statement": [
		{
			"Effect": "Allow",
			"Action": [
				"ecs:*",
				"ecr:*",
				"cloudformation:*",
				"logs:*",
				"tag:*",
				"ssm:*",
				"kms:*"
			],
			"Resource": "*"
		},
		{
			"Effect": "Allow",
			"Action": [
				"s3:*"
			],
			"Resource": "arn:aws:s3:::stackset-{APP_NAME}*"
		},
		{
			"Effect": "Allow",
			"Action": [
				"iam:PassRole",
				"iam:DeleteRolePolicy",
				"iam:GetRole",
				"iam:DeleteRole",
				"iam:CreateRole",
				"iam:TagRole",
				"iam:PutRolePolicy",
				"sts:AssumeRole"
			],
			"Resource": "arn:aws:iam::{ACCOUNT_ID}:role/{APP_NAME}*"
		}
	]
}
```

I know it can be further scope down, just for reference.
