### ISSUE TITLE
Database URL as environment variable

### ISSUE THREAD

**Issue by Simbul** [aws/copilot-cli#2624]
I've been setting up a Load Balanced Web Service backed by a DB (Postgres on Aurora Serverless, in my case).

While having an environment variable that contains credentials in JSON form is very clever, I'm wondering why go for that instead of providing a more simple URL. Something like `postgres://user:pass@host:5432/dbname`.

In my experience, which of course is by no means universal, that's the format that almost all tools and clients work with and it's a pretty compact way to store all the info you need in order to connect.

I've built some simple logic to parse JSON from the environment variable and extract what I need, but I'm ending up having to generate a URL anyway, because of those aforementioned tools. It feels like doing things backwards somehow 😄 

I'd be keen to understand more about the reasoning behind the choice and whether having a DB URL could be a valuable feature request.

**Comment by efekarakus** [comment]
Hi @Simbul 👋 

Thank you for reaching out!
I believe we wrote the output this way due to security concerns. If I am understanding it correctly, this would require us to write the URL with the password in plain text, so the source code will contain the secret value which is a scenario we'd like to avoid. 

As a compromise like you have done, we are injecting the secret as env var and in the application code it has to be parsed.

We could improve our output though to not only show how to parse the variable, but also fill the url!

**Comment by Simbul** [comment]
Hi @efekarakus. Thanks for the answer.

I agree that the password (at the very least) needs to be treated as a secret. What I had not realised is that Secrets Manager natively supports [JSON structures](https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html#term_secret) to represent credentials. So my assumption - having dug a bit into the code - is that it was done because it's just easier to store DB credentials in Secrets Manager as JSON and then dump the same exact format into an ENV variable.

I'm not an expert with CloudFormation: would it be possible to create a different ENV variable and store the URL in it, populating it from the JSON secret? It wouldn't add security issues, AFAICS, because there's already one ENV variable with unencrypted credentials anyway. This would just be for extra convenience.

I tried adding this new output to my DB TerraForm template (as you can guess, `apicluster` is the name of my DB cluster):
```terraform
Outputs:
  apiclusterUrl: # should be later injected as APICLUSTER_URL environment variable
    Description: "A URL that can be used to connect to the database"
    Value: !Sub
      - ${engine}://${username}:${password}@${host}:${port}/${dbname}
      - {
        engine: !Join [ "",  [ '{{resolve:secretsmanager:', !Ref apiclusterAuroraSecret, ":SecretString:engine}}" ]],
        username: !Join [ "",  [ '{{resolve:secretsmanager:', !Ref apiclusterAuroraSecret, ":SecretString:username}}" ]],
        password: !Join [ "",  [ '{{resolve:secretsmanager:', !Ref apiclusterAuroraSecret, ":SecretString:password}}" ]],
        host: !Join [ "",  [ '{{resolve:secretsmanager:', !Ref apiclusterAuroraSecret, ":SecretString:host}}" ]],
        port: !Join [ "",  [ '{{resolve:secretsmanager:', !Ref apiclusterAuroraSecret, ":SecretString:port}}" ]],
        dbname: !Join [ "",  [ '{{resolve:secretsmanager:', !Ref apiclusterAuroraSecret, ":SecretString:dbname}}" ]],
      }
```

I can see the output when I execute the template in CF, but the `resolve` directives are not expanded, so the values are not interpolated (see my redacted screenshot below). I wonder if that directive just doesn't work in `Outputs` (some potential evidence [here](https://stackoverflow.com/a/54663677/551557)).

![Screenshot 2021-07-17 at 11 19 58](https://user-images.githubusercontent.com/147104/126033972-278cfc58-353e-41a3-8f96-1adf09fa151f.png)

Alternatively, I wonder if we could do the same in the [envvars template](https://github.com/aws/copilot-cli/blob/mainline/templates/workloads/partials/cf/envvars.yml).

Keen to hear what you or others here think of the approach. If it doesn't work as a feature request, I'd love to at least be able to figure out the most efficient way of doing this just for myself 🙂

**Comment by bvtujo** [comment]
HI @Simbul, 

My other recommendation as a workaround, instead of possibly exposing secrets manager references in plaintext in the template, is to use `copilot secret init` to create the secret value you need: 

1. Grab the secret from Secrets Manager and store it in a file:
```bash
aws secretsmanager list-secrets --query "SecretList[].Name"
# Using the name that includes your service and aurora, run the following:
aws secretsmanager get-secret-value --secret-id $SECRET_NAME > secret.json
```
2. Construct your URL
```bash
export uri=`jq -r '.SecretString' secret.json | jq -r '"postgres://\(.username):\(.password)@\(.host):\(.port)/\(.dbname)"'`
```
You can do this for each environment you need to deploy this secret to.
3. Run `copilot secret init` to initialize your secret.
```bash
copilot secret init -n postgres-url --values $ENVNAME=$uri
```
4. Modify the `environments` section of your manifest to include the output secret paths. It will look like this:
```yaml
environments:
  test:
    secrets:
      apiClusterUrl: /copilot/$appname/test/secrets/postgres-url
  prod:
    secrets:
      apiClusterUrl: /copilot/$appname/prod/secrets/postgres-url
```

**Comment by neilbmclaughlin** [comment]
For anyone else struggling with this problem thought it was worth a heads up that the CloudFormation code above by @Simbul works for me allowing the creation of a Postgres URL env var with a name of my choosing. Not sure what has changed in CloudFormation or copilot (1.9.0) but the resolve directives are working for me. I'm not using Terraforms just a copilot RDS addon.

As background, my use case is that, as part of my application, I'm deploying a [PostgREST](https://postgrest.org/en/v7.0.0/install.html?highlight=PGRST_DB_URI#docker) docker image and need a DB URL env var called PGRST_DB_URI to work with PostgREST convention.
