### ISSUE TITLE
Configure HTTPS without a custom Domain?

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2625]
I have a requirement that my services must be using HTTPS, but I have no need for a custom domain. 
Since ALB requires a custom domain for an HTTPS listener, this seems like a dead end.

The only thing I can think of at the moment to get around this would be to create a API Gateway as an addon to sit in front of my load balancer (since it comes with HTTPS out of the box), but that seems like messy overkill. 

Figured I would ask here to see if anyone had any thoughts or advice. I'd really like to avoid having to purchase a domain and setting up Route 53 if at all possible.

**Comment by afgallo** [comment]
> The only thing I can think of at the moment to get around this would be to create a API Gateway as an addon to sit in front of my load balancer (since it comes with HTTPS out of the box), but that seems like messy overkill.

Another idea is to use Cloudfront in front of your ALB. This would give you more flexibility in the future as you can lock down your ALB to be accessible via Cloudfront only and enhance security via WAF, etc.

I do understand the extra work though.

**Comment by bvtujo** [comment]
Hey @mikelhamer, we can't currently support HTTPS without a custom domain, as ALB doesn't expose an HTTPS endpoint by default. Under the hood, the default DNS hosted zone for ALBs is owned internally by the load balancer and is not accessible through customer-facing tools. That means we can't validate the required SSL certificate for the default LB domain with our custom resources. 

Like you said, you could create an API gateway in front but I understand this is more work than you'd really want to own for this purpose. If it's any consolation, we make setting up a custom domain for your app incredibly easy--all you need is to purchase a domain in your application's account, then we'll create all the necessary hosted zones cross-account and cross-region so your environments get traffic correctly routed.

**Comment by mikelhamer** [comment]
Thank you both for the insight and suggestions!
