### ISSUE TITLE
`copilot task run` with `--secrets` option raise error AccessDeniedException

### ISSUE THREAD

**Issue by shgtkshruch** [aws/copilot-cli#2641]
Hi, there. I would like to run database migration command with [`copilot task run`](https://aws.github.io/copilot-cli/en/docs/commands/task-run/).

But `copilot task run` command with `--secrets` option raise `AccessDeniedException` error.
Secrets is created by [`copilot secret init`](https://aws.github.io/copilot-cli/en/docs/commands/secret-init/) command, and store in Parameter Store.

![スクリーンショット 2021-07-21 12 51 22](https://user-images.githubusercontent.com/5207601/126428047-7312dc44-b5e9-4a65-bd53-b0fb10bdafa1.png)

```sh
$ copilot --version
1.8.3

$ copilot task run \
  --app chronos \
  --env dev \
  --image 123456789.dkr.ecr.ap-northeast-1.amazonaws.com/chronos/rails:a40efe96b90bf506d834a57a5e476ecdbc935793 \
  --command 'bin/rails db:prepare' \
  --env-vars RAILS_LOG_TO_STDOUT=true,RAILS_ENV=dev \
  --secrets RAILS_MASTER_KEY=/copilot/chronos/dev/secrets/RAILS_MASTER_KEY \
  --follow

- No new infrastructure changes for stack task-chronosnos 
✘ Failed to run chronos.be running for chronos. 

✘ run task chronos: run task chronos: task 1c350295: ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm: service call has been retried 1 time(s): AccessDeniedException: User: arn:aws:sts::123456789:assumed-role...
```

ECS console is bellow.

![スクリーンショット 2021-07-21 12 30 51](https://user-images.githubusercontent.com/5207601/126427551-f5d48fe9-1c3b-48f0-aae6-4b5a37fe8922.png)

I think task execution role dose not have enough authority to pull secrets from Parameter Store. I know copilot task run has `--execution-role` option, but I don't know what value should specify for this option. How can I fix this error? Thank you!

**Comment by Lou1415926** [comment]
Hi @shgtkshruch!

You are correct - the default execution role for the task doesn't have permission to pull secrets from ssm at this moment in order to limit the scope of a one-off task. 

The easiest way to achieve your goal is to modify the existing default execution role we've created and attached to the task for you.

You can go to your CloudFormation management console > look for the task stack (named `task-<task-name>`) > go to "Resource" tab > look for the resource with logical ID "DefaultExecutionRole" > click on its "Physical Resource" link. This will lead you to the page where you can configure the execution role we've created for you.
<img width="1534" alt="Screen Shot 2021-07-21 at 11 04 25 AM" src="https://user-images.githubusercontent.com/79273084/126538187-9c5c1da1-2ae5-4af4-bad8-d630f26beff8.png">

In that page, click on "(+) Add inline policy". You can go to "JSON" tab and paste in the following snippet:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": ["ssm:GetParameters"],
            "Resource": ["arn:aws:ssm:ap-northeast-1:<your-account-id>:parameter/*"],
            "Condition": {
                "StringEquals": {
                    "ssm:ResourceTag/copilot-application": "chronos",
                    "ssm:ResourceTag/copilot-environment": "dev"
                }
            }
        }
    ]
}
```
This will allow your execution role to access secrets created for the application chronos and the environment dev!

**Comment by Lou1415926** [comment]
Alternatively, to take advantage of the `--execution-role` flag, you can create an IAM role with necessary permissions and provide its ARN for `--execution-role`.

Here is a detailed instruction to create an task execution role through either the console or AWS CLI: [ECS doc ](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html#create-task-execution-role). 

In addition to the required `AmazonECSTaskExecutionRolePolicy` policy, as instructed by step 5 (and step 3 if using AWS CLI) in [ECS doc ](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html#create-task-execution-role), you will also need the inline policy with the `ssm:GetParameters` permission I've provided above.

The second solution, i.e. taking advantage of `--execution-role` is recommended as it's more stable, and the IAM role you created can also be reused on other tasks launched in the same application and environment.

The first solution (i.e. modifying the role we created fr you) requires less churn. However, if for any reason the `DefaultExecutionRole` part of the CFN template is modified (either by you or us), CFN will update the role with that modified template, overriding your modification done manually through console as instructed by the first solution.

**Comment by shgtkshruch** [comment]
@Lou1415926 Thank you response! I was able to fetch secrets from SSM as update default execution role created by copilot.
Is it possible that is user pass `--secrets` option to `copilot task run` command, copilot auto create or update execution role to fetch secrets from SSM. I think it is very useful for users.

**Comment by Lou1415926** [comment]
@shgtkshruch Agreed! I've added the "enhancement" label so that we can circle back and implement this. Thanks for the great idea!

**Comment by efekarakus** [comment]
Hi folks! The fix is now released https://github.com/aws/copilot-cli/releases/tag/v1.16.0 🥳 

See announcement: https://aws.github.io/copilot-cli/blogs/release-v116/
