### ISSUE TITLE
Service Deploy with alias not working

### ISSUE THREAD

**Issue by nbarrera** [aws/copilot-cli#2644]
Hi guys I created a new test app with a service that's just the nginx docker image.

I wanted to test how copilot relates with domains now that I 've just got a domain name delegated to Route53.

so lets say I got domain `example.com` delegated into Route53.

Then I created a new hosted zone for a subdomain: `sub1.example.com` I 've took its name servers and put them in a NS record for the `example.com` hosted zone.

Then did that again and came up with `sub2.sub1.example.com`.

Now I 've created the new copilot app using `copilot app init --domain sub2.sub1.example.com` and then `copilot init`

I could check that new hosted zones were created for `${svcname}.sub2.sub1.example.com` and `${env}.${svcname}.sub2.sub1.example.com`

modified the manifest to provide `alias: sub3.sub2.sub1.example.com`

issue `copilot svc deploy` which fails.

```
Environment test is already on the latest version v1.4.1, skip upgrade.
✔ Proposing infrastructure changes for stack XXX 
- Updating the infrastructure for stack XXX                       [update rollback complete]  [427.1s]
  The following resource(s) failed to update: [HTTPListenerRuleWithDomai                                       
  n, HTTPSListenerRule, TaskDefinition].                                                                       
  - Update your environment's shared resources                                     [update complete]           [135.4s]
    - Request and validate an ACM certificate for your domain                      [delete complete]           [5.9s]
    - Add an A-record to the hosted zone for the domain alias                      [create complete]           [37.6s]
  - An ECS service to run and maintain your tasks in the environment cluster       [not started]                
  - An ECS task definition to group your containers and run them on ECS            [delete complete]           [3.6s]
    Resource creation cancelled                                                                                
✘ deploy service: stack XXX did not complete successfully and exited with status UPDATE_ROLLBACK_COMPLETE
```

Then at cloud formation stack events I can see something, but it's not enough info for me to know what's really happening, I wonder if you could help me to spot the cause of the error or just guide me on how to get more insights on how to discover the root cause.

```
Logical ID
TaskDefinition

Resource creation cancelled
```

```
Logical ID
HTTPSListenerRule

CustomResource attribute error: Vendor response doesn't contain Priority key in object arn:aws:cloudformation:us-west-2:511754385474:stack/XXX/0e39ee60-ea46-11eb-b9c8-02778aa47ed3|HTTPSRulePriorityAction|1026b1aa-566d-4c24-a510-4122b3bfb77c in S3 bucket cloudformation-custom-resource-storage-uswest2
```

```
Logical ID
HTTPSListenerRule

CustomResource attribute error: Vendor response doesn't contain Priority key in object arn:aws:cloudformation:us-west-2:511754385474:stack/XXX/0e39ee60-ea46-11eb-b9c8-02778aa47ed3|HTTPSRulePriorityAction|1026b1aa-566d-4c24-a510-4122b3bfb77c in S3 bucket cloudformation-custom-resource-storage-uswest2
```

```
Logical ID
HTTPListenerRuleWithDomain

CustomResource attribute error: Vendor response doesn't contain Priority key in object arn:aws:cloudformation:us-west-2:511754385474:stack/XXX/0e39ee60-ea46-11eb-b9c8-02778aa47ed3|HTTPSRulePriorityAction|1026b1aa-566d-4c24-a510-4122b3bfb77c in S3 bucket cloudformation-custom-resource-storage-uswest2
```

If I try without setting the alias it works properly using the `${env}.${svcname}.sub2.sub1.example.com` domain.

**Comment by bvtujo** [comment]
Oh no, let me see if I can reproduce this issue locally! This sounds like a bug, but DNS is always tricky and there may be some subtlety with the subdomain and NS records. Let me check...

**Comment by bvtujo** [comment]
I'm also having issues with ACM at the moment; it seems like certs are taking a long time to validate. I and some others are also having cert validation issues.

Can you try to do this by just creating a subdomain without copying over the NS or SOA records? Let Route53 default to whatever it's going to do when you create `sub3`, then try to reinitialize the app with `copilot app init --domain sub3.domain.com`?

Could you also paste your manifest (or a sanitized version) so we can take a look?

Thank you so much.

**Comment by nbarrera** [comment]
I 've created route 53 hosted zones

* example.com (assigning sub1's NS record)
* sub1.example.com (assigingin sub2's NS record)
* sub2.sub1.example.com

Then came up with a brand new copilot app

`--domain sub2.sub1.example.com`

then added

`alias: mynewname.sub2.sub1.example.com`

and worked like a charm:

```
✔ Deployed mysvc, you can access it at https://mynewname.sub2.sub1.example.com.
```

not really sure what went wrong before I tried to do exactly that.

Thanks for your suggestions and sorry for interrupting you guys.
👋
