### ISSUE TITLE
How to configure private registry credentials?

### ISSUE THREAD

**Issue by coffeedome** [aws/copilot-cli#2653]
I have a private ontainer registry that requires docker -login whenever I'm trying to run my docker build locally. 

For ECS I realize I can use secrets manager and use repositoryCredentials in the containerDefinition.

What do I need to do to get this working with Copilot? Is there somewhere in the manifest where I should add it?

I've already tried adding an entry to my ~/.docker/config.json file (like I had to for ECR) but that didn't work.

Appreciate if this can also be addressed in an example in the Copilot official documentation.

Thanks!

**Comment by huanjani** [comment]
Hi, @estebanes22! 

Does [this](https://github.com/aws/copilot-cli/pull/2582) solve your issue? It will be included in our next release, tentatively scheduled for next week!

**Comment by coffeedome** [comment]
> Hi, @estebanes22!
> 
> Does [this](https://github.com/aws/copilot-cli/pull/2582) solve your issue? It will be included in our next release, tentatively scheduled for next week!

Yup it should! Thank you!

**Comment by huanjani** [comment]
@estebanes22 -- It's been released! https://github.com/aws/copilot-cli/releases/tag/v1.9.0

**Comment by coffeedome** [comment]
Awesome!!!
