### ISSUE TITLE
"update in progress" stuck

### ISSUE THREAD

**Issue by dimasusername** [aws/copilot-cli#2672]
During `copilot svc deploy` sometimes when the application fails to start (boot error, or something similar), the deployer will continue trying to restart the app for a very long time.

<img width="905" alt="Screenshot 2021-07-28 at 21 12 44" src="https://user-images.githubusercontent.com/7683329/127374523-d8346379-7ec8-4017-9c43-73b194fcbba7.png">

And to deploy the fix, I either have to wait, or go into the AWS Console, cancel the cluster update and rollback, which is troublesome.

Is there any way to stop this process from the cli and re-deploy a new version of the image? Or at least control the number of retries and the delay between them?

**Comment by huanjani** [comment]
Hello @dimasusername! 
I believe your long delay is due to Circuit Breaker waiting for 10 failures.
Would you mind adding a 👍🏼  here: https://github.com/aws/containers-roadmap/issues/1247 ?
Thanks!

**Comment by efekarakus** [comment]
Heya! I'll close this issue for now, once the circuit breaker behavior provides more configuration knobs we will surface it in the manifest files!
