### ISSUE TITLE
copilot deploy hangs if no [default] credential is set

### ISSUE THREAD

**Issue by tiivik** [aws/copilot-cli#2686]
I had accidentally commented out the default region in my AWS credentials like so:
```
#[default]
aws_access_key_id=key-here
aws_secret_access_key=key-here
```
Then, running `copilot deploy --name api --env test` the command just hangs, does not error out or provide any context of why the deploy was hanging.

My mistake ofc, but could be useful if an error message was displayed.

**Comment by Lou1415926** [comment]
Hi @tiivik ! Thanks for bringing this to our attention. It indeed hangs when credential is commented out while region is not. We will look into this and see how we can improve the error messaging!

**Comment by tiivik** [comment]
> Hi @tiivik ! Thanks for bringing this to our attention. It indeed hangs when credential is commented out while region is not. We will look into this and see how we can improve the error messaging!

Thank you, appreciate it!

**Comment by efekarakus** [comment]
Related https://github.com/aws/copilot-cli/issues/2731

**Comment by efekarakus** [comment]
Related https://github.com/aws/copilot-cli/issues/2547

**Comment by efekarakus** [comment]
This fix is now released in https://github.com/aws/copilot-cli/releases/tag/v1.11.0! 🎉
