### ISSUE TITLE
list services in the workspace: yaml: line 33: did not find expected alphabetic or numeric character

### ISSUE THREAD

**Issue by ericterpstra** [aws/copilot-cli#2689]
I came back to a copilot project after a few weeks. The service has been running for quite a while without issue. All I updated was a small bit of code in the project. I tried to deploy with:
`copilot svc deploy` 
and was greeted with:
```
copilot svc deploy --name core-ws
✘ list services in the workspace: yaml: line 33: did not find expected alphabetic or numeric character
```
I don't see a workspace yaml file anywhere.

Most other copilot commands work, though.

```
copilot svc ls
Name                Type
----                ----
core-ws             Load Balanced Web Service
```

I don't remember deleting a "workspace" file. I also don't remember having one. Is this necessary? Is there a way to get it back without starting over?

**Comment by ericterpstra** [comment]
Ok, found the issue. There was an asterisk in my `manifest` file. I put it in quotes, and the deploy worked. :) 

This is the second time I've had an error in my manifest, but the error message pointed to the workspace file.  I think I might open a feature request to clarify the error messages.

**Comment by efekarakus** [comment]
Awesome glad you got it to work! Yea it makes sense to throw better errors if the manifest is malformed.

Related https://github.com/aws/copilot-cli/issues/2077
