### ISSUE TITLE
How to deploy a previous revision?

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2697]
So this is just a simple question. 

How can I deploy an older docker image I previously uploaded to ECR?

I can see that copilot shows the revision numbers while deploying, but I see no command for deploying a specific revision.

Thanks in advance!

**Comment by efekarakus** [comment]
Hi @gtamas !

There are two different options:
1. **[preferred]** Create a [git revert](https://git-scm.com/docs/git-revert) commit and then Copilot will build and deploy a new image to ECS.
2. **[What I think you're asking for]** You can checkout the old commit `git checkout <my-old commit sha>` and run `copilot deploy`. This shouldn't build a new image and instead use the old existing image in ECR. 
3. You can set the [`image.location` field](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-location) in the manifest to use a previous version explictly:
   ```yaml
   image:
     location: <ecr image uri>
   ```

**Comment by gtamas** [comment]
Thanks @efekarakus !

OK so git methods I understand.

Regarding the "ecr image url". Where can I find that? In my ECS task definition, under container definitions there is an "Image" field. That seems to be an image name: 

`183958493007.dkr.ecr.me-south-1.amazonaws.com/APPNAME/some-service@sha256:...`

So this contains an SHA hash. I can look up that hash in ECR console and I can copy the image URL from there. Is this correct?

**Comment by efekarakus** [comment]
>  Is this correct?

Yup that's correct!

**Comment by gtamas** [comment]
OK I'm good. Thanks!
