### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference occurred  at `svc deploy` executed

### ISSUE THREAD

**Issue by sogaoh** [aws/copilot-cli#2708]
## Reproduction Procedure
( premise : has done `copilot app init` , `copilot env init`, `copilot svc init` )

1. `git clone -b copilot-svc-deploy-panic https://github.com/sogaoh/laravel-app-runner-example.git`
1. `cd /path/to/laravel-app-runner-example`
1. Run `copilot svc deploy --name ${your_service_name} --env ${your_environment}`

## Phenomenon

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfa65d0]

goroutine 1 [running]:
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation/stack.(*appRunnerWkld).Parameters(0xc0002b8000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /codebuild/output/src729422157/src/internal/pkg/deploy/cloudformation/stack/workload.go:325 +0x250
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation.toStack(0x2034000, 0xc0005d0d80, 0x10, 0x18, 0x7f237c122108)
        /codebuild/output/src729422157/src/internal/pkg/deploy/cloudformation/cloudformation.go:390 +0xcb
github.com/aws/copilot-cli/internal/pkg/deploy/cloudformation.CloudFormation.DeployService(0x2045220, 0xc0004d0270, 0x2004da0, 0xc0004d0300, 0x2004d20, 0xc0004d4120, 0x2004e40, 0xc0004d4220, 0xc0004d0660, 0x203de40, ...)
        /codebuild/output/src729422157/src/internal/pkg/deploy/cloudformation/workload.go:18 +0x4d
github.com/aws/copilot-cli/internal/pkg/cli.(*deploySvcOpts).deploySvc(0xc0003c4d80, 0x0, 0x0, 0x0, 0x0)
        /codebuild/output/src729422157/src/internal/pkg/cli/svc_deploy.go:555 +0x1aa
github.com/aws/copilot-cli/internal/pkg/cli.(*deploySvcOpts).Execute(0xc0003c4d80, 0x0, 0x0)
        /codebuild/output/src729422157/src/internal/pkg/cli/svc_deploy.go:190 +0x3fa
github.com/aws/copilot-cli/internal/pkg/cli.buildSvcDeployCmd.func1(0xc000374500, 0xc0003a8440, 0x0, 0x4, 0xc00019fd48, 0x0)
        /codebuild/output/src729422157/src/internal/pkg/cli/svc_deploy.go:789 +0x114
github.com/aws/copilot-cli/internal/pkg/cli.runCmdE.func1(0xc000374500, 0xc0003a8440, 0x0, 0x4, 0x0, 0x0)
        /codebuild/output/src729422157/src/internal/pkg/cli/cli.go:66 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc000374500, 0xc0003a8400, 0x4, 0x4, 0xc000374500, 0xc0003a8400)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00032f180, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /codebuild/output/src729422157/src/cmd/copilot/main.go:25 +0x2b
```

## Environment/Version
- copilot 1.9.0 

- a. Amazon Linux 2
    ```
    ❯ cat /etc/os-release
    NAME="Amazon Linux"
    VERSION="2"
    ID="amzn"
    ID_LIKE="centos rhel fedora"
    VERSION_ID="2"
    PRETTY_NAME="Amazon Linux 2"
    ANSI_COLOR="0;33"
    CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
    HOME_URL="https://amazonlinux.com/"
    ```
    ```
    ❯ docker --version
    Docker version 20.10.4, build d3cb89e
    ```    

- b. Macbook Air
    ```
    ❯ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.15.7
    BuildVersion:	19H1323
    ```
    ```
    ❯ docker --version
    Docker version 20.10.7, build f0df350
    ```
    

## Other Information
[Japanese an article (by me)] https://zenn.dev/sogaoh/scraps/26b6cbde3ef707

**Comment by kohidave** [comment]
Oh no! We'll make sure to look at this as soon as possible 🙏  So sorry for the trouble, and thanks for reaching out.

**Comment by bvtujo** [comment]
Hi @sogaoh, is there any chance that you could post the manifest you're using? I have a hunch that the panic is due to a required parameter (port) not being present or having the wrong indentation in the manifest, but I would like to confirm.

**Comment by sogaoh** [comment]
Hi @bvtujo, That's https://github.com/sogaoh/laravel-app-runner-example/blob/copilot-svc-deploy-panic/copilot/lara-sample/manifest.yml . But http://www.yamllint.com/ says `Valid YAML!`.  
Please confirm. 

<details><summary>Screenshot</summary>

<img width="908" alt="yamlint_2021-08-06_ 0956" src="https://user-images.githubusercontent.com/2090887/128439828-95d26426-bfb1-42f8-8c7a-84dd095a13fb.png">


</details>

**Comment by Lou1415926** [comment]
Hi @sogaoh ! Yes we think it's because [`port`](https://aws.github.io/copilot-cli/docs/manifest/rd-web-service/#image-port) is missing from the manifest. We are working on fixing this so that it doesn't panic when `port` is missing. I am so sorry for the trouble 🙇🏼‍♀️  and thank you so much for reporting this issue!

**Comment by bvtujo** [comment]
The YAML is valid but Copilot needs `image.port` to be specified! That's why it might work on mainline but not on your `copilot-svc-deploy-panic` branch. 

Can you try this again by adding 

```yaml
image:
  build:
    dockerfile: appBase/ship/docker/php/Dockerfile
    context: appBase
    args:
      TZ: Asia/Tokyo
      PHP_MODE: production
  port: 80
```

to that manifest?

**Comment by sogaoh** [comment]
@bvtujo @Lou1415926 Thanks! I've added `port: 80` statement ( https://github.com/sogaoh/laravel-app-runner-example/commit/4e078220677b8df0320f5414f99bee60d1fb2b8f ) then `svc deploy` succeeded.

**Comment by efekarakus** [comment]
The fix is now released! https://github.com/aws/copilot-cli/releases/tag/v1.10.0 🥳
