### ISSUE TITLE
AppRunner : Please support StartCommand of CodeConfigurationValues

### ISSUE THREAD

**Issue by sogaoh** [aws/copilot-cli#2709]
I want to use `command` override like compose file setting.
(example : https://github.com/sogaoh/laravel-app-runner-example/blob/main/appBase/run/docker-compose.yml#L17 )

So, please support StartCommand of CodeConfigurationValues in manifest.yml. 

refs:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apprunner-service-codeconfigurationvalues.html
- https://docs.aws.amazon.com/apprunner/latest/api/API_CodeConfigurationValues.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_service#start_command

**Comment by toricls** [comment]
Adding one more link about `StartCommand` in the App Runner API docs - https://docs.aws.amazon.com/apprunner/latest/api/API_ImageConfiguration.html#apprunner-Type-ImageConfiguration-StartCommand

**Comment by Lou1415926** [comment]
Hi @sogaoh. This makes a lot of sense! Thanks for the request ❤️

**Comment by efekarakus** [comment]
This is now released in https://github.com/aws/copilot-cli/releases/tag/v1.11.0! 🎉 

Docs: https://aws.github.io/copilot-cli/docs/manifest/rd-web-service/#command
