### ISSUE TITLE
www & root: multiple aliases for load balanced web service

### ISSUE THREAD

**Issue by zakstucke** [aws/copilot-cli#2714]
My service is deployed at root, but I need the www alias to redirect / also serve the application. 

I've attempted to create an A alias record in route 53 to redirect www to root, but this doesn't seem to work.

The S3 bucket / static hosting redirect method for the www domain does not work as the application is deployed with HTTPS. 

Is there a solution I'm missing, or could multiple aliases be added as a feature?

**Comment by iamhopaul123** [comment]
Hello @zakstucke. We don't do the `www` by default and multiple aliases support has been merged (see #2638), which should be included in our next release!

**Comment by zakstucke** [comment]
Thanks! Love this project

**Comment by efekarakus** [comment]
The feature is now released! https://github.com/aws/copilot-cli/releases/tag/v1.10.0 🥳
