### ISSUE TITLE
Delete an app with Stackset and resources already gone?

### ISSUE THREAD

**Issue by Nikola-Milovic** [aws/copilot-cli#2718]
Hello everyone, I deleted my app and got an error because of hanging Stacksets, after deleting the stacksets manually (after resolving the issue). I forgot to delete the app, now when I try to delete the app I get 

```
copilot app delete kezual
Are you sure you want to delete application kezual? Yes
✘ get regional application resources for kezual: describing application resources: list stack instances for stack set kezual-infrastructure: StackSetNotFoundException: StackSet kezual-infrastructure not found
	status code: 404, request id: ad2c8128-617d-40b9-b0df-3ffdb6645e35
```

The app doesn't exist anymore but is there a way to delete the reference to it in the CLI?

edit: accidentally closed the issue

**Comment by efekarakus** [comment]
Hi @Nikola-Milovic ! 

Copilot stores metadata about the application in the AWS Systems Manager Parameter Store. If you delete the parameter `/copilot/applications/{app}` in your account then you should be good to go.
