### ISSUE TITLE
Expose Internet gateway ID as output for Copilot Env stack

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#2724]
We want to run integration tests in pipeline that need access to resources in VPC.
Our strategy is similar to what is mentioned here https://docs.aws.amazon.com/codebuild/latest/userguide/vpc-support.html
We are creating routing tables that will be used by code build.
However, we need to add a route in public routing table to internet gateway and we have no way to refer to the one copilot creates.

Can we expose internet gateway id as output for {$App}-{$Env} stack?

**Comment by huanjani** [comment]
Related: https://github.com/aws/copilot-cli/issues/2660
