### ISSUE TITLE
How to configure VPC for CodeBuild project?

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2747]
I have been having some issues with Docker pull rate limits causing my builds to fail. I'm not actually reaching those limits, but from what I understand it is a known issue with CodeBuild itself.

AWS Support suggested I try configuring a VPC for the CodeBuild project to get around this. Looking in the Copilot docs I don't see any mention of how I might do this. I checked the generated CodeBuild project I made with Copilot and the VPC config is empty so I have confirmed it wasn't created with my pipeline.

Any suggestions?

**Comment by huanjani** [comment]
Hi @mikelhamer! 
Here is a workaround for the Docker pull rate limit issue: https://github.com/aws/copilot-cli/issues/1869#issuecomment-765643674

**Comment by efekarakus** [comment]
I'll close the issue! Please let us us know @mikelhamer if you'd like to re-open it :)

**Comment by mikelhamer** [comment]
Oh yes thank you, I forgot to reply on this. Thanks @huanjani !
