### ISSUE TITLE
Feature request: No input mode for `copilot svc exec` (automatically install session manager)

### ISSUE THREAD

**Issue by jlucas91** [aws/copilot-cli#2760]
Hi! 

Have a quick feature request for your backlog. As part of my deploy pipeline I run `copilot svc exec -n ... -e ... "my command"` to run database migrations after the deploy. I found initially that the naive implementation didn't work because I was being prompted to install the session manager for the first time. Since this was in CI, there was no one to accept the install.

I worked around it by installing the session manager manually before running the command (included below in case it helps someone else), but it would be great to have a no input flag for svc exec that would install it automatically for me. 

```
curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "session-manager-plugin.rpm"
yum install -y session-manager-plugin.rpm
```

**Comment by huanjani** [comment]
Hello, @jlucas91! 

Thanks for this feature request and your workaround. We have actually already implemented what you're looking for: the `--yes` flag!

```
% copilot svc exec --help
Execute a command in a running container part of a service.

Usage
  copilot svc exec [flags]

Flags
  -a, --app string         Name of the application.
  -c, --command string     Optional. The command that is passed to a running container. (default "/bin/sh")
      --container string   Optional. The specific container you want to exec in. By default the first essential container will be used.
  -e, --env string         Name of the environment.
  -h, --help               help for exec
  -n, --name string        Name of the service, job, or task group.
      --task-id string     Optional. ID of the task you want to exec in.
      --yes                Optional. Whether to update the Session Manager Plugin.
```

We'll make sure to add it to the docs. 

As a side note, `task run` might be useful for db migrations if you'd prefer that over `svc exec`....

Thanks again!

**Comment by jlucas91** [comment]
Ah - that's great! I checked the github pages documentation, but not the CLI --help so missed that. Good to know for future reference that the CLI is the best source of truth for available flags.

I added it to the docs here in case that's helpful!  https://github.com/aws/copilot-cli/pull/2761 Feel free to close it if it's more of a pain to merge through me than to do it on your own. Trying to save you a small bit of time :)

**Comment by huanjani** [comment]
@jlucas91 Wow! Thanks so much for doing that! I just crossed it off of my to-do list! 😉

**Comment by jlucas91** [comment]
Glad it was helpful :) I'm a big fan of the project so want to help where I can.

@huanjani As an FYI - it looks like the --yes flag assumes `sudo` is available so I may need to keep using my workaround for now :(. I'm currently running the command as part of the `test_commands` in my pipeline.yml

```
[Container] 2021/08/23 23:54:09 Running command unbuffer ./copilot-linux svc exec --yes -n ... -e ... -c "..."
--
886 | ✘ install ssm plugin: exec: "sudo": executable file not found in $PATH
887 |  
888 | [Container] 2021/08/23 23:54:11 Command did not exit successfully unbuffer ./copilot-linux svc exec --yes -n ... -e ... -c "...." exit status 1
889 | [Container] 2021/08/23 23:54:11 Phase complete: BUILD State: FAILED
890 | [Container] 2021/08/23 23:54:11 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: unbuffer ./copilot-linux svc exec --yes -n ... -e ... -c "...". Reason: exit status 1
891 | [Container] 2021/08/23 23:54:11 Entering phase POST_BUILD
892 | [Container] 2021/08/23 23:54:11 Phase complete: POST_BUILD State: SUCCEEDED
```
