### ISSUE TITLE
Make `app init` and `app deploy` sub-commands runnable outside of root

### ISSUE THREAD

**Issue by sonofachamp** [aws/copilot-cli#277]
Currently the `app init` and `app deploy` workflows depend on being run from the "root" of a users' repository. `app init` writes `Dockerfile` directories to the application manifests which `app deploy` uses to build images.

Ideally I think these commands should be able to run independent of whether you're in the root of your repository or not as long as you're somewhere in the repository.

Potential solution could be to assume `Dockerfile` paths are relative to the root in both workflows by detecting a `workspace` and getting paths to files relative to the `workspace` directory.

**Comment by kohidave** [comment]
I like your proposal of forming the path based on workspace root path + dockerfile path.

**Comment by efekarakus** [comment]
This is supported now! I can run `copilot svc` commands in sub-directories without errors.
