### ISSUE TITLE
DDOS Protection with Cloudflare/AWS Shield

### ISSUE THREAD

**Issue by lauw70** [aws/copilot-cli#2791]
I'm looking at Copilot for managing our outward-facing API's and I got everything working with custom domains all, but I'm running into the following two security issues that are really related (I think), so I'm only creating one issue:

- How would I go about putting a DDOS protection service (e.g. Cloudflare or AWS Shield) in front of our API? It seems that CNAME routing would be the only way to go or am I missing something? https://support.cloudflare.com/hc/en-us/articles/360020348832-Understanding-a-CNAME-Setup
- Is it possible to disable HTTP traffic. Our servers only serve API calls, so we can just drop all HTTP traffic.

**Comment by bvtujo** [comment]
Hey @lauw70, I'm not sure of the answer to your first question--I'll have to ask around and get back to you. We don't have a simple experience for this, as Copilot does DNS delegation cross-account and it would be difficult to ensure a working CF template in all possible use cases. 

For the time being I'd recommend going this route; you could use a subdomain for copilot services, and point the cloudflare domain file at those subdomains as described there. 

For your second question, there's not a way currently to disable HTTP. We redirect HTTP to HTTPS with a listener at the load balancer level, but I am not sure how this will play with Cloudflare.
