### ISSUE TITLE
Show a warning if docker is not running

### ISSUE THREAD

**Issue by egdelwonk** [aws/copilot-cli#2825]
I noticed my builds hanging on "Environment stage is already on the latest version v1.6.1, skip upgrade." when deploying locally to test.

Turns out docker-desktop was not running locally after a reboot. It might be nice to throw a warning on `copilot deploy` that the docker daemon isn't available to build the image. Otherwise, the deployment will keep running indefinitely with no progress.

**Comment by iamhopaul123** [comment]
Hello @egdelwonk. Sorry for the churning. I just tested it out in macOS and it did return an error instantly as follows:
```
Service name: mysvc
Only found one environment, defaulting to: test
Environment test is already on the latest version v1.6.1, skip upgrade.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
✘ build and push image: build Dockerfile at /Users/penghaoh/Work/python/demo-app/Dockerfile: building image: exit status 1
```
I wonder if you are using Windows instead?

**Comment by egdelwonk** [comment]
@iamhopaul123 yes, it was on windows, sorry for not adding that detail earlier. I tried it on my mac and noticed the same output as you though. :)

**Comment by iamhopaul123** [comment]
@egdelwonk Gotcha. Seems like a discrepancy across different platforms which should be easy to fix! Thank you for reporting this issue.

**Comment by iamhopaul123** [comment]
Hey @egdelwonk. I tried to use my windows machine to run `copilot svc deploy` when docker desktop was not running. It seems like the CLI failed pretty quickly:
```
PS C:\Users\iamho\flask-app> copi svc deploy
Only found one service, defaulting to: mysvc
Only found one environment, defaulting to: test
Environment test is already on the latest version v1.6.1, skip upgrade.
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=zozw0wxgnnzoo6k2op42l7jhc&shmsize=0&t=389803402461.dkr.ecr.us-west-2.amazonaws.com%2Fdemo%2Fmysvc&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may 
also indicate that the docker daemon is not running.
X build and push image: build Dockerfile at C:\Users\iamho\flask-app\Dockerfile: building image: exit status 1
```
I wonder if it was because your windows desktop was in a transit state from `stopped` to `running` or the other way, causing Copilot kept waiting for the response.

**Comment by egdelwonk** [comment]
Not sure. I didn't have docker-desktop running at all, and it's using wsl2, so maybe that has something to do with it. 
Once I started docker-desktop and the wsl2 subsystem started up, the deployment worked fine. Might just be something specific on my end. Thanks so much for the help though!

**Comment by iamhopaul123** [comment]
Oh gotcha. I was not using wsl and maybe that's the reason why. I'll close the issue for now and feel free to open it again!
