### ISSUE TITLE
Test environment creation failed - VPC created in each AZ

### ISSUE THREAD

**Issue by serdar** [aws/copilot-cli#2841]
Hello, 

I've initialised my current project (mono repo with backend and frontend services) with Copilot (version: v1.10.1) using `copilot init` and created a 'Load Balanced Web Service'. The manifest was created, and selected the option to create a test environment.  The process failed with `VpcLimitExceeded`.

```
✔ Proposing infrastructure changes for the XXXXXX environment.
- Creating the infrastructure for the XXXXXX environment.         [rollback complete]  [33.4s]
  The following resource(s) failed to create: [InternetGateway, Cluster,
   VPC]. Rollback requested by user.
  - An IAM Role for AWS CloudFormation to manage resources                           [not started]
  - An ECS cluster to group your services                                            [delete complete]    [0.0s]
    Resource creation cancelled
  - Enable long ARN formats for the authenticated AWS principal                      [not started]
  - An IAM Role to describe resources in your environment                            [not started]
  - A security group to allow your containers to talk to each other                  [not started]
  - An Internet Gateway to connect to the public internet                            [delete complete]    [14.6s]
    Resource creation cancelled
  - Private subnet 1 for resources with no internet access                           [not started]
  - Private subnet 2 for resources with no internet access                           [not started]
  - Public subnet 1 for resources that can access the internet                       [not started]
  - Public subnet 2 for resources that can access the internet                       [not started]
  - A Virtual Private Cloud to control networking of your AWS resources              [delete complete]    [3.9s]
    The maximum number of VPCs has been reached. (Service: AmazonEC2; Stat
    us Code: 400; Error Code: VpcLimitExceeded; Request ID: XXXXXX; Proxy: null)
```

**Comment by efekarakus** [comment]
Hello @serdar ! 👋 

By default AWS accounts get 5 VPCs per region: https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html. A [copilot environment](https://aws.github.io/copilot-cli/docs/concepts/environments/) will also try to create a VPC, and it looks like for the particular region you're deploying to there were already 5 existing VPCs.

There are two possible recommended actions:
1. You can point your profile to a different region where there aren't existing VPCs.
2. You can request an increase for the number of VPCs in your particular region: https://console.aws.amazon.com/servicequotas/home/services/vpc/quotas/L-F678F1CE

Afterwards, hopefully running `copilot init` again should work!

**Comment by serdar** [comment]
Heyya @efekarakus ! Thank you for the clarification, I was actually following through your YT video! Seeing that's the case, it would be great to be able to specify a VPC when initialising

**Comment by efekarakus** [comment]
Heya! It's actually possible 😄 

Instead of running `copilot init` (the guided workflow), you can run the following commands individually:
1. `copilot app init`  -> to create a namespace for all your microservices
2. `copilot env init` -> here you can choose to import an existing VPC instead of creating a brand new one! ⭐️
3. `copilot svc init` -> to register and create the IaC file for your microservice
4. `copilot deploy` -> to deploy the service.

`copilot init` under the hood combines all four of these commands but it will have more narrow options (like it won't ask if you'd like to import a VPC).

Hope this helps!

**Comment by serdar** [comment]
Thanks Efe! Much appreciated, I've been able to progress but hit a new issue with deploying the service (No export named XXX-XXX-PublicSubnets found) - just masked out the app name - more of a usage issue so will hit up the Gitter community.
