### ISSUE TITLE
Fine-grained IAM policy to be attached on CI environment?

### ISSUE THREAD

**Issue by toshitanian** [aws/copilot-cli#2854]
I'm working on making CI/CD workflows (especially GitHub actions) to deploy app onto AWS using copilot. I've been try making an appropriate IAM policy but can found out the necessary and sufficient scope of IAM permissions.
I understand that there're two phase of copilot deployment, (1) setting up environment and deployment (2) keep deploying svc/jobs/etc..
It's fine that we use strong permission while setting up environment and required resources for deployment such as `copilot env init` and `copilot svc init`.
But in phase2, I want to restrict the permission of IAM policy because we put the secrets like `AWS_SECRET_ACCESS_KEY` on GitHub secrets.
Firstly I thought that the only permission required is updating a certain cloudFormation stack, but was not. And have not been able to set up an appropriate IAM policy so fur.

I thought that the IAM policy will be like below but it did not work.
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1631718216459",
            "Action": "cloudformation:*",
            "Effect": "Allow",
            "Resource": "arn:aws:cloudformation:::stack/my-svc*"
        },
        {
            "Sid": "Stmt1631718216460",
            "Action": "ssm:*",
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

So, it should be nice that IAM policies to be attached to CI is clarify and documented.

Best regards,

**Comment by efekarakus** [comment]
Hi @toshitanian ! 👋 

I wonder if the permissions in this comment would help you here? https://github.com/aws/copilot-cli/issues/2615#issuecomment-881034132, it's written for phase 2.

**Comment by toshitanian** [comment]
@efekarakus Thank you for the quick reply!
I will try the permissions on my side and close this issue then!

Do you have a plan to make a documentation of custom IAM policy for deployment at https://aws.github.io/copilot-cli ? 
copilot-cli is so wonderful tool for me and want to keep using for our container use case. On the other hand, permission management is also very importance for us in production use case.
So It's so nice that required IAM permissions are clarified and documented.

**Comment by efekarakus** [comment]
@toshitanian Thank you for your kind words ❤️ 
>  So It's so nice that required IAM permissions are clarified and documented.

Yes that makes a lot of sense, I created this card: https://github.com/aws/copilot-cli/projects/2#card-69166086 on our roadmap to capture your feedback! Thank you for the feedback 🙇

**Comment by toshitanian** [comment]
@efekarakus Good to hear that it was put on the roadmap! Looking forward to see it in the document.
Thank you

**Comment by zackdotcomputer** [comment]
I haven't seen that documentation on the site - did it wind up getting added? Best results I can find right now are the policies listed in [this issue](https://github.com/aws/copilot-cli/issues/2615)
