### ISSUE TITLE
Add copilot environment variables to sidecar environments

### ISSUE THREAD

**Issue by msmart** [aws/copilot-cli#2862]
There are a few copilot environment variables that are added automatically to the environment of the main task container, such as:

- COPILOT_APPLICATION_NAME
- COPILOT_ENVIRONMENT_NAME
- COPILOT_SERVICE_DISCOVERY_ENDPOINT
- COPILOT_SERVICE_NAME

For my use case it is helpful to have this information also exposed in the environment of the sidecar containers.

As a workaround, it is possible to add the env variables via the manifest to the sidecar, as described at https://github.com/aws/copilot-cli/issues/1119

**Comment by efekarakus** [comment]
Thanks @msmart for the feature request, it makes a lot of sense!

**Comment by efekarakus** [comment]
Hi all! The feature is now out: https://github.com/aws/copilot-cli/releases/tag/v1.12.0 🥳
