### ISSUE TITLE
Failed to delete environment xx from application xxx.

### ISSUE THREAD

**Issue by afgallo** [aws/copilot-cli#2882]
Hi there!

I couldn't find an existing issue with the error below so I thought I'd create a new one.

> ✘ Failed to delete environment xx from application xxx.
✘ execute env delete: delete environment xx stack: wait until stack xx-xxx delete is complete: ResourceNotReady: failed waiting for successful resource state

I get this error when I run the following commands in order:

1. `copilot app init xxx --domain xx.com --resource-tags application=xx`
2. `copilot env init --name xx --app xxx --profile xxxx --region ap-southeast-2 --default-config`
3. `copilot app delete -n xxx`

My current setup is as follows:
1. copilot version v1.10.1
2. App version v.1.0.2
3. I use different AWS profiles for creating environments

Error details from CloudFormation logs:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/9999415/135182187-ed67f13f-021b-464d-be4e-e75cccb78059.png">

I hope I provided enough details for you guys to diagnose the issue.

Cheers 🥂

**Comment by Lou1415926** [comment]
Hi @afgallo !

Looks like this is the same issue as #2870. Basically, when you have created an application via `copilot app init --domain xx.com`, then an environment, and that the environment deployment fails - this problem will occur. Sorry for the inconvenience! We'll fix it as soon as we can.

For now, you can delete the environment stack by following the below steps:
1. Go to your Route53 console
2. Go to your environment hosted zone, which is named `<EnvironmentName>.<AppName>.<DomainName>`. 
3. There should be three records there: a "NS" record, an "SOA" record and a "CNAME" record. Delete the CNAME record. This is the "non-required resource record set" that prevents the hosted zone from being deleted, hence the stack.

After removing this record, you can try to run `copilot app delete` again. 

<img width="1446" alt="Screen Shot 2021-09-29 at 9 09 18 AM" src="https://user-images.githubusercontent.com/79273084/135308573-689aed16-af59-4345-8b47-53ae9cd14bb8.png">

**Comment by afgallo** [comment]
Thanks @Lou1415926 ! The workaround worked!

**Comment by efekarakus** [comment]
Hi all! The fix is now out: https://github.com/aws/copilot-cli/releases/tag/v1.12.0 🥳
