### ISSUE TITLE
enable import of default VPC

### ISSUE THREAD

**Issue by huanjani** [aws/copilot-cli#2885]
When customers sign up for an AWS account, they get a [default VPC](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html#default-vpc-components) for quick start-up. 

Currently, Copilot requires two private subnets VPCs. Without two public subnets, load balancing won't work, but we allow users to proceed without public subnets.

To reduce barriers to entry and adoption, Copilot should not require two private subnets, so folks may use their default VPC and try a demo app or simple service that is public-facing. 

Ideas for increasing subnet flexibility:
- [ ] reverse the current UI by selecting all subnets by default 
- [ ] change the assignment of public/private for simplicity? how?
- [ ] error if user doesn't have at least two subnets
- [ ] warn if user doesn't have two private subnets (no backend services)
- [ ] warn if user doesn't have two public subnets (no load-balanced web services)
- [ ] still require at least two of either kind, for AZ placement best practices
- [ ] with `svc package`, error if env doesn't have what the service needs based on workload type/network placement

**Comment by mreferre** [comment]
> warn if user doesn't have two public subnets (no load-balanced web services)

~~But users could setup a LB web service on backend subnets can't they? It's not the default but if they set the flag to deploy LB web services in private subnets it shouldn't fail should it?~~

**Comment by huanjani** [comment]
I think it will fail, because "If your load balancer is an internet-facing load balancer, you must select public subnets in order for your back-end instances to receive traffic from the load balancer (even if the back-end instances are in private subnets)." https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-manage-subnets.html

**Comment by huanjani** [comment]
Copilot will proceed, but the Service won't build with the error: `Load Balancer failed to create: At least two subnets in two different Availability Zones must be specified`

**Comment by mreferre** [comment]
You are right. [ insert GIF of Bart Simpson disappearing into a hedge ]

**Comment by efekarakus** [comment]
This is all done!! The feature will go out next release https://github.com/aws/copilot-cli/pull/3285

**Comment by efekarakus** [comment]
Hi folks! The fix is now released https://github.com/aws/copilot-cli/releases/tag/v1.16.0 🥳 

See announcement: https://aws.github.io/copilot-cli/blogs/release-v116/

**Comment by gabrieljoelc** [comment]
The [documentation](https://aws.github.io/copilot-cli/docs/developing/custom-environment-resources/#importing-existing-resources) makes it sound like you can't import 2 public _or_ 2 private subnets but not both:
> You may use the import feature to bring a VPC with only two public subnets and no private subnets (such as a default VPC), or to bring a VPC with only two private subnets and no public subnets for your workloads that are not internet-facing. (For more details on the resources you'll need for isolated networks, go [here](https://github.com/aws/copilot-cli/discussions/2378).)

but the documentation [here](https://aws.github.io/copilot-cli/docs/manifest/environment/) makes it looks like you can import _both_:
```
name: imported
type: Environment
network:
  vpc:
    id: 'vpc-12345'
    subnets:
      public:
        - id: 'subnet-11111'
        - id: 'subnet-22222'
      private:
        - id: 'subnet-33333'
        - id: 'subnet-44444'
```

**Comment by huanjani** [comment]
@gabrieljoelc, thanks for pointing this out. I'll fix the wording in the documentation. We were trying to emphasize that non-standard options are available, but you're right-- it reads as though the default (2 public and 2 private subnets) is not an option.
