### ISSUE TITLE
Change a storage name

### ISSUE THREAD

**Issue by doneumark** [aws/copilot-cli#2886]
Hi, first of all - great job, what a fantastic tool!

I created a storage using "copilot storage init", and applied the name "api-db" to it.

Everything worked well, except that the name of it's "variables", at the YAML file and mainly at the environment variables are "apidb" (or "process.env.APIDB_SECRET"), in other words: the "api-db" lost the "-", and didn't camel-cased the name, making it rather "unreadable".

I figured the way to make the variables "readable" is changing the db name to something else (with no "-", like: "db"), or the library to automatically camelcase the name if "_" or "-" are in it.

How can one of those solutions be done?

**Comment by efekarakus** [comment]
Hi @doneumark 👋 

Thank you for your kind words! If I'm understanding correctly, there should be output of your template under `addons/` like this:
```yaml
Outputs:
  ApidbSecret:
    Value: !Ref ApidbAuroraSecret
```

I think if you update the output to follow this format instead:
```yaml
Outputs:
  ApiDbSecret:
    Value: !Ref ApidbAuroraSecret
```

This should change the env var to be `API_DB_SECRET` (unfortunately, we don't today generate the env vars with camel case: https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/#what-does-an-addon-template-look-like)

Let us know if this helps or I misunderstood the request :)

**Comment by doneumark** [comment]
Thank you Efe!
It does help internally to read the environment variables, but the name on the the AWS services (like "ApidbAuroraSecret" at the Secrets Manager) is still "unreadable" :(
