### ISSUE TITLE
Adding postgres extensions

### ISSUE THREAD

**Issue by doneumark** [aws/copilot-cli#2888]
Hi!

When setting up a postgres database through the "copilot storage init", some functionalities in the postgres database would not be able to work without the 'CREATE EXTENSION X' command , that need to be typed at the database init.

Because it's a process that suppose to happen at all environments, and over and over when reseting a database instance, I wonder if there a way to use copilot, in order to do just that.

Any ideas?

**Comment by huanjani** [comment]
Just an idea: could you use CommandRunner (https://aws.amazon.com/blogs/mt/running-bash-commands-in-aws-cloudformation-templates/) by adding it to your addons CloudFormation template (https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/)?

**Comment by doneumark** [comment]
I guess I can, It would still be cool if it could all happen on the copilot layer.

**Comment by huanjani** [comment]
Agreed! Thanks for the suggestion!
