### ISSUE TITLE
 unmarshal pipeline manifest: pipeline.yml contains invalid schema version: 0

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2910]
After a botched attempt at running `copilot init` (which failed due to some weird dependency issues) I am trying to run `copilot app delete` but getting this error

 unmarshal pipeline manifest: pipeline.yml contains invalid schema version: 0

It looks like a copilot directory wasn't even created in my project, but I do see the infrastructure and roles stacks on my AWS account.

I am on copilot 1.11.0

**Comment by efekarakus** [comment]
Hi @mikelhamer !

Is there a `pipeline.yml` file under the `copilot/` directory? Would you mind trying to re-run the command after manually deleting the file?
```bash
rm copilot/pipeline.yml
```
