### ISSUE TITLE
copilot tasks run

### ISSUE THREAD

**Issue by grassiricardo** [aws/copilot-cli#2915]
Hello

I'm executing ```taks run``` in specific enviroment and i'm with error 

```
Unable to retrieve Arn attribute for AWS::ECR::Repository, with error                                        
  message null
```
What problem is this?

**Comment by efekarakus** [comment]
Hi @grassiricardo! 

Apologies for the error 🙇 that's strange, the message is pretty cryptic! 🤔 

- Is the application and environment initialized?
  - Do you see outputs generated when running `copilot app show` and `copilot env show`?
- Is this the first time that you're running `task run`?
   - If not, is it possible that the ECR repository was previously deleted?

**Comment by grassiricardo** [comment]
Hi. I did find problem. 

My ECR of this tasks did exclued. I created the repository and of task running again
