### ISSUE TITLE
Need to able to pass a permissions boundary in at runtime

### ISSUE THREAD

**Issue by cougar2009** [aws/copilot-cli#2933]
We have role creation restrictions in place that require a permission boundary.  Sometimes we can get around this by adding the permission boundary to the role in the console but in this case it says "role already created"  and so it fails.  

Please reference CASE 9045582341  with AWS Enterprise Support for more details, but either we need to able to pass a permission boundary in as a command line argument or if it could not fail if the role is already existing that would work too.

**Comment by iamhopaul123** [comment]
Hello @cougar2009.

> Sometimes we can get around this by adding the permission boundary to the role in the console but in this case it says "role already created" and so it fails.

Could you put more details on the context of the case when it says "role already created"? Like what command did you run before?

> CASE 9045582341 with Enterprise Support

I don't quite get what this mean. Can you explain please? Thank you!

**Comment by huanjani** [comment]
This feature is now released in [v1.22](https://github.com/aws/copilot-cli/releases/tag/v1.22.0) 🚀 !

For the blog post: https://aws.github.io/copilot-cli/blogs/release-v122/
Release notes: https://github.com/aws/copilot-cli/releases/tag/v1.22.0
