### ISSUE TITLE
Support multi-account pipeline deployments

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2939]
I have three accounts

tooling
dev
prod

I would like my code commit repo and pipelines to live in the tooling account, and be able to deploy my apps to the dev and prod accounts from there. (see below link for example)
https://aws.amazon.com/blogs/devops/cross-account-ci-cd-pipeline-single-tenant-saas/

Is this currently possible?

**Comment by iamhopaul123** [comment]
Hello @mikelhamer. Not sure if this meets your requirement but Copilot allow and encourage users to define your app and pipeline in one account (in your case it could be the `tooling` account), and then have two different environments " in `dev` and `prod` accounts respectively. So the actual deployment would take place in each environment account. Please let me know you thought!

**Comment by mikelhamer** [comment]
@iamhopaul123 Oh, sweet! And could I do something like having continuous delivery for dev but require manual approval for prod?

**Comment by hkford** [comment]
@mikelhamer You can add a manual approval step by setting `requires_approval` to `true` in your `pipeline.yml`. (Documentation is [here](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-approval).)
In your case `pipeline.yml` would be:

```yaml
stages:
    -
      name: tooling
    -
      name: dev
    -
      name: prod
      requires_approval: true
```

**Comment by mikelhamer** [comment]
@hkford Thank you!

**Comment by iamhopaul123** [comment]
@hkford thank you for the great answer ❤️
