### ISSUE TITLE
SNS Topic Names Can't Have Underscores

### ISSUE THREAD

**Issue by tsmith-rv** [aws/copilot-cli#2948]
I was trying to run `copilot deploy` to deploy a Scheduled Job I had that had an SNS Topic in the publish section of the manifest file.

```yml
publish: # https://aws.github.io/copilot-cli/docs/developing/publish-subscribe/
  topics:
    - name: ready_for_processing
```

The [documentation](https://aws.github.io/copilot-cli/docs/manifest/scheduled-job/) specifies that the name of the SNS Topic "Must contain only upper and lowercase letters, numbers, hyphens, and __underscores__."

However, when using underscores in the name I was receiving an error when trying to deploy:

```
execute job deploy: deploy job: check if changeset is empty: create change set ...: ValidationError: Template format error: Unresolved resource dependencies [ready_for_processingSNSTopic] in the Resources block of the template
	status code: 400, request id: 26ba988c-7d24-42d6-a191-a65e596e8a38: describe change set ...for stack pf-athena-nonprod-ingest: ChangeSetNotFound: ChangeSet [...] does not exist
	status code: 404, request id: ...
```

I ran `copilot job package` to get a better look at where the problem might be and saw that the line `- !Ref ready_for_processingSNSTopic` was the issue since that dependency was nowhere to be found in the file, however I did find `readyforprocessingSNSTopic`. Looks like the underscores are being removed for the resource element, but not for the reference.

Changing my SNS Topic name to `readyForProcessing` fixed things and allowed me to deploy successfully, however there definitely seems to be a bug here.

I'm on the latest release (`v1.11.0`).

**Comment by huanjani** [comment]
Hi, @tsmith-rv! 

Thanks so much for creating this issue; we have a bug fix ready for the next release tentatively scheduled for later this week: https://github.com/aws/copilot-cli/pull/2903

**Comment by efekarakus** [comment]
The fix is now out: https://github.com/aws/copilot-cli/releases/tag/v1.12.0 🥳
