### ISSUE TITLE
COPILOT_SNS_TOPIC_ARNS in Cloudformation Template Uses Incorrect AccountID

### ISSUE THREAD

**Issue by tsmith-rv** [aws/copilot-cli#2949]
When creating an application that has a `publish` section in the manifest file, an SNS Topic will be created when you deploy your application and [according to the documentation](https://aws.github.io/copilot-cli/docs/developing/publish-subscribe/) the ARN of the newly created SNS Topic(s) will be injected into your task environment in the `COPILOT_SNS_TOPIC_ARNS` variable.

So, in my application, I am using two separate accounts. I ran my initial `copilot init` for my app using what I'll call the *prod* account, but have a separate environment in another account that we'll call *nonprod*.

Right now, when deploying my application to my *nonprod* environment/account, while building the ARN for the SNS Topic it is hardcoding the Account ID from the *prod* account. In my cloudformation template you see (using fake account IDs):

```yml
- Name: COPILOT_SNS_TOPIC_ARNS
  Value: '{"readyForProcessing":"arn:aws:sns:us-east-1:111111111prod:pf-athena-nonprod-ingest-readyForProcessing"}'
```

However, I would expect to see:

```yml
- Name: COPILOT_SNS_TOPIC_ARNS
  Value: '{"readyForProcessing":"arn:aws:sns:us-east-1:22222222nonprod:pf-athena-nonprod-ingest-readyForProcessing"}'
```

Or maybe even (I think this is the better way to do it):

```yml
- Name: COPILOT_SNS_TOPIC_ARNS
  Value: !Sub '{"readyForProcessing":"arn:aws:sns:us-east-1:${AWS::AccountId}:pf-athena-nonprod-ingest-readyForProcessing"}'
```

I'm using the latest release (`v1.11.0`)

**Comment by tsmith-rv** [comment]
If my suggestion for using the `${AWS::AccountId}` parameter in place of a hardcoded account ID sounds like the right way to go, I'd be happy to open a PR for that! Unless I'm just missing something here!

**Comment by efekarakus** [comment]
Hi @tsmith-rv ! This definitely sounds like a bug, thank you for reaching out. We'll investigate and get back to you

**Comment by efekarakus** [comment]
I believe this is happening because of:
https://github.com/aws/copilot-cli/blob/d0111329946b71838cf4b0bddc4d730ae1dc9702/internal/pkg/cli/svc_deploy.go#L489-L490

Instead of `targetApp.AccountID` we should be doing `targetEnvironment.AccountID`

**Comment by huanjani** [comment]
Thanks, @tsmith-rv! I was able to replicate this issue. Thanks so much for bringing it to our attention!

**Comment by efekarakus** [comment]
The fix is merged and should be out next release!

**Comment by efekarakus** [comment]
Hi all! The fix is now out: https://github.com/aws/copilot-cli/releases/tag/v1.12.0 🥳
