### ISSUE TITLE
"that accepts {x} parameters" sometimes creates keyword variables in Lua (and possibly other languages) when wrapping around alphabet names.

### ISSUE THREAD

**Issue by iamlanjt** [aws/copilot-cli#2950]
Example of issue in Lua:
```lua
-- A function that accepts 50 parameters.
function func(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, bq, br, bs, bt, bu, bv, bw, bx, by, bz, ca, cb, cc, cd, ce, cf, cg, ch, ci, cj, ck, cl, cm, cn, co, cp, cq, cr, cs, ct, cu, cv, cw, cx, cy, cz, da, db, dc, dd, de, df, dg, dh, di, dj, dk, dl, dm, dn, do, dp, dq, dr, ds, dt, du, dv, dw, dx
```
In the ``dd`` section, somewhere near the end, the keyword ``do`` is written which will cause errors when trying to run the file. Obviously, for practical use, probably no one wants a function with 50 parameters, but I don't know where else this issue can manifest.

**Comment by efekarakus** [comment]
Hi @notthatkuna !

This repository is for AWS Copilot https://aws.github.io/copilot-cli/ which is different than GitHub Copilot :) 

I am unfortunately not sure how to leave feedback for GitHub Copilot.
