### ISSUE TITLE
copilot env init failures in production account

### ISSUE THREAD

**Issue by tsingh2k15** [aws/copilot-cli#2952]
Observing an issue while provisioning copilot resources in production account, the issue did not occur in lower environments. Error messages are not very descriptive to pinpoint the issue. It just tells that failure occurred, but does not provide much clue on why the failure occurred, what is the error code, which api call is failing?

I have deleted the stack and then I retried but the same issue still persists. Sharing the console output below - highlighted the error message. Any guidance/support here would be beneficial. I am checking if the prod account has different guardrails, but I was expecting the error below to be little more helpful. 

Main error -

**The following resource(s) failed to create: [Cluster, CloudformationExecutionRole, ServiceDiscoveryNamespace, EnvironmentSecurityGroup]**

Console logs - 

```
copilot env init -n prod --import-vpc-id some-vpc --import-private-subnets sub1 sub2 --profile my_named_profile

Note: No existing subnets were found in VPC some-vpc

If you proceed without at least two public subnets, you will not be able to deploy Load Balanced Web Services in this environment.

⠋ Linking account prodacct and region us-east-2 to application some-app. 
✔ Linked account prodacct and region us-east-2 to application some-app.

⠋ Proposing infrastructure changes for the some-prod environment. 
✔ Proposing infrastructure changes for the some-prod environment.

Creating the infrastructure for the some-prod environment. [rollback complete] [18.6s]

The following resource(s) failed to create: [Cluster, CloudformationExecutionRole, ServiceDiscoveryNamespace, EnvironmentSecurityGroup]

Rollback requested by user. 

 An IAM Role for AWS CloudFormation to manage resources [delete skipped] [0.0s]

Resource creation cancelled                                                 

An ECS cluster to group your services [delete complete] [2.6s]

Resource creation cancelled                                                       

Enable long ARN formats for the authenticated AWS principal [not started]  

An IAM Role to describe resources in your environment [not started]    

A security group to allow your containers to talk to each other [delete complete] [0.0s]

Resource creation cancelled                                               

✘ stack some-stack-prod did not complete successfully and exited with status ROLLBACK_COMPLETE

```

**Comment by huanjani** [comment]
Hi, @tsingh2k15.

I'm sorry about the less-than-helpful error messaging.
Can you go into your CloudFormation console, click on the stack, then go to the Events tab? Is there more specific error messaging there? Let me know, and we can continue to troubleshoot! 

Thanks!

**Comment by tsingh2k15** [comment]
> Hi, @tsingh2k15.
> 
> I'm sorry about the less-than-helpful error messaging. Can you go into your CloudFormation console, click on the stack, then go to the Events tab? Is there more specific error messaging there? Let me know, and we can continue to troubleshoot!
> 
> Thanks!

That helped, there was a permission issue. I will add the permissions and retest. Thanks @huanjani

**Comment by tsingh2k15** [comment]
> > Hi, @tsingh2k15.
> > I'm sorry about the less-than-helpful error messaging. Can you go into your CloudFormation console, click on the stack, then go to the Events tab? Is there more specific error messaging there? Let me know, and we can continue to troubleshoot!
> > Thanks!
> 
> That helped, there was a permission issue. I will add the permissions and retest. Thanks @huanjani

@huanjani This resolved the issue. Please feel free to close this or any applicable next step. Error message could have been more helpful though.

I have one separate question, in my env for prod account, it shows below boolean which is set to default of `false` for my case. Do I have to set it to `true` in production? What is the significance? I was reading about it a little bit and it appears that this boolean will be used in future? Any details here would be useful as I am using copilot in prod.

`Production        false`

**Comment by huanjani** [comment]
🎉  Glad it's working now! 

You're correct: as of right now, that boolean does not have any impact. You may have come across this in your reading: https://github.com/aws/copilot-cli/discussions/2158#discussioncomment-586933; as of right now we don't have concrete plans as to exactly what or when. 😄

**Comment by tsingh2k15** [comment]
> 🎉 Glad it's working now!
> 
> You're correct: as of right now, that boolean does not have any impact. You may have come across this in your reading: [#2158 (reply in thread)](https://github.com/aws/copilot-cli/discussions/2158#discussioncomment-586933); as of right now we don't have concrete plans as to exactly what or when. 😄

Thank you for the clarification! The reason I asked was, if in future the boolean goes live; then I can still leverage it on existing stack ? or the boolean will only be effective for new stacks?  I would hesitate to recreate the stack in order to leverage boolean :)

**Comment by huanjani** [comment]
@tsingh2k15-- I understand your concern! If we do add it, it should be backwards compatible. 😄
