### ISSUE TITLE
I want to control a copilot app created by someone else.

### ISSUE THREAD

**Issue by haze-it** [aws/copilot-cli#2963]
Hello.

I am setting up an application using Copilot with several people.
How can I make sure that the copilot app created by others can be seen in my CLI?

When I run `copilot app ls`, I can't see the app that others have created.
When I run `copilot app show` I get `get application APP_NAME: couldn't find an application named APP_NAME in account 999999999999 and region ap-northeast-1`. The following message is displayed.

Thanks.

**Comment by haze-it** [comment]
I'm sorry!
I had set up my account incorrectly.

**Comment by efekarakus** [comment]
@haze-it Glad you got it working ! 🥳
