### ISSUE TITLE
Deploy Fails: Upgraded to 1.12.0, http.alias deploy now rejected saying domain not associated

### ISSUE THREAD

**Issue by zackdotcomputer** [aws/copilot-cli#2967]
- I just upgraded to copilot cli 1.12.0.

- I made minor swaps in the manifest to use the new variable replacement feature.

- Tried to do a new deploy of my api container, which uses `http.alias` to deploy to `api.mydomain.com`.

- Deploy builds the container, uploads it, and then fails with:
```
✘ To use `http.alias`, your application must be associated with a domain: `copilot app init --domain example.com`.
✘ alias specified when application is not associated with a domain
```

- I did not change the `http.alias` for my manifest and I have been successfully deploying to my domain for a couple months now.

- I tried running `copilot app init --domain mydomain.com` as suggested, the command completes successfully, however the deploy still fails.

This is preventing my ability to do any deploy with copilot.

**Comment by zackdotcomputer** [comment]
This is [this PR](https://github.com/aws/copilot-cli/commit/ef26b808037a8c307cb14680537bf35eebeff67f) working as intended, surfacing what was previously a silent failure I wasn't aware of. My bad.

**Comment by efekarakus** [comment]
😅 phew, thanks for diving deep in the PRs and figuring it out!
