### ISSUE TITLE
Add support for Docker images from other repositories

### ISSUE THREAD

**Issue by sonofachamp** [aws/copilot-cli#30]
Update the `loadbalanced-fargate-service.yml` CloudFormation template to support images from other repositories (e.g. private ECR repository).

**Comment by kohidave** [comment]
We can extend this to support DockerHub, Private Registry and raw images as well.

**Comment by efekarakus** [comment]
Resolving this issue in favor of https://github.com/aws/copilot-cli/issues/1177
