### ISSUE TITLE
`copilot deploy ...` times out with App Runner

### ISSUE THREAD

**Issue by chriskuech** [aws/copilot-cli#3005]
I am just onboarding to `copilot` and have been doing the guided steps on the [getting started](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/getting-started-aws-copilot-cli.html) page but having issues.  I chose App Runner type but it always times out at the last step and rolls back.

How can I find out why and mitigate?

![image](https://user-images.githubusercontent.com/3680671/140830274-66a3dc5c-1ef3-44de-bb9d-1b22c46713e4.png)

**Comment by Lou1415926** [comment]
Hello @chriskuech !

Sometimes an App Runner service fails to create for various reasons - for example, when the health check fails, or when the container exited unexpectedly. However, these information isn't effectively passed on to CloudFormation (hence the `returned message: "null"` that you've been seeing). 

You can see the log in CloudWatch. You can go to "https://<your-region>.console.aws.amazon.com/cloudwatch/home?region=<your-region>.#logsV2:log-groups", look for log groups named `/aws/apprunner/<appname>-<envname>-<service name>/<random string>/application` and `/aws/apprunner/<appname>-<envname>-<service name>/<random string>/service`. Hopefully you can find the cause of error there! [Here](https://docs.aws.amazon.com/apprunner/latest/dg/monitor-cwl.html) is more information on the difference between service log and application log.
