### ISSUE TITLE
Support for git-remote-codecommit on pipeline command

### ISSUE THREAD

**Issue by davivcgarcia** [aws/copilot-cli#3012]
The AWS CodeCommit now provides an Git credential helper called `git-remote-codecommit` ([blog announcement](https://aws.amazon.com/about-aws/whats-new/2020/03/aws-codecommit-introduces-open-source-remote-helper/)) that simplifies interaction with repositories and IAM.

Looks like `copilot-cli` is not yet compatible with this helper. When I tried to create an Pipeline using the CLI version `1.12.0` i got the following error:

```bash
$ git remote -v
origin	codecommit://helloecs (fetch)
origin	codecommit://helloecs (push)

$ copilot pipeline init
1st stage: test
2nd stage: production
Repository URL: codecommit://helloecs
✘ unknown CodeCommit URL format: codecommit://helloecs
```

**Comment by iamhopaul123** [comment]
Hey @davivcgarcia a quick question: it seems like the codecommit URL format accepted by copilot is like `codecommit::us-west-2://repo-man`, whereas your URL is `codecommit://helloecs`. I wonder if we should just use the region from your default profile? For a quick workaround could you specify the region as the above example to see if it works? Thank you!

**Comment by davivcgarcia** [comment]
> Hey @davivcgarcia a quick question: it seems like the codecommit URL format accepted by copilot is like `codecommit::us-west-2://repo-man`, whereas your URL is `codecommit://helloecs`. I wonder if we should just use the region from your default profile? For a quick workaround could you specify the region as the above example to see if it works? Thank you!

It indeed worked!

```
1st stage: test
2nd stage: production
Repository URL: codecommit::us-east-2://helloecs
✔ Wrote the pipeline manifest for helloecs at 'copilot/pipeline.yml'
The manifest contains configurations for your CodePipeline resources, such as your pipeline stages and build steps.
Update the file to add additional stages, change the branch to be tracked, or add test commands or manual approval actions.
✔ Wrote the buildspec for the pipeline's build stage at 'copilot/buildspec.yml'
The buildspec contains the commands to build and push your container images to your ECR repositories.
Update the build phase to unit test your services before pushing the images.

Required follow-up actions:
- Commit and push the buildspec.yml, pipeline.yml, and .workspace files of your copilot directory to your repository.
- Run `copilot pipeline update` to create your pipeline.
```

So, do you think we could add support for the minified Git remote URL, or the best practice is to use the verbose one?

**Comment by iamhopaul123** [comment]
I think we should add support for the short one. I'll put an enhancement tag. Thank you for surfacing this issue!
