### ISSUE TITLE
Support manifests for env and app

### ISSUE THREAD

**Issue by chriskuech** [aws/copilot-cli#3030]
Copilot team appears aware of the importance of declarative DevOps modeling as Copilot already supports such systems for services and pipelines.  It would be good to extend this support to applications and environments for the same benefits.

With environment/app manifests, copilot could better support shared/non-regional resources, like DNS and storage services.  It is unclear whether resources created with `copilot storage` can be used in multiregional context without additional work, such as modifying IAM grants.

Environment/app manifests could also contain AWS account IDs/profiles to automate this somewhat confusing area of multi-environment management

Lastly, I find it confusing that repos are associated with a service, but apps and environments span multiple services and therefore multiple repos.  This also leads to the confusing/undocumented workspace system.  Adding workspace-wide files, such as environment and application manifests, would better formalize how workspaces function and are structured.

**Comment by efekarakus** [comment]
Hi @chriskuech, we have started the design work to support "Environment" manifests. 
Once we have the proposal ready, we'll update the issue here!

**Comment by chriskuech** [comment]
Sorry I had to build a custom solution for govcloud and no longer use copilot

**Comment by efekarakus** [comment]
No worries, thank you for the feedback! The issue makes a lot of sense and we're always working on expanding the scope of copilot, so this helps.

**Comment by efekarakus** [comment]
This feature is now out in v1.20 🚀 
Release notes: https://github.com/aws/copilot-cli/releases/tag/v1.20.0 !
Blog post: https://aws.github.io/copilot-cli/blogs/release-v120/
