### ISSUE TITLE
Nested addon stack becomes stuck in failed state after resource creation fails preventing further deploys

### ISSUE THREAD

**Issue by sloan-dog** [aws/copilot-cli#3033]
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  ServiceCoreAccessPolicyy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3ObjectActions
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectACL
              - s3:PutObjectTagging
              - s3:DeleteObject
              - s3:RestoreObject
            Resource: some-badly-formed-arn
          - Sid: S3ListAction
            Effect: Allow
            Action: s3:ListBucket
            Resource: some-badly-formed-arn
Outputs:
  ServiceCoreAccessPolicyARN:
    Value: !Ref ServiceCoreAccessPolicyy
    
   After adding this to copilot/service-core/addons/s3-permissions.yml
   
   I ran `copilot deploy`
   
   And the deploy failed while trying to create the substack for the iam permission. 
   
   Subsequent deploys (after fixing arn) provide this indefinitely.

execute svc deploy: deploy service: change set with name copilot-0ce93004-262a-45a1-bc28-a5514f8adc2b for stack soil-doctor-app-test-service-core has no changes: Embedded stack arn:aws:cloudformation:us-west-2:380419645029:stack/soil-doctor-app-test-service-core-AddonsStack-ROVG9OI87APB/7af86900-1aac-11ec-a926-0a5e1eae02b3 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [MyAccessPolicy].

How do i get out of this state?

**Comment by efekarakus** [comment]
Hi @sloan-dog !

What happens if you try to remove the addon completely? 
```
rm copilot/service-core/addons/s3-permissions.yml
```
and run `copilot deploy` again?

I tried re-creating the issue but although the first time the deployment failed, after it reached `ROLLBACK_COMPLETE` subsequent deployments succeeded once I fixed the template.

**Comment by sloan-dog** [comment]
Yea, that does the trick.

**Comment by efekarakus** [comment]
Awesome resolving the issue, glad you got it working!
