### ISSUE TITLE
Backtick disabled on Vs Code on italian layout when copilot is installed.

### ISSUE THREAD

**Issue by superandrew** [aws/copilot-cli#3034]
Provided that I installed copilot even if I don't still have access to it (please, let me in 😂), by doing some investigation around [this issue](https://github.com/microsoft/vscode/issues/136580), I noticed that copilot enabled a keybinding (alt+\) which on italian layout on Mac is used to trigger the key ` (backtick). 

So installing copilot extension basically breaks the backtick on vs code alone. Not sure what to suggest but I'm pretty sure italian mac devs would be disappointed to switch to alt+9 for the backtick in vs code alone.

**Comment by superandrew** [comment]
sorry, wrong repo

**Comment by logovitta** [comment]
still would like if you posted this issue anywhere else, 'cause i got the same problem....
