### ISSUE TITLE
Deleting an application fails with an auth error

### ISSUE THREAD

**Issue by terah** [aws/copilot-cli#3043]
```
$ copilot app delete
Sure? Yes
✔ Cleaned up deployment resources.. 
✔ Deleted pipeline pipeline-clamav-webservice-app-clamav-webservice from application av-ws-app.. 
✘ Error deleting application resources.
✘ delete app resources: operation 05960CAC-9323-4013-8E7D-29208D3847AF for stack set av-ws-app-infrastructure failed

```

In the Stack Set Details page for the Stack Set:

```

36xxxxxxxx | ap-southeast-2 | arn:aws:cloudformation:ap-southeast-2:36xxxxxxxx:stack/StackSet-av-ws-app-infrastructure-2feb55a5-19fa-4d63-ae92-7679e7cf9069/b7e35810-421c-11ec-a25e-xxxxx | INOPERABLE | Account 36xxxxxxxx should have 'av-ws-app-adminrole' role with trust relationship to CloudFormation service.

```

**Comment by efekarakus** [comment]
Hi @terah !

Apologies for the inconvenience 🙇 Do you remember if any of the cloudformation stacks were deleted manually? 

In the mean time, to mitigate the issue I think we can re-create the role `av-ws-app-adminrole` and see if the stackset can be deleted.
The following permission is needed: (replace `demo-adminrole` with `av-ws-app-infrastructure`)
![Screen Shot 2021-11-17 at 10 30 08 AM](https://user-images.githubusercontent.com/879348/142260876-48c2de5f-ab6c-41ce-9d4e-8c3f35919140.png)
and the following trust relationship:
![Screen Shot 2021-11-17 at 10 30 16 AM](https://user-images.githubusercontent.com/879348/142261051-75c37af7-52e1-41cd-9c7f-d364e9a9d84b.png)

**Comment by terah** [comment]
My apologies. It's entirely likely I tried deleting the stack in the web UI the other day.  Please close this issue.

**Comment by efekarakus** [comment]
No worries! thanks for getting back to us :)
