### ISSUE TITLE
task run can't set docker context

### ISSUE THREAD

**Issue by nbarrera** [aws/copilot-cli#3044]
I find no way to define which is the docker context directory when using `copiilot task run`

I could use the `--dockerfile` argument and the docker context will be the `Dockerfile`'s directory which it is useful most of the times, but currently I was making use of the manifest's `build / context:` yaml property to use a different context.

That manifest is for a scheduled task, and I would like to also specify the build context when I 'm running that task manually as a one-off task.

The use case is, the scheduled task failed so I debug and fix it so I want to run it manually and not wait until next trigger time... this is not possible if your scheduled task is making use of the `build / context:` manifest property.

**Comment by efekarakus** [comment]
Hi @nbarrera ! Thank you, the feature request makes a lot of sense. Looks like today we just assume that the context is the path of the dockerfile:
https://github.com/aws/copilot-cli/blob/4597bdc00df0898dd22472422b7fd61ba0faecba/internal/pkg/cli/task_run.go#L754-L756

In order to be backwards compatible, we can introduce a new flag `--build-context` to override the value.

In the mean time, would it be possible to copy the Dockerfile into the context path that might help you get unblocked

**Comment by nbarrera** [comment]
Hi @efekarakus... yes my other option is to put Dockerfiles on the directory I was trying to set as the context. That's not so sexy as I have a monorepo structure, then I would end up with a directory for each module, but Dockerfiles for each module will be on the root, kind of awkward... still doable.

In the mean time I was checking the code that you now mention.

I came up with a fork and a [PR](https://github.com/nbarrera/copilot-cli/pull/1)... didn't went for the PR against your repo because I didn't follow all steps on the contribution guideline... I reached only up to `make tests`.

But anyway you guys may want to check it if you think it's useful.

thank you!

**Comment by efekarakus** [comment]
Thank you! this is awesome 🎉 I can definitely pick it up from your PR and add the additional commits.

I should be able to work on it by end of day!

**Comment by efekarakus** [comment]
If you want to, you can create the PR against this repo `aws/copilot` instead of your fork so you get the contribution :D

**Comment by nbarrera** [comment]
will do, 👍 
thank you

for the record.. I kind of followed the uses of `--dockerfile` and mimic that for the new `--build-context` hope that gets you close enough.

**Comment by efekarakus** [comment]
Thank you for the PR @nbarrera ! It's now merged 😄 it should go out next release

We have also updated the help menu of `task run` in the PR to make it easier to find flags:
![after](https://user-images.githubusercontent.com/879348/142320860-2c96b72c-4cbc-4038-9791-ac5377fc7864.png)

**Comment by efekarakus** [comment]
This is now released 🎉 in v1.13.0 https://github.com/aws/copilot-cli/releases/tag/v1.13.0 !
