### ISSUE TITLE
Document required permissions for copilot CLI operations

### ISSUE THREAD

**Issue by chriskuech** [aws/copilot-cli#3049]
I would like to automate copilot. Unfortunately I cannot leverage pipelines as they are not supported in pipelines.  As such, it would be helpful to document what permissions are required for the main copilot operations, especially `copilot svc deploy`

**Comment by efekarakus** [comment]
Hi @chriskuech ! Apologies this is not well documented today 🙇

Does this comment help? https://github.com/aws/copilot-cli/issues/2615#issuecomment-881034132

**Comment by chriskuech** [comment]
@efekarakus , thanks very helpful.  I see copilot creates "an IAM Role for the Fargate agent to make AWS API calls on your behalf".  I wonder if best strategy would be to have an automation IAM user assume that role?

**Comment by efekarakus** [comment]
> Unfortunately I cannot leverage pipelines as they are not supported in pipelines.

Would you mind elaborating about what's not supported in pipelines? why can't `copilot pipeline init` work for you?

>  I wonder if best strategy would be to have an automation IAM user assume that role?

I might be misunderstanding, but I don't think so! That role is the [Amazon ECS task execution role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html) which can only be assumed by the Fargate agent and is typically used to pull a container image and forward logs.

I think the best thing would be to create an IAM role with the permissions in that issue, then assume that role and run `copilot svc deploy`

**Comment by chriskuech** [comment]
I made #3029 for pipeline support in GovCloud.  The service in question is CodeStar.
