### ISSUE TITLE
Where is local config stored?

### ISSUE THREAD

**Issue by sve-odoo** [aws/copilot-cli#3052]
Hello,

I would like to completely reset my copilot local environment. (apps, envs)
When I type `copilot app ls` I get my app name, and I would like to have nothing instead, to start from scratch.
I get an error when I try to delete it.

Where is this information stored in my filesystem?

Thanks

**Comment by efekarakus** [comment]
Hi  @sve-odoo ! 

There should be a `.workspace` file present under the `copilot/` directory: `copilot/.workspace` which stores the application name locally:
```yaml
application: <your app name>
```
If you delete the file, you should be able to start from scratch!

**Comment by sve-odoo** [comment]
Oddly enough, I believe when I `copilot env ls` even with the copilot directory deleted, my environments are listed. So it makes me think they are stored elsewhere?

**Comment by efekarakus** [comment]
ah yes sorry! Metadata about your application, environments, and services is stored in [SSM Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html) in your application account and region.

Here is a sample screenshot:
![ssm](https://user-images.githubusercontent.com/879348/142666729-5f1591bd-4bce-4308-98c8-c5fa803a63c0.png)

If you delete the `/copilot/*` parameters then the CLI should be in a clean state

**Comment by efekarakus** [comment]
Closing the issue, please let me know if you are running into a problem with deletions and we can re-open it!
