### ISSUE TITLE
Failure event due to premature throttling

### ISSUE THREAD

**Issue by chriskuech** [aws/copilot-cli#3064]
I am getting the error below trying to deploy my service.  I should only have 3 tasks: the previous version of the service, the new version of the service, and another service.

    ✘ Latest failure event                                                                   
      - (service api-sandbox-gateway-Service-Bir1Z3K0mQoZ) was unable to place                                
         a task. Reason: You've reached the limit on the number of tasks you c                                
        an run concurrently. For more information, see the Troubleshooting sec                                
        tion of the Amazon ECS Developer Guide. 

However, when I look at https://us-west-2.console.aws.amazon.com/servicequotas/home/services/ecs/quotas, I see I'm well below any ECS limits.

![image](https://user-images.githubusercontent.com/3680671/142741929-10d1ecc5-d564-4982-ab67-6d07797a339b.png)

**Comment by chriskuech** [comment]
This appears to be breaking rollback as well

**Comment by efekarakus** [comment]
Hi! Is this a brand new AWS account? I believe by default to prevent fraud Fargate tasks will be blocked from launching. If you create a small ec2 instance manually, delete it, and then try again in a few hours it should work.

If it's not a new AWS account that's very strange. In that situation, we could try launching the tasks in private subnets

https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-placement

**Comment by chriskuech** [comment]
It's not a new account and I've been deploying to it with copilot for a few days.  This seems to be the implied quota but it never gets close.

![image](https://user-images.githubusercontent.com/3680671/142744281-e0133f19-ad5d-4e2c-9bd6-c9818124bf4a.png)

**Comment by chriskuech** [comment]
Would deploying a new backend service provide the same validation as frontend service with backend subnet?

**Comment by efekarakus** [comment]
> This seems to be the implied quota but it never gets close.

I see that only 2 tasks were created in the screenshot which seems to align with: https://forums.aws.amazon.com/thread.jspa?threadID=340770
Would you mind creating an ec2 instance and then trying again? Perhaps the fraud detection is not just for new accounts but also when launching to a new region 🤔 

> provide the same validation as frontend service with backend subnet?

Could you elaborate what do you mean by validation and backend subnet?
If the question is if it's possible to deploy a "Backend Service" to private subnets, then yes that's possible:
```yaml
network:
  vpc:
    placement: private
```

**Comment by chriskuech** [comment]
The backend service didn't work for me, but the ec2 deployment did seem to fix the issue.  This was a very frustrating bug--hopefully Fargate team is prioritizing a fix.

**Comment by efekarakus** [comment]
Closing the issue for now as we can't do much from the Copilot side :( but we've shared the experience with the Fargate team
