### ISSUE TITLE
Service Discovery requires additional changes

### ISSUE THREAD

**Issue by chriskuech** [aws/copilot-cli#3065]
Service Discovery is dependent on the private hosted zone to resolve IPs, which is exposed through <subnet> + 2, which is `10.0.0.2` with copilot.  I had to explicitly set this as my domain resolver to get Service Discovery working.  Not sure if it's an nginx-specific issue or not, but I assume it would apply to all services as it's a non-default IP.

**Comment by huanjani** [comment]
Hi, @chriskuech!

I'm not super well-versed in Service Discovery, but it looks like it could be an nginx-related issue: https://stackoverflow.com/questions/53549991/nginx-reverse-proxy-ngx-upstream-resolvemk-trying-to-resolve-srv-from-ecs-se/58392681.... What do you think?

Thanks!

**Comment by chriskuech** [comment]
Not sure. On the one hand, it was completely resolvable within nginx.conf by adding this line:

```nginx
resolver 10.0.0.2 valid=15s; # Route 53 private hosted zone IP (subnet + 2)
```

On the other hand, `10.0.0.2` does not appear to be a standard IP for DNS and figuring this out required a few hours and breaching the `copilot` abstraction layer.

Not sure how much this can really be addressed, but including that DNS IP in the Service Discovery docs would go a long way.
