### ISSUE TITLE
Multiple Load Balanced Applications

### ISSUE THREAD

**Issue by dmathewwws** [aws/copilot-cli#3069]
I have a question from error I am getting:

I add a new front end service of type `Load Balanced Web Service`. It is then available at http://XYZ.region.elb.amazonaws.com
I then add another service of type `Load Balanced Web Service` for my backend. I want this to be accessible to the internet (for example for the backend to be available to my mobile apps). Inside this manifest.yml I add a path for /api for this service. (see below)

```
# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: 'api'
```

it says this service should be available at http://XYZ.region.elb.amazonaws.com/api. But it is unaccessible. 

Is this the right to architect having a frontend and a backend that are both publicly available to the internet?

PS: I have gotten it to work atm by making 2 applications. it then gives 2 distinct URLs for my frontend + backend applications but I was wondering if I could get it to work with one application / one ALB?

**Comment by efekarakus** [comment]
Hi @dmathewwws ! 

Are the handlers for your service starting with `"/api"` ? ALB doesn't rewrite the requests (https://serverfault.com/a/876549) such that anything going to "http://XYZ.region.elb.amazonaws.com/api" would go to your "/" handler, instead it will be routed to a "/api" handler.

For example, using express in nodejs with the manifest above we would need to write:
```js
 app.get('/api', (req, res) => {
   res.send('Hello');
 });
```

**Comment by dmathewwws** [comment]
That was it! thanks :)
