### ISSUE TITLE
NSJail Template

### ISSUE THREAD

**Issue by chadbrewbaker** [aws/copilot-cli#3075]
[Compiler Explorer](https://compiler-explorer.com) - a.k.a. Godbolt - uses [nsjail](https://github.com/compiler-explorer/infra/blob/b419a94ffc423c637e8722d79fb4f42770acf05e/setup-node.sh#L67) to run untrusted code. 

This would be useful for compiling and untrusted media processing.

- [ ] worker cgroup that you can nsjail 
- [ ] ffmpeg example

**Comment by Lou1415926** [comment]
Hi @chadbrewbaker !

I am not certain if this issue is for AWS Copilot. If so, would you mind providing more details of your request?

Thanks!

**Comment by Lou1415926** [comment]
Closing this issue since we haven't heard a response. Please feel free to reopen it if the issue is for AWS Copilot! Thanks!

**Comment by tekknolagi** [comment]
I suppose the issue is supporting privileged mode: https://github.com/aws/copilot-cli/issues/3488

**Comment by chadbrewbaker** [comment]
Godbolt and I talked a bit about it today in the context of making AWS lambdas easy to run a jailed process on. https://twitter.com/smt_solvers/status/1516625452076605440
