### ISSUE TITLE
infinity

### ISSUE THREAD

**Issue by cristianMiranda-Oro** [aws/copilot-cli#3078]
![borrar](https://user-images.githubusercontent.com/60802503/143950720-ad2d80dd-0a84-43d1-ae33-301efa891b62.png)

**Comment by efekarakus** [comment]
Hi @cristianMiranda-Oro 👋 

This is the repo for AWS Copilot CLI: https://aws.github.io/copilot-cli/ and not GitHub Copilot. 
Resolving the issue, thanks!
