### ISSUE TITLE
`task run` should allow additional security group configuration

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#3100]
Currently, with `--app` and `--env` specified, `copilot task run` automatically uses the environment security group for the task. However, user won't be able to configure additional security groups in addition to the environment security group, because  the `--security-groups` flag  is mutually exclusive with `--app` and `--env`.

### Example Use Case
User may want to run a task with the same configuration as one of their services. The environment security group, however, is not necessarily the only security group that their service is using. For example, if the service has an Aurora addon, it will also have an Aurora security group to access the DB.

The task should be able to use this security group as well, in addition to the environment security group.

### Proposal
When user specify `--app`, `--env` and `--security-groups` at the same time, we don't error out. Instead, we append the security groups specified by `--security-groups` to the environment security group.

### Related Issue
In #3094, user wants to run the task in the environment's account, with additional security groups and subnets configuration. Without being able to use `--security-groups` with `--app` and `--env`, they have to switch the default profile to the environment profile before running the `copilot task run` command with `--security-groups`, `--subnets` and `--cluster` flags.

With this proposal, (assuming they don't need additional subnets), they could have run it with `--app`, `--env` and `--security-groups` flags. This way, Copilot can automatically assume the environment manager role, and they wouldn't have to switch the profile.

**Comment by efekarakus** [comment]
Hi folks! The fix is now released https://github.com/aws/copilot-cli/releases/tag/v1.16.0 🥳 Thank you @codekitchen ❤️ 

See announcement: https://aws.github.io/copilot-cli/blogs/release-v116/

**Comment by codekitchen** [comment]
you all are awesome, thanks!
