### ISSUE TITLE
`task run --generate-cmd` workflow

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#3103]
Currently, user can run `copilot task run --generate-cmd <app>/<env>/<svc>` to generate a `task run` command with an existing service's configuration. Then, they'd copy & paste and run the generated command to spin up the tasks.

The issue with this workflow is that the tasks will be spun up in the default profile's account, which is likely the application account, while user probably expect them to be in the environment's account (see #3094). Copilot should be able to provide a better workflow.

Here are two directions from which the improvement can be made:
1. Currently, the command is always generated with the `--subnets`, `--security-groups` and `--cluster` flags. Instead, Copilot could spit out a command that uses the `--app` and `--env` flag (potentially `--security-groups` flag as well - see #3100 )  if the argument is `<app>/<env>/<svc>`. This way, Copilot knows the task is meant to be placed in an environment, thus using the environment manager role to perform any operation instead of the default profile.
2. Copilot could still spit out the command with the `--subnets`, `--security-groups` and `--cluster` flags, just like what it currently does. However, it could prepend two commands `AWS_PROFILE=default; AWS_REGION=<env_region>;`. If Copilot detects that the environment account is different than the application account, it prints to `stderr` to ask user to change `AWS_PROFILE=default` to the environment profile. This way, Copilot makes sure that the user is aware that they may need to switch profile before spinning up the task. (Why `stderr`? Because otherwise user wouldn't receive any message if they had run `$(copilot task run --generate-cmd ...)`)

**Comment by codekitchen** [comment]
We would prefer option 1 here. I feel like option 2 (and the current workarounds to this problem) break the model of environment credentials not being needed for copilot outside of creating/deleting environments, since copilot will assume the envrionment manager role for you. For instance the [Credentials page](https://aws.github.io/copilot-cli/docs/credentials/#environment-credentials) of the docs specifically says

> Unlike the Application credentials, the AWS credentials for an environment are only needed for creation or deletion. 

We could certainly make it work, but we weren't planning on having all dev team members get users and set up profiles in the individual environment accounts.

**Comment by codekitchen** [comment]
We'd still really love to see this first option implemented in tandem with #3100 , allowing `--security-groups` alongside `--app` and `--env`. I haven't seen any further discussion on this two issues -- would it be OK for me to send over PRs for these changes? Or does a decision still need to be made here?

**Comment by Lou1415926** [comment]
@codekitchen Hello!! Thank you very much for offering help 🥳  Really appreciate it! Feel free to open up a PR for #3100  and option 1 in this issue, and please take a look at our contribution guide [here](https://github.com/aws/copilot-cli/blob/mainline/CONTRIBUTING.md)! Thank you so much!

**Comment by codekitchen** [comment]
Great! I'll hopefully do that this week 👍
