### ISSUE TITLE
Issue with using existing VPCa

### ISSUE THREAD

**Issue by vitalykarasik** [aws/copilot-cli#3109]
I'm getting IAM error when trying to use existing VPCs ("copilot env init --name test --profile default --app application-name"):

✘ select VPC: list VPC ID: describe VPCs: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: 6e1f481f-b1b8-41c4-9f90-0964fa50c408

It seems to be copilot CLI issues because:
1) I'm able to run "aws ec2 describe-vpcs"
2) I'm able to run "copilot init     --app my-app    --name me-service     --dockerfile Dockerfile     --deploy     --port 80     --type 'Load Balanced Web Service'"

**Comment by iamhopaul123** [comment]
Hello @vitalykarasik I am able to reproduce the error. Here what I did
```
$ copilot env init
Environment name: prod
Credential source: [profile fra]
Default environment configuration? No, I'd like to import existing resources
✘ select VPC: list VPC ID: describe VPCs: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: 5c69f712-082f-4f65-a5ba-740f906f08e8
```
I manually updated my profile `fra` to have an incorrect credential. Could you check if the profile you are using to deploy the environment has the correct credential? `aws ec2 describe-vpcs` might work if your default profile has the correct cred.

**Comment by vitalykarasik** [comment]
@iamhopaul123 - many thanks, I'll re-check. 
You're right, I didn't use "copilot env init", but  from the other hand, I was able to run another copilot commands, this the same AWS profile (I'm using AWS_PROFILE env variable).

**Comment by iamhopaul123** [comment]
Hello @vitalykarasik sorry for the late reply. I believe your `AWS_PROFILE` env var is configured correctly. However, since you were creating the environment using the `default` profile, I doubt if in your aws config file, the profile with name `default` is configured correctly. Could you double check? Thank you!
