### ISSUE TITLE
Can't use ARM CodeBuild image in pipeline

### ISSUE THREAD

**Issue by wolverian** [aws/copilot-cli#3110]
Using

```
build:
  image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
```

in `pipeline.yml` results in:

```
Failed to call UpdateProject, reason: AWS CodeBuild curated image aws/codebuild/amazonlinux2-aarch64-standard:2.0 is not supported for projects with environment type LINUX_CONTAINER and compute type BUILD_GENERAL1_SMALL (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; Request ID: a17e5d32-9e1b-44b1-942d-aeee3eed4932; Proxy: null)
```

CloudFormation error.

According to https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html, I would need to set the CodeBuild environment `type` value to `ARM_CONTAINER` instead of `LINUX_CONTAINER`. (The naming there contains a category error, but that's a CodeBuild issue, not Copilot.)

**Comment by wolverian** [comment]
Sorry, this might be my fault. I'm trying to run this pipeline in the Stockholm region, which doesn't support ARM CodeBuild environments yet. 🤦

**Comment by iamhopaul123** [comment]
No worries! I'll close this issue and feel free to reopen if you think it is a different root reason 😄
