### ISSUE TITLE
Using Cloudflare Proxy causes ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by aibharata** [aws/copilot-cli#3113]
I have a copilot application mapped with custom domain name. The domain is managed by Cloudflare.  I have added A records of ELB the copilot in Cloudflare DNS. Everything works fine when proxy mode in Cloudflare is turned off.  

However, When I turn on proxy mode in Cloudflare, I get  ERR_SSL_VERSION_OR_CIPHER_MISMATCH. 

Any idea on how to resolve this issue?

**Comment by iamhopaul123** [comment]
Sorry @aibharata I am a little bit confused on how you could use Cloudflare with Copilot. Right now we only accept using a route53 domain. I was wondering how you got cloudflare DNS work with Copilot? Did you not using the `--domain` flag when creating the application at all? Thank you if you could share us your use case!

**Comment by aibharata** [comment]
Our domain xyz.com's DNS  is managed by Cloudflare. And here's the step I followed to create the application:

- Create xyz.com hosted zone in Route53 in AWS. Copy the CNAMEs shown in the hosted zone and create CNAME records in Cloudflare DNS -->` Validation Successful`.

- Create new app: `copilot app init ampiyex --domain xyz.com`
- Use ACM to issue certificates for ampiyex.xyz.com and *.ampiyex.xyz.com. --> Issuing successful.
- Create new environment: `copilot env init -n prod --profile copilot --default-config`
- Create new Service: `copilot svc init --name nginxenvoy --svc-type "Load Balanced Web Service" --dockerfile ./nginxenvoy/Dockerfile`

- To access `nginxenvoy.prod.ampiyex.xyz.com` I had to get Loadbalancers IP addresses and create A records in Cloudflare, 
- Everything works fine when DNS mode only is turned on and I'm able to access `nginxenvoy.prod.ampiyex.xyz.com` from the internet. 
![image](https://user-images.githubusercontent.com/60269206/145662686-003d3327-d412-4434-b723-d6011a9c2d98.png)

However, I want to use Cloudflare proxy in front of the copilot application, that way traffic first hits Cloudflare and then gets routed to the copilot application. With Cloudflare it's easy to turn on under attack mode to mitigate bot traffic when in proxy mode. When I turn on proxy mode, I get the SSL version or Cipher mismatch error.

Any ideas how to get this case to work?

**Comment by iamhopaul123** [comment]
Hello @aibharata. It doesn't seem to be a Copilot issue to me, since it worked without the proxy was enabled. Could you double check the Cloudflare configuration is correct (this [tip](https://www.quora.com/How-do-I-fix-ERR_SSL_VERSION_OR_CIPHER_MISMATCH-Cloudflare) might be useful).

**Comment by h5aaimtron** [comment]
If you're using CloudFlare proxy setting, you'll want to pull the CloudFlare  end to end cert (its a self-signed cert from CloudFlare) and install it in aws. CloudFlare will then present to your clients the wildcard cert *.xyz.com while communicating with your aws hosted back-end using their self-signed cert they issued you.

**Comment by ReDev1L** [comment]
For future references:
You need to buy Advanced Certifacte for your domain in CF and this will work

**Comment by jetaggart** [comment]
@aibharata did this end up working for you? I'm curious how you dealt with the ALB rotating IPs if you're hardcoding them in CF?

**Comment by aibharata** [comment]
> I'm curious how you dealt with the ALB rotating IPs if you're hardcoding them in CF?

No. It didnt work. I had to ditch the copilot service after some time. The rotating IPs was a problem for sometime. I had written a script to  poll the changes and change the  IP via CF API.
