### ISSUE TITLE
Unable to install Copilot on Windows 10

### ISSUE THREAD

**Issue by RoniqueRicketts** [aws/copilot-cli#3151]
Platform: Windows10

Copilot: v 1.13.0

Error: copilot: command not found in CMD

Issue: I tried to install the executable on PC but I get an error that the executable is a command-line tool. I then tried to install the app using URL ```https://aws.github.io/copilot-cli/docs/getting-started/install/ ``` but when I run ```copilot init``` but it returns ```command not found```. What can I do to install this on my Windows PC. 

Installation Command: ```Invoke-WebRequest -OutFile 'C:\Program Files\copilot.exe' https://github.com/aws/copilot-cli/releases/latest/download/copilot-windows.exe```

**Comment by efekarakus** [comment]
Hi Ronique! 
I believe this is because the executable needs to be added to your $PATH. These instructions might help: https://medium.com/@kevinmarkvi/how-to-add-executables-to-your-path-in-windows-5ffa4ce61a53

**Comment by Lou1415926** [comment]
Closing the issue due to [customer's comment on Gitter](https://gitter.im/aws/copilot-cli?at=61cbaa80d41a5853f923f6c4). Please feel free to reopen it if further help is needed!
