### ISSUE TITLE
Make MinimumHealthyPercent and MaximumPercent configurable

### ISSUE THREAD

**Issue by webjunkie** [aws/copilot-cli#3153]
I have an Internet-facing web service that depends on file storage (EFS) and this currently works well with Copilot. However, only a single instance needs to be running. In fact, two instances might mix up data in the file system and are thus prevented from running by placing a lockfile in the data directory.

For this reason I would like to configure `MinimumHealthyPercent` and `MaximumPercent` so that ECS knows that it should not have more than 1 instance running and that it's okay to have 0 instances of the task running.

**Comment by Lou1415926** [comment]
Hello @webjunkie ! 

Would it work for you if you [scale](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#count) the LBWS from 0 to 1? This could be done by specifying 
```
count: 
  range: 0-1
```

One clarification question: `MinimumHealthyPercent` and `MaximumPercent` does not tell ECS how to scale the service, instead, they are [rolling deployment configuration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html ). That is, how many tasks are allowed/needed to be in RUNNING state __during__ the rolling deployment. For example, if the `DesiredCount` of the services is `5`, then eventually, after the deployment reaches a stable state, the number of tasks will be `5` - not controlled by `MinimumHealthyPercent` or `MaximumPercent`. Is this what you are looking for?

**Comment by webjunkie** [comment]
I really am thinking mainly about deployments here. I want to make sure only one task is running. However, I just read on the deployment link you provided that `MinimumHealthyPercent` and `MaximumPercent` are not even taken into account when using Fargate 😔 

What effect would `range: 0-1` have on deploys? I assume ECS would still fire up a new task before stopping the old. I want to old one to be stopped, only then the new one started.

**Comment by iamhopaul123** [comment]
Hello @webjunkie yeah unfortunately even if you put `range: 0-1` it will still spin up a new one and then stop the old one which could be an issue for you :( How about taking two steps? Deploy with `count: 0` and then deploy with `count: 1`?

**Comment by webjunkie** [comment]
That might work, but then it's actually easier to stop the running task manually before deploying. Too bad it seems there are no other options.

**Comment by webjunkie** [comment]
I'm also still not sure why Fargate wouldn't honor `MinimumHealthyPercent`, I might test this directly as I'm not sure whether to trust the docs there 😅  It seems awkward.

**Comment by webjunkie** [comment]
I got around to test this today, [using a fork with these values modified accordingly](https://github.com/webjunkie/copilot-cli/compare/webjunkie:mainline...feature/deploy-config). The behavior was as I expected, despite Fargate:


  <span>
  
  Date | Message
  -- | -- 
  1/7/2022, 11:04:04 AM | (service node-Service-xxx) has reached a steady state.
  1/7/2022, 11:04:04 AM | (service node-Service-xxx) (deployment ecs-svc/xxx) deployment completed.
  1/7/2022, 11:03:44 AM | (service  node-Service-xxx) registered 1 targets in  (target-group  arn:aws:elasticloadbalancing:eu-central-1:xxx:targetgroup/xxx)
  1/7/2022, 11:02:45 AM | (service node-Service-xxx) has started 1 tasks: (task xxx).
  1/7/2022, 11:01:28 AM | (service node-Service-xxx) has stopped 1 running tasks: (task xxx).
  1/7/2022, 11:00:24 AM | (service node-Service-xxx) has begun draining connections on 1 tasks.
  1/7/2022, 11:00:24 AM | (service  node-Service-xxx) deregistered 1 targets in  (target-group  arn:aws:elasticloadbalancing:eu-central-1:xxx:targetgroup/xxx)
  
  </span>

Just to make sure, I used `deploy --force` to get it to deploy. The observed stopping-before-starting is not due to this, right?

Would a PR be welcome to make deployment configurable? If so, what would a be a preferred form? One could set the percentages directly, have a switch for type of deploy (`deploy: rolling | replace`), or else 🤔

**Comment by webjunkie** [comment]
@efekarakus @Lou1415926 can someone confirm my findings? I'd see if I can contribute a PR.

**Comment by iamhopaul123** [comment]
Hello @webjunkie. So sorry for the late reply. 

> One could set the percentages directly, have a switch for type of deploy (deploy: rolling | replace)

Do you mean if they set `rolling` (which is also the default), under the hood we set `100/200` for them while if they set `replace` we set `0/100` for them? I think that's a brilliant idea.

**Comment by webjunkie** [comment]
Yes, that's what I mean 🙂

**Comment by iamhopaul123** [comment]
Hello @webjunkie. After discussing within the team, I've learned that:

1. ECS is working on improving the deployments experience, we're looking to have a proposal that considering the new deployment UX
2. Part of this design, our first milestone will be to support your feature request

Hopefully we'll be able to support this in next couple of months. Please stay tuned!

**Comment by huanjani** [comment]
@webjunkie: The feature is now released in v1.18.0: https://github.com/aws/copilot-cli/releases/tag/v1.18.0!

**Comment by webjunkie** [comment]
Awesome. That's great to hear! Thank you.
