### ISSUE TITLE
Add `--no-rollback` flag to Copilot deploy

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#3156]
Right now by default when using `Copilot` to deploy a workload (either a service or a job), CFN automatically rolls back to if the deployment fails. This could be a problem when debugging or triaging issues because all resources created during the previously failed deployment will get cleaned up automatically.]

As a developer I want to use `copilot deploy --no-rollback` flag when trying to find out the reason why my deployment fails.

**Comment by iamhopaul123** [comment]
However, if users specify `--no-rollback` flag, then if anything goes wrong, they won't be able to deploy again unless they roll the stack back manually either through console or by `aws cli`.

One mitigate could be showing the command they would need to run as recommendation, so that they can just copy, paste, and run the command for manual rollback after triaging the CFN failure.

**Comment by efekarakus** [comment]
Hi folks! The feature is now released https://github.com/aws/copilot-cli/releases/tag/v1.16.0 🥳 

See announcement: https://aws.github.io/copilot-cli/blogs/release-v116/
