### ISSUE TITLE
Explain scheduled job "retries"

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#3160]
I have a question about how the "retry" functionality works with the scheduled job. Basically, what condition(s) determine that an attempt to run a scheduled job has failed and should be retried? 

We have a process that runs as a schedule and we only want to retry running the process if it was unable to start at all. Hopefully my question is clear. Let me know.

Great work by the way!

**Comment by efekarakus** [comment]
Hi @bpottier! Happy new year 🎈 

Apologies for the delay in the response 🙇 Your question is clear.

> Basically, what condition(s) determine that an attempt to run a scheduled job has failed and should be retried?

Today, Copilot listens on `"States.ALL"` to start retrying the scheduled job. I've tried various failure scenarios to see what are the error values returned from step functions and my observations are:
* If an essential container exits with a non-zero exit code, then the `"States.TaskFailed"` error status is returned.
* If the container fails to come up at all (`CMD` instruction fails in Dockerfile), then the `"States.TaskFailed"` error status is returned.

This seems to line up with this post:
>  ECS or Fargate tasks initiated from a Step Function are unable to return information of the exceptions encountered during run-time. Instead, if an unhandled exception occurs, the calling Step Function receives a States.TaskFailed error. 
> https://nuvalence.io/blog/aws-step-function-integration-with-ecs-or-fargate-tasks-data-in-and-out

So I don't think there is a way today to differentiate error types returned from ECS for retrying a task :(

**Comment by bpottier** [comment]
@efekarakus Thanks for the clarification. That definitely makes it clear now.
