### ISSUE TITLE
You cannot associate an existing service/application with a domain after it's already been created by Copilot CLI and deployed

### ISSUE THREAD

**Issue by glynjackson** [aws/copilot-cli#3162]
The first few hours playing with Copilot, so impressive, but I have run into one issue when trying to add a domain and alias. It would appear I cannot associate an existing service/application with a domain after it's already been created by Copilot CLI and deployed. 

_Apologies in advance if some of my terminology isn't correct._

- Running v1.13.0
- Using version 1.13.0 I created a new initial service and application and deployed it successfully (without initially using the --domain flag) 
- Later, I added `alias` in the existing manifest and got the following error message: 

```
✘ To use `http.alias`, your application must be associated with a domain: `copilot app init --domain example.com`.
✘ execute svc deploy: alias specified when application is not associated with a domain
```

- Following the CLI message above  I run  `copilot app init --domain api.mydomain.com` and redeploy, but it still gives the same error message and appeared to have no effect.

I read the documentation and noticed the following wording states...

```
As mentioned in the Application Guide, you can configure the domain name of your app when running copilot app init
``` 

[Ref](https://aws.github.io/copilot-cli/docs/developing/domain/)

My question:

- Can you create an alias for an existing application as the CLI output messages would lead me to believe, and if so, then is this a bug?
-  If you can't create an alias for an existing application after its creation then is the CLI message misleading?

**Comment by efekarakus** [comment]
Hi @glynjackson ! Apologies for the late reply and thank you for the detailed issue description 😍 

I believe this is the same issue as https://github.com/aws/copilot-cli/issues/3045 and you're right unfortunately today you can't associate a domain once the application is created 🙇 
For now users are forced to create a second application with `--domain` with the exact same set of services and then run `copilot app delete` on the old application to delete the resources.

I agree the UX is confusing, we'll add a notice to the docs saying that the feature is supported only while creating the app the first time and can't be updated. We'll also track the feature request's status in #3045, if you wouldn't mind giving a 👍 there!

**Comment by efekarakus** [comment]
Created a PR to add the notice here: https://github.com/aws/copilot-cli/pull/3164, once merged it should become public with our next release!

**Comment by glynjackson** [comment]
Hi @efekarakus 

Thank you for the explanation, it now makes sense and resolves my initial confusion.

#3045 thumbs up given.

Also, thank you for PR #3164 clarifying the domain association, it really helps and I'm sure it will help others coming to Copilot for the first time too. 

Again thanks @efekarakus for the prompt and detailed response. I've heard the Copilot team are fantastic problem solvers, but I didn't expect such a fast and courteous response to my maybe dumb question, so it's very much appreciated. 

Glyn
