### ISSUE TITLE
Clarification around "copilot svc deploy" command

### ISSUE THREAD

**Issue by tsingh2k15** [aws/copilot-cli#3163]
### Discussed in https://github.com/aws/copilot-cli/discussions/3136

<div type='discussions-op-text'>

<sup>Originally posted by **tsingh2k15** December 19, 2021</sup>
I was looking at the docs for `copilot svc deploy` command and was curious to understand/explore more about the steps it performs. https://aws.github.io/copilot-cli/docs/commands/svc-deploy/

My question is around step 1 - `Build your local Dockerfile into an image`

Does it always build the container image from `Dockerfile` even if the image might be already built independently before this step? I know there is a mutually exclusive option in the manifest file - https://aws.github.io/copilot-cli/docs/manifest/backend-service/#image-location but I was curious to check if the deploy command can have an `alternative mode` where it could just tag an already built image and perform remaining steps by `skipping` step 1? 
</div>

**Comment by efekarakus** [comment]
Hi @tsingh2k15 !

If the Dockerfile does not contain any modifications, then a new container image shouldn't be built instead it will do exactly what you said where a new tag is created (if using `--tag` or created a new git commit) and pushed to ECR instead. Did I understand your question correctly? Does this help?

**Comment by tsingh2k15** [comment]
> 

@efekarakus This is correct. I have mentioned detailed scenario in the discussion at - https://github.com/aws/copilot-cli/discussions/3136 Considering that, I believe it could be useful to have a capability added to the `deploy` command, such that user can specify the image especially in the scenarios(refer the scenario I mentioned at https://github.com/aws/copilot-cli/discussions/3136 ) where there are modifications in Dockerfile.
