### ISSUE TITLE
[Question] Should I avoid running internal tasks in Backend Service ?

### ISSUE THREAD

**Issue by g-grass** [aws/copilot-cli#3167]
- Sorry for the rudimentary question, and please feel free to close it if it's not the right place to post it.
- I have a question about how to use the `Backend Service`.

- As for the use of `BackendService`, [the official documentation](https://aws.github.io/copilot-cli/docs/concepts/services/)  says the following.
  > Copilot will provision an ECS Service running on AWS Fargate, but won't set up any internet-facing endpoints.

- On the other hand, according to the [AWS Blog](https://aws.amazon.com/jp/blogs/compute/task-networking-in-aws-fargate/), it is a best practice not to place internal tasks on public subnets when running them on Fargate.
  > If you are running a service that handles private, internal information, you should not put it into a public subnet or use a public IP address. 

### Question
- Should I switch to a private subnet (and, depending on the use case, building a NATGateway.) for internal tasks, even if no endpoint is provided to the Internet?

### Other
- There is already a mechanism in the manifast file to switch to a private subnet, so I don't think it will be a problem for the function.
- https://aws.github.io/copilot-cli/docs/manifest/backend-service/

**Comment by efekarakus** [comment]
Hi @g-grass!

I think it just depends on your compliance requirements, if an external auditor is demanding tasks to be placed in private subnets then like you mentioned the manifest would need to be updated with:
```yaml
network:
  vpc:
    placement: 'private'
```

However, the tradeoff is that NAT gateways cost extra money: https://aws.amazon.com/vpc/pricing/

On the other hand, if the content handled in the tasks are not sensitive, then you can leave the tasks in public subnets. The tasks have a security group that blocks incoming external connections so nothing but other tasks in your VPC should be able to make requests to your Backend Service.

Sorry I couldn't give a definite answer, does this help?

**Comment by g-grass** [comment]
@efekarakus 
Thank you so much for your quick response.
Yes, my question has been answered.
I will also close on this Issue.
