### ISSUE TITLE
Upgrading copilot to latest version

### ISSUE THREAD

**Issue by dmathewwws** [aws/copilot-cli#3168]
Hi, 

I'm looking to upgrade copilot to the most recent version. 

I installed copilot using homebrew so I can upgrade it via homebrew too, but in my `buildspec.yml` I see some hardcoded code to my current version of copilot.

```
      # Download the copilot linux binary.
      - wget https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.12.0
      - mv ./copilot-linux-v1.12.0 ./copilot-linux
```

Is this something that has to be manually updated? And would these 2 things be the only things needed to upgrade copilot. 

Thanks!

**Comment by huanjani** [comment]
Hello, @dmathewwws! 

Yes, you are exactly right-- that line of the buildspec needs to be manually updated, and yes, just those two places. We have buildspec and other pipeline improvements coming down the line, so keep an eye out for them! 😄 

Here is some related discussion of this issue: https://github.com/aws/copilot-cli/issues/2613.

Hope that helps!
