### ISSUE TITLE
`svc logs --follow` doesn't print all logs

### ISSUE THREAD

**Issue by rinogo** [aws/copilot-cli#3220]
Expected behavior
`copilot svc logs --follow` should print all lines printed by the application since the `copilot svc logs --follow` command was executed.

Actual behavior
`copilot svc logs --follow` only prints 10-line "chunks" of output. It doesn't print all lines. In practice, it seems to print the last 10 lines resulting from a test request. I'm assuming the fact that the "chunk" is 10 lines of output is related to the default value for `--limit` (10).

I seem to be able to get around this with `copilot svc logs --follow --limit 10000`, but this feels clumsy and I'm not confident that all logged lines are being printed.

Am I misunderstanding how `copilot svc logs --follow` is intended to be used?

**Comment by rinogo** [comment]
Fwiw, if others are having trouble with this, I've found that using `--since` is a good alternative for printing the output from a recent test request:
`copilot svc logs --since 1m`

**Comment by Lou1415926** [comment]
Hi there @rinogo  👋🏼 ! Thanks for reporting the UX experience! 

Just a clarification question - would you rather expect that `copilot svc logs --follow` prints lines starting from "now", and one by one instead of in chunk?

Thanks!!

**Comment by rinogo** [comment]
Hi, @Lou1415926 ! I don't have much preference of whether it prints lines "one by one" or "in chunks". (In other words, I don't mind if the output is buffered)

The real issue is that `copilot svc logs --follow` seems to omit lines. For example, if the application prints a hundred lines to the console every minute, it seems that `copilot svc logs --follow` will only print ten lines from each one-hundred line burst.

Does that make sense?

**Comment by Lou1415926** [comment]
That totally makes sense. Thanks for the clarification!

This is a bug to `copilot svc log`. I've put a label to this issue so that we can fix it as soon as possible.

Thanks for reporting it!

**Comment by efekarakus** [comment]
Hi @rinogo 👋 We have a fix for the issue in #3258 which should go out next release.

Thank you for submitting this bug !
We're also changing the default behavior of `--follow` such that it prints logs from the current timestamp by default (instead of going to the past) so that you don't have to write `--follow --since 1s`

**Comment by rinogo** [comment]
Excellent! Thank you for being so responsive and helpful. This will improve "quality of life" significantly. I'm loving the progress on `copilot` - I'm enjoying watching this project mature with time. Keep up the great work! :)

**Comment by efekarakus** [comment]
Hi folks! The fix is now released https://github.com/aws/copilot-cli/releases/tag/v1.16.0 🥳 

See announcement: https://aws.github.io/copilot-cli/blogs/release-v116/
