### ISSUE TITLE
Synthesizing issues

### ISSUE THREAD

**Issue by insomniachooman** [aws/copilot-cli#3222]
Copilot was working fine and all of a sudden there are no solutions showing when I press control + enter (basically no synthesizing solutions are shown and even they are shown only the first line is shown). Here are the few things I have tried to fix the issues.
1. Uninstall the extension and reinstall it.
2. Signed out of the account and then signed back again.
3. Restart the laptop.
4. Tried an older version still the same (note that I previously didn't have this issues with synthesizing solutions.)

**Comment by efekarakus** [comment]
Hi @insomniachooman 👋  
Is this issue related to AWS Copilot (https://aws.github.io/copilot-cli/) or GitHub Copilot?  
If it's related to GitHub Copilot, this is unfortunately the wrong repository.

**Comment by insomniachooman** [comment]
I am sorry it is actually issues with Github copilot

**Comment by efekarakus** [comment]
No worries! I'll close the issue, I'm not sure unfortunately how to leave feedback for GitHub copilot
