### ISSUE TITLE
Unable to deploy service after upgrading to v1.14.0

### ISSUE THREAD

**Issue by adonig** [aws/copilot-cli#3229]
I've recently updated copilot-cli to v1.14.0 using homebrew on OS X. Now I can't deploy my service anymore.

Running `copilot svc deploy` fails with the following error (broken into multiple lines for better readability):

```
✘ execute "env upgrade --app myapp --name test":

upload custom resources to bucket stackset-myapp-infrastr-pipelinebuiltartifactbuc-rxbetrwqiavd:

read template custom-resources/dns-cert-validator.js:

open templates/custom-resources/dns-cert-validator.js: file does not exist
```

**Comment by Lou1415926** [comment]
Hi @adonig ! I wonder which homebrew formula you are using? Does [this instruction](https://github.com/aws/copilot-cli/issues/1918#issuecomment-775317935) solve the problem?

**Comment by adonig** [comment]
Hi @Lou1415926 ! There were two formulas of copilot-cli installed. One is called `copilot` and the other `copilot-cli`. I've uninstalled `copilot` and then linked `copilot-cli` and now the deployment works again. Thank you for your help!
