### ISSUE TITLE
Seeing issue with the latest copilot for default environment variable like "COPILOT_SERVICE_DISCOVERY_ENDPOINT"

### ISSUE THREAD

**Issue by naveendigumurthy** [aws/copilot-cli#3242]
After upgrading the copilot to the latest version 1.14.0

When I run the pipeline I am seeing this while building 

✘ interpolate environment variables for comments manifest: environment variable "COPILOT_SERVICE_DISCOVERY_ENDPOINT" is not defined

And the build got failed

**Comment by naveendigumurthy** [comment]
After moving it to the .env file issue got solved and build run successfully

**Comment by iamhopaul123** [comment]
Hello @naveendigumurthy glad it has been resolved! Let us know if you have additional questions.
