### ISSUE TITLE
Using copilot with Terraform / Pulumi (or any IaC)

### ISSUE THREAD

**Issue by guyschlider** [aws/copilot-cli#3243]
Hey,

Does anyone have an experience he can share about how to deploy and set up environments - using copilot and terraform (or any other IaC)?

Our usecase is that we use copilot for most of our services (not all of them) and as copilot didn't supported RDS/S3/ElasticSearch/ElasticCache and so on - we had to create them manually. we are now working on making it fully automated and are looking for any tips/suggestions

Thanks.

**Comment by armouti** [comment]
Hey, how did you end up solving this @guyschlider ?

**Comment by genbit** [comment]
Please take a look at https://aws.github.io/copilot-cli/docs/developing/overrides/cdk/
and https://aws.github.io/copilot-cli/docs/developing/addons/workload/
