### ISSUE TITLE
While using the .env file we are seeing issues in deploying the app through the pipeline

### ISSUE THREAD

**Issue by naveendigumurthy** [aws/copilot-cli#3244]
Updated copilot to latest version 1.14.0 and added a new .env file and triggered the pipeline

At the time of the deploy we are seeing the following error and got roll back

Server deploy got failed

`Partition "" is not valid for resource "arn::s3:::stackset-test-qa-infrastr-pipelinebuiltartifactbuc-1hh4rg3lyds4u/manual/f4063f9663d8d3fb600862222ddf947a61d0ac414a20284b2436336ed4f5/bootstrap.env". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 2b0dg80e-c952-49e8-8e16-e1c7c4009860; Proxy: null)`

Any idea how to fix this Thanks

**Comment by naveendigumurthy** [comment]
We are seeing that "aws" is missing in the value

correct value

`arn:aws:s3:::stackset-test-qa-infrastr-pipelinebuiltartifactbuc-1hh4rg3lyds4u/manual/f4063f9663d8d3fb600862222ddf947a61d0ac414a20284b2436336ed4f5/bootstrap.env`

any way to fix this when we are running the copilot

**Comment by naveendigumurthy** [comment]
Seeing issue at this like on the buildspec

`jq --arg a "arn:$PARTITION:s3:::stackset-test-qa-infrastr-pipelinebuiltartifactbuc-1hh4rg3lyds4u/manual/$checksum/$env_file" '.Parameters.EnvFileARN = $a' ./infrastructure/$workload-qa01.params.json > "$tmp" && mv "$tmp" ./infrastructure/$workload-qa01.params.json`

Here PARTITION value got empty when I updated it as the aws and deploy is good

**Comment by iamhopaul123** [comment]
Hello @naveendigumurthy. Thank you for reporting the issue. We'll fix the bug as soon as possible. Please keep track of this issue for the latest update.

**Comment by iamhopaul123** [comment]
Hello @naveendigumurthy. This bug should be fixed by https://github.com/aws/copilot-cli/pull/3283. Once we have a new release the fix should be out then. Also that would require you to regenerate the buildspec using the latest Copilot. Thank you!

**Comment by efekarakus** [comment]
Hi folks! The fix is now released https://github.com/aws/copilot-cli/releases/tag/v1.16.0 🥳 

See announcement: https://aws.github.io/copilot-cli/blogs/release-v116/
