### ISSUE TITLE
secret init failing

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#3250]
I'm running  v1.14.0 on an M1 Mac running macOS Monterey and when I try to create a secret I get the following error:

```
✘ upload custom resources to bucket stackset-agentportal-inf-pipelinebuiltartifactbuc-1llhxv61py00t: read template custom-resources/dns-cert-validator.js: open templates/custom-resources/dns-cert-validator.js: file does not exist
```

I'm not sure if its a bug or something on my end.

**Comment by iamhopaul123** [comment]
Hello @bpottier. Can I ask how did you get your Copilot installed? If you used Homebrew, then [this version](https://formulae.brew.sh/formula/copilot) is not managed by us and you would want to use `brew install aws/tap/copilot-cli
` instead.

**Comment by bpottier** [comment]
> Hello @bpottier. Can I ask how did you get your Copilot installed? If you used Homebrew, then [this version](https://formulae.brew.sh/formula/copilot) is not managed by us and you would want to use `brew install aws/tap/copilot-cli ` instead.

I did use Homebrew. I uninstalled copilot and used the tap and everything works now. Thanks!
