### ISSUE TITLE
Proposal: `logs -p` or `logs --open`

### ISSUE THREAD

**Issue by geovanisouza92** [aws/copilot-cli#3272]
Currently, if I want to check for the logs of exited tasks, I need to go to AWS console, navigate to ECS, find the cluster, then the service, than switch to stopped tasks, then search for the logs there.

It would be helpful to have a `copilot svg logs -p` where `-p` stands for "previous task" (like k8s), that dumps the logs of the most recent stopped task.

Besides that, an `copilot svc logs --open` that open the cloudwatch logs console with filter applied would be helpful too, just some extra steps (like login in).

**Comment by efekarakus** [comment]
That's a great idea! It totally makes sense to me, once we pick up the issue we'll drop a comment here!
