### ISSUE TITLE
Running one-off tasks from the build pipeline

### ISSUE THREAD

**Issue by mihai-fs** [aws/copilot-cli#3296]
In my pipeline `buildspec.yml` file I've added commands at the end of the `post_build` phase to run database migrations in a one-off task created using `copilot task run` using the newly built image however the build environment doesn't have permissions to provision the resources needed for the task:

```
✘ provision resources for task flowsignal-production-api-db-migrations: check if changeset is empty: create change set copilot-885c4133-cc8d-4785-bf55-c0f163d46b3b for stack task-flowsignal-production-api-db-migrations: AccessDenied: User: arn:aws:sts::899153599789:assumed-role/pipeline-flowsignal-app-BuildProjectRole-1AIMXVC1AQA0B/AWSCodeBuild-26140182-f3d1-430a-8da3-d326c5521a2e is not authorized to perform: cloudformation:CreateChangeSet on resource: arn:aws:cloudformation:us-east-2:899153599789:stack/task-flowsignal-production-api-db-migrations/* because no identity-based policy allows the cloudformation:CreateChangeSet action
--
950 | status code: 403, request id: b23c6546-e45d-4c22-b83e-b40fad303eb4: describe change set copilot-885c4133-cc8d-4785-bf55-c0f163d46b3b for stack task-flowsignal-production-api-db-migrations: ValidationError: Stack [task-flowsignal-production-api-db-migrations] does not exist
951 | status code: 400, request id: e9de5ae0-138c-4f7e-9e66-db4d26b17d6b: describe stack: describe stack events for stack task-flowsignal-production-api-db-migrations: ValidationError: Stack [task-flowsignal-production-api-db-migrations] does not exist
952 | status code: 400, request id: f09acd44-0aa7-45d4-bae3-1549c1fadee7
```

What permissions are needed for running `copilot task run` and what's the best way to get these permissions assigned to the build environment?

**Comment by huanjani** [comment]
Related: #2755

**Comment by Lou1415926** [comment]
Hello @mihai-fs ! Would you mind sharing what flags you are using while running `copilot task run`? Depending on the flags, you may need different permissions for your build project role.

**Comment by mihai-fs** [comment]
I got it working when I passed in the `--env` parameter:

```
./copilot-linux task run \
--app flowsignal --env mihai --image 999999999998.dkr.ecr.us-east-2.amazonaws.com/flowsignal/api:39c7d714-1d45-4c31-ad0d-cb5a69e468e2-mihai \
-n api-db-migrations --follow --command "yarn db:migrate" \
--execution-role arn:aws:iam::999999999999:role/flowsignal-mihai-api-ExecutionRole-1P4BTUSBGT844 \
--task-role arn:aws:iam::999999999999:role/flowsignal-mihai-api-TaskRole-DMBCEDFHQFRQ \
--env-vars COPILOT_APPLICATION_NAME=flowsignal,COPILOT_ENVIRONMENT_NAME=mihai,COPILOT_LB_DNS=flows-Publi-8TCS2WM04MMM-1974642821.us-east-2.elb.amazonaws.com,COPILOT_SERVICE_DISCOVERY_ENDPOINT=mihai.flowsignal.local,COPILOT_SERVICE_NAME=api
```

**Comment by Lou1415926** [comment]
Glad it's working now! A bit of explanation for future readers that found their way to this issue: with `--app` and `--env` flag,  Copilot assumes the environment manager role which has the required permissions. Without these flags, Copilot assumes the default profile in the running environment - in the case of CodeBuild, it's the build project role, which may not have by default those required permissions for `task run`. An enhancement that we can make is to allow additional permissions to be added to the build project role.
