### ISSUE TITLE
ECS service deleted, now I can't deploy!

### ISSUE THREAD

**Issue by coopsmoss** [aws/copilot-cli#3342]
```
5d5962699bd5: Layer already exists 
a42439ce9650: Layer already exists 
26270c5e25fa: Layer already exists 
e2c6ff462357: Layer already exists 
latest: digest: sha256:93ff153ceed5926d1ddf4bf9e0c596d08fd5c2b0b86b32f533ea07a546c67046 size: 3476
✔ Proposing infrastructure changes for stack api-prod-v1 
- Updating the infrastructure for stack api-prod-v1                                  [update rollback complete]  [56.6s]
  The following resource(s) failed to update: [Service].                                                         
  - An autoscaling target to scale your service's desired count                      [not started]                
  - An ECS service to run and maintain your tasks in the environment cluster         [update complete]           [0.0s]
    Failed to retrieve attribute [Arn] for resource [DiscoveryService]: nu                                       
    ll (Service: AWSServiceDiscovery; Status Code: 400; Error Code: Servic                                       
    eNotFound; Request ID: 1eb88d3b-ef8b-4de0-a254-786afd973f8c; Proxy: nu                                       
    ll)                                                                                                          
  - An ECS task definition to group your containers and run them on ECS              [delete complete]           [2.7s]
✘ deploy service: stack api-prod-v1 did not complete successfully and exited with status UPDATE_ROLLBACK_COMPLETE
```
Need advice please!

Deleted the service fro the ECS panel due to another problem. I thought I'd be able to just use deploy or deploy --force but then the above error is given

**Comment by efekarakus** [comment]
Hi @coopsmoss ! If the service was deleted manually, you can try running `copilot svc delete -e <your env name>` to delete the stack completely. Then you should be able to re run `copilot svc init` and `copilot deploy` to redeploy the service

**Comment by coopsmoss** [comment]
Hi @efekarakus 
Is that the only way? This is a production environment and the database is critical!


I'm on the phone now with a support engineer but he doesn't know the copilot system well.

**Comment by efekarakus** [comment]
Gotcha! Hmm perhaps one other way might be trying to recreate the ECS service manually but with the exact same auto generated name by copilot. Once the resources are back to a good original state you can try running `copilot deploy` again

**Comment by coopsmoss** [comment]
Is there a way to get that name? I know they have some kind of unique string on the end of them. "app-env-Service-kfhsdjkfasjkdf"

**Comment by efekarakus** [comment]
Can you check the resources tab in the cloudformation stack? Hopefully it will be listed there

**Comment by Lou1415926** [comment]
You could also try CloudFormation drift detection. Hopefully that could tell you the last state of your service including the autogenerated name.

**Comment by coopsmoss** [comment]
Thanks everyone,

I found the name in the stack's resources and once I made created a new service via the gui based on the template and our testing environment everything came back to life.

Unfortunately I still can't deploy via the cli, I think the ARN for the discovery service is different now.

```
Failed to retrieve attribute [Arn] for resource [DiscoveryService]: nu                                   
    ll (Service: AWSServiceDiscovery; Status Code: 400; Error Code: Servic                                   
    eNotFound; Request ID: 56fabc81-7f7c-4666-9d62-06d7b2f8f7c7; Proxy: nu                                   
    ll)   
```
It's interesting that it says `null` in there. I don't think I can edit the discovery aspect of a service once created though.
Does anyone have any tips on fixing this?

**Comment by efekarakus** [comment]
oh very strange 🤔 -- was there any other resource besides the ECS service, such as the service discovery namespace, that were manually deleted?

If the service discovery service was deleted, we can also try re-creating it manually but I'm not certain if it will work:
1. Find the `DiscoveryService` resource `PhysicalId` by navigating to the CloudFormation "Resources" tab for the stack
2. Navigate to AWS Cloud Map > Namespaces > {env}.{app}.local
3. Create a service with your service name
4. Try `copilot deploy` again

If none of this works, I think my recommended work around would be to create a brand new service `copilot svc init` and `copilot deploy` that.
Once the service is deployed with a brand new database, you can migrate the data from the old database to the new one and then delete the old stack. Hope this helps!

**Comment by coopsmoss** [comment]
Nothing else was deleted explicitly (though I don't know what other deletes occur automatically).
Thank you for the advice one again @efekarakus, I can once again deploy via the cli!

As a total aside, I've noticed this line in the deployment
```
  - An autoscaling target to scale your service's desired count               [not started]      
```
Is this anything to be concerned about? I went back into our CD logs and it was happening before this issue.

**Comment by efekarakus** [comment]
> Is this anything to be concerned about? I went back into our CD logs and it was happening before this issue.

Nope nothing to be concerned about, I'm not sure exactly why but sometimes CloudFormation will have the resource appear in the changeset although nothing gets updated.

I'm glad we got the resources back to a regular state! Closing the issue now 😄 feel free to re-open if you have any other questions

**Comment by coopsmoss** [comment]
Hey @efekarakus thanks for all your help so far. Things still aren't quite right yet though.

When I attempt to `exec` copilot can't locate the service, is there a parameter somewhere I can change to get this straight?
Here is the printout:

```
$ copilot svc exec
Service: v1
✘ describe ECS service for v1 in environment prod: no ECS service found for v1 in environment prod
```

**Comment by efekarakus** [comment]
@coopsmoss hi!
okay I think some resource tags might be missing from the ECS service.
Would you mind adding the following AWS tags to your service: `copilot-application=<your app name>`, `copilot-environment=prod`, `copilot-service=v1`?
I think that should unblock you

**Comment by coopsmoss** [comment]
This didn't fix it at first, but after another deploy it's all working great!
Thanks a bunch @efekarakus.  The outage all the small issues following it have been incredibly stressful, buy you've been so helpful and I think everything is back to normal now, so I can't thank you enough.

**Comment by efekarakus** [comment]
I'm really glad to hear that :) best of luck with the product!

**Comment by coopsmoss** [comment]
Hey @efekarakus me again....

I don't think I'm quite out of the woods yet 😬
I tried to deploy today with an increased instance count but the `AutoScalingTarget` failed with `ScalableTarget was not found.`

When I recreated the ECS service by hand I guess I left the autoscaling blank because I was basing it off test environment that doesn't have a scaling range.

What do you think is the best way to solve this?

- I could manually update the service and configure an autoscaling group. Manually messing with ECS makes me nervous now.
- My other idea is to remove the range from the manifest and set count to a fixed number, deploy, then set it back to a range and deploy again?

Do either of these methods sound reasonable or am I missing something more fundamental here?

Thanks again!

**Comment by efekarakus** [comment]
Hi @coopsmoss 👋 

My recommendation would be option 2 where you hard code `count` first and then recreate auto scaling. However, I suspect that the first time you remove auto scaling it's going to fail because suddenly CloudFormation won't be able to find the auto scaling group to delete.
If that happens, I think you can create the autoscaling group with the same name as what CloudFormation expects (https://docs.aws.amazon.com/cli/latest/reference/autoscaling/create-auto-scaling-group.html) you shouldn't need to connect it to your ECS service so it should be safe to manually create it. Afterwards, CloudFormation should be able to delete the resource, and you can set the `count`.

**Comment by coopsmoss** [comment]
Excellent! All went according to plan.
Thank you once again. :heart: 
I pray this be the end of this thread.
