### ISSUE TITLE
[Feature request] Build a private ALB

### ISSUE THREAD

**Issue by rverpillot** [aws/copilot-cli#3344]
We would like to use copilot to deploy some applications not accessible from the internet (only from our on-premise network).
But the ALB built by copilot use only the "internet-facing" scheme, and it's not possible to change this setup.

So, I currently testing a patch with this new feature. I added a new parameter to use during the environment creation: `copilot env init --private ...`. First tests are OK, but I need to look how to implement the https settings (no public domain, so no AWS certificate).

What do you think about this feature request ?

**Comment by iamhopaul123** [comment]
Related to https://github.com/aws/copilot-cli/issues/2961. Also may I ask the reason why you need a private ALB? Is it because service discovery is not good enough like it can't load balancing traffic? Thank you!

**Comment by rverpillot** [comment]
These applications will not be exposed on internet but they are still web applications with frontend and backend services. So we need a reverse proxy for TLS termination and to route http requests using rules.

**Comment by rverpillot** [comment]
#3319 might solve this use case.

**Comment by huanjani** [comment]
Q for those interested in this feature: 
Would you want
1. all resources within the VPC to have access to the internal load balancer, or
2. only Copilot services to have access?
Thanks!

**Comment by rverpillot** [comment]
We need an internal ALB to access frontend services from our on-prem network.

**Comment by efekarakus** [comment]
@rverpillot 

Does this mean the security group for the ALB needs to allow list a set of IP addresses? or is there some other way that you're thinking of for allowing ingress from on-prem

**Comment by rverpillot** [comment]
@efekarakus 

The current security group seems OK for me with inbound rules for 80 and 443 ports and source from 0.0.0.0/0 .

**Comment by huanjani** [comment]
This feature is now released in v1.19.0: https://github.com/aws/copilot-cli/releases/tag/v1.19.0! 🎉
