### ISSUE TITLE
integrate yaml script with  already authentication application using aws cognito application

### ISSUE THREAD

**Issue by 1Decoders** [aws/copilot-cli#3374]
how to integrate aws copilot yaml file script with already authentication aws cognito application

if there is a possible way to integrate aws copilot yaml file script with already authentication  application using aws cognito application

**Comment by huanjani** [comment]
Hello, @1Decoders!

You can use our [addons functionality](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/#how-to-do-i-add-other-resources) to integrate with AWS Cognito!

For reference check out this sample template by Copilot user @stefnpol: https://github.com/aws/copilot-cli/issues/2050#issuecomment-812838310. 

Hope that helps!

**Comment by 1Decoders** [comment]
Thanks huanjani

**Comment by huanjani** [comment]
You're welcome. I'm closing the issue for now; feel free to reopen it if you need more guidance or have more questions! Thank you!
