### ISSUE TITLE
`copilot svc deploy` receives 400 error when deploying to `eu-central-1` region

### ISSUE THREAD

**Issue by waltzofpearls** [aws/copilot-cli#3389]
I have a copilot app configured with 2 environments in `us-east-2` and `eu-central-1` regions. I've been using this setup for many months, but a few hours ago I started seeing deployments failures when deploying to `eu-central-1`. Please see the error below:

```
✘ execute "env upgrade --app api --name xxxxxx": get template version of environment xxxxxx in app api: get metadata for stack xxxxxx: get template summary: ValidationError: Template format error: Unrecognized resource types: [AWS::CloudFormation::CustomResource, AWS::CloudFormation::ManagedCustomResource, AWS::CloudFormation::UluruResourceV2]
	status code: 400, request id: f550c98a-08fa-4cf8-88f2-bb1b40bb53fa
```

I also tried manually updating the CloudFormation template in AWS web console under `eu-central-1` region, and I received the same 400 error:

![Screen Shot 2022-03-22 at 4 52 37 PM](https://user-images.githubusercontent.com/965430/159595464-9f1b608b-7f96-408b-b3b4-9f4d92cd22fd.png)

It looks like copilot's CloudFormation template is out of sync with some changes recently made in some AWS regions like `eu-central-1`. Currently my deployment only works in `us-east-2`, but the CD pipeline fails because it can't successfully deploy to all the regions.

Do you guys know if there is something going on in `eu-central-1`? And why the existing CloudFormation template stopped working during copilot deployment.

**Comment by Lou1415926** [comment]
hi @waltzofpearls ! This seems like a similar error with [this](https://github.com/aws/aws-sam-cli/issues/3768). Is this issue still happening today?

**Comment by waltzofpearls** [comment]
Hey @Lou1415926, thanks for sharing the issue that links to `aws-sam-cli` repo. It's working again! I tested this morning deploying to `eu-central-1` with `copilot svc deploy`. The error appeared yesterday didn't show up again and I was able to proceed to further steps. All good now :)
