### ISSUE TITLE
Cloudformation addon templates fail with S3 error: Access Denied after updating to 1.16.0

### ISSUE THREAD

**Issue by conorsibley** [aws/copilot-cli#3453]
We are using a Github v2 source step which requires ACLs be enabled on the artifact bucket and results in the owner of uploaded assets be the codepipeline user.  So, now when this step in the buildspec runs:
copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets

The resulting addons files have ACLs set that make them inaccessible to the cloudformation tasks that run on code deployment in other accounts and cause "S3 error: Access Denied" and the CF task to fail.

I you set "bucket-owner-full-control" on the S3 PUTs I think everything would work.

**Comment by huanjani** [comment]
Hello, @conorsibley! 

Thanks for opening this issue. Did your same workflow succeed prior to 1.16.0, without changing permissions?

**Comment by conorsibley** [comment]
Yes it did, but something else is going on that is the root of the permissions issue:  We have 2 pipelines with source stages that follow 2 different branches in the same repository and deploy to multiple different accounts.  They are sharing the same build artifact bucket and since the ADDONS files are being written to the root of the bucket, they keep overwriting each other.

1. PipelineA builds and deploys to s3://artifactbucket/ADDONS.yml (AddonsTemplateURL) and sets ACLS to allow for accounts targeted by PipelineA to s3:get
1. PipelineB builds and deploys to s3://artifactbucket/ADDONS.yml (AddonsTemplateURL) and sets ACLS to allow for accounts targeted by PipelineB to s3:get

Luckily the permissions failure occurred, otherwise we would have been having development and production pipelines sharing ADDONS CF Templates.

**Comment by conorsibley** [comment]
This is part of the codebuild output that illustrates the issue.  Notice for instance api.addons.stack.yml not having the env appended to the svc name:

[Container] 2022/04/13 11:45:59 Running command ls -lah ./infrastructure
--
939 | total 808K
940 | drwxr-xr-x 2 root root 4.0K Apr 13 11:45 .
941 | drwxr-xr-x 8 root root 4.0K Apr 13 11:34 ..
942 | -rw-r--r-- 1 root root  814 Apr 13 11:42 api-prod-au-1.params.json
943 | -rw-r--r-- 1 root root  27K Apr 13 11:42 api-prod-au-1.stack.yml
944 | -rw-r--r-- 1 root root  794 Apr 13 11:42 api-prod-us-1.params.json
945 | -rw-r--r-- 1 root root  27K Apr 13 11:42 api-prod-us-1.stack.yml
946 | -rw-r--r-- 1 root root  803 Apr 13 11:35 api-staging-us-1.params.json
947 | -rw-r--r-- 1 root root  27K Apr 13 11:35 api-staging-us-1.stack.yml
948 | -rw-r--r-- 1 root root 5.0K Apr 13 11:42 api.addons.stack.yml
949 | -rw-r--r-- 1 root root  819 Apr 13 11:43 auth-prod-au-1.params.json
950 | -rw-r--r-- 1 root root  25K Apr 13 11:43 auth-prod-au-1.stack.yml
951 | -rw-r--r-- 1 root root  799 Apr 13 11:42 auth-prod-us-1.params.json
952 | -rw-r--r-- 1 root root  25K Apr 13 11:42 auth-prod-us-1.stack.yml
953 | -rw-r--r-- 1 root root  808 Apr 13 11:37 auth-staging-us-1.params.json
954 | -rw-r--r-- 1 root root  25K Apr 13 11:37 auth-staging-us-1.stack.yml
955 | -rw-r--r-- 1 root root  13K Apr 13 11:43 auth.addons.stack.yml

**Comment by conorsibley** [comment]
And then from the other pipeline, api.addons.stack.yml is the same filename so it gets overwritten:

[Container] 2022/04/13 11:26:03 Running command ls -lah ./infrastructure
--
966 | total 320K
967 | drwxr-xr-x 2 root root 4.0K Apr 13 11:26 .
968 | drwxr-xr-x 8 root root 4.0K Apr 13 11:18 ..
969 | -rw-r--r-- 1 root root  791 Apr 13 11:19 api-dev-us-1.params.json
970 | -rw-r--r-- 1 root root  27K Apr 13 11:19 api-dev-us-1.stack.yml
971 | -rw-r--r-- 1 root root 5.0K Apr 13 11:19 api.addons.stack.yml
972 | -rw-r--r-- 1 root root  796 Apr 13 11:20 auth-dev-us-1.params.json
973 | -rw-r--r-- 1 root root  25K Apr 13 11:20 auth-dev-us-1.stack.yml
974 | -rw-r--r-- 1 root root  13K Apr 13 11:20 auth.addons.stack.yml

**Comment by huanjani** [comment]
Ah, thanks, @conorsibley, for surfacing this, and for the explanation. We apologize for this unexpected behavior!

We are figuring out how Copilot should handle this use case.
 
Meanwhile, could you possibly use [Mappings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) and [Conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html) in a shared/reused addons template to avoid this bucket clash? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#reuse

Hope that works for you!

**Comment by conorsibley** [comment]
I could work around a shared template, but the security issue will still block me.

**Comment by huanjani** [comment]
Can you try something for me? If it works, we'll implement a more fully-baked fix.
Can you go to your CloudFormation console and go into your application Stack ("StackSet-[appName]-infrastructure-...") and manually change your template to include
`AccessControl: BucketOwnerFullControl`
as a Property for `PipelineBuiltArtifactBucket`?

Let's see if that unblocks your security issue! 

Thanks for your patience!

**Comment by efekarakus** [comment]
Hi @conorsibley !

Apologies on the late response, we finally got to the root cause of this issue.

## Root cause
When `copilot` runs `svc package -n $svc -e $env --upload-assets`, it assumes the `EnvManagerRole` to upload assets such as the addons/ template to an S3 bucket.  
In your situation, the `EnvManagerRole` is in `accountA` while the S3 bucket is created in the application's account which is `accountB`.
When this happens, S3 has the following behavior:
> By default, when another AWS account uploads an object to your S3 bucket, that account (the object writer) owns the object, has access to it, and can grant other users access to it through ACLs.
> https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#CannedACL

Therefore, only `accountA` is allowed to read the uploaded addons file. This is the root cause of the bug! When the pipeline that tries to deploy to `accountB` tries reading the same addons file suddenly it doesn't have access to it.

## Action items
1. We should upload objects to S3 such that the owner of the objects is the bucket owner. Here is the diff for the fix that was tested: https://gist.github.com/efekarakus/47eea8ae3df2df8d4302208f5c539c7e
2. If the contents of the files are different, then they should be written under a different path. Addon files shouldn't override each other.

We'll address these items and report back here. Again, I'm really sorry for the inconvenience 🙇 If it's at all possible in the mean time `svc deploy` shouldn't have this problem until we have a fix for the pipeline

**Comment by conorsibley** [comment]
Thank you and looking fwd to the fix!

**Comment by huanjani** [comment]
@conorsibley: The fix is now released in v1.18.0: https://github.com/aws/copilot-cli/releases/tag/v1.18.0! Thanks so much for bringing the bug to our attention!

**Comment by ChaminW** [comment]
I'm getting the same error even with the v1.19.0. Do I need to change the old build spec as well?

Buildspec.yml
![image](https://user-images.githubusercontent.com/13014405/203269323-bfbabfca-b575-4699-a4f3-bc42e9105f20.png)
![image](https://user-images.githubusercontent.com/13014405/203269488-f7c0ca58-9769-4d48-95f3-2d4ffe345461.png)

**Comment by efekarakus** [comment]
Hi @ChaminW !
My recommendation is to use the latest version of Copilot: https://github.com/aws/copilot-cli/releases/tag/v1.23.0
in the buildspec and locally to help us trouble shoot the issue.

My hypothesis is that the action items should be similar to this: https://github.com/aws/copilot-cli/issues/3950#issuecomment-1279616485

1. If there is an [environment manifest](https://aws.github.io/copilot-cli/docs/manifest/environment/) in the repository, can you please run `copilot env deploy` using copilot v1.23, perhaps that will fix some IAM permission issue.
2. Then run `copilot app upgrade` to see if there are any changes that need to be applied to the S3 bucket.

Once the steps above are executed and the buildspec is updated to v1.23, can you try pushing a change again? hopefully these actions should have fixed the pipeline.

**Comment by ChaminW** [comment]
@efekarakus Thanks for the support. The issue was solved permanently with 
`copilot app upgrade` execution.
