### ISSUE TITLE
When I input one letter but got four in visual studio in vue files.

### ISSUE THREAD

**Issue by sotework** [aws/copilot-cli#3454]
env：
windows11
vs2022 folder mode
vue file in editor

When I input one letter but got four,
like I input ‘a’ got ‘aaaa’, ‘b’ got ‘bbbb’, ‘GetName’ got ‘GGGGeeeettttNNNNaaaammmmeeee’
我输入‘a’得到‘aaaa’，输入‘GetName’得到‘GGGGeeeettttNNNNaaaammmmeeee’
I tap Backspace well delete four letter.
我按Backspace删除的时候也会一次删除四个。

详细信息在这个链接里面，这个问题也是我提出的：
https://developercommunity.visualstudio.com/t/%E5%81%B6%E5%B0%94%E6%88%91%E8%BE%93%E5%85%A51%E4%B8%AA%E5%AD%97%E6%AF%8D%EF%BC%8C%E4%BD%86%E6%98%AF%E6%98%BE%E7%A4%BA%E4%BA%864%E4%B8%AA%EF%BC%8C%E5%83%8F%EF%BC%8CGetName--GGGGeeeet/10008186

**Comment by huanjani** [comment]
Hello, this is AWS Copilot, not GitHub Copilot. 
Looks like [this](https://github.com/github/feedback/discussions/categories/copilot-feedback) is the place to post your issue for them.
Good luck!

**Comment by sotework** [comment]
> Hello, this is AWS Copilot, not GitHub Copilot. Looks like [this](https://github.com/github/feedback/discussions/categories/copilot-feedback) is the place to post your issue for them. Good luck!

hahaha, sorry,  visual studio community give me this wrong page url. 
And, thank you.
