### ISSUE TITLE
Buildspec.yml file - Wrong path in pipeline Build Stage

### ISSUE THREAD

**Issue by mrveerachamy** [aws/copilot-cli#3468]
When I create new load balanced service using copilot on windows, the code build project's buildspec.yml file path contains wrong slash.

/copilot\pipelines\<pipeline-name>\buildspec.yml

Same is reflected in buildspec.yml file line 24 as follows.

- pipeline=$(cat $CODEBUILD_SRC_DIR/copilot\pipelines\<pipeline-name>\manifest.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')

**Comment by efekarakus** [comment]
Thanks @mrveerachamy for the bug report!
We'll look into fixing this 🙏

**Comment by huanjani** [comment]
@mrveerachamy: The fix is now released in v1.18.0: https://github.com/aws/copilot-cli/releases/tag/v1.18.0!

**Comment by ghena** [comment]
HI,
during some test using a pipeline on wsl windows, i have  strange error during build:

ODEBUILD_SRC_DIR=/codebuild/output/src1040373850/src
6 | [Container] 2024/04/21 20:07:01.544663 Phase complete: DOWNLOAD_SOURCE State: FAILED
7 | [Container] 2024/04/21 20:07:01.544682 Phase context status code: YAML_FILE_ERROR Message: stat /codebuild/output/src1040373850/src/copilot/pipelines/ecs-demo-php-simple-app-master/buildspec.yml: no such file or directory

the buildspec.yml is inside the source path so i think the whole  path is not correct.


I'm using copilot 1.33
