### ISSUE TITLE
Exporting the service's TaskRole and/or ExecutionRole in Cloudformation output for add-on importing.

### ISSUE THREAD

**Issue by matthewhembree** [aws/copilot-cli#3475]
**Request:**
I'd like a way to add an IAM policy to either the service's TaskRole and/or the ExecutionRole from an add-ons stack.

**Use Case:**
I have a collection of shared SSM parameters and SecretsManager secrets that I'd like to use in my all of my Copilot applications. Global values in the account. (e.g. third-party API keys, endpoint URLs, etc.) It doesn't make sense to add them (manually via `copilot secret init`) to every application * service * environment. Especially, since there would be no drift-detection/synchronization process. Either role would allow me access to the values at execution time (service `manifest.yml`) or runtime via AWS SDK.

**Proposal:**
One of the following to address my exact use case (and maybe more):

1. Add Cloudformation outputs/exports with the role names (or ARNs), so that I can import the value and ref/sub in my add-ons stack. Like [here](https://github.com/aws/copilot-cli/blob/e82c52d5f7f20927ceb8ea9c2f14f0be1700e1ef/internal/pkg/template/templates/workloads/services/lb-web/cf.yml#L292-L303).
2. Adopt an additional convention for tags and add it to a resourceTag policy in the [ExecutionRole](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/workloads/partials/cf/executionrole.yml) or [TaskRole](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/workloads/partials/cf/taskrole.yml).
3. Add a service manifest convention of `policies:` similar to [SAM allowing for attachment](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-policies) of managed or custom policies.

Proposal 1 would be the most extensible, allowing service developers to create any IAM policy for any AWS service and attach it to the desired role. This meets my `use case` and more broadly my `request`.
Proposal 2 is probably too opinionated/conventional and wouldn't allow for flexibility with undetermined resource types.
Proposal 3 is interesting as it pertains to the TaskRole, but I think separating it from the add-ons would break the helpful `ref/getatt/sub` functions that could be used to link least-privilege IAM policy to add-on resources.

Overall, I think proposal 1 allows for the most flexibility and would also serve to gather use cases for future higher level abstractions that could be built into the service manifest.

On the topic of exporting role names versus ARNs, I think the role name would be the most useful as the IAM policy could be centrally attached to the role, rather than distributed with a resource policy. The ARN could be easily interpolated from the service name, if necessary.

**Workaround (potential):**
I could try to create a new named role and IAM policy in an add-on stack and assume that role at runtime before retrieving the values via the AWS SDK. I'm not sure how the trust policy would work though. I'd probably need the TaskRole ARN as the principal (instead of `ecs-tasks.amazonaws.com`) in the trust policy of my new add-on role, which brings me back to the Cloudformation outputs/exports in proposal 1.

**Conclusion:**
If there's something that already exists and I'm completely missing it, let me know.
.
.
Thanks!

**Comment by Lou1415926** [comment]
Hello @matthewhembree ! In addon stack, if you define an IAM policy and output it, Copilot will automatically add the IAM policy to the task role. [Here](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/#connecting-addon-resources-to-your-workloads) are more information. Would this work for your usecase?

**Comment by matthewhembree** [comment]
Yes @Lou1415926 , that will work! That's perfect.

Thanks for pointing that out. I was wondering if I was missing something obvious.
