### ISSUE TITLE
Help with healthcheck configuration for Backend Service

### ISSUE THREAD

**Issue by ampiy** [aws/copilot-cli#3490]
I am facing issues with configuration for healthcheck for Backend Services. Whatever healthcheck commands I write, it fails. However, without the healthcheck everything works fine.

Here's the repo link for the service: https://github.com/ampiyofficial/aws-copilot-nodeapp-microservice

Current Configuration:

       App Name:  test-copilot-app
       Env: test
       Backend Service Name: nodeapp
       Backend Service Port: 10000

Commands in Healthcheck I have tried:

       - command: ["CMD-SHELL", "curl -f http://localhost:10000 || exit 1"] 
       - command: ["CMD-SHELL", "curl -f nodeapp.test.test-copilot-app.local:10000 || exit 1"] 

I even added path based healthcheck that also failed.

Any suggestions on what would be the correct healthcheck command?

**Comment by efekarakus** [comment]
Hi @ampiy !

My guess is that `curl` needs to be installed in the Dockerfile: https://github.com/ampiyofficial/aws-copilot-nodeapp-microservice/blob/main/nodeapp/Dockerfile and that might be why the healthchecks are not able to run.

My hypothesis is that adding the following should hopefully unblock you:
```
RUN apk --no-cache add curl
```

**Comment by ampiy** [comment]
> Hi @ampiy !
> 
> My guess is that `curl` needs to be installed in the Dockerfile: https://github.com/ampiyofficial/aws-copilot-nodeapp-microservice/blob/main/nodeapp/Dockerfile and that might be why the healthchecks are not able to run.
> 
> My hypothesis is that adding the following should hopefully unblock you:
> 
> ```
> RUN apk --no-cache add curl
> ```

Bummer. That was infact the issue. Thanks that solved it. !
