### ISSUE TITLE
copilot svc exec

### ISSUE THREAD

**Issue by afgallo** [aws/copilot-cli#3491]
When I run the above command, I get prompted to update the SSM plugin version. If I select Yes, I get the below error:

> copilot svc exec
Looks like the Session Manager plugin is using version 1.2.245.0.
Would you like to update it to the latest version 1.2.312.0? Yes
Archive:  /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle.zip
   creating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/
  inflating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/install
  inflating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/THIRD-PARTY
  inflating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/seelog.xml.template
  inflating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/LICENSE
   creating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/bin/
  inflating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/bin/session-manager-plugin
  inflating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/NOTICE
  inflating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/README.md
  inflating: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/RELEASENOTES.md
 extracting: /var/folders/dh/92b7pdgn0_92rw436v2n6slw0000gn/T/ssmplugin3399249093/sessionmanager-bundle/VERSION
Password:
env: python: No such file or directory
✘ update ssm plugin: exit status 127

I can run **python** successfully so not sure what's causing this?

**Comment by Lou1415926** [comment]
Hello @afgallo ! This seems to be an error that happened when running
```
sudo path/to/sessionmanager-bundle install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
```
to finish the installation. Could it be that it's looking for `python` while you have `python3`? What is your OS?

An alternative way is to install/upgrade the ssm plugin manually by yourself: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html. This is exactly the steps that Copilot is following.

**Comment by afgallo** [comment]
> to finish the installation. Could it be that it's looking for python while you have python3? What is your OS?

I'm on a Mac and have added an alias python=python3

I will try and do it manually, thanks @Lou1415926

**Comment by afgallo** [comment]
I'm still struggling with this, I got the same error when running it manually which indicates I have a problem in my local env.

> ➜ sudo ./sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
env: python: No such file or directory

I think I've installed python3 via `homebrew` on my mac. Should I remove python3 and install python again?

**Comment by iamhopaul123** [comment]
> I think I've installed python3 via homebrew on my mac. Should I remove python3 and install python again?

Looks like the system default version of Python is not compatible. It might be helpful to do that. Alternatively, you can specify the location of where the session manager plugin to install. For example,

```
sudo /usr/local/bin/python3.6 sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
```

I referred to https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html#install-plugin-macos

**Comment by afgallo** [comment]
I managed to fix this by uninstalling python3 and installing the default image back to MacOs. Thanks for your help!
