### ISSUE TITLE
Passing in secrets for task run

### ISSUE THREAD

**Issue by dmathewwws** [aws/copilot-cli#3500]
Hi, 

Running into an issue with how to set up a task. This is what I had:

```
copilot task run --app APPNAME --env ENVNAME -n db-migration --dockerfile Dockerfile --secrets DB_PASSWORD=/copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/DB_PASSWORD
```

And this is the error I run into:
```
✘ It looks like your task is not able to pull the secrets.
Did you tag your secrets with the "copilot-application" and "copilot-environment" tags?
✘ run task db-migration: run task db-migration: ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm: service call has been retried 1 time(s): AccessDeniedException: User: arn:aws:sts::XXX:assumed-role...
```

Am I supposed to be passing in the secrets in another format?

**Comment by iamhopaul123** [comment]
Hello @dmathewwws could you check if the secret is tagged with
```
"copilot-application": APPNAME
"copilot-environment": ENVNAME
```

Thank you!

**Comment by dmathewwws** [comment]
hey @iamhopaul123 I'm not sure what you mean.

The secret is in the format `DB_PASSWORD=/copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/DB_PASSWORD`

I've taken if from my manifest.yml file. Am I supposed to replace COPILOT_APPLICATION_NAME &  COPILOT_ENVIRONMENT_NAME with APPNAME and ENVNAME?

**Comment by dmathewwws** [comment]
Ah, I think I understand what you mean. 

Yes, when I go to Parameter Store -> the secret -> tags. I see it tagged properly:

```
"copilot-application": APPNAME
"copilot-environment": ENVNAME
```

**Comment by iamhopaul123** [comment]
Hello @dmathewwws. Are the "APPNAME" and "ENVNAME" the same ones as you had when you ran `task run` command?

**Comment by dmathewwws** [comment]
hey @iamhopaul123 not sure I understand your question. Same ones as what?

**Comment by iamhopaul123** [comment]
So just wanted to double check if
```
copilot task run --app APPNAME --env ENVNAME -n db-migration --dockerfile Dockerfile --secrets DB_PASSWORD=/copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/DB_PASSWORD
```
the `APPNAME` and the `ENVNAME` you specified here are the same ones as 

```
"copilot-application": APPNAME
"copilot-environment": ENVNAME
```
otherwise the error doesn't make sense for me, unless the profile you ran `copilot task run` is not the same account/region as where the secret exists 🤔

**Comment by dmathewwws** [comment]
oh boy, it was that I used /copilot/${COPILOT_APPLICATION_NAME}/${COPILOT_ENVIRONMENT_NAME}/secrets/DB_PASSWORD instead of filling in the correct values.

thanks for the help.
