### ISSUE TITLE
 github copilot: the github server is unable to work with this version of the plugin 

### ISSUE THREAD

**Issue by gezmi** [aws/copilot-cli#3511]
Hi,

Recently my PyCharm was updated to 2022.1 and a dew days after, I started getting this error:
The GitHub server is unable to work with this version of the plugin. Completions will be turned off until the next restart. Please update to the latest version.

I checked for update and restarted the IDE but it was not resolved, I am unable to use CoPilot. It shows the notification for installing the new copilot again. What could be the problem?

Thank you!

**Comment by iamhopaul123** [comment]
Hello, this is AWS Copilot, not GitHub Copilot. 
Looks like [this](https://github.com/github/feedback/discussions/categories/copilot-feedback) is the place to post your issue for them.
Good luck!
