### ISSUE TITLE
Progress output from delete commands

### ISSUE THREAD

**Issue by FraserThompson** [aws/copilot-cli#3625]
The deploy commands seem to do a good job of telling us what's happening, but the delete commands just stick with the high-level "Deleting environment x from application y".

This makes it very hard to debug when something is stuck (my `app delete` command has been running for an hour and I can't tell why).

A flag to provide more useful output might help, or just mirroring the behaviour of the deploy command where it provides you with updates on what's happening as it goes.

**Comment by efekarakus** [comment]
Thanks @FraserThompson, the feature request makes a lot of sense!

**Comment by efekarakus** [comment]
Hi @FraserThompson !

We merged #3854 that displays showing detailed events for each stack being deleted, it should go out next release 🚀

**Comment by dannyrandall** [comment]
This feature is now released in v1.21.0! https://github.com/aws/copilot-cli/releases/tag/v1.21.0 🎉 Thanks for the suggestion @FraserThompson!
