### ISSUE TITLE
Service Discovery - Private Backend Service - Route53

### ISSUE THREAD

**Issue by reddotzach** [aws/copilot-cli#3649]
I am setting up a backend service with copilot, however, I am receiving a `SERVFAIL` from dig (inside VPC):

```
dig SERVICE.ENV.APP.local

; <<>> DiG 9.16.1-Ubuntu <<>> SERVICE.ENV.APP.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 1473
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;SERVICE.ENV.APP.local. IN A

;; Query time: 3 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Jun 09 15:45:12 UTC 2022
;; MSG SIZE  rcvd: 76
```

I see in the AWS docs that subdomain delegation doesn't resolve, https://aws.amazon.com/premiumsupport/knowledge-center/route-53-fix-dns-resolution-private-zone/:

> Confirm that there's no zone delegation configured in the private hosted zone
Private hosted zones don't support zone delegation. If delegation is configured, the client gets the "Servfail" response code from the VPC resolver.
Use the AWS CLI to confirm that zone delegation isn't configured in the private hosted zone. For example:
Private hosted zone:abc.com Delegation NS record for: kc.abc.com Resource record: test.kc.abc.com
[ec2-user@ip-172-31-0-8 ~]$ dig test.kc.abc.com
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 63414
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;test.kc.abc.com        IN      A
;; Query time: 15 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Fri Apr 16 15:57:37 2021
;; MSG SIZE  rcvd: 48

I have this in my manifest.yml to keep my service private:

```
network:
  vpc:
    placement: private
```

Is there a concept that I'm missing with connecting with my instance? Is there something additional I need to setup?

**Comment by paragbhingre** [comment]
@reddotzach Thank you for reporting this issue. 

May I know how did you configure your backend service and what all commands you ran before `copilot svc deploy`?
Also, did you use default configuration to create an environment or import an existing VPC?

**Comment by reddotzach** [comment]
Thank you for taking some time to work with me on this.

I am using an existing VPC and manually created public/private subnets, NAT gateway, and internet gateway. I have checked that the VPC has `enableDnsHostnames` and `enableDnsSupport` set to true. My NAT gateway is setup similar to this https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-scenarios.html#public-nat-internet-access to pull secrets off of ASM. I am able to reach my backend service by way of IP address inside the VPC from an EC2 instance.

I initialized the app with these commands:
``` 
# Run through the prompts to setup app and backend service 
copilot init

copilot env init -a APPNAME -n staging --region REGION --import-private-subnets subnet-XXX,subnet-XXX --import-public-subnets subnet-XXX,subnet-XXX  --import-vpc-id vpc-XXX
```

I stripped out that `placement: private` with no help. My manifest is very simple with no explicit networking items other than port setting the port to non-HTTP(s).

I have a working load balanced service; however, I get the same DNS issues if I attempt to call the `.local` address from within the VPC. 

Is there some dig commands that would be helpful to debug this?

**Comment by paragbhingre** [comment]
Does your hosted zone contains DNS record entry for the `.local` (domain/subdomain) with the appropriate `Route traffic to` rules?

You can also use few following commands for troubleshooting - 

NS responsible for your domain - `dig NS local +short`
To check the delegation path to your DNS zone - `dig .local +trace`

**Comment by reddotzach** [comment]
It looks like everything is setup in Route53 and CloudMap:

```
staging.redline-payments.local | NS | Simple | - | ns-1536.awsdns-00.co.uk.ns-0.awsdns-00.com.ns-1024.awsdns-00.org.ns-512.awsdns-00.net.
-- | -- | -- | -- | --
  | staging.redline-payments.local | SOA | Simple | - | ns-1536.awsdns-00.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
  | app.staging.redline-payments.local | A | Multivalue answer | - | 172.20.25.85
  | app.staging.redline-payments.local | SRV | Multivalue answer | - | 1 1 8080 e75447605ab544da9e520c28a7749fab.app.staging.redline-payments.local.
  | e75447605ab544da9e520c28a7749fab.app.staging.redline-payments.local | A | Multivalue answer | - | 172.20.25.85
```

Here is the response from those commands:

```
$ dig NS local +short # No output
$ dig local +trace

; <<>> DiG 9.16.1-Ubuntu <<>> local +trace
;; global options: +cmd
.                       48      IN      NS      a.root-servers.net.
.                       48      IN      NS      b.root-servers.net.
.                       48      IN      NS      c.root-servers.net.
.                       48      IN      NS      d.root-servers.net.
.                       48      IN      NS      e.root-servers.net.
.                       48      IN      NS      f.root-servers.net.
.                       48      IN      NS      g.root-servers.net.
.                       48      IN      NS      h.root-servers.net.
.                       48      IN      NS      i.root-servers.net.
.                       48      IN      NS      j.root-servers.net.
.                       48      IN      NS      k.root-servers.net.
.                       48      IN      NS      l.root-servers.net.
.                       48      IN      NS      m.root-servers.net.
;; Received 262 bytes from 127.0.0.53#53(127.0.0.53) in 0 ms

.                       86400   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2022061000 1800 900 604800 86400
.                       86400   IN      RRSIG   SOA 8 0 86400 20220623050000 20220610040000 47671 . e5mCOj3SHpafZuAeJUIl0F6vMIMjSx00zM2cjNfMN+iUsZIT3lLWpC7D 6/gD2qB9ZdVU12jCFhQ0oS4Le3i+N+s/k/24oEzTLpQrhPh+z7Fyg8vd CwKpVjU3HAsLlKQAJDC90zYVuq8lJSOzDMHVeN8xSTOzsJKfn35/3Ztk fHrBM+iupYgVRordgV5+Q8D1eCNRw3IljtU/c6eHJHPcoqYOIM4kurfx BVVLJ/qKc4cxgjlMG0fL1zxQ5k5wsz/fz5z4mz2aW2d+8ThS954QZJdB QNVHILqmrtcSKsLsh6vQd2F3xuM9qo3EPhnWlvObrstYUTO4DlqVOTzZ inPSiA==
.                       86400   IN      NSEC    aaa. NS SOA RRSIG NSEC DNSKEY
.                       86400   IN      RRSIG   NSEC 8 0 86400 20220623050000 20220610040000 47671 . JBQucTGIsEKQ6gfvBq6aSKCtJGqZTGV0QAQlbjt2waEXTj4lw8UTXXsh f4iO1u5aT8JT/0cC3zdkf8SsqoxKrwCd/gJpigLNs2dW6IyCw/VGfNsN XD79bRfrtkVBbZddlHd6vqU//W19NTq7jJXJ3QJmD4u/JnUgGPtc9Ud1 CoY4VYUhqp4h8iW8XB9YOOHU7Hz7pQro/EX5+9Kh3GkwSFXLVItMmq+O 3SkkTWNKCj8AsOTBsjhu/RrKWW3VJZbgSrO61upA47XEzQawIE4fyRlq pkzeB9G9lBNE08sWs850rAr8pZkRJGEfJptpdOv2MStSsujayqvuoG8Q gLVfDQ==
loans.                  86400   IN      NSEC    locker. NS DS RRSIG NSEC
loans.                  86400   IN      RRSIG   NSEC 8 1 86400 20220623050000 20220610040000 47671 . cBRQu2rlDwEJaxYGPauHZutzNrErIdO287Vekpd5n2l4LL1U3gC0G5rt 3DscNL9KDREbIz58l2jcc9m/DzYSa3lExA7EuFwHYJAhZJm2/1N+i33G Y2ZSpSXy0sUzjNazfKxuSJI/EZga0AzvbYGI/LG0OSM/AVH4+ornhM4r RrBFDrcCGJw1YHK8CSn3CB0YSSvqp+n3g67DYe0Q82wSjhNQp1Svz7fj VsVYjG9V55/RuW+DHCawvaL6HoyIbhvF0l9UqYj9lSl+aPnZc5jcxPsl ck2VxvevBGkaNPgso7CDbPIs6GQJxtNXnpxhe7701eJ/jMBwnQcApIQO kuh9JQ==
;; Received 1054 bytes from 192.112.36.4#53(g.root-servers.net) in 55 ms
```

**Comment by reddotzach** [comment]
I get this from `system-resolve --status`

```
Link 2 (eth0)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 172.20.0.2
         DNS Servers: 172.20.0.2
          DNS Domain: red.lan
```

**Comment by reddotzach** [comment]
Prolly this `red.lan` thing, I'll dig in there. There are a bunch of routes in Route53 referencing it. If you have a quick fix off the top of your head, let me know; otherwise I'll ping you if I can't get anywhere.

**Comment by reddotzach** [comment]
Thank you for your assistance. The issue was an improperly configured EC2 instance calling the newly created Copilot instance.

**Comment by roharvey** [comment]
I struggled with this for a while, because I was doing service discovery with an Ubuntu 20.04 server. It seems like by default they are set up to ignore .local queries.

```
$ dig app.test.demo.local

; <<>> DiG 9.16.1-Ubuntu <<>> app.test.demo.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 52846
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;app.test.demo.local.	IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Apr 25 06:50:11 UTC 2023
;; MSG SIZE  rcvd: 53

```

But this works if you provide the AWS nameserver directly (avoiding the stub method):
```
$ dig @169.254.169.253 app.test.demo.local

; <<>> DiG 9.16.1-Ubuntu <<>> @169.254.169.253 app.test.demo.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2389
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;app.test.demo.local.	IN	A

;; ANSWER SECTION:
app.test.demo.local. 10	IN	A	1.2.3.4

;; Query time: 4 msec
;; SERVER: 169.254.169.253#53(169.254.169.253)
;; WHEN: Tue Apr 25 06:53:05 UTC 2023
;; MSG SIZE  rcvd: 69

```

There are several possible solutions, I used a shorthand approach to remove the stubbed version of resolution.
```
sudo rm /etc/resolv.conf
sudo ln -s /run/systemd/resolve/resolv.conf /etc/
```

However since I needed this for a haproxy load balancer, I just needed to specify the VPC + 2 address in the resolvers section of the haproxy config for my longer term solution.

More info on the DNS setup for VPCs is at https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#AmazonDNS
