### ISSUE TITLE
[Feature] Import certificates into existing environments

### ISSUE THREAD

**Issue by FraserThompson** [aws/copilot-cli#3652]
It's a bit of a hassle to have to delete and create an environment to add new certificates via `--import-cert-arns`.

An example scenario: We have a Copilot application for our customer website and we expand regions, so now we want to add another domain. To do this with Copilot (without Route53) currently would involve creating a new environment, deploying new services into the new environment, pointing DNS at the new services, and then deleting the old environment. This is quite a complex procedure which could involve some form of downtime.

Therefore I would like a way to import certificates into existing environments.

**Comment by paragbhingre** [comment]
Thanks @FraserThompson, this feature makes sense. We are going to work towards introducing [env manifest](https://github.com/aws/copilot-cli/issues/3522) which will take care of your requirement as it will allow you to set `--import-cert-arns` in the env manifest for the existing environment.

**Comment by gleidin** [comment]
@paragbhingre is there a workaround for that now? So I can unblock my deployment here, I missed that feature as well 😄

**Comment by Lou1415926** [comment]
Hello @gleidin ! Unfortunately I can't think of a great workaround at this moment :(... 

I think it is possible to do it by manually modifying some resources, but this will introduce resource drift, and is not guaranteed to work nicely with the upcoming env manifest: when you modify your env manifest and run `copilot env deploy`, CFN likely will override some of the changes you've made manually. Besides, manual modification involved in this can be quite complicated. However, if you're in a hurry, I'm happy to explore with you on whether we can & how to do this!

If creating a new environment is acceptable to you, this will be a better workaround too!

**Comment by gleidin** [comment]
> Hello @gleidin ! Unfortunately I can't think of a great workaround at this moment :(...
> 
> I think it is possible to do it by manually modifying some resources, but this will introduce resource drift, and is not guaranteed to work nicely with the upcoming env manifest: when you modify your env manifest and run `copilot env deploy`, CFN likely will override some of the changes you've made manually. Besides, manual modification involved in this can be quite complicated. However, if you're in a hurry, I'm happy to explore with you on whether we can & how to do this!
> 
> If creating a new environment is acceptable to you, this will be a better workaround too!

Wow, thanks for the quick answer. I am going to change the resource manually by now, it's not the ideal manner and probably is going to block further deployments, but at least it works (and we can watch over the env)!  I will stick to this post to receive news.

I really appreciate the work you guys are doing, it is getting pretty amazing the CLI. Thanks!

**Comment by efekarakus** [comment]
This feature is now possible with environment manifest in v1.20 🚀 
Release notes: https://github.com/aws/copilot-cli/releases/tag/v1.20.0 !
Blog post: https://aws.github.io/copilot-cli/blogs/release-v120/

**Comment by gpmcadam** [comment]
FYI this shows up as the top result when searching for this issue and as suggested above it is now available since v1.20

Something to note though if you're struggling is that after adding the certificate ARN to the environments manifest, ensure you redeploy the env first using `copilot env deploy`, after which you can then add options to your service manifest such as  domain aliases and `redirect_http_to_https`, otherwise it will complain you haven't imported the certs yet.
