### ISSUE TITLE
spring cloud config uri in manifest.yml of aws copilot

### ISSUE THREAD

**Issue by yasinkayade** [aws/copilot-cli#3653]
Hi,

I have to create a small project fetching docker image of a spring boot project from a private artifactory and deploying it on AWS ECS. My project has no spring boot, maven or gradle, but only gitlab-ci.yml and manifest.yml. However, I have to add a config server uri to it in order to source some config files from git repo.
Can I use SPRING_CLOUD_CONFIG_URI directly in the manifest file as variable? Or how can I put it in the project?

**Comment by paragbhingre** [comment]
@yasinkayade 
Thank you for reaching out to us. 

You can use SPRING_CLOUD_CONFIG_URI as variable in your manifest. There are different ways how you can add a variable to your project. Here are some resources on environment variables 

- https://aws.github.io/copilot-cli/docs/developing/environment-variables/
- https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/

Please let us know if you have anymore questions.

**Comment by yasinkayade** [comment]
Thank you @paragbhingre .
I have another issue. When deploying the service to ECS I get "403 Forbidden". 
Manifest.yml file includes:
image:
     location: docker_image_url_in_private_artifactory
     port: 8080

Can I add user name and password (private artifactory provides with) under image or another place? And with which specific variable names can I add them?
Thanks in advance.

**Comment by iamhopaul123** [comment]
Hello @yasinkayade. Just to double check: do you need user name and password in your application code? If so, you could do `copilot secret init` to create secrets for your password (and user name if you want) and then follow the prompt to add it to the manifest. Something like

```yaml
secret:
  foo: bar
```
Also see our docs regarding secrets [here](https://aws.github.io/copilot-cli/docs/developing/secrets/).

For your user name you could either add it as a secret the same as your password. Alternatively it can be added as an env var as plain text. For example in your workload manifest:

```yaml
variables:
  USER_NAME: xyz
```

**Comment by yasinkayade** [comment]
Thank you @iamhopaul123,
I need credentials to fetch the docker image. AFAIK from https://github.com/aws/copilot-cli/issues/2101, there is a parameter with the name credentials (under image) to store in secretsmanager and use them. So the image part of manifest.yml:
```
image:
  credentials: arn:aws:secretsmanager:…….  /* username and password*/
  location: location_of_docker_image_in_jfrog_artifactory
  port: 8080
```

But I still get 403 Forbidden. Because I need a static IP or a certificate in order to be able to fetch the image from private artifactory because of security issues. I would ask how to create a static IP or how to put the certificate into manifest.yml file (or to put to secretsmanager and refer in manifest.yml file)?

BR,

**Comment by yasinkayade** [comment]
I asked it as a new issue (https://github.com/aws/copilot-cli/issues/3787).
