### ISSUE TITLE
Bug Bash Feedback: archer init fail on Windows - git bash

### ISSUE THREAD

**Issue by srrengar** [aws/copilot-cli#366]
archer init fails with an incorrect function error on prompt on git bash on Windows

![image](https://user-images.githubusercontent.com/30325699/68973527-5ed06200-07a3-11ea-9741-b9e5cf9675b6.png)

**Comment by sonofachamp** [comment]
https://github.com/AlecAivazis/survey/issues/148

**Comment by efekarakus** [comment]
We fixed the UX for the CLI on Windows! Closing the issue.
