### ISSUE TITLE
Bug Bash Feedback: Powershell repeats the output of the environment creation

### ISSUE THREAD

**Issue by srrengar** [aws/copilot-cli#369]
The progress gets printed again each time there is an update

![image](https://user-images.githubusercontent.com/30325699/68974452-a3f59380-07a5-11ea-94cd-0b2996da4377.png)

![image](https://user-images.githubusercontent.com/30325699/68974409-8fb19680-07a5-11ea-9dcc-64bbe3de8628.png)

**Comment by efekarakus** [comment]
Ok I just tested this out on windows and it's still a bug!

**Comment by efekarakus** [comment]
We fixed this in the CLI! this was occurring because the cursor on Window is upside/down compared to Linux/macOS. See: https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/term/cursor/vertical_windows.go
