### ISSUE TITLE
copilot task run doesn't fill in secrets and variables from manifest.yml

### ISSUE THREAD

**Issue by h4sh5** [aws/copilot-cli#3693]
When I run `copilot task run` to say, test a scheduled job outside of its schedule, it doesn't actually use the secrets and variables I defined in the manifest.yml file.

For example, if I have a dockerfile to just run `env`:

```
FROM alpine:3.14
CMD 'env'
```

I do not see my secrets and variables output in the logs. I also verified that the environment variables section is empty in the ECS task definition created for that task run, but is populated for the task def created by `copilot job deploy`.

I think `task run` and `job deploy` should be consistent (both follow manifest.yml), or `task run` should have an option to use the manifest file?

**Comment by efekarakus** [comment]
Hi @h4sh5 !

Apologies for the late response 🙇 

> it doesn't actually use the secrets and variables I defined in the manifest.yml file.

Would you mind showing a sample snippet of how you're running `task run`? Like you mentioned today there is no way of using a manifest file for the `task run` command.
If you'd like to use secrets and variables for running a one off task, you can execute the following command:
```
$ copilot task run --env-vars k1=v1,k2=v2 --secrets s1=arn:aws:secretsmanager:us-west-2:111122223333:secret:aes128-1a2b3c
```
**Does this help mitigate the request?**

> I think task run and job deploy should be consistent (both follow manifest.yml), or task run should have an option to use the manifest file?

That request makes sense to me, if I'm following it correctly you'd like to re-use the manifest for a `type: Scheduled Job` to just trigger the job. Is that correct?

If so, a contributor @kangere 🤩 has created the following PR: https://github.com/aws/copilot-cli/pull/3692 `copilot job run` which will allow to trigger the scheduled job and reuse the manifest

**Comment by h4sh5** [comment]
Yep - I am just using `task run` as `copilot task run -e envname --app appname`, not adding any `--secrets` etc. (because I thought they would use the manifest)

#3692 looks awesome and that's exactly what I'm looking for - happy to wait for that to drop. In the meantime, thanks for that example command to add secrets in! Definitely helps with testing.
