### ISSUE TITLE
Allow adding VPC flow logs in environments

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#3721]
## Ask

> VPC Flow Logs is a feature that enables you to capture information about the IP traffic going to and from network interfaces in your VPC. Flow log data can be published to Amazon CloudWatch Logs or Amazon S3. After you create a flow log, you can retrieve and view its data in the chosen destination.

We should make it possible to enable VPC flow logs in environments with the environment manifest. Example CFN resource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-flowlog.html#aws-resource-ec2-flowlog--examples

### Sample manifest

```yaml
network:
  vpc:
    flow_logs: on
```

**Comment by huanjani** [comment]
This feature is now released in v1.23.0: https://github.com/aws/copilot-cli/releases/tag/v1.23.0! 🎉
