### ISSUE TITLE
Using docker buildx in copilot pipeline with CodeBuild

### ISSUE THREAD

**Issue by cykhoo0108** [aws/copilot-cli#3742]
Hi,

I would like to leverage docker build --target to specify the build steps for different environment in dockerfile.
However I'm not able to find a way to make it by using copilot with pipeline.
Is there any way to make this happen?

**Comment by huanjani** [comment]
Hello, @cykhoo0108!

"Classic" Docker builds stages up through the stage indicated by `--target`. (See https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage.) However, Docker BuildKit skips unnecessary build stages. To enable Docker BuildKit, set the `DOCKER_BUILDKIT=1` environment variable in your workload manifest.

```
variables:
  DOCKER_BUILDKIT: 1
```

Thanks!

**Comment by cykhoo0108** [comment]
Hi, this is helpful. My issue is solved. Thanks a lot
