### ISSUE TITLE
task is failing due to loadbalancer

### ISSUE THREAD

**Issue by deeptirajput2** [aws/copilot-cli#3772]
Hi,

I am getting below error while deploying frontend service as load balancer service.

✘ Latest failure event                                                                 
      - (service corpdirectory-test-rasaos-Service-T8qsKYiLhGmT) (port 5005) i                              
        s unhealthy in (target-group arn:aws:elasticloadbalancing:ap-south-1:3                              
        77727317375:targetgroup/corpd-Targe-12YF9HTH1OJGJ/e938d1c7734d02a2) du                              
        e to (reason Health checks failed).

**Comment by huanjani** [comment]
Hi @deeptirajput2!

Let's see if we can get a little bit more information about the nature of the health check failure. Would you mind following the instructions [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html#check-target-health) to see if we can find out more? 
Also, you could try adding a little cushion to the health checks by adjusting some of the values [here](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck). 

Keep us posted! Thanks!

**Comment by deeptirajput2** [comment]
Hi,

It is working now after I added health check port 5005 in config file.
