### ISSUE TITLE
Partition "aws" is not valid for resource error on china region

### ISSUE THREAD

**Issue by comdaze** [aws/copilot-cli#3844]
$ copilot -v
copilot version: v1.20.0

error infor:

$ copilot env init --name test --profile default --default-config
✔ Manifest file for environment test already exists at copilot/environments/test/manifest.yml, skipping writing it.
✔ Linked account 45637028xxxx and region cn-northwest-1 to application ecsworkshop.

✔ Proposing infrastructure changes for the ecsworkshop-test environment.
- Creating the infrastructure for the ecsworkshop-test environment.                  [rollback complete]  [31.1s]
  The following resource(s) failed to create: [EnvironmentManagerRole].                                   
  Rollback requested by user.                                                                             
  - An IAM Role for AWS CloudFormation to manage resources                           [delete skipped]      [9.9s]
  - An IAM Role to describe resources in your environment                            [delete skipped]     [0.5s]
    Partition "aws" is not valid for resource "arn:aws:states:cn-northwest                                
    -1:45637028xxxx:stateMachine:ecsworkshop-test-*". (Service: AmazonIden                                
    tityManagement; Status Code: 400; Error Code: MalformedPolicyDocument;                                
     Request ID: 48b5aabd-7498-400e-b900-1eabe7eaf704; Proxy: null)

**Comment by iamhopaul123** [comment]
Hello @comdaze. Thank you for finding the issue. Just sent out a fix for that and it should be included in our next release.

**Comment by dannyrandall** [comment]
This fix is now released in v1.21.0! https://github.com/aws/copilot-cli/releases/tag/v1.21.0 Thanks @comdaze for reporting this issue!
