### ISSUE TITLE
Update Manifest for Existing Service

### ISSUE THREAD

**Issue by rishindoshi** [aws/copilot-cli#3873]
Hello! I'm quite new to Copilot and I just created an application & service with `copilot init`.  There's quite a bit of configuration I'd like to change in the `manifest.yml` file, so I was wondering what I would run for changes in the manifest to take effect within my cloud service?

Thanks in advance!

**Comment by paragbhingre** [comment]
Hi @rishindoshi,
Once you are done making changes in your service manifest then you can simply run 
`copilot svc deploy --name <serviceName> --env <environmentName>`
and the new changes in your manifest will take effect after deployment is successful. 

Please let us know if you have any more questions.

**Comment by paragbhingre** [comment]
I hope you were able to successfully deploy your service. Please feel free to reopen this issue if you have any more questions.
