### ISSUE TITLE
lambda runtime nodejs12.x deprecation

### ISSUE THREAD

**Issue by dclark** [aws/copilot-cli#3896]
Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 

As of November 14, 2022, Lambda will no longer apply security patches, starting December 14 2022 existing functions cannot be updated.

**Comment by dannyrandall** [comment]
This is now released in v1.21.0: https://github.com/aws/copilot-cli/releases/tag/v1.21.0! Thanks @dclark for contributing!😊
