### ISSUE TITLE
Copilot manifest cache_from not working

### ISSUE THREAD

**Issue by hellolennert** [aws/copilot-cli#3919]
I have a backend service based on a docker file in my solution that looks like this:

```
name: app
type: Backend Service

image:
  build:
    dockerfile: app/Dockerfile.prod
    cache_from:
      - xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx-copilot/app:latest

```

But when building it does not use cache, always just rebuilding Dockerfile.prod.

```
  | 2022-08-18T16:15:54.493+02:00 | Sending build context to Docker daemon 72.67MB
  | 2022-08-18T16:15:54.493+02:00 | Step 1/60 : ARG PYTHON_IMAGE=public.ecr.aws/bitnami/python:3.9.13-debian-11-r33@sha256:e8152fa800d27ec38f6603fb407b4a2ece1f78b9ef471a3ab7442a150dad6005
  | 2022-08-18T16:15:54.493+02:00 | Step 2/60 : ARG NODE_IMAGE=public.ecr.aws/bitnami/node:18.7.0-debian-11-r7@sha256:9922f13c394983ffd638e3cf5178acf477dff470bd1313f5145395097f51ab43
  | 2022-08-18T16:15:54.493+02:00 | Step 3/60 : FROM $PYTHON_IMAGE as pybuilder
  | 2022-08-18T16:15:56.525+02:00 | public.ecr.aws/bitnami/python:3.9.13-debian-11-r33@sha256:e8152fa800d27ec38f6603fb407b4a2ece1f78b9ef471a3ab7442a150dad6005: Pulling from bitnami/python
  | 2022-08-18T16:15:56.525+02:00 | 3b5e91f25ce6: Pulling fs layer
  | 2022-08-18T16:15:56.525+02:00 | 8b38733774ad: Pulling fs layer
```

I also tried to ommit `:latest` but that does not change the result. 
I copied the url from the repository in ECR and there is an image with the tag `latest`.
![image](https://user-images.githubusercontent.com/96723335/185419447-89373372-f364-48f7-9468-2c3001f79861.png)

I'm running copilot 1.20.0 and recently deployed a fresh new pipeline with that version.

Any help appreciated.

**Comment by dannyrandall** [comment]
Hey @hellolennert!

If you're using pipelines and have a `COPY . .` in `Dockerfile.prod`, one issue with caching may be the generated templates affecting an early layer and making the rest have a cache miss. (see https://github.com/aws/copilot-cli/issues/3510#issuecomment-1136317004)

Another potential issue is using `ARG`, which [can also cause cache misses](https://docs.docker.com/engine/reference/builder/#impact-on-build-caching).

If neither of those seem to be the issue, could you share your `Dockerfile.prod`?

**Comment by hellolennert** [comment]
Hi and thanks for getting back. 

The docker file can use cache locally. The COPY . . is at the very end of the docker file. The ARG I use is just a static, but I will try without it to see if it works.

As mentioned in some other posts I read, it would be nice to see the actual docker command just to be sure of what it actually does.

I would expect it to at least use the base image from cache, as it is a fixed image that is mentioned even with a specific sha-tag. I understand that it will miss the cache as soon as it hits updated COPY commands or the like, but we have it quite well optimized for caching, which is again working just fine locally. 

That is why I suspect it's not using the ECR image that I'm pointing to as intended in the manifest above. I also had found the comment you are pointing to and I've already added ./infrastructure to .dockerignore to fix that.

**Comment by dannyrandall** [comment]
I think I've been able to replicate the same issue - could you try adding these commands to the beginning of your `buildspec.yml` and seeing if the `docker build` here still has the same issue of the cache not being used?

```
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <accountID>.dkr.ecr.us-west-2.amazonaws.com
      - docker pull <accountID>.dkr.ecr.us-west-2.amazonaws.com/xxx-copilot/app:latest
      - docker build -t cache-test --cache-from <accountID>.dkr.ecr.us-west-2.amazonaws.com/xxx-copilot/app:latest app
```

At least in my pipeline, this is resulting in the same issue of the cache not being used, but want to verify that occurs for you as well. I'm trying to find out why it's not being used! 🧐

**Comment by dannyrandall** [comment]
Ok I think I've got it working! Try this:

In your `buildspec.yml`, change the `./copilot-linux svc package ...` line to `DOCKER_BUILDKIT=1 ./copilot-linux svc package ...`. This will make `docker build` use buildkit.

If the `cache-from` image is created by Copilot as well, then add the `BUILDKIT_INLINE_CACHE` arg to the "source" service's manifest:
```
image:
  build:
    dockerfile: app/Dockerfile.prod
    cache_from:
      - xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx-copilot/app:latest
    args:
      BUILDKIT_INLINE_CACHE: 1
```
This will make it so that cache metadata is pushed to ECR on the source image, so that it's layers can be used when building other services.

---
Let me know if this works for you!😊

**Comment by hellolennert** [comment]
Yes it works! 

On the first run I got a 401 on the cache manifest, because it wasn't there of course, and  the second time around it found the cache manifest and finished the build in 1 minute 30 seconds (coming from 12 minutes).

This is great, really appreciate you help @dannyrandall !

Error on first run:
```
#5 importing cache manifest from xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx-copilot/app:latest
#5 sha256:11db44df6d193c3586d3fec1c44eaeb126eac89c9cc794cc8bbeef100b674830
#5 ERROR: unexpected status code [manifests latest]: 401 Unauthorized
```

Success on second run:
```
#55 importing cache manifest from xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx-copilot/app:latest
#55 sha256:11db44df6d193c3586d3fec1c44eaeb126eac89c9cc794cc8bbeef100b674830
#55 DONE 0.0s
```

**Comment by dannyrandall** [comment]
Yay! Glad to hear it works.:tada: Feel free to reopen or comment here if you notice any other issues with caching!😊

**Comment by hellolennert** [comment]
Thanks. I expect this guidance at https://aws.github.io/copilot-cli/docs/manifest/backend-service/#image-build
That is where I learned about cache_from, it would make sense to provide complete guidance there.

**Comment by hellolennert** [comment]
So after a few days I noticed that it missed the cache again often times, showing:
`#5 ERROR: unexpected status code [manifests latest]: 401 Unauthorized`

Cause of the problem is that the build agent is kept alive for a few minutes, usually 15 minutes up to one hour sometimes. So the first time it cannot access the cache in ECR, then it uploads the result image of the build to ECR, and then on the next build the build agent can access the cache. Unless the build agent expired and a new build agent is provisioned. The new build agent does not have access to the cache again the first time.

I fixed that using your proposal to add this at the top of the buildspec.yml:
`- aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <accountID>.dkr.ecr.<region>.amazonaws.com`

where for me `<region>` is eu-central-1

Using this, also newly provisioned build agents can fetch the cache from ECR every time.

**Comment by hellolennert** [comment]
I found a reason to reopen this question. 

We're using multi-stage docker files with three stages: two builder stages and one final stage. Observing the behavior of the cache, I found that copilot it is not using cache with the non-final stages of the docker file.

Again, when an existing build agent is still running, it does find the cache of the previous build of the all the stages in my docker file. 
When the build agent expires and the next build is executed by a newly provisioned build agent, it retrieves the docker image from ECR, but that only contains the final stage, so the first 2 stages are always being rebuild.

Most of the gain of using caching for me is in those stages. Is there a way to also persist the two builder stages to ECR? 

@dannyrandall I cannot reopen. Anyway, please have a look at my question and reopen if you think that's appropriate.

**Comment by dannyrandall** [comment]
Hey @hellolennert - I think this is an issue with Docker https://github.com/moby/moby/issues/34715, though according to that issue it's potentially resolved by using [`BUILDKIT_INLINE_CACHE`](https://github.com/moby/moby/issues/34715#issuecomment-550567523). Could you try using just `docker build` and see if that resolves the issue, or if it has the same result as the Copilot build?

> Is there a way to also persist the two builder stages to ECR?

One option could be to add a `docker build --target <target> ... && docker push ...` to your buildspec for each of the 2 stages. https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage---target.
