### ISSUE TITLE
Copilot env init not creating network resources

### ISSUE THREAD

**Issue by zeva-us** [aws/copilot-cli#3928]
Hello all, I am on windows 10 machine, I installed Copilot the latest version. I have used Copilot in the following way:

copilot app init %appname%
copilot env init --app %appname% --name %envname% --profile default --container-insights 

The problem is that the network resources are not being created (only the roles) and so I am not able to continue the deployment. is this a normal behavior? in the tutorials, I can see that vpc and network resources should be created in this step. Below is the output of the command.

![Capture](https://user-images.githubusercontent.com/86469233/185913300-0262bbf5-26b0-4016-8320-2faeba6c026a.png)

**Comment by RaniRishmawi** [comment]
when I used two versions earlier the Network resource were created correctly.

**Comment by huanjani** [comment]
Could you do me a favor and try running the `copilot env init` command and follow the prompts instead of using flags, to see if that will be different? (In v1.21.0.) Thanks!

**Comment by huanjani** [comment]
OH! Sorry- with the introduction of env manifests, you now need to run `copilot env deploy` as well! https://aws.github.io/copilot-cli/blogs/release-v120/#environment-manifest

**Comment by RaniRishmawi** [comment]
Thank you @huanjani
