### ISSUE TITLE
Execute SVC Deploy - Upload custom resources permission failed

### ISSUE THREAD

**Issue by Narnoocom** [aws/copilot-cli#3932]
I've been searching for days to find an answer to this issue which has only just started with my deployments. The previous 35 deployments went without fail.

I've all the sudden started to receive the error message:

execute svc deploy: upload deploy resources for service xxxxxxxxxxxxx-lbws: upload custom resources for "xxxxxxxxxxxxx-lbws": upload custom resource "DynamicDesiredCountFunction": upload manual/scripts/custom-resources/dynamicdesiredcountfunction/acd1f00a18ceccc32a780fb208be61f3f62274d775f987fd9feec37493d9173c.zip to bucket stackset-xxxxxxxxxxxxx-pipelinebuiltartifactbuc-16mzh0wflh1k0: AccessDenied: Access Denied

The user role managing the deployment has been set up with "AdministratorAccess" and I also added them to a Group which has "AmazonS3FullAccess".

I'm just out of ideas here and I'm sure it's something small. Any help would be greatly appreciated.

**Comment by huanjani** [comment]
Hi @Narnoocom! 
Did you recently upgrade to v1.21.0?

**Comment by huanjani** [comment]
Have you run `copilot env deploy` since upgrading?

**Comment by Narnoocom** [comment]
Hi @huanjani thanks for replying. 

The issue started prior to upgrading. The last successful deployment was 4th of August. I upgraded to that version yesterday.

I ran some trials yesterday and discovered the following:
- there was no copilot/environments/{name} folder --> Is this something new to the latest version.
- Deployments fail as there's no "manual" folder found in the copilot generated S3 bucket. --> Is this a new thing? My S3 bucket contained a "scripts" folder?

I also redeployed this code to another copilot application and all the above mentioned issues weren't associated with the latest deployment.
- Environments folder was created
- S3 has a "manual" folder and not a "scripts" folder.

Perhaps I missed some documentation on deployment changes with the latest version, which could have previously created applications?

**Comment by huanjani** [comment]
What version were you using before yesterday?

**Comment by Narnoocom** [comment]
I think it might have been V1.19.0

Looking at the releases I see V1.20 had the introduction of the environments folder.

**Comment by Narnoocom** [comment]
Actually looking at the release data the versioning might have been V1.18

**Comment by huanjani** [comment]
Would you mind checking the CloudFormation console to see the version of your environment stack's template?

**Comment by huanjani** [comment]
It sounds like your environment's CloudFormation template was created before we added some permissions.
If you could, please revert to Copilot v1.18.1 and run `env upgrade`. Then go back to Copilot v1.21.0 and run `copilot env deploy` (you will need to follow the printed instructions to create an env manifest), then retry `copilot svc deploy`.
Let me know how that goes!
