### ISSUE TITLE
Update AppRunner SDKs for new regions

### ISSUE THREAD

**Issue by idelfonsog2** [aws/copilot-cli#3943]
per #3172 it seems that a new binary of copilot needs to be release to get the hardcoded regions into copilot?

Is there a automated process to update it ?

**Comment by huanjani** [comment]
Hi, @idelfonsog2! 
There isn't an automated process, but Copilot should still work if certain regions have been enabled for AppRunner. 
Did you get an error when trying, or just a "proceed with caution" warning?
