### ISSUE TITLE
Resource handler returned message: "Service Unavailable. Please try again later

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#3945]
In copilot i deployed some services, but suddenly not able to deploy with below message , can anyone please help.
while in Ecs service to run and maintain your tasks in the environment cluster stage it is starting to rollback 
```
 - An ECS service to run and maintain your tasks in the environment cluster         [delete complete]    [7.0s]
    Resource handler returned message: "Service Unavailable. Please try ag
    ain later. (Service: AmazonECS; Status Code: 500; Error Code: ServerEx
    ception; Request ID: dc8b6125-bfc2-41ab-900b-0324e4723699; Proxy: null
    )" (RequestToken: d7a68d68-1812-2d97-1697-fbcb497c5156, HandlerErrorCo
    de: GeneralServiceException)
```

**Comment by Dhina-test** [comment]
![image](https://user-images.githubusercontent.com/78138014/186590069-825eceb0-e53c-4d12-bc6f-6b7f8427ad97.png)

**Comment by huanjani** [comment]
Hi @Dhina-test! 

So sorry for the inconvenience! Would you mind trying again? 
There was an outage yesterday that probably caused the issue you experienced.

Please let us know if it works now! Thanks!

**Comment by Dhina-test** [comment]
Thanks working now
