### ISSUE TITLE
how to configure primary-replica configuration for postgres containers by aws copilot

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#3954]
we are hosting postgres containers into ecs by aws copilot , so how to configure master slave configuration for database containers by aws copilot. Can anyone please help

**Comment by Dhina-test** [comment]
For database replication how to configure master and slave configuration ecs db(postgres) containers by aws copilot

**Comment by Lou1415926** [comment]
Would [`storage`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#storage) helps with data transfer between master and slave containers in your case? 

In the meanwhile, if any one has existing set up, please feel free to share and it'll be very appreciated!

**Comment by Dhina-test** [comment]
@Lou1415926 , Is there any option to create secondary container from copy of primary container  ?

**Comment by Lou1415926** [comment]
Yes. 

In the meantime you can also look into RDS's read replica option. You should be able to create an RDS database with PostgreSQL engine as an addon.

**Comment by Dhina-test** [comment]
As of now we are hosting db in ecs containers , can you please help to configure replica  from primary to secondary by copilot

**Comment by Dhina-test** [comment]
Ok , Now i  created 2 ecs containers by copilot , and mounted two different efs volumes for both the containers , Now to how to make sync with primary and secondary ?? can you please help

**Comment by Dhina-test** [comment]
@Lou1415926  , Now i created 2 ecs containers by copilot , and mounted two different efs volumes for both the containers , Now to how to make sync with primary and secondary ?? can you please help

**Comment by Lou1415926** [comment]
Hopefully [this post](https://medium.com/swlh/postgresql-replication-with-docker-c6a904becf77) can help!

**Comment by Lou1415926** [comment]
Or you can set up two Backend services: a master service, and some slave services. When master services receive WRITE to the database, it connects to the slave service via. service discovery endpoint replicating the data. That's potentially an option to explore too.

**Comment by dannyrandall** [comment]
Hey @Dhina-test! Have you looked at https://github.com/bitnami/containers/tree/main/bitnami/postgresql? I think that looks like the easiest way to deploy postgres in a container with a primary/replica setup - they have a nice guide for it [here](https://github.com/bitnami/containers/tree/main/bitnami/postgresql#setting-up-a-streaming-replication). 

Assuming you're deploying this as two Copilot backend services, then you can just configure the [environment variables](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#variables) on the primary and replia services following that guide, using service discovery URLs like @Lou1415926 mentioned.

**Comment by Dhina-test** [comment]
yes @dannyrandall , I am deploying two copilot backend postgres containers , mounted two different efs volumes .checking to configure one as primary and another as a replica.
