### ISSUE TITLE
Warn when deploying with an older version of Copilot than previously used

### ISSUE THREAD

**Issue by benjaminpottier** [aws/copilot-cli#3973]
We just upgraded to the copilot 1.21.1 cli for out CI deployment and we're getting the following error now when deploying our load balanced service:

```
CustomResource attribute error: Vendor response doesn't contain Priority key in object arn:aws:cloudformation:us-east-1:######:stack/apv2-dev-api/78d77910-223d-11ed-af8e-0e86b8cf9aed|HTTPSRulePriorityAction|bc457611-ed6e-4b6b-93e75312b99ffd51 in S3 bucket cloudformation-custom-resource-storage-useast1
```

**Comment by dannyrandall** [comment]
Hey @benjaminpottier! Sorry to hear you're running into this issue - Could you share your manifest for the service? Also, what Copilot version are you upgrading from, and have you made any changes to the manifest before deploying with `v1.21.1`?

**Comment by benjaminpottier** [comment]
> Hey @benjaminpottier! Sorry to hear you're running into this issue - Could you share your manifest for the service? Also, what Copilot version are you upgrading from, and have you made any changes to the manifest before deploying with `v1.21.1`?

So I realized that our pipeline was trying to use a really old version of copilot (1.17.0). I was previously using 1.21.0 but I made a mistake which reverted all the way back to 1.17.0

But, I'm wondering if it might be worth just not letting copilot try to deploy using a version of the cli that isn't compatible with the environment.

**Comment by dannyrandall** [comment]
Oh I see, so basically what happened for this service was:
1. `copilot@v1.17.0 svc deploy` <-- through pipelines
2. `copilot@v1.21.0 svc deploy` <-- locally
3. `copilot@v1.17.0 svc deploy` <-- through pipelines, got the reported error here

Is that right?

> But, I'm wondering if it might be worth just not letting copilot try to deploy using a version of the cli that isn't compatible with the environment.

Can you clarify what you mean here? Just that you haven't deployed your environment with `v1.21.1` yet?

**Comment by benjaminpottier** [comment]
> Oh I see, so basically what happened for this service was:
> 
> 1. `copilot@v1.17.0 svc deploy` <-- through pipelines
> 2. `copilot@v1.21.0 svc deploy` <-- locally
> 3. `copilot@v1.17.0 svc deploy` <-- through pipelines, got the reported error here
> 
> Is that right?
> 
> > But, I'm wondering if it might be worth just not letting copilot try to deploy using a version of the cli that isn't compatible with the environment.
> 
> Can you clarify what you mean here? Just that you haven't deployed your environment with `v1.21.1` yet?

Sorry probably wasn’t clear. I built an app/environment/service with 1.21.0 from local,
setup CI to mange ongoing deployments. I thought I upgraded to 1.21.1 but I accidentally tried to deploy using 1.17.0 (not realizing).

It was a mistake on my part and there was a “Are you using the latest version?” warning. I’m just wondering if it wouldn’t be safer/more clear to just not allow it to attempt the deployment at all if it won’t work. Does that make sense?

**Comment by dannyrandall** [comment]
Ah, gotcha. I agree - a clearer warning saying/blocking you from deploying with an older version of Copilot totally makes sense to me; great idea!😊

**Comment by Lou1415926** [comment]
In the recent [v1.29.0](https://github.com/aws/copilot-cli/releases) we added warning if the application/env/service is being deployed by an older version of Copilot than the last deployment 🎉  I'm closing this issue for now, but please do reopen it / let me know if the issue persists!
