### ISSUE TITLE
Pipeline CloudFormation failures 

### ISSUE THREAD

**Issue by leekanjin** [aws/copilot-cli#3978]
![image](https://user-images.githubusercontent.com/112799391/188304614-417b9fb9-98af-432e-ad1d-da2bc012b9ff.png)
![image](https://user-images.githubusercontent.com/112799391/188304671-d112b39c-8d65-4b03-a98d-b44fb8086117.png)

Please guide me in fixing it. I use a **private subnet** to operate the app **load balance**. Everything was completed, however, the configuration copilot pipline failed.

**Comment by leekanjin** [comment]
The logs indicate that the ECS task has been fixed. Please kindly close the ticket.

**Comment by Lou1415926** [comment]
Closing the issue as it has been fixed.  Feel free to reopen it for further questions!
