### ISSUE TITLE
Could not deploy via CodePipeline "CustomResource attribute error: Vendor response doesn't contain Priority key in object "

### ISSUE THREAD

**Issue by mvn-bachhuynh-dn** [aws/copilot-cli#4008]
Hi all,
I have just create a whole new app.
Everything fine, but could not deploy via CodePipeline.
here is the error

CustomResource attribute error: Vendor response doesn't contain Priority key in object arn:aws:cloudformation:ap-south-1:443171139711:stack/quick-dev-api/0ce34700-381a-11ed-ab9d-06b04aa587c4|HTTPSRulePriorityAction|c7e51f67-80d3-4ec9-b724-919273ceb8ee in S3 bucket cloudformation-custom-resource-storage-apsouth1

Check my image for more error.
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/16200158/191031491-74b96b77-9c6d-4d62-85b1-6f4c7e2770f2.png">

Service deploy via Copilot commandline is totally fine.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/16200158/191031717-15e1ea2a-3865-406b-b811-269e3117ac69.png">

I tried to add AdministratorPermission for the Role, but still failed.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/16200158/191031837-9cd16f39-8018-49f9-b9ca-a7b9f20d945e.png">

Please help me!
Thank you!

**Comment by efekarakus** [comment]
Hi @mvn-bachhuynh-dn !

Which version of Copilot are you using? `copilot version`
More specifically, can you check if in the generated `buildspec` the copilot version matches your local CLI version?
https://github.com/aws/copilot-cli/blob/8c436b4d8717d8b09b3f9ba1385b54210f260ba0/internal/pkg/template/templates/cicd/buildspec.yml#L8-L14

I can see that one of the errors happens with the `HTTPListenerRuleWithDomain` resource where the `HTTPSRulePriorityAction` was removed in `v1.20.0`.

**Comment by efekarakus** [comment]
Here is a past example for a user upgrading from v1.19 to 1.21.1 and resolved this issue: https://gitter.im/aws/copilot-cli?at=63178a19d020d223d324f824

**Comment by mvn-bachhuynh-dn** [comment]
Hi @efekarakus,
Yeap! It's version issue.
I delete the buildspec.yml and recreate via Copilot CLI again, and it's work.

I remember this is the second time I face this issue :(. 

Maybe I have to take a quick note when creating Codepipeline and especially when updating the Copilot version.

Thank you for your support so much! <3

**Comment by efekarakus** [comment]
Awesome, I'm glad it got resolved ❤️!

**Comment by ChaminW** [comment]
Still facing the same issue and tried updating the build spec as well.
![image](https://user-images.githubusercontent.com/13014405/208583611-711255a0-241e-4ce6-9b38-882af3d7b829.png)

Build spec: 
![image](https://user-images.githubusercontent.com/13014405/208583657-61e89c81-a154-4948-83ba-eb866bdea1cd.png)

**Comment by SoundsSerious** [comment]
Also having this issue going from `1.19.0` to `1.22.1`

I have tried updating my pipeline, rebuilding and redeploying the service in different orders.

Its a bit unclear since it seems there are several verisons. My app is 1.1 for example, but copilot is 1.22.1

It would be great if there could be more guidance on how to upgrade, and what is happening behind the scenes. Right now it feels a bit like a black box

**Comment by SoundsSerious** [comment]
@ChaminW i was having some issues, here but you need to make sure the changes propagate to github or other repo source first.
