### ISSUE TITLE
AWS ending support for Node.js 12 in AWS Lambda

### ISSUE THREAD

**Issue by rmarops** [aws/copilot-cli#4009]
AWS is periodically sending nodejs 12 obsolescence emails.  There are a number of node12 based lambda functions created per app deployed into ECS

Excerpt from Notice
"We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, ..."

**Comment by rmarops** [comment]
$ aws lambda list-functions --function-version ALL --region us-east-1 --output text --query "Functions[?Runtime=='nodejs12.x'].FunctionArn"

sanitized and formatted excerpt
```
arn:aws:lambda:us-east-1:100000000000:function:myapp-prod-client-EnvControllerFunction-FAqmEbjiEFtN:$LATEST
arn:aws:lambda:us-east-1:100000000000:function:myapp-prod-nginx-EnvControllerFunction-waAqWgMIEI4E:$LATEST
arn:aws:lambda:us-east-1:100000000000:function:myapp-prod-nginx-RulePriorityFunction-FFSlHXVXOuRt:$LATEST
arn:aws:lambda:us-east-1:100000000000:function:myapp-prod-server-EnvControllerFunction-7CzGiq4VjDm9:$LATEST
arn:aws:lambda:us-east-1:100000000000:function:myapp-qa-client-EnvControllerFunction-eD25NhnX4MMG:$LATEST
arn:aws:lambda:us-east-1:100000000000:function:myapp-qa-nginx-EnvControllerFunction-sjDwgunI99qN:$LATEST
arn:aws:lambda:us-east-1:100000000000:function:myapp-qa-nginx-RulePriorityFunction-ER2JOBOZR2Xg:$LATEST
arn:aws:lambda:us-east-1:100000000000:function:myapp-qa-server-EnvControllerFunction-LJr6N1maRhbl:$LATEST
```

**Comment by efekarakus** [comment]
Hi @rmarops !

Which version of Copilot are you using? `copilot version`.

In v1.21.1, we have upgraded all Lambda functions to use nodejs16: 
- https://github.com/aws/copilot-cli/commit/7f3a66680c2cb66d21d4fd10c5181815547fe5e0
- 670855d7

Once you download the new version of the CLI, after running `copilot svc deploy` and `copilot env deploy` all your Lambda function runtimes should get upgraded 🙇 

Hope this helps!

**Comment by rmarops** [comment]
Thanks for the swift response.  I have determined our CircleCI config.xml is referencing version 1.15.0 so i will update that to 1.21.1 and redeploy.  Closing issue.
