### ISSUE TITLE
Set `ReadonlyRootFilesystem` to `true` by default in manifest files

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#4010]
## Ask

To comply with Security Hub's recommendation of [[ECS.5] ECS containers should be limited to read-only access to root filesystems](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ecs-5). Copilot should consider generating default manifest files with the following field already populated:
```yaml
name: my-service

storage:
  readonly_root_fs: true
```
This way existing deployed service won't break, but newer services will comply with ECS.5 by enabling [`ReadonlyRootFilesystem: true`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-readonlyrootfilesystem) in the CloudFormation template.

**Comment by huanjani** [comment]
This feature is now released in v1.23.0: https://github.com/aws/copilot-cli/releases/tag/v1.23.0! 🎉
