### ISSUE TITLE
Access Denied Deploying Job

### ISSUE THREAD

**Issue by rajbala** [aws/copilot-cli#4040]
Hi!  I see that there was a permissions issue #3556 where uploads of the template to an S3 bucket would fail.  

I am seeing something that appears similar while using Copilot 1.21.1.  I added a job to an existing app.  When I try to deploy the job I get the following error:

> ✘ upload deploy resources for job testjob: upload custom resources for "testjob": upload custom resource "EnvControllerFunction": upload manual/scripts/custom-resources/envcontrollerfunction/3ffcf03598029891816b7ce2d1ff14fdd8079af4406a0cfeff1d4aa0109dcd7d.zip to bucket somebucketname: AccessDenied: Access Denied
> 	status code: 403, request id: somereqid, host id: somehostid

Am I missing something?

**Comment by dannyrandall** [comment]
Hey @rajbala - Could you try updating to Copilot v1.22, run `copilot env deploy`, and try deploying the job again?

We found an issue https://github.com/aws/copilot-cli/issues/3950 and resolved it https://github.com/aws/copilot-cli/pull/3998, which should hopefully resolve this for you.

**Comment by rajbala** [comment]
That ..... worked!  Many thanks!

In case anyone else stumbles upon this ---  I had to follow these steps too before `copilot env deploy` would work:

> It looks like there are no environment manifests in your workspace.
> To create a new manifest for an environment "example", please run:
> 1. Create the directories to store the manifest file:
>    `mkdir -p copilot/environments/example`
> 2. Generate and write the manifest file:
>    `copilot env show -n example --manifest > copilot/environments/example/manifest.yml`
