### ISSUE TITLE
"Grow with Addons" link on the startpage leads to a 404 page

### ISSUE THREAD

**Issue by Gyllsdorff** [aws/copilot-cli#4051]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1038004/193398583-78701836-2f22-478c-8da0-daf3a9e779e1.png">

The "[Grow with Addons](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/)" on the [startpage](https://aws.github.io/copilot-cli/) link leads to a 404 page. It looks like the page was converted into a category and split into [two pages](https://github.com/aws/copilot-cli/tree/mainline/site/content/docs/developing/addons).

**Comment by dannyrandall** [comment]
Great catch! Thanks @Gyllsdorff!❤️
