### ISSUE TITLE
Need npm in development setup?

### ISSUE THREAD

**Issue by hkford** [aws/copilot-cli#4123]
When I provisioned Amazon Linux 2 EC2 instance, install Go 1.18, forked this repository and run `make test`, I got `npm: command not found` error.

![スクリーンショット 2022-10-28 17 44 03](https://user-images.githubusercontent.com/82389275/198545672-668c3dd8-7110-4aed-83e5-05f18bd9b55c.png)

Is this expected behavior? In other words npm is dependent of running `custom-resource-test` and the Copilot team handles this test, so other contributors do not need npm?

**Comment by iamhopaul123** [comment]
Hello @hkford. Yes I think this is expected. The reason why `npm` is required is because we write custom resource lambda functions using javascript. Therefore whenever we run `make test` we need to make sure those js codes are covered as well. Maybe we could add a new alias in the `makefile` to allow developers to only run golang unit tests, ignoring the custom resources?

**Comment by hkford** [comment]
I think so. We just edit [CONTRIBUTING.md](https://github.com/aws/copilot-cli/blob/mainline/CONTRIBUTING.md) to allow developers to run `make run-unit-test` for unit tests.

```markdown
(before)
* Run `make test` to run the unit tests.
(after)
* Run `make run-unit-test` to run the unit tests.
```
According to [Makefile](https://github.com/aws/copilot-cli/blob/mainline/Makefile#L64) when we run `make test`,  both `run-unit-test` (Golang unit tests) and `custom-resource-tests` (custom resource lambda functions js codes tests) are called.  If we have Golang development environment but no Node.js development environment, `run-unit-test` completes successfully and [`custom-resource-tests`](https://github.com/aws/copilot-cli/blob/mainline/Makefile#L67) is called, then [`tools`](https://github.com/aws/copilot-cli/blob/mainline/Makefile#L150) is called and `npm ci` fails saying `npm: command not found`. If developers want to run only Golang unit tests, all they have to do is just running `make run-unit-test`.
![スクリーンショット 2022-10-29 10 08 50](https://user-images.githubusercontent.com/82389275/198755038-d23b14f9-48d5-4626-81a2-61b6ee68b25d.png)
