### ISSUE TITLE
Support AppRunner Private Services

### ISSUE THREAD

**Issue by miketheman** [aws/copilot-cli#4145]
As announced today in the release blog:
https://aws.amazon.com/blogs/containers/announcing-aws-app-runner-private-services/

I should be able to select an application type that presents an internal-facing AppRunner service.

**Comment by efekarakus** [comment]
brb!

**Comment by dannyrandall** [comment]
soon :)

**Comment by huanjani** [comment]
Hi, @miketheman! 

Yes, you should be able to do this with our next release, happening soon!

**Comment by huanjani** [comment]
Thanks for your patience, @miketheman! Give v1.23.0 a spin!

**Comment by miketheman** [comment]
Thanks gang! Congrats!
