### ISSUE TITLE
Copilot svc deploy forcing environment update but failing to update role

### ISSUE THREAD

**Issue by brendenrea** [aws/copilot-cli#4146]
```
copilot svc deploy                                                                                                                                                  1 err  %  09:29:10 
Service name: <appName>-<service>-dev
Environment: dev
✘ Unable to update the environment's manager role with upload artifacts permission
✘ execute "env upgrade --app <appName> --name dev": update environment template with PutObject permissions: wait until stack <appName>-dev update is complete: ResourceNotReady: failed waiting for successful resource state
```

I've looked through other posts and issues and tried manually updating the role with no luck. Hoping to get some assistance in updating this environment from 1.4.0 to 1.9.0

**Comment by brendenrea** [comment]
The documentation is also out of date, not reflecting the 'env upgrade' that runs
https://aws.github.io/copilot-cli/docs/overview/

**Comment by huanjani** [comment]
Hi, @brendenrea-skip! 

I see that you're trying to update your environment version from 1.4 to 1.9; which Copilot version are you on?

**Comment by huanjani** [comment]
I suggest that you upgrade to the latest version and follow the guidance here to upgrade your environments:
https://aws.github.io/copilot-cli/blogs/release-v120/#migrating-existing-environments

Some other resources:
https://aws.github.io/copilot-cli/blogs/release-v120/#environment-manifest
https://aws.github.io/copilot-cli/docs/manifest/environment/

**Comment by brendenrea** [comment]
On version 1.18.1 - will work to update that today and circle back
