### ISSUE TITLE
No services or jobs found for the pipeline to deploy. Please create at least one service or job and push the manifest to the remote

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#4151]
Hi , I am trying to create copilot pipeline for deployment , Getting **No services or jobs found for the pipeline to deploy. Please create at least one service or job and push the manifest to the remote** . Please help.

And for reference here I am sharing  Manifest.yml and buildspec.yml file.

Error:
![image](https://user-images.githubusercontent.com/78138014/199464238-6baef03c-7883-423f-acd4-409916f8a7a4.png)

Manifest file.
![image](https://user-images.githubusercontent.com/78138014/199464854-67e5211d-2a63-47ef-baac-72443c98a882.png)

buildspec.yml
![image](https://user-images.githubusercontent.com/78138014/199465083-e4dee815-ca53-4b14-882f-6ca5ecdec05c.png)

`

**Comment by Dhina-test** [comment]
while pipeline init and deploying creates only buildspec and manifest file .
And my copilot version 1.22.0

**Comment by huanjani** [comment]
Hello, @Dhina-test!

Was the manifest file that you posted above created with the `pipeline init` command? It appears to be a combination of a workload manifest and a pipeline manifest.

Have you run `svc init` or `job init`? Those commands will generate a manifest for each "workload" (job or service) that you wish to create. Then, run `pipeline init` and push the created files to your source repository. 

Does that clarify things? Please let me know if you have further questions!

**Comment by Dhina-test** [comment]
Hello  @huanjani  !!

Thanks Much . I did reverse order so i stucked . Now i deployed app with pipeline.
