### ISSUE TITLE
How can I clean up an environment manually

### ISSUE THREAD

**Issue by alphamu** [aws/copilot-cli#4153]
My internet connection dropped while creating a new environment and since then, the environment appears in my copilot cli, but every time I tried to deploy something to it, it would give me an error like the one below:
```
AccessDenied: User: arn:aws:iam::0000000000:user/ali is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::0000000000:role/app-env-EnvManagerRole
```
I tried to fix this by deleting all the environment resources, roles, s3 bucket, etc. I could find in the AWS console, however the environment still exists, and now it shows me the same error when I try to delete a service from my app.

```
X delete service: get template body of stack "app-env-svc-customer-internal": get template app-env-svc-customer-internal: AccessDenied: User: arn:aws:iam::0000000000:user/ali is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::0000000000:role/app-env-EnvManagerRole
        status code: 403, request id: 60ba7571-89a8-4ab3-abb7-b3f2ad43b066
```

Is there anyway to purge this environment manually?

**Comment by alphamu** [comment]
Never mind, found it.
AWS Systems Manager > Parameter Store
delete it from there and it's working.

**Comment by billmetangmo** [comment]
you saved my day man @alphamu
