### ISSUE TITLE
May I have justification for the AWS Copilot Best Practices?

### ISSUE THREAD

**Issue by Macaroni2629** [aws/copilot-cli#4156]
Hi there, when I read this:

"Copilot takes best practices, from infrastructure to continuous delivery, and makes them available to customers from the comfort of their command line
Is there research into why there are 2 public and 2 private subnets, along with all the other configurations?"  https://aws.amazon.com/containers/copilot/faqs/

Where do these best practices come from?  Is there a white paper on it?

I'm doing a research project on this product and would appreciate any helpful sources, thanks!

**Comment by efekarakus** [comment]
Hi @Macaroni2629 !

> Where do these best practices come from? Is there a white paper on it?

They are from various different locations!
1. ECS best practices guide: https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/intro.html
   For example, the [Reduce load balancer health check thresholds.](https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/capacity-availability.html) is applied in the templates by default:
   https://github.com/aws/copilot-cli/blob/a8bb072f8014273a87c39c6cc1a192ab637edc7b/internal/pkg/template/templates/workloads/partials/cf/alb.yml#L40
   
 2. The AWS Well Architected framework: https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html
    > Distribute workload data and resources across multiple Availability Zones or, where necessary, across AWS Regions.
 
    Just to be clear not all of these are applied because Copilot tries to be as cost effective as possible while having maintaining security as priority no 1. So it's a fine balance between creating 1 task to optimize on cost vs. multiple tasks by default for reliability.
 
 3. We consider also recommendations from Security Hub: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ecs-8
 Again some of these have tradeoffs, for example [[ECS.12] ECS clusters should have Container Insights enabled](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ecs-12) costs extra money. So we apply the recommendations that are deemed appropriate for application developers, and surface options to toggle additional settings.
 
 4. Finally, Copilot is an open source and customer-driven product. Many of the Copilot's best practices are result of learnings and feedback from our customers through GitHub issues and Gitter conversations.
 
 Hope this helps!

**Comment by Macaroni2629** [comment]
Hi Efe,

I have been watching your lectures on YouTube and reading your blog posts, so it's amazing to have you reply to my post!

I might have more questions in the future, but I just wanted to acknowledge that I read your response, thanks!

**Comment by dannyrandall** [comment]
Thanks for opening the issue, @Macaroni2629! I'll close it for now, but feel free to reopen if you have any other questions!
