### ISSUE TITLE
Copilot Pipeline Codebuild issue with referencing another ECR repo as base image "no basic auth credentials"

### ISSUE THREAD

**Issue by jericopulvera** [aws/copilot-cli#4190]
```
manifests/latest": no basic auth credentials
--
142 | upload resources required for deployment for
```

 I hit a rate limit with Docker Hub that's and I decided to host the base Docker image I use to ECR. 

I have reviewed the Build project role permission and I have seen this Policy statement.

```
      "Condition": {
                "StringEquals": {
                    "ecr:ResourceTag/copilot-application": "application-name"
                }
            },
```

I have copied this tag into the Docker image I have manually pushed to ECR but then I'm still getting error.

**Comment by huanjani** [comment]
Hello, @jericopulvera!

It looks like you are running into the same issue as the user here: https://github.com/aws/copilot-cli/issues/2033#issuecomment-796372280 Read all the way to the bottom, as it looks like there are a couple of potential fixes.

The other option is to solve the Docker pull rate limit problem by doing this fix suggested here: https://github.com/aws/copilot-cli/issues/1869#issuecomment-765643674.

Let us know if either of those works for you!

Thanks!
