### ISSUE TITLE
unable to deploy .NET 7 app

### ISSUE THREAD

**Issue by mathiasnohall** [aws/copilot-cli#4191]
I upgraded my .NET application too .NET 7 from .NET 6 and since then the copilot deploy step timeouts in MSBuild and takes forever. It works if I downgrade the app to .NET 6.

![Image 2022-11-17 at 10 26](https://user-images.githubusercontent.com/2675171/202408508-616cb5c5-1fbb-40f5-aaf2-9c210e25c6af.jpg)

dockerfile
`FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /app

COPY RunRun.Api/RunRun.Api.csproj ./
COPY . . 

RUN dotnet publish -c release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS runner

ENV COMPlus_EnableDiagnostics=0
ENV ASPNETCORE_URLS=http://+:5443

WORKDIR /app
COPY --from=build /app/out .
EXPOSE 5443
ENTRYPOINT [ "dotnet", "RunRun.Api.dll" ]`

**Comment by huanjani** [comment]
Hi @mathiasnohall! 

I'm not familiar with .NET, unfortunately, but see if this helps:
Try running `docker build` locally and building your updated image. If it's successful, when you run Copilot, it will use the cached version instead of trying to build again. 

Hope that helps!

**Comment by mathiasnohall** [comment]
> Hi @mathiasnohall!
> 
> I'm not familiar with .NET, unfortunately, but see if this helps: Try running `docker build` locally and building your updated image. If it's successful, when you run Copilot, it will use the cached version instead of trying to build again.
> 
> Hope that helps!

Hi!
Thanks for your reply! However it does not resolve my issue. I have tried building it locally and it runs locally but it doesn’t seem to pick the cached version. I’m using the same tag.

**Comment by mathiasnohall** [comment]
Im also getting this error sometimes under the `MSBUILD` line:

`=> => # qemu: uncaught target signal 11 (Segmentation fault) - core dumped`

seems to be some error related with the CPU architecture. Im using a MacBook Pro M1

**Comment by huanjani** [comment]
Ah. I see from your first comment that you have [`platform`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#platform) set as `linux/amd64`. Do you mean to have platform set as `linux/arm64`?

**Comment by mathiasnohall** [comment]
Yes I tried to change the platform in the manifest but I got this error: `App Runner services can only build on amd64 and x86_64 architectures`. I also tried to change the docker image architecture to linux-x64 but no luck

**Comment by huanjani** [comment]
Would you want to try making this an ECS-based service: a Load-Balanced Web Service or a Backend Service rather than an App Runner service (Request Driven Web Service)?

**Comment by mathiasnohall** [comment]
ok cool that worked! changed to `type: Load Balanced Web Service` and `platform: linux/arm64` and it now builds and deploys successfully to AWS ECS. now I just need to rearrange the dns and certificates :)

thanks!
