### ISSUE TITLE
S3 Permission Error with v1.23.0

### ISSUE THREAD

**Issue by erikosmond** [aws/copilot-cli#4194]
CAVEAT: If we have AWS premium support, is there a place we should open AWS copilot issues?

I have been using AWS copilot successfully for over a year using the following copilot setup

Eriks-MacBook-Pro-5@wormhole[main|…20⚑2] % copilot deploy
Name: wormhole-sched
Only found one environment, defaulting to: production
Environment production is already on the latest version v1.7.0, skip upgrade.
Eriks-MacBook-Pro-5@wormhole[main|⚑1] % copilot --version
copilot version: v1.13.0
Eriks-MacBook-Pro-5@wormhole[main|⚑1] % copilot app upgrade
Skip upgrading application demo to version v1.0.2 since it's on version v1.1.0.

I recently got a new computer and now have this version of the app

eriks-mbp@wormhole[main|✚1…1] % copilot app upgrade
Application demo is already on the latest version v1.1.0, skip upgrade.
eriks-mbp@wormhole[main|✚1…1] % copilot --version
copilot version: v1.23.0

which is producing this error when I run `copilot deploy`:
`✘ execute svc deploy: upload deploy resources for service gravity: upload custom resources for "gravity": upload custom resource "DynamicDesiredCountFunction": upload manual/scripts/custom-resources/dynamicdesiredcountfunction/acd1f00a18ceccc32a780fb208be61f3f6ELIDED.zip to bucket stackset-demo-infrastruc-pipelinebuiltartifactbuc-ELIDED: AccessDenied: Access Denied
	status code: 403, request id: ELIDED, host id: ELIDED+WGyrM8hLysJ2OYi0PzsGJfvNfWeTX1Jroi/Yg==`

**Comment by paragbhingre** [comment]
Hi @erikosmond I am looking into your issue. Stay tuned.

**Comment by paragbhingre** [comment]
@erikosmond May I know what is the version of your environment right now on the new machine? Because latest environment version is `1.13.0`. Could you please check that once for me and let me know?

You can check that by going to cloudformation and checking the template section of the stack --> `<app>-<env>`

Also Copilot introduced environment manifests in  v1.20 which makes it important for older versions of environments to migrate to the new one. Here is a doc mentioning to how [migrate your environments](https://aws.github.io/copilot-cli/blogs/release-v120/#migrating-existing-environments).

Please let us know if you face any issue while migrating your environment.

**Comment by erikosmond** [comment]
Hi @paragbhingre Thanks so much for taking a look. That was really helpful information. I found this in cloudformation: EnvVersion: v1.7.0, so I followed your steps. I created the environment manifest file. I ran copilot env deploy, and now cloudformation shows EnvVersion: v1.13.0.

I then ran copilot svc deploy, the deployment starts off well, but my tasks start failing with this error in the ECS task:
`exec /app/bootscript.sh: exec format error` and then the container exits. 

My Dockerfile has always had this in it, and it's been running fine for the last year, until this upgrade:
ENTRYPOINT ["/app/bootscript.sh"]

I know `/app/bootscript.sh` exists and is executable. Does the exec format error look familiar?

**Comment by paragbhingre** [comment]
I see. I am not sure if this is related to the Copilot error or not. But I can take a look at it for you.
What machine are you on? Have you tried setting the [platform](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#platform) field in manifest?

**Comment by erikosmond** [comment]
Hi @paragbhingre Yes, I did indeed have to set the platform in the manifest as I moved from an intel laptop to an Apple Silicon machine. Deployment now successful! Huge thanks to you! 10/10!!

Have a great weekend.

PS: minor feature request, if the environment manifest is missing when using a newer version of the cli, maybe a warning message could be sent to the console?
