### ISSUE TITLE
Get the Subnet Url

### ISSUE THREAD

**Issue by dmathewwws** [aws/copilot-cli#4204]
Hi,

I have a Backend Service that I want to communicate with a Load Balanced Web Service. Currently it is doing do via the public elb url (http://XXX.us-west-2.elb.amazonaws.com). 

Is there a way to get the subnet private url so that I can communicate between the services without going through the public link?

Thanks :)

**Comment by paragbhingre** [comment]
@dmathewwws Thank you for your question. 
I think you can use service discovery endpoint of the Load Balanced Web Service to communicate with it without going through the public link. You can check service discovery endpoint by running `copilot svc show` command. You will see `COPILOT_SERVICE_DISCOVERY_ENDPOINT` variable inside Variables section. `COPILOT_SERVICE_DISCOVERY_ENDPOINT` has value in the form of `<env>.<app>.local` and if your service name is `frontend` then you can call your service internally through `frontend.<env>.<app>.local`

**Comment by paragbhingre** [comment]
@dmathewwws Thank you for your question.
I think you can use service discovery endpoint of the Load Balanced Web Service to communicate with it without going through the public link. You can check service discovery endpoint by running `copilot svc show` command. You will see `Service Discovery` section that shows service discovery endpoint of the service. 

Do let me know if you have any more questions.

**Comment by dmathewwws** [comment]
it worked great. Thx!

**Comment by paragbhingre** [comment]
I am glad that it worker for you! Feel free to open up this issue if you have any further questions :)
