### ISSUE TITLE
Unable to create a new .NET based App Runner service using copilot

### ISSUE THREAD

**Issue by hariohmprasath** [aws/copilot-cli#4210]
Hi Team,
I have a customer who is unable to create a new App Runner service using copilot CLI. The same worked for .NET6 but not working after the upgrade. The issue was reported in a tweet (https://twitter.com/MathiasNohall/status/1595156454411227136)

![FiMiNu-XkAAbEkB](https://user-images.githubusercontent.com/2615325/203474236-cd311808-4918-4b32-bcb6-bc3ca976112e.jpeg)

Regarding the next steps:
* Do you have any suggestions that you would recommend to the customer to work around this issue? 
* Do the team need any additional details or logs from the customer that would help them to root cause this issue faster, if so please share the detail part of this ticket

**Comment by paragbhingre** [comment]
@hariohmprasath thank you for raising this question to us. We are taking care of the same request in another [issue](https://github.com/aws/copilot-cli/issues/4191). Feel free track the other issue for the progress.
