### ISSUE TITLE
Adding container_insights to an old version app

### ISSUE THREAD

**Issue by doneumark** [aws/copilot-cli#4223]
Hi,
I recently saw the option of: container_insights, inside an environment maifest.yml, that I would like to use.
Problem is, my app was initialized about a year ago, when there was no environment manifest (at least not that i'm aware of), so I don't have any copilot/environment  folder.
I only have copilot/app/manifest.yml, where, at least according to the docs, there is no "container_insights" option.
How can I add this functionality to my app?

**Comment by Lou1415926** [comment]
Hello @doneumark! You can refer to the blog post [here](https://aws.github.io/copilot-cli/blogs/release-v120/#migrating-existing-environments) for how to create an environment manifest for an existing environment. 

After you run `copilot env show --manifest`, Copilot tries to read your environment configurations as best as it can and writes the configurations in the output it gives you. 

After you have the environment manifest under `copilot/environments/<env_name>/manifest.yml`, I think it'd be a good idea to first try to `copilot env deploy` before proceeding to enble `container_insights` in the manifest, just to make sure that you've successfully migrated to the manifest world!

**Comment by doneumark** [comment]
thank you!

**Comment by efekarakus** [comment]
Resolving this issue! Please feel free to re-open it if you have any questions :)
