### ISSUE TITLE
Increase storage space  for ecs by copilot 

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#4239]
Hi support ,
 I deployed our microservices by copilot into ecs , Here i am getting my storage as 30 GB  But our requirement is minimum 100 GB .
 Can you help to increase container storage space by manifest file .
 
 For your reference , I am sharing Manifest file and continer storage size.
![image](https://user-images.githubusercontent.com/78138014/205047886-f907b1b0-35d6-4eb3-bb87-7a646101bdd2.png)

![image](https://user-images.githubusercontent.com/78138014/205047239-93acd526-b8a7-4d95-8459-c71989497cf6.png)

**Comment by efekarakus** [comment]
Hi @Dhina-test !

Would the following `storage.ephemeral` setting work for you: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#ephemeral

```yaml
storage:
  ephemeral: 200
```

**Comment by Dhina-test** [comment]
@efekarakus , Thanks for the help

**Comment by efekarakus** [comment]
No problem! I'll resolve the issue now, feel free to write again if you run into a problem.
