### ISSUE TITLE
Lambda functions Nodejs runtime upgrade

### ISSUE THREAD

**Issue by Anushamuthukur14** [aws/copilot-cli#4241]
Hi,

We want to update the Nodejs runtime versions from 12.x to 16.x for the Lambda functions.

we were using an older copilot version (copilot-linux-v1.12.0) which creates node lambda on node12; latest copilot creates lambda on node16 - question is how do we get copilot to upgrade these for us since copilot manages the lambdas.

The Cloudformation contains the lambda resources. Copilot will create the cloudformation template and the pipeline will be deployed automatically. 

We have tried upgrading the copilot version from 1.12.0 to 1.24.0 but the Nodejs runtime version is not updated , it is still in 12.x.

Can anyone please help to sort out how do we upgrade the Nodejs Runtime versions from 12.x to 16. for the Copilot services.

Thanks in advance.

**Comment by Lou1415926** [comment]
Hello @Anushamuthukur14 ! Have you used the upgraded Copilot binary to run `copilot svc deploy`? This will update the CloudFormation template for your service which uses the 16.x runtime version.
