### ISSUE TITLE
Deploying linux/arm64 container

### ISSUE THREAD

**Issue by faisalil** [aws/copilot-cli#4245]
I am trying to see if I can try and deploy an linux/arm64 image to my setup. The service I am using is `Load Balanced Web Service`. I deployed it correctly to 2 environments and it worked okay. Now, I am trying to see if I can use `linux/arm64` platform to get the build to happen faster. I am running on a mac and the nodeJs docker build took ~30 mins when I had it as `linux/x86_64`.

What is did was to simply update the platform and made it `linux/arm64`. I did copilot deploy and the docker image was built correctly, however, now its stuck at the step of `An ECS service to run and maintain your tasks in the environment cluster`. It has been 20+ mins and it still didn't complete. Is there anything else I have to update for this configuration to work? Anything I can speicify so I can deploy arm64 images to ECS?

**Comment by iamhopaul123** [comment]
Hello @faisalil. It seems odd to me. If the Service spinning up takes too much time, could you please go to the ECS console and look at the service's events see what is going on there? If you see tasks keep getting spinning up and draining, could you look at one of the failed task and find the reason why it gets killed? Thank you!
