### ISSUE TITLE
Docs: Missing english language version of docs page "developing/service-discovery.ja.md"

### ISSUE THREAD

**Issue by a-poor** [aws/copilot-cli#4251]
On the documentation homepage (https://aws.github.io/copilot-cli), under the "Get started with architectures" section, the "Networking" link (see below) returns a `404`.

The link takes you to the following page: https://aws.github.io/copilot-cli/docs/developing/service-discovery

There is a Japanese-language version of this page ([service-discovery.ja.md](./site/content/docs/developing/service-discovery.ja.md)) but not an English-language version.

- ja documentation page: https://aws.github.io/copilot-cli/ja/docs/developing/service-discovery/
- ja markdown file: https://github.com/aws/copilot-cli/blob/mainline/site/content/docs/developing/service-discovery.ja.md

---

_Bad link from home to the docs' "Networking" page_
<img width="1338" alt="Screen Shot 2022-12-05 at 2 13 46 PM" src="https://user-images.githubusercontent.com/45295232/205754847-781df276-7ff2-45cb-949a-be7b94b791fd.png">

**Comment by iamhopaul123** [comment]
Hello @a-poor. Sorry we recently just renamed that file. I'll send out a quick fix for the doc. Thank you for reporting this bug!

**Comment by a-poor** [comment]
Thanks! 

(And thanks for working on copilot - big fan!)
