### ISSUE TITLE
Preview diff on deploy/package

### ISSUE THREAD

**Issue by dannyrandall** [aws/copilot-cli#4259]
This issue is a design proposal for adding a flag to `copilot [noun] deploy` and `copilot [noun] package` that previews changes that will be made to the existing cloudformation stack. This will show what changes Copilot will make to existing and new resources, which will become especially useful when testing/deploying extensions via https://github.com/aws/copilot-cli/issues/4208 or https://github.com/aws/copilot-cli/issues/4209.

## Proposal
A new flag, `--diff`, will be added to `deploy` and `package` commands that calculates and prints the diff between the deployed stack (including the addons stack!) and the stack that _will be_ deployed or generated.

After displaying the diff, `copilot [noun] deploy --diff` will prompt with a confirmation like:
```
Continue with deployment? [y/N]:
```
before deploying the proposed changes.

`copilot [noun] package --diff` will print the diff and exit. The exit code will be as follows:
0 = no diffs found
1 = diffs found
2 = error producing diff

This should allow for a script to skip deploying a stack if no changes will occur.

### UX Examples
Some examples of how a diff will look in different scenarios:

#### Adding a lambda function
```
~ Resources:
  + EnvControllerFunction:
    + Type: AWS::Lambda::Function
    + Properties:
      + Code:
        + S3Bucket: "s3://location"
        + S3Key: "s3://location"
      + Timeout: 900
      + MemorySize: 512
```

#### Adding a statement to an IAM Role `AssumeRolePolicyDocument`:
```
~ Resources:
  ~ TaskRole:
    ~ Properties:
      ~ AssumeRolePolicyDocument:
        ~ Statement:
          # (1 unchanged list entry)
          + - Action: "*"
              Effect: "Allow"
              Principal:
                Service: "ecs-tasks.amazonaws.com"
          # (2 unchanged list entries)
```

#### Updating an attribute of an IAM Role `AssumeRolePolicyDocument`:
```
~ Resources:
  ~ TaskRole:
    ~ Properties:
      ~ AssumeRolePolicyDocument:
        ~ Statement:
          # (1 unchanged list entry)
          ~ - Effect: "Allow" -> "Deny"
          # (2 unchanged list entries)
```

#### Changing the `ContainerPort` parameter
```
~ Parameters:
  ~ ContainerPort:
    ~ Value: 80 -> 443
```

**Comment by efekarakus** [comment]
Hi folks!!

I'm really excited to say that AWS Copilot v1.27 is out and preview with `--diff` is now supported! 🚀 

* Blog post: https://aws.github.io/copilot-cli/blogs/release-v127/#preview-aws-cloudformation-template-changes
* Release notes: https://github.com/aws/copilot-cli/releases/tag/v1.27.0

I'll close the issue now! If you have any questions, feedback, or suggestions please feel free to open new GitHub issues 🥳
