### ISSUE TITLE
Update regional resources with stack set "myapp-infrastructure"  [failed]

### ISSUE THREAD

**Issue by lexicalunit** [aws/copilot-cli#4266]
```
➜ copilot init
Welcome to the Copilot CLI! We're going to walk you through some questions
to help you get set up with a containerized application on AWS. An application is a collection of
containerized services that operate together.

Use existing application: No
Application name: myapp
Workload type: Load Balanced Web Service
Service name: myapp
Dockerfile: ./Dockerfile
Ok great, we'll set up a Load Balanced Web Service named myapp in application myapp listening on port 80.

✔ Proposing infrastructure changes for stack myapp-infrastructure-roles
- Creating the infrastructure for stack myapp-infrastructure-roles                           [create complete]  [50.5s]
  - A StackSet admin role assumed by CloudFormation to manage regional stacks                   [create complete]  [19.8s]
  - An IAM role assumed by the admin role to create ECR repositories, KMS keys, and S3 buckets  [create complete]  [19.4s]
✔ The directory copilot will hold service manifests for application myapp.

✔ Wrote the manifest for service myapp at copilot/myapp/manifest.yml
Your manifest contains configurations like your container size and port (:80).

- Update regional resources with stack set "myapp-infrastructure"  [failed]      [7.1s]
```

At this point if I hit Enter I just get that last error over and over again. I can ctrl+c out of it.

**Comment by efekarakus** [comment]
Hi @lexicalunit !

It looks like for an unknown reason the AWS CloudFormation StackSet failed to create 🤔 
Would you mind navigating to the following consoles to help us troubleshoot:

1. Navigate to the AWS CloudFormation console and click on "StackSets" in the left panel to choose "myapp-infrastructure"
![Screen Shot 2022-12-13 at 1 12 50 PM](https://user-images.githubusercontent.com/879348/207444697-f8e6cfbf-9889-425f-89ad-e40104bafedc.png)

2. Under the "Stack Instances" tab there should be a Status Reason that's potentially explaining why "myapp-infrastructure" failed. Would you mind sharing what you see?

![Screen Shot 2022-12-13 at 1 14 24 PM](https://user-images.githubusercontent.com/879348/207444941-9c9aa239-c75d-4267-9320-6bdb5422636b.png)

My hypothesis is that the credentials used to create "myapp-infrastructure" is lacking some permissions that's needed by Copilot while creating resources that are needed to create the infrastructure for your containerized app.

**Comment by lexicalunit** [comment]
@efekarakus I think what happened is I didn't realize that I could delete apps/services from the CLI using copilot and I tried to go and delete everything and I guess maybe I missed something? So now when I try to recreate the app with the same name it explodes. To unblock myself I've just started using `myapp2` as my app name for now. When I do a `app ls` command I see the old one is still there:

```shell
➜ copilot app ls
myapp
myapp2
```

But when I try to delete it, things explode again:

```shell
➜ copilot app delete --name myapp
Sure? Yes
✘ execute env delete: find service cloudformation stacks: AccessDenied: User: arn:aws:iam::355113744808:user/me is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::355113744808:role/myapp-main-EnvManagerRole
	status code: 403, request id: 0ba882ee-212f-465e-a728-2817d0745b2b
```

The thing is, I think I delete that role. If I got to AWS console and check for roles in IAM, that role does not exist. So it makes sense my user can't delete it. My user has `AdministratorAccess` permissions so it's not that it doesn't have the correct permissions to delete it.

Is there anyway I can blast the old `myapp` out of memory so that I can use that name again? Or is that app name just forever lost to me and I should just use the new one?

**Comment by lexicalunit** [comment]
@efekarakus There are no stack sets, I think I deleted all those manually.

**Comment by efekarakus** [comment]
Gotcha! 

Just to make sure is `myapp2` all going OK so far?

> Is there anyway I can blast the old myapp out of memory so that I can use that name again? Or is that app name just forever lost to me and I should just use the new one?

Yes! you can delete the old entry by navigating to the AWS Systems Manager console:
![Screen Shot 2022-12-13 at 3 17 13 PM](https://user-images.githubusercontent.com/879348/207465964-01fb5fca-3f82-42a2-acc5-4e9670a678cd.png)

And then clicking on "Parameter Store" in the left navigation panel, and then choose `copilot/application/oldapp` and delete the entry. 
AWS Copilot uses the Parameter Store as a "database" to look up metadata about your application. After that it should disappear from the options.

**Comment by lexicalunit** [comment]
> Just to make sure is `myapp2` all going OK so far?

Maybe? I got much further but now I'm seeing:

```
➜ copilot deploy -a myapp2 -e test
Only found one workload, defaulting to: myapp2
[+] Building 0.5s (20/20) FINISHED

[docker build logs omitted ...]

✔ Proposing infrastructure changes for stack myapp2-test-myapp2
- Updating the infrastructure for stack myapp2-test-myapp2                    [update in progress]  [1012.3s]
  - An ECS service to run and maintain your tasks in the environment cluster  [update in progress]  [994.1s]
    Deployments
               Revision  Rollout        Desired  Running  Failed  Pending
      PRIMARY  2         [in progress]  1        0        4       0
  - An ECS task definition to group your containers and run them on ECS       [update complete]    [2.8s]
```
And the number failed just keeps going up very slowly over time. Not sure why. Maybe my application is just blowing up over and over again because I haven't configured storage yet? So it's trying to connect to a nonexistent database. That's what I expect _should_ be happening anyway, but not sure why that would cause copilot to hang forever. I figured I'd get the deploy working first, then try to figure out database stuff.

> Yes! you can delete the old entry by navigating to the AWS Systems Manager console: ![Screen Shot 2022-12-13 at 3 17 13 PM](https://user-images.githubusercontent.com/879348/207465964-01fb5fca-3f82-42a2-acc5-4e9670a678cd.png)

That did it! 🎉

**Comment by lexicalunit** [comment]
Yep, found the logs in cloudwatch, my application is expectedly falling over again and again. How can I make copilot stop waiting for it to come up since that will never happen? Just ctrl+c out of the `copilot deploy -a myapp2 -e test` command?

**Comment by efekarakus** [comment]
Awesome! Almost there 😅 

Okay so by default Amazon ECS will stop the deployment once 10 failures are reached. Unfortunately that number isn't configurable so Copilot can't stop the deployment earlier :( 

One way of "hacking" and tricking copilot that the deployment is all good is by going to the Amazon ECS console and updating the service to have a desired count of 0. This will make it think that the deployment has succeeded.
![Screen Shot 2022-12-13 at 3 52 00 PM](https://user-images.githubusercontent.com/879348/207470354-ff5d5fc0-210d-4018-a1e2-0ab68a97b34c.png)


Afterwards, you can make your changes and run `copilot deploy -a myapp2 -e test` again and it should work fine.

**Comment by lexicalunit** [comment]
**Edit: Nevermind, I found it in `CloudFormation > Stacks`. There was one that was still in progress, so I cancelled it.**

---

Aw crud. I think I messed it up. I did actually ctrl+c out of the initial deploy b/c it was taking forever and I knew it wouldn't ever succeed. And now when I try to deploy I get an error saying it's already in progress:

```shell
➜ copilot deploy -a myapp2 -e test
[...]
✘ Proposing infrastructure changes for stack myapp2-test-myapp2
✘ execute svc deploy: deploy service myapp2 to environment test: deploy service: stack myapp2-test-myapp2 is currently being updated and cannot be deployed to
```

But if I look at the stack sets there's nothing in progress there. There's just one stack set named `myapp2-infrastructure` which is showing as status "ACTIVE".

**Comment by efekarakus** [comment]
Ohh how about regular CloudFormation stacks? Do you see `myapp2-test-myapp2` deploying there:
![Screen Shot 2022-12-13 at 4 12 37 PM](https://user-images.githubusercontent.com/879348/207472738-d55e0524-d675-49c4-9b91-e63955053c81.png)

I wonder if the cancellation is now _in progress_ and that's why it can't deploy. If the cancellation is also stuck on the ECS service, the updating service count to 0 trick should also work for it.

**Comment by lexicalunit** [comment]
Ty for all the help! ❤️
