### ISSUE TITLE
copilot app init --domain followed by copilot init fails due to HTTPSCert

### ISSUE THREAD

**Issue by lexicalunit** [aws/copilot-cli#4270]
I ran the following commands:

```shell
$ copilot app init --domain aws.spellbot.io
$ copilot init

Use existing application: No
Workload type: Backend Service
Service name: spellbot
Dockerfile: ./Dockerfile.bot
Deploy: Yes
```

And encountered the following errors. Everything else seemed to work except HTTPSCert.

```
The following resource(s) failed to create: [HTTPSCert]

- A Route 53 Hosted Zone for the environment's subdomain:

    The specified hosted zone contains non-required resource record sets
    and so cannot be deleted. (Service: Route53, Status Code: 400, Request
    ID: a28557c2-1a40-458a-a49e-27b84bb702c6, Extended Request ID: null)
    The specified hosted zone contains non-required resource record sets
    and so cannot be deleted. (Service: Route53, Status Code: 400, Request
    ID: 586c74d4-e434-42ce-9a67-e13c24fd4a1a, Extended Request ID: null)

- Request and validate an ACM certificate for your domain:

    Received response status [FAILED] from custom resource. Message return
    ed: Resource is not in the state certificateValidated (Log: /aws/lambd
    a/spellbot-test-CertificateValidationFunction-RYnN39hsF5fa/2022/12/14/
    [$LATEST]1d2aba50501a4172a4c4c1f0518ca852) (RequestId: f03478d7-1e1b-4
    164-a6ab-4656db5ab632)
    Received response status [FAILED] from custom resource. Message return
    ed: Cannot read properties of undefined (reading 'Name') (Log: /aws/la
    mbda/spellbot-test-CertificateValidationFunction-RYnN39hsF5fa/2022/12/
    14/[$LATEST]1d2aba50501a4172a4c4c1f0518ca852) (RequestId: 4f475642-c54
    4-4b6f-b466-98691b1a0fc0)
```

After hanging for over 20 minutes the process started emitting a line like the following 10 times a second until I killed it.
```log
- Creating the infrastructure for the spellbot-test environment.                     [update rollback complete cleanup in progress]  [1159.9s]
```

Note that I have 3 hosted zones, and one of them is my `aws.spellbot.io` HZ that I created manually before running the `copilot` commands. I then set up NS records for the Name servers created by that HZ in my DNS management tool of my personal website.

Should I have not done that? Is it confused because I manually set up the HZ myself?

**Comment by lexicalunit** [comment]
Actually, no, it seems like if I don't create the HZ myself, then I get an error. Here I am trying it with a different domain that I haven't set up manually in Route 53 yet:

```shell
$ copilot app init --domain test.spellbot.io
Note: The account does not seem to own the domain that you entered.
Please make sure that test.spellbot.io is registered with Route53 in your account, or that your hosted zone has the appropriate NS records.
To transfer domain registration in Route53, see:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-transfer-to-route-53.html
To update the NS records in your hosted zone, see:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/SOA-NSrecords.html#NSrecords
✘ get hosted zone ID for domain test.spellbot.io: hosted zone is not found for domain test.spellbot.io
```

**Comment by lexicalunit** [comment]
Wait, do I have to transfer registration for my domain to Amazon Route 53 for this to work?

**Comment by efekarakus** [comment]
Hi Amy! 

Apologies for the late response,

> Wait, do I have to transfer registration for my domain to Amazon Route 53 for this to work?

🤔 That's not necessarily the case, if this was set up "set up NS records for the Name servers created by that HZ in my DNS management tool of my personal website" then the hosted zone should be usable by AWS Copilot to create certificates for it. I wonder if somehow the content of the hosted zone is wrong and that's causing issues, the first and second step in this guide might help: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/migrate-dns-domain-in-use.html

There is also another alternative for getting `https://aws.spellbot.io` to work with Copilot: https://aws.github.io/copilot-cli/docs/developing/domain/#use-domain-in-your-existing-validated-certificates

So you can keep your existing, and navigate to [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/) to create a certificate for `aws.spellbot.io`. Then in your environment manifest, you can add the certificate to the load balancer: https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public-certificates
Then you can point to the `aws.spellbot.io` domain to the load balancer and it should work! 
However, the tradeoff is that it's a lot more steps than the `--domain` flag

**Comment by h5aaimtron** [comment]
@efekarakus I'm having a similar issue, albeit not the cert part. I delegated responsibility of a subdomain from my prod to a non-prod account which I setup a hosted zone for and everything. All my A records for static sites hosted out of S3 are working great, but when I try to do the copilot app init --domain dev.workstream.dept.ucla.edu it responds that the account doesn't seem to own that domain. It's odd. FYI that isn't the actual subdomain, just an example structure in case depth is an issue.

**Comment by efekarakus** [comment]
@lexicalunit 

OK I've just purchased a new domain name 😂 outside of Route53 https://efekarakustest.com/ and can see that it works.
The steps I have taken are like this:
1. Purchase efekarakustest.com from another provider.
2. Go to the Route53 console, and create a new hosted zone named `efekarakustest.com`.
3. Copy the 4 NS records for the hosted zone from the AWS console.
4. Go to page of the other registrar and paste the 4 custom name servers.

After these steps, the hosted zone can now be safely used by Copilot to deploy an application with `copilot app init --domain efekarakustest.com`


@h5aaimtron 
Did you see this warning message? 
```
Note: The account does not seem to own the domain that you entered.
Please make sure that efekarakustest.com is registered with Route53 in your account, or that your hosted zone has the appropriate NS records.
To transfer domain registration in Route53, see:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-transfer-to-route-53.html
To update the NS records in your hosted zone, see:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/SOA-NSrecords.html#NSrecords
```
If so I think our warning message is unnecessarily scary, if you have updated the NS record the hosted zone's name servers then feel free to ignore the warning.

Continuing with the other steps and deploying a load balanced web service should still work.

**Comment by lexicalunit** [comment]
> @lexicalunit
> 
> OK I've just purchased a new domain name 😂 outside of Route53 https://efekarakustest.com/ and can see that it works. The steps I have taken are like this:
> 
> 1. Purchase efekarakustest.com from another provider.
> 2. Go to the Route53 console, and create a new hosted zone named `efekarakustest.com`.
> 3. Copy the 4 NS records for the hosted zone from the AWS console.
> 4. Go to page of the other registrar and paste the 4 custom name servers.
> 
> After these steps, the hosted zone can now be safely used by Copilot to deploy an application with `copilot app init --domain efekarakustest.com`

Interesting, I think that's pretty much what I tried.

1. I own `spellbot.io` from another provider.

2. I created a hosted zone for `aws.spellbot.io` 
![Screenshot 2022-12-14 at 4 22 38 PM](https://user-images.githubusercontent.com/1903876/207743710-dcedf2b6-011d-4a5f-90b0-8f2e87ae4813.png)

3. I copied the 4 NS records from the AWS hosted zone.

4. I then added NS records in my DNS management page on the hosting provider where I purchased `spellbot.io`.
![Screenshot 2022-12-14 at 4 24 47 PM](https://user-images.githubusercontent.com/1903876/207744096-0a7eed42-7a82-4b37-867a-783dc30e2afb.png)

5. Then I ran:

    ```shell
    copilot app init --domain aws.spellbot.io
    copilot init
    ```

Maybe I needed to wait a little longer for DNS to propagate or something? I'll try again.

**Comment by lexicalunit** [comment]
Hrm, same error again. Here's the cloudwatch logs:
```log
START RequestId: 7da3038a-2e28-4eec-92e4-6981f513f59e Version: $LATEST
2022-12-15T00:40:10.564Z	7da3038a-2e28-4eec-92e4-6981f513f59e	INFO	UPSERT DNS record into Hosted Zone OMIT: _beb7d9e49841fe8097e9424163d645e9.test.spellbot.aws.spellbot.io. CNAME OMIT.OMIT.acm-validations.aws.
2022-12-15T00:40:10.569Z	7da3038a-2e28-4eec-92e4-6981f513f59e	INFO	UPSERT DNS record into Hosted Zone OMIT: _beb7d9e49841fe8097e9424163d645e9.test.spellbot.aws.spellbot.io. CNAME OMIT.OMIT.acm-validations.aws.
2022-12-15T00:40:41.608Z	7da3038a-2e28-4eec-92e4-6981f513f59e	INFO	Caught error ResourceNotReady: Resource is not in the state certificateValidated.
END RequestId: 7da3038a-2e28-4eec-92e4-6981f513f59e
REPORT RequestId: 7da3038a-2e28-4eec-92e4-6981f513f59e	Duration: 40779.51 ms	Billed Duration: 40780 ms	Memory Size: 512 MB	Max Memory Used: 85 MB	Init Duration: 460.48 ms	
START RequestId: 5d5e8209-cb28-4ff2-a548-f44af0dcf57d Version: $LATEST
2022-12-15T00:41:03.641Z	5d5e8209-cb28-4ff2-a548-f44af0dcf57d	INFO	Waiting for certificate arn:aws:acm:us-east-1:355113744808:certificate/5f4fc856-029a-48cb-b4c2-c9ce0ddbc814 to become unused
```

Edit: Also as I understand it I only need one CAA record for the root domain and it should apply to subdomains:
![Screenshot 2022-12-14 at 4 52 55 PM](https://user-images.githubusercontent.com/1903876/207746968-0ca71087-0627-4cde-b339-65ae27d9a0ae.png)

**Comment by efekarakus** [comment]
Which region are you deploying in? ACM certificate validation can sometimes take a long time, and we have a timeout for the Lambda function that creates the certificate for 15 mins 💭 . 

I wonder if we are running into a timeout issue 😢 if so I think the safest bet would be to not use `--domain` flag, create the ACM certificate separately, and update the environment manifest to use the ACM certificate.

**Comment by lexicalunit** [comment]
> Which region are you deploying in? ACM certificate validation can sometimes take a long time, and we have a timeout for the Lambda function that creates the certificate for 15 mins 💭 .

I've been trying us-east-1. It does seem like it takes about 15 minutes for the error to occur.

**Comment by lexicalunit** [comment]
> There is also another alternative for getting `https://aws.spellbot.io` to work with Copilot: https://aws.github.io/copilot-cli/docs/developing/domain/#use-domain-in-your-existing-validated-certificates
> 
> So you can keep your existing, and navigate to [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/) to create a certificate for `aws.spellbot.io`. Then in your environment manifest, you can add the certificate to the load balancer: https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public-certificates Then you can point to the `aws.spellbot.io` domain to the load balancer and it should work! However, the tradeoff is that it's a lot more steps than the `--domain` flag

This is ultimately what I did 👍🏻

**Comment by lexicalunit** [comment]
Actually, I thought I had it, but it doesn't seem to be working. Here's what I did:

First, in AWS I went to `AWS Certificate Manager > Certificates`. Then I created one for `aws.spellbot.io`. I copied that ARN and used it as the value for the parameter ` --import-cert-arns` in the `copilot env init` command.

```shell
$ copilot init
Use existing application: No
Application name: spellbot
Workload type: Load Balanced Web Service
Service name: spellbot
Dockerfile: ./Dockerfile
Deploy: No

$ copilot env init --import-cert-arns arn:aws:acm:us-east-1:355113744808:certificate/OMIT
Environment name: test
Credential source: [profile default]
Default environment configuration? Yes, use default.

$ copilot env deploy --name test

$ copilot deploy -a spellbot -n spellbot -e test
```

My service was deployed successfully to http://spell-Publi-1RYOHJZRU3DWD-2051968828.us-east-1.elb.amazonaws.com however https://aws.spellbot.io/ can not be reached.

I still have all the name server DNS stuff set up from earlier too, as described here: https://github.com/aws/copilot-cli/issues/4270#issuecomment-1352399912

**Comment by efekarakus** [comment]
👋 good morning!

Ok gotcha! so I'm thinking that if you open the manifest for the "test" environment it should look like this:
```yaml
# In copilot/environments/test/manifest.yml
name: test
type: Environment
http:
  public:
      certificates:
      - arn:aws:acm:us-east-1:355113744808:certificate/OMIT
```
What we need to do next is now specify the `aws.spellbot.io` as an [`alias`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) for your load balanced web service.

So in the manifest file for the `spellbot` service, we need to update it like this:
```yaml
# In copilot/spellbot/manifest.yml
name: spellbot
type: Load Balanced Web Service

http:
  alias: 'aws.spellbot.io'
```
Once the alias field is added hopefully https://aws.spellbot.io/  should work!

The reason why we require `alias` is that it's possible the certificate is for various domains, so we need to know which one to use. Alternatively, you can also say I want "aws.spellbot.io" and "other.spellbot.io" to all go to the ECS on Fargate service.

**Comment by efekarakus** [comment]
Oh I should add once the `http.alias` field is set in the Load Balanced Web Service you'll need to also add A-records to the `aws.spellbot.io` hosted zone [[1]](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html#routing-to-elb-load-balancer-configuring) [[2]](https://aws.github.io/copilot-cli/blogs/release-v118/#certificate-import) so that requests are routed to the application load balancer.

**Comment by h5aaimtron** [comment]
@efekarakus yeah definitely got that message. What I learned, and I guess I should have known by now, is that even though you pass a root hosted zone, copilot will not when using an alias create more than a single hosted zone off of that. If your root is example.com, you can't set an alias like api.appName.example.com as appName.example.com doesn't exist or may not be owned by copilot. We temporarily renamed to appName-api.example.com to get around for the moment.

**Comment by lexicalunit** [comment]
@efekarakus So I added this section to `copilot/environments/test/manifest.yml`:

```yaml
http:
  public:
      certificates:
      - arn:aws:acm:us-east-1:355113744808:certificate/OMIT
```

And I got all the way to `copilot deploy -a spellbot -n spellbot -e test` but it errored out with:
```log
  - Update your environment's shared resources                                                       [update rollback complete]  [321.5s]
    The following resource(s) failed to create: [HTTPSListener].
    - A security group for your load balancer allowing HTTPS traffic                                 [delete complete]           [16.9s]
    - A security group for your load balancer allowing HTTP traffic                                  [delete complete]           [14.6s]
    - An Application Load Balancer to distribute public traffic to your services                     [delete complete]           [121.7s]
    - A load balancer listener to route HTTPS traffic                                                [delete complete]           [2.8s]
      Resource handler returned message: "The certificate 'arn:aws:acm:us-ea
      st-1:355113744808:certificate/OMIT' mu
      st have a fully-qualified domain name, a supported signature, and a su
      pported key size. (Service: ElasticLoadBalancingV2, Status Code: 400,
      Request ID: 618e4d58-2e15-4332-b1a9-dabe4875ac92, Extended Request ID:
       null)" (RequestToken: OMIT, HandlerEr
      rorCode: InvalidRequest)
```

Just to review, these are the commands I did, in order:

```shell
$ copilot init
Use existing application: No
Application name: spellbot
Workload type: Load Balanced Web Service
Service name: spellbot
Dockerfile: ./Dockerfile
Deploy: No

# At this point I created the ACM cert for aws.spellbot.io and copy/pasted the arn for the next command:

$ copilot env init --import-cert-arns arn:aws:acm:us-east-1:355113744808:certificate/OMIT
Environment name: test
Credential source: [profile default]
Default environment configuration? Yes, use default.

$ copilot storage init
Only found one workload, defaulting to: spellbot
Storage type: Aurora Serverless
Storage resource name: spellbot-cluster
Database engine: PostgreSQL
Initial database name: spellbot

$ copilot env deploy --name test

$ copilot secret init -a spellbot -n SPELLTABLE_AUTH_KEY
$ copilot secret init -a spellbot -n BOT_TOKEN

$ copilot deploy -a spellbot -n spellbot -e test
```

**`copilot/environments/test/manifest.yml`**:
```yaml
name: test
type: Environment

http:
  public:
      certificates:
      - arn:aws:acm:us-east-1:355113744808:certificate/OMIT

observability:
  container_insights: false
```

**`copilot/spellbot/manifest.yml`**:
```yaml
name: spellbot
type: Load Balanced Web Service

image:
  build: Dockerfile
  port: 80

http:
  path: '/'
  alias: aws.spellbot.io
  hosted_zone: OMIT # the hosted zone id I manually created for aws.spellbot.io, from earlier

cpu: 1024      # cpu units / task
memory: 2048   # memory MiB / task
count: 1       # task count
exec: true     # allow commands in container
network:
  connect: true

environments:
  test:
    variables:
      LOG_LEVEL: INFO
    secrets:
      BOT_TOKEN: /copilot/spellbot/test/secrets/BOT_TOKEN
      SPELLTABLE_AUTH_KEY: /copilot/spellbot/test/secrets/SPELLTABLE_AUTH_KEY
```

**Comment by lexicalunit** [comment]
> Oh I should add once the `http.alias` field is set in the Load Balanced Web Service you'll need to also add A-records to the `aws.spellbot.io` hosted zone [[1]](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html#routing-to-elb-load-balancer-configuring) [[2]](https://aws.github.io/copilot-cli/blogs/release-v118/#certificate-import) so that requests are routed to the application load balancer.

Could not having done this cause the `"The certificate '...' must have a fully-qualified domain name, a supported signature, and a supported key size.` error? Because I haven't done this yet.

**Comment by efekarakus** [comment]
This error is odd:
> "The certificate 'arn:aws:acm:us-east-1:355113744808:certificate/OMIT' must have a fully-qualified domain name, a supported signature, and a supported key size. (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: 618e4d58-2e15-4332-b1a9-dabe4875ac92, Extended Request ID: null)" (RequestToken: OMIT, HandlerErrorCode: InvalidRequest)

It seems to indicate that somehow the certificate doesn't have the appropriate data?

Here are the steps for creating the certificate:
1. Navigate to the ACM console to request a certificate
<img width="1691" alt="Screen Shot 2022-12-15 at 10 44 14 AM" src="https://user-images.githubusercontent.com/879348/207942362-6c4be3e0-3a5c-4f21-8830-010161ec24a9.png">

2. Enter your domain name (and optionally more names if you'd like)

<img width="1453" alt="Screen Shot 2022-12-15 at 10 44 55 AM" src="https://user-images.githubusercontent.com/879348/207942424-d7105cd5-bdf9-4101-a0c7-528b061b7360.png">

3. Grab the CNAME records for DNS validation for your certificate

<img width="2204" alt="Screen Shot 2022-12-15 at 10 47 18 AM" src="https://user-images.githubusercontent.com/879348/207942737-10a66f2b-543a-445d-8be2-a4e15e882473.png">


4. Navigate to the hosted zone and add the CNAME records

<img width="1195" alt="Screen Shot 2022-12-15 at 10 49 45 AM" src="https://user-images.githubusercontent.com/879348/207942980-53caa7b4-5dcf-42ca-8678-dfd7124ad5e5.png">

**Comment by lexicalunit** [comment]
I'd done everything except for step 4 there, maybe that was the issue?

**Comment by lexicalunit** [comment]
@efekarakus So I did the last step, 4, and created the CNAME record using the record name and value from the cert I created in ACM. Same error as before: "... must have a fully-qualified domain name, a supported signature, and a supported key size."

**Comment by efekarakus** [comment]
According to https://stackoverflow.com/a/72401336/1201381 it means the certificate hasn't been validated yet.

If you navigate back to the certificate UI does it say that the status is now validated?

**Comment by lexicalunit** [comment]
It says `Pending validation` ... maybe it takes a couple days?

**Comment by lexicalunit** [comment]
It seems like I need to do something on my DNS management page for spellbot.io, outside of AWS, to validate? From: https://docs.aws.amazon.com/acm/latest/userguide/dns-validation.html

It looks like I need to create a CNAME record, maybe? At least that's what "If you are not using Route 53 as your DNS provider, you need to manually enter CNAME records provided by ACM into your provider's database, usually through a website." sounds like to me. So maybe for me, that step 4 with the CNAME record, should have been done outside of AWS?

**Comment by lexicalunit** [comment]
Hrm... it doesn't seem like DNS validation is working. I guess maybe I just need to wait longer, but from everything I can find on google it seems like it should have worked by now.

**Comment by efekarakus** [comment]
Hmm yeah, typically DNS validation is pretty quick - which makes me think that something else is going 🤔 

I wonder if the CNAME record in the route53 hosted zone is entered correctly?

1. The record name should only be `_a4b8440427a09b980fdb600180cffa55` don't put the `.aws.spellbot.io.` suffix in the record name
2. The CNAME value should be the entire string given by ACM: `_2bb0cb251ce1ecc7f51e14cb558f07ff.pmgvbzmzyk.acm-validations.aws.`

**Comment by lexicalunit** [comment]
I tried a bunch of different variations. I tried:
- `_bc3d0d63716f1155909944d3147cef7c.aws.spellbot.io.aws.spellbot.io`
- `_bc3d0d63716f1155909944d3147cef7c.aws.aws`
- `_bc3d0d63716f1155909944d3147cef7c.aws.spellbot.io`
![Screenshot 2022-12-15 at 2 38 44 PM](https://user-images.githubusercontent.com/1903876/207982112-df54d5d3-1e89-478d-9181-2f34727a8ab2.png)

Nothing seems to work. Might just have to transfer the domain to Route53 to make things work.

**Comment by efekarakus** [comment]
I think we might want just `_bc3d0d63716f1155909944d3147cef7c` in the name can we try that as well 🥺 

Your screenshot looks right though 🤔

**Comment by efekarakus** [comment]
@h5aaimtron We've updated the warning based on your feedback so we should no longer give a scary message unless the NS records for the domain don't match https://github.com/aws/copilot-cli/pull/4281

**Comment by efekarakus** [comment]
hi @lexicalunit !

OK I just did some investigating, let me know if I'm missing something:
```
$ dig spellbot.io NS +short
ns58.domaincontrol.com.
ns57.domaincontrol.com.
```
```
$ dig aws.spellbot.io NS +short # returns nothing
```

I assume that there is a hosted zone in route53 for `aws.spellbot.io` but the NS records for the hosted zone are not copy/pasted in GoDaddy. For each NS record in the hosted zone, we would need to create one like this:
<img width="1008" alt="Screen Shot 2022-12-16 at 9 04 58 AM" src="https://user-images.githubusercontent.com/879348/208150978-87f62fd1-5b68-482c-8d02-69b10c31bdf4.png">

I _think_ this is why the certificate isn't getting validated 🤔 . As far as I can tell, ACM won't validate the certificate if the subdomain `aws.spellbot.io` itself cannot be looked up.

**Comment by matthewhembree** [comment]
Hi @lexicalunit!

Hopefully I can help. Focusing on getting the Copilot ACM automation. It's likely that your CAA record is causing the issues. If you have not modified it, that's the root cause.

Perform the following:
1. (AWS) Create a public hosted zone for `aws.spellbot.io`.
2. (Parent zone registrar) Take the 4 name server hosts and create NS records in the parent zone `spellbot.io`

Ref [A](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html)

Additionally, you will need to have a proper CA authorization record (CAA). They are hierarchical. CAs will search the most specific subdomain for authorization first (`aws.spellbot.io`, then `spellbot.io`)
[This](https://github.com/aws/copilot-cli/issues/4270#issuecomment-1352409201) shows that you have only authorized `letsencrypt.org` for your entire domain hierarchy. To ensure AWS ACM can issue certificates, you can do **one** of the following:
1. Add to the current CAA record in your parent domain. It looks like you could click `Add Parameter` in the DNS-CAA UI.
2. Create a new CAA record in your `aws.spellbot.io` subdomain. This allows you to restrict ACM to only issue certificates for the `aws.spellbot.io` subdomain.

Refs [A](https://aws.amazon.com/premiumsupport/knowledge-center/acm-troubleshoot-caa-errors/) [B](https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html)

You will need to add this data into either CAA record:
```
0 issue "amazon.com"
0 issue "amazontrust.com"
0 issue "awstrust.com"
0 issue "amazonaws.com"
```

If you do option # 2, it should look like this:
![image](https://user-images.githubusercontent.com/47449406/211441252-a84c4221-1c48-4d86-b373-7ac78d1fc194.png)


After that you should be able to begin to use Copilot.

```sh
# The following will create a new Route53 hosted zone of ${AppName}.${DomainName}
copilot app init --domain aws.spellbot.io

# If you elect to deploy as part of the `copilot svc init`,
# a 'test' environment will be created, and
# a new Route53 hosted zone of test.${AppName}.${DomainName} will be created.
#
# Next an ACM certificate *request* will be created for
# test.${AppName}.${DomainName} and *.test.${AppName}.${DomainName}.
#
# The ACM DNS validation records (CNAMEs) will be automatically added to the test.${AppName}.${DomainName}
# Route53 hosted zone.
copilot svc init
```

The AWS ACM console will show you the status of the certificate issuance.
