### ISSUE TITLE
Copilot cli installation via brew is failing recently due to some sam dependencies

### ISSUE THREAD

**Issue by nandubatchu** [aws/copilot-cli#4290]
Installation via brew was working perfectly fine until last week. Pasting the error faced currently for reference.

```
> brew install aws/tap/copilot-cli
==> Tapping aws/tap
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/aws/homebrew-tap'...
remote: Enumerating objects: 4655, done.
remote: Counting objects: 100% (755/755), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 4655 (delta 641), reused 662 (delta 566), pack-reused 3900
Receiving objects: 100% (4655/4655), 699.52 KiB | 529.00 KiB/s, done.
Resolving deltas: 100% (3511/3511), done.
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-nightly.rb
aws-sam-cli-nightly: undefined method `on_intel' for #<Class:0x0000000002c09980>
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb
aws-sam-cli: undefined method `on_intel' for #<Class:0x0000000002cac8b0>
Error: Cannot tap aws/tap: invalid syntax in tap!
```

**Comment by KollaAdithya** [comment]
Hi @nandubatchu

- I just tried to reproduce the issue but it worked out.

- The error above makes it look like the issue with the `SAM CLI` and not the `copilot CLI `

- Can you try to `brew uninstall aws/tap/aws-sam-cli`  and install copilot cli to see if that fixes the issue
- If the error still persists, Alternatively if you don't want/can’t use brew, they you can install the CLI directly with `curl` following these instructions: [https://aws.github.io/copilot-cli/docs/getting-started/install/](https://aws.github.io/copilot-cli/docs/getting-started/install/)

You can run the below command for the macOS platform 
`curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-darwin && chmod +x copilot && sudo mv copilot /usr/local/bin/copilot && copilot --help`

**Comment by Tumble17** [comment]
Is this the official Homebrew? https://formulae.brew.sh/formula/copilot

**Comment by dannyrandall** [comment]
No, the official homebrew is https://github.com/aws/homebrew-tap. You can follow the install instructions [here](https://aws.github.io/copilot-cli/docs/getting-started/install/).
