### ISSUE TITLE
Pass `--target` option from the service `manifest.yml` to `docker build` command run in Build phase of a pipeline

### ISSUE THREAD

**Issue by GorreriFranco** [aws/copilot-cli#4307]
Hi!

I'm moving from doing the deploys by running locally `copilot deploy` to creating a pipeline to automate them. 

In my service `manifest.yml` I added the `target: production` option when running `docker build`. That worked as expected when running `copilot deploy`. But now that I'm building the image on the BUILD phase inside my pipeline, I noticed in the CodeBuild logs that the `--target production` option is missing on the docker build command:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/40183872/209678365-55920cf9-3e46-4b99-80fe-bdd213560c01.png">

Is this a bug? Should I specify how to run the docker build command elsewhere now that I'm using the copilot pipeline?

Thank you in advance!

**Comment by huanjani** [comment]
Hello, @GorreriFranco!

I wonder if you're experiencing the same thing described in [this issue](https://github.com/aws/copilot-cli/issues/3742). Let us know if the solution described there works for you!
