### ISSUE TITLE
Associate WAF ACL with ALB

### ISSUE THREAD

**Issue by lgarvey** [aws/copilot-cli#4319]
Hi,

I've seen this issue crop up in the past with some CFN workarounds.

It'd be great if we could do something like:

```
http:
    waf-acl-arn: ......
```

Are there any plans to allow associating WAF with ALB in the copilot config?

Cheers,
Lyndon

**Comment by paragbhingre** [comment]
@lgarvey, we are planning on supporting WAF ACL through [environment level addons](https://github.com/aws/copilot-cli/issues/4219) which is not released yet though. But there is a workaround for that using [workload addons](https://github.com/aws/copilot-cli/issues/2254#issuecomment-861658890). I hope this helps you.

**Comment by lgarvey** [comment]
HI @paragbhingre yes, that seems fine.   We can actually hold out until environment level addons are available.

Thank you!
