### ISSUE TITLE
copilot env package: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tuomassiren** [aws/copilot-cli#4321]
$ uname -a
Linux xxx 5.10.135-122.509.amzn2.x86_64 #1 SMP Thu Aug 11 22:41:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ copilot -v
copilot version: v1.22.0

$ copilot env show
Only found one environment, defaulting to: dev
About

  Name        dev
  Region      eu-west-2
  Account ID  xxxx

Workloads

  Name             Type
  ----             ----
  xxx  Load Balanced Web Service

Tags

  Key                  Value
  ---                  -----
  copilot-application  xxx-dev
  copilot-environment  dev

% copilot env package -n dev --upload-assets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12ddede]

goroutine 1 [running]:
github.com/aws/copilot-cli/internal/pkg/describe.NewEnvDescriber({{0xc0003b2470, 0x9}, {0xc0000392e9, 0x3}, 0x0, {0x0, 0x0}, {0x0, 0x0}})
        /codebuild/output/src864945534/src/internal/pkg/describe/env.go:78 +0x7e
github.com/aws/copilot-cli/internal/pkg/cli/deploy.NewEnvDeployer(0xc0005be6f0)
        /codebuild/output/src864945534/src/internal/pkg/cli/deploy/env.go:112 +0x2cd
github.com/aws/copilot-cli/internal/pkg/cli.newPackageEnvOpts.func2()
        /codebuild/output/src864945534/src/internal/pkg/cli/env_package.go:112 +0xbb
github.com/aws/copilot-cli/internal/pkg/cli.(*packageEnvOpts).Execute(0xc0004055f0)
        /codebuild/output/src864945534/src/internal/pkg/cli/env_package.go:153 +0x24d
github.com/aws/copilot-cli/internal/pkg/cli.run({0x1f0cd70, 0xc0004055f0})
        /codebuild/output/src864945534/src/internal/pkg/cli/cli.go:98 +0x59
github.com/aws/copilot-cli/internal/pkg/cli.buildEnvPkgCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
        /codebuild/output/src864945534/src/internal/pkg/cli/env_package.go:282 +0x65
github.com/aws/copilot-cli/internal/pkg/cli.runCmdE.func1(0xc00039c000?, {0xc0003fcba0?, 0x3?, 0x3?})
        /codebuild/output/src864945534/src/internal/pkg/cli/cli.go:72 +0x7b
github.com/spf13/cobra.(*Command).execute(0xc00039c000, {0xc0003fcb70, 0x3, 0x3})
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc00034d400)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /codebuild/output/src864945534/src/cmd/copilot/main.go:34 +0x25

**Comment by paragbhingre** [comment]
Hi @tuomassiren, I am so sorry to hear that you faced this issue. I could reproduce this issue on my local, so I will look more into it. Meanwhile, could you please upgrade to the latest version of Copilot? The latest version doesn't seem to have this issue. I tried it by myself, and it works fine.

**Comment by paragbhingre** [comment]
Hello @tuomassiren, I can confirm that this bug was resolved in the next release itself i.e. v1.22.1 patch release. could you please try upgrading to the latest version of Copilot and confirm if it resolves your problem?

**Comment by tuomassiren** [comment]
Upgraded to 1.24, works. Closing issue. Thanks.
