### ISSUE TITLE
Add Task and Cluster definiton and values with app show

### ISSUE THREAD

**Issue by VaZark** [aws/copilot-cli#4324]
I'm setting up a github action workflow as the autogenerated copilot pipeline does not fit my requirements.

As a part of the deployment to ECS, I need to specify the cluster and service names. However the `copilot app show --json` command shows only the semantic name used to refer to the env setup. I want to fetch the actual cluster and service names associated with the resources to use with `aws ecs updae-service`

**Comment by VaZark** [comment]
I found issue #791  that supposed to deal with this but I'm unable to find the `describe` subcommand under app command as mentioned in the associated PR

**Comment by paragbhingre** [comment]
@VaZark Currently, we do not have any commands that show actual cluster and service names. But you can try using `copilot svc show --resources` which should expose the service ARN to you, which consists of a cluster and service name.
