### ISSUE TITLE
Github Actions rate-limited from accessing Copilot

### ISSUE THREAD

**Issue by zackdotcomputer** [aws/copilot-cli#4336]
Hey Copilot team - not sure who best to raise this with but we've started getting a deploy error on Github Actions:
```
API rate limit exceeded for 40.84.170.98
```
when attempting to deploy with copilot.

We are making our requests authenticated, of course, so are unsure how best to proceed or with whom to raise the issue.

**Comment by Lou1415926** [comment]
@zackdotcomputer 🤔Weird - I am not sure what is causing this. Does this only occur when you have `copilot` command in the steps? What about after the rate_limit is [reset](https://docs.github.com/en/rest/rate-limit?apiVersion=2022-11-28#get-rate-limit-status-for-the-authenticated-user)? What public actions are you using?

**Comment by zackdotcomputer** [comment]
@Lou1415926 Very weird indeed! Looking into it, I'm not 100% sure either but it's possible that this is in a different part of the copilot supply chain than the copilot <-> aws link (it might be in the GHA <-> npm link instead). I'm going to close this and will reopen if I can track down more precisely that this is happening in an interaction with an Amazon-controlled surface.
