### ISSUE TITLE
svc deploy: Resource handler returned message: "Invalid request provided: CreateService error: SC service is already used by ...

### ISSUE THREAD

**Issue by tuomassiren** [aws/copilot-cli#4337]
I'm trying to deploy a load-balanced web service and getting an error at deployment:

  - An ECS service to run and maintain your tasks in the environment cluster                [delete complete]       [0.0s]
    Resource handler returned message: "Invalid request provided: CreateSe                                          
    rvice error: SC service is already used by arn:aws:servicediscovery:eu                                          
    -west-2:329873754284:namespace/ns-r2enqwrp7ezscumk (Service: AmazonECS                                          
    ; Status Code: 400; Error Code: InvalidParameterException; Request ID:                                          
     9fe805e1-dbbc-4899-86c5-5b0149aa9bc0; Proxy: null)" (RequestToken: 76                                          
    8f0053-cfe7-f6de-2a57-a42e942c15ab, HandlerErrorCode: InvalidRequest)                                           

There might be some remains from earlier failed pipeline runs and/or manual deployments.
I've deleted the app and env several times, no stacks remain.
What do I need to delete?

**Comment by tuomassiren** [comment]
Or is there a limit on svc name length? Mine is xxxxx-xxxx-xxxx-xxxxxxxxxx

**Comment by Lou1415926** [comment]
Hello @tuomassiren ! This looks like the issue [here](https://github.com/aws/copilot-cli/issues/4313).

There is currently an issue with SC, and the service team is actively working to fix this. To quote an email that AWS sent out earlier last week:
> We have identified an issue that can cause errors with ECS Service Connect when ECS circuit breakers are enabled and trying to recreate a deleted service. The service is left in a state where it cannot be recreated after deletion. However, there is no impact to already running tasks.

As mentioned in [#4313](https://github.com/aws/copilot-cli/issues/4313#issuecomment-1372638002), our suggestion for you right now is to temporarily turn of SC. After the service team rolls out the fix, we will let you know!

**Comment by tuomassiren** [comment]
OK, thank you!
