### ISSUE TITLE
The state machine IAM Role is not authorized to access the Log Destination

### ISSUE THREAD

**Issue by vrodriguezcl** [aws/copilot-cli#4338]
Hello team,
I'm getting an error trying to deploy a scheduled job using copilot to ecs.

![image](https://user-images.githubusercontent.com/92444358/211354135-826ea96e-239a-4ee5-b9af-23db91e29c58.png)

I granted already the iam permissions to the role to assume with this task: **LambdaFullAccess**, **ECSFullAccess**, **CloudWatchFullAccess**, **S3FullAccess**, and **ECRFullAccess**. I give this permissions with full access just to test purposes to avoid any issue trying to use copilot cli.

Im using copilot cli version: `version: v1.24.0, built for linux
`
Any idea of how can I solve this ?

**Comment by Lou1415926** [comment]
Hello @vrodriguezcl 👋🏼 Do you know if your application has permissions boundary? That is, was your application created  via `copilot app init --permissions-boundary` ?

**Comment by vrodriguezcl** [comment]
> I did already using this option, and it does not work. I created a policy with all required and mentioned permissions and without any luck :(.

**Comment by Lou1415926** [comment]
Gotcha. Thanks for the information! Are you comfortable with letting me take a look at the policy that you used for `--permissions-boundary`? Alternatively, can you take a look at that policy, and let me know what `log:` actions are there?

**Comment by vrodriguezcl** [comment]
> Gotcha. Thanks for the information! Are you comfortable with letting me take a look at the policy that you used for `--permissions-boundary`? Alternatively, can you take a look at that policy, and let me know what `log:` actions are there?

I have also tried with a fewer version of copilot, and the error persists. `version: v1.21.0, built for linux`

Here's the policy that Im using with the --permissions-boundary flag on copilot cli.

![image](https://user-images.githubusercontent.com/92444358/211429247-e01b1b17-1719-48c5-b4c6-af0db9fcc42d.png)

**Comment by Lou1415926** [comment]
@vrodriguezcl  I am wondering if there are other necessary permissions that are not explicitly listed on the AWS docs. 

Just for test purpose, if you want to try changing the permissions boundary policy to:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "*"
            ],
            "Resource": "*"
        }
    ]
}
```
We can see if `copilot job deploy` succeeds after that 🤔

**Comment by vrodriguezcl** [comment]
> @vrodriguezcl I am wondering if there are other necessary permissions that are not explicitly listed on the AWS docs.
> 
> Just for test purpose, if you want to try changing the permissions boundary policy to:
> 
> ```json
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "*"
>             ],
>             "Resource": "*"
>         }
>     ]
> }
> ```
> 
> We can see if `copilot job deploy` succeeds after that 🤔

Let me try this. I will notify you in few minutes.

**Comment by vrodriguezcl** [comment]
> @vrodriguezcl I am wondering if there are other necessary permissions that are not explicitly listed on the AWS docs.
> 
> Just for test purpose, if you want to try changing the permissions boundary policy to:
> 
> ```json
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "*"
>             ],
>             "Resource": "*"
>         }
>     ]
> }
> ```
> 
> We can see if `copilot job deploy` succeeds after that 🤔

Failed again.

![image](https://user-images.githubusercontent.com/92444358/211606186-81572227-cbbc-470c-9e7c-849c772daaad.png)

**Comment by Lou1415926** [comment]
I see! Then looks like it's not because of permissions boundary.

My second guess is CloudWatch resource policy became too long and hit the limit of 5120 characters. 

Every time the `StateMachine` resource is created, CloudWatch tries to update a resource policy so that `delivery.logs.amazonaws.com` has the permission to write logs to the designated log group. It keeps appending log groups to the resource every time a StateMachine is created, and eventually the policy document is too big.

Can you verify by doing the following:
1. Running `aws logs describe-resource-policies --region <the region you wanted to deploy the job to>`
2. Look for a policy named `AWSLogDeliveryWrite20150319`
3. Look at its `policyDocument`, check if it's over 5120 charaters. (Edit: originally I had a typo here that says "51820" but it's really "5120")
