### ISSUE TITLE
AWS Health Notification

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#4339]
We received a notification within our AWS Health Dashboard regarding our services deployed into ECS via copilot. The description provided is as follows:

_We have identified an issue that can cause errors with ECS Service Connect when ECS circuit breakers are enabled and trying to recreate a deleted service. The service is left in a state where it cannot be recreated after deletion. However, there is no impact to already running tasks. We have found your account has ECS service(s) that are at risk of encountering this issue._

We created our app/env/services with copilot cli 1.24.0 which is listed as the latest, so I would assume others may be getting this notification as well. I wanted to know if there is anything I can do to resolve the issue via copilot, my setup, or if a fix is in the works.

**Comment by Lou1415926** [comment]
Hello @h5aaimtron ! Given that your service has service connect enabled, the issue occurs when a deployment fails and triggers the circuit breaker. 

To avoid this from happening (after all, you can't say for sure if the deployment is definitely not going to trigger circuit breaker), until a fix is rolled out, our suggestion would be to disable service connect for your services temporarily. 

Related: https://github.com/aws/copilot-cli/issues/4337, #4313
