### ISSUE TITLE
Connection to a public RDS Aurora serverless v2 endpoint

### ISSUE THREAD

**Issue by PierFio** [aws/copilot-cli#4341]
Hello

I am trying to use the public interface of an Aurora Serverless v2 service from a copilot-deployed service.
I can access the RDS endpoint without problem from my local machine and I can telnet to a regular website from the container on port 80. However when I try to telnet the RDS instance on port 5432 from the container, telnet simply hangs.
I have read discussions about the compatibility between copilot and aurora V2, but I was assuming it only concerned having Aurora as an add-on to a deployed container. Now I wonder if this is why I cannot have a working connection or if I should look in another direction to solve this issue? Thank you for your help.

**Comment by Lou1415926** [comment]
Hello @PierFio ! My first guess is that it's because of how security groups are configured. Which service are you telnet-ing from? Which service is the RDS addon created under?

**Comment by PierFio** [comment]
Hello @Loo, thank you for your help. To answer your question:
I connected to the deployed container (copilot svc connect) and I was able to telnet to a regular website on port 80.
The RDS instance is not an add-on but installed with a public endpoint. I am able to connect to this endpoint from my local machine on port 5432 and it operates flawlessly. What I cannot do is: from the container, telnet the port 5432 of this public endpoint. If security groups are involved, the problem should be caused by a restriction of the outbound traffic from the container, but all traffic are apparently allowed.
Additionally, the name of the RDS instance appears to be correctly resolved by the DNS on the container side.

**Comment by Lou1415926** [comment]
@PierFio I did a little experiment myself. I created an Aurora Serverless v2 launched in the default VPC, and assigned it a security group that allows inbound traffic from anywhere. Note that this cluster is created outside of Copilot, like yours.

Just like in your case, I was able to `telnet <endpoint> <port, which is 3306 in my case)` into the instances from my local machine. The response I got:
```sh
Connected to <endpoint>
...<some gibberish string>
```

Then I `copilot svc exec` into one of my existing Copilot services, and run `telnet <endpoint> 3306`, I received the same response. I tried the same thing for a load balanced web service and a backend service, both succeeded. This is where mine differs from yours.

Therefore, it seems to be possible for Copilot services to connect with an Aurora cluster created outside of Copilot. You mentioned that the security group for your services allow all outbound traffic, what about the security group attached to your Aurora cluster? Does it allow traffic from the service's security group?

**Comment by PierFio** [comment]
@Lou1415926 This solves it, thank you a lot. But I do not understand the situation.
I had a look to the security group associated with the RDS VPC. It is the default one (used a very basic configuration during creation with allowing public access) with 2 rules for inbound traffic
1. Allow all traffics inside the sg
2. Allow all traffics from an IP address (which should be the Internet Gateway? Surprisingly this address is different from the address I get from the DNS resolution).
I added a third rule allowing all the traffic from anywhere as you did, and the telnet connected correctly.
Now I do not understand how could the inbound rules could behave differently for a traffic from the container to the public endpoint and a traffic from anywhere (my local machine) to this same endpoint? Is the traffic from the container not going through the gateway?

**Comment by PierFio** [comment]
OK, I understood it: the second rule was defined by default using the address of my own connection! Of course it was then working for me only. I feel a bit stupid, but at the same time the interface information is a bit unclear of what public means.

**Comment by Lou1415926** [comment]
Glad it worked out! 

I just have a bit more to add just in case! If you create your RDS in the same VPC as the services, you can allow ingress from the environment security group (named `<app>-<env>-EnvironmentSecurityGroup-<random_string>`), instead of anywhere. This allows all services from the environment to access RDS, without exposing the db to the world. 

The best practice is to allow ingress from only one service though. To do so, you can create your own security group, allow ingress from that security group, and then attach it to the service via [`security_groups`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-security-groups) field in the manifest.
