### ISSUE TITLE
Does Copilot cli have the ability to run ecs task locally

### ISSUE THREAD

**Issue by tkumark** [aws/copilot-cli#4342]
Is Copilot-cli a replacement for ecs-cli? In ecs-cli there is a command `ecs-cli local up --task-def-remote app-main:6` Is there a similar in Copilot?

**Comment by Lou1415926** [comment]
Thank you @tkumark  for the inquiry! Right now, this would be a feature request for us. However, discussions are happening around this feature and I am interested in learning what you expect to see if/when we do support something similar. Is there anything that you feel like is missing in ecs-cli that you’d like to see in Copilot?

**Comment by tkumark** [comment]
1) run task locally based on locally defined taskdefinition.
2) In the taskdefinition we define secretes and parameter store it should be able to pull those information
3) Should be able to test our the roles as part of local development. usually we find that some role is missing after deploying to aws.

**Comment by Lou1415926** [comment]
Related: #5137

**Comment by dannyrandall** [comment]
Hey @tkumark! We just released this feature in [v1.30.0](https://github.com/aws/copilot-cli/releases/tag/v1.30.0)!🚀🎉

We're still working on (3) that you specified - it's on our roadmap here: https://github.com/aws/copilot-cli/discussions/5263! Test `copilot run local` and share your feedback with us there!
