### ISSUE TITLE
Pipeline does not allow specifying the build image compute type

### ISSUE THREAD

**Issue by jaredsieling** [aws/copilot-cli#4345]
In the Pipeline manifest, the [build.image](https://aws.github.io/copilot-cli/en/docs/manifest/pipeline/#build-image) property allows you to chose the base Docker image to perform the CodeBuild stage in.  However, for each of those build images that AWS provides, there are different size options, which they call "computer type". You can see a list of those options [here](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html).

The problem is that the Pipeline manifest does not provide any way for us to set that compute type, meaning we are stuck with the default.  That is a problem when more RAM than 3GB is needed in the build commands.  As far as I can tell, there is no way to set that compute type in the buildspec.yml, either.  My current work around is to go into AWS console and set compute type manually in the CodeBuild's Build project settings, but then a redeploy of pipeline updates overwrites that.

A potential fix would be to add `build.compute_type` property to the pipeline manifest, or provide a way to pass more general set of parameters that would be set for the build environment.

**Comment by Lou1415926** [comment]
Hello @jaredsieling! This totally makes sense to me. In fact, there is already a feature request for this: https://github.com/aws/copilot-cli/issues/3143. Please give it a thumb-up to help us prioritize the feature!

**Comment by Lou1415926** [comment]
Hello @jaredsieling ! We've released `pipeline override` recently in [v1.29.0](https://github.com/aws/copilot-cli/releases/tag/v1.29.0). It allows you to override any CloudFormation fields in your pipeline stack. You can update your Copilot to the latest version and try it out!

Closing this issue for now. Feel free to reopen it if there are further questions!
