### ISSUE TITLE
Need better error message if Docker is not running

### ISSUE THREAD

**Issue by piradeepk** [aws/copilot-cli#437]
Running archer init - after the environments are created it asks me about which app I want to use, I select an app, but I'm not running Docker daemon, it currently errors out. As a user, it might be useful to add a message after the error to tell me what my next step should be (i.e. what command should i run after i start docker daemon to continue)

<img width="568" alt="Screen Shot" src="https://user-images.githubusercontent.com/44981951/69268316-bdbb2000-0b83-11ea-89c8-445fd28b00d2.png">

**Comment by sonofachamp** [comment]
@pkandasamy91 try running `service docker restart` and try again.

**Comment by efekarakus** [comment]
We now detect if the docker daemon is not running and limit the prompts to using only an existing image. Resolving the issue. https://github.com/aws/copilot-cli/pull/1821
