### ISSUE TITLE
Backend Service with Service Connect

### ISSUE THREAD

**Issue by niros1** [aws/copilot-cli#4376]
I tried to activate Service Connect to my service. 
```
network:
      connect: true
```
the result was a service without IP, the network section of the task is empty. 
what am I doing wrong?
Thanks

**Comment by iamhopaul123** [comment]
Hello @niros. You can verify if Service connect is enabled for your service by running `copilot svc show`. For example,

```
$copilot svc show
Only found one service, defaulting to: frontend
About

...

Internal Service Endpoint

  Endpoint                     Environment  Type
  --------                     -----------  ----
  frontend:80                  test         Service Connect
  frontend.test.demo.local:80  test         Service Discovery
```

> the result was a service without IP, the network section of the task is empty.

Can you elaborate this please? Thank you!

**Comment by niros1** [comment]
It is now Service Discovery because I roll it back because of this problem.
I can try to redeploy it with connect: true if thats what you mean 
On another service I have this configuraiton:
```
http:
  path: "service-name"
```
and svc show:
```
Endpoint                                     Environment  Type
  --------                                     -----------  ----
  service-name:8080                      prod, dev    Service Connect
  service-name.bv-labrain-be.local:8080  prod, dev    Service Discovery
```

**Comment by iamhopaul123** [comment]
Yeah it looks good to me. Also be aware of the indentation/space for yaml formatting.

**Comment by niros1** [comment]
bu I thought I need to add `connect: true ` to the network section.

**Comment by iamhopaul123** [comment]
Yeah that's what i meant. Just wanted to follow up: are you still experience any issue with Service Connect?
