### ISSUE TITLE
GH release for 1.25 references blog post without detail (CloudFront feature).

### ISSUE THREAD

**Issue by matthewhembree** [aws/copilot-cli#4381]
For The CloudFront feature:

I see the boilerplate added [here](https://github.com/aws/copilot-cli/pull/4349/files#diff-a33e3e3cccd9b18bc5e75faa7deffd23de5e5c5f914edbb1149696f85d2f2426R36).

But there's nothing but the header that's linked in the GH [Release](https://github.com/aws/copilot-cli/releases/tag/v1.25.0).

> Read the [blog post](https://aws.github.io/copilot-cli/blogs/release-v125/#static-content-delivery-with-cloudfront) for more!

I searched for pending PRs, but didn't find anything relevant.

**Comment by matthewhembree** [comment]
I see the formal [docs](https://aws.github.io/copilot-cli/docs/developing/content-delivery/), but just wanted to mention that the teaser was missing.

**Comment by iamhopaul123** [comment]
Hello @matthewhembree. Thank you for your interest in this feature! The section will be available once [this PR](https://github.com/aws/copilot-cli/pull/4355) gets merged.

**Comment by Lou1415926** [comment]
It's live now @matthewhembree !

**Comment by matthewhembree** [comment]
Thanks!
