### ISSUE TITLE
Unable to deploy basic nestjs app - failed to normalize image reference "./Dockerfile"

### ISSUE THREAD

**Issue by Mickaz89** [aws/copilot-cli#4386]
i am trying to deploy very basic nest js app to ECS using aws copilot .

   ` nest new my-app //Generate basic nest js app`

My Dockerfile 

```
    # Base image
    FROM node:18
    
    # Create app directory
    WORKDIR /usr/src/app
    
    # A wildcard is used to ensure both package.json AND package-lock.json are copied
    COPY package*.json ./
    
    # Install app dependencies
    RUN npm install
    
    # Bundle app source
    COPY . .
    
    # Creates a "dist" folder with the production build
    RUN npm run build
    
    EXPOSE 3000
    # Start the server using the production build
    CMD [ "node", "dist/main.js" ]
```

Then running copilot 

`    copilot init`

When asking for Dockerfile i am choosing ./Dockerfile
When asking for deploy test environment i choose yes 

At the end i can see the deploy failed 10 times and get 

`> ECS Deployment Circuit Breaker was triggered`

Then i go to the ECS console to check for STOPPED Tasks and i get this error message 

```
>  InternalError: failed to create container model: failed to normalize
> image reference "./Dockerfile". Launch a new task to retry.
```

Also i cheked on the ECR console that copilot create a repository but it is empty with no image
  
Thanks for your help 

Note: My Dockerfile is on my root project like this :

```
    > dist
    > node_modules
    > src
    > test
    Dockerfile
    package.json
    ...
```

**Comment by iamhopaul123** [comment]
Hello @Mickaz89. It looks strange to me that the ECR repository was empty. Did you see image building and upload when you ran `copilot init`? And could you go to the CloudFormation console and see what's the `ContainerImage` parameter for the service stack (with stack name to be `${AppName}-${EnvName}-${ServiceName}`)?

**Comment by Mickaz89** [comment]
<img width="789" alt="Capture d’écran 2023-01-19 à 21 47 22" src="https://user-images.githubusercontent.com/26713649/213544844-b7413e17-63ca-4c02-99c9-6eca19a58026.png">


> 
No i don't see any step of building docker image or publishing to ecr repository , also doesnt see any loggin information to ecr repository 
ContainerImage parameter is ./Dockerfile

**Comment by Mickaz89** [comment]
> Hello @Mickaz89. It looks strange to me that the ECR repository was empty. Did you see image building and upload when you ran `copilot init`? And could you go to the CloudFormation console and see what's the `ContainerImage` parameter for the service stack (with stack name to be `${AppName}-${EnvName}-${ServiceName}`)?

<img width="709" alt="213545558-03205f01-1cbb-4717-a964-ef2fe3c39bfd" src="https://user-images.githubusercontent.com/26713649/213548959-9e293b13-143e-48ca-9132-17ee0ad0b995.png">
<img width="789" alt="213544844-b7413e17-63ca-4c02-99c9-6eca19a58026" src="https://user-images.githubusercontent.com/26713649/213548980-c5258c3d-e5a8-4671-bed8-00f192aa3e5b.png">

No i don't see any step of building docker image or publishing to ecr repository , also doesnt see any loggin information to ecr repository

ContainerImage parameter is ./Dockerfile

**Comment by iamhopaul123** [comment]
Thank you @Mickaz89. Could you also share your service manifest (`manifest.yaml`) file? I wonder if `.Dockerfile` is filled in `image.location` instead of `image.build`.
