### ISSUE TITLE
CDN support for multiple s3 buckets

### ISSUE THREAD

**Issue by mlazar-endear** [aws/copilot-cli#4394]
Hi, I've been following along with issue https://github.com/aws/copilot-cli/issues/3701 and I'm excited to see S3 support added for Cloudfront. However, I don't think it fits for my use-case which I will outline below.

I have two load balanced web services operating in a single copilot environment, which I have assigned unique domains for.

- svc1.example.com
- svc2.example.com

I want each service to have its own S3 bucket for media files, and I want to serve those buckets through Cloudfront so I don't have to expose the raw bucket URLs.

- svc1.example.com/media/ -> s3://bucket1/media/
- svc2.example.com/media/ -> s3://bucket2/media/

What I've found with the current config in copilot v1.25 is that I can only specify a single global bucket on the cdn. And that it will apply that bucket route pattern to *every* subdomain defined in my copilot environment, since they're all going through the same cloudfront distribution regardless of the domain name.

```
cdn:
  static_assets:
    location: cf-s3-ecs-demo-bucket.s3.us-west-2.amazonaws.com
    alias: svc1.example.com  # This doesn't seem to do anything?
    path: media/*
```

Any ideas on how I can pull this off? My best guess so far is writing a Lambda@Edge function to update the s3 origin bucket based on the host header.

**Comment by iamhopaul123** [comment]
Hello @mlazar-endear. First of all, thanks for the feedback and interest in this feature! Using multiple S3 bucket with CloudFront is not available for now. We could easily add support for that but I am worried that it might not work for your use case below:

```
svc1.example.com/media/ -> s3://bucket1/media/
svc2.example.com/media/ -> s3://bucket2/media/
```

From my understanding CloudFront doesn't really support host header routing which means if you just can't have two S3 buckets configured with `/media/*` as the path because both `svc1.example.com/media` and `svc2.example.com/media` route to the same place.

> writing a Lambda@Edge function to update the s3 origin bucket based on the host header

I think that'll be the only way. In order to support that we could either simply expose `LambdaFunctionAssociations` for each origin or support it natively by creating the edge function under the hood (which i'm more inclined right now).

Also just curious, could you, by any chance, use the same S3 bucket or having different path for `svc1` and `svc2`? For example:

```
svc1.example.com/media1/ -> s3://bucket1/media/
svc2.example.com/media2/ -> s3://bucket2/media/
```

**Comment by mlazar-endear** [comment]
@iamhopaul123 

> From my understanding CloudFront doesn't really support host header routing which means if you just can't have two S3 buckets configured with /media/* as the path because both svc1.example.com/media and svc2.example.com/media route to the same place.

Thanks, that's what I gathered as well. It seems like the solution AWS is guiding me towards is to have a separate cloudfront distribution for each service's "site". I actually wouldn't mind doing that and just managing them myself, but I imagine copilot would overwrite the DNS records to point back to the ALB whenever I deploy.

I'm considering dropping the `http: alias` from my copilot config all together and just managing the custom domains and TLS certificates myself. This might be better for me in the long term anyway, because I don't feel great about my generated TLS certificate having a CN and a bunch of Subject Alt Names that expose the internals of my copilot environment.

> Also just curious, could you, by any chance, use the same S3 bucket or having different path for svc1 and svc2? For example:
> ```
> svc1.example.com/media1/ -> s3://bucket1/media/
> svc2.example.com/media2/ -> s3://bucket2/media/
> ```

I think I could get away with using a single S3 bucket along with per-directory access permissions for each service, like this:

```
svc1.example.com/media/ -> s3://bucket1/svc1/media/
svc2.example.com/media/ -> s3://bucket1/svc2/media/
```

But I definitely can't have the files exposed across all of my domains. In my case, I'm setting up a multi-tenant architecture where each web service will correspond to a different tenant's web portal (I don't want to use totally isolated environments because there will also be shared backend services and infra across all tenants). So exposing static files from svc1 on svc2's domain, even if the URL path is different, would be a bad look / a security issue.

**Comment by efekarakus** [comment]
Thank you so much @mlazar-endear for the added info! 

>  It seems like the solution AWS is guiding me towards is to have a separate cloudfront distribution for each service's "site". 

I can't think of an alternative either.

It sounds like a good feature request for Copilot could be supporting the `cdn` property within the `Load Balanced Web Service` manifest. For example:
```yaml
http:
   path: '/'

cdn: 
   alias: 'svc1.example.com'
   static_assets:
      path: 'media/*'
```
And the A-record for `svc1.example.com` points to the CloudFront distribution which routes requests to media/ to the bucket and the rest to the ALB.


---

Which makes me think I wonder if we can mitigate this feature request using service [`addons/`](https://aws.github.io/copilot-cli/docs/developing/addons/workload/).
Where within `addons/template.yml`, we can define a `Type: AWS::CloudFront::Distribution` that points to the service's bucket and shared load balancer.
However, like you've said the A-record would have to be managed separately I think :(

**Comment by mlazar-endear** [comment]
> Which makes me think I wonder if we can mitigate this feature request using service [addons/](https://aws.github.io/copilot-cli/docs/developing/addons/workload/).
> Where within addons/template.yml, we can define a Type: AWS::CloudFront::Distribution that points to the service's bucket and shared load balancer.
However, like you've said the A-record would have to be managed separately I think :(

Is the A-record the only roadblock that you can see for doing it this way?

Personally, I think an addon makes a lot of sense and I would prefer to go that route, because it gives me flexibility in configuring CloudFront if I want to setup custom error pages, add more s3 buckets, configure the caching policy, etc. CloudFront has a lot of options that people will want to twiddle with when they get to production environments.

**Comment by efekarakus** [comment]
> Is the A-record the only roadblock that you can see for doing it this way?

That's indeed the only blocker that I foresee!

> CloudFront has a lot of options that people will want to twiddle with when they get to production environments.

Yes definitely! Our goal with the `cdn` field in the Environment manifest was to provide a default experience for CloudFront that's easy to use for most common scenarios. However, I think otherwise using [environment addons](https://aws.github.io/copilot-cli/docs/developing/addons/environment/) and [workload addons](https://aws.github.io/copilot-cli/docs/developing/addons/workload/) for more advanced configurations is the way to go 🚀

**Comment by efekarakus** [comment]
I'll close the issue for now. Feel free to re-open it if you have any questions 👍
