### ISSUE TITLE
Using with multiple regions

### ISSUE THREAD

**Issue by gusgordon** [aws/copilot-cli#4395]
I have an app that uses websockets where I want to maintain low latency to users. I want multiple containers running in 2-3 different regions, so that servers are located close to my users and low latency can be maintained. Traffic should be routed to the nearest server (ie lowest latency).

Is this possible to achieve with Copilot? I'm wondering if I can launch one stack for each region (eg. one for Europe, one for North America), then put something in front of copilot, like Route 53, to route traffic.

Thanks for the help!

**Comment by efekarakus** [comment]
Hi @gusgordon !

> Is this possible to achieve with Copilot?

Yes! Please let me know what you think of these steps and if they work out for you.

1. If you'd like geolocation based routing, then I **do not** recommend using the `--domain` flag with `app init`. Instead, I'd recommend using imported certificates in your Environment manifest (for example: https://aws.github.io/copilot-cli/blogs/release-v118/#certificate-import)

2. 
>  I'm wondering if I can launch one stack for each region (eg. one for Europe, one for North America), then put something in front of copilot, like Route 53, to route traffic.

Yes, exactly this! You can run `copilot env init` multiple times and creating  production environments in different regions. For example:
```console
copilot env init -n prod-iad # production in us-east-1
copilot env init -n prod-dub # production in eu-west-1 
```

<details>
  <summary> You can set HTTPS endpoints to the load balancer by importing the certs in the environment manifests </summary>
  
  ```yaml
  http:
    public:
      certificates: 
      - arn:aws:acm:${AWS_REGION}:${AWS_ACCOUNT_ID}:certificate/13245665-cv8f-adf3-j7gd-adf876af95
  ```
</details>

3. Afterwards, you can launch[ Load Balanced Web Services](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/) in these environments, for example:
```yaml
name: web
type: Load Balanced Web Service

http:
  path: '/'
  alias: 'example.com'
```

4. Finally, in the hosted zone of `example.com`, you can use [Geolocation alias records](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values-geo-alias.html) to point customers to the right load balancer based on their location.
 Here is an example screenshot that I've done on my personal domain:
 
   ![Screen Shot 2023-01-23 at 1 16 22 PM](https://user-images.githubusercontent.com/879348/214164416-b92d98fa-e9b1-4684-b801-45222cd5a3d5.png)


Hope this helps!

**Comment by gusgordon** [comment]
Thank you! I will give this a shot.

**Comment by gusgordon** [comment]
@efekarakus trying this now! I was able to assign a certificate to both my `us-east-1` and `us-west-1` environments, and both are running now. Now, I'm trying to enable SSL on both and put them behind the same endpoint so that traffic is routed to the lowest-latency/closest one. Having a few issues/points of confusion - I might be missing something:

1. It looks like I need an application load balancer to use certificates. However, (I think?) websockets can only be used through a network load balancer. Is this right? If so, I won't be able to create secure websockets ie. via `wss://`.

2. My domain isn't hosted on Route 53, and my TLD (`.lt`) isn't allowed on R53. What should I do? I was thinking of doing this through Global Accelerator instead. Is it practical to create a setup here with SSL?

3. I define an alias through the service's `manifest.yml` file. E.g., like this:
```
http:
  path: '/'
  alias: app.example.lt
```
where I added a certificate for `*.example.lt` through Certificate Manager for both regions. How does the service "know" which environment to connect to, since the alias is at the service level? Like will this connect to my `us-east-1` or `us-west-1` environment? I'm sure I'm missing something in this case!

Thank for you all the help!

**Comment by efekarakus** [comment]
Hi @gusgordon ! 👋 

> 1. It looks like I need an application load balancer to use certificates. However, (I think?) websockets can only be used through a network load balancer. Is this right? If so, I won't be able to create secure websockets ie. via wss://.

According to the following docs: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html, it looks ALB should work fine with `wss`
> Application Load Balancers provide native support for WebSockets. You can upgrade an existing HTTP/1.1 connection into a WebSocket (ws or wss) connection by using an HTTP connection upgrade

I think whichever client-side library that you'll be using for establishing the websocket connection should handle the HTTP upgrade so I'd expect it to work 👍 


> 2. My domain isn't hosted on Route 53, and my TLD (.lt) isn't allowed on R53. What should I do? I was thinking of doing this through Global Accelerator instead. Is it practical to create a setup here with SSL?

I just tested this and it looks like even if the TLD isn't available in route53, you can still create a public hosted zone for `example.lt`. Therefore, it should be possible to delegate your domain to route53 (check out the 4 steps in [this comment](https://github.com/aws/copilot-cli/issues/4270#issuecomment-1352373191) for how)


> How does the service "know" which environment to connect to, since the alias is at the service level? 

Ok awesome, I'm glad you got the certificates applied to the ALB using the environment manifest 🚀 
The `alias` that's in the service level is going to be used as a setting within the Listener Rule of the ALB. Copilot will add conditions such that if the host header `app.example.lt` is in the request then the load balancer will forward the request to the service. Does that make sense?

To route the `app.example.lt` domain to the appropriate ALB, you will have to modify the route53 hosted zone `example.lt` with alias records of Geolocation type (like in the [previous comment ](https://github.com/aws/copilot-cli/issues/4395#issuecomment-1401098630) above)

| Record name      | Type | Routing policy | Differentiator| Value/Route traffic to |
| ----------- | ----------- |----------|------|------------|
| app.example.lt      | A       | Geolocation | Europe |  `EU env ELB dns name` |
| app.example.lt   | A        | Geolocation | North America | `NA env ELB dns name` |

Hope this helps!

**Comment by gusgordon** [comment]
@efekarakus thank you! After much trial and error, I finally got it working. Yep, an ALB worked for websockets, and added a subdomain into Route 53. I ended up using latency-based routing from Route 53. Thanks again!
