### ISSUE TITLE
Need to update security policy for loadbalancer by copilot

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#4414]
Hi support,

 we are deploying our services by copilot for our application. at the time of cluster creation   alb also created by copilot .
 Here security policy for loadbalancer is **ELBSecurityPolicy-2016-08**  we need to update the security policy version to **ELBsecurityPolicy-TLS-1-2-2017-01** by copilot , can you help.
 
![image](https://user-images.githubusercontent.com/78138014/214571977-109cc709-c71c-40d2-8ab9-e577ece0e464.png)

**Comment by efekarakus** [comment]
Hi @Dhina-test !

You can achieve this by updating your environment manifest's [`http.public.ssl_policy`](https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public-sslpolicy) field. This field was added on `v1.23` of copilot, so if you have an earlier version please update 🙏 

For example:
```yaml
name: test
type: Environment

http:
  public:
    ssl_policy: 'ELBsecurityPolicy-TLS-1-2-2017-01
```

I'm closing the issue for now, if you have any further questions please don't hesitate to reach out here.

**Comment by Dhina-test** [comment]
Hi @efekarakus , I updated copilot latest version , now i have v1.25.0
Then i updated in environment manifest file 
![image](https://user-images.githubusercontent.com/78138014/215025753-a93d6649-6ae4-46cf-9645-afff98a14ed9.png)
After, while deploying environment manifest file getting 'ELBsecurityPolicy-TLS-
    1-2-2017-01' not found
    
    
![image](https://user-images.githubusercontent.com/78138014/215026308-32476f35-b839-49a3-8d59-0bacb978d1e3.png)
can you help

**Comment by efekarakus** [comment]
It looks like there is a typo in the string in the manifest with a small 's'. The value should be `ELBSecurityPolicy-TLS-1-2-2017-01 `

**Comment by Dhina-test** [comment]
Thanks for your great supprot @efekarakus  Working now
