### ISSUE TITLE
Monorepo deployments with NX/Turborepo

### ISSUE THREAD

**Issue by doneumark** [aws/copilot-cli#4424]
Hi!

In a monorepo app with the following structure:
Apps: API, Client, Admin, Backend-services...
Packages: shared-ui, ORM, etc...

Is there a way to safely deploy the apps to different services, while having it all in a monorepo (single repository and branch in git), and even while using the pipeline feature?

The monorepo is set to be built with Turborepo, or NX, still undecided due to the way copilot can handle the deploy stage with both.

**Comment by efekarakus** [comment]
Hi @doneumark!

It's good to hear back from you :)

> Is there a way to safely deploy the apps to different services, while having it all in a monorepo

That should be totally okay, I can't think of any blockers 🤔 
If I'm understanding correctly, you'd be running `copilot svc init` multiple times and generate separate services for the apps:

```
copilot/
  api/
    manifest.yml
  admin/
    manifest.yml
  client/
    manifest.yml
  # other services...
```
The Dockerfiles in the individual manifests.yml can combine and use whichever package and app code.

There shouldn't be a problem with using monorepo and the pipeline feature either 👍 

Does that help?

**Comment by doneumark** [comment]
Very much!
1. So basically the "solution" is to edit the dockerfile to take only the build from the specific app folder, in each app.
Do you have an example of dockerfiles and pipeline file, of different services that can perform end-to-end test (involving all services) and afterward - deploy the right build to each cluster?
2. Also, do you have a recommendation/preference about deciding between NX and Turbopack, for working with copilot?
3. If I have a storage in RDS as well, would all services be able to access it? Can I control their permissions or to what tables they will have access to?

**Comment by efekarakus** [comment]
1.
> So basically the "solution" is to edit the dockerfile to take only the build from the specific app folder, in each app.

Yes! that's right :)

> Do you have an example of dockerfiles and pipeline file, of different services that can perform end-to-end test (involving all services) and afterward - deploy the right build to each cluster?

This isn't a monorepo setup but it might still provide some sample examples for inspiration: https://github.com/copilot-example-voting-app
For pipelines, we have some sample manifests in the docs here: https://aws.github.io/copilot-cli/docs/manifest/pipeline/ we're happy to help if you have further questions while trying to release the services with pipelines.
For performing end-to-end tests, I'd recommend checking out the [`test_commands`](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-test-cmds) field in the manifest.

2. 

> Also, do you have a recommendation/preference about deciding between NX and Turbopack, for working with copilot?

Unfortunately, I'm not familiar at all with either project 😅 But to be honest from Copilot's point-of-view the choice does not matter. I expect this decision to be encapsulated within the container image, and hence Copilot should be able to deploy either option just fine.

3. 
>If I have a storage in RDS as well, would all services be able to access it? Can I control their permissions or to what tables they will have access to?

It really depends on you as the architect. This discussion might help for architecture patterns for services to access RDS: https://github.com/aws/copilot-cli/discussions/4275

We also recently introduced [Environment Addons](https://aws.github.io/copilot-cli/docs/developing/addons/environment/) which simplifies defining RDS clusters that can be shared across services.

Hope this helps!

**Comment by doneumark** [comment]
Amazing answer, thank you @efekarakus! you've been very helpful!

**Comment by efekarakus** [comment]
I'll close this issue. Feel free to reach out to us if you have other questions 👍 !
