### ISSUE TITLE
If you keep deploying add-ons, you will reach the rate limit.

### ISSUE THREAD

**Issue by iamyukihiro** [aws/copilot-cli#4426]
When deploying the Backend Service (ECS/ECR) on a regular basis, if you repeatedly include CloudFormation templates in addons, you will be limited by StackSets quota and will not be able to deploy.

## Cause

FAILED StackSets are accumulated in nested Stacks when there are no changes in addons (CFn templates).

For example, FAILED StackSets have the following information.

### nest change set

```
# Status
FAILED

# Reason for status
The submitted information didn't contain changes. Submit different information to create a change set

# Execution status
UNAVAILABLE
````

Go to the root change set above and attempt to delete StackSets, but cannot do so because it has the following information.

### root change set
 
```
# Status
CREATE_COMPLETE

# Reason for status
-

# Execution status
EXECUTE_COMPLETE
````

I tried to delete the StackSets via AWS-CLI, but if the execution status is EXECUTE_COMPLETE, the StackSets cannot be deleted.
Therefore, FAILED StackSets will continue to accumulate and will not be deployable in the future.

## Error messages on commands

```
$ copilot svc deploy -e env -n foo
.
.
.
⠋oposing infrastructure changes for stack *****-env-foo
✘ deploy service foo to environment env: deploy service: wait for creation of change set copilot-****** for stack *****-env-foo: ResourceNotReady: failed waiting for successful resource state: ChangeSet limit exceeded for stack arn:aws:cloudformation:**************:************:stack/*****-env-foo-AddonsStack-*******/**********
```

## Good solution

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

The user guide provides the following information.

> 1000 stack sets

> To create more stack sets, delete stack sets that you don't need or request an increase in the maximum number of stack sets in your AWS account. For more information, see AWS service quotas in the AWS General Reference.

I think it is not a good idea to use AWS Copilot in the normal way and get stuck with the above quotas.
Is there a good solution?

**Comment by KollaAdithya** [comment]
Hello @iamyukihiro !

Currently Copilot creates a Nested Stack for Service Addons and environment Addons. Let us say you have the following structure.
```yaml
.
└── copilot
    └── webhook
        ├── addons     # Store addons associated with the service "webhook".
        │   └── mytable-ddb.yaml
        └── manifest.yaml 
```
Copilot creates a 
1. stack for `webhook` service [parent stack]
2. Nested stack for `addons` 

I have a clarification question to completely understand the issue.
> FAILED StackSets are accumulated in nested Stacks when there are no changes in addons (CFn templates).

**Is it possible to create either stackset or stackset instance with in a nested stack 🤔 ?**
I think it is not possible to create any `stackset or stackset instance` from a `nested stack`. Also Copilot does not create any stackset with addons, it just creates a `nested stack`.
