### ISSUE TITLE
Stream loadbalancer logs into s3 by copilot

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#4449]
Hi ,

we are trying to enable loadbalancer access logs to s3 by copilot env maifest file by below , 
![image](https://user-images.githubusercontent.com/78138014/216312062-b7f4e08e-509e-414a-b323-e9518aff4848.png)

While deploying its get roll back
![image](https://user-images.githubusercontent.com/78138014/216312347-097d7313-32f6-4c31-9318-98eee1273cf8.png)

Can you help

**Comment by KollaAdithya** [comment]
Hello @Dhina-test !
Are you trying to bring in your own S3 bucket or you want copilot create a bucket for you?
When importing your own bucket, you need to make sure that the bucket exists and has the required [bucket policy](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html#attach-bucket-policy) for the load balancer to write access logs to it.

**Comment by Dhina-test** [comment]
Hi @KollaAdithya ,

 I have already s3 bucket. In mycase i missed to set  s3 bucket policy . After adding bucket policy issue fixed .
 Thanks Much.

**Comment by KollaAdithya** [comment]
Glad that you are able to resolve. I will this issue for now. Feel free to open if you still face any issues.
