### ISSUE TITLE
Need to deploy services in new subnets by copilot beacuse of unavailable IP's status in current subnet

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#4457]
Hi ,

we are deploying our services in two private  subnets by copilot . but unfortunately we have unavailable ip's status in one subnet.
so i created new private subnet, then i replaced new subnet with unavailable ip status subnet in  env manifest file.

Then i tried to deploy env manifest file ,but it is getting rollback with some services using current subnet (unavailable ip's status subnet)status .
![image](https://user-images.githubusercontent.com/78138014/216814687-e3654538-e090-42dc-bd40-118f3998349e.png)

Can you help.

**Comment by huanjani** [comment]
Hi @Dhina-test! 
You could create a new environment and import the existing resources, including the new private subnet, then deploy the workloads into the new environment. If you'd like to fully move all of the workloads over to the new environment, you can run `copilot svc delete --env staging` to allow `copilot env delete -n staging` after all of the workloads are gone from that environment. 
Would that work for you?

**Comment by Dhina-test** [comment]
yes @huanjani , Thanks

**Comment by huanjani** [comment]
@Dhina-test, if you are faced with the situation of running out of IPs again, you could consider using the `network.vpc.placement` field to set placement to `private`-- this way, private IPs will be used instead of public ones. The downside is that it will cost more because NAT gateways will be created.

**Comment by Dhina-test** [comment]
@huanjani can you please provide some sample manifest file for an example

**Comment by huanjani** [comment]
Yes, in your workload manifests, add
```
network:
  vpc:
    placement: private
``` 
https://aws.github.io/copilot-cli/docs/manifest/backend-service/#network-vpc-placement
