### ISSUE TITLE
XRay with AWSXRayRecorder

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#4470]
I've configured x-ray within the manifest and have a sidecar container running, however; while using AWS's AWSXRayRecorder (.NET Core) library, nothing seems to ever go to CloudWatch under the XRay Service map or Traces. I'm wondering if there is some sort of config I would need to pass to that library to know about the sidecar and pass information there. Unfortunately, there doesn't appear to be a lot of great examples I could find that are combining copilot and AWSXRayRecorder.

**Comment by huanjani** [comment]
Hi, @h5aaimtron! Unfortunately, I'm not too familiar with X-Ray Recorder, but I wonder if you need to add IAM permissions. There is an example [here](https://aws.github.io/copilot-cli/docs/developing/sidecars) for just X-Ray; I'm not sure what else X-Ray Recorder may need.... I'll keep digging!

**Comment by berkayopak** [comment]
Hi @h5aaimtron, I think these permissions will fix the issue:
![image](https://github.com/aws/copilot-cli/assets/8148816/53578c1e-b9cb-4a79-badc-b7e2e9482ca7)

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeLogStreams",
                "logs:DescribeLogGroups",
                "xray:PutTraceSegments",
                "xray:PutTelemetryRecords",
                "xray:GetSamplingRules",
                "xray:GetSamplingTargets",
                "xray:GetSamplingStatisticSummaries"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}`

Also, you can add this custom policy to your environment manifest.yml like this : 
![image](https://github.com/aws/copilot-cli/assets/8148816/fc64f3e8-e8b8-4e4e-9c54-17ba84ff511a)

`permission_boundary: CustomPolicyName`
For ex, in my case: 
`permission_boundary: AWSDistroOpenTelemetryPolicy`

But if you don't want to automate this process as I described above, you can also add this custom created IAM policy to your 'Task Role' on ECS.

This worked for me, I hope it works for you too 👍

**Comment by h5aaimtron** [comment]
@berkayopak I understand the manifest.yml but how is the policy creation automated? Also, do we want to allow *?

**Comment by dannyrandall** [comment]
Hey @h5aaimtron - have you already tried setting [`observability.tracing: awsxray`](https://aws.github.io/copilot-cli/docs/developing/observability/)? Currently, that option only provides support for [OpenTelemetry Protocol traces](https://docs.aws.amazon.com/xray/latest/devguide/xray-dotnet-opentel-sdk.html), not XRay traces, but you could enable support for XRay traces with the following [YAML patch override](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/):
```
- op: replace
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/1/Command/0
  value: --config=/etc/ecs/ecs-default-config.yaml
```

**Comment by berkayopak** [comment]
> @berkayopak I understand the manifest.yml but how is the policy creation automated? Also, do we want to allow *?

No, not exactly, actually policy creation is not automated with this 'permission_boundary' part. You have to create your policy manually, but this is how you can automatically assign it to your TaskRole.
