### ISSUE TITLE
Add a CI Option for reduced clutter in Output Log

### ISSUE THREAD

**Issue by cmaerz** [aws/copilot-cli#4471]
Currently i get about 30-40k lines of Log output when I deploy my App via Gitlab CI. Because it updates every 1-2 Seconds or more.

There should be a way to reduce the output of the CLI for better overview, if sth fails.

**Comment by huanjani** [comment]
Hi @cmaerz! 
You should be able to do this by setting the environment variable `CI=true`. Please let us know if that works for you! 
Thanks!
