### ISSUE TITLE
Pipeline update should detect new applications

### ISSUE THREAD

**Issue by uttarasridhar** [aws/copilot-cli#449]
## add a new app to the project
```
$ ./archer app init
...
 ✔ Success! Wrote the manifest for scorekeep-frontend app at 'ecs-project/scorekeep-frontend-app.yml'
Your manifest contains configurations like your container size and ports.

✔ Success! Created ECR repositories for application scorekeep-frontend.
2019/11/20 20:22:30 Created Application with version 1
Recommended follow-up actions:
- Update your manifest ecs-project/scorekeep-frontend-app.yml to change the defaults.
- Run `archer app deploy --name scorekeep-frontend --env test` to deploy your application to a test environment.
```
## update pipeline
```
$ ./archer pipeline update
✔ Success! Successfully added pipeline resources to your project: scorekeep
✔ Success! Successfully updated pipeline: pipeline.yml
```

## Ask

Calling pipeline update after app init didn't add the app to the pipeline :( I also tried to do `$ ./archer pipeline init` again, but it was a NoOp also.

Instead, I deleted my pipeline and started `./archer pipeline init` and it created 1 pipeline with 2 apps. Hurray!

It'd be nice if pipeline update recognized addition of a new app and updated the stages accordingly.

**Comment by efekarakus** [comment]
I believe the current implementation does pick up new services in the repository if users run `copilot pipeline update` again. Resolving the issue!
