### ISSUE TITLE
 webstorm plugin copilot login issue

### ISSUE THREAD

**Issue by Ksondzyk** [aws/copilot-cli#4503]
when I try to enter I enter the confirmation code, there is a long download and nothing happens after downloading. I remain logged in

**Comment by Ksondzyk** [comment]
![image](https://user-images.githubusercontent.com/55708207/219303554-931fc69a-a940-485c-9927-0895ceedbaee.png)

**Comment by vatskus** [comment]
Problem copilot in VsCode! Today copilot doesn't work. Don't log in!

([INFO] [auth] [2023-02-16T08:08:49.816Z] Invalid copilot token: missing token: 403 
[ERROR] [default] [2023-02-16T08:08:49.818Z] GitHub Copilot could not connect to server. Extension activation failed: "Contact Support")

**Comment by paragbhingre** [comment]
Hello folks, I think you are posting this question in the wrong forum. This repo belongs to AWS Copilot and not Github Copilot. Posting this in Github Copilot would give you more traction. Closing this issue from our side.
