### ISSUE TITLE
Support Secrets in Request Driven Service

### ISSUE THREAD

**Issue by sfarley85** [aws/copilot-cli#4506]
According to the docs and some testing it looks like copilot currently only supports secrets in the Load Balanced ECS service, not a request driven apprunner one. According to this it looks like perhaps support for secrets was recently added to AppRunner: https://aws.amazon.com/about-aws/whats-new/2023/01/aws-app-runner-secrets-configuration-aws-secrets-systems-manager/

Would be great to be able to use secrets in such services.

**Comment by paragbhingre** [comment]
Thanks for this feature request, @sfarley85. Currently, we are actively working on this feature. Stay tuned for more updates!

**Comment by iamhopaul123** [comment]
Hello! The feature is now released in v1.26.0: https://github.com/aws/copilot-cli/releases/tag/v1.26.0
