### ISSUE TITLE
Unable to find or use Github Copilot in VS

### ISSUE THREAD

**Issue by littlehoneybunnytuttifruttipumpkinpie** [aws/copilot-cli#4553]
I subscribed to Copilot and used instructions at https://docs.github.com/en/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-visual-studio-code
This was several weeks ago and I use Visual Studio every day, yet I was never able to find Copilot anywhere in VS, despite long hours researching on Google where it is and how to invoke it. There is no Copilot icon at the bottom, there are no code suggestions, and I don’t see any signs of Copilot working. I’ve never seen any signs of Github Copilot in my Visual Studio, don’t know how it looks, how it works, what it does - all despite subscribing to it. There is no “activation” button for Copilot anywhere in Visual Studio, no dialogs, no pop-ups, nothing. How can I ever see this thing and try to use it?
Please let me know how to start using Copilot.

![image](https://user-images.githubusercontent.com/20084989/221375563-6734c78a-0929-4e2c-9b11-5201ec7fabcd.png)

**Comment by Lou1415926** [comment]
Hey there @littlehoneybunnytuttifruttipumpkinpie  this is AWS Copilot 👋🏼 Seems like you've landed on the wrong repo. But if you are looking to build your application on AWS ECS/App Runner in the future, this would be the right place to go 😄
