### ISSUE TITLE
Cannot delete an app

### ISSUE THREAD

**Issue by devoffisis** [aws/copilot-cli#4570]
I have a trouble in delete an app.
When I initialize an app, the terminal running copilot went down. Then I try to restart `copilot app init`, then I have the following message.

>If you want to create a new workspace reusing the existing application mydjango, please switch to the region where you created the application, and run `copilot app init`.
If you'd like to recreate the application and all of its resources, please switch to the region where you created the application, and run `copilot app delete`.
✘ application named "mydjango" already exists in another region

Furthermore I try to delete it, then I have the following message.

>get application mydjango: couldn't find an application named mydjango in account 573143736992 and region us-west-2

How can I delete miscreated app?

**Comment by devoffisis** [comment]
Sorry, I have self-resolved. I delete the CloudFormation stack in the AWS console.

**Comment by iamhopaul123** [comment]
Hello @devoffisis. I'm glad you've found your way out. I guess your default profile was in `us-west-2` before and then switched to another region to run `copilot app init` again. You can also switch back to the previous region and run `copilot app init` again to finish the app creation or `copilot app delete` to delete remaining resources.
