### ISSUE TITLE
Is it possible to deploy 2 services in the same environment with different domains?

### ISSUE THREAD

**Issue by faisalil** [aws/copilot-cli#4620]
In a single environment, is it possible to have 2 web services that have 2 different domains? lets say app.test.com and app2.test.com?

**Comment by KollaAdithya** [comment]
Hello @faisalil !
Yeah It is possible.
If you have created your application with `copilot app init --domain test.com`

For the first service you can set the alias in workload manifest to have
```
http
  alias: app.test.com
 ```
For second service, you can set alias as
```
http
  alias: app2.test.com
 ```
 Please let me if this works for you!
 
 Here the [doc](https://aws.github.io/copilot-cli/docs/developing/domain/#customized-domain-alias) that explains more about customized domain alias.
