### ISSUE TITLE
Add a 4th stage to CodePipeline to run postman/newman

### ISSUE THREAD

**Issue by menbatisiunissart** [aws/copilot-cli#4654]
Hello,

Im looking at adding a 4th stage to CodePipeline to run postman/newman, to follow the same CodePipeline  implementation as per this AWS blog:
https://aws.amazon.com/blogs/devops/automating-your-api-testing-with-aws-codebuild-aws-codepipeline-and-postman/

It looks like right now the only way to do this with copilot is to manually edit the Cloudformation template to add a 4th stage to CodePipeline.
(As per this existing issue here: https://github.com/aws/copilot-cli/issues/4552)

Or would you recommend another solution?

Thanks

**Comment by huanjani** [comment]
The ability to add pipeline stages is something we've been trying to get to for a long time, but haven't been able to yet, unfortunately. 

You can manually edit your pipeline's CloudFormation template, but beware that if you run `copilot pipeline deploy`, your changes will be reverted.

Is there any way to use the `test_commands` field to add it as an `Action` within the Deploy `Stage`?

**Comment by menbatisiunissart** [comment]
Thanks for the pointer.

Regarding `test_commands` i was looking for some more detailed documentation/examples about what commands are supported.

I am looking at running 2 commands:

- copy some files over from AWS S3:
  - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPIEnvironment.postman_environment.json" ./02postman/

- run `npx` to install and run `newman` (a node JS app available on npm)
  - npx newman run <collection_file>.json

And if possible use the `reports` capabilities of CodeBuild

**Comment by huanjani** [comment]
Our `test_commands` documentation is pretty scant, unfortunately: https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-test-cmds

I think you should be able to do the `npx` commands, but I don't think the pipeline has the necessary S3 permissions to access your bucket. CodeBuild `reports` looks cool! I'll open an issue to support that, so it stays on our radar.

**Comment by menbatisiunissart** [comment]
Thanks for the pointer.

`npx` command ran with no problems.

Also FYI, regarding `test_commands` documentation, i ended up following this Blog post which has a pretty good description and code example how to use `test_commands` for integration testing. That example can be easily adapted to run other integration testing like postman.

You may consider adding some of his examples in the documentation

- https://aws.amazon.com/blogs/containers/automatically-deploying-your-container-application-with-aws-copilot/
- https://github.com/nathanpeck/string-reverse
