### ISSUE TITLE
CreateServiceError: SC service is already used

### ISSUE THREAD

**Issue by byF** [aws/copilot-cli#4659]
While I'm aware of [the existing issues on the topic](https://github.com/aws/copilot-cli/issues?q=is%3Aissue+SC+service+is+already+used+is%3Aclosed), I want to confirm if the following behavior isn't a Copilot bug after all.

I've got a Copilot application with a set of services and two environments `dev` and `prod`.

Service A manifest has Service Connect turned on at the manifest top level.

```
network:
  connect: true
```

1. the deployment of  the service A to `prod` succeeds.
2. the deployment of  the service A to `dev` fails with
    ```
    Invalid request provided: CreateService error: SC service is already used by arn:aws:servicediscovery:us-west-2:071199777470:namespace/ns-ABC
    ```

So the interesting part is:
1. `ns-ABC` belongs to `dev` env
2. however there are Service Connect records created in this namespace during the `prod` deployment!

So I've checked the `prod` ECS service configuration and it's referencing `dev` Cloud Map namespace 😬

EDIT: Alright, so I guess it's because we were very early adopters of Copilot and some things changed: https://aws.github.io/copilot-cli/docs/developing/svc-to-svc-communication/#legacy-environments-and-service-discovery

What's the best way to upgrade our "legacy" env without recreating it?

**Comment by huanjani** [comment]
Hello, @byF!

I'm not sure which Copilot version you're using, but I'm guessing you don't have env manifests? If that's the case, please follow the instructions [here](https://aws.github.io/copilot-cli/blogs/release-v120/#migrating-existing-environments) to generate them. 

Let us know what happens after you upgrade to the latest Copilot version. 🤞🏼

**Comment by byF** [comment]
Heya, I'm using the latest copilot version 1.26, but it's true we don't
keep the environment manifests around.

**Comment by huanjani** [comment]
Hi @byF. Just checking in. Were you able to resolve your issue after updating your environments? As with the existing issues that you found (above), you could try disabling Service Connect to see if that will put you back in business. Unfortunately, it seems the old format of our service discovery endpoints (`{app name}.local` instead of `{env name}.{app name}.local` is causing this problem now that Service Connect has been introduced.

**Comment by byF** [comment]
@huanjani Hi, we got rid of service connect altogether as we realized we don't need it in this particular project.
