### ISSUE TITLE
Error when creating infrastructure for ECS

### ISSUE THREAD

**Issue by amarmashruwala** [aws/copilot-cli#4680]
Hi Guys, 
I was trying to deploy an application to ECS using copilot in the ap-southeast-1 region. i have previously deployed in ap-southeast-2 region and that is working.
When running copilot init or copilot app init i got the following error. What would this error be due to? thank you!
wait until stack chime-to-rtmp-infrastructure-roles create is complete: ResourceNotReady: failed waiting for successful resource state
It seems when i try to deploy in a different region i get this error. It works when deploying to ap-southeast-2.
Is this something to do with IAM permissions for a specific region, as i looked at the regions and they are enabled by default.
I had a look at cloudformation stack event log -
 AdministrationRole
CREATE_FAILED
chime-to-rtmp-adminrole already exists
not sure how to fix this.

**Comment by huanjani** [comment]
Hi, @amarmashruwala.

Are you trying to deploy the exact same app again? Instead, could you just run `copilot env init` to create a new environment of the same app in `ap-southeast-2`? Some context: https://aws.github.io/copilot-cli/docs/concepts/environments/

Let us know if that helps. Thanks!

**Comment by amarmashruwala** [comment]
Hi @huanjani huanjani
Yes i am trying to deploy exactly the same app again but this time in the same account and new region - ap-southeast-1 instead of ap-southeast-2
I just tried running copilot env init instead of copilot init:
Error: get application chime-to-rtmp configuration: couldn't find an application named chime-to-rtmp in account XXXXX and region ap-southeast-1

**Comment by huanjani** [comment]
Start out using the profile with `ap-southeast-2` configured, where your app is. When you run `copilot env init`, you will be prompted to select a profile. At that point you can choose credentials with `ap-southeast-1`. Does that make sense?
