### ISSUE TITLE
Failed create 'copilot' folder in current dir because an account named 'copilot' exists on Mac

### ISSUE THREAD

**Issue by idawnwon** [aws/copilot-cli#4681]
This thing really makes me laugh and cry 😂.

I just follow [the starter guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Copilot.html), very careful, step by step. It keeps saying `couldn't find an application associated with this workspace`.

Yes, there is no folder named 'copilot' in my current work directory. 

According to #3262, I tried `find / -name "copilot"`, on my Mac, there is an account named "Copilot", the home folder of it is 'copilot', so its folder is searched out. By that time, I believe this couldn't be the problem. My working folder is in my account, very deep, very far from the "Copilot" account.

According to #4195, I tried to find some where above `../../../../`, OMG, here comes the 'copilot' folder of that account. I `cd` into it, no manifest file is there.  I believe this couldn't be the problem, again.

I tried to uninstall copilot-cli, reinstall by another way. Restart computer ....

3 hours later, doesn't work. What pissed me off is, even I wanna give up with copilot-cli, I found no way to delete those already created apps. Deleted CloudFormation stacks in AWS Console, `copilot app ls`, they are still listed there.

Finally, I deleted the "Copilot" account. Problem gone. `copilot init`, a blink 'copilot' folder is created in my current work directory.

I know that this is really one edge case. But it reflects copilot-cli really has to give more explicit warning or errors to prevent user guessing where was the 'copilot' folder gone.

Whatever, I still wanna thank you guys for creating Copilot, really handy, after all. ❤️

**Comment by huanjani** [comment]
Hi @idawnwon! 

Thank you for telling us about your experience. If we had a warning in the docs, maybe on [this page](https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/), do you think that would prevent this from happening to someone else? Did you use the docs at https://aws.github.io/copilot-cli/, or just the starter guide you mentioned above? I'm just curious about the user experience. 

Also, for future reference, you can delete the traces of apps so they're not listed with `copilot app ls` by deleting them from your Systems Manager Parameter Store.

Thanks and sorry
Related: [#3294](https://github.com/aws/copilot-cli/issues/3294)

**Comment by idawnwon** [comment]
@huanjani, thank you for your timely reply! ♥️ 

> If we had a warning in the docs, maybe on [this page](https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/), do you think that would prevent this from happening to someone else?

As a newbie to AWS Copilot, I googled `AWS Copilot`, it guided me to [AWS doc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/getting-started-aws-copilot-cli.html). I didn't read anything on [this page](https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/) cause it was low ranking in Google search results. But, I read it just now, WOW, far detailed than that. Yes, this would be a very good place to contain more FAQ.

> ...by deleting them from your Systems Manager Parameter Store

Thanks! I feel shame that I didn't find it out by my own 🤣

Thanks again, for your active support! ♥️
