### ISSUE TITLE
Pipelines - Ignore changes on specific folder to prevent source stage from being triggered

### ISSUE THREAD

**Issue by GorreriFranco** [aws/copilot-cli#4694]
Hi! I have a copilot-cli pipeline set up and now I'm trying to add to the pipeline steps [semantic-release](https://semantic-release.gitbook.io/semantic-release/)

I'm having trouble preventing the pipeline execution from being triggered again when semantic-release pushes the latest build to the /dist folder in my repository. Is there a way on the manifest.yml of my pipelines to tell to ignore and not trigger the source stage when changes are being done to the /dist folder of my repository?

**Comment by paragbhingre** [comment]
Hi @GorreriFranco, Unfortunately, there is no field in the manifest that can stop pipeline triggering when there is a change in a certain folder of your repository. But one thing that I can think of is `requires_approval: true`, which will definitely not stop the pipeline from triggering but will not do any deployment until you approve it when you think it is the right time to do so. I know it's not the most efficient workarounds but I can only think of this for now. If I come across a better way, then I will definitely share it with you.
