### ISSUE TITLE
Documentation: Sidecar documentation needs update

### ISSUE THREAD

**Issue by hkford** [aws/copilot-cli#4704]
[Sidecar documentation](https://github.com/aws/copilot-cli/blob/mainline/site/content/docs/developing/sidecars.en.md?plain=1#L215) says AWS Copilot currently does not support local sidecar images.

> Currently, we only support using remote images for sidecars, which means users need to build and push their local sidecar images.

However, [AWS Copilot v1.27](https://aws.github.io/copilot-cli/blogs/release-v127/#build-and-push-container-images-for-sidecar-containers) announced support for local sidecar images.

> You can now build and push container images for sidecar containers just like you can for your main container. 

Therefore [Sidecar documentation](https://github.com/aws/copilot-cli/blob/mainline/site/content/docs/developing/sidecars.en.md?plain=1#L215) should be updated. If needed, I am prepared to create a pull request.

**Comment by paragbhingre** [comment]
@hkford  Thank you so much for spotting this one. We will update the documentation. But you are always welcome to make contributions. We encourage our customers to make contributions. Feel free to send out a PR.

**Comment by paragbhingre** [comment]
@hkford, Thank you so much for catching this one. Feel free to send out a PR.
