### ISSUE TITLE
Adding new resources to Copilot VPC with CDK

### ISSUE THREAD

**Issue by coding-velociraptor** [aws/copilot-cli#4713]
Hey team!

I'm trying to deploy a RDS Postgres instance alongside a load-balanced and worker service with the Copilot CLI.

My first thought was to use addons, as the additional resource has no need of modifying the Copilot constructs. However, I noticed that addons are only supported in CloudFormation templates. At the moment, I managed additional resources like the mentioned RDS Postgres instance through a separate CDK package in my project.

On second approach, I tried to create an environment override for the RDS instance by running `copilot env override --tool cdk --skip-resources`. This provided me with a template for an override, not an addon. In order to pass the VPC to constructs of CDK, I lookup the VPC like suggested [here](https://github.com/aws/aws-cdk/issues/14809#issuecomment-1411554148):
```ts
    private getVPC() {
        const cfnVpc = this.template.getResource('VPC') as ec2.CfnVPC;
        const privateSubnet1 = this.template.getResource('PrivateSubnet1') as ec2.CfnSubnet;
        const privateSubnet2 = this.template.getResource('PrivateSubnet2') as ec2.CfnSubnet;
        const publicSubnet1 = this.template.getResource('PublicSubnet1') as ec2.CfnSubnet;
        const publicSubnet2 = this.template.getResource('PublicSubnet2') as ec2.CfnSubnet;

        const vpc = ec2.Vpc.fromVpcAttributes(this, "ImportedVpc", {
            vpcId: cfnVpc.ref,
            availabilityZones: cdk.Fn.getAzs(),
            privateSubnetIds: [privateSubnet1.ref, privateSubnet2.ref],
            publicSubnetIds: [publicSubnet1.ref, publicSubnet2]
        });

        return vpc;
    }
```
and then later in the same stack:
```ts
new rds.DatabaseInstance(this, "Database", {
    vpc,
    vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS, // PRIVATE_ISOLATED is not supported
    },
});
```

However, it does not work and fails with: `Error: There is already a Construct with name 'undefinedSubnet2' in ImportedVpc [ImportedVpc]`. What do you suggest to be the best setup? 

Lastly, I believe it might be a common use case and could benefit from an example. 

Thank you for providing Copilot CLI for simple access tool to containerised applications on ECS.

Cheers!

**Comment by paragbhingre** [comment]
Hi @coding-velociraptor, The error that we see is kind of unrelated to what is happening here. So if you look at `availabilityZones: cdk.Fn.getAzs()` inside `ec2.Vpc.fromVpcAttributes` then must be returning the wrong number of values, and for Copilot we need `availabilityZones: [0, 1].map(i => cdk.Fn.select(i, cdk.Fn.getAzs()))` as we have 2 public and 2 private zones. If you make that change in your CDK code, then it should work. 
We tried it on our end, and it worked fine for us.

**Comment by efekarakus** [comment]
Just for your reference, here is the entire override code: https://gist.github.com/efekarakus/d9f367ed6eab7bbadd7f6fa9e13177b7 

Hope this helps!

**Comment by coding-velociraptor** [comment]
Thank you @paragbhingre and @efekarakus. It worked out! `copilot env deploy` takes care of secret, database and bastion host, now. Wonderful! One step closer to a single command deploy.
