### ISSUE TITLE
How to detect cloudwatch logs when they were issued

### ISSUE THREAD

**Issue by phasetr** [aws/copilot-cli#4728]
When I run some copilot commands, cloudwatch logs are as follows:

>- /aws/apprunner/aspdotnet-staging-web/2789d398a5234454bb6567587b013062/application
>- /aws/apprunner/aspdotnet-staging-web/2789d398a5234454bb6567587b013062/service
>- /aws/apprunner/aspdotnet-staging-web/2de8e88e23a04c20a1e41d31e89fc8c7/application
>- /aws/apprunner/aspdotnet-staging-web/2de8e88e23a04c20a1e41d31e89fc8c7/service

It is difficult to survey logs. I'd like to know which logs were issued and when. Can I customize log names, or some good methods?

**Comment by iamhopaul123** [comment]
Hello @phasetr can you elaborate what Copilot commands did you run? I tried to run `copilot svc logs` and this is what I got

```
instance/f18f0b380dc6468c /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
instance/f18f0b380dc6468c /docker-entrypoint.sh: Configuration complete; ready for start up
instance/f18f0b380dc6468c 2023/04/04 17:09:17 [notice] 1#1: using the "epoll" event method
instance/f18f0b380dc6468c 2023/04/04 17:09:17 [notice] 1#1: nginx/1.23.4
instance/f18f0b380dc6468c 2023/04/04 17:09:17 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
instance/f18f0b380dc6468c 2023/04/04 17:09:17 [notice] 1#1: OS: Linux 4.14.255-291-231.527.amzn2.x86_64
instance/f18f0b380dc6468c 2023/04/04 17:09:17 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:4096
instance/f18f0b380dc6468c 2023/04/04 17:09:17 [notice] 1#1: start worker processes
instance/f18f0b380dc6468c 2023/04/04 17:09:17 [notice] 1#1: start worker process 28
instance/f18f0b380dc6468c 2023/04/04 17:09:17 [notice] 1#1: start worker process 29
```

**Comment by phasetr** [comment]
Hi @iamhopaul123 !

I am sorry to write my commands, and I run commadns, e.g., `copilot svc deploy`. I get DB access errors, so I want to check debug messages.

Furthermore,

> /aws/apprunner/aspdotnet-staging-web/2789d398a5234454bb6567587b013062/application
> /aws/apprunner/aspdotnet-staging-web/2789d398a5234454bb6567587b013062/service
> /aws/apprunner/aspdotnet-staging-web/2de8e88e23a04c20a1e41d31e89fc8c7/application
> /aws/apprunner/aspdotnet-staging-web/2de8e88e23a04c20a1e41d31e89fc8c7/service

these are in the CloudWatch Logs explorer in VSCode extension, or the AWS CloudWatch console list. Of course drilled downing shows me datetimes, but I want to see them in the log group names!

For now I begin to follow your advice in log survey. Thank you!
