### ISSUE TITLE
copilot deploy give Access Denied

### ISSUE THREAD

**Issue by sodhigurpreetsingh** [aws/copilot-cli#4729]
Hello 

I am getting this error on deploying using copilot deploy..

33abe9f: digest: sha256:bf7197088cc2189815b055d7699280357da6a6c49e2fa8ed71b0a27c0fd34e16 size: 3055
✘ execute svc deploy: upload deploy resources for service api: upload custom resources for "api": upload custom resource "CustomDomainFunction": upload manual/scripts/custom-resources/customdomainfunction/766143c42de56c5ed0d0ab437557d8ca7872e1c12ae10e72515b0a0dc13b6faa.zip to bucket stackset-xxxxxx-xxxxx-pipelinebuiltartifactbuc-t2f8wk6kah4e: AccessDenied: Access Denied
        status code: 403, request id: H5QE0KM73S7SMTDV, host id: KHGKQjw8WG7RdoFTT9z6BrES2lclQbvjtNAfP9SHuhAnw8kRgWncluleFwpWHmPrNsN1F7cy2lY=

I have double checked my keys and region and they are all correct..

please help how can i troubleshoot this..

Thanks
Gurpreet

**Comment by iamhopaul123** [comment]
Hello @sodhigurpreetsingh, could you update Copilot to the latest version and then run `copilot env deploy` to deploy the environment again? After that you could do `copilot svc deploy` to deploy the service.
