### ISSUE TITLE
When I created the svc override (CDK), the copilot deployment failed.

### ISSUE THREAD

**Issue by gmae199boy** [aws/copilot-cli#4732]
hi
I'm currently trying to deploy a service using the CDK override.
However, when I run the `copilot deploy` command, it returns the

```
✘ Proposing infrastructure changes for stack app-env-servicename
✘ execute svc deploy: deploy service event-server to environment stage: deploy service: check if changeset is empty: create change set copilot-xxxxxxxxx-xxxx-xxxx-xxxx for stack app-env-servicename: ValidationError: Parameter values specified for a template which does not require them.
        status code: 400, request id: xxxxxxxxx-xxxx-xxxx-xxxx: describe change set copilot-xxxxxxxxx-xxxx-xxxx-xxxx  for stack app-env-servicename: ValidationError: Stack [app-env-servicename] does not exist
        status code: 400, request id: xxxxxxxxx-xxxx-xxxx-xxxx : describe stack: describe stack events for stack app-env-servicename: ValidationError: Stack [app-env-servicename] does not exist
        status code: 400, request id: xxxxxxxxx-xxxx-xxxx-xxxx 
```

and the deployment fails with this error.
If I clear the override or deploy it as a YAML file, the deployment succeeds with no errors. Am I missing something?

The order of command execution is
1. `copilot init`
2. `copilot env init`
3. `copilot env deploy`
4. `copilot svc override -> cdk`
5. `copilot deploy`

ps.
When I use `copilot app delete` command, I get stuck on `Cleaning up deployment resources` message and the app is not deleted, so I have to manually delete S3 and StackSet, do `copilot init` again and then `copilot app delete` to delete the app. Am I the only one having problems with this?

**Comment by iamhopaul123** [comment]
Hello @gmae199boy.

> create change set copilot-xxxxxxxxx-xxxx-xxxx-xxxx for stack app-env-servicename: ValidationError: Parameter values specified for a template which does not require them.

From the error msg it seems like your CDK override template is trying to pass a parameter (the one specified in CDK override file) to a CloudFormation template that does not contain that certain parameter. I wonder if you want to specify a new parameter in CDK override file?

> When I use copilot app delete command, I get stuck on Cleaning up deployment resources message and the app is not deleted

This is really strange. It happens when Copilot is cleaning up objects within the stackset bucket so that CloudFormation can delete the bucket. I wonder if it's some internet connection issue? It should be transient.

**Comment by gmae199boy** [comment]
Hello @iamhopaul123 

I get the same error when I run `copilot deploy` with just a purely generated default template, where I created `copilot svc override -> cdk` and didn't change anything. I haven't modified anything, and even if I do, I get the same error.

> This is really strange. It happens when Copilot is cleaning up objects within the stackset bucket so that CloudFormation can delete the bucket. I wonder if it's some internet connection issue? It should be transient.

As for the `copilot app delete` command, I've used my work computer, my home computer, and two different AWS accounts, and it's all the same. It's so frustrating every time I try to delete an app.

**Comment by iamhopaul123** [comment]
> I get the same error when I run copilot deploy with just a purely generated default template, where I created copilot svc override -> cdk and didn't change anything. I haven't modified anything, and even if I do, I get the same error.

I tried to reproduce the issue by running `copilot svc override` and deploy along with an empty template (chose no resources in wizard). 

```ts
import * as cdk from 'aws-cdk-lib';
import * as path from 'path';

interface TransformedStackProps extends cdk.StackProps {
    readonly appName: string;
    readonly envName: string;
}

export class TransformedStack extends cdk.Stack {
    public readonly template: cdk.cloudformation_include.CfnInclude;
    public readonly appName: string;
    public readonly envName: string;

    constructor (scope: cdk.App, id: string, props: TransformedStackProps) {
        super(scope, id, props);
        this.template = new cdk.cloudformation_include.CfnInclude(this, 'Template', {
            templateFile: path.join('.build', 'in.yml'),
        });
        this.appName = props.appName;
        this.envName = props.envName;
    }
}
```
Deployment seems good to me. Could you share your default template with me?

> As for the copilot app delete command, I've used my work computer, my home computer, and two different AWS accounts, and it's all the same. It's so frustrating every time I try to delete an app.

I am terribly sorry for this. I've never seen this issue before tho. So could you assist me by answering the follow-up questions? 

1. Did you see "✔ Cleaned up deployment resources." or the spinner just kept spinning?
2. Does it happen every time even if you just init a very simple example application by "copilot init"?

**Comment by gmae199boy** [comment]
This is the empty default I used. just delete Error.

```typescript 
import * as cdk from 'aws-cdk-lib';
import * as path from 'path';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as iam from 'aws-cdk-lib/aws-iam';

interface TransformedStackProps extends cdk.StackProps {
  readonly appName: string;
  readonly envName: string;

  this.transformTaskRole();
}

export class TransformedStack extends cdk.Stack {
  public readonly template: cdk.cloudformation_include.CfnInclude;
  public readonly appName: string;
  public readonly envName: string;

  constructor(scope: cdk.App, id: string, props: TransformedStackProps) {
    super(scope, id, props);
    this.template = new cdk.cloudformation_include.CfnInclude(this, 'Template', {
      templateFile: path.join('.build', 'in.yml')
    });
    this.appName = props.appName;
    this.envName = props.envName;
  }

  // TODO: implement me.
  transformTaskRole() {
    const taskRole = this.template.getResource('TaskRole') as iam.CfnRole;
  }
}
```

> I am terribly sorry for this. I've never seen this issue before tho. So could you assist me by answering the follow-up questions?

I don't know because I've never used `copilot app delete` when I've only used the `copilot init` command. I've always run it up to `copilot deploy`, then `copilot app delete`, at which point the `Cleaned up deployment resources.` message keeps spinning. 

I can wait for hours while it keeps spinning like this, and it never ends. 

It wasn't until I accessed the aws console and manually cleared S3, emptied the Stackset, deleted the Stackset, and ran `copilot init` again that `copilot app delete` correctly deleted the app.

The IAM I'm using has admin privileges.

**Comment by iamhopaul123** [comment]
Hello @gmae199boy. It seems like this code snippet was problematic because `this.transformTaskRole();` is undefined in `TransformedStackProps`

```ts
interface TransformedStackProps extends cdk.StackProps {
  readonly appName: string;
  readonly envName: string;

  this.transformTaskRole();
}
```
Just for reference, I tried to do the same and this was the template I got:

```ts
import * as cdk from 'aws-cdk-lib';
import * as path from 'path';
import { aws_iam as iam } from 'aws-cdk-lib';

interface TransformedStackProps extends cdk.StackProps {
    readonly appName: string;
    readonly envName: string;
}

export class TransformedStack extends cdk.Stack {
    public readonly template: cdk.cloudformation_include.CfnInclude;
    public readonly appName: string;
    public readonly envName: string;

    constructor (scope: cdk.App, id: string, props: TransformedStackProps) {
        super(scope, id, props);
        this.template = new cdk.cloudformation_include.CfnInclude(this, 'Template', {
            templateFile: path.join('.build', 'in.yml'),
        });
        this.appName = props.appName;
        this.envName = props.envName;
        this.transformTaskRole();
    }
    
    // TODO: implement me.
    transformTaskRole() {
        const taskRole = this.template.getResource("TaskRole") as iam.CfnRole;
        throw new Error("not implemented");
    }
    
}
```

> at which point the Cleaned up deployment resources. message keeps spinning.

It indicates that Copilot hanged when trying to empty the bucket by calling S3 APIs. I'll keep investigating and at the same time feel free to upgrade your Copilot version to the latest if it is not.

**Comment by gmae199boy** [comment]
@iamhopaul123 Sorry about that. I wrote it wrong, I was running it with the same code as you wrote, just deleted the Error from it and ran it.

**Comment by dannyrandall** [comment]
Hey @gmae199boy - just to clarify, are you still having issues running `copilot svc deploy`, or is the issue resolved now?

**Comment by gmae199boy** [comment]
Hi @dannyrandall. I am still not able to resolve this error.
The `copilot app delete` is being manually deleted from the console as I said above, and the override is also not deployable, so I am implementing it in a different way.
