### ISSUE TITLE
Cannot create or delete services or jobs lack of authorization

### ISSUE THREAD

**Issue by phasetr** [aws/copilot-cli#4733]
I delete an app (and svc and job) to recreate app with domain by `copilot job delete`, `copilot svc delete`, and `copilot app delete`. Somehow this deletion may be incomplete, and I cannot recreate an app. E.g., I have a follwoing message.

>% copilot app delete
>Sure? Yes
>✘ execute job delete: delete job stack: get template body of stack "maitred-staging-dbmigrate": get template maitred-staging-dbmigrate: AccessDenied: User: arn:aws:iam::573143736992:user/maitre-d is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::573143736992:role/maitred-staging-EnvManagerRole
>        status code: 403, request id: 2635454c-66b2-4215-9cf6-67dbc0d74c61

The above `maitred` is my app name and `dbmigrate` is my job. Furthermore I run the follwoing command and I got the result.

>% copilot env delete -n staging
>Sure? Yes
>✘ find service cloudformation stacks: AccessDenied: User: arn:aws:iam::573143736992:user/maitre-d is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::573143736992:role/maitred-staging-EnvManagerRole
>        status code: 403, request id: b71ae1f2-66ad-4e3a-b402-209b3b961a39

>% copilot job delete -n dbmigrate
>Sure? Yes
>✘ delete job stack: get template body of stack "maitred-staging-dbmigrate": get template maitred-staging-dbmigrate: AccessDenied: User: arn:aws:iam::573143736992:user/maitre-d is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::573143736992:role/maitred-staging-EnvManagerRole
>        status code: 403, request id: 8ee51f36-264f-4ff4-bd9c-7722245f7844

In the CloudFormation AWS console, the stack `maitred-staging` remained. The drift status is as follows.

>CertificateValidationFunction	maitred-staging-CertificateValidationFunction-B2ca6yfUPl2S	AWS::Lambda::Function	DELETED	2023-04-05 15:32:28 UTC+0900	-
>CloudformationExecutionRole	maitred-staging-CFNExecutionRole	AWS::IAM::Role	MODIFIED	2023-04-05 14:49:12 UTC+0900	-
>CustomDomainFunction	maitred-staging-CustomDomainFunction-oMU5bwAW9qZU	AWS::Lambda::Function	DELETED	2023-04-05 14:49:12 UTC+0900	-
>CustomResourceRole	maitred-staging-CustomResourceRole-1WNK3CNTF0O41	AWS::IAM::Role	MODIFIED	2023-04-05 14:49:13 UTC+0900	-
>DNSDelegationFunction	maitred-staging-DNSDelegationFunction-IhfBLlVehazz	AWS::Lambda::Function	DELETED	2023-04-05 14:49:12 UTC+0900	-
>EnvironmentHostedZone	Z1028703206Q5IDPJFE44	AWS::Route53::HostedZone	DELETED	2023-04-05 14:49:14 UTC+0900	-
>EnvironmentManagerRole	maitred-staging-EnvManagerRole	AWS::IAM::Role	DELETED	2023-04-05 14:49:14 UTC+0900	-
>EnvironmentSecurityGroup	sg-0b779c72e269efa3b	AWS::EC2::SecurityGroup	IN_SYNC	2023-04-05 14:49:14 UTC+0900	-
>HTTPListener	arn:aws:elasticloadbalancing:us-west-2:573143736992:listener/app/maitr-Publi-Y5ELXWO73F6V/a4f25ca6b3de1314/f5ea0c61feae2ede	AWS::ElasticLoadBalancingV2::Listener	DELETED	2023-04-05 14:49:15 UTC+0900	-
>HTTPSListener	arn:aws:elasticloadbalancing:us-west-2:573143736992:listener/app/maitr-Publi-Y5ELXWO73F6V/a4f25ca6b3de1314/f941b4c1657c23e0	AWS::ElasticLoadBalancingV2::Listener	DELETED	2023-04-05 14:49:15 UTC+0900	-
>PublicHTTPLoadBalancerSecurityGroup	sg-0ade18a6521143894	AWS::EC2::SecurityGroup	IN_SYNC	2023-04-05 14:49:16 UTC+0900	-
>PublicHTTPSLoadBalancerSecurityGroup	sg-0243a5eeab5a98e1f	AWS::EC2::SecurityGroup	IN_SYNC	2023-04-05 14:49:16 UTC+0900	-
>PublicLoadBalancer	arn:aws:elasticloadbalancing:us-west-2:573143736992:loadbalancer/app/maitr-Publi-Y5ELXWO73F6V/a4f25ca6b3de1314	AWS::ElasticLoadBalancingV2::LoadBalancer	DELETED	2023-04-05 14:49:16 UTC+0900	-

What right/role do I create and assign? How do I refresh the app?

**Comment by iamhopaul123** [comment]
Hello @phasetr. I'm very appreciated that you included the drift detection result. It is really helpful. Looks like a lot of resources in the env stack were deleted. Do you know why they were deleted? I think the reason why you got the error when you ran Copilot commands were also because of that.

> What right/role do I create and assign? How do I refresh the app?

You could just run `copilot env deploy` to redeploy the `staging` environment.

**Comment by phasetr** [comment]
Thank you for your comment, @iamhopaul123!

> Do you know why they were deleted? I think the reason why you got the error when you ran Copilot commands were also because of that.

If my memory serves me right, it took over an hour to execute some deletion command, but it stopped midway due to an error. So I ran the deletion command twice. The second time also took quite some time, but I don't remember if it ended normally.

>You could just run `copilot env deploy` to redeploy the staging environment.

I tried running the commands, `copilot env deploy` and `copilot env delete`, and the results are as follows.

>% copilot env deploy
>Only found one environment, defaulting to: staging
>✘ upload artifacts for environment staging: ensure env manager role has permissions to upload: get environment template for "staging": get template maitred-staging: AccessDenied: User: arn:aws:iam::573143736992:user/maitre-d is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::573143736992:role/maitred-staging-EnvManagerRole
>        status code: 403, request id: 4a313579-f745-48f5-bca3-64eec4de978f

>% copilot env delete
>Only found one environment, defaulting to: staging
>Sure? Yes
>✘ find service cloudformation stacks: AccessDenied: User: arn:aws:iam::573143736992:user/maitre-d is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::573143736992:role/maitred-staging-EnvManagerRole
>        status code: 403, request id: d73c41d0-e81a-4627-b21b-9831785a8195

I need some authorization to an account. I can access the AWS by an administration account, and check `maitred-staging-EnvManagerRole`. However this role does not exist in IAM. What authorization do I create?

**Comment by phasetr** [comment]
Added: I try to delete resources in AWS console, but I can't delete it. In particular, when I try to delete a network interface, I get the message `API error: You do not have permission to access the specified resource`. I get this message even by the root account. (I do not understand IAM well, but is there an operation prohibited even for administrators?)

**Comment by iamhopaul123** [comment]
@phasetr it seems like your `EnvManagerRole` was deleted and that's why you can't use your root account to assume that role. Could you try to create a role manually as `maitred-staging-EnvManagerRole` (with admin permission) and then you would be able to delete the stack.

Sorry again for this annoying issue. You can't delete a stack if the role you used last time to update the stack was deleted.

**Comment by phasetr** [comment]
Thank you, @iamhopaul123 !
I created a role, `maitred-statig-EnvManagerRole`, ran the command, and get the following message:

>% copilot env deploy
>Only found one environment, defaulting to: staging
>✘ upload artifacts for environment staging: upload custom resources to bucket stackset-maitred-infrast-pipelinebuiltartifactbuc-s6s19usaaw8: upload custom resource "CustomDomainFunction": upload manual/scripts/custom-resources/customdomainfunction/59613d232aee00a9c055f3ef5dc9f2729015cef989cb599e355e1a3cb3d69b10.zip to bucket stackset-maitred-infrast-pipelinebuiltartifactbuc-s6s19usaaw8: AccessDenied: Access Denied
>        status code: 403, request id: HR4263FHS26NCWYA, host id: xwyoxnNd4lL59VPDhXzc5WODs6vEaXNEYQe/Jn0slxmLN5+HpqKLahB6luJQg1u7I5Eb0C0yS2c=

>% copilot env delete
>Only found one environment, defaulting to: staging
>Sure? Yes
>✘ find service cloudformation stacks: AccessDeniedException: User: arn:aws:sts::573143736992:assumed-role/maitred-staging-EnvManagerRole/1680827907356843000 is not authorized to perform: tag:GetResources because no identity-based policy allows the tag:GetResources action
>        status code: 400, request id: 11b1364c-ff45-453d-a6cf-4349d82882e7

Now I'm trying to allow this operation in IAM!

**Comment by phasetr** [comment]
The above error may disappear, but I met a next error.
I added the role `maitred-staging-CFNExecutionRole` and attached the policy `AWSCloudFormationFullAccess`, but I had the following error.

>% copilot env delete --name staging --yes
>✔ Retained IAM roles for the "staging" environment
>- Delete environment stack maitred-staging  [not started]
>✘ delete environment staging stack: delete stack maitred-staging: ValidationError: Role arn:aws:iam::573143736992:role/maitred-staging-CFNExecutionRole is invalid or cannot be assumed
>        status code: 400, request id: e660ebde-a0d1-4840-8523-206134d37036

Next I'll try to resolve this.

**Comment by phasetr** [comment]
I added the role `maitred-staging-CFNExecutionRole`, and add the poilcy `AWSCloudFormationFullAccess` to it. However I got the error 
>delete environment staging stack: delete stack maitred-staging: ValidationError: Role arn:aws:iam::573143736992:role/maitred-staging-CFNExecutionRole is invalid or cannot be assumed

The operator account `maitre-d` has a policy `maitred-CFN`, and this poiicy has a role `maitred-CFN` and `AWSCloudFormationFullAccess`.

**Comment by iamhopaul123** [comment]
> delete environment staging stack: delete stack maitred-staging: ValidationError: Role arn:aws:iam::573143736992:role/maitred-staging-CFNExecutionRole is invalid or cannot be assumed

It seems like the `aitred-staging-CFNExecutionRole` (which is part of the env stack) also got deleted. Sorry I didn't realize that. Could you try to recreate that role and do the `env delete` again?

**Comment by iamhopaul123** [comment]
Sorry @phasetr. What about the trust relationship? CFN execution role needs to trust

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": [
                    "lambda.amazonaws.com",
                    "cloudformation.amazonaws.com"
                ]
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

**Comment by phasetr** [comment]
Thank you, @iamhopaul123, the setting allows me to run `copilot env delete`, and this yields next errors! I will report that below.

By the way, can I reset IAM settings? If it is OK, I'd like to know the CFn setting file and how to publish it. (I am an AWS newbie, I don't know what commands are proper in AWS CLI.)

---

The command `copilot env deploy` yields, e.g.,

>% copilot env deploy
>Only found one environment, defaulting to: staging
>✘ upload artifacts for environment staging: upload custom resources to bucket stackset-maitred-infrast-pipelinebuiltartifactbuc-s6s19usaaw8: upload custom resource "CertificateValidationFunction": upload manual/scripts/custom-resources/certificatevalidationfunction/4e5b1583b1c797952569047008b6e100768ea2a0a057f0729b9dc0095b376c58.zip to bucket stackset-maitred-infrast-pipelinebuiltartifactbuc-s6s19usaaw8: AccessDenied: Access Denied
>        status code: 403, request id: 19M4XJ8AGXAPGAR4, host id: yToyTudEM11a6pjr8vV8+A04/sjJ52vHolgbU2AGLUklS8eh8hTqfP4KG95NJTm788xbzkc9w5s=

The command `copilot env delete` yields

>- Request and validate an ACM certificate for your domain                          [delete failed]      [0.0s]
>  User: arn:aws:sts::573143736992:assumed-role/maitred-staging-CFNExecut
>  ionRole/AWSCloudFormation is not authorized to perform: lambda:InvokeF
>  unction on resource: arn:aws:lambda:us-west-2:573143736992:function:ma
>  itred-staging-CertificateValidationFunction-B2ca6yfUPl2S because no id
>  entity-based policy allows the lambda:InvokeFunction action (Service:
>  AWSLambda; Status Code: 403; Error Code: AccessDeniedException; Reques
>  t ID: 6c761dab-5e71-4d2a-931f-1f7138b6e5c5; Proxy: null)
>- An Application Load Balancer to distribute public traffic to your services       [delete failed]      [0.0s]
>  API: elasticloadbalancingv2:DeleteLoadBalancer User: arn:aws:sts::5731
>  43736992:assumed-role/maitred-staging-CFNExecutionRole/AWSCloudFormati
>  on is not authorized to perform: elasticloadbalancing:DeleteLoadBalanc
>  er on resource: arn:aws:elasticloadbalancing:us-west-2:573143736992:lo
>  adbalancer/app/maitr-Publi-Y5ELXWO73F6V/a4f25ca6b3de1314 because no id
>  entity-based policy allows the elasticloadbalancing:DeleteLoadBalancer
>   action
>- An Internet Gateway to connect to the public internet                            [delete failed]      [2.6s]
>  Resource handler returned message: "You are not authorized to perform
>  this operation. (Service: Ec2, Status Code: 403, Request ID: 48c643b8-
>  528d-444a-8cbb-7f4823bf3720)" (RequestToken: 644e06db-27fa-b736-7e23-a
>  005915ed678, HandlerErrorCode: GeneralServiceException)
>- Public subnet 1 for resources that can access the internet                       [delete in progress]  [2.8s]
>- Public subnet 2 for resources that can access the internet                       [delete in progress]  [2.8s]
>- A custom route table that directs network traffic for the public subnets         [delete failed]      [0.0s]
>  Resource handler returned message: "You are not authorized to perform
>  this operation. (Service: Ec2, Status Code: 403, Request ID: a074fa25-
>  bda5-4f1a-8fb9-7ceac34641be)" (RequestToken: 9dbb34a7-2ed3-af4c-850f-0
>  acff7f7eea6, HandlerErrorCode: GeneralServiceException)
>- A security group for your load balancer allowing HTTPS traffic                   [delete failed]      [0.0s]
>  API: ec2:DeleteSecurityGroup You are not authorized to perform this op
>  eration. Encoded authorization failure message: CAbiaUyElNuMkWy5etOxIC
>  -O-2c8C-0nw9VemlfLB8rWA6Sp2h8Y9IYtd-dAe9TH4v9nZOup2LQSZEp12Aj3Wx01a2ex
>  u3skLPb3DfWcyPJrFA8TLg4gNKdsodJOnNODtlYTfJnEI2K-AIzsBiZzqlIKPqHRlAzDwg
>  XHxUY78hCvu93OlfE1BkULu7axCb_Krf4jFIczm2mKQjD9P8UBfU6cgvEeM_DUFsQafKhK
>  96Fo0iAMzzNJ_MnRpckkv6HqNVy6HcTmf-oQcVaM8sc93tJZgyixpVhDgJG1xIwQmDdRIn
>  SCy-gpfjmEz4c1-gtEcJo6GzTb0gqYHXhxmm0mhxpS5v8quDrHtnkG34BpXTRQwD3oL7Ja
>  yDCfqEMi-d5d90tidNeyFGG4_s__9RGPTPKCWw_MRFyV7Msoj6E56X2jh5ApdLFjm-XylV
>  G7Uds4OS7Ea647nWOwVv0IxXEd_MnG6FmwoEtCpuDoBuXZqXAjGakyZhUxmVqaCVtRIQhN
>  cyreVJzreVmHcgsdZB_0YsVY9gvGwbkoP_Ics33cSco75yIx7K12we3mM_Iuno4zFozpyI
>  12zeyVYOEdMgbNCNKp1BF-fB9OFXIpUdTldpPGbyIMKzVcNSitRsrymr8_Bn-AH8bJJ97n
>  2CHQimC8LCNMvR-UHPpu9hNCclSiOeB__reIwqWHxHCumkFZC1kLoSOu3N1e_2xchaBlob
>  z8nMAOGl43tO4fEvU1fU_lGYqPjdwOTb98OmQvpgTQ9QySMY_KwbUGN2urPSbeBa5Hb6es
>  dQUBjWaPeaXtPAFgZEmqY8Z8cGr262JOorhemNoM9hYHOGCLlrBMxvl5nVcykrFuGG2ndu
>  PyiCon6JuvFqrAM5m4VW6FC1I
>- A security group for your load balancer allowing HTTP traffic                    [delete failed]      [0.0s]
>  API: ec2:DeleteSecurityGroup You are not authorized to perform this op
>  eration. Encoded authorization failure message: 4m13q5WrazsIKmkODHDF2M
>  lkqjLBsIQpF2d29XNwHPoFD15Dw7y8W3Aq901soJ1Uma6W3ppHoe1vHFQ5IuT7HWYc8oAc
>  TTpQM8Nb3InR78D-m8bPWJAkP7bjVUYwTHWh6xOu2C2yMZ_keYCfRnQmEzdHYX728NK4sE
>  jwwYW4RrOkG3-kOvkS0vWC5s27AqcHSHsjlTDmo1gqWVoVwWceAWzFV6pZw5TB8N1Gx25j
>  PY6mEYeGKfOlaQa025OZceLeqfMZ-hkc8GlU9frjszom3RtI531CCIgR-1fMt7GxBeAPsA
>  TBxEfbFTnmd6JvcEx5qeBLU9RJf-mxyPtYg5d5X2gcF8zjtwwtj-_f8Plsi2CggA1a1yga
>  nuB_pn3R7NCLu6vtkN6tJXI2OgMwNA00cwEazHZf24U8CbWqwFc0PwyjA4KiilAnw5h4OM
>  0L1RW4UIlQ1HjUO2LYIi7v0J_0YUO02JpkwRfHeJ6DNIWjRVv_5AvXrN5tNFmmPksUJ_Du
>  DfSCZw0CcLhmY92byY59_uCoCryOVirQYaRdRtobfFN66cS-VX3NYXX3StyQQM0U0BknvL
>  1XAjC9OA-8J4VNhTePiohWk5GvgWLvvafO-qzByxBzsLd71bxgFDTTAdpXyLbhLB374xki
>  sgKmc_-pAAlLqhKMmIocpX15aWu0w7XsDqSUvhyl3TXhQNybUvyaxx9v-4rst-Nmbn1hI_
>  W3j1SbCz2NqTY6XDxPPX-HjEBJK3QCVbsB_r7nyjuyBrvq4sg4vaCIlvIcs-Br6YQyuGrN
>  aPq-NWrHyAh4GTmCT3Z_M9nfYysQlgAJ4yc3mUYH5ggDkiFAG_ZZCg6BPi5PNnPQFzT5c1
>  5kugtdZSz67RWsP1HdYlltNQ
>- Delegate DNS for environment subdomain                                           [delete failed]      [0.0s]
>  User: arn:aws:sts::573143736992:assumed-role/maitred-staging-CFNExecut
>  ionRole/AWSCloudFormation is not authorized to perform: lambda:InvokeF
>  unction on resource: arn:aws:lambda:us-west-2:573143736992:function:ma
>  itred-staging-DNSDelegationFunction-IhfBLlVehazz because no identity-b
>  ased policy allows the lambda:InvokeFunction action (Service: AWSLambd
>  a; Status Code: 403; Error Code: AccessDeniedException; Request ID: 7e
>  aac53a-5edb-4239-a31d-e2253156b17a; Proxy: null)

**Comment by phasetr** [comment]
Hi, @iamhopaul123!

I need some more IAM settings, which you taught me, and finally I can solve the problem thanks to additional AWS paid support.

I close this issue. Thanks again @iamhopaul123 !
