### ISSUE TITLE
ECR Container Images no longer being tagged

### ISSUE THREAD

**Issue by zackdotcomputer** [aws/copilot-cli#4753]
On our applications something changed around 4/7. Prior to this date, containers uploaded to ECR by copilot would be tagged with both a short hash (e.g. `77e5bc0`) and the tag `latest`. After this date, they were no longer tagged `latest`. Our build and uploads are managed by Github Actions so the source and platform are consistent, and there haven't been any updates to that workflow or our Dockerfile in months. The change happened at the same time across all our copilot projects. so I've ruled out a manifest change on our end. It was also not at the same time as a new CLI release, so I'm wondering if something changed with ECR and how it expected to receive images from the CLI?

**Comment by dannyrandall** [comment]
Hey @zackdotcomputer! That's really interesting - I just double checked on one of my services and it seems like `copilot svc deploy` (v1.27.0) is still pushing the `latest` tag for me 🤔. What version of Copilot are you using? Are you using `copilot svc deploy` or `copilot svc package` in your pipeline? Could you share a Copilot `manifest.yml` from one of your services?

**Comment by zackdotcomputer** [comment]
An update here - we started a new project in a new account with a new manifest and from day one it is tagging `latest` but not the short hash/sha. @dannyrandall are you seeing short hash/sha tags still being applied to yours, or are you only seeing the `latest` tag?

![Screenshot 2023-06-14 at 16 14 09](https://github.com/aws/copilot-cli/assets/643058/52d537b6-1c46-4e7b-bbe2-5979ed0186a9)

**Comment by zackdotcomputer** [comment]
(I also cannot remove the `stale` tag on this issue, but would like this to still get looked at)

**Comment by iamhopaul123** [comment]
Hello @zackdotcomputer 

> @dannyrandall are you seeing short hash/sha tags still being applied to yours, or are you only seeing the latest tag?

Can you try to use our latest Copilot version (v1.28.0)? 
<img width="1083" alt="Screenshot 2023-06-15 at 9 51 30 AM" src="https://github.com/aws/copilot-cli/assets/51377557/a13b636b-c56b-4d87-911f-b7096b6e2938">

We recently changed our way of tagging images because of the fact that we can now build and push the image for sidecar container too. Does it look good to you?
