### ISSUE TITLE
Pipeline deployment clear user files

### ISSUE THREAD

**Issue by yanmyocore** [aws/copilot-cli#4757]
I have deployed an application to aws ecs with copilot pipeline(github). There is a problem when everytime I deploy, user upload photos are deleted or lost. I don't know how to solve it. Are there any configuration to prevent user upload photos lost? All photos are under project folder. The following is my buildspec.yml
```
# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
      ruby: 3.1
      nodejs: 16
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.27.0
      - mv ./copilot-linux-v1.27.0 ./copilot-linux
      - chmod +x ./copilot-linux
  build:
    commands:
      - echo "Run your tests"
      # - make test
  post_build:
    commands:
      - ls -l
      - export COLOR="false"
      - pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipelines/univcoop-logistics-pipeline-dev/manifest.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')
      - pl_envs=$(echo $pipeline | jq -r '.stages[].name')
      # Find all the local services in the workspace.
      - svc_ls_result=$(./copilot-linux svc ls --local --json)
      - svc_list=$(echo $svc_ls_result | jq '.services')
      - >
        if [ ! "$svc_list" = null ]; then
          svcs=$(echo $svc_ls_result | jq -r '.services[].name');
        fi
      # Find all the local jobs in the workspace.
      - job_ls_result=$(./copilot-linux job ls --local --json)
      - job_list=$(echo $job_ls_result | jq '.jobs')
      - >
        if [ ! "$job_list" = null ]; then
          jobs=$(echo $job_ls_result | jq -r '.jobs[].name');
        fi
      # Raise error if no services or jobs are found.
      - >
        if [ "$svc_list" = null ] && [ "$job_list" = null ]; then
          echo "No services or jobs found for the pipeline to deploy. Please create at least one service or job and push the manifest to the remote." 1>&2;
          exit 1;
        fi
      # Generate the cloudformation templates.
      # The tag is the build ID but we replaced the colon ':' with a dash '-'.
      # We truncate the tag (from the front) to 128 characters, the limit for Docker tags
      # (https://docs.docker.com/engine/reference/commandline/tag/)
      # Check if the `svc package` commanded exited with a non-zero status. If so, echo error msg and exit.
      - >
        for env in $pl_envs; do
          tag=$(echo ${CODEBUILD_BUILD_ID##*:}-$env | sed 's/:/-/g' | rev | cut -c 1-128 | rev)
          for svc in $svcs; do
          ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
          if [ $? -ne 0 ]; then
            echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
            exit 1;
          fi
          done;
          for job in $jobs; do
          ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
          if [ $? -ne 0 ]; then
            echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
            exit 1;
          fi
          done;
        done;
      - ls -lah ./infrastructure
artifacts:
  files:
    - "infrastructure/*"
    - "!html/upload/save_image"

```

**Comment by dannyrandall** [comment]
Hey @yanmyocore! Just to clarify what you're trying to do - are people uploading files to your Copilot service, and your service is writing them to its local filesystem? And then when your pipeline runs and a new version of your service is deployed, those files are disappearing?

Or, are those images stored in your git repo, and you expect the files to be available for your service to read after it's been deployed?

Thanks! Just want to make sure I'm understanding what you're trying to do.😊

**Comment by yanmyocore** [comment]
@dannyrandall Yes, people upload photo from web and save them under project folder `html/upload/save_image` . When the pipeline deploy new version, people uploaded photos are disappeared. 
Thanks.

**Comment by dannyrandall** [comment]
Gotcha! By default in Copilot services are given [20 Gib of ephemeral storage](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#ephemeral). "Ephemeral" in this context means that whenever your service is restarted (1), anything written to the disk will disappear. The only files present in the new task are ones in your docker image, which is created by your `Dockerfile`.

If you want to write images to a local disk, Copilot can create and attach an [EFS volume](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#efs) for you. In your case, the configuration would look something like:
```
storage:
  volumes:
    images:
      path: /html/upload/save_image
      efs: true
      read_only: false
```

Alternatively, storing uploaded images in S3 is a fairly common pattern. Happy to give more details on that if you'd like!

(1): Services are restarted in a few scenarios:
  - `copilot svc deploy` with changes
  - `copilot svc deploy --force`
  - You make a git commit and your Copilot pipeline runs
  - Your service exits/ends - ECS will start a new one

---

In case I'm misunderstanding you and you mean that people are _saving images to a folder **in your git repo**_ at `html/upload/save_image`, then one thing you could do is include those images in your docker image. Add a line like this to your Dockerfile:
```dockerfile
COPY html/upload/save_image /html/upload/save_image
```
This line will copy the local folder `html/upload/save_image` into the docker image, which your service can read from at `/html/upload/save_image`.

**Comment by yanmyocore** [comment]
@dannyrandall Thanks.

**Comment by dannyrandall** [comment]
You're welcome! I'll close this issue for now, but feel free to reopen if you're still having any issues!😊
