### ISSUE TITLE
Github coplit fails to start in Visual Studio 2022 preview 4

### ISSUE THREAD

**Issue by AlanNevill** [aws/copilot-cli#4817]
[severity: It’s more difficult to complete my work]
GitHub Copilot 1.73.3.0 (v1.73.3.0@ccaf0843c)
GitHub Copilot Agent v1.73.0
[Error] An error occurred for ‘OnServerInitializeFailedAsync’: StreamJsonRpc.ConnectionLostException: The JSON-RPC connection with the remote party was lost before the request could complete. —> System.OperationCanceledException: The operation was canceled.

**Comment by bvtujo** [comment]
See also #4818
