### ISSUE TITLE
increase test coverage for `ini.go`

### ISSUE THREAD

**Issue by khareyash05** [aws/copilot-cli#4829]
Currently the test coverage for `internal/pkg/ini/ini.go` is 46.67% [https://app.codecov.io/gh/aws/copilot-cli/blob/mainline/internal/pkg/ini/ini.go](https://app.codecov.io/gh/aws/copilot-cli/blob/mainline/internal/pkg/ini/ini.go). I would like to increase the test coverage

**Comment by efekarakus** [comment]
Hi @khareyash05 ! sure thing, feel free to open a PR for any package where you'd like to improve the test coverage 🙌

**Comment by efekarakus** [comment]
I'll resolve the issue, contributions are always welcome :)
