### ISSUE TITLE
copilot pipeline build process fails using GitHub repo with copilot directory not under root-dir of the repo.

### ISSUE THREAD

**Issue by ustrahlendorf** [aws/copilot-cli#4851]
Using GitHub repo as source for the copilot pipeline.
The repo structure is 
GitHub repo name --> github-user/my-repo.git
Directory structure:
- src
- work-folder 
          |- copilot
Build process fails because buildspec.yml could not be find.
Reason:
CODEBUILD_SRC_DIR is set by the system and did not include "work-folder"
The automated setup for the build project set the Buildspec name to: copilot/pipelines/<module-name>/buildspec.yml. In my case it needs to be set to work-folder/copilot/pipelines/<module-name>/buildspec.yml
I have not found any place in the copilot configuration files to add the folder to the path for the buildspec file.

To get a successful build there are 2 other changes in the buildspec file necessary because the path  $CODEBUILD_SRC_DIR/copilot/ ..... is hard coded in the generated file.

I have no real experience with CodeBuild in combination with GitHub, therefore there might be a solution how to fix the issue without changing the generated buildspec-file by hand. If this is the case, I am happy to learn.

Regards
Uwe

**Comment by KollaAdithya** [comment]
Hey @ustrahlendorf !
This is how the overall structure of Copilot including your source code should look like.
```yaml
demo                                (git repository)
├── copilot                        (application directory)
│   ├── .workspace                 (workspace summary)
│   ├── frontend
│   │   └── manifest.yml           (service manifest for frontend)
|   |   environments
|   |   └── test
│   │       └── manifest.yml       (environment manifest for the environment test)
│   ├── pipelines
│   │   ├── pipeline-app-beta
│   │   │   ├── buildspec.yml      (buildspec for the pipeline 'pipeline-app-beta')
│   ┴   ┴   └── manifest.yml       (pipeline manifest for the pipeline 'pipeline-app-beta')
└── src                   (your source code)
```
I think you need to run `copilot app init` with in the demo(git repository) directory which will create `copilot` directory containing all the manifest and buildspec files with the above structure. In this case ,you do not need sub directory `work-folder` containing all the configuration files of `copilot`.

Here is a detailed [guide](https://aws.github.io/copilot-cli/docs/concepts/pipelines/) on deploying a pipeline using copilot with Github repository as source.
Let me know if this helps! Feel free to ask any more questions.

**Comment by ustrahlendorf** [comment]
Hi Kolla,
thanks for the hint.
I worked through this workshop: "AWS Copilot Workshop"; https://catalog.us-east-1.prod.workshops.aws/workshops/bbe33a01-4c98-4cfc-b859-d55d699419b8/en-US
May be I have misunderstood parts of the Lab steps for module 5 (Building CI/CD)

What if I have to use (for what ever reason) a repo structure where the copilot directory is in a subfolder like work-folder?
Does this mean I could not use copilot in this scenario or are there knobs to adjust it?

**Comment by ustrahlendorf** [comment]
Hi Kolla,
want to give you an update. Thanks for the hint, everything works well after restructuring the folders in my repo.
It might be a good idea to put this advice into your documentation. If someone wants to use copilot with the pipeline the directory structure has to be like the one you mentioned.

In addition I checked the steps in the Workshop I mentioned above. The steps described in Module 5 are definitely the reason why I started to put the copilot directory in a sub-directory (work-folder).  This had cost me several hours of digging around what went wrong and how to fix it through configuration changes in manifest- and buildspec-files. 
I don't who can do some changes for the Workshop, it might be helpful for others.

regards
Uwe

**Comment by KollaAdithya** [comment]
Thanks for the update! Glad that you are able to deploy your pipeline :wohoo:

But the instructions workshop seems to be correct 🤔 
In the module 1 of the workshop instructions are https://catalog.us-east-1.prod.workshops.aws/workshops/bbe33a01-4c98-4cfc-b859-d55d699419b8/en-US/30-mod1-deploy-webapp

> You need to work in the folder titled work-folder. If work-folder doesn't exist, please manually create it. It will be an empty folder since it's the first module. The work-folder is your primary folder.

So I would assume `work-folder` is going to be the root of the git repository
In module 5 instructions are

> You need to work in the folder titled work-folder.
> There is no additional source codes you need to copy into your work-folder.

**Comment by ustrahlendorf** [comment]
Hi Kolla,
thanks for your comment. Seems I missunderstood the steps. I started the Workshop local without a git repo.

Anyway, I now know how ist should look like.

Regards
Uwe

**Comment by KollaAdithya** [comment]
Closing this issue for now. Feel free to reopen incase of any further issues.
