### ISSUE TITLE
Cannot manually delete CloudFormation stacks due to "CloudFormation did not receive a response from your Custom Resource." in EnvControllerAction, HTTPRuleWithDomainPriorityAction, HTTPSRulePriorityAction

### ISSUE THREAD

**Issue by blu3r4y** [aws/copilot-cli#4868]
I am trying to delete the services and environment of my "Load Balanced Web Service" app manually, by deleting the CloudFormation stack. I can not use the CLI because the CLI tries to assume a role and my federated user is not allowed to assume roles. I figured, manually deleting the stacks in CloudFormation should also work.

However, if I do this I struggle to delete the following three resources:

* EnvControllerAction
* HTTPRuleWithDomainPriorityAction
* HTTPSRulePriorityAction

I see the following error when I try to delete the stack for one my services:

_CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [xxx]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version._

I am very much confused by this error and the internet wasn't of great help yet. Any ideas how I could resolve that?

The resources have been generated in February 2023 with Copilot version v1.23.0

**Comment by KollaAdithya** [comment]
Hey @blu3r4y !

Can you go to your `CloudFormation stack->Events` and check the resource which was failed to delete first and also can you provide the status reason for that resource.

**Comment by blu3r4y** [comment]
I eventually managed to delete the stacks by manually deleting all the individual resources that failed to delete. Specifically, I deleted all Lambdas, VPCs, EFS, and even Route 53 entries.

The status reason was the same for all three resources, and as written in my initial message:

_CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [xxx]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version._

**Comment by KollaAdithya** [comment]
Glad that you are able to delete all the resources 😍 . But can you check for the logs of Lambdas if available to get more specific reason for the failure.

**Comment by blu3r4y** [comment]
I checked all the logs in CloudTrail for all Lambda functions, but sadly the last log entries are more than 3 months old, back when I generated the application. So I guess these errors did not log anything ...

**Comment by KollaAdithya** [comment]
Hey @blu3r4y closing the issue for now. Feel free to reopen incase of any more issues.
