### ISSUE TITLE
"No new infrastructure changes" treated as error

### ISSUE THREAD

**Issue by rmarops** [aws/copilot-cli#4869]
I would rather this exit 0 successful or exit ## (some custom higher number) so it could be trapped and handled by the calling app which could then exit successfully.
```
- No new infrastructure changes for stack prod-client
Note: Set --force to force an update for the service.
✘ deploy service client to environment prod: deploy service: change set with name copilot-5c403e30-1a8e-4fa7-a661-ca44832118c5 for stack prod-client has no changes

Exited with code exit status 1
```
My reasoning is under normal conditions the state is achieved (latest iteration of the app is deployed).   This error confuses app devs and junior ops will lean towards using --force.  And I argue that should only be used sparingly (ie to correct a broken stack).  A forced stack is also incredibly slow to complete.

**Comment by KollaAdithya** [comment]
Hey @rmarops !
Thank you for bringing up this issue with the exit code.
can you  answer these few questions. 
Prior to running the command `copilot svc deploy` what changes did you make.
1. Did you change your application/src code.
2. Are you using `--tag ` when you run `copilot svc deploy`. 
3. Is the `tag` changed from previous deployment.

**Comment by rmarops** [comment]
The project is split in to server, client and proxy ECS services and sometimes 1+ of those may not have code changes but as part of the code push, all are requested to be built by the pipeline.
We don't use tag argument.

**Comment by rmarops** [comment]
We use CircleCI for deployments so today upon revisiting this issue I'm going to look at incorporating this --tag call, the tag will be the first 7 characters of the current git revision for which always changes.

As I understand it, this would should cause the image to be pushed anyway.  I like this approach much better than a --force.

**Comment by rmarops** [comment]
dropping notes from my internal circleci implementation and closing

add new run section just before the run section that defines the SvcDeploy()
```
      - run:
          name: Generate short SHA to use as image tag which will cause the image to always deploy
          command: |
            echo "SHORT_SHA=`echo << pipeline.git.revision >> | cut -c1-7`" >> "$BASH_ENV"
            source "$BASH_ENV"
            echo "SHORT_SHA=$SHORT_SHA"
```

update the SvcDeploy() definition as follows (introduces the --tag parameter)
```
            SvcDeploy() {
                echo "Executing copilot svc deploy -a $COPILOT_APP -e $COPILOT_ENV -n $COPILOT_SVC_NAME --tag $SHORT_SHA"
                $COPILOT svc deploy --app $COPILOT_APP --env $COPILOT_ENV --name $COPILOT_SVC_NAME --tag $SHORT_SHA
            }
```
