### ISSUE TITLE
deploy --force does not work

### ISSUE THREAD

**Issue by VaZark** [aws/copilot-cli#4878]
During a deployment, I missed an env secret that triggered the Circuit breaker after multiple retries. The rollback failed too as there were other env secrets that were removed. So the cloudFormation stack was at `UPDATE_ROLLBACK_FAILED`

After updating the manifest with the updated secrets. I wished to force deploy however the deployment returns an error with CloudFormation

```
✘ Proposing infrastructure changes for stack lenbox-tenant-backend-test-lbx-backend
✘ execute svc deploy: deploy service lbx-backend to environment test: deploy service: check if changeset is empty: create change set copilot-DUMMY for stack lenbox-tenant-backend-test-lbx-backend: 
ValidationError: arn:stack/lenbox-tenant-backend-test-lbx-backend/DUMMY is in UPDATE_ROLLBACK_FAILED state and can not be updated.
        status code: 400, request id: DUMMY: describe change set copilot-DUMMY for stack lenbox-tenant-backend-test-lbx-backend: ChangeSetNotFound: ChangeSet [copilot-DUMMY] does not exist
        status code: 404, request id: DUMMY: Resource handler returned message: "Error occurred during operation 'ECS Deployment Circuit Breaker was triggered'." (RequestToken: DUMMY, HandlerErrorCode: GeneralServiceException)
```

**Comment by huanjani** [comment]
Hello, @VaZark! 

Let's first try getting your CloudFormation stack out of the `UPDATE_ROLLBACK_FAILED` state, then try redeploying.
Please run `aws cloudformation continue-update-rollback --stack-name lenbox-tenant-backend-test-lbx-backend`; let us know how that goes.
Thanks!

**Comment by VaZark** [comment]
Hello, 

I was able to fix it by restoring the old secrets and running "continue rollback"

I created this issue as i expected `--force` to override the cloudformation and force deploy

**Comment by huanjani** [comment]
Ah, gotcha. Thanks for the clarification.

Yeah, unfortunately, the `--force` flag can't get the stack out of that state. (Ref: https://repost.aws/knowledge-center/cloudformation-update-rollback-failed.) The `--force` flag is for redeploying without having made changes.
