### ISSUE TITLE
service with more than one container

### ISSUE THREAD

**Issue by krish-adi** [aws/copilot-cli#4880]
In the docs: https://aws.github.io/copilot-cli/docs/concepts/environments/ a reference is made for running more than one container for a service. How is this achieved? I didn't not find any info on how to set this. 

However I found this: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/ does the count here refer to the number of containers? And if so, is the cpu/memory replicated for each container or does it run 2 containers inside the cpu/memory configured?

**Comment by huanjani** [comment]
Hello, @krish-adi!

This doc may help clarify some of the ECS concepts: https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/application.html#task-definition.

Yes, you may set the `count` field in your workload manifest (which is translated into your "task definition" via a CloudFormation template) to indicate the number of tasks to launch. The number of tasks generally maps to the number of containers, unless you have sidecar containers alongside your main containers. 

The cpu/memory values are [part of the task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size) and are at the task level, so the values are per task.

Hope this helps; let us know if you have other questions!

**Comment by krish-adi** [comment]
Makes sense now! Thanks a ton.
