### ISSUE TITLE
How do I associate a Route 53 private hosted zone created in AWS Copilot with a VPC on a different AWS account?

### ISSUE THREAD

**Issue by icruwrks** [aws/copilot-cli#4899]
Hello.

I would like to access a Route53 private hosted zone created with the AWS Copilot Backend Service from another VPC.

I think I can do this by using this URL method (create-vpc-association-authorization and associate-vpc-with-hosted-zone commands) after the service is built, but is there any problem using this in AWS Copilot? 
https://repost.aws/knowledge-center/route53-private-hosted-zone

Also, if I want to access a service from an external VPC, should I create it with Load Balanced Web Service instead of Backend Service? I want to make sure that the service I build can only be accessed from within the same VPC and from certain external VPCs.

**Comment by Lou1415926** [comment]
Hello @icruwrks !

> I would like to access a Route53 private hosted zone created with the AWS Copilot Backend Service from another VPC.

I think right now the only way is indeed like you said, to do it through either SDK or AWS CLI, unfortunately. If [this CloudFormation feature](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/371) is supported some day,  you will be able to do it as an environment addon in Copilot. If you are interested, you can go ahead and given them a 👍🏼 !

> but is there any problem using this in AWS Copilot?

I _don't think_ there will be any 🤔. After all, you are creating the association hook outside of Copilot, and Copilot doesn't  prevent you from doing that. 

I guess there is one thing that you should keep in mind. Copilot will delete that private route 53 hosted zone from the environment stack if you have deleted all of the backend services that has the `http` field from that same environment. 

If you are still worried, you can manage the private route53 hosted zone yourself. In Copilot, you'd need to import the certificates under `http.private` in the environment manifest, and write `http.alias` and `http.alias.hosted_zone` in the backend service's manifest. But again, I don't think there will be an issue with your current plan!

> Also, if I want to access a service from an external VPC, should I create it with Load Balanced Web Service instead of Backend Service? I want to make sure that the service I build can only be accessed from within the same VPC and from certain external VPCs.

Definitely backend service. LBWS is meant to be public. I think your approach - backend service with internal load balancer - sounds pretty good to me.

**Comment by icruwrks** [comment]
The method in the above URL has been executed on the AWS CLI and the connection has been established without any problems.

I have no problem closing this guidance. 

Thank you.
