### ISSUE TITLE
Support non-string shell env vars in manifest interpolation

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#4928]
Related: https://github.com/aws/copilot-cli/discussions/4907

Currently, only string-type shell env vars can be rendered into manifest correctly. This is because Copilot substitutes `${ENV_VAR_NAME}`s with their actual values always as `string`s https://github.com/aws/copilot-cli/blob/83f09c7decb89560667f171e278aa57d72a05853/internal/pkg/manifest/interpolate.go#L75
without switching the node `Kind` to the actual kind (e.g. `!!seq`). Because `${ENV_VAR_NAME}` is always recognized as a `string` by the default YAML unmarshaler, the unmarshal fails for fields that are not expecting a string.

**Comment by jhtann** [comment]
for the interpolation, is the feat only apply on manifest file? i tried on patch/addons file and it's doesn't recognised

**Comment by Lou1415926** [comment]
@jhtann yes it is only applied on manifest today!

**Comment by huanjani** [comment]
This enhancement has been released in v1.29.0: https://github.com/aws/copilot-cli/releases/tag/v1.29.0!
