### ISSUE TITLE
Copilot yaml patch override checks for CDK 

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/copilot-cli#4945]
I am trying to override generated CFN template of Copilot using YAML patch (instead of using CDK Override).
I have file `/copilot/<svc-name>/overrides/cfn.patches.yml` with below contents:
```- op: add
  path: /Resources/Service/LaunchType
  value: EC2
- op: remove
  path: /Resources/Service/PlatformVersion
- op: add
  path: /Resources/TaskDefinition/Properties/RequiresCompatibilities
  value: EC2
- op: remove
  path: /Resources/TaskDefinition/Properties/Cpu
  value: EC2
 ```
 And I get the error message:
```
Only found one service, defaulting to: prisidio-svc-v1
✘ look up overrider at "/Users/gautam/Documents/prisidio/workdir/svc/prisidio-svc-v1/copilot/prisidio-svc-v1/overrides": look up CDK project for directories with multiple files: "cdk.json" does not exist under "/Users/gautam/Documents/prisidio/workdir/svc/prisidio-svc-v1/copilot/prisidio-svc-v1/overrides"
```

Even though I am trying to use YAML patch override, instead of CDK override,
Copilot is checking for CDK on my machine. 
Can we please omit this check?

**Comment by dannyrandall** [comment]
Hey @gautam-nutalapati! What version of Copilot are you using that's causing that error? If I remember correctly, that error was in a development version of Copilot, but removed before v1.27 was released 🤔 https://github.com/aws/copilot-cli/commit/6fd1e48faa1d973648f13e09ac8d54565f189da9
