### ISSUE TITLE
Windows 10 installation issue 

### ISSUE THREAD

**Issue by Badrabu** [aws/copilot-cli#4948]
can someone help on the reason why I'm getting access denied :

 Invoke-WebRequest -OutFile 'C:\Program Files\copilot.exe' https://github.com/aws/copilot-cli/releases/latest/download/copilot-windows.exe
Invoke-WebRequest : Access to the path 'C:\Program Files\copilot.exe' is denied.
At line:1 char:1
+ Invoke-WebRequest -OutFile 'C:\Program Files\copilot.exe' https://git ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by Badrabu** [comment]
I run PowerShell as an administrator, and I added path of the copilot to environment variable.
and i still run this error;

PS C:\WINDOWS\system32> copilot --version
copilot : The term 'copilot' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ copilot --version
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (copilot:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by dannyrandall** [comment]
Hey @Badrabu! I saw your [message over on gitter](https://app.gitter.im/#/room/#aws_copilot-cli:gitter.im/$FRviLqZVzQjrs_cLkcY1sicq75kDJy21KtFrPQKe84w) as well - could you try the following steps again? I want to make sure the Copilot executable (not the signature file!) was downloaded while running PowerShell as an Administrator!
1. Run PowerShell as an Administrator
2. Run:
```
Invoke-WebRequest -OutFile 'C:\Program Files\copilot.exe' https://github.com/aws/copilot- 
cli/releases/latest/download/copilot-windows.exe
```
3. Run `copilot --version`

**Comment by Badrabu** [comment]
Hey @dannyrandall  Thx for replay,
when I ran the link you provided, I get this error;
Invoke-WebRequest : The request was aborted: The connection was closed unexpectedly.
At line:1 char:1
+ Invoke-WebRequest -OutFile 'C:\Program Files\copilot.exe' https://git ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

cli/releases/latest/download/copilot-windows.exe : The term 'cli/releases/latest/download/copilot-windows.exe' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:2 char:1
+ cli/releases/latest/download/copilot-windows.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cli/releases/la...lot-windows.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
and for some reason when copied the link i used before(I cant see the difference btw) "Invoke-WebRequest -OutFile 'C:\Program Files\copilot.exe' https://github.com/aws/copilot-cli/releases/latest/download/copilot-windows.exe"
I can see the file downloaded "C:\Program Files\copilot.exe"as an exe file, but when I run copilot --version, I got this error "copilot : The term 'copilot' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ copilot --version
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (copilot:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

**Comment by dannyrandall** [comment]
Hmmm.🤔 Now that you've verified that the file `C:\Program Files\copilot.exe` exists, I wonder if it's only in your _user's_ `PATH`, and not (sorry for my lack of Windows knowledge!) the Administrator's `PATH`? So, assuming that file is still there - what happens if you run PowerShell as your user (**not** as an Administrator) and run `copilot --version`?

**Comment by Badrabu** [comment]
still have same error run PowerShell as user.
 Btw I updated PATH at environmental variables too

**Comment by dannyrandall** [comment]
Could you share the value of your `PATH` env var?

**Comment by Badrabu** [comment]
sure


C:\Python311\Scripts\;C:\Python311\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\PowerShell\7\;C:\Program Files\PowerShell\7-preview\preview;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\copilot.exe;

**Comment by dannyrandall** [comment]
Thanks! I'm curious what happens if you change the last entry - `C:\Program Files\copilot.exe` to `C:\Program Files` instead?

**Comment by Badrabu** [comment]
thanks man its working now :)))

**Comment by dannyrandall** [comment]
np! glad it's working!!😊 Enjoy Copilot☺️
