### ISSUE TITLE
Set Security Policy MinimumProtocolVersion in Copilot created Cloudfront Distribution

### ISSUE THREAD

**Issue by gidsg** [aws/copilot-cli#4953]
Currently I am not sure how to set the viewer [Security Policy](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValues-security-policy) of the Copilot created Cloudfront Distribution.

As this issue was flagged in a Penetration Test we would like to be able to set this in the environment yml, for example equivalent to setting [`MinimumProtocolVersion`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-viewercertificate.html#cfn-cloudfront-distribution-viewercertificate-minimumprotocolversion) in cloudformation.

Is this possible using YAML or CDK overrides? If so please may an example be provided?

**Comment by dannyrandall** [comment]
Hey @gidsg! Here's an example YAML Patch to change the `MinimumProtocolVersion` to `TLSv1.2_2021`:
```
- op: replace
  path: /Resources/CloudFrontDistribution/Properties/DistributionConfig/ViewerCertificate/1/MinimumProtocolVersion
  value: TLSv1.2_2021
```
