### ISSUE TITLE
Storage init (S3) should use other variable name than `DB_NAME`

### ISSUE THREAD

**Issue by adminradio** [aws/copilot-cli#4954]
When running `copilot storage init` and using `S3` as storage type, **Copilot** should use a different variable name than `DB_NAME`. It's misleading and irritating.

Yes, it's cosmetic and I know that I can fix it by myself; but people who are new to this kind of stuff are really unsure and `copilot` could avoid that, when using something like `S3_BUCKET_NAME` or using uppercase **storage resource name** as pre- or suffix. For example `S3_BUCKET_CMSFILES` if running like in the attached screenshot.

<img width="1403" alt="screenshot" src="https://github.com/aws/copilot-cli/assets/2880143/a665aa86-a457-4fb0-81f5-4ebf12e1a78e">

**Comment by dannyrandall** [comment]
Hey @adminradio! Sorry for the confusion and thanks for the feedback!
