### ISSUE TITLE
Possible security issue: credentials cached and mismatch with default profile

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#4977]
Original ticket is below, though as I dove deeper I found something much stranger than it seemed initially.

> Have run through this a few times, starting with `copilot pipeline init` committing the generated files to my repo, and then I running `copilot pipeline deploy`. I get this action required message:
ACTION REQUIRED! Go to https://console.aws.amazon.com/codesuite/settings/connections to update the status of connection copilot-t******* from PENDING to AVAILABLE.
>
> I 've waited and waited and no connection ever shows up. I've tried deleting/starting over/etc, nothing seems to work. 
>
> I did go through the process of trying to create a connection by hand and the creation worked fine (though copilot doesn't seem to know about it). 

It turns out what was actually happening is `copilot deploy` was using some cached credentials (no idea where these were being cached) and deploying to the correct AWS account, HOWEVER my default profile was pointing to a different AWS account and `copilot pipeline init` created this in a totally different AWS account. The upshot, different commands were acting on different accounts. I tried a number of ways to back out of this but I could no longer get either account to properly deploy anything and ended up having to essentially completely destroy all the resources in both AWS accounts and start from scratch!

**Comment by ssyberg** [comment]
Even stranger:
```
% copilot pipeline deploy 
Only found one pipeline; defaulting to: *****-develop
✔ Successfully added pipeline resources to your application: *****
Are you sure you want to redeploy an existing pipeline: *****-develop? Yes
✔ Successfully deployed pipeline: ****-develop
```

But there is nothing reflected in the AWS account at all. FWIW I can do a `copilot deploy` and successfully deploy my services (don't think there are any credential issues).

**Comment by iamhopaul123** [comment]
Hello @ssyberg.

> Have run through this a few times, starting with copilot pipeline init committing the generated files to my repo, and then I running copilot pipeline deploy. I get this action required message:
ACTION REQUIRED! Go to https://console.aws.amazon.com/codesuite/settings/connections to update the status of connection copilot-t******* from PENDING to AVAILABLE.
I 've waited and waited and no connection ever shows up. I've tried deleting/starting over/etc, nothing seems to work.

Did you go to https://console.aws.amazon.com/codesuite/settings/connections and update the status of the connection? Make sure you are in the same pipeline account for the connection update.

> It turns out what was actually happening is copilot deploy was using some cached credentials (no idea where these were being cached) and deploying to the correct AWS account, HOWEVER my default profile was pointing to a different AWS account and copilot pipeline init created this in a totally different AWS account. The upshot, different commands were acting on different accounts. I tried a number of ways to back out of this but I could no longer get either account to properly deploy anything and ended up having to essentially completely destroy all the resources in both AWS accounts and start from scratch!

I am not sure if I understand correctly but please let me know me if anything is not correct. So you tried to

1. Created a pipeline in account A
2. Ran `copilot svc deploy` with default profile to be account A
3. Copilot deployed the service to account B instead of account A which was unexpected to you

Does the description above sound accurate to you?

**Comment by ssyberg** [comment]
> I am not sure if I understand correctly but please let me know me if anything is not correct. So you tried to

Not quite, will try to clarify:
- I originally set up copilot with `export AWS_PROFILE=foo` tied to AWS account `foo`, set up an environment, deployed two Load Balanced Web Services, etc etc
- A few months went by, I hadn't deployed in a while and I went back to this project and forgot to export my AWS_PROFILE before running the `copilot pipeline init`, this used my default profile tied to AWS account `bar`
- Copilot successfully created the connect, but the connect was created in AWS account `bar`, NOT in the account `foo`
- Immediately afterwards, I ran a `copilot deploy` (note my AWS_PROFILE is still pointing to `bar`) and the services were successfully deployed to `foo`!

So as I said above, depending on the copilot command I was running, copilot was modifying a _different aws account_. Backing out of this proved impossible, I could not get the `foo` account to register again and could not add any new services or pipelines. I tried for hours to delete all of the stacks and roles and everything copilot had generated but I still ran into multiple errors. I ended up actually just _closing the AWS account entirely_ and starting over.

**Comment by ssyberg** [comment]
FWIW for people who manage a lot of projects this could happen very easily, we should really be able to specify which profile to use in the copilot config itself or this is bound to happen again.

**Comment by iamhopaul123** [comment]
Hello @ssyberg. I feel like this bug had been fixed. What's your Copilot version? I tried to reproduce this using the latest Copilot version and I got `✘ validate application: couldn't find an application named demo in account 1234567890 and region us-west-2` for both `copilot pipeline init` and `copilot deploy`.

**Comment by ssyberg** [comment]
I'm running 1.28.0

**Comment by iamhopaul123** [comment]
That's very strange. I was using v1.28.0 to

1. Created an app and get the services/envs deployed in account `foo`
2. Switched my default profile to `bar`
3. Ran `copilot pipeline init` and `got `✘ get application demo configuration: couldn't find an application named demo in account bar  and region us-west-2`
4. Ran `copilot deploy` and got `✘ select service or job: no jobs or services found`

I think you _might_ have run `copilot app init` again in the `bar` account before, and right now we don't have a good mechanism preventing users from creating app with the same name in different AWS account (if it is in the same AWS account but different region we will error out tho). Could you help me check if in your `bar` account you have a parameter called `/copilot/applications/yourAppName`?

**Comment by ssyberg** [comment]
It is possible that I ran `copilot app init` in the `bar` account, but I think the "bug" here would still be that different copilot commands were using different credentials. Again I'd suggest specifying which credentials you should use a config could address this.

As an aside, having ran app init a few times today, I also noticed I can no longer specify a profile other then default. The only options it shows me are "temporary credentials" or the default profile (and my aws/credentials lists roughly 15 different profiles.

**Comment by iamhopaul123** [comment]
> Again I'd suggest specifying which credentials you should use a config could address this.

That makes sense to me! It's one of the action item on top of our backlog.

> As an aside, having ran app init a few times today, I also noticed I can no longer specify a profile other then default. The only options it shows me are "temporary credentials" or the default profile (and my aws/credentials lists roughly 15 different profiles.

Did you mean `env init`? I don't think we ask for profile when `app init` 🤔

**Comment by ssyberg** [comment]
> Did you mean env init? I don't think we ask for profile when app init 🤔

Ha certainly possible, getting it all confused in my head!
