### ISSUE TITLE
Suggestion: option to specify ARN when using --permissions-boundary

### ISSUE THREAD

**Issue by dsm1015** [aws/copilot-cli#4978]
Custom paths and checks within our AWS environment prevent Copilot from correctly identifying the permissions boundary when only providing the name of the boundary with `--permissions-boundary`. Please add the option to use the ARN of the boundary for identification.

**Comment by huanjani** [comment]
This enhancement has been released in v1.29.0: https://github.com/aws/copilot-cli/releases/tag/v1.29.0! Thanks for the suggestion!
