### ISSUE TITLE
What is the idiomatic way to deploy services in different repositories with Copilot?

### ISSUE THREAD

**Issue by PedroAlvarado** [aws/copilot-cli#4982]
We have multiple services under different github respositories. We are wondering what would be the idiomatic way to use copilot in this case? (multiple apps each with one services vs multiple services under one app, etc)

**Comment by iamhopaul123** [comment]
Hello @PedroAlvarado. You can have the following dir structure:

```
SRC
|- copilot
  |- .workspace
  |- environments
  |- serviceA
    |- manifest.yaml
  ...
|- serviceA
  |- Dockerfile
  |- src
|- serviceB
  |- ...
...
```

And you run `$copilot app init` in SRC with all the services/envs in the `copilot `folder.

**Comment by PedroAlvarado** [comment]
@iamhopaul123 Thank you for your prompt response. 

In your example "copilot", "serviceA" and "serviceB" are different Git repositories? To clarify, we have no desire to create a mono-repo. Instead, we are wondering if there is well-known pattern to work with copilot while keeping our services under different Git repositories.

**Comment by iamhopaul123** [comment]
Sorry about that. If it is not a mono repo, you can run `copilot app init` within "serviceA" and "serviceB" respectively and use the same appName:
```
SRC
|- serviceA
  |- copilot
    |- .workspace
    |- environments
    |- serviceA
      |- manifest.yaml
  |- Dockerfile
  |- src
|- serviceB
  |- ...
...
```

**Comment by ghost** [comment]
Following the advice above, you will end up with duplicate manifests of your infra within each repository. Doesn't seem like a great idea.
I think the answer is to have a separate infra repo. But for the container sources, you will need to either:

- Build docker images from individual service repos into ECR, and hand off to the infra repo to deploy, passing along the image to use.  But copilot commands don't seem to support just the ECR upload step alone.
- Move or duplicate dockerfiles into the infra repo (Neither sounds good)
- Checkout the service repos to gain access to the dockerfiles, or `curl` the dockerfiles from Github.

I'm not sure why this is not specified in the docs. And all of the walkthroughs online conveniently assume all your services are in the same repo. Which I don't expect is the default scenario...

**Comment by iamhopaul123** [comment]
Alternatively you can have environments defined in a separate infra repo


```
SRC
|- copilot
  |- .workspace
  |- environments
|- serviceA
  |- copilot
    |- .workspace
    |- serviceA
      |- manifest.yaml
  |- Dockerfile
  |- src
|- serviceB
  |- copilot
    |- .workspace
    |- serviceB
      |- manifest.yaml
  |- ...
...
```

**Comment by neanias** [comment]
Hi, follow-up question for this: when creating a shared Copilot infrastructure repo for environments as suggested, should pipelines also go in there or are they best kept with their services?
