### ISSUE TITLE
How to enable "deployment.rolling: recreate" when using copilot pipelines?

### ISSUE THREAD

**Issue by PedroAlvarado** [aws/copilot-cli#4987]
We are developing copilot pipelines. We find ourselves having customize the buildspec.yml file. During this development process, it would be very convenient to setup ECS deployment similarly to how "deployment.rolling: recreate" works. Is there a way to achieve this behavior at development time?

**Comment by huanjani** [comment]
Hi, @PedroAlvarado!

If you're looking for a while to enable `deployment.rolling: recreate` for Copilot services that are deployed via a Copilot pipeline, great news: that deployment config is already applied, even when deploying via pipeline. Or are trying to do something else?

Also, I'm just curious, what is prompting you to customize the buildspec? We are hoping to improve our pipeline feature, and always like hearing user input!

Thanks!

**Comment by PedroAlvarado** [comment]
@huanjani Thank you.

We customize buildspec because we do not use docker files. Instead, we use BuildPacks(https://paketo.io/). This requires us to build our images and publish them to ECR ourselves before we can use "image.location". Buildspec is where we make this happen for lack of a better place/alternative.

Let me know if this makes sense to you or if there is a better practice you know of. Thanks!

**Comment by huanjani** [comment]
Hi, @PedroAlvarado. Sorry for the late reply. I just want to clarify what the `recreate` setting is for: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling. This is what you intended, right? Thanks!

**Comment by PedroAlvarado** [comment]
> Hi, @PedroAlvarado. Sorry for the late reply. I just want to clarify what the `recreate` setting is for: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling. This is what you intended, right? Thanks!

Yes
