### ISSUE TITLE
How to re-upload files to S3 through copilot for Static Site

### ISSUE THREAD

**Issue by YiCChi** [aws/copilot-cli#5001]
I am using Static Site workload. 
When I deployed for the first time, copilot uploaded my local files to S3.
But when I deployed again, copilot told me that change set has no change so deployment failed.
Is there a way to re-upload files to S3 via copilot cli?
btw, I'm building a react app.

**Comment by iamhopaul123** [comment]
Hello @YiCChi. The changeset is empty probably because you don't have any changes either for the setting or the files you want to upload. 

> Is there a way to re-upload files to S3 via copilot cli?

If you make any changes to these files - adding new files, removing any files, or modify any files content, the deployment should be picked up by Copilot

**Comment by YiCChi** [comment]
Thank you @iamhopaul123 .
It's my mistask.
BTW, does this mean that I can use the code pipeline to complete CD?
And BTW, I split my react app into chunks during build. I'm worried that if the name of the chunk changes every time it is built, it will cause old files to remain in S3.
Well, what I want to ask is, in this case, should I empty S3 every time before uploading, or I just don't need to care about it . 
Do you have any advice.

**Comment by iamhopaul123** [comment]
> BTW, does this mean that I can use the code pipeline to complete CD?

Yes that's correct.

> should I empty S3 every time before uploading, or I just don't need to care about it . Do you have any advice.

Hmm if you empty the S3 every time before uploading, doesn't it cause the down time of your service (like users won't be able to see certain static content during deployment time)? I would suggest keep the file name the same and only update the content instead of the file name.

**Comment by YiCChi** [comment]
Thanks, @iamhopaul123 .
You are right. I'd like to try your advice.
