### ISSUE TITLE
Allow deploying all services in a Copilot app with a single command

### ISSUE THREAD

**Issue by lewijacn** [aws/copilot-cli#5002]
It would be helpful to be able to deploy all services contained within an application with a command similar to :
`copilot deploy --all `

This functionality may be present as part of Pipelines but would be helpful for cases where Pipelines are not used.

Additionally having the functionality to specify a set of services and their order within a deployment command would be very useful:
`copilot deploy --svc-list service1,service2,service3`

**Comment by iamhopaul123** [comment]
Same as #3474

**Comment by lewijacn** [comment]
Closing as duplicate of https://github.com/aws/copilot-cli/issues/3474
