### ISSUE TITLE
[Question/Feature?] Addons Env Deployment 

### ISSUE THREAD

**Issue by remstone7** [aws/copilot-cli#5014]
Not entirely sure if this is a question / feature request or maybe me formatting my project somewhat incorrectly.  I have a setup as follows:

```
copilot
  ./environments
     ./production/
     ./staging
     ./addons/ [redis / rds]
  ./api
```

I deployed a staging environment with redis & rds addons. I just went to deploy my production environment and used `copilot env init` and set up my production env.  Inside of my AddOns, i use CF Mappings, so i specified db size, redis cache size etc.. for the new production env.  For RDS, i have a line like `VpcId: { 'Fn::ImportValue': !Sub '${App}-${Env}-VpcId' }` to dynamically import the vpcid of the environment.  

Once this was all setup, i ran  `copilot env deploy --name production` to deploy my environment.  Naively, i assumed it would make changes to the actual production env first and then do the addons, instead i immediately received an error that my VpcId wasn't found and it was related to my rds addon.

I'm surprised that the environment wouldn't deploy the main environment first and then deploy the addons after, is this expected behavior? If not, it would be great to include a flag like `copilot env deploy --name production --skip-addons`. So i can run this first and then re-deploy my addons after with `copilot env deploy --name production`.  Instead, i just removed the addons dir, deployed my env, then re-added my addons folder and redeployed the environment.

Thanks!

**Comment by ssyberg** [comment]
Following

**Comment by KollaAdithya** [comment]
Hey @remstone7 👋 

In order to refer the `VpcId` from the environment stack in your nested addons stack. In `addons.parameters.yml`, you can define the values of those additional parameters.

```
.
└── addons/
    ├── template.yml
    └── addons.parameters.yml # Add this file under your addons/ directory.
```
You can follow these steps.
1. In `addons.parameters.yml` you can have
```
Parameters:
  VPCID: !Ref VPC
```
This will refer to values from your environment stack.

2. In the `template.yml` In the Parameters section
```
Parameters:
# Additional parameters defined in addons.parameters.yml
  VPCID:
    Type: String
    Description: The ID of the VPC in which to create the Aurora Serverless v2 cluster.
    Default: ""
```
In this way directly refer to `VPCID` in the addons stack`

**Comment by remstone7** [comment]
thanks @KollaAdithya that makes a lot of sense, figured i had set this up incorrectly, although the way i had it works if the env is deployed prior to the addons, will use this for reference in the future!

**Comment by KollaAdithya** [comment]
You can refer to our docs on Addons over here https://aws.github.io/copilot-cli/docs/developing/addons/workload/. 
Closing the issue for now. Feel free to reopen incase of any other problem.

**Comment by KollaAdithya** [comment]
In case if you are importing your VPC you can refer to this issue #4419
