### ISSUE TITLE
ECS task definition not generating the correct image tag after copilot svc deploy

### ISSUE THREAD

**Issue by vshah11** [aws/copilot-cli#5019]
There is a test environment setup using copilot env init along with a Load Balanced Website deployed using copilot svc init/deploy. 

There was a recent cleanup due to which we decided to recreate the environment and initialize the services again in it. But for some subtle reason, it is not correctly deploying the service within it. For further details, the ECS task definition just contains the last 7 characters of the git commit instead of having the entire image tag and using 'copilot svc package' did not really help to find why the container image did not have the correct value.

The screenshot below is what is currently being generated - 
<img width="393" alt="Screenshot 2023-06-21 at 10 10 30 AM" src="https://github.com/aws/copilot-cli/assets/124619761/df017247-60ee-4c3a-948d-adbd8ae4a947">

This is what it should look like (screenshot is of another development server) - 
<img width="653" alt="Screenshot 2023-06-21 at 10 12 20 AM" src="https://github.com/aws/copilot-cli/assets/124619761/a75f9573-f7a9-4e65-9f8b-9c14683df0ad">

Any kind of guidance to figure out the actual reason this is happening would be really helpful! 

Thank You!

**Comment by KollaAdithya** [comment]
Hey @vshah11 !

If you are using `image.build` to build your image locally, you will see the below ⬇️  UX for `building your container image`.
```yaml
Building your container image "happy": docker build -t 535307839156.dkr.ecr.eu-west-2.amazonaws.com/hyatt/happy:latest --platform linux/x86_64 --label com.aws.copilot.image.builder=copilot-cli --label com.aws.copilot.image.container.name=happy --label com.aws.copilot.image.version=v1.28.0 /Users/kolladit/demo/web -f /Users/kolladit/demo/web/Dockerfile
     19c5a00adb61: Layer already exists
     78a822fe2a2d: Layer already exists
     33eb4c69ef1d: Layer already exists
     latest: digest: sha256:44b8f0e81f9201e4e4b3574a4afa363abe147def63c18bedba69f361d69cf789 size: 1780
```

can you please run `copilot svc deploy` and paste the same UX for your container image. This will help us to know the issue on why the image URI is not correctly populated in the task definition.

**Comment by vshah11** [comment]
Hey @KollaAdithya!

Thank you for the prompt response. 

Am not sure if we were using image.build but I have attached a screenshot of the UX that comes up once we build the container. Let me know if that helps to resolve the issue.

<img width="1406" alt="Screenshot 2023-06-21 at 11 51 38 AM" src="https://github.com/aws/copilot-cli/assets/124619761/b7764a84-32c6-4775-9ddc-23240937caf3">

<img width="1143" alt="Screenshot 2023-06-21 at 11 49 36 AM" src="https://github.com/aws/copilot-cli/assets/124619761/f5afac87-8a78-44b6-88a2-aa2c7038117b">

Its post the build that the copilot deploy begins to  update the task definition & infrastructure stack.

**Comment by KollaAdithya** [comment]
can you go to the AWS CloudFormation Console and look at the service stack and see the `parameters` section and look at for the Container Image Parameter

It should look like something below ⬇️ 
![Screenshot 2023-06-21 at 12 08 15 PM](https://github.com/aws/copilot-cli/assets/71282729/e1d48f7a-1774-4109-beae-fbfdf0d65b71)

can you provide the screenshot of your `Container Image` param

**Comment by vshah11** [comment]
Sure, that container image is all what is causing the issue. I have attached the screenshot below. (Just for reference, I have two services in the environment and the first one deploys just fine with no issues even though I recreated the environment and the service later. Its only this one - 'study-portal' that is acting funny)

<img width="1069" alt="Screenshot 2023-06-21 at 12 12 35 PM" src="https://github.com/aws/copilot-cli/assets/124619761/e6e68b28-fbb7-4ae3-90a8-e29bfc6feb17">

**Comment by KollaAdithya** [comment]
Which version of copilot are you using?

**Comment by vshah11** [comment]
I am using - copilot version: v1.26.0

**Comment by KollaAdithya** [comment]
It is a bit odd that one service is getting properly tagged and the other one isn't. can you provide your manifest if you don't mind

**Comment by vshah11** [comment]
<img width="1056" alt="Screenshot 2023-06-21 at 12 33 56 PM" src="https://github.com/aws/copilot-cli/assets/124619761/f71ab167-776e-49c3-a199-614cfb61d310">

Post the service definition, the manifest contains details for an associated sidecar. I dont think thats relevant because the sidecar is correctly tagged and deployed.

**Comment by vshah11** [comment]
Hey @KollaAdithya!

Any suggestions or reviews on the manifest?

**Comment by KollaAdithya** [comment]
@vshah11 Your manifest looks good to me.

I just deployed a LoadBalanced web service with Copilot v1.26.0 with same config as your manifest and the image is getting properly tagged and  I am able to deploy my service.

Is the Image correctly pushed to AWS ECR repository? Can you go to AWS ECR repository and see whether the image is there in the repository created by Copilot

As a workaround you can use `image.location`([doc](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-location)) and point to the Image already pushed to ECR repository. Let me know if this works!

**Comment by vshah11** [comment]
I decided to delete the existing image and repository on ECR. Creating and deploying the service after that seems to magically work with no issues regarding the container image.

Thank you for pointing me in this direction @KollaAdithya 

Will close the issue since there is nothing else left to be done here.

**Comment by GerardGarcia** [comment]
same happened to us today. No idea why, we are still investigating

**Comment by vshah11** [comment]
> same happened to us today. No idea why, we are still investigating

Hey Gerard,

Do try to delete the existing  image on your Elastic Container Repository and then redeploy the service. That surprisingly worked for me.

**Comment by GerardGarcia** [comment]
Thanks, but doesn't seem to solve my issue.

EDIT: I tried to just delete the image. I think the point is re-creating the service since that will update the infrastructure stack and add the ECR (see next message)

**Comment by GerardGarcia** [comment]
Apparently, all the ECR repos got deleted from the `<app>-infrastructure` stack. Seems like someone created a new svc (`svc init`) with copilot v1.26 after updating to v1.28 and that triggered the deletion of all these ECRs (I can see it in the stack event history). It failed to delete them because there were still images, though. I think they should be there because if I create a new svc using v1.28 it adds the ECR repo there.

I'm assuming these outputs are used by copilot to determine the ECR name when deploying a service but that is just an assumption. I'll try to update the template manually and re-add the ECR repos to see if that is enough to solve the issue. If someone has an idea to properly update the `<app>-infrastrucutre` stack so it re-adds all the ECR (and undos any other change, if any) that would be very helpful.

EDIT: that may be a better way to do it: https://matrix.to/#/!QdxoBcgpJveoAoIPCc:gitter.im/$zD_GizF1tSqT7bRZnU5L8LLIkruESOKwzUCdpu8Q-jA?via=gitter.im&via=matrix.org&via=matrix.unope.ru

**Comment by dannyrandall** [comment]
Hey @GerardGarcia! Sorry about the headache.😔 Your analysis is correct! For some reason the Gitter link you shared isn't loading for me, so I just wanted to share a different link to what I'm assuming is the same thread: https://app.gitter.im/#/room/#aws_copilot-cli:gitter.im/$cMgL8ey5pMdDFlJCKqDVdcEb394KOhGj6XjxQQZRUfc. 

Additionally, we're adding a mechanism in our upcoming release (v1.29) to help prevent (but still allow, if requested!) someone unintentionally downgrading their Copilot stacks. This should help prevent this class of issues in the future 🤞.
