### ISSUE TITLE
Should the ECR repository name contain the environment?

### ISSUE THREAD

**Issue by joanniclaborde** [aws/copilot-cli#5028]
Hi,

First of all, thanks for this project, it's great!! So we use copilot to deploy our service to two environments, `staging` and `production`. The images are both built from the same Dockerfile but with different `args`, so they do not contain the exact same code. After deploying `staging`, I noticed that the repo name in ECR doesn't contain the environment, just the app name and service name (`my_app/my_svc:[commit_hash]`).

If I deploy `production` now, the repo name and commit hash will be the same, but the image will be different, right? I'm thinking of using the `--tag` argument when building the images, to prevent this name clash:

```bash
% copilot svc deploy --env staging --name my_svc --tag $(git rev-parse --short HEAD)-staging
```

Is this the right way to proceed, or should somehow the repo name be `my_app/staging/my_svc` (I have found no way to change this)?

Thanks!

**Comment by huanjani** [comment]
Hi, @joanniclaborde!

We're so glad you are enjoying Copilot! Yes, you are correct that `--tag` should enable you to differentiate your images between your environments. Let us know if you have any other questions!

Related: https://github.com/aws/copilot-cli/issues/4517

**Comment by joanniclaborde** [comment]
Oooh sorry I missed that issue, thanks for the confirmation!
