### ISSUE TITLE
override-az-names options is not work

### ISSUE THREAD

**Issue by interu** [aws/copilot-cli#5037]
Hey!

As of copilot v1.28.0

```sh
copilot env init --name $APP_ENV_NAME --profile $AWS_PROFILE --override-public-cidrs 10.1.0.0/24,10.1.1.0/24 --override-private-cidrs 10.1.100.0/24,10.1.101.0/24 --override-vpc-cidr 10.1.0.0/16 --override-az-names ap-northest-1c,ap-northeast-1d
```

However, VPC subnets are created in `ap-notheast-1a` and `ap-northeast-c`. <<-- default selected value

I got the same result whether I changed it in the GUI or specified the override-az-names option.

**Comment by interu** [comment]
Sorry, I specified it in manifest.yml.

**Comment by huanjani** [comment]
Hi, @interu! 
I'm glad you were able to get unstuck using the manifest, but I am still confused and concerned about why the `--override-az-names` flag didn't work as expected. 🤔

**Comment by huanjani** [comment]
Okay, I just tried to reproduce your experience. 
Did the env manifest that was automatically generated have your desired AZs listed? That should happen. What we would expect to be created in your default and/or app region are the **bootstrap resources**.

**Comment by interu** [comment]
@huanjani 

I am building multiple applications with copilot-cli, so I have prepared manifest.yml in advance.
So `env init` skips generating manifest.yml.
This time, I missed that log. It was my mistake and I closed the issue.
