### ISSUE TITLE
Copilot pipeline is not gets Trigger

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#5039]
Hi, I configured Copilot 2 months ago, and it was working fine. However, for the past month, I haven't deployed anything. Recently, I pushed a new commit to my CodeCommit repository, but the pipeline did not start. Could you please help me fix this issue?

![image](https://github.com/aws/copilot-cli/assets/78138014/997803d6-ea77-41ae-9a1b-d45f12e5c538)

**Comment by Lou1415926** [comment]
@Dhina-test For now, you can start the pipeline execution manually, either via. the "Release change" button on the console or aws-cli (see [the AWS doc](https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-rerun-manually.html) for more). 

There is one thing that I'm not sure of. After you trigger a manual execution, is this "inactive pipeline" switched back to being an "active pipeline", hence start the polling again? Would you please let me know if & after you've tried?

**Comment by Lou1415926** [comment]
However this brings to my attention that we currently don't have a great way to support event-based change detection. This will be a feature request from us. 

Perhaps we can introduce a manifest field for pipeline:
```yaml
source:
  provider: CodeCommit

 # New field.
 change_detection: 'event-based' 
 # or change_detection: 'polling'
``` 

If empty, it defaults to `'polling'`. `copilot pipeline init` will produce a manifest with `'event-based'`, as it is now the recommendation by CodePipeline.

Before Copilot offers any built-in support for this, people should be able to use `copilot pipeline override` (once released) to deploy an event-based pipeline. 


On how to configure an event-based pipeline (helpful for both the core-team for developing the build-in support, and folks that need to use pipeline override): https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html#update-change-detection-codecommit

Related: #4208 #4209 #5034

**Comment by huanjani** [comment]
It's now possible to switch your pipeline to `event-based`, using the pipeline overrides feature introduced in v1.29.0: https://github.com/aws/copilot-cli/releases/tag/v1.29.0!

Here is a YAML patch that you could use to do this! https://gist.github.com/Lou1415926/099ae2a2f681bf510b9fb2dad35926d4
