### ISSUE TITLE
Bug: "more than one ECS cluster are found with tags" .. 

### ISSUE THREAD

**Issue by erno** [aws/copilot-cli#5052]
My `copilot task run` invocation is failing with the error message: `run task <task name>: get cluster for environment dev1: more than one ECS cluster are found with tags "copilot-application"="<app name>","copilot-environment"="dev1"`

I didn't see any other such clusters in the web console. I put some debugging prints in the copilot source code and found which ARN the second cluster was about. With aws cli I could call describe-clusters on it and saw that it was in INACTIVE state. In https://docs.aws.amazon.com/cli/latest/reference/ecs/delete-cluster.html it is said that "Clusters with an INACTIVE status might remain discoverable in your account for a period of time".

The deleted cluster is from (at least) last week, this is not a transient state.

It would seem to me that when searching for ECS clusters by tag, the copilot code is either not filtering out INACTIVE status clusters or there is some other problem in in the cluster finding logic.

Update: also happens with other commands, eg `copilot job delete` - discovered as I attempted to delete the environment contents (trying to recreate the environment with a new name).

**Comment by dannyrandall** [comment]
Hey @erno! Thanks for the bug report! We should definitely filter out the non-active clusters. I just opened https://github.com/aws/copilot-cli/pull/5062 which should resolve the issue - feel free to test after it's merged and lmk if you still run into issues!

**Comment by huanjani** [comment]
This fix has now been released in v1.29.0: https://github.com/aws/copilot-cli/releases/tag/v1.29.0!
