### ISSUE TITLE
copilot task exec shows error of more than one cluster found

### ISSUE THREAD

**Issue by rickychew77** [aws/copilot-cli#5053]
Currently wanted to try out this command for ease of accessing the task without getting the task ID everytime and doesn't seems to able fix the ECS cluster name.

However, running this command with `-e` and `-n` flag gives error of `list active tasks in environment dev: more than one cluster is found in environment` however there's only one cluster in my environment.

How can we leverage this potentially useful troubleshooting CLI commands? Is there anything we missed?

**Comment by dannyrandall** [comment]
Hey @rickychew77! Does your issue look the same as this one? https://github.com/aws/copilot-cli/issues/5052

**Comment by rickychew77** [comment]
Oops yes the error is similar, just that using different CLI command. Thanks for pointing it out.

**Comment by dannyrandall** [comment]
This has been resolved by https://github.com/aws/copilot-cli/pull/5062!

**Comment by huanjani** [comment]
The fix to this issue has been released in v1.29.0: https://github.com/aws/copilot-cli/releases/tag/v1.29.0! Thanks for bringing it to our attention!

**Comment by rickychew77** [comment]
hey, thanks for the prompt update. just tried it with v1.29.0, running same command (`copilot task exec -e dev -n <app_name>`) output this:
`✘ select running task in environment dev: no running tasks found` 

did I missed anything?

**Comment by huanjani** [comment]
Hi, @rickychew77. 
Just to confirm: `<app_name>` is the name of your service, job, or task group, right? And your expectation is that there is exactly one running task in your environment?

**Comment by rickychew77** [comment]
@huanjani yup, that is correct. there is only one service running but it keep saying no running task found

**Comment by dannyrandall** [comment]
@rickychew77 just to clarify, are you trying to `exec` into a _service_ (`copilot svc exec`), or a task (`copilot task exec`)? If a task, could you take a look at the ECS console in the cluster for your app and share the ECS Services that are listed there, and verify that there is at least one ECS Task running in that service?

**Comment by rickychew77** [comment]
@dannyrandall i am trying to exec into a task using `copilot task exec -e dev -n <my_app_name>`  and there is task running it. I still can do `aws ecs execute-command` though but it seems that i cannot control the cluster name and task id changes on each deployment. wanted to use this cli to make it more convenient instead of fetching the new task id everytime.

**Comment by dannyrandall** [comment]
And this was a task created by Copilot, correct? Started by using `copilot task run`? If so, could you share what the tags for your service and task look like? If you go to the ECS console -> your env's cluster -> the service for your task -> tags and taskID -> tags.

**Comment by rickychew77** [comment]
yes they were created by Copilot, these tasks were created by `copilot svc deploy`. they all have these tags `copilot-application`, `copilot-environment` and `copilot-service`

**Comment by dannyrandall** [comment]
Gotcha! Since they were created by `copilot svc deploy`, can you try `copilot svc exec` to see if that works?

**Comment by rickychew77** [comment]
hey @dannyrandall  thanks so much it works! i overlooked this from the docs.
