### ISSUE TITLE
Copilot pipeline build failed

### ISSUE THREAD

**Issue by Dhina-test** [aws/copilot-cli#5059]
Hi I tried to create copilot pipeline ,
So I did  below

1.**copilot app init**
2.**copilot svc init**
3.**copilot pipeline init**
and then i pushed changes to codecommit repository
4.Then i did **copilot pipeline deploy** 

And then pipeline were started , but build is getting failed
![image](https://github.com/aws/copilot-cli/assets/78138014/20a62c4e-b57d-457a-b2fe-443026477793)

can you please help

**Comment by Lou1415926** [comment]
It seems like you've reached docker pull rate limit (the error message on the second line of the screenshot). Can you try the [solution mentioned here](https://github.com/aws/copilot-cli/issues/1869#issuecomment-765643674) and see if it goes away?
