### ISSUE TITLE
Generating Aurora DB with storage init leads to undefined resource error

### ISSUE THREAD

**Issue by TheAdamGalloway** [aws/copilot-cli#5087]
I am trying to provision an Aurora DB using copilot. The service has already been deployed successfully with a test environment. I ran `copilot storage init` successfully and have updated my application code to use the new secrets. However, when I run `copilot svc deploy` it ends up failing with:

> Proposing infrastructure changes for stack leaf-backend-test-leaf-backend-service
> ✘ execute svc deploy: deploy service leaf-backend-service to environment test: deploy service: check if changeset is empty: create change set copilot-abca7ad4-1419-4d16-993f-bbf056e9c0a7 for stack leaf-backend-test-leaf-backend-service: ValidationError: Template error: instance of Fn::GetAtt references undefined resource ServiceSecurityGroup
>         status code: 400, request id: 8f2e042c-63ea-496d-a7ad-e9401f62690b: describe change set copilot-abca7ad4-1419-4d16-993f-bbf056e9c0a7 for stack leaf-backend-test-leaf-backend-service: ChangeSetNotFound: ChangeSet [copilot-abca7ad4-1419-4d16-993f-bbf056e9c0a7] does not exist
>         status code: 404, request id: b9edd49f-813f-44d4-be8f-3f13229802d2

My parameters file: 
`Parameters:
  ServiceSecurityGroupId: !GetAtt ServiceSecurityGroup.GroupId`

It seems to be an issue with the ServiceSecurityGroupId parameter referencing the SecurityGroup resource. I have tried changing 'ServiceSecurityGroup' to the logical name of the resource (leafbackendserviceclusterDBClusterSecurityGroup) but this also doesn't work. Could this be some issue with parameters being defined before resources are created? I'm really not sure what else I can try.

**Comment by Lou1415926** [comment]
Hello @TheAdamGalloway. Two quick questions - is `leaf-backend-service` a request-driven web service? Is the `network.vpc.placement` to `"private"` ?

`ServiceSecurityGroup` is a security group that is only created if you set `network.vpc.placement` to `"private"` (this puts the RDWS into a VPC, and an RDWS has to be in a VPC in order to use security group). If your placement is "public", the resource is not there, and it would cause a `instance of Fn::GetAtt references undefined resource ServiceSecurityGroup` error.

**Comment by TheAdamGalloway** [comment]
Thanks for your help @Lou1415926 - looks like that was the cause of my error. I've just redeployed but it has been stuck on creating the Aurora writer instance for about 30 mins. Hopefully it will work!

**Comment by TheAdamGalloway** [comment]
Oh btw, think it might be worth documenting this somewhere. I lost hours looking for a solution! :)
