### ISSUE TITLE
Pipeline CloudFormation Error: File [infrastructure/???.params.json] does not exist in artifact [BuildOutput]

### ISSUE THREAD

**Issue by lominming** [aws/copilot-cli#5088]
Situation:
- I am using Load Balanced Web Service (Fargate)
- 2 environments: test and prod
- svc deploy for both environment works fine

Added codepipeline via `copilot pipeline`:
- added `workload` type
- setup flow such that Github code > build > deploy to test > deploy to prod

What happen:
- Failed at Deploy to Test with the message of `File [infrastructure/app-test.params.json] does not exist in artifact [BuildOutput]`
- I don't know what happen at all because all the infrastructure files are generated, and I cannot find a way to "browse" them either
- Debugging is basically impossible, and this is just the default push

The closest I see someone else having this issue is a while back: https://github.com/aws/copilot-cli/issues/2033

What I suspect:
- My copilot files are in root i.e. `./`
- But my Dockerfile is in app i.e. `./app` 
- Is that causing the error?

![image](https://github.com/aws/copilot-cli/assets/742933/79c4cf11-2a87-45e0-a340-26fdf48505ac)

**Comment by vicpara** [comment]
I had the same issue. 
Delete this one and try the other pipeline type. That worked for me.

**Comment by zachradtka** [comment]
I have the same issue as @lominming . I have tried to use both the `Workloads` pipeline and `Environments` pipeline and I get the same error for every service I am trying to deploy: 
```
File [infrastructure/api-test.params.json] does not exist in artifact [BuildOutput]
```
Looking at the artifacts from BuildOutput in S3 there are only two files: test.env.params.json and test.env.yml. It seems to not be creating artifacts for my services.

**Comment by vicpara** [comment]
If you run 'copilot svc deploy' does it work successfully without any errors?

**Comment by iamhopaul123** [comment]
I wonder if you have the "workload" pipeline manifest with the "env" pipeline buildspec for some reason. Would you mind sharing your buildspec file by any chance?
