### ISSUE TITLE
copilot pipeline init creates publicly accessible s3 buckets

### ISSUE THREAD

**Issue by gabelton** [aws/copilot-cli#5089]
We've noticed that buckets created by running `copilot pipeline init` (e.g. codepipeline, cloudtrail) are getting flagged by Trusted Advisor / Security Hub as missing some of the expected public access blocks. Is this by design or should it be considered a bug?

<img width="1095" alt="Screenshot 2023-07-14 at 16 04 44" src="https://github.com/aws/copilot-cli/assets/46938749/32c91568-fa52-485d-8818-c9f2e1c8b105">

**Comment by bvtujo** [comment]
None of the artifacts that Copilot uploads have public access turned on; we don't configure default public access blocks but I think this is something we should consider. Thanks for bringing this to our attention!

**Comment by iamhopaul123** [comment]
Hello @gabelton. The request totally makes sense to me. As a temporary workaround in the meanwhile, could you set [block public access at the account level](https://docs.aws.amazon.com/AmazonS3/latest/userguide/configuring-block-public-access-account.html)?

**Comment by dannyrandall** [comment]
Hey @gabelton! This fix has been released in [v1.29.1](https://github.com/aws/copilot-cli/releases/tag/v1.29.1)!🚀🎉
