### ISSUE TITLE
Remove the 64 character domain name limit

### ISSUE THREAD

**Issue by richardbored** [aws/copilot-cli#5101]
I work in an organisation where apps must be deployed under a subdomain, creating fairly long domains. Is it possible to remove this limit? Trying to find ways around this limitation is becoming arduous. 

Thanks!

R

**Comment by bvtujo** [comment]
Unfortunately, this [limitation comes from ACM](https://docs.aws.amazon.com/acm/latest/APIReference/API_RequestCertificate.html#ACM-RequestCertificate-request-DomainName), which is our tool for validating certificates for custom domains. 

Short of taking DNS management fully into your own hands, I don't have a lot of solutions for you 😞 . Is there any way you could create some internal DNS record with a shorter name for copilot purposes and redirect your long subdomains to that?

**Comment by bvtujo** [comment]
On further reading, it looks like we might be able to pass longer aliases to the SubjectAlternativeNames field, but this may require a significant refactor on our part. To help me diagnose feasibility, can you share what errors you're getting and at what stage of the deployment process?
