### ISSUE TITLE
Aurora Serverless V1 creates a Postgres Family engine 10

### ISSUE THREAD

**Issue by pvborromeo** [aws/copilot-cli#5110]
When running the following commands:

`$ copilot storage init -t Aurora -l environment --serverless-version v1`
`$ copilot env deploy`

It generates a Manifest which has by default an engine family 10 which seems to be no longer available and the following message is given:

`Resource handler returned message: "The engine mode serverless you requested is currently unavailable. (Service: Rds, Status Code: 400, Request ID: 0e03048b-982f-49b8-9ccf-e53a35680b6c)" (RequestToken: 3761f6c0-e7ba-ee5f-d0e4-d4beae8ede87, HandlerErrorCode: InvalidRequest)`

**Comment by bvtujo** [comment]
Thanks for bringing this up! We'll get a fix out as soon as possible once we verify the supported aurora serverless versions.

**Comment by dannyrandall** [comment]
Fixed in https://github.com/aws/copilot-cli/pull/5121!
