### ISSUE TITLE
Attach ManagedPolicy to a Task Role using AddOns

### ISSUE THREAD

**Issue by pvborromeo** [aws/copilot-cli#5118]
Hello Copilot-cli Team,

I am trying to add a managed policy using add ons, but I'm noticed that the policy is not being added to the Task Role but to the Execution Role. Below you can see the configuration used for the addOn at the service level:

```
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: Your workload's name.
Resources:
  MyDBSecretAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Grants Read access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: ["secretsmanager:*"]
            Resource: "*"
              
Outputs:
  # 1. You need to output the IAM ManagedPolicy so that Copilot can add it as a managed policy to your ECS task role.
  MyDBSecretAccessPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref MyDBSecretAccessPolicy
```
Could you please let me know if there is something that I am missing here?
In case you need more context from my setup, just let me know it.

Thanks in advance!

**Comment by iamhopaul123** [comment]
Actually I just realized the name of the addon file is `addons.parameters.yml` but it is actually an addons template instead of parameter file. Can you try to rename the file as maybe `policy.yml` or `addons.yml`?

**Comment by pvborromeo** [comment]
Sure, @iamhopaul123 let me try it out.

**Comment by jdimmerman** [comment]
@pvborromeo @iamhopaul123 I'm running into this but have a unrelated filanem (eg `blah-access.yml`). Any resolution?
