### ISSUE TITLE
Does Copilot support deploying multiple environments to the same AWS account?

### ISSUE THREAD

**Issue by lewijacn** [aws/copilot-cli#5138]
Background: 
In my repo I have initialized an app(migration-copilot), environment(dev, us-east-1), and services. I now want to deploy another environment(dev2, us-west-2) with the same services in another region (us-west-2) within the same AWS account.

Issue: 
When I try to initialize the environment I hit error:
```
copilot env init -a migration-copilot --name dev2 --region us-west-2

✘ get application migration-copilot configuration: couldn't find an application named migration-copilot in account 123456789123 and region us-west-2
```
However, upon trying to initialize the app with my AWS configured region changed to us-west-2 I hit another error:
```
copilot app init migration-copilot

If you want to create a new workspace reusing the existing application migration-copilot, please switch to the region where you created the application, and run `copilot app init`.
If you'd like to recreate the application and all of its resources, please switch to the region where you created the application, and run `copilot app delete`.
✘ application named "migration-copilot" already exists in another region
```

This leads me to think support for deploying multiple environments to the same account does not exist, but would be very happy to be corrected here?

**Comment by dannyrandall** [comment]
Hey @lewijacn! You definitely can deploy multiple environments in the same AWS account.

To do so, create a new profile in your `~/.aws/config` with the same credentials as the profile you created your app with. Then, for the new profile, change the `region` to `us-west-2`. It should look something like:
```
[profile default]
region = us-east-1
# some other fields

# add this profile
[profile dev2]
region = us-west-2
# the rest the same as "default"
```

Then, run `copilot env init` with the _profile you created your app with._ In my example, it's the "default" profile. Copilot will prompt you to pick a separate profile to use to create your new environment, and you should select the `dev2` profile. This will create a new environment in the new region!

**Comment by lewijacn** [comment]
Thanks for the info here

I think I have identified the issue I was hitting. In my scenario I was creating development environments on the fly with a command similar to below, while using temporary AWS credentials:
```
copilot env init -a $COPILOT_APP_NAME --name $COPILOT_DEPLOYMENT_STAGE --import-vpc-id $MIGRATION_VPC_ID --import-public-subnets $MIGRATION_PUBLIC_SUBNETS --import-private-subnets $MIGRATION_PRIVATE_SUBNETS --aws-access-key-id $AWS_ACCESS_KEY_ID --aws-secret-access-key $AWS_SECRET_ACCESS_KEY --aws-session-token $AWS_SESSION_TOKEN --region $AWS_DEFAULT_REGION
```

It seems that if the AWS_DEFAULT_REGION environment variable is set to a new region from the initial environment you created, it will cause an issue like the error from my initial post. I was originally using this environment variable for a CDK deployment. However if I clear the value of this variable (`export AWS_DEFAULT_REGION=`) and alter my command to use another variable i.e.:
```
--region $REGION
or explicitly
--region us-west-2
```
It deploys normally. The error message for this was a bit misleading but ultimately seems this variable is factored in with Copilot deployments

**Comment by Lou1415926** [comment]
@lewijacn Glad it worked out!

>  ultimately seems this variable is factored in with Copilot deployments

This is correct. Copilot first needs to look for your application. To do this, it asks `aws-sdk` to retrieve the "default" credential and region. Under the hood, when `aws-sdk` tries to figure out what your "default" region is, it reads `AWS_DEFAULT_REGION` - if this is not set, it falls back to the `[default]` profile in ` .aws/config`. In your case, you probably have set `AWS_DEFAULT_REGION` to `us-west-2` - which then led Copilot to look for `migration-copilot` in us-west-2.

**Comment by lewijacn** [comment]
Yes makes sense, closing this issue
