### ISSUE TITLE
cannot unmarshal !!str `See #5140` into []string

### ISSUE THREAD

**Issue by dannyrandall** [aws/copilot-cli#5140]
## Why am I seeing this error?

In v1.28, Copilot introduced our first non ECS-based workload type, Static Site. As part of that, we added new logic to support workloads that didn't need an ECR repo.

After release, we discovered a bug that occurred in the following scenario:
1. Upgrade the Application Stack Set by creating a new service or upgrading an application
  ```
  ➜ copilot@v1.28.0 svc init
  # or
  ➜ copilot@v1.28.0 app upgrade
  ```
2. Downgrade the Application Stack Set by creating a new service with an older version of Copilot
  ```
  # any Copilot version <= v1.27.0
  ➜ copilot@v1.27.0 svc init
  ```

If step 1 was done with >= v1.29.1, then step 2 should error out with a link to this issue.

If step 1 was done with v1.28.0 or v1.29.0, any services in the Application will have their ECR repos removed from the Application Stack Set. While this **does not result in any service downtime**, it makes it impossible to deploy a _new_ version of a service without [a workaround](#v1.28.0,-v1.29.0). If you have images in your ECR repo, the repo should still exist in ECR, just not in the CloudFormation Stack Set.

## What is Copilot doing to mitigate this issue?
While we can't patch all of older versions of Copilot that are out there and force everyone to upgrade, we introduced a new version downgrade checker feature to prevent this class (upgrade followed by downgrade) of bug in the future. Stack downgrades will now error out, and we added a new flag `--allow-downgrade` to explicitly allow a downgrade to all `init`, `deploy` and `package` commands.

Additionally, for Application Stack Sets deployed by Copilot >= v1.29.1, we added a line to the template that causes Copilot <= v1.27 to error on operations that modify the Application Stack Set with a link to this issue.

### >= v1.29.1
If you got this error message:
```
cannot unmarshal !!str `See #5140` into []string
```
This means that someone has updated your Application Stack Set with Copilot >= v1.29.1. Upgrade your version of Copilot to the latest version, and run your command again.

### v1.28.0, v1.29.0
If you are seeing one of these errors:
```
Container.image repository should not be null or empty
```
```
image is not supported by App Runner: @sha256:<hash>
```
```
failed to normalize image reference ":<hash>". Launch a new task to retry.
```

This likely means your Application Stack Set was deployed with Copilot v1.28.0 or v1.29.0 and subsequently downgraded. The error is a result of your ECR repos being removed from the Application Stack Set. To resolve this issue, first upgrade your version of Copilot to the latest version. Then, do the following **_for each service in your application_**.
1. Delete the service from SSM Parameter Store
  a. Open the System Manager console in the same region/account the `<APP NAME>-infrastructure-roles` CloudFormation stack is deployed in.
  b. Search for the parameter named `/copilot/applications/<APP NAME>/components/<SVC NAME>`
  c. Remember the "type" field from the parameter value
  d. Delete the parameter
2. Check if the ECR repo exists by opening the ECR console, and searching for the repo `<APP NAME>/<SVC NAME>`. If it does, do the following to backup the images in it:
  a. Install [`skopeo`](https://github.com/containers/skopeo).
  b. Click on the "View push commands" button in the ECR repo console.
  c. Login to ECR by running the first step (`aws ecr get-login-password ...`) on your machine, but change the word "`docker`" to "`skopeo`".
  d. Copy the ECR repo URL from the 4th step - the bit after "`docker push`". It should be in the format `<ACCOUNT ID>.dkr.ecr.<REGION>.amazonaws.com/<APP NAME>/<SVC NAME>`. Note that you should not copy the `:latest` tag.
  e. Create a new folder to store all of the images in: `mkdir <SVC NAME>`
  f. Download all of the image digests to your machine from the ECR repo:
    ```
    aws ecr list-images --repository-name <APP NAME>/<SVC NAME> --output json --max-results 1000 --no-cli-pager | jq -r '.imageIds[].imageDigest' | xargs -P1 -n1 -I{} skopeo copy --all --preserve-digests docker://<ECR REPO URL>@{} dir:<SVC NAME>/{}
    ```
   g. Verify the directories created in the `<SVC NAME>` directory match all of the image digests in your ECR repo.
   h. Delete the ECR Repo using the console.
3. Recreate the service. This will add the service back to SSM Parameter Store and recreate the ECR repo.
```
➜ copilot svc init --name <svc name> --svc-type <type from SSM parameter>
```
4. If you had to do step two, do the following to push all of the saved images to the new ECR repo:
  a. Run the command:
    ```
    ls -1 <SVC NAME> | xargs -P1 -n1 -I{} skopeo copy --all --preserve-digests dir:<SVC NAME>/{} docker://<ECR REPO URL>
    ```
    b. Verify the new ECR Repo has the correct set of image digests.

**Comment by alexfdz** [comment]
We were in the same situation and we needed a few more steps to get it working.

1. Upgrade your copilot-cli to at least the 1.30.1. 
2. Remove component parameters in the AWS Systems Manager Parameter store for every job or service. They follow the pattern `/copilot/applications/$APP_NAME/components/$NAME`.
3. Remove the ECR repositories for every component. They follow the pattern `$APP_NAME/$NAME`.
4. Run a `copilot app upgrade -n $APP_NAME` 
5. In sequence for every service or job run a copilot init.
6. For every service or job run a copilot deploy.

**Comment by eduardo-tamaki** [comment]
Hi all, I did all the steps for 1 service and still getting the error:

`Resource handler returned message: "Invalid request provided: Create T
    askDefinition: Container.image repository should not be null or empty.
     (Service: AmazonECS; Status Code: 400; Error Code: ClientException; R
    equest ID: 4bf563a9-d740-4751-a3d0-fe5f3ad115d1; Proxy: null)" (Reques
    tToken: 5015d191-35dd-0ef3-c72d-52bc9150307c, HandlerErrorCode: Invali
    dRequest)`

I am doing something wrong? should I do for all services?

Bests!

**Comment by alexfdz** [comment]
@eduardo-tamaki you need to do it for all your components (services and jobs).

To be sure you are fixing the issue you could check:

- In Cloudformation > StackSets find the stackset $APP-ifrastructure and its template
- Check that for each service/job you fixed you find:
  - An entry in `Workloads`
  - A `AWS::ECR::Repository` in `Resources`
  - An output that exposes the ECR repository ARN 
- In Cloudformation > Stacks
- Check that for each service/job you fixed you can find in Parameters > ContainerImage a valid  ECR image path (not just the label)

**Comment by eduardo-tamaki** [comment]
Hi, @alexfdz I'm still getting the same message, even doing all the steps for all services and jobs:

    Resource handler returned message: "Invalid request provided: Create T                                                           
    askDefinition: Container.image repository should not be null or empty.                                                           
     (Service: AmazonECS; Status Code: 400; Error Code: ClientException; R                                                           
    equest ID: 02618f79-525d-4d34-a378-...; Proxy: null)" (Reques                                                           
    tToken: 0f1a05f3-52ca-8e96-b025-..., HandlerErrorCode: Invali                                                           
    dRequest)     

And yep the parameters are still only the tag

like this:
`ContainerImage | @sha256:498f0f41e3db9ba45...`

The app and my cli are 1.30.1.

What am I doing wrong?

Thank you very much!

**Comment by iamhopaul123** [comment]
Hello @eduardo-tamaki. Sorry for the inconvenience. Did you remove all the existing ECR repos and run `app upgrade` and rerun `svc/job init` to recover the ECR repos?

**Comment by eduardo-tamaki** [comment]
Hey there! Just wanted to let you know that I encountered  the solution. 

The issue was that I ran the 'copilot app upgrade' command, before I knew It was a huge problem of versions and after that it said the app was upgraded.

However, upon completing all the necessary steps, the application failed to function properly, and the 'copilot app upgrade' command continued to display the application version as 1.30.1. Subsequently, upon careful examination and multiple attempts, I discovered that there were two failed steps within the Operations tab of the infrastructure StackSet.

In order to rectify the situation, I proceeded to re-run the steps and subsequently initiated a StackSet update without any modifications, effectively reattempting the previously failed steps. As a result of these actions, the issue has been successfully resolved.


Thanks @alexfdz and @iamhopaul123 for the assistance.

**Comment by eduardo-tamaki** [comment]
Hi, me again!

Is there a way to deny any cli with a version below of the app version?

The team was a little worried on what had happened.

Thanks

**Comment by iamhopaul123** [comment]
Hello @eduardo-tamaki. We disabled template version downgrade after v1.29.1 to prevent this accidental version downgrade from happening again. And we are thinking seriously to remove the problematic version `v1.27` and `v1.28` from our binary list.

**Comment by ivandcv** [comment]
This solved my issue thanks! But fair WARNING the skoepo command does not restore the image tag. So if you have jobs that depend on the image tag like we do. You will have to find a workaround. In our case we just redeployed the last working build to create a new image with the tag.
