### ISSUE TITLE
Copilot

### ISSUE THREAD

**Issue by mtrackeros** [aws/copilot-cli#5143]
https://github.com/github/docs/blob/main/content/copilot/configuring-github-copilot/configuring-github-copilot-settings-on-githubcom.md

**Comment by dannyrandall** [comment]
Hi @mtrackeros - I think this issue is meant for [Github Copilot](https://github.com/features/copilot), not [AWS Copilot](https://aws.github.io/copilot-cli/docs/overview/)!
