### ISSUE TITLE
Unable to Connect via EXEC: ”Plugin with name InteractiveCommands not found. Step name: InteractiveCommands”

### ISSUE THREAD

**Issue by oiekjr** [aws/copilot-cli#5160]
## Problem

The svc exec command is suddenly unavailable.

> copilot svc exec -c bash -n xxx-api -e dev
> Execute `bash` in container xxx-api in task eb545f***.
> 
> Starting session with SessionId: ecs-execute-command-0d84350***
> 
> SessionId: ecs-execute-command-0d84350*** : Plugin with name InteractiveCommands not found. Step name: InteractiveCommands

(Note: The asterisks are actually alphanumeric characters.)

I'm certain that the service manifest is set to `exec: true`.

Does anyone have any information on this?

Even after deleting and recreating the service, the error was not resolved.

## Environments

- `aws --version`
  - `aws-cli/2.13.7 Python/3.11.4 Darwin/22.5.0 source/arm64 prompt/off`
- `session-manager-plugin --version`
  - `1.2.497.0`
- `copilot version`
  - `v1.29.1`

**Comment by huanjani** [comment]
Hello, @oiekjr.

This appears to be related to https://github.com/aws/session-manager-plugin/issues/64#issuecomment-1662335697 and https://github.com/aws/copilot-cli/issues/4627-- a lag between release and GH release. I just tested it and it appears to be working now. Let us know if you're still getting an error!

**Comment by huanjani** [comment]
Closing for now, but feel free to reopen if you're still unable to run `exec`.
