### ISSUE TITLE
Best practice for service redeployment

### ISSUE THREAD

**Issue by vicpara** [aws/copilot-cli#5161]
I have multiple environments that run a backend service.
Let's say there's a bug/ misconfiguration/ error that prevents the service from reaching a healthy state after deployment. 

Let's say a fix is ready. The deployed service is still struggling to reach a healthy state through multiple restarts orchestrated by fargate. What's the fastest way to redeploy a fix?

Currently our process is to delete the entire service (~400s of deleting a lot of resources). Then redeploy the service for another 300s.
This seems a wasteful process, an overkill and an incredibly time consuming. Is there a better/ faster leaner way to just :
1. update the docker image
2. change/update/overwrite the definition of the stack 
3. restart the new service from the latest docker image ?

Also, i'm not sure what 'copilot svc deploy --force' is for since it doesn't force anything at deployment time. Once a service failed, deleting the service is the fastest way to re-deploy the service. Alternatively we can wait for it to finish trying, service auto-delete and then try again.

**Comment by huanjani** [comment]
Hi, @vicpara! Apologies for the delay in response.

Exciting news: we have a ctrl-c feature coming out in the next release, tentatively scheduled for a couple weeks from now! After that's released, you'll be able to cancel the deployment much more easily.

In the meantime, I'd love to get more clarity on your experience. 

How are you currently deleting the service?-- through the CloudFormation console? Because you shouldn't be able to delete via Copilot while Circuit Breaker is still trying to deploy ten times; otherwise, you'd be able to redeploy via Copilot instead!

Is the failing deployment the initial deployment? If not, when you cancel the deployment through the CloudFormation console, it should roll back and you can redeploy without deleting.

**Comment by vicpara** [comment]
Good news indeed. However it all depends what happens after Ctrl + C. Do you start an automatic roll back? If there's a mistake in the service config + code, do I have to wait 10 mins now ?

Yes, i delete the service through CloudFormation UI. Indeed, the copilot cli is useless after the deployment was initiated. Exactly. One can only wait. 

If we delete the service then the immediate next deployment is an initial deployment, right? Then we do a lot of initial deployment. From our perspective, after a service failed deploying, then we need to remediate the situation.

Here's our context. We are currently migrating to AWS from on-prem and GCP. 

We need to get so many things right for the entire app to run correctly. So as we make changes iteratively to the apps. As we get some parts right we move on to integrating additional features (CDN, EFS, secrets, configs) and migrate more services. As you can imagine things go wrong all the time. As we understand what goes wrong we want to fix it and move on.

An example:
1. Start a service from your docker image. The service starts but then it fails. The required env vars are missing.
2. Great, np, add the env vars. Error, updated the copilot manifest but the env file doesn't get picked up because mistakes in the manifest file.
3. Redeploy with the updated manifest.
4. Now the secrets are missing. Try to get these rights now in the right environment.
5. Failure, incorrect mounting of secrets in the specific environment. Fix it + redeploy
(18 failed deployment attempts so far)
6. EFS is not mounting + fix attempt + redeploy
7. EFS is still not mounting / private subnet?/public subnet? / bursting?/ + .... fix attempts + redeploy... fix attempts..

I guess you can quickly realise that up until point 7 a couple of days passed by.

I think there are two different worlds. The paradise, after the system has been working nominally for 1 year, everything works great and a careless mistake brings a service down. The orchestrator job is to keep the system operational by rolling back to last known working state. The rollback, even though slow, eventually succeeds.

And then is the hell of getting there through initial app migrations, configurations, scripts and what not. We are here.
Finding the correct configuration, process, fix, script in the AWS documentation is matched by on par waiting time of executing the command and seeing it's effects.

Some bad ideas as possible fixes:

* Reduce the number of retries until a service is declared defunct and sent to oblivion (2-3) ?
* After 10 failures, just let the failed service be there, don't delete it, allow devs to check the logs, fix the trouble through a new revision and start again.

* During the deployment, allow all users with the right permissions to force overwrite the service stack definition. Currently revision X is being deployed and the orchestrator does it's best to make it healthy even though it's faulty by design. Great. Just let me create another revision X+1 and roll that out asap. Or perhaps allow me to mark a revision as failed forever and untouchable. Halt all self-healing systems. Don't delete the service + ALB + EFS + ... yet. Leave it as is in the failed state. However, allow further ops/changes through the copilot cli to replace the service. Also, this keeps the logs.

* Yes, the service will pass through a temporary period of failures. So what? The state is broken anyways. Basically I want the ability to skip waiting for all the self-healing, recovery mechanisms to kick in. Redeploy and move on.

* Make '--no-rollback' and '--force' actually work, regardless of the service state. Today, when using '--no-rollback' and there's a failure in the deployment, the subsequent deployments choke. Using '--no-rollback' it's whimsy. You can't just use '--no-rollback' with every deployment, accept the perils and move on. Once you hit an error during the deployment it's game over. It will get the system crying and circuit breakers will come upon you. Now go figure what happened. Or just be a barbarian, delete the service and start again. It works even without a phd.

**Comment by huanjani** [comment]
> Do you start an automatic roll back? 

Yes! You can get a sneak peek here: https://github.com/aws/copilot-cli/pull/5123, and there will be more details in the release notes. `ctrl+c` will start a rollback of the deployment, and a second `ctrl+c` will cause the rollback to occur in the background.

One thing you could try is setting your initial desired count to 0. Then redeploy with your actual desired count. That way a failed deployment will roll back to the initial deployment, skipping the delete step and shortening the subsequent deployments.

**Comment by KollaAdithya** [comment]
Hello @vicpara !
`Ctrl-C` feature is released in [v1.30](https://github.com/aws/copilot-cli/releases/tag/v1.30.0) 🎉 . You can now cancel your stack update to rollback to previous configuration.
