### ISSUE TITLE
support imported certificates for the static site

### ISSUE THREAD

**Issue by KollaAdithya** [aws/copilot-cli#5164]
Discussion from gitter: https://app.gitter.im/#/room/#aws_copilot-cli:gitter.im/$CiugVIlvsMFmkL_CSuqPBlvGLRvpiQWsjEdtRur44EQ

Currently Copilot does not support imported certificates for `Static site` service type. Ask here is Similarly like other services in copilot should support imported certificates.

**Comment by cool-raj** [comment]
I would also love to enhance this feature with possibility to provide alternate domain names for the cloudfront distribution.

**Comment by Lou1415926** [comment]
You can now import certificates for your static site in AWS Copilot v1.31.0!For more, see the [release note](https://github.com/aws/copilot-cli/releases/tag/v1.31.0 ) and the [blog post](https://aws.github.io/copilot-cli/blogs/release-v131/) 🎉🚀 🚀
