### ISSUE TITLE
Static Site workflow for npm build

### ISSUE THREAD

**Issue by cworkschris** [aws/copilot-cli#5165]
Hi, I'm wondering if it is possible to deploy a javascript frontend via the Static Site mechanism without checking in the built assets.

In [https://aws.github.io/copilot-cli/docs/concepts/pipelines/ ](https://aws.github.io/copilot-cli/docs/concepts/pipelines/)
Step 3, would the buildspec require the use of other services like CodeArtifact?  Can you give me a quick hello world example of how the npm toolset would be introduced and then executed against the source?

**Comment by huanjani** [comment]
Hi, @cworkschris!

Could you clarify what you mean by "checking in the built assets"-- do you mean uploading the files to S3? 

This is what the default pipeline buildspec looks like: https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/cicd/buildspec.yml. Does that help?

Thanks!

**Comment by cworkschris** [comment]
Hi Janice!

I just mean that the copilot pipeline would be executing in the context of files that were in git (bitbucket in my case) right?  (e.g. for it to work in the simplest way I would npm build the assets and git push them, then the copilot static site deployment would put them in s3 and cause them to be served from aws cloud - but I don't want to version control the build assets)

Are you saying rather than edit the manifest I need to alter the buildspec to include steps for an npm build? (which would need to include setup in phases: install: )
Sorry if that's too obvious I haven't had to go to that lower level yet!

**Comment by huanjani** [comment]
Ohhh, I see what you mean-- you don't want to check the `manifest.yml` and `buildspec.yml` files into your repo? You do need to check those in if you want to use Copilot pipelines, but you by no means have to use a Copilot pipeline-- you can absolutely just create a Static Site with Copilot without a pipeline! 

(Sorry if I'm totally misunderstanding.)

**Comment by huanjani** [comment]
Or is it the pipeline build assets that are uploaded to S3 that you want to avoid?

**Comment by huanjani** [comment]
@cworkschris-- I believe you're looking for something similar to this: #5026. Please thumbs-up this issue, and add your use case if you'd like. Thanks!

**Comment by cworkschris** [comment]
> @cworkschris-- I believe you're looking for something similar to this: #5026. Please thumbs-up this issue, and add your use case if you'd like. Thanks!

Yes, thank you!  Right now I'm doing an npm build and putting it on s3 via boto3, but it seems like that workflow would be nicer.
