### ISSUE TITLE
copilot seems to be ignoring `platform: linux/x86_64`

### ISSUE THREAD

**Issue by lgarvey** [aws/copilot-cli#5181]
copilot version: v1.29.1

I'm trying to deploy a service from a Dockerfile on an m1 mac, but the container fails to run in fargate  with an "exec format error" indicating its a arm/x86 platform issue.

When I do a `copilot svc deploy` it shows the docker build command without the appropriate `--platform linux/amd64` flag:

```
Building your container image "web": docker build -t [...].dkr.ecr.eu-west-2.amazonaws.com/my-test/web:latest --label com.aws.copilot.image.builder=copilot-cli --label com.aws.copilot.image.container.name=web --label com.aws.copilot.image.version=v1.29.1 /Users/x/Desktop/copilot-test -f /Users/x/Desktop/copilot-test/Dockerfile
```

With `docker image inspect` I can see the image has the wrong architecture. 
```
        "Architecture": "arm64",
```

The manifest.yml file has the following:
```
image:
  build: ./Dockerfile 
  platform: linux/x86_64
```

Am I missing something or is this a bug?   We have a few services that are deployed from Dockerfiles and this is the first time I've seen this issue.

**Comment by huanjani** [comment]
Hi, @lgarvey!

`platform` is a top-level field, so it's currently not being read in its spot within `image`.

```
image:
  build: ./Dockerfile
platform: linux/x86_64
```

https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#platform

Copilot should automatically add this to your manifest when it detects an M1 machine.

Hope that helps!

**Comment by lgarvey** [comment]
Hi @huanjani,

Ah my mistake.  I see this works exactly as you describe!

Thanks for your help!

Cheers,
lg
