### ISSUE TITLE
Unable to delete copilot created VPC

### ISSUE THREAD

**Issue by geoffw8** [aws/copilot-cli#5189]
I manually deleted some stacks that copilot created in a wild act of "I need to start again" after not being able to get our app deployed properly.

I'm now in a position where I can't deploy an env because I have hit the 5 limit, and I simply can't delete the ones that are there. I can't delete the VPC because it has resources, I can't delete the resources because of "permission denied" errors. I am the admin.

Is there a way to "reconnect" copilot to the vpcs? Delete them that way? Or is there another method I should be using?

Thanks in advance all

**Comment by KollaAdithya** [comment]
Hey @geoffw8 !
So sorry that you are facing the issue.
I have few questions that will help me to fix the issue.
1. Does the environments have some active services deployed to it.
2. Also can you paste the errors that you getting when deleting the stack manually? Can you go to `AWS console --> Cloudformation --> env stack--> stack events`.

**Comment by geoffw8** [comment]
Hey @KollaAdithya 

No problem at all, thank you for such a brilliant tool.

> Does the environments have some active services deployed to it.

It does not, no.

> Also can you paste the errors that you getting when deleting the stack manually? Can you go to AWS console --> Cloudformation --> env stack--> stack events.

The stack is actually gone (that list is empty) - its the VPC's that have stuck around.

To get moving again, I simply picked another region. I managed to get our app working 🎉 but realised I needed a domain, so I followed the instructions to `delete` the env via copilot, but am getting another dependency error:

<img width="1413" alt="Screenshot 2023-08-18 at 12 47 33" src="https://github.com/aws/copilot-cli/assets/97499/871f07a3-e30d-4841-8a05-86f82c0fc075">

Unfortunately this means I now can't bring the app back up.

**Comment by KollaAdithya** [comment]
Hey @geoffw8 !

can you go the `AWS console->VPC->copilot-tembo-backend`. Can you try to delete the VPC manually. does this work?
This is an article that step by step instruction on deleting the VPC.
https://repost.aws/knowledge-center/troubleshoot-dependency-error-delete-vpc

**Comment by geoffw8** [comment]
Hi @KollaAdithya

Unfortunately it does not. I am stuck in a dependency loop. AWS Support have given me a set of instructions which still do not quite work and so I'm waiting to hear back from them.

Are other people reporting this issue? I don't have much of a complicated setup and I am unable to delete an application using the delete command. Has something perhaps changed on the API side?

Thanks for all your help
Geoff

**Comment by dannyrandall** [comment]
Hey @geoffw8 - you're saying you're still getting the "has dependencies and cannot be deleted" error? If so, could you share (by running the script in step 1 of the article linked by @KollaAdithya) which resources are still in your VPC?
