### ISSUE TITLE
Enable ALB access logs on CDK override

### ISSUE THREAD

**Issue by Kqirk** [aws/copilot-cli#5210]
Hi Copilot Team,

I'm trying to enable the access logs for the public load balancer via CDK overrides in typescript and have been unsuccessful.
I would greatly appreciate some guidance for enabling this.

I've tried two methods 
```
const loadBalancerAttributeProperty: cdk.aws_elasticloadbalancingv2.CfnLoadBalancer.LoadBalancerAttributeProperty = {
            key: "access_logs.s3.enabled",
            value: "true"
 }; 
const bucket_name: cdk.aws_elasticloadbalancingv2.CfnLoadBalancer.LoadBalancerAttributeProperty = {
            key: "access_logs.s3.bucket",
            value: "s3bucketname/alb"
};
alb.addOverride("Properties.LoadBalancerAttributes", [
            loadBalancerAttributeProperty,
            bucket_name
    ]
);
```

and 

```
alb.addOverride("Properties.LoadBalancerAttributes", [
            {
                key: "access_logs.s3.enabled",
                value: "true"
            },
            {
                key: "access_logs.s3.bucket",
                value: "s3bucketname/alb"
            }
    ]
 );
```
However, I'm getting an "Encountered unsupported property value" error when deploying the ALB.
I've also tried detecting the drift by enabling this attribute via the console but it was not detected. 
I'm able to override the load balancer name, so the alb reference is correct for the example given above.

Thank you for your time.

**Comment by dannyrandall** [comment]
Hey @Kqirk! Out of curiosity, does [`http.public.access_logs`](https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public-access-logs) in the manifest work for you? You can use that field/subfields to either have Copilot create a new bucket for the logs or to import an existing bucket. If not, I'm happy to dig more into your CDK override but figured I should check!

**Comment by Kqirk** [comment]
Hi @dannyrandall, that totally works🤣 , thank you so much, I tried to over-engineer a solution I guess
However, I am curious why the CDK override didn't work as I referenced the docs and another attribute "subnet_mappings" for my typescript code above, for my own knowledge as I went quite deep into the rabbit hole for this.
Once again, thank you so much for your guidance!

**Comment by dannyrandall** [comment]
My guess is the error is because you had the bucket name _and_ path in the `access_logs.s3.bucket` attribute. Based on [this](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html), the correct format is to have `access_logs.s3.bucket: "s3bucketname"` and `access_logs.s3.prefix: "alb"`.

**Comment by Kqirk** [comment]
thank you so much!
