### ISSUE TITLE
Scheduled copilot job fails to run after deploy

### ISSUE THREAD

**Issue by iamsabin** [aws/copilot-cli#5218]
Hi,

I've been running into an issue with copilot starting the past couple of weeks.

Scheduled copilot job fails to run after successful deployment. I get the following error in CloudWatch as "TaskFailed":
`"StoppedReason": "InternalError: failed to create container model: failed to normalise image reference \":9c84b09\". Launch a new task to retry.",`  
[ecstaskfailed.log](https://github.com/aws/copilot-cli/files/12425021/ecstaskfailed.log)

The issue started when I ran `copilot init` for a new job using copilot v1.1.0 on 4th Aug 2023. There are 50+ jobs in the namespace that were initialised and deployed using copilot v1.28.0 and lower versions as early as March 2021. All of them are running as scheduled. But, whenever I try to make a code change and deploy any old jobs that were previously initialised (when I created a new job using v1.1.0), it fails with the above error.

Steps I have tried, which didn't fix the problem (old job failing to run with change)
1. Upgrading the copilot version to 1.29.1 to deploy. I also tried with `--allow-downgrade`
2. Add the image location in the manifest file. like `location: xxxx.dkr.ecr.xxx.amazonaws.com/xxx:latest`
3. Followed instructions from 2 issues. [https://github.com/aws/copilot-cli/issues/5032](https://github.com/aws/copilot-cli/issues/5032), [https://github.com/aws/copilot-cli/issues/4963](https://github.com/aws/copilot-cli/issues/4963)
4. Upgrade the app using `copilot app --upgrade`

The only solution that works is"
1. Delete the copilot job
2. Delete the image from ECR
3. Initialise the copilot job
4. Deploy the job
5. It runs at scheduled time.

We've over 50 jobs that are currently running, so it can be really time-consuming to delete them all and recreate them. Can you please go over this? This is a sample task definition it deploys: 
[taskdefinition.log](https://github.com/aws/copilot-cli/files/12425039/taskdefinition.log)

**Comment by dannyrandall** [comment]
Hey @iamsabin! So sorry for the issue.😔  We made a change in v1.28.0 that resulted in all service/job ECR Repos being removed from the Application if someone later created a new workload or updated the Application with an _older_ version of Copilot.

Have you looked at https://github.com/aws/copilot-cli/issues/5140? It should have a workaround for you, but unfortunately you do have to follow the steps for each job.😔 Again - so sorry for the headache!

**Comment by iamsabin** [comment]
Thanks @dannyrandall for your response. We slowly moved to the new copilot version following the steps.
