### ISSUE TITLE
Handle images built by a remote builder

### ISSUE THREAD

**Issue by ytanay** [aws/copilot-cli#5236]
When I configure a remote BuildKit builder (e.g. [Depot](https://depot.dev)), I see the image is successfully built, but cannot be pushed to ECR because it isn't loaded into the local daemon.

Here's an example:
```
$ copilot job deploy -e test -n example
Login Succeeded
Building your container image "example": docker build -t 000000000000.dkr.ecr.us-east-1.amazonaws.com/org/example:latest --platform linux/arm64 --build-arg RUST_BUILD_PROFILE=release --label com.aws.copilot.image.builder=copilot-cli --label com.aws.copilot.image.container.name=example --label com.aws.copilot.image.version=v1.29.1 <DIR>  
     What's Next?
     View summary of image vulnerabilities and recommendations → docker scout quickview
     
upload deploy resources for job example: build and push the image "example": push to repo <repo>: docker push 000000000000.dkr.ecr.us-east-1.amazonaws.com/org/example:latest: exit status 1                                                                                       
```

I believe the best course of action would be to push the image directly by adding `--push` to the `docker build` args, or alternatively to add `--load` (but that would introduce unnecessary round trip between the remote builder and the local machine), but of course there might be compatibility requirements with non-BuildKit environments I'm not familiar with :)

Thanks!

**Comment by bvtujo** [comment]
Thanks for pointing out this gap in use cases! We don't currently support passing `--load` or `--push` to a remote builder, but as a workaround could you perhaps build outside of copilot and use the `image.location` field for your services?

```
docker build -t 000000000000.dkr.ecr.us-east-1.amazonaws.com/org/example:latest ...
docker push 000000000000.dkr.ecr.us-east-1.amazonaws.com/org/example:latest
```

then in your svc manifest:
```
image:
  location: 000000000000.dkr.ecr.us-east-1.amazonaws.com/org/example:latest
```
You can deploy this even if there are no immediate infra changes and the tag is the same by running 
```
copilot svc deploy --force
```
to force a redeployment of the service.

**Comment by ytanay** [comment]
Cool, thanks for the tip!

Wouldn't the resulting task configuration refer to the "latest" tag instead a concrete hash though? I worry the service might unintentionally update to a different version when the image is updated but not yet deployed. Or does Copilot resolve this when creating the task definition?

**Comment by bvtujo** [comment]
If you're building in a git repo context, Copilot will automatically tag your images with the SHA they're generated from. You could also specify a custom image tag using `copilot job deploy --tag 1234fde`, for example. 

You don't necessarily always have to use `latest`, I was just lazy in my example!

**Comment by ytanay** [comment]
We ended up setting the image to `location: 000000000000.dkr.ecr.us-east-1.amazonaws.com/org/example:${GITHUB_SHA}`, which works nicely with the rest of our setup. Thanks!
