### ISSUE TITLE
Support for Credential provisioned by AWS IAM Identity Center 

### ISSUE THREAD

**Issue by kangere** [aws/copilot-cli#5257]
Does copilot support credentials created using SSO token provider configuration as described in the link below?
https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html 

I have tried to create temporary credentials as described in the link above but copilot seems to defer to my static credentials which are now deactivated while the aws cli is able to use the temporary credentials. Is this a matter of the static credentials taking precedence over the temporary credentials created through sso token configuration ? or does copilot not support sso token provider configuration?

Edit: According to this [docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html) The IAM Identity Center credentials which are stored in the `config` file should take precedence over the static credentials stored in the `credentials` file. So would it be a correct assumption to say that copilot does not support credentials provisioned by the IAM Identity Center? If so is there a timeline to support this?

**Comment by bvtujo** [comment]
I've successfully used sso with Copilot in the past with a profile. If there's a way you can move the static creds to another profile, and make the sso profile your default, then that should work. 

Alternatively, you can set the AWS_PROFILE env var to your sso profile, either exported to persist it through your terminal session, or at the beginning of each command:
```sh
$ export AWS_PROFILE=my-sso-profile

// or per-command
$ AWS_PROFILE=my-sso-profile copilot deploy
```

**Comment by bvtujo** [comment]
I think the problem is that the SDK doesn't know which credentials to resolve when you have SSO in the config file, but static creds in ~/.aws/credentials. 

For example, if you want sso to be the default, I'd set up AWS config like this:
```
[default]
sso_start_url = https://d-xxxxxxxxxxx.awsapps.com/start
sso_region = eu-central-1
sso_account_id = xxxxxxxxxxxx
sso_role_name = YourRoleName
region = us-west-2
output = json

[profile static_creds]
region = us-west-2
output = json
```

Then in `~/.aws/credentials`:
```
[default]

[static_creds]
aws_access_key_id = XXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by kangere** [comment]
@bvtujo  Thanks that worked for me. 

The AWS CLI docs [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html) mention that sso should take precedence over static credentials so is this a bug in the AWS SDK?

**Comment by bvtujo** [comment]
In the credential provider chain, that's true. However, a big caveat with the precedence list is that it isn't necessarily possible to specify any two credential sources at the same time. 

On that list, providers 3 through 8 are all ways of authenticating with the `config` and `credentials` files. You can only specify one of those per profile; the SDK doesn't know how to resolve a profile with, for example, `role_arn` in the config file and static credentials in the `credentials` file.
