### ISSUE TITLE
UX: copilot app delete defaults to yes

### ISSUE THREAD

**Issue by acodeninja** [aws/copilot-cli#5258]
The copilot command `copilot app delete` asks for confirmation to delete the application. This defaults to Yes, whereas `copilot env delete` and other destructive commands default to no. This is important as an accidental double tap of the enter key will act as confirmation.

I would expect this confirmation to default to no, as many other destructive commands do.

**Comment by bvtujo** [comment]
This is a great idea, and I don't actually know why we didn't do this to begin with. Thanks for pointing it out!

**Comment by bvtujo** [comment]
This fix is now released in v1.30.1: https://github.com/aws/copilot-cli/releases/tag/v1.30.1

**Comment by yusufsheiqh** [comment]
@bvtujo Thank you kindly! 😄

**Comment by acodeninja** [comment]
Thanks for fixing this so quickly @bvtujo
