### ISSUE TITLE
Overview diagram of Backend Services is misleading

### ISSUE THREAD

**Issue by ghost** [aws/copilot-cli#5283]
# Problem
Take a look at the diagrams of the Load balanced services and the backend services in the [Services](https://aws.github.io/copilot-cli/docs/concepts/services/) article:
![86045951-39762880-ba01-11ea-9a47-fc9278600154](https://github.com/aws/copilot-cli/assets/104418584/53ec9406-59a8-4639-aa89-137a1b09c483)
![86046929-e8673400-ba02-11ea-8676-addd6042e517](https://github.com/aws/copilot-cli/assets/104418584/b3cf9da8-1403-414e-bc5e-46c991e413ac)

Based on the diagram one's assumption can be, that if they need an ALB, they have to use Load balanced web services. This is however not the case, backend services also do support ALBs (internal ones) according to the [documentation](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#http).

The description of the Backend services also makes no mention of ALBs:

> If you want a service that can't be accessed externally, but only from other services within your application, you can create a Backend Service. Copilot will provision an ECS Service running on AWS Fargate, but won't set up any internet-facing endpoints. To learn about creating Backend Services with internal load balancers, go [here](https://aws.github.io/copilot-cli/docs/developing/internal-albs/).

# Proposed solution
Add an internal ALB to the diagram of the Backend services. Additionally, add some notes about the optional internal ALB in the [Services](https://aws.github.io/copilot-cli/docs/concepts/services/) article.

**Comment by ghost** [comment]
Note: the name _Load balanced web services_ might also be a misleading choice, as the backend services can also be load balanced...

**Comment by iamhopaul123** [comment]
Hello @bencehornak-gls. Those are very good finding. I agree the naming for "Load Balanced Web Service" and "Backend Service" might be confusing because they share so many similarities and the key difference right now is actually if it is a "public" service or "private" service.

However, for the diagram we try to outline the most common use cases that we expect our users to have, and the default setting we have for our users. For "Load Balanced Web Service" we'll have an public ALB setup for them and put ECS tasks in public subnets, whereas for "Backend Service" we'll have no ALB setup by default for them and put ECS tasks in private subnets.

> Additionally, add some notes about the optional internal ALB in the [Services](https://aws.github.io/copilot-cli/docs/concepts/services/) article.

I think we do mention optional internal ALB in our description as
> To learn about creating Backend Services with internal load balancers, go [here](https://aws.github.io/copilot-cli/docs/developing/internal-albs/).

**Comment by ghost** [comment]
Hi @iamhopaul123,

> I agree the naming for "Load Balanced Web Service" and "Backend Service" might be confusing because they share so many similarities and the key difference right now is actually if it is a "public" service or "private" service.

Very nicely put. I think naming, where this duality comes into foreground (e.g. 'Public container service'/'Private container service') would be more favorable, because yes, the main distinction is the accessibility through the public internet.

> I think we do mention optional internal ALB in our description as

You are right, I overlooked this, never mind.

So since you intentionally left out the internal ALB from the diagram, I'm closing this ticket. I'll open one dedicated to the naming, because that might be an interesting topic.

Thanks for the quick feedback!
