### ISSUE TITLE
Installation via homebrew is broken

### ISSUE THREAD

**Issue by huguesmp** [aws/copilot-cli#5357]
SHA256 values need to be updated for homebrew, I am getting this error on both Linux Mint and MacOS:

![image](https://github.com/aws/copilot-cli/assets/71036729/f75ce8b6-90a0-4a04-8863-244eea32cd61)

**Comment by johncblandii** [comment]
I'm definitely getting this as well.

**Comment by iamhopaul123** [comment]
Hello @huguesmp and @johncblandii. I am so sorry about that. Just merged a [homebrew PR](https://github.com/aws/homebrew-tap/pull/519) to fix this. Can you remove the brew cache download file for Copilot, and then do `brew update` before reinstalling?

**Comment by huguesmp** [comment]
Hi @iamhopaul123, thank you for the timely response!

I just tested on both my machines and everything is working now, closing the issue.

**Comment by johncblandii** [comment]
Yup...worked.

**Comment by johncblandii** [comment]
thx @iamhopaul123
