### ISSUE TITLE
deploy multiple different instances under the same ALB

### ISSUE THREAD

**Issue by shunjizhan** [aws/copilot-cli#5370]
Is it possible to deploy 2 different versions of `Load Balanced Web Service` under the same ALB?

Let's say I have a service with performance tracking enabled, and I hope to compare the performance between 2 different versions. So I need to deploy these 2 versions under the same ALB, and the traffic from the same endpoint can randomly go into one of them.

something like this would be awesome
```
name: myApp
type: Load Balanced Web Service

image:
  location:
     - myApp:v0.0.1
     - myApp:v0.0.2

count:
    - 1
    - 1
```

**Comment by iamhopaul123** [comment]
It sounds very similar to https://github.com/aws/copilot-cli/issues/1758. What do you think @shunjizhan?

**Comment by shunjizhan** [comment]
Yeah they are indeed very similar! I think my case is a subset of B/G deployment since it's simpler - it only requires two instances under the same ALB, and ALB can route traffic randomly to any of the instance. I don't need any more fine-grind traffic control that might be required by G/B deployment

**Comment by iamhopaul123** [comment]
I see. Hmm i don't think it's natively supported by Copilot but can you try

```
$ copilot task run --generate-cmd myapp/prod/mysvc

copilot task run \
--execution-role arn:aws:iam::1234567890:role/myapp-prod-mysvc-ExecutionRole-1DT0BFMP265BL \
--task-role arn:aws:iam::1234567890:role/myapp-prod-msvc-TaskRole-18SPG39UMYA4E \
--image 1234567890.dkr.ecr.us-west-2.amazonaws.com/myapp/mysvc:d601353b-17f3-4681-bf0c-3743bcc167a2-prod \
--entrypoint "" \
--command "" \
--security-groups sg-01f2716bf599fed80 \
--app myapp \
--env prod
```

it'll generate what command you can run to manually run tasks in the same service. You can substitute with any image of the older/newer version you'd like to run (with `--count` if you'd like to run more than 1 task).

**Comment by shunjizhan** [comment]
sounds great! Will try this out, thanks!!

**Comment by KollaAdithya** [comment]
Hello @shunjizhan !

I have another workaround for your use case of having 2 different versions of same service.
You can use yaml patches to use same Target Group for both services. In this way Load balancer will route traffic request to different targets in a round robin method.

Step1: Output the Target group Arn for service1 
```
- op: add
  path: /Outputs/MyTargetGroupArn
  value:
    Description: ARN of the Target group.
    Value: !GetAtt TargetGroup.TargetGroupArn
    Export:
      Name: MyTargetGroupArn
```
Step2: Remove the target group of service2 and replace with Target group created for service1.
```
- op: remove
  path: /Resources/TargetGroup

- op: replace
  path: /Resources/Service/Properties/LoadBalancers/0/TargetGroupArn
  value: 
    Fn::ImportValue: 
      "MyTargetGroupArn"

- op: replace
  path: /Resources/HTTPListenerRule/Properties/Actions/0/TargetGroupArn
  value: 
    Fn::ImportValue:
      "MyTargetGroupArn"
```

**Comment by shunjizhan** [comment]
@KollaAdithya this is an interesting way, will give it a try! Thanks a lot for providing the alternative solution
