### ISSUE TITLE
Support build args in `copilot task run` command

### ISSUE THREAD

**Issue by briercliffe** [aws/copilot-cli#5376]
A Dockerfile that I am trying to run as a Task requires build args. I am able to set the build args in a Job manifest successfully, but there is no option to declare them when running as a one-off task. Consider adding support for a `--build-args` when using `copilot task run`.

**Comment by Lou1415926** [comment]
Hi @briercliffe! AWS Copilot v1.32.0 is now released https://github.com/aws/copilot-cli/releases/tag/v1.32.0 🎉🚀 Your contribution is in this new release - thank you very much! Also check out our [blog post](https://aws.github.io/copilot-cli/blogs/release-v132/) for other very cool features ❤️ !
