### ISSUE TITLE
Update the default build image for AWS CodeBuild

### ISSUE THREAD

**Issue by blombard** [aws/copilot-cli#5421]
The image `aws/codebuild/amazonlinux2-x86_64-standard:3.0` has been deprecated: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html#deprecated-images

https://github.com/aws/copilot-cli/blob/fe2f0b3f551ccfb459a75fff9e4b14950d92dd10/site/content/docs/manifest/pipeline.en.md?plain=1#L137-L138

I think it would make sense to update the default image to `aws/codebuild/amazonlinux2-x86_64-standard:5.0`

I'd gladly do it if I have the go of a maintainer :) (And maybe a small guidance)

**Comment by huanjani** [comment]
Hi, @blombard!

Thanks so much for bringing this to our attention! It seems when [we updated the image from 3.0 to 4.0](https://github.com/aws/copilot-cli/pull/4666), we missed some of the docs! So the good news is that we're no longer using the deprecated 3.0. 

Thanks so much for the offer to make the changes, but I'll just update the docs for now. For future reference, the exact place is here: https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/deploy/pipeline.go#L29. Maybe we'll bump up from 4.0 to 5.0 at some point. ;)
