### ISSUE TITLE
Node.js 16 is now 'End of Life'

### ISSUE THREAD

**Issue by CameronMcAuley** [aws/copilot-cli#5422]
https://nodejs.org/en/blog/announcements/nodejs16-eol

'We are moving the End-of-Life date of Node.js 16 by seven months to coincide with the end of support of OpenSSL 1.1.1 on September 11th, 2023.'

With the newest version of the copilot-cli, generated Lambdas still use Node.js 16 which is EOL.
Are there any plans to upgrade this to 18 or 20?

**Comment by iamhopaul123** [comment]
Reopen in favor of https://github.com/aws/copilot-cli/pull/5432

**Comment by CameronMcAuley** [comment]
Hi @iamhopaul123 , has this been implemented?
I updated my copilot version to the latest and ran a copilot svc deploy on my already existing application, but the node.js  version of the codepilot genereated lambas did not update. Is there something else I need to do on my end?
Thanks

**Comment by KollaAdithya** [comment]
Hello @CameronMcAuley

`nodejs16.x` is still not upgraded to `nodejs18.x`. As mentioned over here 

> we can't use SDK v2 in our custom resource code(lambdas). Adopting to SDK v3 takes more effort.

Thanks for your patience!

**Comment by h5aaimtron** [comment]
@KollaAdithya what is the timeline for this upgrade? This has been flagged here at UCLA as a potential issue across accounts using copilot. Operationally, we are required to create upgrade and deprecation roadmaps aligned with EOL for various dependencies and their versions. Generally speaking, this allows us to migrate to new versions 3-6 months before their deprecation. Hoping to get something on our board for this so we can upgrade ASAP.

**Comment by Lou1415926** [comment]
@h5aaimtron sorry about the trouble! this is one of the top tasks on the list - we'll roll out the upgrade asap, and update the status here 🙇🏼‍♀️ !

**Comment by KollaAdithya** [comment]
Hello @CameronMcAuley and @h5aaimtron !

Nodejs 16.x  is now upgraded to nodejs20.x and now released in [v1.33](https://github.com/aws/copilot-cli/releases/tag/v1.33.0)

Upgrade to Copilot version v1.33 and run `copilot env deploy` and `copilot svc deploy` for all the environments and services to upgrade lambda runtimes to 20.x
