### ISSUE TITLE
Unable to deploy environment changes

### ISSUE THREAD

**Issue by ds29** [aws/copilot-cli#5428]
Hi, I'm unable to deploy changes to my environment using `copilot env deploy`. For some context/background, I've been using copilot very successfully since version 1.8.1. At that time, there were no environment manifests so my project did not have one until recently.

While on v1.31.0, I ran `copilot env init` to create the manifest for my staging environment. I set the manifest to this:
```
name: staging
type: Environment
http:
  public:
    access_logs: true
```
And then deployed it using `copilot env deploy`. This worked fine. I did all of this to try to troubleshoot a different issue I'm having. I posted on gitter about that one.

Since the logs were mostly noisy, I attempted to change the env manifest to disable access logs and enable observability insights instead:
```
name: staging
type: Environment
observability:
  container_insights: true
http:
  public:
    access_logs: false
```

After attempting to deploy, I received this error:
```
copilot env deploy
Name: staging
✔ Proposing infrastructure changes for the stronghaven-staging environment.
- Creating the infrastructure for the stronghaven-staging environment.               [update rollback complete]  [24.9s]
  The following resource(s) failed to update: [Cluster, PublicLoadBalanc
  er, EnvironmentManagerRole].
  - An ECS cluster to group your services                                            [update complete]           [4.3s]
    Resource update cancelled
  - Add an A-record to the hosted zone for the domain alias                          [not started]
  - An IAM Role to describe resources in your environment                            [update complete]           [4.3s]
    Resource update cancelled
  - An Application Load Balancer to distribute public traffic to your services       [update complete]           [0.0s]
    Resource handler returned message: "Attributes cannot be empty (Servic
    e: ElasticLoadBalancingV2, Status Code: 400, Request ID: 838a06dc-02a9
    -40b8-a5ab-2d924a53cd3c)" (RequestToken: ca63222c-0a11-7ca2-8715-364b9
    3ef5540, HandlerErrorCode: InvalidRequest)

✘ deploy environment staging: stack stronghaven-staging did not complete successfully and exited with status UPDATE_ROLLBACK_COMPLETE
```

I'm really confused about what is happening inside the environment. I appreciate any help in identifying and resolving the issue.

**Comment by iamhopaul123** [comment]
Hello @ds29. I am able to reproduce the error. It seems to be a bug. Thank you for reporting the issue!

> I'm really confused about what is happening inside the environment. I appreciate any help in identifying and resolving the issue.

So sorry about the confusion. I'm trying to figure out the cause of this issue and will give update here.

**Comment by iamhopaul123** [comment]
Hello @ds29. The root cause for this is because when you remove `access_logs` config, we actually remove `LoadBalancerAttribute` from the CFN template too. However, CFN expects users to explicitly set `access_logs.s3.enabled` to `false` when disabling the feature. We are working on a fix right now. Sorry again for the inconvenience.

**Comment by ds29** [comment]
Hi @iamhopaul123, glad to hear it. Many thanks for the upcoming fix.

**Comment by Lou1415926** [comment]
Hi @ds29 , AWS Copilot v1.32.0 is now released: https://github.com/aws/copilot-cli/releases/tag/v1.32.0 🎉🚀 The fix for his issue is also released - you should now be able to disable `access_logs`. Also check out our [blog post](https://aws.github.io/copilot-cli/blogs/release-v132/) for other very cool features ❤️ !
