### ISSUE TITLE
Is it possible to forward a port with `copilot svc exec`?

### ISSUE THREAD

**Issue by laughingman7743** [aws/copilot-cli#5441]
Hello, we can easily execute any command with the `copilot svc exec`, but is it possible to forward a port?

https://aws.github.io/copilot-cli/docs/commands/svc-exec/

I would like to be able to use port forwarding to easily access a backend database located in a private segment from a local environment. It would be very helpful for many developers.

Ecspresso seems to have such a feature.
https://github.com/kayac/ecspresso#exec

SSM supports port forwarding, so I would guess that Copilot could support it as well.
https://aws.amazon.com/jp/blogs/mt/use-port-forwarding-in-aws-systems-manager-session-manager-to-connect-to-remote-hosts/

**Comment by iamhopaul123** [comment]
Hello @laughingman7743. It seems like it can be resolved by https://github.com/aws/copilot-cli/discussions/5263. Feel free track the discussion and we'll give more update there!

**Comment by laughingman7743** [comment]
Thanks for your information, I will track the discussion.
I hope such a port forwarding feature will be implemented.

**Comment by dannyrandall** [comment]
Hey @laughingman7743! We recently released `copilot run local --proxy` in [v1.32](https://aws.github.io/copilot-cli/blogs/release-v132/). You can use that feature to access your database from the code running on your local machine. Give it a try and let us know if it works for your use case!

I'll close this now, but feel free to reopen or share any feedback!😊

**Comment by laughingman7743** [comment]
Great feature. 🎉  Thank you!
