### ISSUE TITLE
Unable to deploy  using copilot for existing service

### ISSUE THREAD

**Issue by shain-digix** [aws/copilot-cli#5450]
I have a service(B) which i manually created inside my cluster. Now i want to switch the deployment to using copilot. What is the best way to achieve it?

Note: In my cluster, I already have a service(A) which is already deployed using aws copilot. This is the second service which I want to deploy under the same cluster.

Also I want to use the same Loadbalancer for service B which I am already using for service A

**Comment by CaptainCarpensir** [comment]
Currently using Copilot you have to delete and redeploy an ECS service to have it be managed by Copilot. We have an old existing issue for [importing a service](#1095) that you can show interest in. However, in the next release you'll be able to import existing ALBs as described in #5438.
