### ISSUE TITLE
copilot sign failed issue

### ISSUE THREAD

**Issue by kakao-logan-kk** [aws/copilot-cli#5451]
Whenever I log in to github copilot. I met this issue.

What wrong with my account? or device?

------

thanks, never mind this issue

**Comment by CaptainCarpensir** [comment]
Sorry for the confusion, this is AWS Copilot-CLI, not GitHub Copilot. We're a tool used for deploying containers on AWS. You may be able to find what you need [here](https://docs.github.com/en/copilot).
