### ISSUE TITLE
cannot delete env

### ISSUE THREAD

**Issue by sebastianovide** [aws/copilot-cli#5481]
trying to delete an environment and keep failing. From cloud formation I can see 

```
PublicSubnet1 | DELETE_FAILED | Resource handler returned message: "The subnet 'subnet-018a56d9f6694def5' has dependencies and cannot be deleted. (Service: Ec2, Status Code: 400, Request ID: 39bc4d02-03b0-4acd-a316-e19076f80a11)" (RequestToken: 5b984c69-34dc-62e8-0874-d3fa00a65486, HandlerErrorCode: InvalidRequest)
-- | -- | --
```

Trying to manually delete that subnet I get
![Screenshot 2023-11-15 at 17 24 56](https://github.com/aws/copilot-cli/assets/1496395/36a2c092-adc4-4286-977f-4bf5ed8c7fc7)

and trying to delete the network interfaces I get
![Screenshot 2023-11-15 at 17 27 33](https://github.com/aws/copilot-cli/assets/1496395/92200367-8a6b-4e5b-a1ad-4afb3cd1437e)

Clicking on
![Screenshot 2023-11-15 at 17 29 19](https://github.com/aws/copilot-cli/assets/1496395/6f6b6ecd-7798-4c7d-af52-411512f37e08)
 the Possible owning resource I see nothing:
 

what's next ?

Thanks

**Comment by Lou1415926** [comment]
@sebastianovide Hi 👋🏼 This is quite bizarre. Do you know anything about the "docker-dev" nlb, e.g. when it is created, is it in a stack, etc.?

You can use aws cli to check up "docker-dev" info as well, just in case it's a glitch only on the console: 
```
AWS_REGION=<the region you are looking at> aws elbv2 describe-load-balancers --names docker-dev
```

**Comment by sebastianovide** [comment]
thanks @Lou1415926 . After digging everywhere I found a resource being owned by another account...
