### ISSUE TITLE
RRSet with DNS name <name> is not permitted in zone when deploying environment

### ISSUE THREAD

**Issue by CyanCode** [aws/copilot-cli#5493]
Hi folks, I'm getting the following error when trying to deploy a new environment named qa. 

```
Received response status [FAILED] from custom resource. Message returned: [RRSet with DNS name qa.<app>.<domain>.com. is not permitted in zone prod.<app>.<domain>.com.] (Log: /aws/lambda/<app>-qa-DNSDelegationFunction-Kt3hcugbCrpH/2023/11/17/[$LATEST]39053033015441fc9fc63498019644a7) (RequestId: b43cdfd5-82f9-4498-8091-1234615e11d1)
```

causing a rollback of the CloudFormation stack (`The following resource(s) failed to create: [ServiceDiscoveryNamespace, DelegateDNSAction].`). For some reason it looks like its trying to modify `prod.<app>.<domain>.com` despite me deploying the qa environment

Some things to know:
- The name of this environment (qa) is one I had deployed previously but had deleted. I'm now trying to stand up a new environment with the same name so its possible there are some resources that weren't cleaned up causing this issue.
- I have another environment (prod) that is currently deployed with 3 hosted zones (`<domain>.com`, `prod.<app>.<domain>.com`, and `prod.<app>.local`)

**Comment by KollaAdithya** [comment]
Hello @CyanCode !

Which version of `Copilot` are you using? Is it `v1.32.0`.

**Comment by KollaAdithya** [comment]
Also can you provide more information for these questions

1. Do you have an application with `domain`?
2. Does both the environments `qa` and `prod` have imported certificates or not`?

**Comment by CyanCode** [comment]
Hi there,
- copilot version v1.28.0 (I can try updating if that might help)
- I do have an application with that domain set, yes
- I didn't set certificates through the manifest but they do have certificates, yes. After the environment was deployed previously I went into Route53 + Cert Manager and added certificates manually. This was months ago though and up until I had deleted the QA env (which I'm now working to recreate) I had no issues with this method.

**Comment by KollaAdithya** [comment]
Hey @CyanCode !

can you run `copilot env package` and paste the CloudFormation template over here.

**Comment by CyanCode** [comment]
Yep, [here's a gist](https://gist.github.com/CyanCode/35a3c88cb80071267fc117b493eb8cf4)

**Comment by KollaAdithya** [comment]
Out of the following three custom resources in your env stack

1. DelegateDNSAction
2. CustomDomainAction
3. HTTPSCert

Is only DelegateDNSAction failed to create and are the other remaining custom resources successfully created?
