### ISSUE TITLE
Error creating roles: minimum field size of 20, AssumeRoleInput.RoleArn

### ISSUE THREAD

**Issue by adeperio-avarni** [aws/copilot-cli#5497]
When I try create an app and environment using copilot init I always get the error:
`minimum field size of 20, AssumeRoleInput.RoleArn.`

When looking further in the Stacks and resources geneeratedit doesn't seem to create the following roles
EnvManagerRole
CFNExecutionRole

And the related parameter store entry for the environment has blank values for those properties (executionRoleARN, and managerRoleARN)

The following is some of the console output:

```
All right, you're all set for local development.
Deploy: Yes
Only found one option, defaulting to: Create a new environment
Environment name: dev
Environment dev does not yet exist in application [app]; initializing it.
✔ Wrote the manifest for environment dev at copilot/environments/dev/manifest.yml
- Update regional resources with stack set "[app]-infrastructure"  [succeeded]  [164.7s]
✔ Proposing infrastructure changes for the [app]-dev environment.
✔ Provisioned bootstrap resources for environment dev in region ap-southeast-2 under application [app].
✔ Provisioned bootstrap resources for environment dev.
✘ get template version of environment dev: get metadata for stack [app]-dev: get template summary: InvalidParameter: 1 validation error(s) found.
- minimum field size of 20, AssumeRoleInput.RoleArn.
```

I have deleted the app and environments and recreated them a number of times. Is there anything else that I can be looking at? I'm on v1.32 of copliot.

This is the first time I have encountered this issue. I have successfully created other applications with copilot in the past without seeing this error.

**Comment by KollaAdithya** [comment]
Hello @adeperio-avarni 

Can you run `copilot env init --name dev` instead of `copilot init`. Does it produce the same error as above?

**Comment by adeperio-avarni** [comment]
Hi @KollaAdithya yea just tried that and getting the same thing

**Comment by adeperio-avarni** [comment]
A little bit of more info, it also only manages to generate two stacks:

<img width="305" alt="image" src="https://github.com/aws/copilot-cli/assets/114455891/c5d3eae5-3d3f-4874-abf6-4f964c26aa9a">

**Comment by KollaAdithya** [comment]
ah this seems little weird both `copilot init` and `copilot env init` does not create `EnvManagerRole` and `CFNExecutionRole` 🤔 

 I tried out creating a new environment with `v1.32.0`. I do not see any issues with Environment creation.
 
 ```
 copilot-cli took 7m 10.2s ✦ ➜ copilot env init         
Environment name: demo
Credential source: [profile user1]
Default environment configuration? Yes, use default.
✔ Manifest file for environment demo already exists at copilot/environments/demo/manifest.yml, skipping writing it.
- Update regional resources with stack set "dhoni-infrastructure"  [succeeded]  [9.2s]
✔ Proposing infrastructure changes for the dhoni-demo environment.
- Creating the infrastructure for the dhoni-demo environment.  [create complete]  [58.6s]
  - An IAM Role for AWS CloudFormation to manage resources     [create complete]  [21.4s]
  - An IAM Role to describe resources in your environment      [create complete]  [25.0s]
✔ Provisioned bootstrap resources for environment demo in region us-east-1 under application dhoni.
Recommended follow-up actions:
  - Update your manifest copilot/environments/demo/manifest.yml to change the defaults.
  - Run `copilot env deploy --name demo` to deploy your environment.
  ```
  
  Can you check once whether the `user profile` that you are using to create an environment  have necessary permissions.
  
  My user profile has admin access though
  ```
  {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

**Comment by adeperio-avarni** [comment]
Hi @KollaAdithya thanks for your reply. The way I managed this in the end was that after I run copilot init, and it asks me to create an environment, I actually say no at this point. Then I go ahead and create the environment manually using copilot env init. Every time I tried to follow the prompts from copilot init, it never created those roles, which I thought was weird. Do you see that happening on your end?
