### ISSUE TITLE
Not authorized to perform: kms:GenerateDataKey when I set  IP address restrictions for IAM users

### ISSUE THREAD

**Issue by interu** [aws/copilot-cli#5500]
in copilot-cli v 1.32.0

Errors now occur when setup a new environment(Load Balanced Web Service).

```
$ copilot env init --name $APP_ENV --profile $AWS_PROFILE

- Update regional resources with stack set "test-app-infrastructure"  [succeeded]  [9.1s]
✘ upload manual/templates/test-app-production/xxxxxxxxxxxxx.yml to bucket 
stackset-test-app-infrastruc-pipelinebuiltartifactbuc-cgxxxxxxxxx: AccessDenied: 
User: arn:aws:iam::0123456789:user/copilot-cli-admin is not authorized to perform: kms:GenerateDataKey on
resource: arn:aws:kms:ap-northeast-1:0123456789:key/xxxxxxxxxxxxxxxxxx because no identity-based 
policy allows the kms:GenerateDataKey action
```

The error seems to be caused by the IAM user in profile.
I am adding an IP address restriction setting to narrow down the permissions of the IAM user.

A sample is below.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "123.123.123.123/32"
                }
            }
        }
    ]
}
```

I was found that if the "Condition" was removed, the error would no longer occur.

However, for security reasons, we do not want to relax this condition.

For reference, a similar event also occurs with "copilot pipeline deploy".

**Comment by KollaAdithya** [comment]
Hello @interu !

Do you have `permission boundaries` or any other additional policies attached to the Profile other than the policy mentioned above?

**Comment by interu** [comment]
Hello @KollaAdithya 
No, I haven't.

**Comment by Lou1415926** [comment]
Hi @interu ! Can you go to the CloudTrail console, locate the denied action and find the source ip of that call and see if it matches the condition that you specified?

<img width="786" alt="Screenshot 2023-11-22 at 11 50 43 AM" src="https://github.com/aws/copilot-cli/assets/79273084/336f223a-5f93-47ee-b658-b55395585302">

**Comment by interu** [comment]
@Lou1415926 
Sorry for the Japanese screenshot.
![image](https://github.com/aws/copilot-cli/assets/10859/9ce2dfd4-2cbe-4d9e-a655-4f4c0044a6a8)

Source IP address is "AWS Internal"

I'll give it a try, as I think the following modification to IAM might solve the problem.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "NotIpAddress": {
                    "aws:SourceIp": [
                        "123.123.123.123/32"
                    ]
                },
                "Bool": {"aws:ViaAWSService": "false"}
            }
        },
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

If you have a better way to define it, please let me know.

**Comment by interu** [comment]
@Lou1415926 @KollaAdithya

Changing to the above IAM policy solved the problem.
Thank you for your cooperation in investigating the cause.
