### ISSUE TITLE
[GitHub] No Branch [branch] found for FullRepositoryName [branch]

### ISSUE THREAD

**Issue by sabin2018** [aws/copilot-cli#5507]
after configure my pipeline manifest i run `copilot pipeline deploy` it give me `Successfully deployed pipeline` message but my pipeline fails with message [GitHub] No Branch [branch] found for FullRepositoryName [branch] at AWS pipeline console. I run my pipeline command under same environment.

**Comment by CaptainCarpensir** [comment]
Copilot finds the branch used for a pipeline by reading the pipeline manifest. By default the branch is set to the branch you currently have checked out on your local machine. My guess is that you were checked out to a testing branch that you later deleted and so the pipeline could no longer find the branch. 

If this isn't the case, can you post the pipeline manifest here so I can see what else may have happened?

**Comment by engrbilal1** [comment]
I got the same issue after researching I found that when we select GitHub as a source for the repo then you will see 2 versions when selecting version 2 so now during the creating connection you should be using the "GitHub link app" where you can select the required repos after that your issue will be solved.
