### ISSUE TITLE
Deployment Time

### ISSUE THREAD

**Issue by nicks6853** [aws/copilot-cli#5515]
Hi,

I have a project using AWS Copilot, it has two services, one that holds a MySQL database and the other runs a Ruby on rails application. I am struggling to improve the deployment times and I am wondering if it something that I am doing wrong.

I saw [this issue](https://github.com/aws/copilot-cli/discussions/3480) where it was recommended that I adjust the healthcheck configuration, but I do not have anything set for those, and the defaults seem reasonable.

I am working on a example application as our company is looking to move some Ruby apps to AWS, but I have made a simple code change to my Ruby on Rails application and deploying that with `copilot svc deploy --name web` took over 450 seconds which is too much for us to make this the tool we use long term.

Do you have any recommendations on what I could do to improve the deployment times? Am I doing something wrong or is this normal.

**Comment by CaptainCarpensir** [comment]
Thanks for your question, I have a couple answers!

First off, because it looks like a small deployment change is taking a long time for you, we have a manifest field called `recreate` which lets ECS remove the old tasks and deploy the new tasks at the same time which you can read about [here](https://aws.github.io/copilot-cli/en/blogs/release-v118/#recreate-strategy-for-faster-redeployments). This is good for testing environments when you don't need to maintain uptime in your service.

Secondly, we recently released a feature `copilot run local --proxy`! In a situation like this where you're just testing a small code change, instead of making new deployments every time for testing sake, you can spin up containers on your local machine and the `--proxy` flag will create connections to service connect hosts and RDS databases. This way you won't need to deal with a lengthy ECS deployment when testing changes.

**Comment by nicks6853** [comment]
Hey, thank you for getting back to me. I will have to spend some time experimenting with this. Sounds promising.

**Comment by nicks6853** [comment]
Wondering if I could also get some help with this, it seems that whenever a deployment fails it keeps trying forever. I have two services, one for a DB and another for a Rails app. I had a mistake in my config where the DB host was not specified correctly so my Docker entrypoint script was failing to run for my Rails container. Whenever it failed it kept trying to create a new container (for over 30 minutes) until I stopped it manually. Is there any way around that? Wondering how this would work for us if we try to automate deployments with Bitbucket pipelines and something goes wrong during the deployment.

**Comment by Lou1415926** [comment]
> Whenever it failed it kept trying to create a new container (for over 30 minutes) until I stopped it manually. 

I believe the [ECS circuit breaker](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-circuit-breaker.html) was triggered, which will retry the deployment a certain number of times (calculated based on the desired task count) before it gives up on that deployment. 

In this case, when you deploy using `copilot svc deploy` from your local machine, you can hit ctrl+c. Copilot will tell CloudFormation to rollback the deployment, which will override the retries that ECS circuit breaker is attempting and instead  just rollback.

> Wondering how this would work for us if we try to automate deployments with Bitbucket pipelines and something goes wrong during the deployment.

If you _already_ know that there is an error and want to short circuit the retries - unfortunately I am not aware of any manual rollback option in CodePipeline yet 😞 . However, you could either a) go to the CloudFormation console, click "Stack actions" and then "Cancel update stack" or b) use aws cli `aws cloudformation cancel-update-stack --stack-name xxx`. This will:
1) Rollback the said stack early, before waiting for the ECS Circuit Breaker to give up (basically the same as hitting ctrl+c). The caveat is that it has no effect on the other stacks in the `DeployToXX` stage, meaning that you may end up with the said stack on version X, and the other stacks on version X+1.
2) Eventually put your `DeployToXX` stage in the CodePipeline (assuming you are using the `copilot pipeline` feature) into a failed state. 

After that, you can "rollback" all stacks to version X but reverting the latest commit: when the execution goes to `DeployToXX` stage, it deploys the problem stack from version X to version X, and deploys the other stack from version X+1 to X.

Alternatively to "rollback" to version X, you can push a newly fixed code - this deploys the problem stack from X to X+2, and the other stacks from X+1 to X+2.

Hope this answers the questions!
