### ISSUE TITLE
2nd Service Does Use Default Domain Alias URL

### ISSUE THREAD

**Issue by oxbits** [aws/copilot-cli#5544]
Thank you for this amazing command line interface: 
AWS copilot is AWESOME !!!!  🚀 🚀 🚀 🚀 

I am experiencing something I cannot figure out ....

First I did this:

```
% copilot app init --domain mydomain.com
```

Then I did this:

```
% copilot init
```

and I create a `Static Site`

I deployed it to `myenv` environment

Then I did this again:

```
% copilot init
```

and I create a `Request-Driven Web Service`

I deployed it to `myenv` environment

Details of app and svc:

```
% copilot app show
About

  Name                  test-application
  Version               v1.30.1
  URI                   mydomain.com
  Permissions Boundary  N/A

Environments

  Name     AccountID     Region
  ----     ---------     ------
  myenv  XXXXXXXXXXXX  us-east-1

Workloads

  Name            Type                        Environments
  ----            ----                        ------------
  static-service  Static Site                 myenv
  webserv         Request-Driven Web Service  myenv

Pipelines

  Name
  ----

################################

% copilot svc show
Service name: static-service
About

  Application  test-application
  Name         static-service
  Type         Static Site

Routes

  Environment  URL
  -----------  ---
  myenv      https://xxxxxxxxxxxxxx.cloudfront.net/ or https://static-service.myenv.test-application.mydomain.com/

S3 Bucket Objects

  Environment  myenv
.
└── index.html

################################

% copilot svc show
Service name: webserv
About

  Application  test-application
  Name         webserv
  Type         Request-Driven Web Service

Configurations

  Environment  CPU (vCPU)  Memory (MiB)  Port
  -----------  ----------  ------------  ----
  myenv      1           2048          80

Routes

  Environment  Ingress   URL
  -----------  -------   ---
  myenv      internet  https://xxxxxxxxxx.us-east-1.awsapprunner.com

Variables

  Name                      Environment  Value
  ----                      -----------  -----
  COPILOT_APPLICATION_NAME  myenv      test-application
  COPILOT_ENVIRONMENT_NAME    "          myenv
  COPILOT_SERVICE_NAME        "          webserv
```

Why isn't my `Request-Driven Web Service` available at a default URL like my `Static Site` is?:

Assumed default service name i.e.:
`${SvcName}.${EnvName}.${AppName}.${DomainName}`

AVAILABLE - Static Site URL:
`https://static-service.myenv.test-application.mydomain.com/`

NOT AVAILABLE ?!?! - Request-Driven Web Service URL:
`https://webserv.myenv.test-application.mydomain.com/`

Why?

.... and what can I do to make my `Request-Driven Web Service` available at the expected default URL?

**Comment by iamhopaul123** [comment]
Hello @oxbits 

> Thank you for this amazing command line interface:
AWS copilot is AWESOME !!!! 🚀 🚀 🚀 🚀

Thank you! I am very happy that you like the tool.

> NOT AVAILABLE ?!?! - Request-Driven Web Service URL:
https://webserv.myenv.test-application.mydomain.com/

I think it's mostly because by default AWS app runner gives a HTTPS URL with a default certificate. You can make the same call for the static site service as CloudFront gives a default HTTPS URL too, but IIRC this is actually the first time we get such a feature request regarding RDWS's default alias.

> .... and what can I do to make my Request-Driven Web Service available at the expected default URL?

You can easily specify [an alias in your local manifest](https://aws.github.io/copilot-cli/docs/manifest/rd-web-service/#http-alias) with a consistent style as the default alias.

Please let me know if you have more questions!

**Comment by oxbits** [comment]
@iamhopaul123 thank you for your reply

When I add this code to my `webserv` manifest.yml:
```
http:
  alias: webserv.myenv.test-application.mydomain.com
```

I get this error:
```
✘ webserv.myenv.test-application.mydomain.com of `http.alias` field should match the pattern <subdomain>.mydomain.com 
Where <subdomain> cannot be the application name.
✘ deploy service webserv to environment myenv: webserv.myenv.test-application.mydomain.com is an environment-level alias, which is not supported yet
```

**Comment by iamhopaul123** [comment]
Hello @oxbits. Sorry for the confusion. I forgot https://github.com/aws/copilot-cli/issues/5095 was not supported yet. Do you have to keep `webserv.myenv.test-application.mydomain.com` this alias or it's ok for you to use an alias with `<subdomain>.mydomain.com ` this pattern?

**Comment by oxbits** [comment]
@iamhopaul123  thank you for the clarification of what is supported and not supported, this helps immensely, and i can make it work knowing what is possible.

one last thing: is it possible to point `mydomain.com` without any subdomain at one of my services using aws copilot ?

**Comment by Lou1415926** [comment]
@oxbits yes - you can specify `http.alias: mydomain.com`!
