### ISSUE TITLE
[BUG] cannot delete deleted app

### ISSUE THREAD

**Issue by RyosukeDTomita** [aws/copilot-cli#5545]
Hi. I'm sigma.
I'm beginner of copilot cli.

I created at app using `copilot`.
After that, I delete Cloud Formation stack, then `copilot` command display deleted stack app.
I tried to delete app, but stack is already deleted.

```shell
copilot app delete
Application: myapp-copilot
Sure? Yes
✘ execute env delete: find service cloudformation stacks: AccessDenied: User: arn:aws:iam::xxxxxxxxxxxx:user/tomita-cli is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxxxx:role/myapp-copilot-test-EnvManagerRole
        status code: 403, request id: ff7728bc-826a-4deb-b314-160164c6ee82

copilot app ls
myapp-copilot # ← This is deleted by Cloud Formation Stack. So, I want to erase it when I call copilot app ls. 
```

Please teach me how to fix it.

I also tried to use `copilot app ls` in AWS Cloud Shell.
But, same result is returned.

**Comment by RyosukeDTomita** [comment]
Where does `copilot app ls` get its list of applications from?

**Comment by RyosukeDTomita** [comment]
I delete parameter store value. Then fix it.

**Comment by iamhopaul123** [comment]
Hello @RyosukeDTomita. I am glad you figured the problem out on your own. Please feel free to open another issue if you are still in trouble getting started with Copilot.
