### ISSUE TITLE
Prompt the user for environment name in init flow

### ISSUE THREAD

**Issue by sonofachamp** [aws/copilot-cli#56]
When a user runs the `init` command they are asked if they want to create a test environment. If they select `y` we're defaulting an environment name `"test"`. We should also prompt them for a name with a default value of `"test"`.

**Comment by efekarakus** [comment]
Similar to https://github.com/aws/amazon-ecs-cli-v2/issues/317

**Comment by efekarakus** [comment]
Closing this issue as I don't think we'll change the "init" workflow. The "init" command aims at being a great getting started point to understand the concepts of the CLI, but if you need more environments or intricate flows users can use directly the `copilot env` and `copilot svc` commands.
