### ISSUE TITLE
Login Fails

### ISSUE THREAD

**Issue by piratetorben** [aws/copilot-cli#5600]
I am unable to login and therefore use the product with vscode. 

1. I am in vscode and I am installing the extension via the marketplace.
2. The copilot extension gets installed
3. I expect to see a login screen. However, instead, I see an info saying `your GitHub token is invalid. Please sign out from your Github account...`
4. Yet, vscode won't let me login with my github account.

**Comment by iamhopaul123** [comment]
Hello @piratetorben this is AWS Copilot CLI and we can't answer questions related to GH Copilot.
