### ISSUE TITLE
Grant ECS tagging authorisation where required

### ISSUE THREAD

**Issue by mattattui** [aws/copilot-cli#5601]
I've recently been mailed with the subject "\[Action Required\] Update your IAM policies by March 29, 2024 by adding explicit “Allow” for ecs:TagResource action". The message informed me that AWS ECS introduced [tagging authorisation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#tag-resources-setting) for resource creation in April 2023, and are planning to soon (over February & March 2024) require principals which call the CreateCapacityProvider, CreateCluster, CreateService, CreateTaskSet, RegisterContainerInstance, RunTask, StartTask, and RegisterTaskDefinition APIs to be explicitly granted the `ecs:tagResource` IAM permission.

One such principal is the Copilot environment controller. Am I right in understanding that this permission is missing from the [mainline branch's environment controller template](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/environment/partials/environment-manager-role.yml#L63-L85)? 

There may be other copilot-managed roles which also require this permission… I'm afraid I'm not very well acquainted with Copilot's inner workings.

**Comment by iamhopaul123** [comment]
Hello @mattattui. That's a good question. The env manager role you referred to is actually the one we use to interact with resources created through CloudFormation, including the ECS resources. Therefore, we don't need to grant the `ecs:tagResource` permission. As for [the CFN execution role](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/environment/partials/cfn-execution-role.yml), ideally it can create any resource if not bounded by the permission boundary set by users when creating the Copilot applications.

**Comment by mattattui** [comment]
Thanks @iamhopaul123 – I've enabled Tagging Authorisation in my ECS account settings and will reopen this issue if I notice any problems.
