### ISSUE TITLE
Is there any documentation for getting the list of Permissions that are needed for copilot to run without any permission error?

### ISSUE THREAD

**Issue by shain-digix** [aws/copilot-cli#5608]
Because everytime I run the copilot service deploy, a new permission error pops up.

Received response status [FAILED] from custom resource. Message return ed: User: arn:aws:sts::193980408680:assumed-role/cd-paas-ngpay-service -dev-ngpay-EnvControllerRole-fMcu2P8hPESe/cd-paas-ngpay-service-dev-ng -EnvControllerFunction-J7PWnRaTHdEe is not authorized to perform: iam: PassRole on resource: arn:aws:iam::193980408680:role/cd-paas-ngpay-ser vice-dev-CFNExecutionRole because no identity-based policy allows the iam:PassRole action (Log: /aws/lambda/cd-paas-ngpay-service-dev-ng-Env ControllerFunction-J7PWnRaTHdEe/2024/01/15/[$LATEST]f3847d2a4eac4849b6 c69af1fa44a629) (RequestId: 914b386d-e4a2-4286-b74f-988f61fbd787)

**Comment by Lou1415926** [comment]
@shain-digix I can help you with that. Just one thing that I want to make sure before jumping into the solution, I assume you have permissions boundary added to the app right? Sorry for the trouble :(!
