### ISSUE TITLE
Feature request: Additional configuration on ALB managed by Copilot

### ISSUE THREAD

**Issue by rickychew77** [aws/copilot-cli#5620]
While we are making deployment with CoPilot, we need to ensure configuration like `Drop invalid header fields` and others like `Deletion protection`, `WAF fail open` etc are enabled in ALB and doesn't seems to be able to manage it in CoPilot manifest, ideally each ALB we deploy with CoPilot should have this, otherwise we'll have to manually turn it on in console which can be daunting for ClickOps!

Having this attribute may making backend server target vulnerable to HTTP desync attacks.

Do let me know if there's any better way than ClickOps to do so! Cheers

**Comment by Lou1415926** [comment]
Try using [yaml patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) for the environments! You can use yaml patch to add [these attributes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattribute.html) to the CloudFormation template that Copilot generates. After you have the patch, run `copilot svc package --diff` or `copilot svc deploy --diff` to make sure that you are happy with the change before deploying!
