### ISSUE TITLE
delete env addon without deleting env

### ISSUE THREAD

**Issue by oxbits** [aws/copilot-cli#5624]
is there a way to delete an env addon without deleting the env ?

specifically an s3 env addon and an aurora env addon ?

**Comment by Lou1415926** [comment]
yeah - you can just remote the corresponding addons files and run `copilot env deploy`. This will deploy an environment stack that does _not_ contain the s3 / aurora addon, which will trigger a "DELETE" on those resources defined by the deleted files from CloudFormation.
