### ISSUE TITLE
`svc package` fails on Request Driven Web Service

### ISSUE THREAD

**Issue by CaptainCarpensir** [aws/copilot-cli#5634]
When trying to view the template of a RDWS with `copilot svc package` it currently fails unless you use `image.location`. This is because when generating the template parameters, the image is not populated correctly by [this](https://github.com/aws/copilot-cli/blob/c3e424953587e4f7238010e7cf96375ba78fd324/internal/pkg/deploy/cloudformation/stack/workload.go#L419) line.

This results in the error: 
`✘ generate workload rdws template against environment test: generate stack template parameters: determine image repository type: image is not supported by App Runner: `
Because AppRunner validates the image type, this fails when the image is an empty string.

**Comment by jorgeavaldez** [comment]
Also noting that this command works when it's run via a codepipeline with the buildspec body provided by the `pipeline init` command
