### ISSUE TITLE
Access Denied on env init command

### ISSUE THREAD

**Issue by icruwrks** [aws/copilot-cli#5640]
Hello!

After updating from copilot version: v1.30.1 to v1.33.0, I am getting Access Denied during env init.
What should I do?

If I revert to copilot version: v1.30.1, this error does not occur.

```
# v1.33.0
$ copilot env init
Environment name: test
Credential source: [profile default]
Default environment configuration? Yes, use default.
✓ Manifest file for environment test already exists at copilot/environments/test/manifest.yml, skipping writing it.
- Update regional resources with stack set "my-app-infrastructure"  [succeeded]  [10.3s]
✓ Proposing infrastructure changes for the my-app-test environment.
✘ check if changeset is empty: create change set copilot-4c8ffafd-aaaa-bbbb-cccc-xxxxxxxxxxxx for stack my-app-test: ValidationError: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
        status code: 400, request id: c2f4915c-aaaa-bbbb-cccc-xxxxxxxxxxxx: describe change set copilot-4c8ffafd-aaaa-bbbb-cccc-xxxxxxxxxxxx for stack my-app-test: ValidationError: Stack [my-app-test] does not exist
        status code: 400, request id: dae1ac31-aaaa-bbbb-cccc-xxxxxxxxxxxx
```

```
# v1.30.1
$ copilot env init
Environment name: test
Credential source: [profile default]
Default environment configuration? Yes, use default.
✓ Manifest file for environment test already exists at copilot/environments/test/manifest.yml, skipping writing it.
- Update regional resources with stack set "my-app-infrastructure"  [succeeded]  [41.1s]
✓ Proposing infrastructure changes for the my-app-test environment.
- Creating the infrastructure for the my-app-test environment.  [create complete]  [49.6s]
  - An IAM Role for AWS CloudFormation to manage resources          [create complete]  [21.4s]
  - An IAM Role to describe resources in your environment           [create complete]  [19.8s]
✓ Provisioned bootstrap resources for environment test in region ap-northeast-1 under application my-app.
Recommended follow-up actions:
  - Update your manifest copilot/environments/test/manifest.yml to change the defaults.
  - Run `copilot env deploy --name test` to deploy your environment.
```

**Comment by KollaAdithya** [comment]
Hello @icruwrks !

Once you upgrade to v1.33.0
1. run `copilot app upgrade` if there are any changes that need to be applied to the S3 bucket.
2. Then run `copilot env init` to deploy the environment.

Let me know how it goes.

**Comment by icruwrks** [comment]
I tried running copilot app upgrade and updating to v1.33.1, but the error did not change.
I will continue to look into this.

**Comment by icruwrks** [comment]
The 'copilot pipeline deploy' command also fails, so there may be a problem with the privileges of the user executing it.

`
$ copilot pipeline deploy --name my-app-dev
✓ Successfully added pipeline resources to your application: my-app
Are you sure you want to redeploy an existing pipeline: my-app-dev? Yes
✘ Failed to accept changes for pipeline: my-app-dev.
✘ update pipeline: update pipeline: check if changeset is empty: create change set copilot-0a82ad22-aaaa-bbbb-cccc-xxxxxxxxxxxx for stack pipeline-my-app-my-app-dev: ValidationError: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
        status code: 400, request id: 5462e625-aaaa-bbbb-cccc-xxxxxxxxxxxx: describe change set copilot-0a82ad22-aaaa-bbbb-cccc-xxxxxxxxxxxx for stack pipeline-my-app-my-app-dev: ChangeSetNotFound: ChangeSet [copilot-0a82ad22-7395-47a5-822c-d29fd2853770] does not exist
        status code: 404, request id: 5ffd520f-aaaa-bbbb-cccc-xxxxxxxxxxxx
`

**Comment by KollaAdithya** [comment]
Hello @icruwrks 

I couldn't reproduce issue on my end.

can you verify the scenarios described in a previous GitHub [discussion](https://github.com/aws/copilot-cli/discussions/5575#discussioncomment-7911275) where a customer encountered a similar situation.

**Comment by icruwrks** [comment]
It seems to have been caused by the lack of policy regarding kms for the executing user.
Adding the following policy enabled execution.

Thank you very much.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "kms:GenerateDataKey",
                "kms:Decrypt",
                "kms:Encrypt"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```
