### ISSUE TITLE
Missing DeployTo-{env} stage in pipeline

### ISSUE THREAD

**Issue by federicobond** [aws/copilot-cli#5645]
Hi! From the docs I was expecting to see a DeployTo-* stage in a new pipeline created with `copilot pipeline init` but my pipeline only has Source and Build stages.

Under what conditions is the deploy stage created? I could find no information about it online.

I am running copilot v1.33.

**Comment by federicobond** [comment]
Apparently if you add a `stages.deployments.{svc}` key to the pipeline manifest it creates a DeployTo stage, but the docs make it look like this should only be required when you want to manually control deployment ordering.

**Comment by KollaAdithya** [comment]
Hello @federicobond !

Sorry for the confusion that you had. Can you point me to the docs where this is mentioned so that i can fix this.

> but the docs make it look like this should only be required when you want to manually control deployment ordering.

**Comment by federicobond** [comment]
It's partly [this section](https://aws.github.io/copilot-cli/docs/concepts/pipelines/#ordering) and the fact that the `deployments` field is not mentioned previously.

**Comment by KollaAdithya** [comment]
Hello @federicobond !

That seems to be correct to me. [`deployments`](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-deployments) are indeed helps to control the order of deployments of a service and the field is **optional**. If not specified then all the workloads in that environment is deployed in parallel.


You need to specify the [`stages.name`](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-name) **(required)** to generate the `DeployTo-{env }` stage in the pipeline.


For example, In your pipeline manifest you at least need the below snippet ⬇️ 

```
stages:
  - name: test # Deploys all the workloads to test environment.
```

**Comment by federicobond** [comment]
I can confirm that I had the `stages.name` set and it did not create a `DeployTo-{env}` stage for whatever reason. It was only after I added the `deployments` key that the stage was included.

**Comment by KollaAdithya** [comment]
I could not reproduce the issue with version v1.33.

Can you please reverify for me by doing the following

1. Create a Pipeline with below command 

```
 copilot pipeline init \    
   --name frontend-main \  
   --url https://github.com/gitHubUserName/frontend.git \  
   --git-branch main \  
   --environments "test,prod" \
   --pipeline-type "Workloads"
 ```
 
 2. Run command `copilot pipeline deploy --diff` to see the diff of the pipeline.
 
 3. git add copilot/ && git commit -m "Adding pipeline artifacts" && git push
 
 4. copilot pipeline deploy
 
 After running these commands can you verify in the CloudFormation template, There should be couple of stages `DeployTo-test` and `DeployTo-prod` in the CodePipeline.
