### ISSUE TITLE
Deployment failure due incorrect load balancer ARN with no change to manifests/aws

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5652]
I haven't made any recent changes to either manifest or aws directly (besides adding a rule manually to the load balancer) and now I'm unable to deploy one of my services. The really weird thing is the other services using this same load balancer deploy just fine to this environment:
 
An ECS service to run and maintain your tasks in the environment cluster      
    Resource handler returned message: "Invalid request provided: UpdateSe                                     
    rvice error: The target group with targetGroupArn arn:aws:elasticloadb                                     
    alancing:us-east-1:***:targetgroup/****-Targe-****/                                     
    ***** does not have an associated load balancer. (Service:                                      
    AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Re                                     
    quest ID: e7071ea4-a5a4-4fdf-9a45-656983a69372; Proxy: null)" (Request                                     
    Token: 7bb09fe3-2102-1009-05f0-c9025339a9eb, HandlerErrorCode: Invalid                                     
    Request)

**Comment by ssyberg** [comment]
I think this has to do with maxing out the http, alias list and adding additional rules. I now can't remember if I accidentally deleted a rule pointing to a target group so there's a chance this was user error. I'll reopen if I can't solve this.

**Comment by ssyberg** [comment]
Reopening this, I must have accidentally deleted a rule, how can I get it back or get back in sync here? All deploys are still failing...

**Comment by ssyberg** [comment]
I was now able to get past deployment by deleting the additional http alias, but now I'm finding that the target groups are not registering with the updated internal ips of the ecs tasks, I've had to make this change manually on the last two deploys.

**Comment by ssyberg** [comment]
Can I just delete the load balancer somehow and have copilot recreate it?

**Comment by KollaAdithya** [comment]
Hello @ssyberg !

Just to have clarity, Can you paste in the manifest so that i can figure out and reproduce the behavior.

**Comment by ssyberg** [comment]
I don't think you'll be able to reproduce this with my manifest since the drift was caused by something unrelated to the manifest itself, I'm just trying to figure out how to "re-sync" copilot with the current state or "start over" on the load balancer/target groups.

**Comment by iamhopaul123** [comment]
Hello @ssyberg. Sorry to hear about this deployment failure. Hopefully we can get it back soon.

> I was now able to get past deployment by deleting the additional http alias, but now I'm finding that the target groups are not registering with the updated internal ips of the ecs tasks, I've had to make this change manually on the last two deploys.

I think the problem might be you manually deleted the target group so that there's a drift for that target group resource. That's probably why when the other resource that refers to the target group gets updated, CFN complains that it can't find the target group anymore.

To double check on this, can you do a drift detection on the CFN console for this service stack? And if you see there's indeed a drift for the target group resource, could you try to make any config update to the target group (for example, set https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-deregistration-delay to 300)? CFN should be able to pick up the change and recover the missing target group then.

**Comment by ssyberg** [comment]
> could you try to make any config update to the target group

Ah this is what I was looking for, I will give this a try!

**Comment by ssyberg** [comment]
Unfortunately adding a deregister delay didn't have any effect, it's still not updating the registered targets and they remain pointing to the previous, now non-existant IPs.

I feel like doing something as simple as accidentally deleting a rule shouldn't render my entire deploy useless, I'm really hoping there's a way to solve this!

**Comment by ssyberg** [comment]
I tried updating the "drifted" target group association by hand, will see if that solves it on the next deploy.

**Comment by iamhopaul123** [comment]
> Unfortunately adding a deregister delay didn't have any effect, it's still not updating the registered targets and they remain pointing to the previous, now non-existant IPs.

Yeah sounds like we need a way to replace the target group so that it can sync up again, rather than just updating the config in-place. 

> I feel like doing something as simple as accidentally deleting a rule shouldn't render my entire deploy useless, I'm really hoping there's a way to solve this!

100% with you I think it would be ideal to have a much better experience to let CFN know any manual changes, so that it can sync up again. Or an easier way of importing existing resources to sub. the current one managed by CFN.

**Comment by JuanSeZ** [comment]
I'm having the exact same issue. After changing a rule manually and rolling back the changes did not fix it. 
@ssyberg were you able to fix it?

**Comment by ssyberg** [comment]
> I'm having the exact same issue. After changing a rule manually and rolling back the changes did not fix it. [@ssyberg](https://github.com/ssyberg) were you able to fix it?

I can't remember exactly how I solved this unfortunately (I should have come back and posted my bad!) but I have found it useful to use the cloudformation console to identify drift and fix things by hand. 

> I tried updating the "drifted" target group association by hand, will see if that solves it on the next deploy.

**Comment by JuanSeZ** [comment]
I managed to make it work by doing it manually. I appreciate the help
