### ISSUE TITLE
Problem with Docker

### ISSUE THREAD

**Issue by Pascapone** [aws/copilot-cli#5656]
I followed the simple getting started guide. I have docker installed and the docker enginge is running. When i try to deploy the example app I get the following error:
X execute Load Balanced Web Service init: check if docker engine is running: unmarshal docker info message: invalid character 'i' in literal false (expecting 'l')

I'm running this on windows 10.

**Comment by iamhopaul123** [comment]
Hello @Pascapone. Sorry about the confusing error message you got when going through the guide. Did you run Copilot command using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install)?

**Comment by ghost** [comment]
Hello @iamhopaul123 !
I got a similar error when running `svc deploy` on windows(not in wsl).

> upload deploy resources for service MY_SERVICE: check if docker engine is running: unmarshal docker info message: invalid character 'i' in literal false (expecting 'l')

copilot version: get this error both in 1.32.1 and 1.33.1
os: windows 10
docker desktop version: 4.27.1
engine: WSL2 based engine

I try to find the reason and it seems like copilot got invalid JSON when running `docker info '{{json .}}'` according to the [code](https://github.com/aws/copilot-cli/blob/d3b36ac9bb3d2c189c829327d20b3b10b04519bf/internal/pkg/docker/dockerengine/dockerengine.go#L442) .
But I got valid JSON when running the same command. I'm so confused..

**Comment by Pascapone** [comment]
Hello @iamhopaul123. 
I'm not using wsl to run copilot.

I actually have the same setup as @psYifanChen.
copilot version: 1.33.1
os: windows 10
docker desktop version: 4.27.1
engine: WSL2 based engine

**Comment by iamhopaul123** [comment]
Hello @Pascapone and @psYifanChen. Thank you for bringing it up this issue. Just sent out the fix and in the meanwhile before the patch release is out, instead of using Docker Desktop, can you run `apt install docker` in WSL to get linux docker installed?

**Comment by ghost** [comment]
@iamhopaul123 
Sure. I'll try it today.

**Comment by alienself** [comment]
Same issue here on windows 11.
Just to be sure I updated docker to 4.27.2 (latest) but it did not change a thing :(

**Comment by iamhopaul123** [comment]
@alienself Can you try the workaround I mentioned above? That should be unblock you for now.

**Comment by KollaAdithya** [comment]
Hello @Pascapone  and @psYifanChen 

Hello!
Fix is now released in Copilot v1.33.2
https://github.com/aws/copilot-cli/releases/tag/v1.33.2 🎉🚀
