### ISSUE TITLE
Issue with deleting Cloudwatch groups

### ISSUE THREAD

**Issue by astrokathi** [aws/copilot-cli#5659]
When I execute the command
`copilot svc delete` 
All the resources gets deleted including the lambda functions generated for 
**EnvControllerFunction** and
**RulePriorityFunction**
but, it doesn't delete the cloud watch log groups created for the lambda functions and keep on growing when a new deployment is done etc.,

Please guide me to make this work.

**Comment by iamhopaul123** [comment]
Hello @astrokathi. Yes you are correct. These log groups won't be automatically deleted. For now I think it's also a common problem for the other services that generate logs. You would have to delete them either manually or batch delete them using a script.

**Comment by astrokathi** [comment]
@iamhopaul123 
Okay, this is a know issue, isn't it?
Thanks for the information.

**Comment by iamhopaul123** [comment]
> Okay, this is a know issue, isn't it?

I think while it does add extra burden potentially from users perspective, it can be also considered dangerous to delete logs since they might be helpful even if the service/lambda is not there anymore.
