### ISSUE TITLE
Syntax and Verification for Elastic IP to `nlb` Assignment

### ISSUE THREAD

**Issue by cworksbrian** [aws/copilot-cli#5661]
Hi, I've been working on using copilot to deploy a service on AWS Fargate connected to an Elastic IP. [AWS Documentation](https://repost.aws/knowledge-center/ecs-fargate-static-elastic-ip-address) suggests that this can be done by configuring an `nlb`, which [copilot supports](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#nlb).
```yaml
nlb:
    port: 443/tls
```

However, I ran into a snag here: copilot doesn't support Elastic IPs for `nlb` explicitly, nor can Elastic IPs be allocated to subnets within the load balancer after a deployment. After reading #4063 and the follow-up #4208, the current approach seems to be to use `copilot svc override` (particularly given the age of the original feature request). I am not experienced with AWS CloudFormation, so accomplishing this has proven difficult.

Per the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html), it is clear to me I need to create a `SubnetMapping` for the load balancer containing the `AllocationId` of the Elastic IP I want to assign. Following the documentation for [YAML overrides](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/), I produced this initial attempt:
 ```yaml
 - op: add
   path: /Resources/PublicNetworkLoadBalancer/Properties/SubnetMapping
   value:
       AllocationId: !GetAtt ${AppName}-${SvcName}-${EnvName}-ip.AllocationId
       SubnetId: !Ref '${AppName}-${SvcName}-${EnvName}-pub1'
 ```
 
There are a few points I could use assistance with, the most glaring of which is the `AllocationId`. I don't know how to specify the logical name of an Elastic IP created outside of copilot's scope; in the example I provided, `${AppName}-${SvcName}-${EnvName}-ip` would correspond to the `Name` of an existing Elastic IP. This is more of a CloudFormation question, but it is relevant if one wants to replicate the functionality proposed in #4063.

I'd also like to verify whether my impression of the override syntax looks correct in the example provided.
 
The last thing I'd like to verify is the possibility of specifying a `SubnetMapping` for the `nlb` to begin with. Referring back to [the CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html), `SubnetMappings` seem to be mutually exclusive with `Subnets`, and I'm not sure which of the two copilot uses under the hood.

Thank you for your work on AWS Copilot thus far. It has been a major boon for simplifying the process of deploying containerized services to AWS.

**Comment by iamhopaul123** [comment]
Hello @cworksbrian I think EIP is not related to NLB. If you just want to use EIP for your tasks instead of getting different ip address for each task, you can simply set [`placement`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-placement) in your service manifest to "private".

**Comment by cworksbrian** [comment]
Thank you for your response yesterday @iamhopaul123. I raised this issue because I was attempting to replicate the functionality of #4063, which, as I understand, would have allowed EIPs to be connected to the ENIs of subnets within the VPC associated with the copilot-initialized NLB. You're right that the EIP isn't directly related to an NLB; sorry for the confusion there!

I assume using the "private" setting is for creating the NAT gateways and corresponding EIPs. However, my service will need to accept inbound connections, and [AWS documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html) suggests that AWS-managed NAT gateways only support outbound connections. This is why I sought the NLB approach recommended by the [AWS Knowledge Center](https://repost.aws/knowledge-center/ecs-fargate-static-elastic-ip-address).

To be sure, I verified what would happen if I deployed the service after setting `network.vpc.placement` to "private". Two NAT gateways and corresponding EIPs are indeed created during the process, but all `curl` requests to both of those IPs hang.

Your suggestion does hone in on the fact that I don't necessarily need the overhead of an NLB to run the service; I'm just not aware of any other solution that would allow inbound connections to an EIP for Fargate tasks. If there is another solution, I'd be very interested to know.

Please don't hesitate to let me know if anything seems wrong about my understanding of the situation.

**Comment by iamhopaul123** [comment]
Gotcha. I think the reason why `curl` requests for those EIPs hang is because by default we set an instance level security group which only allows inbound traffic from the ALB. Maybe in your use case you can configure [`security_group`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-security-groups) and use your own security group, instead of the default security group we created which only allows ingress from the ALB or itself.

**Comment by cworksbrian** [comment]
As suggested, I have created a security group enabling inbound traffic from anywhere and attached it to the VPC via `security_group`. However, requests to both EIPs still hang. Requests to the URL created for the ALB still succeed, and no problems are being reported by the health checker; therefore, the problem isn't with the service itself.

**Comment by iamhopaul123** [comment]
Gotcha. It seems like EIP is only to guarantee the outbound traffic uses the limited set of IPs. If you only care about calling a static IP publicly, can you resolve the DNS for the NLB and use its IP address:

```yaml
http: false
nlb:
  port: 80/tcp
...
network:
  vpc:
    placement: private
```

and I got

```
Recommended follow-up action:
  - Your service is accessible at bugbas-Publi-IiwQ1W2GtrpR-8ac9b46e0873ef94.elb.us-west-2.amazonaws.com:80 over the internet.
```

I can access the IP for NLB publicly without updating the security group

```
curl -v 52.37.19.255:80           
*   Trying 52.37.19.255:80...
* Connected to 52.37.19.255 (52.37.19.255) port 80
> GET / HTTP/1.1
> Host: 52.37.19.255
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: text/html; charset=utf-8
< Content-Length: 11
< ETag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
< Date: Thu, 08 Feb 2024 19:38:35 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host 52.37.19.255 left intact
Hello World%      
```

If you don't need static IP for outbound traffic,

```yaml
network:
  vpc:
    placement: private
```

can be omitted too.

If you want to use existing EIP for inbound traffic rather than the default IP address for the NLB, you can use override to specify the EIP [allocation ID](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-subnetmapping.html#cfn-elasticloadbalancingv2-loadbalancer-subnetmapping-allocationid) for the NLB.

**Comment by cworksbrian** [comment]
Thank you for your patience and detailed responses thus far @iamhopaul123. I can confirm it is possible to access the service via the NLB's IP. Initially, my goal was to use an existing EIP with with the Fargate tasks, so it doesn't quite accomplish what I want.

The [NLB template](https://github.com/aws/copilot-cli/blob/d3b36ac9bb3d2c189c829327d20b3b10b04519bf/internal/pkg/template/templates/workloads/partials/cf/nlb.yml#L7) uses `Subnets` rather than `SubnetMapping`, so my initial approach was also suspect; I would have had to replace `Subnets` with `SubnetMapping` instead of adding to an existing `SubnetMapping`.

After some thought, I think this might be an XY problem. While it would be nice to know how to use the overrides to achieve what's described in #4063, the reason I need an existing EIP is its association with an existing non-AWS domain. I am exploring the [options](https://aws.github.io/copilot-cli/docs/developing/domain/) copilot provides for working with domains, and I'm considering migrating the domain to Route 53. If that works out, it's probably safe to close this issue.

**Comment by cworksbrian** [comment]
Casting aside the intellectual exercise of connecting an NLB to an EIP, the problem I wanted to resolve with this issue is no longer relevant. Outstanding problems with the migration to a Route 53 domain have been fixed, so it is likely safe to close this issue as well.
