### ISSUE TITLE
Unable to Delete App without `iam:DeleteRolePermissionsBoundary` Permission

### ISSUE THREAD

**Issue by jsato8094** [aws/copilot-cli#5672]
When attempting to delete an application using the AWS Copilot CLI, the process fails during the deletion of roles. According to the CloudFormation event logs, it appears that the deletion of the AdministrationRole fails due to insufficient permissions.

The specific error message is as follows:

> Resource handler returned message: "User: arn:aws:iam::${account}:user/${user} is not authorized to perform: iam:DeleteRolePermissionsBoundary on resource: role ${app-name}-adminrole with an explicit deny in a permissions boundary (Service: Iam, Status Code: 403, Request ID: xxxxxxx)" (RequestToken: xxxxxx, HandlerErrorCode: AccessDenied)

Interestingly, manual deletion of the AdministrationRole via the AWS Management Console is possible, suggesting that the operation might not be essential. However, in my organization, acquiring `iam:DeleteRolePermissionsBoundary` permission is not feasible. Therefore, it would be greatly beneficial if the deletion of applications via the CLI could be performed without requiring this specific permission.

Thank you for considering this request.

**Comment by KollaAdithya** [comment]
Hello @jsato8094 !

Did you initialize the app with `--permissions-boundary` flag because the error says `role ${app-name}-adminrole with an explicit deny in a permissions boundary `

Can you check in the AWS console whether the role/user profile that you have used to create Copilot app have permission to delete the admin role ${app-name}-adminrole

**Comment by jsato8094** [comment]
@KollaAdithya Thank you very much. I apologize for the delayed response. I've found that obtaining the necessary permissions in my company's environment is difficult. Unfortunately, I'll have to give up on using AWS Copilot. I'll close the issue.
