### ISSUE TITLE
How to limit number of public IP v4 for services created by AWS Copilot

### ISSUE THREAD

**Issue by thientran1707** [aws/copilot-cli#5680]
From Feb 2024, AWS will charge for public ip v4, I am exploring AWS Copilot to deploy the service under "Load Balanced Web Service".

I would like to limit the number of public IP v4 associated with the service, not sure how this can be done? I try to check in the documentation but can not find any information yet

**Comment by Kylir** [comment]
Hello!
Any news on that? Last month we paid 200$ for the public IP v4. 90% of our services are not exposed...
Where is the cost coming from? The load balancers?

Thank you

**Comment by iamhopaul123** [comment]
Hello if the services are not exposed can you try putting them into the private subnets to avoid unnecessary public ipv4 addr for each task? e.g.

```yaml
network:
  vpc:
    placement: private
```

**Comment by Kylir** [comment]
Thanks @iamhopaul123 ,

My understanding is that Copilot is creating a NAT that has some cost attached to it.
I guess I need to evaluate what is the best.

**Comment by iamhopaul123** [comment]
That's true. The default behavior is to create the NAT if any workload is placed in private subnets. However, if you don't need NAT at all (aka no public traffic for private subnets), you can override this behavior by always setting the env stack condition `CreateNATGateways` false using [yaml patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) for your env stack:

```yaml
- op: replace
  path: /Conditions/CreateNATGateways
  value: false
```
