### ISSUE TITLE
Is it possible to use different platform for sidecar container?

### ISSUE THREAD

**Issue by MonuAnu** [aws/copilot-cli#5681]
Hello,

I have a scenario like my application container requires a platform linux/x86_64 but my sidecar container requires a platform linux/arm64 or linux/amd64.

I have tried below configuration. But it still takes default linux/x86_64 for sidecar container and I end up with exec format error.
sidecars:
  typesense:
    image: 514235915148.dkr.ecr.eu-central-1.amazonaws.com/typesense:0.25.2
    platform: linux/arm64
    port: 8108

Is it possible to have different platforms? In the documentation I found that platform is top level field.

Thank you in advance.

**Comment by Lou1415926** [comment]
Hello @MonuAnu 👋🏼  It is not possible today to run the same ECS tasks with containers requiring different runtime platforms unfortunately :( All containers (your main container and the sidecars) are hosted on the same infra, hence their runtime platform configuration is shared.
