### ISSUE TITLE
Creation of demo app failed; copilot stopped functioning

### ISSUE THREAD

**Issue by haarts** [aws/copilot-cli#5682]
Dear all,

I've been trying to start a simple demo app. Something went wrong during `init`:

![image](https://github.com/aws/copilot-cli/assets/10660/2d974588-e975-42cd-a1a5-7eae5c7cab46)

Some kind of timeout. It happens.

But now I can't do anything anymore with the copilot cli. Each and everyone of the subcommands comes back with an error like this: 
![image](https://github.com/aws/copilot-cli/assets/10660/e46c8cec-3c6f-4559-9dcd-98feeffd538b)

I can't delete the failed app b/c it can't be found:

![image](https://github.com/aws/copilot-cli/assets/10660/d4601333-767f-428b-8f76-419fe0b3f445)

I've logged in on the web console and I can't find anything there either (should I be able to?).

I've logged out. I've removed the `.aws` directory entirely. I don't think I have state on my local machine.

What else can I try?

**Comment by Lou1415926** [comment]
It is possible that there isn't any lingering resource in your AWS account. If your goal is to delete "demo" completely, that means you don't need to do anything from this point. 

If there is anything at all, I think the only resource would be the "demo-infrastructure-roles" stack. To look for the stack - 1) go to CloudFormation console, 2) switch to the region that you ran `init` with (if you didn't set any AWS environment variables related to regions, e.g. AWS_REGION, AWS_DEFAULT_REGION, etc.), 3) see if there is a stack named "demo-infrastructure-roles" 4) If there isn't any, look for "Deleted" stacks and "Failed" stacks.

If you can't find any stack, or you found it in "Deleted" / "Failed", then you are good! 

To elaborate on the error message - Copilot reads the `copilot/.workspace` file and finds out that there should an application called "demo". It then tries to read from your account & region an SSM parameter named "copilot/applications/demo", and emits the error that you saw when it can't find one.
