### ISSUE TITLE
How to migrate old pipelines to a new version of Copilot?

### ISSUE THREAD

**Issue by Kylir** [aws/copilot-cli#5689]
Hello,

My company has an application running a dozen of Copilot services. I've been using Copilot for years and it's a life saver!
We are now approaching the 30k users and I wanted to enable auto-scaling.

The issue is that the pipelines are very old and using `copilot-linux-v1.11.0`.
So, when I add the auto scaling configuration in the Manifest, the deployment is failing at the `DynamicDesiredCountFunction` event. The error I receive is:

> Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: c2059d34-5e22-4c24-8841-cf65271cb21f)" (RequestToken: 8187e784-a9a3-6025-13bb-fbfe7cea0e98, HandlerErrorCode: InvalidRequest)

It seems obvious that I need to update my pipelines and use an up to date version of Copilot in the pipelines.
What is the best way to do that please?

Thank you!

**Comment by Lou1415926** [comment]
Hey @Kylir, thanks for the kind words - glad that Copilot has been able to help ❤️ !

You can update your `buildspec.yml` (in your `copilot/pipelines` folder), and simply change `copilot-linux-v1.11.0` to a new version. Then commit this change and push it to your remote repo. This will trigger the pipeline - when it goes to the `Build` stage, it will read the `buildspec.yml` file which tells CodeBuild to download the new version of Copilot, instead of v1.11.0.

Let me know how it goes!

**Comment by Kylir** [comment]
Thanks @Lou1415926 for the response.
My version of Copilot was so old that I don't have a `copilot/pipelines` folder! :sweat_smile: 

To migrate from my ancient pipeline to a new one I first used copilot to generate the new version of a `buildspec.yml`.
Then I tweaked slightly the buildspec config file to point to the pipeline manifest at the root of the copilot folder - because I have no `pipelines` folder!

Another small hurdle: We use a token stored as a secret at container build time. I added this at the top of my `buildspec.yml`:

```yml
version: 0.2
env:
    parameter-store:
        NPM_TOKEN: NPM_TOKEN
```

And in my `copilot/<project name>/manifest.yml` I used this:

```yml
image:
    build:
        dockerfile: Dockerfile
        args:
            NPM_TOKEN: ${NPM_TOKEN}
```

It all worked fine. The service was deployed successfully :partying_face: 

What I would like now is to have this `pipelines` folder so that I can have several pipelines in parallel.
Can I edit The CodeBuild config and move the buildspec.yml to another location?

**Comment by Lou1415926** [comment]
Glad it worked for you 🚢 !


> Then I tweaked slightly the buildspec config file to point to the pipeline manifest at the root of the copilot folder - because I have no pipelines folder!

Out of curiosity (and a little extra caution), I wonder what did you have to tweak in the buildspec.yml file?

Just a small clarification (and context on why I was maybe curious), you are not required to move your _legacy_ pipeline's buildspec and manifest around to make it work with a newer version of Copilot, i.e. you are free to keep this structure:
```
copilot/
    buildspec.yml
    pipeline.yml
```
Running `copilot pipeline deploy` with the new version will still work with this legacy pipeline, even without `copilot/pipelines/` folder.

> What I would like now is to have this pipelines folder so that I can have several pipelines in parallel.

You can run `copilot pipeline init` with the new version of Copilot, and it will generate pipeline manifest and buildspec with the new directory structure. Along with your legacy pipeline, your workspace will look something like this:
```
copilot/
    buildspec.yml # The legacy pipeline.
    pipeline.yml # The legacy pipeline.
    pipelines/
        new-pipeline-name/  # The new pipeline.
            manifest.yml
            buildspec.yml
```

You will be able to `ls`, `deploy`, and `show`, etc. both the legacy pipeline and the new pipelines.

> Can I edit The CodeBuild config and move the buildspec.yml to another location?

Is the [`build.buildspec`](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#build-buildspec) field what you are looking for?

**Comment by Kylir** [comment]
Hello! Thanks for the reply :)

To clarify on my previous post: To solve my earlier issue I did exactly what you suggested: I ran `copilot pipeline init` to generate an up-to-date version of the pipeline's buildspec config for my project.
I needed to tweak the path to the pipeline's manifest. In `buildspec.yml` there is this line:

```bash
pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipelines/<pipeline name>/manifest.yml ... )
```
And I changed it to point to my layout (`copilot/manifest.yml`)

Now, I'm working on a second improvement.
I already have 2 old pipelines per project and the way I am handling that at the moment is by having 2 git branches (`main` and `release`.)
Each branch has its own version of the `buildspec.yml` and I have a `.gitattributes` file to make sure merging is not overwriting the buildspec.
But this is tedious and I wanted to use Copilot's improved way of handling multiple pipelines with a folder for each one.

Any suggestion how I could do that easily?
I spotted that the path to `buildspec.yml` is editable in AWS CodeBuild.

**Comment by Lou1415926** [comment]
The best way is to create two new pipelines, and delete the legacy ones. Is this acceptable in your case? If so, simply run `copilot pipeline init`, specify `main` or `release` and deploy those pipeline; after that, you can delete the legacy pipelines and remove the `.gitattributes` file. There isn't really a good way to "migrate" the legacy pipelines while retaining the old ones :(

**Comment by Kylir** [comment]
Hi @Lou1415926 ,
Thank you. It's a bit painful but it's probably the cleanest way to do it.
I'll close the issue.
