### ISSUE TITLE
After updating manifest.yml to pipeline Build Stage Fails

### ISSUE THREAD

**Issue by GorreriFranco** [aws/copilot-cli#5693]
Hi, could you help me with an issue with my pipeline setup?

Recently I changed my pipeline's "branch" property to another branch. Then I  pushed the changes to my GitHub repository and ran "copilot pipeline deploy -a <my-app-name> -n <my-pipeline-name>". Now I'm getting this error on the build stage of my pipeline:

<img width="840" alt="image" src="https://github.com/aws/copilot-cli/assets/40183872/e84a6008-6338-4652-bae6-a5379ff94b04">

For context this is the install phase on my buildspec.yml. (I haven't changed anything)

  install:
    runtime-versions:
      docker: 19
      ruby: 2.6
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.24.0
      - mv ./copilot-linux-v1.24.0 ./copilot-linux
      - chmod +x ./copilot-linux

**Comment by Lou1415926** [comment]
Hi @GorreriFranco ! From [this CodeBuild doc](https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html) it doesn't seem like `docker` is an available runtime to be specified under `runtime-versions`; this also agrees with the error message that you've seen! If you don't have very specific requirement for docker 19, you can just leave that line out.

Here is my guess on why you are having this issue now but were fine before. From [this issue](https://github.com/aws/aws-codebuild-docker-images/issues/283), it seems like `docker` used to be a valid option under `runtime-versions` for older codebuild images. You were likely using one of these older images previously. After updating the branch and running `copilot pipeline deploy`, the CodeBuild image is automatically updated to use a newer official image which no longer accepts `docker` under `runtime-versions`.

**Comment by GorreriFranco** [comment]
Hi @Lou1415926 ! Yes that was what happended. I opted to create a new pipeline with the changes I needed and in fact the new `buildspec.yml` created by copilot does not include specified `runtime-versions` anymore.

Thank you!
