### ISSUE TITLE
copilot app upgrade: ECR Errors

### ISSUE THREAD

**Issue by anne-montoya** [aws/copilot-cli#5694]
We have 2 applications located into 2 separate regions (APP_1: ap-southeast-1, APP_2: us-west-2)
Both applications are on copilot v1.1.0 (based from StackSet-infrastructure instance template)

When trying to upgrade both, got an error:
```
Unable to retrieve Arn attribute for AWS::ECR::Repository, with error message null
```

The StackSet template for both are now on v1.33.0 but the StackSet instance are still on v1.1.0 and has Status: **`UPDATE_ROLLBACK_COMPLETE`**

When I tried to upgrade again, I got `Application is already on the latest version v1.33.0, skip upgrade.`
Can you guide on how to properly upgrade the apps?

Also, when doing copilot svc init, this error is seen on the StackSet-infra instance

> The following resource(s) failed to create: [ECRRepotestDASHservice, ECRReponifi, ECRRepotest, ECRRepotestDASHserviceDASH1, ECRRepocopilotDASHpipelineDASHfixDASHtrial, ECRRepoanneDASHtestDASHnifiDASHcopilot]. The following resource(s) failed to update: [ECRRepotestDASHredis, ECRRepoimage, ECRRepobusiness, ECRRepomongo, ECRRepoplace, ECRRepoeventDASHgateway, ECRRepoaccount, ECRRepoproduct, ECRRepomongoDASHhcDASHtest, ECRReposearchDASHproducts, ECRReposales, ECRRepoaccountDASHlb4, ECRRepochico, ECRRepomembership, ECRRepopayment, ECRRepoeventDASHbridgeup, ECRRepocontent, ECRRepoprovision, ECRReporedis, ECRRepooffer, ECRRepoperson, ECRRepomissionDASHcontrol, ECRRepodatax, ECRRepochico2, ECRRepocrmDASHtest, ECRReporeport, PipelineBuiltArtifactBucket, ECRRepomessaging, ECRRepomongoDASHtest, ECRReporeward].

**Comment by Lou1415926** [comment]
Sorry that you are having this issue :( ! A few questions if you don't mind:
1. Did both instances in ap-southeast-1 and in us-west-2 fail?
2. If so, are they failing for the same reason, on the same resource?
3. Note the name of the ECR repo to which you saw the "Unable to retrieve Arn attribute for AWS::ECR::Repository, with error message null" error message. Go to the ECR console (in that region) and look for that repo - is it there? If not, do you remember manually deleting that repo previously?


> The following resource(s) failed to create: [ECRRepotestDASHservice, ECRReponifi, ECRRepotest, ECRRepotestDASHserviceDASH1, ECRRepocopilotDASHpipelineDASHfixDASHtrial, ECRRepoanneDASHtestDASHnifiDASHcopilot]. The following resource(s) failed to update: [ECRRepotestDASHredis, ECRRepoimage, ECRRepobusiness, ECRRepomongo, ECRRepoplace, ECRRepoeventDASHgateway, ECRRepoaccount, ECRRepoproduct, ECRRepomongoDASHhcDASHtest, ECRReposearchDASHproducts, ECRReposales, ECRRepoaccountDASHlb4, ECRRepochico, ECRRepomembership, ECRRepopayment, ECRRepoeventDASHbridgeup, ECRRepocontent, ECRRepoprovision, ECRReporedis, ECRRepooffer, ECRRepoperson, ECRRepomissionDASHcontrol, ECRRepodatax, ECRRepochico2, ECRRepocrmDASHtest, ECRReporeport, PipelineBuiltArtifactBucket, ECRRepomessaging, ECRRepomongoDASHtest, ECRReporeward].
4. The error message ⬆️ Can you go to the CloudFormation console, to the "Event" tab, and look for the first failure triggered by that specific update? If you can share a screenshot then that's the easiest!
5. On the same error message - are all of these repo expected to exist?

**Comment by anne-montoya** [comment]
Hello, thanks for responding

1. Yes
2. Now that I look into the events the APP_B has error: `Unable to retrieve Arn attribute for AWS` and APP_A has the error: `The following resource(s) failed to create: [ECRRepotestDASHservice,...`

**Comment by anne-montoya** [comment]
Hello, thanks for responding :)

1. Yes
2. Now that I look into the events, the APP_B has error: `Unable to retrieve Arn attribute for AWS` and APP_A has the error: `The following resource(s) failed to create: [ECRRepotestDASHservice,...`
3. There is no particular ECR repo listed. But I can confirm that some of the services listed on the StackSet instance doesn't have ECR anymore because we deleted it through `copilot svc delete`. It is also possible that we manually delete ECR because we do cleanups.
4. I can confirm that the first failure is `Resource handler returned message: "The repository with name 'test' does not exist in the registry`
5. They don't exist anymore because of reasons in number 3.

So with this, can I just manually recreate all the missing ECRs and retry `copilot app upgrade`? How to retry when I got this `Application is already on the latest version v1.33.0, skip upgrade.`?

**Comment by Lou1415926** [comment]
Thanks! From the information gathered so far, I can see two places where things are out of sync:
1. The individual stackset instances (i.e. the stacks named `StackSet-<app>-infrastructure-<random>` in each of the regions) are out of sync with the respective ECR repositories. Some repos are gone, but the stacks are unaware and are still trying to fetch those non-existent repos.
2. The stackset is out-of-sync with the two instances. When stackset gets updated, it propagates the change to each of its instances. Even if an instance update fails, the stackset update will still succeed ([related](https://github.com/aws/copilot-cli/issues/4296#issuecomment-1363447206
)). In your case, the update was to bump the TemplateVersion from v1.1.0 to v1.33.0 (among other potential resource updates). Now the stackset thinks it is on v1.33.0, however the actual instances are not.

I'd suggest fixing the first out-of-sync issue before trying to fix the second one.

To fix the first issue, like you said, simply recreate those missing repos. Be sure to fix all the missing repos, and for both regions. This should be enough to fix it. 

The second isn't too complicated to fix either, fortunately. You can run `copilot svc delete` to delete any service that you no longer need - that is, if there is any. Alternatively, run `copilot svc init` to create a dummy service and delete it afterwards. Either of these options should be able to bring your stackset instances in sync with the stackset.

**Comment by anne-montoya** [comment]
It works! Thanks 😊
