### ISSUE TITLE
AWS Copilot Windows Container Deployment issues

### ISSUE THREAD

**Issue by chris-vaughan-285** [aws/copilot-cli#5696]
While trying to deploy my windows container using copilot I get the following error:
- An ECS service to run and maintain your tasks in the environment cluster [create failed][0.0s]Resource handler returned message: "Unsupported operating system in task definition. Please choose Linux"

I have the following in my manifest:
platform: windows/x86_64

cpu: 1024       # Number of CPU units for the task.
memory: 2048    # Amount of memory in MiB used by the task.
count: 1       # Number of tasks that should be running in your service.
exec: true     # Enable running commands in your container.
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
  
  Is there anything that would cause this issue or do you have any potential fixes for it?

**Comment by Lou1415926** [comment]
Hello @chris-vaughan-285 ! Service connect doesn't work with tasks that need to run on Windows. Try changing `network.network` to `false`!

The error message is confusing though - it also took me a while to figure out what was wrong. I will see if there is anything we can do in Copilot to clearly communicate that service connect isn't compatible with Windows.
