### ISSUE TITLE
Is it possible to update the Application name or switch the application name from same repo?

### ISSUE THREAD

**Issue by shain-digix** [aws/copilot-cli#5722]
I have already deployed my app to UAT environment using the application name **app-reload** and the current cluster name is **app-reload-uat-Cluster-RANDOM**. 

Now I want to deploy it to production. But due to some company policy, for production environment, I need to se the prefix **aws-engg** making the application name **aws-engg-app-reload**. Is there a way for me to update the application name? Or any other way I can switch the application name when I am deploying to corresponding environments?

**Comment by huanjani** [comment]
Hello, @shain-digix!
Unfortunately, there isn't a way to update your app name at this stage. 
I'm sorry!

**Comment by huanjani** [comment]
I'm closing this issue, but feel free to re-open it or start a new one if you have more questions!
