### ISSUE TITLE
AWS Lambda end of support for Node.js 16

### ISSUE THREAD

**Issue by afgallo** [aws/copilot-cli#5729]
Hi there,

AWS has started advising clients regarding end of support for node 16 as per below:

> Hello,
> 
> We are contacting you as we have identified that your AWS Account currently has one or more AWS Lambda functions using the Node.js 16 runtime.
> 
> We are ending support for Node.js 16 in Lambda on June 12, 2024. This follows Node.js 16 End-Of-Life (EOL) reached on September 11, 2023 [1].
> 
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in several stages. Starting on June 12, 2024, Lambda will no longer apply security patches and other updates to the Node.js 16 runtime used by Lambda functions, and functions using Node.js 16 will no longer be eligible for technical support. Also, Node.js 16 will no longer be available in the Console, although you can still create and update functions using Node.js 16 via AWS CloudFormation, the AWS CLI, AWS SAM, or other tools. Starting July 15, 2024, you will no longer be able to create new Lambda functions using the Node.js 16 runtime. Starting August 15, 2024, you will no longer be able to update existing functions using the Node.js 16 runtime.
> 
> We recommend that you upgrade your existing Node.js 16 functions to Node.js 20 before June 12, 2024. A list of your Node.js 16 functions can be found in the 'Affected resources' tab of the AWS Health Dashboard.
> 
> End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.
> 
> This notification is generated for functions using the Node.js 16 runtime for the $LATEST function version. The following command shows how to use the AWS CLI [3] to list all functions in a specific region using Node.js 16, including published function versions. To find all such functions in your account, repeat this command for each Region:
> 
> aws lambda list-functions --region us-west-2 --output text --query "Functions[?Runtime=='nodejs16.x'].FunctionArn"
> 
> From 180 days before deprecation, you can also use Trusted Advisor to identify all functions using the Node.js 16 runtime, including published function versions [4].
> 
> If you have any concerns or require further assistance, please contact AWS Support [5].

Upon reviewing our accounts, we have identified that these functions are Copilot managed. Are there any plans to upgrade these functions in upcoming release of Copilot? If not, can we expect advice so that this upgrade can be done safely?

Thanks a lot!

**Comment by KollaAdithya** [comment]
Hello @afgallo !

we are already upgraded lambda runtime from node js 16 to 20 in release [v1.33.0](https://github.com/aws/copilot-cli/releases/tag/v1.33.0) and here is similar [issue](https://github.com/aws/copilot-cli/issues/5422) that is already addressed.

Which version of Copilot are using? Can you please upgrade to V1.33.0 ?

**Comment by afgallo** [comment]
Hi @KollaAdithya thanks for the advice on upgrading versions, I just realised we are running on v`1.31.x`. Will upgrade asap.
