### ISSUE TITLE
Access the same bucket from two workloads

### ISSUE THREAD

**Issue by SyntelK** [aws/copilot-cli#5757]
I am creating s3 bucket in teamcity pipeline using copilot below command
copilot storage init -n abcbatchreceipt -t S3 -w ba1 -l workload
copilot storage init -n abcbatchreceipt -t S3 -w ba2 -l workload

this create 2 different buckets , i want to use my ba1 and ba2 (both are jobs) should use same bucket , as these 2 jobs are reading and writing to the same bucket .
i gave bucket name as  abcbatchreceipt , and it is creating by below names.

abc-app-preproduction-dgi-a-abcbatchreceiptbucket-divcpjs1dlbm
abc-app-preproduction-dgo-a-abcbatchreceiptbucket-8wxr7mrkfyct

how can i achieve the same as i tried removing -w , but it give some workload error . -w multiple time in single command is also not working

**Comment by Lou1415926** [comment]
Hi @SyntelK! Sorry, I am not sure I fully understand 😞 

Can you confirm whether you are looking to:
1. Create just one S3 bucket, instead of two.
2. Access that one bucket from two jobs.

Am I missing something from your requirements?

**Comment by samuelhwilliams** [comment]
I have the same question (at least from my understanding). In my case it's situation 2: a single bucket that already exists for one service/workload (a load balanced web service), that I now need to access from another new service/workload (a backend service that is reading from redis to process some jobs, so not quite a Copilot "Worker Service" but essentially the same thing).

Is there a way to share access to an existing workload's S3 bucket addon with another workload?
