### ISSUE TITLE
Deleted environment still shows up in "env ls"

### ISSUE THREAD

**Issue by sodhi1981** [aws/copilot-cli#5771]
### Description:
I deleted an environment but for some reason it failed.
Now when I try to delete it again I get the following error message
✘ find service cloudformation stacks: AccessDenied: User: arn:aws:iam::056619616473:user/txxxxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::056619616473:role/xxxxxxx-platform-test-EnvManagerRole
        status code: 403, request id: d0333ce6-e336-4ed7-895a-eeae2f565430

Because this environment is stuck in this undeleted state, I am unable to create new services in my application.

I tried to contact the cloudformation support but they told me to contact copilot team.

### Details:

Copilot version is : v1.33.2

**Comment by BlessND** [comment]
+1

**Comment by iamhopaul123** [comment]
Hello @sodhi1981. Did you try to recreate the role and then run `env delete` again?

**Comment by sodhi1981** [comment]
@BlessND @iamhopaul123  I am going to try creating the roles and get back to you as soon as possible.

**Comment by sodhi1981** [comment]
@iamhopaul123  @BlessND I created the roles and now I get the following error message

$copilot env delete
Environment: test
Sure? Yes
✔ Retained IAM roles for the "test" environment
- Delete environment stack imprexis-platform-test  [not started]  
✘ delete environment test stack: delete stack imprexis-platform-test: AccessDenied: User: arn:aws:sts::056619616473:assumed-role/imprexis-platform-test-EnvManagerRole/1712939613795923203 is not authorized to perform: iam:PassRole on resource: arn:aws:iam::056619616473:role/imprexis-platform-test-CFNExecutionRole because no identity-based policy allows the iam:PassRole action
	status code: 403, request id: 20d6b330-f2ab-480b-93be-af9e162431cd

**Comment by iamhopaul123** [comment]
hello @sodhi1981 did you create the env manager role based on https://github.com/aws/copilot-cli/issues/5615#issuecomment-1897924828? Note that you do need to sub. the env/app name based on your own case.

**Comment by sodhi1981** [comment]
@iamhopaul123 @BlessND 
I created the role and here's the policy

{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": [
				"logs:GetLogRecord",
				"logs:GetQueryResults",
				"logs:StartQuery",
				"logs:GetLogEvents",
				"logs:DescribeLogStreams",
				"logs:StopQuery",
				"logs:TestMetricFilter",
				"logs:FilterLogEvents",
				"logs:GetLogGroupFields",
				"logs:GetLogDelivery"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "CloudwatchLogs"
		},
		{
			"Action": [
				"cloudwatch:DescribeAlarms"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "Cloudwatch"
		},
		{
			"Action": [
				"ecs:ListAttributes",
				"ecs:ListTasks",
				"ecs:DescribeServices",
				"ecs:DescribeTaskSets",
				"ecs:ListContainerInstances",
				"ecs:DescribeContainerInstances",
				"ecs:DescribeTasks",
				"ecs:DescribeClusters",
				"ecs:UpdateService",
				"ecs:PutAttributes",
				"ecs:StartTelemetrySession",
				"ecs:StartTask",
				"ecs:StopTask",
				"ecs:ListServices",
				"ecs:ListTaskDefinitionFamilies",
				"ecs:DescribeTaskDefinition",
				"ecs:ListTaskDefinitions",
				"ecs:ListClusters",
				"ecs:RunTask"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "ECS"
		},
		{
			"Condition": {
				"StringEquals": {
					"aws:ResourceTag/copilot-environment": "test",
					"aws:ResourceTag/copilot-application": "imprexis-platform"
				}
			},
			"Action": [
				"ecs:ExecuteCommand"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "ExecuteCommand"
		},
		{
			"Action": [
				"states:StartExecution",
				"states:DescribeStateMachine"
			],
			"Resource": [
				"arn:aws:states:eu-west-1:056619616473:stateMachine:imprexis-platform-test-*"
			],
			"Effect": "Allow",
			"Sid": "StartStateMachine"
		},
		{
			"Action": [
				"cloudformation:CancelUpdateStack",
				"cloudformation:CreateChangeSet",
				"cloudformation:CreateStack",
				"cloudformation:DeleteChangeSet",
				"cloudformation:DeleteStack",
				"cloudformation:Describe*",
				"cloudformation:DetectStackDrift",
				"cloudformation:DetectStackResourceDrift",
				"cloudformation:ExecuteChangeSet",
				"cloudformation:GetTemplate",
				"cloudformation:GetTemplateSummary",
				"cloudformation:UpdateStack",
				"cloudformation:UpdateTerminationProtection"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "CloudFormation"
		},
		{
			"Condition": {
				"StringEquals": {
					"iam:ResourceTag/copilot-application": "imprexis-platform",
					"iam:ResourceTag/copilot-environment": "test"
				}
			},
			"Action": [
				"iam:GetRole",
				"iam:PassRole"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "GetAndPassCopilotRoles"
		},
		{
			"Action": [
				"ecr:BatchGetImage",
				"ecr:BatchCheckLayerAvailability",
				"ecr:CompleteLayerUpload",
				"ecr:DescribeImages",
				"ecr:DescribeRepositories",
				"ecr:GetDownloadUrlForLayer",
				"ecr:InitiateLayerUpload",
				"ecr:ListImages",
				"ecr:ListTagsForResource",
				"ecr:PutImage",
				"ecr:UploadLayerPart",
				"ecr:GetAuthorizationToken"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "ECR"
		},
		{
			"Action": [
				"resource-groups:GetGroup",
				"resource-groups:GetGroupQuery",
				"resource-groups:GetTags",
				"resource-groups:ListGroupResources",
				"resource-groups:ListGroups",
				"resource-groups:SearchResources"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "ResourceGroups"
		},
		{
			"Action": [
				"ssm:DeleteParameter",
				"ssm:DeleteParameters",
				"ssm:GetParameter",
				"ssm:GetParameters",
				"ssm:GetParametersByPath"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "SSM"
		},
		{
			"Action": [
				"ssm:PutParameter",
				"ssm:AddTagsToResource"
			],
			"Resource": [
				"arn:aws:ssm:eu-west-1:056619616473:parameter/copilot/imprexis-platform/test/secrets/*"
			],
			"Effect": "Allow",
			"Sid": "SSMSecret"
		},
		{
			"Action": [
				"elasticloadbalancing:DescribeLoadBalancerAttributes",
				"elasticloadbalancing:DescribeSSLPolicies",
				"elasticloadbalancing:DescribeLoadBalancers",
				"elasticloadbalancing:DescribeTargetGroupAttributes",
				"elasticloadbalancing:DescribeListeners",
				"elasticloadbalancing:DescribeTags",
				"elasticloadbalancing:DescribeTargetHealth",
				"elasticloadbalancing:DescribeTargetGroups",
				"elasticloadbalancing:DescribeRules"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "ELBv2"
		},
		{
			"Action": [
				"s3:ListBucketByTags",
				"s3:GetLifecycleConfiguration",
				"s3:GetBucketTagging",
				"s3:GetInventoryConfiguration",
				"s3:GetObjectVersionTagging",
				"s3:ListBucketVersions",
				"s3:GetBucketLogging",
				"s3:ListBucket",
				"s3:GetAccelerateConfiguration",
				"s3:GetBucketPolicy",
				"s3:GetObjectVersionTorrent",
				"s3:GetObjectAcl",
				"s3:GetEncryptionConfiguration",
				"s3:GetBucketRequestPayment",
				"s3:GetObjectVersionAcl",
				"s3:GetObjectTagging",
				"s3:GetMetricsConfiguration",
				"s3:HeadBucket",
				"s3:GetBucketPublicAccessBlock",
				"s3:GetBucketPolicyStatus",
				"s3:ListBucketMultipartUploads",
				"s3:GetBucketWebsite",
				"s3:ListJobs",
				"s3:GetBucketVersioning",
				"s3:GetBucketAcl",
				"s3:GetBucketNotification",
				"s3:GetReplicationConfiguration",
				"s3:ListMultipartUploadParts",
				"s3:GetObject",
				"s3:GetObjectTorrent",
				"s3:GetAccountPublicAccessBlock",
				"s3:ListAllMyBuckets",
				"s3:DescribeJob",
				"s3:GetBucketCORS",
				"s3:GetAnalyticsConfiguration",
				"s3:GetObjectVersionForReplication",
				"s3:GetBucketLocation",
				"s3:GetObjectVersion",
				"kms:Decrypt"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "BuiltArtifactAccess"
		},
		{
			"Action": [
				"s3:PutObject",
				"s3:PutObjectAcl"
			],
			"Resource": [
				"arn:aws:s3:::stackset-imprexis-platfo-pipelinebuiltartifactbuc-t2f8wk6kah4e",
				"arn:aws:s3:::stackset-imprexis-platfo-pipelinebuiltartifactbuc-t2f8wk6kah4e/*"
			],
			"Effect": "Allow",
			"Sid": "PutObjectsToArtifactBucket"
		},
		{
			"Action": [
				"kms:GenerateDataKey"
			],
			"Resource": "arn:aws:kms:eu-west-1:056619616473:key/77dd9eac-33c3-4e30-9f6e-ea8453e318d7",
			"Effect": "Allow",
			"Sid": "EncryptObjectsInArtifactBucket"
		},
		{
			"Action": [
				"ec2:DescribeSubnets",
				"ec2:DescribeSecurityGroups",
				"ec2:DescribeNetworkInterfaces",
				"ec2:DescribeRouteTables"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "EC2"
		},
		{
			"Action": [
				"apprunner:DescribeService",
				"apprunner:ListOperations",
				"apprunner:ListServices",
				"apprunner:PauseService",
				"apprunner:ResumeService",
				"apprunner:StartDeployment",
				"apprunner:DescribeObservabilityConfiguration",
				"apprunner:DescribeVpcIngressConnection"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "AppRunner"
		},
		{
			"Action": [
				"tag:GetResources"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "Tags"
		},
		{
			"Action": [
				"application-autoscaling:DescribeScalingPolicies"
			],
			"Resource": "*",
			"Effect": "Allow",
			"Sid": "ApplicationAutoscaling"
		},
		{
			"Action": [
				"iam:DeleteRole",
				"iam:ListRolePolicies",
				"iam:DeleteRolePolicy"
			],
			"Resource": [
				"arn:aws:iam::056619616473:role/imprexis-platform-test-CFNExecutionRole",
				"arn:aws:iam::056619616473:role/imprexis-platform-test-EnvManagerRole"
			],
			"Effect": "Allow",
			"Sid": "DeleteRoles"
		},
		{
			"Action": [
				"cloudformation:DescribeStacks",
				"cloudformation:DeleteStack"
			],
			"Resource": [
				"arn:aws:cloudformation:eu-west-1:056619616473:stack/imprexis-platform-test/*"
			],
			"Effect": "Allow",
			"Sid": "DeleteEnvStack"
		}
	]
}
I am wondering where the problem is.

**Comment by iamhopaul123** [comment]
That's strange. I wonder if it is because `arn:aws:iam::056619616473:role/imprexis-platform-test-CFNExecutionRole` was somehow created manually and it is not tagged with 
```json
					"iam:ResourceTag/copilot-application": "imprexis-platform",
					"iam:ResourceTag/copilot-environment": "test"
```
Would you mind to double check on that (as well as the new env manager role just in case)?

**Comment by sodhi1981** [comment]
They are both tagged.

Here's the latest error message when I try to delete the environment

delete environment test stack: delete stack imprexis-platform-test: AccessDenied: User: arn:aws:sts::056619616473:assumed-role/imprexis-platform-test-EnvManagerRole/1712945310735184107 is not authorized to perform: iam:PassRole on resource: arn:aws:iam::056619616473:role/imprexis-platform-test-CFNExecutionRole because no identity-based policy allows the iam:PassRole action
	status code: 403, request id: 40f5aa0e-7617-46b9-8975-a4f2519c0f53

**Comment by sodhi1981** [comment]
![Uploading Screenshot from 2024-04-12 23-39-45.png…]()

**Comment by sodhi1981** [comment]
![Screenshot from 2024-04-12 23-39-15](https://github.com/aws/copilot-cli/assets/31075654/0fcf7015-0126-441f-9ace-e69a79a0ec75)
![Screenshot from 2024-04-12 23-39-45](https://github.com/aws/copilot-cli/assets/31075654/01beea8c-5c6a-4b6b-88e5-7b51aa921894)

**Comment by iamhopaul123** [comment]
> They are both tagged.

Hello @sodhi1981 did you just update the tags or they were both tagged before you checked?

**Comment by sodhi1981** [comment]
@iamhopaul123 Both the roles did not have the tags before.

**Comment by iamhopaul123** [comment]
Very likely it's because the tags provisioning takes time and there could be some transient state when on console you see the tags are there but they are not populated to all regions etc. Would you mind to try an another `env delete` and see if you can delete the environment this time?

**Comment by sodhi1981** [comment]
I tried env delete again but it did not work

delete environment test stack: delete stack imprexis-platform-test: AccessDenied: User: arn:aws:sts::056619616473:assumed-role/imprexis-platform-test-EnvManagerRole/1713199512522720600 is not authorized to perform: iam:PassRole on resource: arn:aws:iam::056619616473:role/imprexis-platform-test-CFNExecutionRole because no identity-based policy allows the iam:PassRole action

**Comment by iamhopaul123** [comment]
I got the problem now. In your tag keys can you remove `iam:ResourceTag/` this prefix? Otherwise we are not tagging the roles correctly...

**Comment by sodhi1981** [comment]
I removed the prefix and the delete was successful. Thanks a lot for your help!
