### ISSUE TITLE
[Bug]: Order of operations issue with environment addons

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5772]
I just struggled for a few hours trying to figure out why I kept getting errors when trying to deploy a working set of addons to a new environment. It turns out there's an undocumented order of operations issue inherent in environment level addons. 

In my particular case, I was using the RDS Postgress addon template from this [comment](https://github.com/aws/copilot-cli/issues/1178#issuecomment-963408231), which I had already successfully deployed to my `staging` environment. I ran `init`on a new `production` environment and then attempted to deploy and hit errors about missing subnets and vpcs. I temporarily _deleted_ the addon manifests and again attempted to deploy the environment which was successful. I then added the addon manifests back and deployed the environment one more time, and again this was successful.

**Comment by iamhopaul123** [comment]
Sorry @ssyberg I don't get what bug you think we can solve on our side 🤔 Technically you can define anything in your addons template and https://github.com/aws/copilot-cli/issues/1178#issuecomment-963408231 this is just an example. Additionally you don't have to always do this in two steps if you don't refer to the vpc id like `Fn::ImportValue': !Sub '${App}-${Env}-VpcId'`. Instead you would need to define the VPC id as a parameter (for example https://github.com/aws/copilot-cli/issues/5014#issuecomment-1599370665)

**Comment by ssyberg** [comment]
Haha I am editing the manifest of remstone7 from that ticket, I guess he never implemented that suggestion. I will try it out and report back!

As far as suggestions, I guess this kind of thing could be avoided with better documentation and/or the ability to target/exclude addons (I know that ticket already exists)... It's frequently unclear to me what is copilot magic and what is standard CFN templating.

**Comment by ssyberg** [comment]
I'm not totally following the suggestion, how does the parameter know where to get the VPC value? App and Env I know copilot provides so it makes sense that those will be populated, but less clear to me how we would know "VPC" is defined here?

```
Parameters:
  VPCID: !Ref VPC
```

**Comment by iamhopaul123** [comment]
That's a good question! If you do `env package` you'll see it's part of the env template (where VPC is defined)

**Comment by ssyberg** [comment]
Got it! And for the private subents do I have to add a parameter entry for `PrivateSubnet1` and `PrivateSubnet2` individually or is there some shortcut for just getting all the private subnet ids as well?

**Comment by iamhopaul123** [comment]
Yes that's right!

**Comment by ssyberg** [comment]
Amazing, attempting deploy now will report back 👍🏼

**Comment by ssyberg** [comment]
Seems all to be working, closing this, thank you!
