### ISSUE TITLE
[Bug]: Error when changing environment addon parameter

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5775]
I recently edited my environment addon for RDS to use secretsmanager instead of ssm, I've run `copilot env package` to confirm `ssm-secure` is no longer anywhere in my manifests/templates, but I'm still getting this error:

```
% copilot env deploy
Name: production
✔ Proposing infrastructure changes for the <redacted>-production environment.
- Creating the infrastructure for the <redacted>-production environment.                    [update rollback failed]  [375.1s]
  The following resource(s) failed to update: [AddonsStack].                                                     
  The following resource(s) failed to update: [AddonsStack].                                                     
  - A CloudFormation nested stack for your additional AWS resources                    [update rollback failed]  [365.9s]
    Internal Failure                                                                                             
    The following resource(s) failed to update: [DBInstance].                                                    
    - DB cluster                                                                       [update failed]           [0.0s]
      Parameters: [ssm-secure:/copilot/<redacted>/production/secrets/RDS_PASSWORD                                     
      :1] cannot be found.  
```

**Comment by iamhopaul123** [comment]
Hey @ssyberg. If you run `env package`, it won't show you the env addon template you defined locally. From the error msg you provided above, it does seem like the error is within the addons stack - `ssm-secure` is used there. Would you mind to check your env addons template?

**Comment by ssyberg** [comment]
Oh yea I did a full search for that string in the entire repo, it doesn't exist as far as I can tell...

**Comment by iamhopaul123** [comment]
That's weird...if you can go to the CFN console, can you check the failed nested stack and you can view the CFN template that is used to deploy the addons nested stack?

**Comment by ssyberg** [comment]
Yea and I don't see any of my local addon changes reflected in the template.

**Comment by ssyberg** [comment]
It might be something on my addon stack, you can ignore this for now, I'd like to delete and try again but I'm stuck on delete now: https://github.com/aws/copilot-cli/issues/5776
