### ISSUE TITLE
[Bug]: Can't delete service DELETE_FAILED on EnvControllerAction because Response object is too long.

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5776]
I'm tried to delete one of my services with `copilot svc delete` and it keeps failing. When I check the CFN events I see this: DELETE_FAILED on EnvControllerAction because "Response object is too long"

I tried deleting a few other services and they are having the same issue.

**Comment by iamhopaul123** [comment]
Hello @ssyberg. When the env controller is triggered at `svc delete`, essentially we just update the env stack to delete the service info from there. Can you check the env stack and see why the env stack update failed?

**Comment by ssyberg** [comment]
Ahh that makes sense! And the env update is failing because of that ssm issue!
