### ISSUE TITLE
Stuck on it for 2 days. Path specified in manifest file is not working correctly

### ISSUE THREAD

**Issue by shain-digix** [aws/copilot-cli#5795]
I have a cluster with 3 services. Below are the configuration for service manifest file

1. Service 1 - api1
`environments:
  dev:
    http:
      path: '/'
      healthcheck: '/api/healthcheck'`

2. Service 2 - api2
`environments:
  dev:
    http:
      path: '/'
      healthcheck: '/healthcheck'`

3. Service 3 - api3 - Newly Added
`environments:
  dev:
    http:
      path: '/orders-api'
      healthcheck: '/api/healthcheck'`

This is how the HTTP listener for new api3 looks like:

<img width="947" alt="Screenshot at Apr 25 23-47-08" src="https://github.com/aws/copilot-cli/assets/60873542/35464389-83fd-429b-a176-f7760d53443c">

When I enter the url, ALB_URL/orders-api it is not going to the new service api3.

Any idea where did I go wrong?

**Comment by spencer-leopold** [comment]
I think the load balancer rules are exact matches, so you would need a rule forwarding `/orders-api` in addition to `/orders-api/*`.

Have you tried setting the `http.path` to `/orders-api/*` and then add `http.additional_rules.path: '/orders-api'`?  Not sure if including the wildcard is valid or not in the copilot manifest.

**Comment by spencer-leopold** [comment]
Looks like copilot should create a rule for `/orders-api` OR `/orders-api/*` just by having `http.path` set to `/orders-api`.
Are you importing a load balancer and your screenshot is a rule you added manually?

**Comment by shain-digix** [comment]
Thanks @spencer-leopold . Solved it

```
http:
      path: '/orders-api'
      healthcheck: '/orders-api/healthcheck'
      additional_rules:
        path: '/orders-api'
```

**Comment by shain-digix** [comment]
Solved

**Comment by nhathoang241199** [comment]
I have a same issue. My config:

http:
  path: "/share-video-frontend"
  healthcheck: "/share-video-frontend/healthcheck"
  additional_rules:
    path: "/share-video-frontend"
    
But after i deploy and access to "url/share-video-frontend". Throw error "503 Service Temporarily Unavailable". Can you know what I did wrong?

**Comment by iamhopaul123** [comment]
Hello @nhathoang241199 can you check if 
1. `/share-video-frontend` is handled in your application
2. when you go to the ALB console, do you see `/share-video-frontend` added correctly as a listener rule?
