### ISSUE TITLE
Something causes drift

### ISSUE THREAD

**Issue by webmonch** [aws/copilot-cli#5821]
I've been deploying a service with copilot for about 6 months now and everything was fine, until recently a drift started to occur in cloudformation stack . 
PlatformVersion is expected to be LATEST but for some reason it is 1.4.0

What could possibly cause it? 

<img width="1027" alt="Screenshot 2024-05-23 at 21 13 50" src="https://github.com/aws/copilot-cli/assets/1910471/5fd2b1a7-2f74-4300-ae93-9c79df7f419a">

**Comment by dannyrandall** [comment]
Hey @webmonch! Just to double check, what error are you seeing when you run `copilot svc deploy`?

Based on https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform-linux-fargate.html, `1.4.0` _is_ the latest version of Fargate for ECS, so I'm surprised to see this is causing an issue.

**Comment by fgd-mark** [comment]
@webmonch I've just encountered this now as well. I'm not certain if it's just a red herring but my deployments are failing.
