### ISSUE TITLE
[Bug]: copilot svc exec - fails (more than one ECS service with the name api found in environment)

### ISSUE THREAD

**Issue by cworkschris** [aws/copilot-cli#5830]
I think this is unrelated but also naming conflicts (https://github.com/aws/copilot-cli/issues/2753)

### Description:
copilot svc exec -c "python3 -m fastapi_shell" 
Found only one deployed service api in environment dev
✘ describe ECS service for api in environment dev: more than one ECS service with the name api found in environment dev

### Details:

I have an error doing copilot svc exec that a colleague does not have.
The obvious difference is that I have another app (in a separate directory structure) that also has a svc called api and environment called dev

### Observed result:
✘ describe ECS service for api in environment dev: more than one ECS service with the name api found in environment dev

### Expected result:
Is this some kind of namespace collision?

### Debugging:
I looked through the issues, looked at "copilot app show" info and googled to no avail.

➜ copilot app show
About

  Name                  md2
  Version               v1.33.4 (latest available: v1.1.0)
  URI                   tutorworks.net
  Permissions Boundary  N/A

Environments

  Name    AccountID     Region
  ----    ---------     ------
  dev     297000690820  us-west-1

Workloads

  Name    Type                       Environments
  ----    ----                       ------------
  api     Load Balanced Web Service  dev

Pipelines

  Name
  ----

**Comment by cworkschris** [comment]
I think it is a problem on my local machine - on 2 other machines I can do the svc exec.
Is there a way to do a clean or remove caches or...

**Comment by cworkschris** [comment]
The problem magically went away and I could connect the next day.

**Comment by iamhopaul123** [comment]
Hello @cworkschris. Closing the issue for now. Feel free to reopen with more details if it happens again!
