### ISSUE TITLE
Low/No traffic not scaling in, how to utilize `TreatMissingData`?

### ISSUE THREAD

**Issue by ssyberg** [aws/copilot-cli#5854]
I have a staging deployment that often gets very low traffic, is there any way to use a patch or something to leverage `TreatMissingData` such that the scale in alarm triggers when request/response times have dropped to nothing (which IMO should default to scaling back in...)

**Comment by Lou1415926** [comment]
Hi @ssyberg. I haven't tried this - but I suspect setting `TreatMissingData` to `notBreaching` might be a good place to start experimenting!
