### ISSUE TITLE
[Bug]: When creating a new DB Storage  after creating a App Runner service It can't be deployed  

### ISSUE THREAD

**Issue by Frans06** [aws/copilot-cli#5856]
### Description:
I created a new App with Copilot. I wanted to create an App runner service and then attach a DB to this service. I did this a couple of times before without any issues. I installed the latest Copilot version and after trying to follow the same procedure I got the following error at deploying db.

ValidationError: Template error: instance of Fn::GetAtt references undefined resource ServiceSecurityGroup

At the beginning I thought that I had made a mistake but after cleaning up the current app and creating a new one I still had the same problem. I didn't change the auto-generated manifest, and the docker image I was using was public.ecr.aws/docker/library/httpd:2.4

### Details:

Copilot version: 1.33.4
OS: Ubuntu 22.04.4
AWS region: us-east-2

### Observed result:

ValidationError: Template error: instance of Fn::GetAtt references undefined resource ServiceSecurityGroup

### Expected result:

I would expect not to get that error.
In case it is an expected behavior I think the CLI and documentation should be updated.

### Debugging:

WORKAROUND
After digging up the problem I did a workaround forcing a security group on the app runner manifest. Despite of App runner doesn't have a Security group configuration I bypassed the the error. 
```yml
network:
  vpc:
    placement: private
    security_groups:
      - "sg-0001668de5c18249f"
```

**Comment by Lou1415926** [comment]
ah, this is weird considering you have `network.vpc.placement: private`. Was this field added _after_ you added the `security_groups` field? If yes, can you try removing `security_groups` while keeping `placement`, then run `copilot svc package` and see if the output template contains `ServiceSecurityGroup`?

**Comment by andreashasse** [comment]
I've also run into this bug.

**Comment by Frans06** [comment]
> ah, this is weird considering you have `network.vpc.placement: private`. Was this field added _after_ you added the `security_groups` field? If yes, can you try removing `security_groups` while keeping `placement`, then run `copilot svc package` and see if the output template contains `ServiceSecurityGroup`?

Sorry, I remember I tried to do what you suggested without success. The security private was always there the only part i added was the security_groups to fix it looking for the security group it created at the beginning.

**Comment by nitzan-frock** [comment]
I am also seeing this issue.

The steps I've done to get into this state (after nuking everything and trying again) are:

using copilot version: v1.34.0

1. `copilot env init -n dev`
2. `copilot env deploy -n dev`
3. `copilot svc init -n server -e dev`
4. `copilot storage init -n server-cluster -t Aurora -w server --engine PostgreSQL --initial-db my_db -l environment.`
5. `copilot svc deploy -n server`
