### ISSUE TITLE
E2E tests

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#625]
We want to have e2e tests to validate that our CLI works.

TODO: write details.

**Comment by kohidave** [comment]
I want to create the following test cases:

* [x] Go through the init workflow
   * [x] Ensure a service is deployed
   * [x] Delete the project, env and app
* [x] Multi App Workflow 
    * [x] Add two apps
    * [x] Deploy both apps (ensure they're up)
    * [x] Run app show on both apps
    * [x] Delete everything
* [ ] Multi Env Workflow
    * [x] Add two environments (different accounts)
    * [x] Add an App
    * [x] Deploy app to both environments (ensure they're up)
    * [x] Run app show on both apps
    * [ ] Create a codepipeline, push a change, make sure the change is released
    * [x] Delete everything
* [x] Go through the project init workflow with a custom domain
    * [x] Add an environment
    * [x] Add an app
    * [x] Deploy the app, ensure the domain name uses the custom domain
    * [x] Delete everything:
* [ ] Operational Work 
  * [x] Wire up E2E in CodePipeline
  * [ ] Detect if a TTY is present, and if not, don't spin the spinners

**Comment by kohidave** [comment]
One other follow up task can be to add our e2e status as a badge in our GH repo :)

**Comment by efekarakus** [comment]
We have e2e tests for our CLI :D The only major flow that's not tested atm is for pipelines, which we'll track separately. Closing this issue.
