### ISSUE TITLE
More helpful error message when trying to re-init a project

### ISSUE THREAD

**Issue by SoManyHs** [aws/copilot-cli#631]
Tried to run `archer-init` on a project I apparently had already init'd in the past and got:
```
✘ Error! Failed to create the infrastructure to manage container repositories under project backend.
Error: execute project init: failed to create stack backend-infrastructure-roles: ResourceNotReady: failed waiting for successful resource state

```
Now that we have `project delete` (https://github.com/aws/amazon-ecs-cli-v2/pull/609) might be helpful to suggest deleting the project first or some other recommendation that is a bit more obvious, since roles are abstracted from the customer.

**Comment by toricls** [comment]
Just FYI but I'm seeing the follows by re-init at this point :)

```shell
$ copilot --version
copilot version: v0.1.0

$ copilot init
Note: It's best to run this command in the root of your Git repository.
Welcome to the Copilot CLI! We're going to walk you through some questions
to help you get set up with an application on ECS. An application is a collection of
containerized services that operate together.

Your workspace is registered to application demo.

  Which service type best represents your service's architecture?  [Use arrows to move, type to filter, ? for more help]
  > Load Balanced Web Service
    Backend Service
```

**Comment by efekarakus** [comment]
Hi @toricls :wave:!

Was that surprising for you or did you expect it to pick up the "demo" app?

**Comment by toricls** [comment]
@efekarakus sorry for my unclear comment, but I thought we can close this issue at the moment since it's good enough to me!

**Comment by efekarakus** [comment]
Oohh ahaha that makes sense to me, thank you!
