### ISSUE TITLE
Pipeline buildspec points to nonexistent version of ecs-preview when using non-release build

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#634]
The below information is out of date; this issue is a one of documentation and messaging regarding what files created by esc-preview should be committed to the repo. 
-------

I pulled the latest changes, built, then ran `pipeline init` and `pipeline update` in a repo I'm using for testing. 

The pipeline deployed successfully but the buildspec contains these lines: 
```sh
# Download the ecs-cli-v2 linux binary.
- wget https://ecs-cli-v2-release.s3.amazonaws.com/ecs-preview-linux-v0.0.4-75-g921d12b
- mv ./ecs-preview-linux-v0.0.4-75-g921d12b ./ecs-preview
- chmod +x ./ecs-preview
```
This binary doesn't exist, and the build stage fails. 

Changing the version to v0.0.4 solves this issue, but introduces the following error, where `ecs-preview env ls --json` prompts the "user" for input and fails, causing no packaging to occur and the infrastructure folder to not be created.

```sh
485 | [Container] 2020/01/29 17:28:42 Running command export COLOR="false"
486 |  
487 | [Container] 2020/01/29 17:28:42 Running command manifests=$(find ./ecs-project -name '*-app.yml')
488 |  
489 | [Container] 2020/01/29 17:28:43 Running command apps=$(find ./ecs-project -name '*-app.yml' \| sed -e 's!.*/!!' -e 's/-app.yml//')
490 |  
491 | [Container] 2020/01/29 17:28:43 Running command envs=$(./ecs-preview env ls --json \| jq '.environments[].name' \| sed 's/"//g')
492 | fatal: not a git repository (or any parent up to mount point /codebuild)
493 | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
494 | ·[0G·[2K? Which project's environments would you like to list?  [Use arrows to move, type to filter, ? for more help]
495 | > austins-cool-project
496 | ·[?25l·[?25hError: failed to get project name: EOF
497 |  
498 | [Container] 2020/01/29 17:28:43 Running command tag=$(sed 's/:/-/g' <<<"$CODEBUILD_BUILD_ID")
499 |  
500 | [Container] 2020/01/29 17:28:43 Running command for env in $envs; do
501 | for app in $apps; do
502 | ./ecs-preview app package -n $app -e $env --output-dir './infrastructure' --tag $tag;
503 | done;
504 | done;
505 |  
506 |  
507 | [Container] 2020/01/29 17:28:43 Running command ls -lah ./infrastructure
508 | ls: cannot access ./infrastructure: No such file or directory
```

That prior version can't seem to list envs properly and therefore isn't creating the infrastructure directory and failing silently. 

When I manually specify the envs, I get the following errors, where the software is not able to recognize that $CODEBUILD_SRC_DIR should in fact be a git repository.
```sh
[Container] 2020/01/31 00:50:38 Running command for env in $envs; do
507 | for app in $apps; do
508 | ./ecs-preview app package -n $app -e $env --output-dir './infrastructure' --tag $tag;
509 | done;
510 | done;
511 |  
512 | fatal: not a git repository (or any parent up to mount point /codebuild)
513 | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
514 | Error: could not find a project attached to this workspace, please run `project init` first
515 | fatal: not a git repository (or any parent up to mount point /codebuild)
516 | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
517 | Error: could not find a project attached to this workspace, please run `project init` first
```

Perhaps all these are related to versioning issues and will be updated in the next release.

**Comment by kohidave** [comment]
This is related to our dev builds. We don't have a good way, yet, of pulling dev builds into the codebuild step. The generated codebuild spec just shells out to --version to get the version to download.

This is more a known sharp edge around local testing.

**Comment by kohidave** [comment]
Also, yay! Glad you're pulling it down and playing with it!

**Comment by bvtujo** [comment]
It seems like this was caused by me not committing the `.ecs-workspace` file in the ecs-project directory, since it wasn't automatically picked up by git. Is there any way we could improve messaging on this? I wasn't sure what I needed to commit to my repo vs what could stay local and didn't get any guidance from the tool.

**Comment by sonofachamp** [comment]
Expanding on @kohidave 's point:

When you pull the latest code and make changes (specifically commits) the result returned by `git describe` changes. It returns the latest tag + the number of commits since that tag + the latest commit short hash. What this means is if you make changes, build a binary, and then generate a pipeline, **your pipeline will be referencing an ecs-cli-v2 binary that does not exist**.

The pipelines subcommand depends on the ecs-cli-v2 binary to run `app package` to get the CloudFormation to be deployed, but the pipeline will fail before this point due to not being able to pull the binary.

This circular dependency is a bit tricky to solve, because the build needs to be able to distinguish between a local build that needs to reference potentially new local changes versus a release build which needs to reference the about to be built thing.

**Comment by efekarakus** [comment]
This issue is stale and affects only devs working on pipeline changes instead of customers. I'll close the issue!
