### ISSUE TITLE
Refactor app delete

### ISSUE THREAD

**Issue by SoManyHs** [aws/copilot-cli#641]
The `delete_stacks` method in `app_delete.go` instantiates the CFN client rather than calling a method on a deployer interface, which makes it more difficult to test: https://github.com/aws/amazon-ecs-cli-v2/blob/master/internal/pkg/cli/app_delete.go#L180-L201

We should refactor to have the delete_stacks method use a deployer interface, similar to how we do other deletes (see: [env_delete.go](https://github.com/aws/amazon-ecs-cli-v2/blob/master/internal/pkg/cli/env_delete.go#L246-L255) )

**Comment by efekarakus** [comment]
Looks like we have now `svc_delete_test.go` which validates the `Execute` method! i'll resolve the issue.
