### ISSUE TITLE
Allow docker-compose file as input to project init

### ISSUE THREAD

**Issue by SoManyHs** [aws/copilot-cli#689]
We would like to allow a docker-compose.yml as input on `project init`. This will translate the services to an application.

More details TBD.

**Comment by shrasool** [comment]
ECS cli v1 supports this out of the box, so I found it surprising there is no mention of it even in the roadmap.

**Comment by shrasool** [comment]
nevermind, they left that implementation to docker
Link: https://aws.amazon.com/blogs/containers/aws-docker-collaborate-simplify-developer-experience/

**Comment by efekarakus** [comment]
> nevermind, they left that implementation to docker
> Link: https://aws.amazon.com/blogs/containers/aws-docker-collaborate-simplify-developer-experience/

Yup, I'll close this issue for the link above. We can re-open it if we have more concrete work in the future.
