### ISSUE TITLE
Interrupt app deploy if exposed port does not match manifest

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#711]
Making sure that the port mapping is correct is crucial to preventing nonfunctioning services from being deployed by ecs-preview. When a user runs `app deploy`, we should check if the Dockerfile exposes different ports than the app manifest, and if there is a discrepancy (ie the manifest port is not exposed by any expose statement in the Dockerfile), we should interrupt the deployment with a generic "Continue anyway?" message and prompt for y/N response. 

This behavior should be overridable with a `--yes` or `--ignore-warnings` flag, which we should surface by reminding the user of its existence after they select yes or no.

**Comment by efekarakus** [comment]
I believe `EXPOSE` instructions are optional so we shouldn't interrupt customers workflows if they don't have any. Closing the issue.
