### ISSUE TITLE
Better output on `ls` commands when no resources to show

### ISSUE THREAD

**Issue by SoManyHs** [aws/copilot-cli#734]
Currently on `env ls` and `app ls` with no envs or apps:

```
$ ecs-preview env ls

$ ecs-preview app ls
Name                Type
----                ----
```

It would be nice to hav a similar output to `app show` when there are no apps:

```
$ ecs-preview app show
No applications found in project backend
.
```

**Comment by WillHoule** [comment]
Put together a quick fix that gives the following output:

```bash
❯ ./bin/local/ecs-preview env ls

? Which project's environments would you like to list? test-project
No environments to list for project "test-project"
```

```bash
❯ ./bin/local/ecs-preview app ls

? Which project's applications would you like to list? test-project
Sorry! No configured apps found for the project "test-project"
```

Just checking the length of `envs` and `opts.applications` with an `if/else`. I think there may be some more room for deduping the writer logic here, but I'm not sure I want to over-complicate things :)

**Comment by efekarakus** [comment]
We made this consistent so that if there is no env in an application you get the following error:
```
couldn't find an application named hello in account 615288112214 and region us-west-2
```

Please feel free to re-open the issue if you'd a different UX :)
