### ISSUE TITLE
HTTP API + Cloud Map support

### ISSUE THREAD

**Issue by aidansteele** [aws/copilot-cli#741]
Now that HTTP APIs have [gone GA and added support for Cloud Map](https://aws.amazon.com/blogs/compute/building-better-apis-http-apis-now-generally-available/), would it be worth considering adding support for that to the generated architecture?

I'm sure there are pros and cons to HTTP API + Cloud Map vs public ALB, but in a personal hobbyist developer context, I'm very excited about the new functionality as it will save me a substantial amount of money. Right now ALBs cost a fair bit more than the Fargate tasks themselves, even moreso for Fargate Spot.

I'd be especially keen to hear why this **isn't** a good idea. I guess one consideration would be that even if there are no problems with HTTP API + Cloud Map per se, what does that mean for the ECS CLI? Should it a) switch to that approach or b) support ALBs and HTTP APIs, just adding more complexity?

**Comment by kohidave** [comment]
We were just talking about this last night! We'll dig into this and see what the pros and cons are.

**Comment by aidansteele** [comment]
Great! Meanwhile I will experiment with using it myself (to be honest I’ve not yet used ECS service discovery or Cloud Map at all) and see if I hit any stumbling blocks. 

The blog post indicates that SAM support is coming by the 20th, which I guess means that CloudFormation support will be there in time for us if the ECS CLI decides to go for it.

**Comment by kohidave** [comment]
What's kind of neat is we just released a Service Discovery change so each service spins up a cloudmap. HTTP APIs have support for cloudmaps as targets :D I was just playing around and got HTTP API calling one of my ecs-cli v2 services easy. I'll keep digging, but this looks cool!
