### ISSUE TITLE
Support for 3 AZ infrastructure

### ISSUE THREAD

**Issue by tachyonics** [aws/copilot-cli#780]
To support use cases where there is a requirement for splitting services across 3 AZs, provide an option to create infrastructure with 3 AZs rather than 2.

**Comment by flemzord** [comment]
Do you have any news about the possibility of adding this feature? Or a hint to make a PR?  cc @efekarakus

**Comment by iamhopaul123** [comment]
Hello @flemzord. Currently it's not planned for the short term within the month. But we'd love to get a PR to add the feature! Would you mind to give a thumb-up for this issue https://github.com/aws/copilot-cli/issues/2260 so that we can better prioritize our feature requests? Thank you!

**Comment by huanjani** [comment]
This is now released 🎉 in v1.14.0 https://github.com/aws/copilot-cli/releases/tag/v1.14.0 !
