### ISSUE TITLE
Support for CodeCommit pipeline triggers

### ISSUE THREAD

**Issue by tachyonics** [aws/copilot-cli#781]
Support use cases where pipelines should be triggered by changes in a CodeCommit repository rather than a Github repository.

**Comment by lakshan-n-able** [comment]
Yes that is a major requirement. Please help with this.

**Comment by jarrodu** [comment]
@efekarakus thanks for the reply on Twitter. It would be great to get this into copilot. One of the  big benefits for me is better integration with other AWS services. For instance IAM.

**Comment by efekarakus** [comment]
This was released just now in v1.1.0: https://github.com/aws/copilot-cli/releases/tag/v1.1.0!
