### ISSUE TITLE
Support for end-to-end integration tests in pipelines

### ISSUE THREAD

**Issue by tachyonics** [aws/copilot-cli#783]
For use cases where a set of services need to have end-to-end integration tests. ie. integration tests for a gamma/pre-prod stage. This would require something like the ability to block deployment to a stage to allow coordinated testing in that stage across pipelines (providing the hooks to enable this capability in a pipeline, the actual pipeline coordination mechanism can be user-provided)

**Comment by kohidave** [comment]
This has been released as `test_commands` feature :) 

aws-application-working-group@amazon.com
