### ISSUE TITLE
Don't delete local files generated with the CLI

### ISSUE THREAD

**Issue by SoManyHs** [aws/copilot-cli#800]
Currently, `pipeline delete` removes the `ecs-project/pipeline.yml` file from your workspace directory. We should probably not do that and simply ask to override the file instead.

Similarly, we currently don't delete the `ecs-project/buildspec.yml` file that is generated from `pipeline init`, but this results in the following error if you delete the pipeline and then try to run `pipeline init` again:

```
Error: write buildspec to workspace: file ~/ecs-project/buildspec.yml already exists
```

**Comment by efekarakus** [comment]
Resolved with #1034
