### ISSUE TITLE
Check to see if an application exists globally before creating it

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#815]
# Problem 

Right now application configuration is setup in a particular region - whichever region the default profile is configured with. 

Application names, however, have to be unique within the account, across regions - mostly to reduce the confusion of working on two projects named the same thing, in different regions.

In order to enforce this restriction right now - we create the application admin role as the name of the application. 

https://github.com/aws/copilot-cli/blob/ebd3abd80defc3b170f46b6a4b60306fac4c2b3d/templates/app/versions/v1.0.1/app.yml#L31-L34

So for example, if you run `copilot app init my-proj` in `us-east-1`, then run `copilot app init my-proj` in `us-west-2` - the second init should fail.

That currently happens - but the error you get is pretty gross:

```
Error: execute app init init: describe change set copilot-d2d6af69-9a90-4269-bbaa-204f6e7638b9 for stack codenames-infrastructure-roles: ChangeSetNotFound: ChangeSet [ecscli-d2d6af69-9a90-4269-bbaa-204f6e7638b9] does not exist
	status code: 404, request id: ca14ed0a-aa2d-4d7b-bc54-1a20626d8b06
```

This happens because CloudFormation can't create two roles with the same name since roles are global.

# Fix

To fix this, we should check to see if the admin role exists already (which is of the form `{app-name}-adminrole`). 

In the project deploy code:

https://github.com/aws/copilot-cli/blob/29349c6467e49d6e8c7ca0bc0fa0482910728805/internal/pkg/deploy/cloudformation/app.go#L26-L38

We can add a check which calls fetches `StackSetAdminRoleARN()` from the stack object, calls IAM (via [GetRole](https://docs.aws.amazon.com/sdk-for-go/api/service/iam/#IAM.GetRole)) to see if it exists, and if it does returns an error.

**Comment by kohidave** [comment]
What we should do:

1. Check to see if the app name exists in SSM
2. If it doesn't, check to see if the role exists
3. If the role exists, but the param doesn't exist we should show an error: `This app name is already being used in another region`

**Comment by rubiagatra** [comment]
Hey @kohidave, maybe I can help with this, I think it is pretty clear the description for the issue.

Can I get started with this with your guidance?

**Comment by Lou1415926** [comment]
This enhancement has been waiting for a while but it's finally here in [v1.24.0](https://github.com/aws/copilot-cli/releases/tag/v1.24.0) 🚀

**Comment by andreas-bergstrom** [comment]
Just a FYI, in the most recent version of Copilot I got "application named "foo" already exists in another region" when the foo-infrastructure-roles template existed in the same region. Not a big deal but a bit confusing for a newcomer

**Comment by KollaAdithya** [comment]
Hey @andreas-bergstrom !
Thanks for reporting this! We can fix this by logging the specific `region` in which region the application already exists.

**Comment by henriquesantanati** [comment]
Hey @KollaAdithya , yeah, it will be really helpful if copilot can show which is exactly the region that is conflicting.
