### ISSUE TITLE
Dummy issue to capture images

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#82]
![prompt](https://user-images.githubusercontent.com/879348/65549185-e4394380-ded1-11e9-9fce-f1b19cd4f27f.png)
![gradient](https://user-images.githubusercontent.com/879348/65549210-ef8c6f00-ded1-11e9-865d-b30ef7b94223.png)
![colors](https://user-images.githubusercontent.com/879348/65549416-5578f680-ded2-11e9-8d0f-21e0737f43ef.png)
![task-progress](https://user-images.githubusercontent.com/879348/65549555-9ffa7300-ded2-11e9-955f-fa842263fb99.gif)
![sequential-task-progress](https://user-images.githubusercontent.com/879348/65549577-abe63500-ded2-11e9-988b-00be9e770c85.gif)

**Comment by efekarakus** [comment]
<img width="747" alt="update-colors-dim" src="https://user-images.githubusercontent.com/879348/68536239-80919b00-0304-11ea-9393-d6f0ff1f6d68.png">

**Comment by efekarakus** [comment]
![Environment Diagram](https://user-images.githubusercontent.com/879348/69382067-19aca400-0c6b-11ea-9b9a-78620187cc66.png)

**Comment by efekarakus** [comment]
![Loadbalanced Webapp](https://user-images.githubusercontent.com/879348/69385723-20d8af80-0c75-11ea-9521-ddd361a0cf64.png)

**Comment by efekarakus** [comment]
![Screen Shot 2020-02-05 at 3 52 51 PM](https://user-images.githubusercontent.com/879348/74207181-59b07100-4c33-11ea-9897-246776b4f740.png)

**Comment by efekarakus** [comment]
![Screen Shot 2020-05-04 at 2 59 11 PM](https://user-images.githubusercontent.com/879348/81017755-03109880-8e18-11ea-8379-93788adbeca0.png)

**Comment by efekarakus** [comment]
![copilot-help](https://user-images.githubusercontent.com/879348/85748055-a4032d80-b6bc-11ea-9562-b7adf38d5c26.png)

**Comment by kohidave** [comment]
<img width="762" alt="Screen Shot 2020-06-25 at 2 33 09 PM" src="https://user-images.githubusercontent.com/828419/85797638-e181ae00-b6f0-11ea-8751-3a7552e3fa7f.png">

**Comment by efekarakus** [comment]
Application concepts
![app-concept](https://user-images.githubusercontent.com/879348/85869625-cd858d00-b780-11ea-817c-638814049d2d.png)
![app-infra](https://user-images.githubusercontent.com/879348/85869637-d0807d80-b780-11ea-8359-6d75933c562a.png)

**Comment by efekarakus** [comment]
Environment concepts
![env-concept](https://user-images.githubusercontent.com/879348/85873795-7da9c480-b786-11ea-9990-9604a3cc5f01.png)
![env-infrastructure](https://user-images.githubusercontent.com/879348/85873802-800c1e80-b786-11ea-8b2c-779b01abbaf4.png)

**Comment by efekarakus** [comment]
Getting started
<img width="826" alt="gettingstarted" src="https://user-images.githubusercontent.com/879348/86040246-8d304400-b9f8-11ea-9590-2878c3a1d3de.png">

<img width="826" alt="init" src="https://user-images.githubusercontent.com/879348/86040314-ab963f80-b9f8-11ea-8de6-c8caea8f6abf.png">

<img width="834" alt="deploy" src="https://user-images.githubusercontent.com/879348/86040356-be107900-b9f8-11ea-82cd-3bf2a5eb5c9d.png">

<img width="738" alt="delete" src="https://user-images.githubusercontent.com/879348/86040380-c9fc3b00-b9f8-11ea-87c2-6d42518d39dd.png">

**Comment by efekarakus** [comment]
Service Types

![lb-web-service-infra](https://user-images.githubusercontent.com/879348/86045951-39762880-ba01-11ea-9a47-fc9278600154.png)

**Comment by efekarakus** [comment]
![copilot-cli-v0-3-0](https://user-images.githubusercontent.com/879348/90834852-087aeb80-e300-11ea-8340-7f64326036fc.png)

**Comment by efekarakus** [comment]
![copilot-light-48](https://user-images.githubusercontent.com/879348/113342379-46eb7680-92e3-11eb-9e4b-f93c87b69f8f.png)
