### ISSUE TITLE
Dockerfile port extraction can be smarter

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#827]
Currently, dockerfiles which use an ARG statement to define the value for an EXPOSE statement are registered as errors, despite the port actually being defined in the dockerfile:
```Dockerfile
FROM golang:1.13
ARG PORT=5000
EXPOSE $PORT
ENTRYPOINT ["go", "run", "main.go"]
```

This can be done more intelligently by creating a map of all ARG statements in the dockerfile at parse time:
```
{
    "PORT": "5000"
}
```

Then, when parseExpose encounters an argument that's not parseable by its \<PORT\>[/\<PROTOCOL\>] syntax, it can go looking through the ARG map for the token "PORT", then try parsing *that* with the expose regex.

**Comment by efekarakus** [comment]
Closing in favor of https://github.com/aws/copilot-cli/issues/469 as the two issues are related.
