### ISSUE TITLE
Support deploying backend apps

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#868]
### Ask
We want to enable `app deploy` to deploy a backend application from a backend manifest.

### How?
The works should be very similar to https://github.com/aws/amazon-ecs-cli-v2/pull/863!
Once the stack is deployed it'd be neat to display a message like:
```
log.Successf("Deployed %s, you can make requests from other applications by querying %s\n", color.HighlightUserInput(o.AppName), color.HighlightResource(backendURI.String()))
```
Where `backendURI.String() = http://{appName}.{projectName}.local`

**Comment by kohidave** [comment]
This is very much done! Good job EFE!
